Sample split for ML

# Libraries

In [1]:
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split

In [2]:
# fixed random seed
RANDOM_STATE = 42

# EDA

In [3]:
path_data = Path('../data')

In [4]:
df_main = pd.read_excel(path_data / 'df_main.xlsx')
df_modelling_dimensionless = pd.read_excel(path_data / 'df_modelling_dimensionless.xlsx')
df_modelling_full = pd.read_excel(path_data / 'df_modelling_full.xlsx')
df_modelling_no_multicollinearity = pd.read_excel(
    path_data / 'df_modelling_no_multicollinearity.xlsx')

In [6]:
common_columns = list(set(df_modelling_dimensionless.columns) & set(df_modelling_full.columns) &\
                set(df_modelling_no_multicollinearity.columns))
print(f'Common columns for dataframes:\n{common_columns}')

Common columns for dataframes:
['inclination', 'particle_droplet_diameter_ratio', 'splashing', 'Re', 'particle_liquid_density_ratio', 'We', 'net_impact', 'wettability', 'volume_fraction_binary', 'roughness_binary', 'We_Re']

In [7]:
df_modelling_dimensionless.shape,  df_modelling_full.shape, df_modelling_no_multicollinearity.shape

((372, 11), (372, 19), (372, 15))

In [8]:
(df_modelling_dimensionless[common_columns] == df_modelling_full[common_columns]).sum()

inclination                        372
particle_droplet_diameter_ratio    372
splashing                          372
Re                                 372
particle_liquid_density_ratio      372
We                                 372
net_impact                         372
wettability                        372
volume_fraction_binary             372
roughness_binary                   372
We_Re                              372
dtype: int64

In [9]:
(df_modelling_no_multicollinearity[common_columns] == df_modelling_full[common_columns]).sum()

inclination                        372
particle_droplet_diameter_ratio    372
splashing                          372
Re                                 372
particle_liquid_density_ratio      372
We                                 372
net_impact                         372
wettability                        372
volume_fraction_binary             372
roughness_binary                   372
We_Re                              372
dtype: int64

Number of experiment (test) matches number of row in every modelling dataframe

# Train/test split

## Splashing

In [25]:
train_splashing, test_splashing = train_test_split(df_modelling_full, 
                                               test_size=0.2, random_state=RANDOM_STATE,
                                               stratify=df_modelling_full['splashing'])

In [26]:
train_splashing['splashing'].value_counts()

1    192
0    105
Name: splashing, dtype: int64

In [27]:
test_splashing['splashing'].value_counts()

1    48
0    27
Name: splashing, dtype: int64

In [28]:
train_indexes = train_splashing.index 
test_indexes = test_splashing.index
df_split = pd.DataFrame({
    'index': list(train_indexes)+list(test_indexes),
    'sample': (['train'] * len(train_indexes)) + (['test'] * len(test_indexes))
})
df_split.sample(5, random_state=RANDOM_STATE).T

         327    33     15    314    57
index     28    293    198   113     18
sample  test  train  train  test  train

In [29]:
df_split.to_excel(path_data / 'df_ml_split_splashing.xlsx')

## Net impact

In [30]:
train_net_impact, test_net_impact = train_test_split(df_modelling_full, 
                                               test_size=0.2, random_state=RANDOM_STATE,
                                               stratify=df_modelling_full['net_impact'])

In [31]:
train_net_impact['net_impact'].value_counts()

0    218
1     79
Name: net_impact, dtype: int64

In [32]:
test_net_impact['net_impact'].value_counts()

0    55
1    20
Name: net_impact, dtype: int64

In [33]:
train_indexes = train_net_impact.index 
test_indexes = test_net_impact.index
df_split = pd.DataFrame({
    'index': list(train_indexes)+list(test_indexes),
    'sample': (['train'] * len(train_indexes)) + (['test'] * len(test_indexes))
})
df_split.sample(5, random_state=RANDOM_STATE).T

         327    33     15    314    57
index    371     85    270   322     79
sample  test  train  train  test  train

In [34]:
df_split.to_excel(path_data / 'df_ml_split_net_impact.xlsx')