In [5]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

# Check the equality of excel-files

In [6]:
# Import data
df_main = pd.read_excel('../data/df_main.xlsx', index_col=0).reset_index(drop=True)
## Drop unused columns
# drop_columns = ['voltage', 'long_impulse_duration', 'long_impulse_dur_binary']
# df_main = df_main.drop(drop_columns, axis=1)
display(df_main.head())
df_main.info()

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
0,3,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
1,4,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
2,5,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
3,7,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small
4,8,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   test                             372 non-null    int64
 1   one_drop                         372 non-null    int64
 2   splashing                        372 non-null    int64
 3   breaking_up                      372 non-null    int64
 4   net_impact                       372 non-null    int64
 5   rebound                          372 non-null    int64
 6   voltage                          372 non-null    float64
 7   long_impulse_duration            372 non-null    int64
 8   height                           372 non-null    float64
 9   inclination                      372 non-null    int64
 10  droplet_diameter                 372 non-null    float64
 11  liquid_density                   372 non-null    int64
 12  surface_tension                  372 non-null    float64
 13  viscosity                        372 non-null    float64
 14  particle_mean_diameter           372 non-null    float64
 15  particle_liquid_density_ratio    372 non-null    float64
 16  volume_fraction                  372 non-null    float64
 17  wettability                      372 non-null    object
 18  roughness                        372 non-null    float64
 19  long_impulse_dur_binary          372 non-null    object
 20  roughness_binary                 372 non-null    int64
 21  volume_fraction_binary           372 non-null    int64
 22  velocity                         372 non-null    float64
 23  Re                               372 non-null    float64
 24  We                               372 non-null    float64
 25  We_Re                            372 non-null    float64
 26  particle_droplet_diameter_ratio  372 non-null    float64
 27  particle_diameter_cat            372 non-null    object
dtypes: float64(14), int64(11), object(3)
memory usage: 81.5+ KB

In [7]:
# Import data
df_merged = pd.read_excel('../data/df_merged_edited.xlsx', index_col=0).reset_index(drop=True)

display(df_merged.head())
df_merged.info()

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
0,3,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
1,4,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
2,5,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
3,7,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small
4,8,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   test                             372 non-null    int64
 1   one_drop                         372 non-null    int64
 2   splashing                        372 non-null    int64
 3   breaking_up                      372 non-null    int64
 4   net_impact                       372 non-null    int64
 5   rebound                          372 non-null    int64
 6   voltage                          372 non-null    float64
 7   long_impulse_duration            372 non-null    int64
 8   height                           372 non-null    float64
 9   inclination                      372 non-null    int64
 10  droplet_diameter                 372 non-null    float64
 11  liquid_density                   372 non-null    int64
 12  surface_tension                  372 non-null    float64
 13  viscosity                        372 non-null    float64
 14  particle_mean_diameter           372 non-null    float64
 15  particle_liquid_density_ratio    372 non-null    float64
 16  volume_fraction                  372 non-null    float64
 17  wettability                      372 non-null    object
 18  roughness                        372 non-null    float64
 19  long_impulse_dur_binary          372 non-null    object
 20  roughness_binary                 372 non-null    int64
 21  volume_fraction_binary           372 non-null    int64
 22  velocity                         372 non-null    float64
 23  Re                               372 non-null    float64
 24  We                               372 non-null    float64
 25  We_Re                            372 non-null    float64
 26  particle_droplet_diameter_ratio  372 non-null    float64
 27  particle_diameter_cat            372 non-null    object
dtypes: float64(14), int64(11), object(3)
memory usage: 81.5+ KB

In [8]:
df_main.equals(df_merged)

True

DataFrame sent by Dmitry

In [10]:
df_merged_2 = pd.read_excel('../data/df_merged_edited (3).xlsx', index_col=0).reset_index(drop=True)

df_merged.equals(df_merged_2)

True

In [11]:
df_merged_3 = pd.read_excel('../data/df_merged.xlsx', index_col=0).reset_index(drop=True)

df_merged_3.equals(df_merged)

False