Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

base_estimator_params - redundant thing in logging! - SOLVED!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-smote_opt-model'
add_smote = True
is_smotenc = True
common_smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 1500 # set 1500

save_model_and_metrics = True
metrics_file = "metrics_modelling4_5.2-opt_smotenc_with_ensembles.xlsx"

smote_params = {
    'splashing': {
        **common_smote_params,
        'k_neighbors': 7,
        'sampling_strategy': 0.8, # 0.9 for SMOTE
    },
    'no_fragmentation': {
        **common_smote_params,
        'k_neighbors': 5,
        'sampling_strategy': 0.6,
    }
}

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    base_estimator:Type[BaseEstimator]=None,
    base_estimator_params:dict=None,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    base_estimator_params_list:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    
    target_smote_params = smote_params[target]
    
    estimator_params = estimator_params.copy()
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=target_smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    # Process base_estimator_params
    if base_estimator_params_list:
        best_params_base_estimator = {}
        for param in base_estimator_params_list:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params_base_estimator[param] = best_params.pop(key)
        print('best_params for main estimator')
        display(best_params)
        print('best_params for base estimator')
        display(best_params_base_estimator)
        if base_estimator_params is None:
            base_estimator_params = best_params_base_estimator
        else:
            base_estimator_params = base_estimator_params.copy()
            base_estimator_params.update(best_params_base_estimator)
    else:
        print('best_params')
        display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params, # Would be None if base_estimator_params_list is not provided
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=target_smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# CatBoost

In [6]:
estimator = CatBoostClassifier
target = 'splashing'
# TODO: Try with GPU!
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

def catboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "iterations": trial.suggest_int("iterations", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 3, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "grow_policy": trial.suggest_categorical("grow_policy", ["SymmetricTree", "Depthwise", "Lossguide"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"]),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", ["Balanced", "SqrtBalanced", None]),
    }
    
    if suggested_estimator_params['bootstrap_type'] == 'Bernoulli':
        suggested_estimator_params['subsample'] = trial.suggest_float(
            "subsample", 0.5, 1.0
        )
        
    if suggested_estimator_params['bootstrap_type'] == 'Bayesian':
        suggested_estimator_params['bagging_temperature'] = (
            trial.suggest_float("bagging_temperature", 0.0, 1.0)
        )

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 09:40:58,580] A new study created in memory with name: model_study
[I 2025-04-18 09:41:07,309] Trial 0 finished with value: 0.8707266993763729 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8707266993763729.
[I 2025-04-18 09:41:11,319] Trial 1 finished with value: 0.8874865734272449 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 1 with value: 0.8874865734272449.
[I 2025-04-18 09:41:20,872] Trial 2 finished with value: 0.8669952324316712 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 1 with value: 0.8874865734272449.
[I 2025-04-18 09:41:26,034] Trial 3 finished with value: 0.877144400558599 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 1 with value: 0.8874865734272449.
[I 2025-04-18 09:41:29,100] Trial 4 finished with value: 0.9005633756865283 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 4 with value: 0.9005633756865283.
[I 2025-04-18 09:41:32,441] Trial 5 finished with value: 0.87469603125744 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 4 with value: 0.9005633756865283.
[I 2025-04-18 09:41:35,927] Trial 6 finished with value: 0.9043807134584875 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:41:45,154] Trial 7 finished with value: 0.8812295959853275 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:00,554] Trial 8 finished with value: 0.865995966980714 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:02,722] Trial 9 finished with value: 0.8651271374554061 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:06,972] Trial 10 finished with value: 0.8976435019925585 and parameters: {'iterations': 652, 'learning_rate': 0.03357104002950685, 'depth': 5, 'l2_leaf_reg': 0.0011799062523159302, 'random_strength': 0.5025312176747964, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.06569066558371356}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:11,019] Trial 11 finished with value: 0.8924627105857945 and parameters: {'iterations': 727, 'learning_rate': 0.0073749081572081895, 'depth': 5, 'l2_leaf_reg': 0.0013119764983343123, 'random_strength': 0.9930825760518938, 'border_count': 34, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.214371635598811}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:14,712] Trial 12 finished with value: 0.8971786224658765 and parameters: {'iterations': 483, 'learning_rate': 0.05716649396119186, 'depth': 6, 'l2_leaf_reg': 0.0074603161741068685, 'random_strength': 0.6276429452559499, 'border_count': 103, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.4892941806716758}. Best is trial 6 with value: 0.9043807134584875.
[I 2025-04-18 09:42:21,660] Trial 13 finished with value: 0.9074969572590011 and parameters: {'iterations': 1000, 'learning_rate': 0.01078382443857064, 'depth': 6, 'l2_leaf_reg': 0.005867433881732628, 'random_strength': 0.34181407760905663, 'border_count': 82, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.4286103862846429}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:28,411] Trial 14 finished with value: 0.9036056515204047 and parameters: {'iterations': 1000, 'learning_rate': 0.014269906911384007, 'depth': 6, 'l2_leaf_reg': 0.007014792137864268, 'random_strength': 0.3242617733528243, 'border_count': 78, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.4068254612090233}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:32,900] Trial 15 finished with value: 0.8823106925551458 and parameters: {'iterations': 733, 'learning_rate': 0.05807524017480548, 'depth': 5, 'l2_leaf_reg': 0.003124633046953447, 'random_strength': 0.004740119653089292, 'border_count': 128, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.3264404364792821}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:33,445] Trial 16 finished with value: 0.8028024435065708 and parameters: {'iterations': 56, 'learning_rate': 0.010142127623865783, 'depth': 3, 'l2_leaf_reg': 0.013810257711304461, 'random_strength': 0.34846107776278246, 'border_count': 128, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.7274356793983534}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:45,356] Trial 17 finished with value: 0.8746453201862483 and parameters: {'iterations': 998, 'learning_rate': 0.002714606442157933, 'depth': 8, 'l2_leaf_reg': 1.5257066795346366, 'random_strength': 0.1317955370773498, 'border_count': 85, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.5582887879382636}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:54,772] Trial 18 finished with value: 0.893683431623166 and parameters: {'iterations': 598, 'learning_rate': 0.03055794007065367, 'depth': 6, 'l2_leaf_reg': 0.0022638160816371078, 'random_strength': 0.4000419141163639, 'border_count': 174, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:42:59,303] Trial 19 finished with value: 0.8968522578552464 and parameters: {'iterations': 839, 'learning_rate': 0.014422577597340579, 'depth': 4, 'l2_leaf_reg': 0.02708439706855693, 'random_strength': 0.6058846602813076, 'border_count': 68, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.9938427850497089}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:10,305] Trial 20 finished with value: 0.8861636846090695 and parameters: {'iterations': 876, 'learning_rate': 0.06502000756008273, 'depth': 8, 'l2_leaf_reg': 0.007328925641357473, 'random_strength': 0.21523161743847058, 'border_count': 118, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.18851458307303104}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:17,120] Trial 21 finished with value: 0.9040523754389368 and parameters: {'iterations': 972, 'learning_rate': 0.012204932518963351, 'depth': 6, 'l2_leaf_reg': 0.006031731431219689, 'random_strength': 0.37651318345433404, 'border_count': 85, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.39846499058180035}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:22,278] Trial 22 finished with value: 0.8926579163117766 and parameters: {'iterations': 925, 'learning_rate': 0.0025830894597633157, 'depth': 5, 'l2_leaf_reg': 0.003013503950504034, 'random_strength': 0.4145917565949375, 'border_count': 35, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.3282260571079754}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:27,295] Trial 23 finished with value: 0.8966895517471623 and parameters: {'iterations': 715, 'learning_rate': 0.019653726558987422, 'depth': 6, 'l2_leaf_reg': 0.001180099151306869, 'random_strength': 0.5996277193685422, 'border_count': 87, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.5694374100792974}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:31,535] Trial 24 finished with value: 0.8938285116863864 and parameters: {'iterations': 805, 'learning_rate': 0.013546393430660343, 'depth': 4, 'l2_leaf_reg': 0.013491343196041297, 'random_strength': 0.27003445426356487, 'border_count': 55, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.2269847737644084}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:38,170] Trial 25 finished with value: 0.8920550939461981 and parameters: {'iterations': 484, 'learning_rate': 0.009396374185076295, 'depth': 6, 'l2_leaf_reg': 0.09099237909899582, 'random_strength': 0.433705534434632, 'border_count': 78, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:43,935] Trial 26 finished with value: 0.8897263177181873 and parameters: {'iterations': 938, 'learning_rate': 0.029536908742174035, 'depth': 5, 'l2_leaf_reg': 0.005418014653184754, 'random_strength': 0.12652462231224804, 'border_count': 113, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.4079371142305373}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:50,278] Trial 27 finished with value: 0.8852871006715591 and parameters: {'iterations': 623, 'learning_rate': 0.0034207275735111033, 'depth': 8, 'l2_leaf_reg': 0.001736115071539774, 'random_strength': 0.007875874005311173, 'border_count': 62, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.05007413428788987}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:43:57,169] Trial 28 finished with value: 0.9001029965399174 and parameters: {'iterations': 798, 'learning_rate': 0.09645405507507981, 'depth': 7, 'l2_leaf_reg': 0.011831540091446862, 'random_strength': 0.2152189818611025, 'border_count': 92, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.6251395930402179}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:02,188] Trial 29 finished with value: 0.8799142451236046 and parameters: {'iterations': 311, 'learning_rate': 0.008770886802480022, 'depth': 9, 'l2_leaf_reg': 0.11137680146646914, 'random_strength': 0.16778637993517345, 'border_count': 70, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:06,628] Trial 30 finished with value: 0.9010185663039975 and parameters: {'iterations': 540, 'learning_rate': 0.025557378380613477, 'depth': 6, 'l2_leaf_reg': 0.004606657984455261, 'random_strength': 0.5309288066611477, 'border_count': 146, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.33172575056104525}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:13,321] Trial 31 finished with value: 0.9001029965399174 and parameters: {'iterations': 996, 'learning_rate': 0.014411811697449397, 'depth': 6, 'l2_leaf_reg': 0.007266138898480222, 'random_strength': 0.32920443782034353, 'border_count': 75, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.4313234117973488}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:19,220] Trial 32 finished with value: 0.8967007615200353 and parameters: {'iterations': 934, 'learning_rate': 0.011196991852032415, 'depth': 6, 'l2_leaf_reg': 0.03066220679297059, 'random_strength': 0.3732591672064445, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.418362194510054}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:29,917] Trial 33 finished with value: 0.8887556881749141 and parameters: {'iterations': 955, 'learning_rate': 0.04327759846240511, 'depth': 7, 'l2_leaf_reg': 0.0023153380286464412, 'random_strength': 0.2719669909964, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.2812178703760208}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:34,836] Trial 34 finished with value: 0.8783432928137361 and parameters: {'iterations': 895, 'learning_rate': 0.006722922585373507, 'depth': 5, 'l2_leaf_reg': 0.736709148131115, 'random_strength': 0.29041428701915967, 'border_count': 32, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.46890876979937735}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:46,927] Trial 35 finished with value: 0.9000598091152968 and parameters: {'iterations': 804, 'learning_rate': 0.019601984391762996, 'depth': 7, 'l2_leaf_reg': 0.010166608121018116, 'random_strength': 0.079337248758245, 'border_count': 113, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:44:49,428] Trial 36 finished with value: 0.8742162611403124 and parameters: {'iterations': 442, 'learning_rate': 0.0041548314844805775, 'depth': 4, 'l2_leaf_reg': 0.004198686177275811, 'random_strength': 0.441773592316485, 'border_count': 93, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.5152673521593867}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:07,264] Trial 37 finished with value: 0.9008803057533078 and parameters: {'iterations': 992, 'learning_rate': 0.01746693808478957, 'depth': 7, 'l2_leaf_reg': 0.017631980839775192, 'random_strength': 0.6862349003597239, 'border_count': 78, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.13156291446020568}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:14,761] Trial 38 finished with value: 0.878502080855944 and parameters: {'iterations': 570, 'learning_rate': 0.0403326152002018, 'depth': 9, 'l2_leaf_reg': 2.823894893911405, 'random_strength': 0.457507475798951, 'border_count': 51, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.9948283159207818}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:21,913] Trial 39 finished with value: 0.8929336923119954 and parameters: {'iterations': 367, 'learning_rate': 0.006478465075634894, 'depth': 6, 'l2_leaf_reg': 0.0437566597750032, 'random_strength': 0.3235326650151714, 'border_count': 236, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.3831507145146695}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:25,844] Trial 40 finished with value: 0.8963483572983154 and parameters: {'iterations': 675, 'learning_rate': 0.012680722216381004, 'depth': 5, 'l2_leaf_reg': 0.10366816181201548, 'random_strength': 0.1925298640512888, 'border_count': 62, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.5120288644469331}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:30,060] Trial 41 finished with value: 0.8934195956812656 and parameters: {'iterations': 514, 'learning_rate': 0.023934515930835613, 'depth': 6, 'l2_leaf_reg': 0.004900542113573515, 'random_strength': 0.49176584302818016, 'border_count': 146, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.32927056805665994}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:32,422] Trial 42 finished with value: 0.890153576754883 and parameters: {'iterations': 249, 'learning_rate': 0.026765242538160906, 'depth': 6, 'l2_leaf_reg': 0.002075924648875397, 'random_strength': 0.5434420704598744, 'border_count': 163, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.3080307172071793}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:37,027] Trial 43 finished with value: 0.8896551114940897 and parameters: {'iterations': 435, 'learning_rate': 0.01616201012472228, 'depth': 7, 'l2_leaf_reg': 0.0037388106857505353, 'random_strength': 0.5663158331227494, 'border_count': 140, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.5434044240957049}. Best is trial 13 with value: 0.9074969572590011.
[I 2025-04-18 09:45:41,819] Trial 44 finished with value: 0.8775798301951372 and parameters: {'iterations': 845, 'learning_rate': 0.291177361911713, 'depth': 5, 'l2_leaf_reg': 0.0010713231216413312, 'random_strength': 0.6796572572356556, 'border_count': 103, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.3794059192797489}. Best is trial 13 with value: 0.9074969572590011.

best_params

{'iterations': 504,
 'learning_rate': 0.019473565802789774,
 'depth': 5,
 'l2_leaf_reg': 0.0013931022467039463,
 'random_strength': 0.814665031592886,
 'border_count': 69,
 'grow_policy': 'Lossguide',
 'bootstrap_type': 'Bayesian',
 'auto_class_weights': 'SqrtBalanced',
 'bagging_temperature': 0.9998351625186293}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                          0.88
holdout_test_accuracy_balanced                                             0.868056
holdout_test_roc_auc                                                       0.950617
holdout_test_f1                                                                0.92
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.879545
cv_test_accuracy_balanced_median                                           0.900794
cv_test_roc_auc_median                                                     0.950464
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                      0.85

Model saved in ..\results\models_modelling4\CatBoostClassifier_splashing_smotenc_opt-smote_opt-model

In [ ]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 12:03:12,340] A new study created in memory with name: model_study
[I 2025-04-18 12:03:21,800] Trial 0 finished with value: 0.8291920727481006 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8291920727481006.
[I 2025-04-18 12:03:25,985] Trial 1 finished with value: 0.8344903641414426 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 1 with value: 0.8344903641414426.
[I 2025-04-18 12:03:35,237] Trial 2 finished with value: 0.8364977988985943 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 2 with value: 0.8364977988985943.
[I 2025-04-18 12:03:40,730] Trial 3 finished with value: 0.847533337729019 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 3 with value: 0.847533337729019.
[I 2025-04-18 12:03:44,019] Trial 4 finished with value: 0.8436692042856192 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 3 with value: 0.847533337729019.
[I 2025-04-18 12:03:47,267] Trial 5 finished with value: 0.8358777818648753 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 3 with value: 0.847533337729019.
[I 2025-04-18 12:03:50,899] Trial 6 finished with value: 0.8416701993602915 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 3 with value: 0.847533337729019.
[I 2025-04-18 12:03:59,757] Trial 7 finished with value: 0.854286732846932 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 7 with value: 0.854286732846932.
[I 2025-04-18 12:04:15,274] Trial 8 finished with value: 0.8307973528213125 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 7 with value: 0.854286732846932.
[I 2025-04-18 12:04:17,647] Trial 9 finished with value: 0.8456209084404792 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 7 with value: 0.854286732846932.
[I 2025-04-18 12:04:21,360] Trial 10 finished with value: 0.8505604956865768 and parameters: {'iterations': 70, 'learning_rate': 0.07767314798840616, 'depth': 10, 'l2_leaf_reg': 0.7803665684896557, 'random_strength': 0.9834247540824036, 'border_count': 226, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.012311169564937496}. Best is trial 7 with value: 0.854286732846932.
[I 2025-04-18 12:04:24,256] Trial 11 finished with value: 0.850047871106217 and parameters: {'iterations': 58, 'learning_rate': 0.07324963963746431, 'depth': 10, 'l2_leaf_reg': 1.096772009080415, 'random_strength': 0.9938060331835449, 'border_count': 229, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.006569541499435333}. Best is trial 7 with value: 0.854286732846932.
[I 2025-04-18 12:04:43,623] Trial 12 finished with value: 0.8604447794814287 and parameters: {'iterations': 766, 'learning_rate': 0.05105823178669672, 'depth': 9, 'l2_leaf_reg': 1.438494697238284, 'random_strength': 0.9912440663582666, 'border_count': 190, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.002951634325972667}. Best is trial 12 with value: 0.8604447794814287.
[I 2025-04-18 12:05:04,163] Trial 13 finished with value: 0.8644953905810807 and parameters: {'iterations': 820, 'learning_rate': 0.04800122959997557, 'depth': 9, 'l2_leaf_reg': 1.6245569945819849, 'random_strength': 0.6182218542766706, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.5058585565635159}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:05:24,882] Trial 14 finished with value: 0.8425948485479721 and parameters: {'iterations': 836, 'learning_rate': 0.04103652238586884, 'depth': 9, 'l2_leaf_reg': 2.7345335474799968, 'random_strength': 0.5998924799776718, 'border_count': 179, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.5545349164923506}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:05:30,199] Trial 15 finished with value: 0.8509604737870379 and parameters: {'iterations': 737, 'learning_rate': 0.04391527823093653, 'depth': 5, 'l2_leaf_reg': 1.9858725332787173, 'random_strength': 0.3834633552909257, 'border_count': 180, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.4152272367138179}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:05:51,222] Trial 16 finished with value: 0.8389853765703348 and parameters: {'iterations': 991, 'learning_rate': 0.010923733371330947, 'depth': 9, 'l2_leaf_reg': 2.2326519824977398, 'random_strength': 0.6089582803996045, 'border_count': 142, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.6537096158441438}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:06:00,099] Trial 17 finished with value: 0.8399703076234356 and parameters: {'iterations': 619, 'learning_rate': 0.09396676796026655, 'depth': 8, 'l2_leaf_reg': 0.6066296118381393, 'random_strength': 0.6590705720892039, 'border_count': 145, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:06:14,099] Trial 18 finished with value: 0.844430882363806 and parameters: {'iterations': 693, 'learning_rate': 0.04073081017888244, 'depth': 8, 'l2_leaf_reg': 0.11998217000060728, 'random_strength': 0.40745698530395225, 'border_count': 202, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.990843761715617}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:06:23,534] Trial 19 finished with value: 0.8500371673615249 and parameters: {'iterations': 983, 'learning_rate': 0.012594724787324672, 'depth': 6, 'l2_leaf_reg': 9.658318826868316, 'random_strength': 0.7275372626784159, 'border_count': 255, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.24333912656439152}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:06:40,452] Trial 20 finished with value: 0.8479173777229028 and parameters: {'iterations': 787, 'learning_rate': 0.029697377092187897, 'depth': 9, 'l2_leaf_reg': 0.013957691457683668, 'random_strength': 0.8917728472008136, 'border_count': 150, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.24464677759186668}. Best is trial 13 with value: 0.8644953905810807.
[I 2025-04-18 12:07:14,423] Trial 21 finished with value: 0.8662966865443823 and parameters: {'iterations': 912, 'learning_rate': 0.2992030214224366, 'depth': 9, 'l2_leaf_reg': 0.35500726610018213, 'random_strength': 0.8968343757296071, 'border_count': 204, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9913842220836627}. Best is trial 21 with value: 0.8662966865443823.
[I 2025-04-18 12:07:34,732] Trial 22 finished with value: 0.8380417572973821 and parameters: {'iterations': 896, 'learning_rate': 0.2987934767801689, 'depth': 8, 'l2_leaf_reg': 3.176454154723358, 'random_strength': 0.9152601871717813, 'border_count': 197, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.5283382636788065}. Best is trial 21 with value: 0.8662966865443823.
[I 2025-04-18 12:07:47,484] Trial 23 finished with value: 0.8683065417721932 and parameters: {'iterations': 644, 'learning_rate': 0.13068522594556398, 'depth': 10, 'l2_leaf_reg': 1.1315112564944965, 'random_strength': 0.6885886389893303, 'border_count': 168, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:07:59,202] Trial 24 finished with value: 0.8399949884124924 and parameters: {'iterations': 655, 'learning_rate': 0.13341802441244502, 'depth': 10, 'l2_leaf_reg': 0.13969648223009465, 'random_strength': 0.5238291592820093, 'border_count': 121, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:08:16,662] Trial 25 finished with value: 0.8674819158576026 and parameters: {'iterations': 925, 'learning_rate': 0.13565696997207286, 'depth': 10, 'l2_leaf_reg': 0.5449950663128273, 'random_strength': 0.692957549953857, 'border_count': 161, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:08:34,057] Trial 26 finished with value: 0.8402484358084783 and parameters: {'iterations': 914, 'learning_rate': 0.1389218270075123, 'depth': 10, 'l2_leaf_reg': 0.46641596263605706, 'random_strength': 0.7020258723623357, 'border_count': 168, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:08:44,710] Trial 27 finished with value: 0.8478952305839754 and parameters: {'iterations': 552, 'learning_rate': 0.2155250101252521, 'depth': 10, 'l2_leaf_reg': 0.1945383826289833, 'random_strength': 0.7328903133678389, 'border_count': 161, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:09:01,242] Trial 28 finished with value: 0.8479077727144652 and parameters: {'iterations': 937, 'learning_rate': 0.28866143939188676, 'depth': 10, 'l2_leaf_reg': 0.0655974171375961, 'random_strength': 0.8398384561816135, 'border_count': 126, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:09:10,222] Trial 29 finished with value: 0.8387692693825178 and parameters: {'iterations': 480, 'learning_rate': 0.17082245340369867, 'depth': 8, 'l2_leaf_reg': 0.7002005019520828, 'random_strength': 0.5463829492925386, 'border_count': 212, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:09:21,148] Trial 30 finished with value: 0.8497803419478459 and parameters: {'iterations': 707, 'learning_rate': 0.09420512328235374, 'depth': 8, 'l2_leaf_reg': 0.3113728054221989, 'random_strength': 0.43055884272608086, 'border_count': 81, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:09:37,221] Trial 31 finished with value: 0.8616644008713786 and parameters: {'iterations': 821, 'learning_rate': 0.06374104266918384, 'depth': 9, 'l2_leaf_reg': 1.1610239676049474, 'random_strength': 0.6291899350214888, 'border_count': 187, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:10:12,479] Trial 32 finished with value: 0.8474337926686287 and parameters: {'iterations': 851, 'learning_rate': 0.11037693747506928, 'depth': 9, 'l2_leaf_reg': 3.35777409423869, 'random_strength': 0.5764989914587388, 'border_count': 156, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:10:24,076] Trial 33 finished with value: 0.8443189144807912 and parameters: {'iterations': 611, 'learning_rate': 0.18447093191291253, 'depth': 10, 'l2_leaf_reg': 4.679085389910373, 'random_strength': 0.6816514338673793, 'border_count': 132, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9813465272850804}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:10:58,294] Trial 34 finished with value: 0.8485468527221592 and parameters: {'iterations': 924, 'learning_rate': 0.2967689552538817, 'depth': 9, 'l2_leaf_reg': 0.5061047235865641, 'random_strength': 0.7573519654592159, 'border_count': 178, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9958075105446772}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:11:15,123] Trial 35 finished with value: 0.862642614711432 and parameters: {'iterations': 798, 'learning_rate': 0.03113393583593959, 'depth': 10, 'l2_leaf_reg': 1.2959542549684144, 'random_strength': 0.44321015339838943, 'border_count': 206, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:11:33,844] Trial 36 finished with value: 0.8442138632037578 and parameters: {'iterations': 996, 'learning_rate': 0.10784205313484793, 'depth': 8, 'l2_leaf_reg': 0.20463218231051014, 'random_strength': 0.7859526223719038, 'border_count': 224, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.8378825597495559}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:12:10,734] Trial 37 finished with value: 0.8512731226663716 and parameters: {'iterations': 761, 'learning_rate': 0.05999562602230832, 'depth': 9, 'l2_leaf_reg': 5.237085648380246, 'random_strength': 0.3181428142547701, 'border_count': 166, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:12:19,980] Trial 38 finished with value: 0.8485832454492145 and parameters: {'iterations': 940, 'learning_rate': 0.15637935891792695, 'depth': 5, 'l2_leaf_reg': 0.05841470126914881, 'random_strength': 0.9275220704529881, 'border_count': 108, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.5007250058963767}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:12:41,358] Trial 39 finished with value: 0.8435606589260232 and parameters: {'iterations': 875, 'learning_rate': 0.002612410861878738, 'depth': 7, 'l2_leaf_reg': 0.3884040117588857, 'random_strength': 0.8384041703830074, 'border_count': 194, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.5959138172085039}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:13:05,841] Trial 40 finished with value: 0.8424705776525325 and parameters: {'iterations': 431, 'learning_rate': 0.22714242788058478, 'depth': 10, 'l2_leaf_reg': 0.8377560478751469, 'random_strength': 0.6512037684716091, 'border_count': 237, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:13:22,752] Trial 41 finished with value: 0.8582172806014936 and parameters: {'iterations': 798, 'learning_rate': 0.02649287576044835, 'depth': 10, 'l2_leaf_reg': 1.6769273843564587, 'random_strength': 0.35425830713091694, 'border_count': 211, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:13:36,591] Trial 42 finished with value: 0.85418394622181 and parameters: {'iterations': 661, 'learning_rate': 0.031175874000589358, 'depth': 10, 'l2_leaf_reg': 1.2449775370072793, 'random_strength': 0.4705387080130221, 'border_count': 204, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:13:52,705] Trial 43 finished with value: 0.8588551713819934 and parameters: {'iterations': 823, 'learning_rate': 0.01828796410102874, 'depth': 9, 'l2_leaf_reg': 1.0007016508767672, 'random_strength': 0.23084372941943423, 'border_count': 175, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:14:07,535] Trial 44 finished with value: 0.8472204706707667 and parameters: {'iterations': 711, 'learning_rate': 0.00991431108736506, 'depth': 10, 'l2_leaf_reg': 5.048251537281437, 'random_strength': 0.47798526564764465, 'border_count': 216, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'SqrtBalanced'}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:14:13,839] Trial 45 finished with value: 0.8539928215221652 and parameters: {'iterations': 309, 'learning_rate': 0.08622689209531635, 'depth': 9, 'l2_leaf_reg': 0.5447578153800733, 'random_strength': 0.5631308741893033, 'border_count': 188, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8819908486886308}. Best is trial 23 with value: 0.8683065417721932.
[I 2025-04-18 12:14:46,720] Trial 46 finished with value: 0.8479470392153565 and parameters: {'iterations': 586, 'learning_rate': 0.054329410066326855, 'depth': 10, 'l2_leaf_reg': 0.030060917126185582, 'random_strength': 0.8143281454680342, 'border_count': 159, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 23 with value: 0.8683065417721932.

# XGBoost

In [ ]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {
    'n_jobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 132/240 # For splashing

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [scale_pos_weight, 1.0]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 00:06:22,064] A new study created in memory with name: model_study
[I 2025-04-18 00:06:22,293] Trial 0 finished with value: 0.7632749043590484 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 0.55}. Best is trial 0 with value: 0.7632749043590484.
[I 2025-04-18 00:06:22,712] Trial 1 finished with value: 0.8432896785087662 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8432896785087662.
[I 2025-04-18 00:06:22,924] Trial 2 finished with value: 0.7460153486126597 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8432896785087662.
[I 2025-04-18 00:06:23,332] Trial 3 finished with value: 0.8565808215998213 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 1.0}. Best is trial 3 with value: 0.8565808215998213.
[I 2025-04-18 00:06:23,535] Trial 4 finished with value: 0.7450495467256278 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 0.55}. Best is trial 3 with value: 0.8565808215998213.

best_params

{'n_estimators': 952,
 'learning_rate': 0.24659691172104828,
 'max_depth': 9,
 'min_child_weight': 7,
 'gamma': 0.48836057003191935,
 'subsample': 0.8421165132560784,
 'colsample_bytree': 0.7200762468698007,
 'reg_alpha': 0.003077180271250686,
 'reg_lambda': 0.09565499215943825,
 'scale_pos_weight': 1.0}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smotenc_opt-smote_opt-...
holdout_test_f1_macro                                                       0.86631
holdout_test_accuracy_balanced                                             0.857639
holdout_test_roc_auc                                                       0.929398
holdout_test_f1                                                            0.909091
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.901587
cv_test_roc_auc_median                                                     0.947368
cv_test_f1_median                                                          0.925373
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.888889
cv_test_f1_class_0_median                                                  0.864865

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smotenc_opt-smote_opt-model

In [ ]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {
    'n_jobs': 1,
}
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 273/99 # For no_fragmentation

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [1.0, scale_pos_weight]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 00:06:24,285] A new study created in memory with name: model_study
[I 2025-04-18 00:06:24,504] Trial 0 finished with value: 0.786127056179522 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 1.0}. Best is trial 0 with value: 0.786127056179522.
[I 2025-04-18 00:06:24,927] Trial 1 finished with value: 0.8398156588981732 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8398156588981732.
[I 2025-04-18 00:06:25,139] Trial 2 finished with value: 0.7798174061588329 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8398156588981732.
[I 2025-04-18 00:06:25,539] Trial 3 finished with value: 0.8432733020679338 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 2.757575757575758}. Best is trial 3 with value: 0.8432733020679338.
[I 2025-04-18 00:06:25,739] Trial 4 finished with value: 0.7868412086436388 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 1.0}. Best is trial 3 with value: 0.8432733020679338.

best_params

{'n_estimators': 952,
 'learning_rate': 0.24659691172104828,
 'max_depth': 9,
 'min_child_weight': 7,
 'gamma': 0.48836057003191935,
 'subsample': 0.8421165132560784,
 'colsample_bytree': 0.7200762468698007,
 'reg_alpha': 0.003077180271250686,
 'reg_lambda': 0.09565499215943825,
 'scale_pos_weight': 2.757575757575758}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smotenc_opt-smo...
holdout_test_f1_macro                                                      0.867725
holdout_test_accuracy_balanced                                             0.879545
holdout_test_roc_auc                                                       0.978182
holdout_test_f1                                                            0.809524
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.886022
cv_test_accuracy_balanced_median                                            0.90293
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                           0.83871
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                               0.95
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.933333

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smotenc_opt-smote_opt-model

# AdaBoost

In [ ]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

def adaboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_base_estimator_params = {
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20), # Closed to min_child_weight
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }
    base_estimator_params = update_estimator_params(
        ml_pipe,
        suggested_base_estimator_params,
        estimator_type='base',
    )

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        base_estimator=ml_pipe._pipeline_params['base_estimator'],
        estimator_params=estimator_params,
        base_estimator_params=base_estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 00:06:26,461] A new study created in memory with name: model_study
[I 2025-04-18 00:06:27,676] Trial 0 finished with value: 0.8668766881908763 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.8668766881908763.
[I 2025-04-18 00:06:33,503] Trial 1 finished with value: 0.8746099073286845 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.8746099073286845.
[I 2025-04-18 00:06:35,152] Trial 2 finished with value: 0.857649745178913 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 1 with value: 0.8746099073286845.
[I 2025-04-18 00:06:36,596] Trial 3 finished with value: 0.8558458939870419 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 1 with value: 0.8746099073286845.
[I 2025-04-18 00:06:42,334] Trial 4 finished with value: 0.8925076651722611 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 4 with value: 0.8925076651722611.

best_params for main estimator

{'n_estimators': 952, 'learning_rate': 0.24659691172104828}

best_params for base estimator

{'max_depth': 6,
 'min_samples_split': 2,
 'min_samples_leaf': 13,
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.806892
holdout_test_accuracy_balanced                                             0.799769
holdout_test_roc_auc                                                       0.902778
holdout_test_f1                                                            0.868687
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.915873
cv_test_accuracy_balanced_median                                           0.906347
cv_test_roc_auc_median                                                     0.941176
cv_test_f1_median                                                          0.939394
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.857143
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.888889

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smotenc_opt-smote_opt-model

In [ ]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 00:06:50,788] A new study created in memory with name: model_study
[I 2025-04-18 00:06:51,965] Trial 0 finished with value: 0.7969678363101872 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.7969678363101872.
[I 2025-04-18 00:06:57,599] Trial 1 finished with value: 0.8019275450780119 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.8019275450780119.
[I 2025-04-18 00:06:59,200] Trial 2 finished with value: 0.8330350548754203 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 2 with value: 0.8330350548754203.
[I 2025-04-18 00:07:00,606] Trial 3 finished with value: 0.8661730538550927 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 3 with value: 0.8661730538550927.
[I 2025-04-18 00:07:06,295] Trial 4 finished with value: 0.837673748046348 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 3 with value: 0.8661730538550927.

best_params for main estimator

{'n_estimators': 239, 'learning_rate': 0.018785426399210624}

best_params for base estimator

{'max_depth': 2,
 'min_samples_split': 7,
 'min_samples_leaf': 8,
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.877451
holdout_test_accuracy_balanced                                             0.927273
holdout_test_roc_auc                                                       0.977273
holdout_test_f1                                                            0.833333
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.886887
cv_test_accuracy_balanced_median                                            0.90293
cv_test_roc_auc_median                                                     0.965812
cv_test_f1_median                                                           0.83871
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.969697
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smotenc_opt-smote_opt-model

# Random Forest

In [ ]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def rf_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int('min_samples_leaf', 1, 20),
        "max_features": trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        "bootstrap": trial.suggest_categorical('bootstrap', [True, False]),
        "criterion": trial.suggest_categorical('criterion', ['gini', 'entropy']),
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 00:07:08,592] A new study created in memory with name: model_study
[I 2025-04-18 00:07:10,239] Trial 0 finished with value: 0.855484241940141 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.855484241940141.
[I 2025-04-18 00:07:11,286] Trial 1 finished with value: 0.8432707901227564 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.855484241940141.
[I 2025-04-18 00:07:12,358] Trial 2 finished with value: 0.8750558135577879 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8750558135577879.
[I 2025-04-18 00:07:14,106] Trial 3 finished with value: 0.8386162738767953 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8750558135577879.
[I 2025-04-18 00:07:17,325] Trial 4 finished with value: 0.8289029770846134 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8750558135577879.

best_params

{'n_estimators': 239,
 'max_depth': 11,
 'min_samples_split': 13,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'bootstrap': False,
 'criterion': 'gini',
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smotenc_opt-s...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.944444
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.835913
cv_test_accuracy_balanced_median                                           0.845238
cv_test_roc_auc_median                                                     0.939628
cv_test_f1_median                                                          0.885714
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.823529
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.789474

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smotenc_opt-smote_opt-model

In [ ]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 00:07:19,017] A new study created in memory with name: model_study
[I 2025-04-18 00:07:20,712] Trial 0 finished with value: 0.8306703994855411 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8306703994855411.
[I 2025-04-18 00:07:21,802] Trial 1 finished with value: 0.812756436404767 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8306703994855411.
[I 2025-04-18 00:07:22,761] Trial 2 finished with value: 0.8301656429451812 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8306703994855411.
[I 2025-04-18 00:07:24,335] Trial 3 finished with value: 0.8095974516643633 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8306703994855411.
[I 2025-04-18 00:07:27,443] Trial 4 finished with value: 0.8207497456980134 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 0 with value: 0.8306703994855411.

best_params

{'n_estimators': 406,
 'max_depth': 20,
 'min_samples_split': 15,
 'min_samples_leaf': 12,
 'max_features': 'sqrt',
 'bootstrap': True,
 'criterion': 'gini',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.903516
holdout_test_accuracy_balanced                                             0.929545
holdout_test_roc_auc                                                       0.958182
holdout_test_f1                                                            0.863636
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.805861
cv_test_accuracy_balanced_median                                           0.805861
cv_test_roc_auc_median                                                     0.945299
cv_test_f1_median                                                          0.714286
cv_test_accuracy_median                                                    0.851852
cv_test_precision_class_0_median                                           0.911765
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.902439

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smotenc_opt-smote_opt-model

# LightGBM

In [ ]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def lgbm_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        # "max_depth": trial.suggest_int("max_depth", 1, 10),
        "num_leaves": trial.suggest_int("num_leaves", 4, 512), # more important than max_depth
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "min_split_gain": trial.suggest_float("gamma", 0., 5.), # gamma from XGBoost
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0), # colsample_bytree from XGBoost
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "boosting_type": trial.suggest_categorical("boosting_type", ["gbdt", "dart"]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 00:07:29,916] A new study created in memory with name: model_study
[I 2025-04-18 00:07:34,270] Trial 0 finished with value: 0.8376996457054992 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8376996457054992.
[I 2025-04-18 00:07:36,634] Trial 1 finished with value: 0.7891125826629805 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8376996457054992.
[I 2025-04-18 00:07:41,258] Trial 2 finished with value: 0.8160836599330076 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8376996457054992.
[I 2025-04-18 00:07:41,539] Trial 3 finished with value: 0.7447689409889607 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8376996457054992.
[I 2025-04-18 00:07:43,264] Trial 4 finished with value: 0.811785239045132 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8376996457054992.

best_params

{'n_estimators': 406,
 'learning_rate': 0.22648248189516848,
 'num_leaves': 376,
 'min_child_samples': 62,
 'min_child_weight': 4,
 'gamma': 0.7799726016810132,
 'subsample': 0.5290418060840998,
 'colsample_bytree': 0.9330880728874675,
 'reg_alpha': 0.2537815508265665,
 'reg_lambda': 0.679657809075816,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smotenc_opt-smote_opt...
holdout_test_f1_macro                                                      0.829581
holdout_test_accuracy_balanced                                               0.8125
holdout_test_roc_auc                                                       0.934799
holdout_test_f1                                                            0.893204
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.844575
cv_test_accuracy_balanced_median                                           0.870743
cv_test_roc_auc_median                                                     0.947619
cv_test_f1_median                                                          0.885714
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.823529
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.818182

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smotenc_opt-smote_opt-model

In [ ]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 00:07:49,401] A new study created in memory with name: model_study
[I 2025-04-18 00:07:53,354] Trial 0 finished with value: 0.8408513639691539 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8408513639691539.
[I 2025-04-18 00:07:55,749] Trial 1 finished with value: 0.7675222849078824 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8408513639691539.
[I 2025-04-18 00:07:59,762] Trial 2 finished with value: 0.8051312282702155 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8408513639691539.
[I 2025-04-18 00:08:00,021] Trial 3 finished with value: 0.7004743044704194 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8408513639691539.
[I 2025-04-18 00:08:01,702] Trial 4 finished with value: 0.7813557668102344 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8408513639691539.

best_params

{'n_estimators': 406,
 'learning_rate': 0.22648248189516848,
 'num_leaves': 376,
 'min_child_samples': 62,
 'min_child_weight': 4,
 'gamma': 0.7799726016810132,
 'subsample': 0.5290418060840998,
 'colsample_bytree': 0.9330880728874675,
 'reg_alpha': 0.2537815508265665,
 'reg_lambda': 0.679657809075816,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_opt-sm...
holdout_test_f1_macro                                                      0.897727
holdout_test_accuracy_balanced                                             0.897727
holdout_test_roc_auc                                                       0.978182
holdout_test_f1                                                                0.85
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.882148
cv_test_accuracy_balanced_median                                           0.874359
cv_test_roc_auc_median                                                     0.961538
cv_test_f1_median                                                          0.827586
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.938272

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smotenc_opt-smote_opt-model