# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from pytorch_tabular.models import CategoryEmbeddingModelConfig, TabNetModelConfig

from pathlib import Path
import sys

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    PytorchTabularEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

# from pytorch_lightning.loggers import MLFlowLogger
from pytorch_lightning.loggers import TensorBoardLogger

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'first_launch'

scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
# n_trials = 1500 # checked with 15 and 100

save_model_and_metrics = True
metrics_file = "metrics_modelling4_6-neural_networks.xlsx"

## MultiLayer Perceptron (MLP)

In [5]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'layers': '128-64-32',
        'activation': 'LeakyReLU',
        # 'activation_config': {'negative_slope': 0.01},
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        # 'output_dir': Path("..", "results", "models_modelling4"), # take from ml_pipe
        # 'log_target': 'wandb',
        # 'logger_name': 'default',
        # 'checkpoints': 'f1_macro',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

2025-04-25 18:00:44,755 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:00:44,769 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:00:44,785 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:00:44,811 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:00:44,831 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:00:44,849 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:00:53,285 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:00:53,286 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:00:53,336 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:00:53,345 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:00:53,347 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:00:53,357 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:00:53,372 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:00:53,379 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:01:09,317 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:01:09,320 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:01:09,413 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:01:09,429 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:01:09,435 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:01:09,454 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:01:09,469 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:01:09,484 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:01:31,364 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:01:31,365 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:01:31,424 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:01:31,434 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:01:31,437 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:01:31,447 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:01:31,460 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:01:31,467 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:01:40,281 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:01:40,282 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:01:40,329 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:01:40,338 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:01:40,340 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:01:40,350 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:01:40,362 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:01:40,369 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:04,013 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:04,014 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:04,076 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:04,087 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:04,090 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:04,099 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:04,113 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:04,120 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:11,553 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:11,555 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:11,603 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:11,612 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:11,614 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:11,624 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:11,636 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:11,642 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:24,189 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:24,192 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:24,354 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:24,371 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:24,378 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:24,395 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:24,447 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:24,470 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (5) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:47,410 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:47,412 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                                    splashing
model                             CategoryEmbeddingModel_splashing_smote_first_l...
holdout_test_f1_macro                                                      0.823391
holdout_test_accuracy_balanced                                             0.818287
holdout_test_roc_auc                                                       0.909722
holdout_test_f1                                                            0.877551
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.842262
cv_test_accuracy_balanced_median                                           0.859133
cv_test_roc_auc_median                                                     0.941176
cv_test_f1_median                                                             0.875
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.777778
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.809524

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_splashing_smote_first_launch

In [6]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'activation': 'LeakyReLU',
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

2025-04-25 18:02:48,071 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:48,085 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:48,088 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:48,106 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:48,132 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:48,140 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:52,514 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:52,515 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:52,570 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:52,580 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:52,582 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:52,592 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:52,605 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:52,611 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:58,037 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:58,038 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:58,092 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:58,101 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:58,103 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:58,113 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:58,126 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:58,132 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:04,271 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:04,275 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:04,671 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:04,685 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:04,691 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:04,765 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:04,910 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:04,988 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:25,639 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:25,640 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:25,702 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:25,712 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:25,714 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:25,726 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:26,011 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:26,018 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:35,392 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:35,393 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:35,445 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:35,454 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:35,457 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:35,466 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:35,481 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:35,487 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:43,112 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:43,113 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:43,165 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:43,174 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:43,177 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:43,186 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:43,199 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:43,205 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:04:01,072 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:04:01,076 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:04:01,190 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:04:01,213 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:04:01,218 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:04:01,234 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:04:01,264 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:04:01,278 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:04:07,897 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:04:07,898 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.853293
holdout_test_accuracy_balanced                                             0.870455
holdout_test_roc_auc                                                           0.97
holdout_test_f1                                                            0.790698
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.902564
cv_test_roc_auc_median                                                     0.965812
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.971429
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.931507

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_no_fragmentation_smotenc_first_launch

## TabNet

In [7]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

estimator_params = {
    "model_class": TabNetModelConfig,
    "model_config_params": {
        'n_d': 8, # decoder dimension
        'n_a': 8, # attention dimension
        'n_steps': 3, # number of steps of the attention mechanism
        'gamma': 1.2, # sparsity parameter
        'n_independent': 1, # number of independent GLU layers (shared across decision steps)
        'n_shared': 1, # number of shared GLU layers (shared across steps & features)
        'virtual_batch_size': 32, # batch size for Ghost Batch Normalization
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 300,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 15,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

2025-04-25 18:04:08,202 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:04:08,211 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:04:08,214 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:04:08,224 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:04:08,241 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:04:08,248 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:04:52,590 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:04:52,591 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:04:52,672 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:04:52,682 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:04:52,686 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:04:52,696 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:04:52,711 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:04:52,729 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:06:04,633 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:06:04,634 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:06:04,754 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:06:04,764 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:06:04,767 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:06:04,777 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:06:04,793 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:06:04,802 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:06:55,617 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:06:55,619 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:06:55,700 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:06:55,711 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:06:55,713 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:06:55,724 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:06:55,739 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:06:55,747 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:07:54,705 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:07:54,709 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:07:54,996 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:07:55,017 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:07:55,025 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:07:55,046 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:07:55,074 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:07:55,087 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:08:52,120 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:08:52,121 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:08:52,204 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:08:52,214 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:08:52,217 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:08:52,227 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:08:52,243 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:08:52,253 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:10:26,325 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:10:26,326 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:10:26,424 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:10:26,436 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:10:26,440 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:10:26,451 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:10:26,467 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:10:26,483 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:11:07,789 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:11:07,790 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:11:07,895 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:11:07,906 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:11:07,910 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:11:07,921 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:11:07,936 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:11:07,951 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (5) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:12:11,002 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:12:11,006 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                         0
target                                                           splashing
model                             TabNetModel_splashing_smote_first_launch
holdout_test_f1_macro                                                 0.75
holdout_test_accuracy_balanced                                    0.763889
holdout_test_roc_auc                                              0.865741
holdout_test_f1                                                        0.8
holdout_test_accuracy                                                 0.76
cv_test_f1_macro_median                                           0.766862
cv_test_accuracy_balanced_median                                    0.7887
cv_test_roc_auc_median                                            0.852941
cv_test_f1_median                                                 0.806452
cv_test_accuracy_median                                           0.773585
cv_test_precision_class_0_median                                      0.64
cv_test_recall_class_0_median                                     0.842105
cv_test_f1_class_0_median                                         0.727273

Model saved in ../results/models_modelling4/TabNetModel_splashing_smote_first_launch

In [8]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

estimator_params = {
    "model_class": TabNetModelConfig,
    "model_config_params": {
        'n_d': 8, # decoder dimension
        'n_a': 8, # attention dimension
        'n_steps': 3, # number of steps of the attention mechanism
        'gamma': 1.2, # sparsity parameter
        'n_independent': 1, # number of independent GLU layers (shared across decision steps)
        'n_shared': 1, # number of shared GLU layers (shared across steps & features)
        'virtual_batch_size': 32, # batch size for Ghost Batch Normalization
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 300,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 15,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

2025-04-25 18:12:12,506 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:12:12,515 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:12:12,518 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:12:12,529 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:12:12,543 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:12:12,551 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:13:07,583 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:13:07,584 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:13:07,678 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:13:07,689 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:13:07,692 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:13:07,703 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:13:07,720 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:13:07,738 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:14:22,075 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:14:22,077 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:14:22,164 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:14:22,174 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:14:22,177 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:14:22,187 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:14:22,202 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:14:22,217 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:15:32,292 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:15:32,294 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:15:32,522 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:15:32,549 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:15:32,554 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:15:32,606 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:15:32,627 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:15:32,639 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:16:29,778 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:16:29,779 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:16:29,860 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:16:29,870 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:16:29,873 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:16:29,882 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:16:29,897 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:16:29,910 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:17:34,551 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:17:34,553 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:17:34,635 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:17:34,645 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:17:34,648 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:17:34,658 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:17:34,673 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:17:34,680 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:18:30,033 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:18:30,034 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:18:30,121 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:18:30,133 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:18:30,146 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:18:30,177 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:18:30,198 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:18:30,213 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:19:44,351 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:19:44,353 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:19:44,444 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:19:44,455 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:19:44,458 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:19:44,468 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: TabNetModel

2025-04-25 18:19:44,483 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:19:44,491 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type             ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _embedding_layer │ Identity         │      0 │ train │
│ 1 │ _backbone        │ TabNetBackbone   │  3.0 K │ train │
│ 2 │ _head            │ Identity         │      0 │ train │
│ 3 │ loss             │ CrossEntropyLoss │      0 │ train │
└───┴──────────────────┴──────────────────┴────────┴───────┘

Trainable params: 3.0 K
Non-trainable params: 0
Total params: 3.0 K
Total estimated model params size (MB): 0
Modules in train mode: 78
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:20:38,638 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:20:38,642 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             TabNetModel_no_fragmentation_smotenc_first_launch
holdout_test_f1_macro                                                      0.874582
holdout_test_accuracy_balanced                                             0.911364
holdout_test_roc_auc                                                           0.96
holdout_test_f1                                                            0.826087
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.820946
cv_test_accuracy_balanced_median                                           0.858974
cv_test_roc_auc_median                                                     0.919414
cv_test_f1_median                                                              0.75
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.944444
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.891892

Model saved in ../results/models_modelling4/TabNetModel_no_fragmentation_smotenc_first_launch