Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-smote_default-model'
add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
n_trials = 50

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=best_params,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )
    
    
def optimize_smote_grid(
    target:str,
    estimator:object,
    estimator_params:dict,
    param_grid:dict=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters with GridSearchOptimizer for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )
    
    if param_grid is None:
        param_grid = {
        'sampling_strategy': [0.6, 0.7, 0.8, 0.9, 1.0],
        'k_neighbors': list(range(3,11)),
    }
    opt = GridSearchOptimizer(
        objective=partial(pure_smote_objective, ml_pipe=ml_pipe),
        param_grid=param_grid,
        verbose=True,
    )

    opt.optimize()
    best_params = opt.best_params

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=best_params,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [ ]:
estimator_class = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    n_trials=n_trials,
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-11 16:46:23,656] A new study created in memory with name: smote_study
[I 2025-04-11 16:46:23,727] Trial 0 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.7795918367346939.
[I 2025-04-11 16:46:23,795] Trial 1 finished with value: 0.7826336975273146 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.7826336975273146.
[I 2025-04-11 16:46:23,863] Trial 2 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 2 with value: 0.800925925925926.
[I 2025-04-11 16:46:23,931] Trial 3 finished with value: 0.7826336975273146 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 2 with value: 0.800925925925926.
[I 2025-04-11 16:46:23,999] Trial 4 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,065] Trial 5 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,133] Trial 6 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,200] Trial 7 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,268] Trial 8 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,334] Trial 9 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,403] Trial 10 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,471] Trial 11 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,540] Trial 12 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,612] Trial 13 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,683] Trial 14 finished with value: 0.7980769230769231 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,755] Trial 15 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,827] Trial 16 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,898] Trial 17 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:24,968] Trial 18 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:25,038] Trial 19 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:25,182] Trial 20 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:25,254] Trial 21 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-11 16:46:25,324] Trial 22 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,394] Trial 23 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,463] Trial 24 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,533] Trial 25 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,602] Trial 26 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,672] Trial 27 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,745] Trial 28 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,817] Trial 29 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,890] Trial 30 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:25,961] Trial 31 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,029] Trial 32 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,098] Trial 33 finished with value: 0.7888707037643208 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,166] Trial 34 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,237] Trial 35 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,308] Trial 36 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,393] Trial 37 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,465] Trial 38 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,534] Trial 39 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,606] Trial 40 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,677] Trial 41 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,750] Trial 42 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,821] Trial 43 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,890] Trial 44 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:26,960] Trial 45 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:27,030] Trial 46 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:27,102] Trial 47 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:27,174] Trial 48 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-11 16:46:27,315] Trial 49 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9}. Best is trial 22 with value: 0.8088888888888889.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.6}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.883488
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

In [7]:
estimator_class = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   0%|          | 0/40 [00:00<?, ?it/s]

Progress: 1/40.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:02, 13.93it/s]

Progress: 2/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 3/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:00<00:02, 14.46it/s]

Progress: 4/40.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.
Progress: 5/40.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:00<00:02, 12.05it/s]

Progress: 6/40.	Score: 0.8023529411764707.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  20%|██        | 8/40 [00:00<00:02, 13.08it/s]

Progress: 7/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 8/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 9/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:00<00:02, 13.70it/s]

Progress: 10/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  30%|███       | 12/40 [00:00<00:01, 14.15it/s]

Progress: 11/40.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 12/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.
Progress: 13/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:01<00:01, 14.38it/s]

Progress: 14/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.
Progress: 15/40.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [00:01<00:01, 14.44it/s]

Progress: 16/40.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 17/40.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  45%|████▌     | 18/40 [00:01<00:01, 14.40it/s]

Progress: 18/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 19/40.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  50%|█████     | 20/40 [00:01<00:01, 14.41it/s]

Progress: 20/40.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 21/40.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:01<00:01, 14.40it/s]

Progress: 22/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 23/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  60%|██████    | 24/40 [00:01<00:01, 12.51it/s]

Progress: 24/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 25/40.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:01<00:01, 12.98it/s]

Progress: 26/40.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 28/40 [00:02<00:00, 12.99it/s]

Progress: 27/40.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 28/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  75%|███████▌  | 30/40 [00:02<00:00, 13.31it/s]

Progress: 30/40.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 31/40.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  80%|████████  | 32/40 [00:02<00:00, 13.66it/s]

Progress: 32/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 34/40 [00:02<00:00, 13.94it/s]

Progress: 33/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 34/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  95%|█████████▌| 38/40 [00:02<00:00, 13.04it/s]

Progress: 35/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 36/40.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 37/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 38/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters: 100%|██████████| 40/40 [00:02<00:00, 13.51it/s]

Progress: 39/40.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 40/40.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.8088888888888889
Best params: {'k_neighbors': 9, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.883488
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

Model saved in ../results/models_modelling4/LogisticRegression_splashing_smote_opt-smote_default-model

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator_class = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:02, 16.47it/s]

Progress: 1/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 2/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 3/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:00<00:02, 16.81it/s]

Progress: 4/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  15%|█▌        | 6/40 [00:00<00:02, 16.76it/s]

Progress: 5/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 6/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 7/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  25%|██▌       | 10/40 [00:00<00:02, 14.97it/s]

Progress: 8/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 9/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.
Progress: 10/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 11/40.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  35%|███▌      | 14/40 [00:00<00:01, 15.71it/s]

Progress: 12/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.
Progress: 13/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 14/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.
Progress: 15/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  45%|████▌     | 18/40 [00:01<00:01, 16.47it/s]

Progress: 16/40.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 17/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 18/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 19/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:01<00:01, 16.64it/s]

Progress: 20/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 21/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 22/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 23/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:01<00:00, 16.84it/s]

Progress: 24/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 25/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 26/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 27/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  75%|███████▌  | 30/40 [00:01<00:00, 16.98it/s]

Progress: 28/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.
Progress: 30/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  85%|████████▌ | 34/40 [00:02<00:00, 15.27it/s]

Progress: 31/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 32/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.
Progress: 33/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 34/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  95%|█████████▌| 38/40 [00:02<00:00, 16.20it/s]

Progress: 35/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 36/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 37/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 38/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters: 100%|██████████| 40/40 [00:02<00:00, 16.04it/s]

Progress: 39/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 40/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.8346153846153845
Best params: {'k_neighbors': 6, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.785539
holdout_test_accuracy_balanced                                                0.825
holdout_test_roc_auc                                                           0.95
holdout_test_f1                                                            0.708333
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.869231
cv_test_roc_auc_median                                                     0.946886
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.820513
cv_test_f1_class_0_median                                                  0.888889

Model saved in ../results/models_modelling4/LogisticRegression_no_fragmentation_smote_opt-smote_default-model

# KNClassifier

In [9]:
estimator_class = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:00<00:06,  5.90it/s]

Progress: 1/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   8%|▊         | 3/40 [00:00<00:04,  8.62it/s]

Progress: 2/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 3/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 4/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:00<00:03,  9.48it/s]

Progress: 5/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 6/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  22%|██▎       | 9/40 [00:00<00:03,  9.84it/s]

Progress: 7/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 8/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 9/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  28%|██▊       | 11/40 [00:01<00:02, 10.09it/s]

Progress: 10/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 11/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 12/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  38%|███▊      | 15/40 [00:01<00:02, 10.29it/s]

Progress: 13/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 14/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.
Progress: 15/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  42%|████▎     | 17/40 [00:01<00:02, 10.28it/s]

Progress: 16/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 17/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 18/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▎    | 21/40 [00:02<00:01, 10.29it/s]

Progress: 19/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 20/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 21/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  57%|█████▊    | 23/40 [00:02<00:01, 10.24it/s]

Progress: 22/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 23/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 24/40.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:02<00:01,  9.36it/s]

Progress: 25/40.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 26/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  72%|███████▎  | 29/40 [00:02<00:01,  9.67it/s]

Progress: 27/40.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 28/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 31/40 [00:03<00:00,  9.92it/s]

Progress: 30/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 31/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 32/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  88%|████████▊ | 35/40 [00:03<00:00, 10.07it/s]

Progress: 33/40.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 34/40.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 35/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  92%|█████████▎| 37/40 [00:03<00:00, 10.18it/s]

Progress: 36/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 37/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 38/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters: 100%|██████████| 40/40 [00:04<00:00,  9.90it/s]

Progress: 39/40.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 40/40.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.8683385579937304
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smote_opt-smote...
holdout_test_f1_macro                                                      0.810348
holdout_test_accuracy_balanced                                              0.80787
holdout_test_roc_auc                                                       0.874228
holdout_test_f1                                                            0.865979
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.835913
cv_test_accuracy_balanced_median                                           0.844427
cv_test_roc_auc_median                                                     0.918731
cv_test_f1_median                                                          0.882353
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                               0.75
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.790698

Model saved in ../results/models_modelling4/KNeighborsClassifier_splashing_smote_opt-smote_default-model

In [10]:
estimator_class = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:03, 11.39it/s]

Progress: 1/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 2/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 3/40.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:00<00:03, 11.52it/s]

Progress: 4/40.	Score: 0.7658802177858439.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.
Progress: 5/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:00<00:02, 11.56it/s]

Progress: 6/40.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  20%|██        | 8/40 [00:00<00:02, 11.56it/s]

Progress: 7/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 8/40.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 9/40.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:00<00:02, 11.45it/s]

Progress: 10/40.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 11/40.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  30%|███       | 12/40 [00:01<00:02, 11.41it/s]

Progress: 12/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  35%|███▌      | 14/40 [00:01<00:02, 11.32it/s]

Progress: 13/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 14/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  40%|████      | 16/40 [00:01<00:02, 10.01it/s]

Progress: 15/40.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 16/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 17/40.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 20/40 [00:01<00:01, 10.67it/s]

Progress: 18/40.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 19/40.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 20/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:02<00:01, 10.93it/s]

Progress: 21/40.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 22/40.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 23/40.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:02<00:01, 11.37it/s]

Progress: 24/40.	Score: 0.7904490377761939.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 25/40.	Score: 0.8089668615984404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 26/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 28/40 [00:02<00:01, 11.23it/s]

Progress: 27/40.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 28/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  80%|████████  | 32/40 [00:02<00:00, 11.25it/s]

Progress: 30/40.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 31/40.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 32/40.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 34/40 [00:03<00:00, 11.30it/s]

Progress: 33/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 34/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 35/40.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  95%|█████████▌| 38/40 [00:03<00:00, 11.42it/s]

Progress: 36/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 37/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 38/40.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters: 100%|██████████| 40/40 [00:03<00:00, 10.92it/s]

Progress: 39/40.	Score: 0.8464285714285714.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 40/40.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.8699334543254689
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.780518
holdout_test_accuracy_balanced                                             0.809091
holdout_test_roc_auc                                                       0.937273
holdout_test_f1                                                            0.695652
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.928571
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.918919

Model saved in ../results/models_modelling4/KNeighborsClassifier_no_fragmentation_smote_opt-smote_default-model

# SVC

In [11]:
estimator_class = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:00<00:06,  5.90it/s]

Progress: 1/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:04,  7.62it/s]

Progress: 2/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:   8%|▊         | 3/40 [00:00<00:04,  8.39it/s]

Progress: 3/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:00<00:04,  8.70it/s]

Progress: 4/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:00<00:03,  8.77it/s]

Progress: 5/40.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  18%|█▊        | 7/40 [00:00<00:03,  9.34it/s]

Progress: 6/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 7/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  22%|██▎       | 9/40 [00:01<00:03,  9.32it/s]

Progress: 8/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 9/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  30%|███       | 12/40 [00:01<00:02,  9.61it/s]

Progress: 10/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 11/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 12/40.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  35%|███▌      | 14/40 [00:01<00:02,  9.43it/s]

Progress: 13/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 14/40.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  40%|████      | 16/40 [00:01<00:02,  8.10it/s]

Progress: 15/40.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 16/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  45%|████▌     | 18/40 [00:02<00:02,  8.81it/s]

Progress: 17/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 18/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  50%|█████     | 20/40 [00:02<00:02,  8.65it/s]

Progress: 19/40.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 20/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  57%|█████▊    | 23/40 [00:02<00:01,  9.40it/s]

Progress: 21/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 22/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 23/40.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  62%|██████▎   | 25/40 [00:02<00:01,  9.33it/s]

Progress: 24/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 25/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  68%|██████▊   | 27/40 [00:02<00:01,  9.68it/s]

Progress: 26/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 27/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▎  | 29/40 [00:03<00:01,  9.53it/s]

Progress: 28/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 31/40 [00:03<00:01,  8.17it/s]

Progress: 30/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 31/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  82%|████████▎ | 33/40 [00:03<00:00,  8.83it/s]

Progress: 32/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.
Progress: 33/40.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  88%|████████▊ | 35/40 [00:03<00:00,  8.94it/s]

Progress: 34/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 35/40.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  92%|█████████▎| 37/40 [00:04<00:00,  9.49it/s]

Progress: 36/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 37/40.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  98%|█████████▊| 39/40 [00:04<00:00,  9.48it/s]

Progress: 38/40.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 39/40.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 40/40 [00:04<00:00,  9.09it/s]

Progress: 40/40.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.875222816399287
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                            0
target                                                              splashing
model                             SVC_splashing_smote_opt-smote_default-model
holdout_test_f1_macro                                                0.793956
holdout_test_accuracy_balanced                                       0.789352
holdout_test_roc_auc                                                 0.893519
holdout_test_f1                                                      0.857143
holdout_test_accuracy                                                0.813333
cv_test_f1_macro_median                                              0.863049
cv_test_accuracy_balanced_median                                     0.885449
cv_test_roc_auc_median                                               0.922601
cv_test_f1_median                                                    0.888889
cv_test_accuracy_median                                              0.867925
cv_test_precision_class_0_median                                         0.75
cv_test_recall_class_0_median                                        0.894737
cv_test_f1_class_0_median                                            0.837209

Model saved in ../results/models_modelling4/SVC_splashing_smote_opt-smote_default-model

In [12]:
estimator_class = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▎         | 1/40 [00:00<00:06,  6.27it/s]

Progress: 1/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   8%|▊         | 3/40 [00:00<00:04,  8.89it/s]

Progress: 2/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 3/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:00<00:03,  9.17it/s]

Progress: 4/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:00<00:03,  9.27it/s]

Progress: 5/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 6/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  18%|█▊        | 7/40 [00:00<00:03,  9.92it/s]

Progress: 7/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  20%|██        | 8/40 [00:00<00:03,  9.81it/s]

Progress: 8/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  22%|██▎       | 9/40 [00:00<00:03,  9.70it/s]

Progress: 9/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:01<00:03,  9.52it/s]

Progress: 10/40.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  30%|███       | 12/40 [00:01<00:02, 10.01it/s]

Progress: 11/40.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 12/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.
Progress: 13/40.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:01<00:02, 10.04it/s]

Progress: 14/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  38%|███▊      | 15/40 [00:01<00:02,  9.91it/s]

Progress: 15/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [00:01<00:02,  8.78it/s]

Progress: 16/40.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  42%|████▎     | 17/40 [00:01<00:02,  8.89it/s]

Progress: 17/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  48%|████▊     | 19/40 [00:02<00:02,  9.32it/s]

Progress: 18/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 19/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:02<00:01,  9.77it/s]

Progress: 20/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 21/40.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 22/40.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  60%|██████    | 24/40 [00:02<00:01,  9.85it/s]

Progress: 23/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 24/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  68%|██████▊   | 27/40 [00:02<00:01, 10.15it/s]

Progress: 25/40.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 26/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 27/40.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▎  | 29/40 [00:03<00:01, 10.10it/s]

Progress: 28/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 29/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 31/40 [00:03<00:00, 10.16it/s]

Progress: 30/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 31/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 32/40.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  82%|████████▎ | 33/40 [00:03<00:00, 10.27it/s]

Progress: 33/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 34/40.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  88%|████████▊ | 35/40 [00:03<00:00, 10.14it/s]

Progress: 35/40.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 36/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  98%|█████████▊| 39/40 [00:04<00:00,  9.60it/s]

Progress: 37/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 38/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 39/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 40/40 [00:04<00:00,  9.64it/s]

Progress: 40/40.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.8650345260514751
Best params: {'k_neighbors': 9, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smote_opt-smote_default-m...
holdout_test_f1_macro                                                      0.857143
holdout_test_accuracy_balanced                                             0.886364
holdout_test_roc_auc                                                           0.95
holdout_test_f1                                                                 0.8
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                           0.877289
cv_test_roc_auc_median                                                     0.947802
cv_test_f1_median                                                               0.8
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.901408

Model saved in ../results/models_modelling4/SVC_no_fragmentation_smote_opt-smote_default-model

# CatBoost

In [13]:
estimator_class = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:03<02:33,  3.93s/it]

Progress: 1/40.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:08<02:34,  4.06s/it]

Progress: 2/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:   8%|▊         | 3/40 [00:12<02:32,  4.13s/it]

Progress: 3/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:16<02:32,  4.23s/it]

Progress: 4/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:21<02:30,  4.31s/it]

Progress: 5/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:25<02:21,  4.17s/it]

Progress: 6/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  18%|█▊        | 7/40 [00:29<02:17,  4.17s/it]

Progress: 7/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  20%|██        | 8/40 [00:33<02:13,  4.18s/it]

Progress: 8/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  22%|██▎       | 9/40 [00:37<02:11,  4.24s/it]

Progress: 9/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:42<02:09,  4.30s/it]

Progress: 10/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  28%|██▊       | 11/40 [00:46<02:01,  4.20s/it]

Progress: 11/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  30%|███       | 12/40 [00:50<01:56,  4.17s/it]

Progress: 12/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  32%|███▎      | 13/40 [00:54<01:53,  4.21s/it]

Progress: 13/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:58<01:49,  4.22s/it]

Progress: 14/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  38%|███▊      | 15/40 [01:03<01:47,  4.32s/it]

Progress: 15/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [01:07<01:41,  4.24s/it]

Progress: 16/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  42%|████▎     | 17/40 [01:11<01:37,  4.26s/it]

Progress: 17/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  45%|████▌     | 18/40 [01:15<01:33,  4.24s/it]

Progress: 18/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  48%|████▊     | 19/40 [01:20<01:29,  4.26s/it]

Progress: 19/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  50%|█████     | 20/40 [01:24<01:26,  4.30s/it]

Progress: 20/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  52%|█████▎    | 21/40 [01:28<01:21,  4.27s/it]

Progress: 21/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  55%|█████▌    | 22/40 [01:32<01:15,  4.20s/it]

Progress: 22/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  57%|█████▊    | 23/40 [01:37<01:11,  4.21s/it]

Progress: 23/40.	Score: 0.9004629629629629.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  60%|██████    | 24/40 [01:41<01:07,  4.22s/it]

Progress: 24/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  62%|██████▎   | 25/40 [01:45<01:04,  4.33s/it]

Progress: 25/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  65%|██████▌   | 26/40 [01:49<00:59,  4.23s/it]

Progress: 26/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  68%|██████▊   | 27/40 [01:53<00:53,  4.11s/it]

Progress: 27/40.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  70%|███████   | 28/40 [01:57<00:47,  3.97s/it]

Progress: 28/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  72%|███████▎  | 29/40 [02:01<00:43,  3.92s/it]

Progress: 29/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  75%|███████▌  | 30/40 [02:05<00:39,  3.94s/it]

Progress: 30/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 31/40 [02:08<00:34,  3.84s/it]

Progress: 31/40.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  80%|████████  | 32/40 [02:12<00:30,  3.78s/it]

Progress: 32/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  82%|████████▎ | 33/40 [02:16<00:26,  3.81s/it]

Progress: 33/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 34/40 [02:20<00:22,  3.82s/it]

Progress: 34/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  88%|████████▊ | 35/40 [02:24<00:19,  3.88s/it]

Progress: 35/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  90%|█████████ | 36/40 [02:27<00:15,  3.79s/it]

Progress: 36/40.	Score: 0.9004629629629629.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  92%|█████████▎| 37/40 [02:31<00:11,  3.75s/it]

Progress: 37/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  95%|█████████▌| 38/40 [02:35<00:07,  3.73s/it]

Progress: 38/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  98%|█████████▊| 39/40 [02:38<00:03,  3.77s/it]

Progress: 39/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 40/40 [02:43<00:00,  4.08s/it]

Progress: 40/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.9004629629629629
Best params: {'k_neighbors': 7, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                          0.85
holdout_test_accuracy_balanced                                              0.83912
holdout_test_roc_auc                                                       0.946759
holdout_test_f1                                                                 0.9
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.860788
cv_test_accuracy_balanced_median                                           0.873839
cv_test_roc_auc_median                                                      0.95356
cv_test_f1_median                                                          0.898551
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.833333
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.829268

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smote_opt-smote_default-model

In [14]:
estimator_class = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smotenc_de...
holdout_test_f1_macro                                                      0.916089
holdout_test_accuracy_balanced                                             0.922727
holdout_test_roc_auc                                                       0.984545
holdout_test_f1                                                            0.878049
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.881326
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                      0.97265
cv_test_f1_median                                                          0.827586
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                               0.95
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smotenc_default

# XGBoost

In [15]:
estimator_class = XGBClassifier
target = 'splashing'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                        0
target                                                          splashing
model                             XGBClassifier_splashing_smotenc_default
holdout_test_f1_macro                                                0.88
holdout_test_accuracy_balanced                                   0.868056
holdout_test_roc_auc                                             0.932485
holdout_test_f1                                                      0.92
holdout_test_accuracy                                            0.893333
cv_test_f1_macro_median                                          0.876935
cv_test_accuracy_balanced_median                                 0.876935
cv_test_roc_auc_median                                           0.946032
cv_test_f1_median                                                0.909091
cv_test_accuracy_median                                          0.886792
cv_test_precision_class_0_median                                 0.809524
cv_test_recall_class_0_median                                    0.894737
cv_test_f1_class_0_median                                        0.842105

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smotenc_default

In [16]:
estimator_class = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                               0
target                                                          no_fragmentation
model                             XGBClassifier_no_fragmentation_smotenc_default
holdout_test_f1_macro                                                   0.885894
holdout_test_accuracy_balanced                                          0.904545
holdout_test_roc_auc                                                    0.988182
holdout_test_f1                                                         0.837209
holdout_test_accuracy                                                   0.906667
cv_test_f1_macro_median                                                 0.875762
cv_test_accuracy_balanced_median                                        0.877289
cv_test_roc_auc_median                                                  0.967033
cv_test_f1_median                                                       0.814815
cv_test_accuracy_median                                                  0.90566
cv_test_precision_class_0_median                                        0.926829
cv_test_recall_class_0_median                                           0.948718
cv_test_f1_class_0_median                                               0.936709

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smotenc_default

# AdaBoost

In [14]:
estimator_class = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:00<00:12,  3.18it/s]

Progress: 1/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:10,  3.60it/s]

Progress: 2/40.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:   8%|▊         | 3/40 [00:00<00:09,  3.72it/s]

Progress: 3/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:01<00:09,  3.77it/s]

Progress: 4/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:01<00:09,  3.77it/s]

Progress: 5/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:01<00:08,  3.82it/s]

Progress: 6/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  18%|█▊        | 7/40 [00:01<00:08,  3.86it/s]

Progress: 7/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  20%|██        | 8/40 [00:02<00:08,  3.83it/s]

Progress: 8/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  22%|██▎       | 9/40 [00:02<00:08,  3.83it/s]

Progress: 9/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:02<00:07,  3.81it/s]

Progress: 10/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  28%|██▊       | 11/40 [00:02<00:08,  3.61it/s]

Progress: 11/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  30%|███       | 12/40 [00:03<00:07,  3.71it/s]

Progress: 12/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  32%|███▎      | 13/40 [00:03<00:07,  3.75it/s]

Progress: 13/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:03<00:06,  3.77it/s]

Progress: 14/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  38%|███▊      | 15/40 [00:03<00:06,  3.79it/s]

Progress: 15/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [00:04<00:06,  3.84it/s]

Progress: 16/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  42%|████▎     | 17/40 [00:04<00:05,  3.87it/s]

Progress: 17/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  45%|████▌     | 18/40 [00:04<00:05,  3.89it/s]

Progress: 18/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  48%|████▊     | 19/40 [00:05<00:05,  3.88it/s]

Progress: 19/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  50%|█████     | 20/40 [00:05<00:05,  3.84it/s]

Progress: 20/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  52%|█████▎    | 21/40 [00:05<00:04,  3.88it/s]

Progress: 21/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:05<00:04,  3.90it/s]

Progress: 22/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  57%|█████▊    | 23/40 [00:06<00:04,  3.90it/s]

Progress: 23/40.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  60%|██████    | 24/40 [00:06<00:04,  3.71it/s]

Progress: 24/40.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  62%|██████▎   | 25/40 [00:06<00:04,  3.73it/s]

Progress: 25/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:06<00:03,  3.81it/s]

Progress: 26/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  68%|██████▊   | 27/40 [00:07<00:03,  3.85it/s]

Progress: 27/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  70%|███████   | 28/40 [00:07<00:03,  3.86it/s]

Progress: 28/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  72%|███████▎  | 29/40 [00:07<00:02,  3.87it/s]

Progress: 29/40.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  75%|███████▌  | 30/40 [00:07<00:02,  3.84it/s]

Progress: 30/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 31/40 [00:08<00:02,  3.88it/s]

Progress: 31/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  80%|████████  | 32/40 [00:08<00:02,  3.90it/s]

Progress: 32/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  82%|████████▎ | 33/40 [00:08<00:01,  3.87it/s]

Progress: 33/40.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 34/40 [00:08<00:01,  3.85it/s]

Progress: 34/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  88%|████████▊ | 35/40 [00:09<00:01,  3.81it/s]

Progress: 35/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  90%|█████████ | 36/40 [00:09<00:01,  3.84it/s]

Progress: 36/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  92%|█████████▎| 37/40 [00:09<00:00,  3.71it/s]

Progress: 37/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  95%|█████████▌| 38/40 [00:09<00:00,  3.74it/s]

Progress: 38/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  98%|█████████▊| 39/40 [00:10<00:00,  3.76it/s]

Progress: 39/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 40/40 [00:10<00:00,  3.80it/s]

Progress: 40/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.873900293255132
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.751994
holdout_test_accuracy_balanced                                                 0.75
holdout_test_roc_auc                                                       0.854552
holdout_test_f1                                                            0.824742
holdout_test_accuracy                                                      0.773333
cv_test_f1_macro_median                                                    0.794892
cv_test_accuracy_balanced_median                                           0.794892
cv_test_roc_auc_median                                                     0.891641
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.736842
cv_test_recall_class_0_median                                              0.736842
cv_test_f1_class_0_median                                                  0.736842

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smote_opt-smote_default-model

In [18]:
estimator_class = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_de...
holdout_test_f1_macro                                                      0.839194
holdout_test_accuracy_balanced                                             0.861364
holdout_test_roc_auc                                                       0.951364
holdout_test_f1                                                            0.772727
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.826067
cv_test_accuracy_balanced_median                                           0.823077
cv_test_roc_auc_median                                                     0.930403
cv_test_f1_median                                                          0.740741
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.916667
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.911392

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smotenc_default

# Random Forest

In [15]:
estimator_class = RandomForestClassifier
target = 'splashing'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:00<00:18,  2.14it/s]

Progress: 1/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:00<00:18,  2.03it/s]

Progress: 2/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:   8%|▊         | 3/40 [00:01<00:17,  2.07it/s]

Progress: 3/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:01<00:17,  2.08it/s]

Progress: 4/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:02<00:16,  2.09it/s]

Progress: 5/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:02<00:16,  2.12it/s]

Progress: 6/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  18%|█▊        | 7/40 [00:03<00:15,  2.14it/s]

Progress: 7/40.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  20%|██        | 8/40 [00:03<00:14,  2.14it/s]

Progress: 8/40.	Score: 0.9004629629629629.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  22%|██▎       | 9/40 [00:04<00:14,  2.14it/s]

Progress: 9/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:04<00:14,  2.13it/s]

Progress: 10/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  28%|██▊       | 11/40 [00:05<00:13,  2.15it/s]

Progress: 11/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  30%|███       | 12/40 [00:05<00:13,  2.15it/s]

Progress: 12/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  32%|███▎      | 13/40 [00:06<00:12,  2.14it/s]

Progress: 13/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:06<00:12,  2.13it/s]

Progress: 14/40.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  38%|███▊      | 15/40 [00:07<00:12,  2.07it/s]

Progress: 15/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [00:07<00:11,  2.10it/s]

Progress: 16/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  42%|████▎     | 17/40 [00:08<00:10,  2.12it/s]

Progress: 17/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  45%|████▌     | 18/40 [00:08<00:10,  2.12it/s]

Progress: 18/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  48%|████▊     | 19/40 [00:08<00:09,  2.11it/s]

Progress: 19/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  50%|█████     | 20/40 [00:09<00:09,  2.10it/s]

Progress: 20/40.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  52%|█████▎    | 21/40 [00:09<00:08,  2.13it/s]

Progress: 21/40.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:10<00:08,  2.13it/s]

Progress: 22/40.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  57%|█████▊    | 23/40 [00:10<00:07,  2.13it/s]

Progress: 23/40.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  60%|██████    | 24/40 [00:11<00:07,  2.13it/s]

Progress: 24/40.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  62%|██████▎   | 25/40 [00:11<00:07,  2.11it/s]

Progress: 25/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:12<00:06,  2.13it/s]

Progress: 26/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  68%|██████▊   | 27/40 [00:12<00:06,  2.05it/s]

Progress: 27/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  70%|███████   | 28/40 [00:13<00:05,  2.07it/s]

Progress: 28/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  72%|███████▎  | 29/40 [00:13<00:05,  2.06it/s]

Progress: 29/40.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  75%|███████▌  | 30/40 [00:14<00:04,  2.06it/s]

Progress: 30/40.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 31/40 [00:14<00:04,  2.09it/s]

Progress: 31/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  80%|████████  | 32/40 [00:15<00:03,  2.10it/s]

Progress: 32/40.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  82%|████████▎ | 33/40 [00:15<00:03,  2.11it/s]

Progress: 33/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 34/40 [00:16<00:02,  2.11it/s]

Progress: 34/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  88%|████████▊ | 35/40 [00:16<00:02,  2.05it/s]

Progress: 35/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  90%|█████████ | 36/40 [00:17<00:01,  2.09it/s]

Progress: 36/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  92%|█████████▎| 37/40 [00:17<00:01,  2.10it/s]

Progress: 37/40.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  95%|█████████▌| 38/40 [00:18<00:00,  2.11it/s]

Progress: 38/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  98%|█████████▊| 39/40 [00:18<00:00,  2.11it/s]

Progress: 39/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 40/40 [00:18<00:00,  2.11it/s]

Progress: 40/40.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
-------------------------------------------------------------------------------------
Best score: 0.9004629629629629
Best params: {'k_neighbors': 4, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smote_opt-smo...
holdout_test_f1_macro                                                          0.82
holdout_test_accuracy_balanced                                             0.810185
holdout_test_roc_auc                                                       0.943673
holdout_test_f1                                                                0.88
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.876935
cv_test_roc_auc_median                                                     0.947619
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.842105

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smote_opt-smote_default-model

In [20]:
estimator_class = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.885894
holdout_test_accuracy_balanced                                             0.904545
holdout_test_roc_auc                                                           0.99
holdout_test_f1                                                            0.837209
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.954701
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smotenc_default

# LightGBM

In [7]:
estimator_class = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▎         | 1/40 [00:01<00:50,  1.30s/it]

Progress: 1/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:   5%|▌         | 2/40 [00:02<00:46,  1.24s/it]

Progress: 2/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:   8%|▊         | 3/40 [00:03<00:48,  1.30s/it]

Progress: 3/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  10%|█         | 4/40 [00:05<00:47,  1.32s/it]

Progress: 4/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  12%|█▎        | 5/40 [00:06<00:47,  1.37s/it]

Progress: 5/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▌        | 6/40 [00:07<00:44,  1.31s/it]

Progress: 6/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  18%|█▊        | 7/40 [00:09<00:43,  1.32s/it]

Progress: 7/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  20%|██        | 8/40 [00:10<00:41,  1.29s/it]

Progress: 8/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  22%|██▎       | 9/40 [00:11<00:40,  1.30s/it]

Progress: 9/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  25%|██▌       | 10/40 [00:13<00:40,  1.34s/it]

Progress: 10/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  28%|██▊       | 11/40 [00:14<00:37,  1.29s/it]

Progress: 11/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  30%|███       | 12/40 [00:15<00:36,  1.29s/it]

Progress: 12/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  32%|███▎      | 13/40 [00:17<00:36,  1.34s/it]

Progress: 13/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  35%|███▌      | 14/40 [00:18<00:36,  1.40s/it]

Progress: 14/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  38%|███▊      | 15/40 [00:19<00:34,  1.38s/it]

Progress: 15/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  40%|████      | 16/40 [00:21<00:31,  1.31s/it]

Progress: 16/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  42%|████▎     | 17/40 [00:22<00:28,  1.24s/it]

Progress: 17/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  45%|████▌     | 18/40 [00:23<00:27,  1.26s/it]

Progress: 18/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  48%|████▊     | 19/40 [00:24<00:26,  1.28s/it]

Progress: 19/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  50%|█████     | 20/40 [00:26<00:27,  1.37s/it]

Progress: 20/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  52%|█████▎    | 21/40 [00:27<00:25,  1.32s/it]

Progress: 21/40.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  55%|█████▌    | 22/40 [00:28<00:23,  1.30s/it]

Progress: 22/40.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  57%|█████▊    | 23/40 [00:30<00:22,  1.31s/it]

Progress: 23/40.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  60%|██████    | 24/40 [00:31<00:21,  1.34s/it]

Progress: 24/40.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  62%|██████▎   | 25/40 [00:33<00:20,  1.37s/it]

Progress: 25/40.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  65%|██████▌   | 26/40 [00:34<00:18,  1.31s/it]

Progress: 26/40.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  68%|██████▊   | 27/40 [00:35<00:16,  1.30s/it]

Progress: 27/40.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  70%|███████   | 28/40 [00:36<00:15,  1.33s/it]

Progress: 28/40.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  70%|███████   | 28/40 [00:37<00:16,  1.35s/it]

KeyboardInterrupt:

In [22]:
estimator_class = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

estimator = estimator_class(
    **estimator_params
)

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[LightGBM] [Info] Number of positive: 234, number of negative: 234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000350 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 746
[LightGBM] [Info] Number of data points in the train set: 468, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 234, number of negative: 234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000312 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 747
[LightGBM] [Info] Number of data points in the train set: 468, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Number of positive: 234, number of negative: 234
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000323 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 752
[LightGBM] [Info] Number of data points in the train set: 468, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

                                                                                0
target                                                           no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_default
holdout_test_f1_macro                                                    0.916089
holdout_test_accuracy_balanced                                           0.922727
holdout_test_roc_auc                                                     0.986364
holdout_test_f1                                                          0.878049
holdout_test_accuracy                                                    0.933333
cv_test_f1_macro_median                                                  0.886022
cv_test_accuracy_balanced_median                                          0.90293
cv_test_roc_auc_median                                                   0.974359
cv_test_f1_median                                                         0.83871
cv_test_accuracy_median                                                   0.90566
cv_test_precision_class_0_median                                         0.948718
cv_test_recall_class_0_median                                            0.923077
cv_test_f1_class_0_median                                                0.935065

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smotenc_default

# For the notebook with Model optimization!

In [ ]:
# def update_estimator_params(
#     ml_pipe:MLPipeline,
#     suggested_params:dict,
# ) -> dict:
#     """Update the estimator parameters based on the pipeline parameters.

#     Args:
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.
#         suggested_params: A dictionary containing the suggested Estimator hyperparameters.
    
#     Returns:
#         A dictionary containing the estimator parameters.
#     """
#     estimator_params = ml_pipe._pipeline_params['estimator_params']
#     estimator_params.update(suggested_params)
#     return estimator_params

# def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
#     """Objective function for logistic regression optimization using Optuna.

#     Args:
#         trial: An Optuna trial object used to suggest hyperparameters.
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.

#     Returns:
#         The score of the model based on the specified evaluation metric.
#     """
    
#     categorical_features = ('wettability', 'inclination')
    
#     random_state = ml_pipe._pipeline_params['random_state']
    
#     # sample params
#     C = trial.suggest_loguniform('C', 1e-4, 1e3)
    
#     # SMOTE params
#     add_smote = trial.suggest_categorical('add_smote', [True, False])
#     if add_smote:
#         is_smotenc = trial.suggest_categorical('is_smotenc', [True, False])
#         smote_params = {
#             'sampling_strategy': trial.suggest_categorical(
#                 'sampling_strategy', [0.6, 0.7, 0.8, 0.9, 1.0]
#             ),
#             'k_neighbors': trial.suggest_int('k_neighbors', 3, 10),
#             'random_state': random_state,
#         }
#     else:
#         is_smotenc = False
#         smote_params = None
#     if is_smotenc:
#         wettability_cat = trial.suggest_categorical('wettability_cat', [True, False])
#         if wettability_cat:
#             inclination_cat = trial.suggest_categorical('inclination_cat', [True, False])
#         else:
#             inclination_cat = True
        
        
#         mask = [wettability_cat, inclination_cat]
        
#         masked_features = [
#             feature for feature, mask_value in zip(categorical_features, mask) 
#             if mask_value
#         ]
#         smote_params = {
#             **smote_params,
#             'categorical_features': masked_features,
#         }

#     suggested_params = {
#         "C": C,
#     }
    
#     estimator_params = update_estimator_params(ml_pipe, suggested_params)

#     estimator = LogisticRegression(
#         **estimator_params,
#         random_state=random_state,
#     )

#     score = ml_pipe.step(
#         estimator=estimator,
#         add_smote=add_smote,
#         is_smotenc=is_smotenc,
#         smote_params=smote_params,
#     )
    
#     return score



# opt = OptunaOptimizer(
#     objective=partial(logreg_objective, ml_pipe=ml_pipe),
#     study_name="logreg_study",
#     direction="maximize",
# )

# opt.optimize(n_trials=200)

# best_params = opt.study.best_trial.params
# display(best_params)
# # estimator_params = update_estimator_params(ml_pipe, best_params)

# # estimator = LogisticRegression(
# #     **estimator_params,
# #     random_state=ml_pipe._pipeline_params['random_state'],
# # )

[I 2025-04-11 00:02:50,034] A new study created in memory with name: logreg_study
[I 2025-04-11 00:02:50,105] Trial 0 finished with value: 0.7754010695187166 and parameters: {'C': 7.659422407680541, 'add_smote': False}. Best is trial 0 with value: 0.7754010695187166.
[I 2025-04-11 00:02:50,166] Trial 1 finished with value: 0.7730205278592375 and parameters: {'C': 0.3986291498738802, 'add_smote': False}. Best is trial 0 with value: 0.7754010695187166.
[I 2025-04-11 00:02:50,237] Trial 2 finished with value: 0.7787307032590051 and parameters: {'C': 0.0030108676374517194, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.6, 'k_neighbors': 5}. Best is trial 2 with value: 0.7787307032590051.
[I 2025-04-11 00:02:50,569] Trial 3 finished with value: 0.800925925925926 and parameters: {'C': 17.34448264461045, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 3 with value: 0.800925925925926.
[I 2025-04-11 00:02:50,640] Trial 4 finished with value: 0.8023529411764707 and parameters: {'C': 758.3359279831292, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:50,711] Trial 5 finished with value: 0.7980769230769231 and parameters: {'C': 203.92585538650982, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 6}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:50,772] Trial 6 finished with value: 0.7980769230769231 and parameters: {'C': 221.86487957852427, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:50,861] Trial 7 finished with value: 0.800925925925926 and parameters: {'C': 0.11908154175580475, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 7, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:50,921] Trial 8 finished with value: 0.7980769230769231 and parameters: {'C': 153.12600655357986, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:50,992] Trial 9 finished with value: 0.7865416436845009 and parameters: {'C': 57.21566847310466, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.8, 'k_neighbors': 6}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,061] Trial 10 finished with value: 0.7367521367521368 and parameters: {'C': 0.0001382745238361112, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 10}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,156] Trial 11 finished with value: 0.7888707037643208 and parameters: {'C': 5.299580369726267, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,258] Trial 12 finished with value: 0.800925925925926 and parameters: {'C': 999.1991465843992, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': True}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,353] Trial 13 finished with value: 0.7865416436845009 and parameters: {'C': 4.63227365389217, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,426] Trial 14 finished with value: 0.800925925925926 and parameters: {'C': 14.310660343503818, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,520] Trial 15 finished with value: 0.7826336975273146 and parameters: {'C': 0.3765631429881078, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 8, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,595] Trial 16 finished with value: 0.800925925925926 and parameters: {'C': 560.7647151958364, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.6, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,691] Trial 17 finished with value: 0.800925925925926 and parameters: {'C': 25.620774121865896, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 5, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,754] Trial 18 finished with value: 0.7826336975273146 and parameters: {'C': 0.06522060585403741, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,856] Trial 19 finished with value: 0.800925925925926 and parameters: {'C': 1.3681639784550572, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.8, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': True}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:51,928] Trial 20 finished with value: 0.7567873303167421 and parameters: {'C': 0.013894823031470554, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,034] Trial 21 finished with value: 0.800925925925926 and parameters: {'C': 0.07241455464861371, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 8, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,131] Trial 22 finished with value: 0.7980769230769231 and parameters: {'C': 1.4874416085858608, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 8, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,224] Trial 23 finished with value: 0.7367521367521368 and parameters: {'C': 0.003802614029527969, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 7, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,320] Trial 24 finished with value: 0.800925925925926 and parameters: {'C': 44.05411755147171, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 7, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,413] Trial 25 finished with value: 0.800925925925926 and parameters: {'C': 0.07785189050227168, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 10, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,475] Trial 26 finished with value: 0.7754010695187166 and parameters: {'C': 1.2240880825824965, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,549] Trial 27 finished with value: 0.800925925925926 and parameters: {'C': 89.58635991245508, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,640] Trial 28 finished with value: 0.7567873303167421 and parameters: {'C': 0.00014586733053217522, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.6, 'k_neighbors': 9, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,701] Trial 29 finished with value: 0.7754010695187166 and parameters: {'C': 7.269858216315348, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,773] Trial 30 finished with value: 0.7597254004576659 and parameters: {'C': 0.022728453178952276, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.8, 'k_neighbors': 6}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,877] Trial 31 finished with value: 0.800925925925926 and parameters: {'C': 771.6590749474054, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': True}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:52,983] Trial 32 finished with value: 0.800925925925926 and parameters: {'C': 712.6132716047963, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': True}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,087] Trial 33 finished with value: 0.800925925925926 and parameters: {'C': 329.98946091802503, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.9, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': True}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,182] Trial 34 finished with value: 0.8023529411764707 and parameters: {'C': 926.0302486879541, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,244] Trial 35 finished with value: 0.7980769230769231 and parameters: {'C': 15.926509897567172, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,340] Trial 36 finished with value: 0.800925925925926 and parameters: {'C': 109.17167491929746, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 5, 'wettability_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,435] Trial 37 finished with value: 0.8023529411764707 and parameters: {'C': 191.0463275712305, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,498] Trial 38 finished with value: 0.7980769230769231 and parameters: {'C': 278.74178996573914, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,573] Trial 39 finished with value: 0.8023529411764707 and parameters: {'C': 40.091484769663175, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,646] Trial 40 finished with value: 0.800925925925926 and parameters: {'C': 54.47679948935729, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,718] Trial 41 finished with value: 0.8023529411764707 and parameters: {'C': 222.23952066402705, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,790] Trial 42 finished with value: 0.8023529411764707 and parameters: {'C': 300.3511355829723, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,863] Trial 43 finished with value: 0.8023529411764707 and parameters: {'C': 120.69959149564401, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:53,936] Trial 44 finished with value: 0.800925925925926 and parameters: {'C': 340.58236498411867, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,011] Trial 45 finished with value: 0.8023529411764707 and parameters: {'C': 35.0068948193826, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,085] Trial 46 finished with value: 0.8023529411764707 and parameters: {'C': 162.39122028891217, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,160] Trial 47 finished with value: 0.8023529411764707 and parameters: {'C': 479.9292784357507, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,232] Trial 48 finished with value: 0.800925925925926 and parameters: {'C': 68.08263346498758, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,305] Trial 49 finished with value: 0.8023529411764707 and parameters: {'C': 181.77682405345308, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,366] Trial 50 finished with value: 0.7980769230769231 and parameters: {'C': 728.9076641988763, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,440] Trial 51 finished with value: 0.8023529411764707 and parameters: {'C': 317.9312770073304, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,511] Trial 52 finished with value: 0.8023529411764707 and parameters: {'C': 987.9816117808202, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,583] Trial 53 finished with value: 0.8023529411764707 and parameters: {'C': 222.79321051771691, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,655] Trial 54 finished with value: 0.7730205278592375 and parameters: {'C': 491.1791432310039, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 6}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,727] Trial 55 finished with value: 0.800925925925926 and parameters: {'C': 31.469257473274233, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.6, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,798] Trial 56 finished with value: 0.800925925925926 and parameters: {'C': 127.93416203520269, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,869] Trial 57 finished with value: 0.8023529411764707 and parameters: {'C': 3.577839382546268, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:54,942] Trial 58 finished with value: 0.8023529411764707 and parameters: {'C': 11.794488387892473, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,013] Trial 59 finished with value: 0.800925925925926 and parameters: {'C': 76.05560542705902, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.8, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,110] Trial 60 finished with value: 0.8023529411764707 and parameters: {'C': 24.015184788899802, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,198] Trial 61 finished with value: 0.800925925925926 and parameters: {'C': 170.6633908389088, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,273] Trial 62 finished with value: 0.8023529411764707 and parameters: {'C': 439.8797759241413, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,345] Trial 63 finished with value: 0.8023529411764707 and parameters: {'C': 108.97675140167404, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,417] Trial 64 finished with value: 0.8023529411764707 and parameters: {'C': 253.78097470915236, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,489] Trial 65 finished with value: 0.800925925925926 and parameters: {'C': 990.7422532779691, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.6, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,584] Trial 66 finished with value: 0.800925925925926 and parameters: {'C': 49.25299481860905, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 5, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,694] Trial 67 finished with value: 0.7980769230769231 and parameters: {'C': 480.78674888703824, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,768] Trial 68 finished with value: 0.800925925925926 and parameters: {'C': 0.7042569954406481, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.8, 'k_neighbors': 6}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,865] Trial 69 finished with value: 0.8023529411764707 and parameters: {'C': 147.13526994001944, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 4, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:55,940] Trial 70 finished with value: 0.8023529411764707 and parameters: {'C': 88.45386321851618, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.9, 'k_neighbors': 3}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,014] Trial 71 finished with value: 0.8023529411764707 and parameters: {'C': 40.24060597443792, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,088] Trial 72 finished with value: 0.8023529411764707 and parameters: {'C': 28.528652813186294, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,159] Trial 73 finished with value: 0.800925925925926 and parameters: {'C': 0.2048259599371698, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 4}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,255] Trial 74 finished with value: 0.8023529411764707 and parameters: {'C': 11.739268579941868, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 0.7, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,330] Trial 75 finished with value: 0.800925925925926 and parameters: {'C': 247.18063794080592, 'add_smote': True, 'is_smotenc': False, 'sampling_strategy': 0.7, 'k_neighbors': 5}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,428] Trial 76 finished with value: 0.7663043478260869 and parameters: {'C': 520.6818170056906, 'add_smote': True, 'is_smotenc': True, 'sampling_strategy': 1.0, 'k_neighbors': 3, 'wettability_cat': True, 'inclination_cat': False}. Best is trial 4 with value: 0.8023529411764707.
[I 2025-04-11 00:02:56,490] Trial 77 finished with value: 0.7754010695187166 and parameters: {'C': 2.8775296150489718, 'add_smote': False}. Best is trial 4 with value: 0.8023529411764707.

{'C': 1.6850403782968544,
 'add_smote': True,
 'is_smotenc': False,
 'sampling_strategy': 0.7,
 'k_neighbors': 4}