Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-smotenc_default-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
n_trials = 50

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )
    
    
def optimize_smote_grid(
    target:str,
    estimator:object,
    estimator_params:dict,
    param_grid:dict=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters with GridSearchOptimizer for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )
    
    if param_grid is None:
        param_grid = {
        'sampling_strategy': [0.6, 0.7, 0.8, 0.9, 1.0, 'auto'],
        'k_neighbors': list(range(2,11)),
    }
    opt = GridSearchOptimizer(
        objective=partial(pure_smote_objective, ml_pipe=ml_pipe),
        param_grid=param_grid,
        verbose=True,
    )

    opt.optimize()
    best_params = opt.best_params

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    n_trials=n_trials,
    save_model_and_metrics=False,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-13 15:46:53,454] A new study created in memory with name: smote_study
[I 2025-04-13 15:46:53,804] Trial 0 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.7795918367346939.
[I 2025-04-13 15:46:54,053] Trial 1 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.800925925925926.
[I 2025-04-13 15:46:54,298] Trial 2 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.800925925925926.
[I 2025-04-13 15:46:54,570] Trial 3 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 3 with value: 0.8055555555555556.
[I 2025-04-13 15:46:54,806] Trial 4 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:55,048] Trial 5 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:55,288] Trial 6 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:55,524] Trial 7 finished with value: 0.7730205278592375 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:55,761] Trial 8 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:56,004] Trial 9 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:56,246] Trial 10 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:56,488] Trial 11 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:56,736] Trial 12 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:56,987] Trial 13 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:57,227] Trial 14 finished with value: 0.8023529411764707 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:57,479] Trial 15 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:57,720] Trial 16 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:57,968] Trial 17 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:58,229] Trial 18 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:58,483] Trial 19 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:58,738] Trial 20 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:58,978] Trial 21 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:59,229] Trial 22 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:59,473] Trial 23 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:59,705] Trial 24 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:46:59,934] Trial 25 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:00,184] Trial 26 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:00,463] Trial 27 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:00,702] Trial 28 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:00,933] Trial 29 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:01,165] Trial 30 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:01,396] Trial 31 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:01,639] Trial 32 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:01,883] Trial 33 finished with value: 0.7980769230769231 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:02,110] Trial 34 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:02,344] Trial 35 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:02,596] Trial 36 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:02,841] Trial 37 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:03,085] Trial 38 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:03,328] Trial 39 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:03,569] Trial 40 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:03,804] Trial 41 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:04,043] Trial 42 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:04,294] Trial 43 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:04,543] Trial 44 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:04,806] Trial 45 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:05,037] Trial 46 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:05,274] Trial 47 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:05,514] Trial 48 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.
[I 2025-04-13 15:47:05,758] Trial 49 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8088888888888889.

best_params

{'k_neighbors': 6, 'sampling_strategy': 0.6}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.875772
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.781238
cv_test_accuracy_balanced_median                                           0.791796
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.835821
cv_test_accuracy_median                                                    0.792453
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.731707

In [7]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:12,  4.21it/s]

Progress: 1/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:12,  4.18it/s]

Progress: 2/54.	Score: 0.7831932773109243.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:11,  4.27it/s]

Progress: 3/54.	Score: 0.7865416436845009.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:11,  4.29it/s]

Progress: 4/54.	Score: 0.7865416436845009.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:11,  4.26it/s]

Progress: 5/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:11,  4.26it/s]

Progress: 6/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:10,  4.29it/s]

Progress: 7/54.	Score: 0.7730205278592375.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:10,  4.20it/s]

Progress: 8/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:10,  4.13it/s]

Progress: 9/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:10,  4.11it/s]

Progress: 10/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:10,  4.07it/s]

Progress: 11/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:02<00:10,  4.00it/s]

Progress: 12/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:10,  3.92it/s]

Progress: 13/54.	Score: 0.8023529411764707.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:10,  3.99it/s]

Progress: 14/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:09,  4.00it/s]

Progress: 15/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:09,  4.01it/s]

Progress: 16/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:04<00:09,  4.06it/s]

Progress: 17/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:04<00:08,  4.01it/s]

Progress: 18/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:04<00:08,  4.02it/s]

Progress: 19/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:08,  4.04it/s]

Progress: 20/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:05<00:08,  4.08it/s]

Progress: 21/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:05<00:08,  3.91it/s]

Progress: 22/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:05<00:07,  3.93it/s]

Progress: 23/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:05<00:07,  4.00it/s]

Progress: 24/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:06<00:07,  4.07it/s]

Progress: 25/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:06<00:06,  4.12it/s]

Progress: 26/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:06<00:06,  4.16it/s]

Progress: 27/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:06<00:06,  4.07it/s]

Progress: 28/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:07<00:06,  3.96it/s]

Progress: 29/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:07<00:06,  3.84it/s]

Progress: 30/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:07<00:05,  3.92it/s]

Progress: 31/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:07<00:05,  4.00it/s]

Progress: 32/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:08<00:05,  4.02it/s]

Progress: 33/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:08<00:04,  4.05it/s]

Progress: 34/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:08<00:04,  4.01it/s]

Progress: 35/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:08<00:04,  4.02it/s]

Progress: 36/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:09<00:04,  4.00it/s]

Progress: 37/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:09<00:03,  4.06it/s]

Progress: 38/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:09<00:03,  4.07it/s]

Progress: 39/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:09<00:03,  4.11it/s]

Progress: 40/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:10<00:03,  3.82it/s]

Progress: 41/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:10<00:03,  3.93it/s]

Progress: 42/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:10<00:02,  3.99it/s]

Progress: 43/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:10<00:02,  4.06it/s]

Progress: 44/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:11<00:02,  4.04it/s]

Progress: 45/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:11<00:01,  4.00it/s]

Progress: 46/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:11<00:01,  4.06it/s]

Progress: 47/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:11<00:01,  4.09it/s]

Progress: 48/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:12<00:01,  4.13it/s]

Progress: 49/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:12<00:00,  4.12it/s]

Progress: 50/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:12<00:00,  3.87it/s]

Progress: 51/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:12<00:00,  3.96it/s]

Progress: 52/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:13<00:00,  3.98it/s]

Progress: 53/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:13<00:00,  4.04it/s]

Progress: 54/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8088888888888889
Best params: {'k_neighbors': 6, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.875772
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.781238
cv_test_accuracy_balanced_median                                           0.791796
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.835821
cv_test_accuracy_median                                                    0.792453
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.731707

Model saved in ..\results\models_modelling4\LogisticRegression_splashing_smotenc_opt-smotenc_default-model

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:13,  4.00it/s]

Progress: 1/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:12,  4.30it/s]

Progress: 2/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:11,  4.51it/s]

Progress: 3/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:11,  4.50it/s]

Progress: 4/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:11,  4.36it/s]

Progress: 5/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:10,  4.56it/s]

Progress: 6/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.
Progress: 7/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:10,  4.58it/s]

Progress: 8/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:01<00:09,  4.65it/s]

Progress: 9/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:09,  4.63it/s]

Progress: 10/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.
Progress: 11/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:02<00:09,  4.63it/s]

Progress: 12/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:08,  4.72it/s]

Progress: 13/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:08,  4.62it/s]

Progress: 15/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:08,  4.63it/s]

Progress: 16/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:03<00:07,  4.65it/s]

Progress: 17/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:07,  4.72it/s]

Progress: 19/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:04<00:07,  4.69it/s]

Progress: 21/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:04<00:06,  4.64it/s]

Progress: 22/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.
Progress: 23/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:05<00:07,  4.21it/s]

Progress: 24/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  48%|████▊     | 26/54 [00:05<00:06,  4.40it/s]

Progress: 25/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 26/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:05<00:06,  4.48it/s]

Progress: 27/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:06<00:05,  4.45it/s]

Progress: 28/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:06<00:05,  4.47it/s]

Progress: 29/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:06<00:05,  4.52it/s]

Progress: 30/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:06<00:05,  4.57it/s]

Progress: 31/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:07<00:04,  4.59it/s]

Progress: 32/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:07<00:04,  4.59it/s]

Progress: 33/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:07<00:04,  4.59it/s]

Progress: 34/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:07<00:04,  4.44it/s]

Progress: 35/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:07<00:04,  4.44it/s]

Progress: 36/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:08<00:04,  4.19it/s]

Progress: 37/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:08<00:03,  4.33it/s]

Progress: 38/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:08<00:03,  4.41it/s]

Progress: 39/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:08<00:03,  4.43it/s]

Progress: 40/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:09<00:02,  4.41it/s]

Progress: 41/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:09<00:02,  4.28it/s]

Progress: 42/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:09<00:02,  4.34it/s]

Progress: 43/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:09<00:02,  4.33it/s]

Progress: 44/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:10<00:01,  4.46it/s]

Progress: 45/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:10<00:01,  4.52it/s]

Progress: 47/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:10<00:01,  4.38it/s]

Progress: 48/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:10<00:01,  4.39it/s]

Progress: 49/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:11<00:00,  4.23it/s]

Progress: 50/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:11<00:00,  4.35it/s]

Progress: 51/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:11<00:00,  4.43it/s]

Progress: 52/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:11<00:00,  4.46it/s]

Progress: 53/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:12<00:00,  4.48it/s]

Progress: 54/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8392857142857143
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.785539
holdout_test_accuracy_balanced                                                0.825
holdout_test_roc_auc                                                       0.953636
holdout_test_f1                                                            0.708333
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.864469
cv_test_roc_auc_median                                                     0.946886
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.794872
cv_test_f1_class_0_median                                                  0.885714

Model saved in ..\results\models_modelling4\LogisticRegression_no_fragmentation_smotenc_opt-smotenc_default-model

# KNClassifier

In [9]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:15,  3.37it/s]

Progress: 1/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:15,  3.36it/s]

Progress: 2/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:15,  3.33it/s]

Progress: 3/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:15,  3.22it/s]

Progress: 4/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:15,  3.12it/s]

Progress: 5/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:15,  3.19it/s]

Progress: 6/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:14,  3.25it/s]

Progress: 7/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:14,  3.27it/s]

Progress: 8/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:13,  3.23it/s]

Progress: 9/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:13,  3.25it/s]

Progress: 10/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:13,  3.18it/s]

Progress: 11/54.	Score: 0.7881773399014778.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:13,  3.22it/s]

Progress: 12/54.	Score: 0.7881773399014778.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:12,  3.23it/s]

Progress: 13/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:12,  3.26it/s]

Progress: 14/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:11,  3.25it/s]

Progress: 15/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:11,  3.26it/s]

Progress: 16/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:11,  3.14it/s]

Progress: 17/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:11,  3.04it/s]

Progress: 18/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:11,  3.11it/s]

Progress: 19/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:10,  3.13it/s]

Progress: 20/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:10,  3.12it/s]

Progress: 21/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:10,  3.10it/s]

Progress: 22/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  3.03it/s]

Progress: 23/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.05it/s]

Progress: 24/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:09,  3.10it/s]

Progress: 25/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:08,  3.12it/s]

Progress: 26/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.14it/s]

Progress: 27/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:08,  3.04it/s]

Progress: 28/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  3.06it/s]

Progress: 29/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:07,  3.09it/s]

Progress: 30/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:07,  3.05it/s]

Progress: 31/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.05it/s]

Progress: 32/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.07it/s]

Progress: 33/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:06,  3.09it/s]

Progress: 34/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  3.07it/s]

Progress: 35/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:05,  3.06it/s]

Progress: 36/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:05,  3.00it/s]

Progress: 37/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  3.04it/s]

Progress: 38/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.10it/s]

Progress: 39/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:04,  3.14it/s]

Progress: 40/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:04,  3.13it/s]

Progress: 41/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:03,  3.14it/s]

Progress: 42/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:13<00:03,  3.17it/s]

Progress: 43/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:14<00:03,  3.20it/s]

Progress: 44/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.17it/s]

Progress: 45/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:14<00:02,  3.18it/s]

Progress: 46/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  3.14it/s]

Progress: 47/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:15<00:01,  3.03it/s]

Progress: 48/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:15<00:01,  3.08it/s]

Progress: 49/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:15<00:01,  3.13it/s]

Progress: 50/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:00,  3.13it/s]

Progress: 51/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:16<00:00,  3.15it/s]

Progress: 52/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:16<00:00,  3.13it/s]

Progress: 53/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.14it/s]

Progress: 54/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8444444444444446
Best params: {'k_neighbors': 2, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smotenc_opt-smo...
holdout_test_f1_macro                                                      0.784689
holdout_test_accuracy_balanced                                             0.787037
holdout_test_roc_auc                                                       0.871914
holdout_test_f1                                                            0.842105
holdout_test_accuracy                                                           0.8
cv_test_f1_macro_median                                                    0.844575
cv_test_accuracy_balanced_median                                           0.870743
cv_test_roc_auc_median                                                     0.926471
cv_test_f1_median                                                          0.870968
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                               0.72
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.818182

Model saved in ..\results\models_modelling4\KNeighborsClassifier_splashing_smotenc_opt-smotenc_default-model

In [10]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:14,  3.53it/s]

Progress: 1/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:14,  3.59it/s]

Progress: 2/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:14,  3.56it/s]

Progress: 3/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:14,  3.44it/s]

Progress: 4/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:14,  3.48it/s]

Progress: 5/54.	Score: 0.8089668615984404.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:13,  3.51it/s]

Progress: 6/54.	Score: 0.8089668615984404.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:13,  3.54it/s]

Progress: 7/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:12,  3.54it/s]

Progress: 8/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:12,  3.56it/s]

Progress: 9/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:12,  3.57it/s]

Progress: 10/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:12,  3.56it/s]

Progress: 11/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:11,  3.57it/s]

Progress: 12/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:11,  3.59it/s]

Progress: 13/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:11,  3.61it/s]

Progress: 14/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:10,  3.59it/s]

Progress: 15/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:10,  3.55it/s]

Progress: 16/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:04<00:10,  3.56it/s]

Progress: 17/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:10,  3.56it/s]

Progress: 18/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:09,  3.59it/s]

Progress: 19/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:05<00:09,  3.60it/s]

Progress: 20/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:05<00:09,  3.60it/s]

Progress: 21/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:08,  3.59it/s]

Progress: 22/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:08,  3.56it/s]

Progress: 23/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:06<00:08,  3.55it/s]

Progress: 24/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:08,  3.56it/s]

Progress: 25/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:07<00:07,  3.58it/s]

Progress: 26/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:07<00:07,  3.59it/s]

Progress: 27/54.	Score: 0.7904490377761939.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:07<00:07,  3.56it/s]

Progress: 28/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:08<00:07,  3.56it/s]

Progress: 29/54.	Score: 0.7857142857142857.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:08<00:06,  3.56it/s]

Progress: 30/54.	Score: 0.7857142857142857.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:08<00:06,  3.45it/s]

Progress: 31/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:09<00:06,  3.50it/s]

Progress: 32/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:09<00:05,  3.53it/s]

Progress: 33/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:09<00:05,  3.54it/s]

Progress: 34/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:09<00:05,  3.55it/s]

Progress: 35/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:10<00:05,  3.56it/s]

Progress: 36/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:10<00:04,  3.59it/s]

Progress: 37/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:10<00:04,  3.61it/s]

Progress: 38/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:10<00:04,  3.56it/s]

Progress: 39/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:11<00:03,  3.57it/s]

Progress: 40/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:11<00:03,  3.58it/s]

Progress: 41/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:11<00:03,  3.58it/s]

Progress: 42/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:12<00:03,  3.60it/s]

Progress: 43/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:12<00:02,  3.61it/s]

Progress: 44/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:12<00:02,  3.61it/s]

Progress: 45/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:12<00:02,  3.59it/s]

Progress: 46/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:13<00:01,  3.56it/s]

Progress: 47/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:13<00:01,  3.57it/s]

Progress: 48/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:13<00:01,  3.61it/s]

Progress: 49/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:14<00:01,  3.63it/s]

Progress: 50/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:14<00:00,  3.63it/s]

Progress: 51/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:14<00:00,  3.63it/s]

Progress: 52/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:14<00:00,  3.62it/s]

Progress: 53/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:15<00:00,  3.57it/s]

Progress: 54/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8650345260514751
Best params: {'k_neighbors': 9, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smotenc_...
holdout_test_f1_macro                                                      0.807033
holdout_test_accuracy_balanced                                             0.827273
holdout_test_roc_auc                                                           0.93
holdout_test_f1                                                            0.727273
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.854396
cv_test_roc_auc_median                                                     0.929487
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.923077

Model saved in ..\results\models_modelling4\KNeighborsClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# SVC

In [11]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:16,  3.20it/s]

Progress: 1/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:15,  3.32it/s]

Progress: 2/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:15,  3.30it/s]

Progress: 3/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:15,  3.16it/s]

Progress: 4/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:15,  3.18it/s]

Progress: 5/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:15,  3.18it/s]

Progress: 6/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:14,  3.30it/s]

Progress: 7/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:13,  3.35it/s]

Progress: 8/54.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:13,  3.34it/s]

Progress: 9/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:13,  3.33it/s]

Progress: 10/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:13,  3.27it/s]

Progress: 11/54.	Score: 0.8285714285714286.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:12,  3.25it/s]

Progress: 12/54.	Score: 0.8285714285714286.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:12,  3.33it/s]

Progress: 13/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:11,  3.36it/s]

Progress: 14/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:11,  3.36it/s]

Progress: 15/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:11,  3.35it/s]

Progress: 16/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:11,  3.31it/s]

Progress: 17/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:11,  3.25it/s]

Progress: 18/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:10,  3.34it/s]

Progress: 19/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:10,  3.37it/s]

Progress: 20/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:09,  3.37it/s]

Progress: 21/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:09,  3.34it/s]

Progress: 22/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:09,  3.30it/s]

Progress: 23/54.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.29it/s]

Progress: 24/54.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:10,  2.88it/s]

Progress: 25/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:10,  2.80it/s]

Progress: 26/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:09,  2.95it/s]

Progress: 27/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:08,  3.06it/s]

Progress: 28/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.81it/s]

Progress: 29/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:08,  2.93it/s]

Progress: 30/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:07,  3.04it/s]

Progress: 31/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.14it/s]

Progress: 32/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:08,  2.42it/s]

Progress: 33/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:07,  2.64it/s]

Progress: 34/54.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  2.80it/s]

Progress: 35/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:06,  2.92it/s]

Progress: 36/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:05,  3.08it/s]

Progress: 37/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  3.17it/s]

Progress: 38/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.23it/s]

Progress: 39/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:04,  3.27it/s]

Progress: 40/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:03,  3.25it/s]

Progress: 41/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:03,  3.25it/s]

Progress: 42/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:13<00:03,  3.34it/s]

Progress: 43/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:13<00:02,  3.38it/s]

Progress: 44/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.35it/s]

Progress: 45/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:14<00:02,  3.34it/s]

Progress: 46/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  3.31it/s]

Progress: 47/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:15<00:01,  3.30it/s]

Progress: 48/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:15<00:01,  3.38it/s]

Progress: 49/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:15<00:01,  3.42it/s]

Progress: 50/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:00,  3.10it/s]

Progress: 51/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:16<00:00,  3.12it/s]

Progress: 52/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:16<00:00,  3.17it/s]

Progress: 53/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.17it/s]

Progress: 54/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.875222816399287
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                                0
target                                                                  splashing
model                             SVC_splashing_smotenc_opt-smotenc_default-model
holdout_test_f1_macro                                                    0.810348
holdout_test_accuracy_balanced                                            0.80787
holdout_test_roc_auc                                                     0.906636
holdout_test_f1                                                          0.865979
holdout_test_accuracy                                                    0.826667
cv_test_f1_macro_median                                                  0.863049
cv_test_accuracy_balanced_median                                         0.876935
cv_test_roc_auc_median                                                   0.928793
cv_test_f1_median                                                        0.888889
cv_test_accuracy_median                                                  0.867925
cv_test_precision_class_0_median                                             0.75
cv_test_recall_class_0_median                                            0.842105
cv_test_f1_class_0_median                                                0.837209

Model saved in ..\results\models_modelling4\SVC_splashing_smotenc_opt-smotenc_default-model

In [12]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:16,  3.25it/s]

Progress: 1/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:15,  3.45it/s]

Progress: 2/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:14,  3.43it/s]

Progress: 3/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:15,  3.31it/s]

Progress: 4/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:14,  3.32it/s]

Progress: 5/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:14,  3.31it/s]

Progress: 6/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:13,  3.42it/s]

Progress: 7/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:13,  3.46it/s]

Progress: 8/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:12,  3.47it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:12,  3.44it/s]

Progress: 10/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:12,  3.41it/s]

Progress: 11/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:12,  3.39it/s]

Progress: 12/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:11,  3.48it/s]

Progress: 13/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:11,  3.51it/s]

Progress: 14/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:14,  2.78it/s]

Progress: 15/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:13,  2.91it/s]

Progress: 16/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  3.01it/s]

Progress: 17/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:14,  2.47it/s]

Progress: 18/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:12,  2.75it/s]

Progress: 19/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:11,  2.96it/s]

Progress: 20/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:10,  3.11it/s]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:10,  3.19it/s]

Progress: 22/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:09,  3.22it/s]

Progress: 23/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.25it/s]

Progress: 24/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:09,  3.08it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:08,  3.23it/s]

Progress: 26/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.31it/s]

Progress: 27/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:07,  3.35it/s]

Progress: 28/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:07,  3.19it/s]

Progress: 29/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:07,  3.23it/s]

Progress: 30/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:06,  3.38it/s]

Progress: 31/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:09<00:06,  3.44it/s]

Progress: 32/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.48it/s]

Progress: 33/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:05,  3.49it/s]

Progress: 34/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:10<00:05,  3.47it/s]

Progress: 35/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:05,  3.44it/s]

Progress: 36/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:04,  3.52it/s]

Progress: 37/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:11<00:04,  3.58it/s]

Progress: 38/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:11<00:04,  3.60it/s]

Progress: 39/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:03,  3.57it/s]

Progress: 40/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:12<00:04,  3.16it/s]

Progress: 41/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:12<00:03,  3.23it/s]

Progress: 42/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:13<00:03,  3.37it/s]

Progress: 43/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:13<00:03,  2.79it/s]

Progress: 44/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:03,  2.72it/s]

Progress: 45/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:14<00:02,  2.92it/s]

Progress: 46/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  2.77it/s]

Progress: 47/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:15<00:02,  2.95it/s]

Progress: 48/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:15<00:01,  2.62it/s]

Progress: 49/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:15<00:01,  2.61it/s]

Progress: 50/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:01,  2.61it/s]

Progress: 51/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:16<00:00,  2.83it/s]

Progress: 52/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:16<00:00,  2.69it/s]

Progress: 53/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.13it/s]

Progress: 54/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8650345260514751
Best params: {'k_neighbors': 4, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smotenc_opt-smotenc_defau...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.958182
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.950549
cv_test_f1_median                                                               0.8
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.901408

Model saved in ..\results\models_modelling4\SVC_no_fragmentation_smotenc_opt-smotenc_default-model

# CatBoost

In [13]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:09<08:18,  9.41s/it]

Progress: 1/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:18<08:12,  9.48s/it]

Progress: 2/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:28<08:12,  9.66s/it]

Progress: 3/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:38<08:08,  9.77s/it]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:48<08:06,  9.93s/it]

Progress: 5/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:59<07:59, 10.00s/it]

Progress: 6/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [01:08<07:46,  9.92s/it]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [01:18<07:38,  9.97s/it]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [01:28<07:27,  9.94s/it]

Progress: 9/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [01:38<07:18,  9.95s/it]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [01:49<07:11, 10.03s/it]

Progress: 11/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [01:59<07:04, 10.10s/it]

Progress: 12/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [02:09<06:49, 10.00s/it]

Progress: 13/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [02:19<06:39, 10.00s/it]

Progress: 14/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [02:28<06:29,  9.99s/it]

Progress: 15/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [02:38<06:19,  9.99s/it]

Progress: 16/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [02:49<06:10, 10.02s/it]

Progress: 17/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [02:59<06:01, 10.04s/it]

Progress: 18/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [03:09<05:49, 10.00s/it]

Progress: 19/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [03:19<05:39, 10.00s/it]

Progress: 20/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [03:28<05:28,  9.96s/it]

Progress: 21/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [03:38<05:19,  9.97s/it]

Progress: 22/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [03:49<05:12, 10.07s/it]

Progress: 23/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [03:59<05:01, 10.05s/it]

Progress: 24/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [04:09<04:50, 10.02s/it]

Progress: 25/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [04:19<04:38,  9.96s/it]

Progress: 26/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [04:28<04:28,  9.95s/it]

Progress: 27/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [04:38<04:18,  9.93s/it]

Progress: 28/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [04:48<04:09,  9.98s/it]

Progress: 29/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [04:59<04:00, 10.04s/it]

Progress: 30/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [05:08<03:49,  9.99s/it]

Progress: 31/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [05:19<03:40, 10.02s/it]

Progress: 32/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [05:29<03:30, 10.03s/it]

Progress: 33/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [05:39<03:20, 10.02s/it]

Progress: 34/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [05:49<03:10, 10.05s/it]

Progress: 35/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [05:59<03:01, 10.08s/it]

Progress: 36/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [06:09<02:50, 10.03s/it]

Progress: 37/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [06:19<02:39,  9.95s/it]

Progress: 38/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [06:29<02:29,  9.96s/it]

Progress: 39/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [06:38<02:18,  9.93s/it]

Progress: 40/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [06:49<02:10, 10.02s/it]

Progress: 41/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [06:59<02:00, 10.08s/it]

Progress: 42/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [07:10<01:54, 10.38s/it]

Progress: 43/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [07:20<01:43, 10.35s/it]

Progress: 44/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [07:30<01:31, 10.21s/it]

Progress: 45/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [07:40<01:21, 10.17s/it]

Progress: 46/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [07:50<01:11, 10.16s/it]

Progress: 47/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [08:01<01:01, 10.19s/it]

Progress: 48/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [08:10<00:50, 10.10s/it]

Progress: 49/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [08:20<00:40, 10.04s/it]

Progress: 50/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [08:30<00:29,  9.96s/it]

Progress: 51/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [08:40<00:19,  9.97s/it]

Progress: 52/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [08:50<00:09, 10.00s/it]

Progress: 53/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [09:00<00:00, 10.01s/it]

Progress: 54/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8940886699507389
Best params: {'k_neighbors': 7, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.823391
holdout_test_accuracy_balanced                                             0.818287
holdout_test_roc_auc                                                       0.952932
holdout_test_f1                                                            0.877551
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.860788
cv_test_accuracy_balanced_median                                           0.873839
cv_test_roc_auc_median                                                     0.955108
cv_test_f1_median                                                          0.898551
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.823529
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.829268

Model saved in ..\results\models_modelling4\CatBoostClassifier_splashing_smotenc_opt-smotenc_default-model

In [14]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:09<08:09,  9.25s/it]

Progress: 1/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:18<08:05,  9.33s/it]

Progress: 2/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:28<08:04,  9.49s/it]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:38<07:58,  9.58s/it]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:47<07:50,  9.60s/it]

Progress: 5/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:57<07:42,  9.63s/it]

Progress: 6/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [01:06<07:28,  9.54s/it]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [01:16<07:15,  9.48s/it]

Progress: 8/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [01:25<07:08,  9.52s/it]

Progress: 9/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [01:35<06:58,  9.51s/it]

Progress: 10/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [01:44<06:51,  9.56s/it]

Progress: 11/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [01:54<06:43,  9.61s/it]

Progress: 12/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [02:04<06:33,  9.60s/it]

Progress: 13/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [02:13<06:20,  9.51s/it]

Progress: 14/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [02:22<06:10,  9.51s/it]

Progress: 15/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [02:32<06:01,  9.51s/it]

Progress: 16/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [02:42<05:53,  9.54s/it]

Progress: 17/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [02:51<05:44,  9.56s/it]

Progress: 18/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [03:01<05:33,  9.53s/it]

Progress: 19/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [03:10<05:24,  9.55s/it]

Progress: 20/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [03:20<05:13,  9.51s/it]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [03:29<05:05,  9.56s/it]

Progress: 22/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [03:39<04:57,  9.59s/it]

Progress: 23/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [03:48<04:46,  9.56s/it]

Progress: 24/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [03:58<04:35,  9.49s/it]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [04:07<04:25,  9.49s/it]

Progress: 26/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [04:17<04:17,  9.52s/it]

Progress: 27/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [04:27<04:08,  9.57s/it]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [04:36<04:01,  9.66s/it]

Progress: 29/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [04:46<03:53,  9.73s/it]

Progress: 30/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [04:56<03:40,  9.58s/it]

Progress: 31/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [05:05<03:30,  9.56s/it]

Progress: 32/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [05:15<03:21,  9.59s/it]

Progress: 33/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [05:24<03:11,  9.58s/it]

Progress: 34/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [05:34<03:01,  9.55s/it]

Progress: 35/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [05:43<02:51,  9.55s/it]

Progress: 36/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [05:53<02:40,  9.46s/it]

Progress: 37/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [06:02<02:31,  9.44s/it]

Progress: 38/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [06:11<02:21,  9.43s/it]

Progress: 39/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [06:21<02:13,  9.51s/it]

Progress: 40/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [06:31<02:04,  9.56s/it]

Progress: 41/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [06:41<01:55,  9.65s/it]

Progress: 42/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [06:50<01:45,  9.61s/it]

Progress: 43/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [07:00<01:35,  9.55s/it]

Progress: 44/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [07:09<01:26,  9.61s/it]

Progress: 45/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [07:19<01:17,  9.63s/it]

Progress: 46/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [07:29<01:07,  9.65s/it]

Progress: 47/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [07:38<00:57,  9.65s/it]

Progress: 48/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [07:48<00:47,  9.57s/it]

Progress: 49/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [07:57<00:38,  9.57s/it]

Progress: 50/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [08:07<00:28,  9.56s/it]

Progress: 51/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [08:16<00:19,  9.60s/it]

Progress: 52/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [08:26<00:09,  9.59s/it]

Progress: 53/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [08:36<00:00,  9.56s/it]

Progress: 54/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8768328445747801
Best params: {'k_neighbors': 7, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.897727
holdout_test_accuracy_balanced                                             0.897727
holdout_test_roc_auc                                                       0.979091
holdout_test_f1                                                                0.85
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                      0.97094
cv_test_f1_median                                                          0.846154
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                      0.95

Model saved in ..\results\models_modelling4\CatBoostClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# XGBoost

In [15]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:21,  2.51it/s]

Progress: 1/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:21,  2.45it/s]

Progress: 2/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:20,  2.44it/s]

Progress: 3/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:20,  2.47it/s]

Progress: 4/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:02<00:20,  2.37it/s]

Progress: 5/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:19,  2.40it/s]

Progress: 6/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:19,  2.46it/s]

Progress: 7/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:03<00:18,  2.45it/s]

Progress: 8/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:18,  2.46it/s]

Progress: 9/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:04<00:17,  2.47it/s]

Progress: 10/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:04<00:17,  2.48it/s]

Progress: 11/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:16,  2.48it/s]

Progress: 12/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:05<00:16,  2.48it/s]

Progress: 13/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:05<00:15,  2.50it/s]

Progress: 14/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:06<00:15,  2.50it/s]

Progress: 15/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:06<00:15,  2.50it/s]

Progress: 16/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:06<00:14,  2.50it/s]

Progress: 17/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:07<00:14,  2.46it/s]

Progress: 18/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:07<00:14,  2.49it/s]

Progress: 19/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:08<00:13,  2.50it/s]

Progress: 20/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:08<00:13,  2.51it/s]

Progress: 21/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:08<00:12,  2.51it/s]

Progress: 22/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:09<00:12,  2.49it/s]

Progress: 23/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:09<00:12,  2.46it/s]

Progress: 24/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:10<00:11,  2.49it/s]

Progress: 25/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:10<00:11,  2.50it/s]

Progress: 26/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:10<00:10,  2.51it/s]

Progress: 27/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:11<00:10,  2.49it/s]

Progress: 28/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:11<00:10,  2.45it/s]

Progress: 29/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:12<00:09,  2.46it/s]

Progress: 30/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:12<00:09,  2.50it/s]

Progress: 31/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:12<00:08,  2.52it/s]

Progress: 32/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:13<00:08,  2.51it/s]

Progress: 33/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:13<00:08,  2.48it/s]

Progress: 34/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:14<00:07,  2.46it/s]

Progress: 35/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:14<00:07,  2.47it/s]

Progress: 36/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:14<00:06,  2.50it/s]

Progress: 37/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:15<00:06,  2.52it/s]

Progress: 38/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:15<00:06,  2.45it/s]

Progress: 39/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:16<00:05,  2.34it/s]

Progress: 40/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:16<00:05,  2.39it/s]

Progress: 41/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:17<00:04,  2.43it/s]

Progress: 42/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:17<00:04,  2.48it/s]

Progress: 43/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:17<00:04,  2.50it/s]

Progress: 44/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:18<00:03,  2.47it/s]

Progress: 45/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:18<00:03,  2.48it/s]

Progress: 46/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:18<00:02,  2.49it/s]

Progress: 47/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:19<00:02,  2.49it/s]

Progress: 48/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:19<00:01,  2.52it/s]

Progress: 49/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:20<00:01,  2.50it/s]

Progress: 50/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:20<00:01,  2.50it/s]

Progress: 51/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:20<00:00,  2.50it/s]

Progress: 52/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:21<00:00,  2.47it/s]

Progress: 53/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:21<00:00,  2.48it/s]

Progress: 54/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8962962962962964
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smotenc_opt-smotenc_de...
holdout_test_f1_macro                                                      0.896019
holdout_test_accuracy_balanced                                             0.886574
holdout_test_roc_auc                                                        0.94213
holdout_test_f1                                                            0.929293
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                     0.87381
cv_test_accuracy_balanced_median                                           0.873839
cv_test_roc_auc_median                                                     0.948916
cv_test_f1_median                                                          0.914286
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                               0.85
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.833333

Model saved in ..\results\models_modelling4\XGBClassifier_splashing_smotenc_opt-smotenc_default-model

In [16]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:19,  2.67it/s]

Progress: 1/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:19,  2.66it/s]

Progress: 2/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:20,  2.43it/s]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:20,  2.45it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:19,  2.50it/s]

Progress: 5/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:18,  2.53it/s]

Progress: 6/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:18,  2.58it/s]

Progress: 7/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:03<00:17,  2.60it/s]

Progress: 8/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:17,  2.59it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:17,  2.57it/s]

Progress: 10/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:04<00:16,  2.58it/s]

Progress: 11/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:16,  2.58it/s]

Progress: 12/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:05<00:15,  2.61it/s]

Progress: 13/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:05<00:15,  2.62it/s]

Progress: 14/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:05<00:15,  2.59it/s]

Progress: 15/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:06<00:14,  2.60it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:06<00:14,  2.61it/s]

Progress: 17/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:06<00:13,  2.62it/s]

Progress: 18/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:07<00:13,  2.64it/s]

Progress: 19/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:07<00:12,  2.65it/s]

Progress: 20/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:08<00:12,  2.61it/s]

Progress: 21/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:08<00:12,  2.61it/s]

Progress: 22/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:08<00:11,  2.62it/s]

Progress: 23/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:09<00:11,  2.61it/s]

Progress: 24/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:09<00:11,  2.63it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:10<00:10,  2.62it/s]

Progress: 26/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:10<00:10,  2.60it/s]

Progress: 27/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:10<00:09,  2.61it/s]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:11<00:09,  2.61it/s]

Progress: 29/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:11<00:09,  2.62it/s]

Progress: 30/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:11<00:08,  2.65it/s]

Progress: 31/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:12<00:08,  2.62it/s]

Progress: 32/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:12<00:08,  2.62it/s]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:13<00:07,  2.62it/s]

Progress: 34/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:13<00:07,  2.50it/s]

Progress: 35/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:13<00:07,  2.53it/s]

Progress: 36/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:14<00:06,  2.55it/s]

Progress: 37/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:14<00:06,  2.55it/s]

Progress: 38/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:15<00:05,  2.58it/s]

Progress: 39/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:15<00:05,  2.60it/s]

Progress: 40/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:15<00:04,  2.61it/s]

Progress: 41/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:16<00:04,  2.61it/s]

Progress: 42/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:16<00:04,  2.59it/s]

Progress: 43/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:16<00:03,  2.61it/s]

Progress: 44/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:17<00:03,  2.63it/s]

Progress: 45/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:17<00:03,  2.63it/s]

Progress: 46/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:18<00:02,  2.62it/s]

Progress: 47/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:18<00:02,  2.62it/s]

Progress: 48/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:18<00:01,  2.60it/s]

Progress: 49/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:19<00:01,  2.62it/s]

Progress: 50/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:19<00:01,  2.63it/s]

Progress: 51/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:20<00:00,  2.53it/s]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:20<00:00,  2.55it/s]

Progress: 53/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:20<00:00,  2.59it/s]

Progress: 54/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8503207412687099
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smotenc_opt-smo...
holdout_test_f1_macro                                                      0.931818
holdout_test_accuracy_balanced                                             0.931818
holdout_test_roc_auc                                                       0.991818
holdout_test_f1                                                                 0.9
holdout_test_accuracy                                                      0.946667
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.854396
cv_test_roc_auc_median                                                     0.978022
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.923077

Model saved in ..\results\models_modelling4\XGBClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# AdaBoost

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:34,  1.56it/s]

Progress: 1/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:34,  1.52it/s]

Progress: 2/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:33,  1.52it/s]

Progress: 3/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:32,  1.53it/s]

Progress: 4/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:03<00:32,  1.52it/s]

Progress: 5/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:31,  1.52it/s]

Progress: 6/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:30,  1.53it/s]

Progress: 7/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:05<00:29,  1.54it/s]

Progress: 8/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:29,  1.53it/s]

Progress: 9/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:06<00:28,  1.53it/s]

Progress: 10/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:07<00:28,  1.52it/s]

Progress: 11/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:27,  1.52it/s]

Progress: 12/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:08<00:26,  1.53it/s]

Progress: 13/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:09<00:26,  1.53it/s]

Progress: 14/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:09<00:25,  1.52it/s]

Progress: 15/54.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:10<00:24,  1.53it/s]

Progress: 16/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:11<00:24,  1.53it/s]

Progress: 17/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:11<00:23,  1.52it/s]

Progress: 18/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:12<00:22,  1.54it/s]

Progress: 19/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:13<00:21,  1.55it/s]

Progress: 20/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:13<00:21,  1.55it/s]

Progress: 21/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:14<00:20,  1.54it/s]

Progress: 22/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:15<00:20,  1.54it/s]

Progress: 23/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:15<00:19,  1.54it/s]

Progress: 24/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:16<00:18,  1.55it/s]

Progress: 25/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:16<00:18,  1.55it/s]

Progress: 26/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:17<00:17,  1.55it/s]

Progress: 27/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:18<00:16,  1.54it/s]

Progress: 28/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:18<00:16,  1.53it/s]

Progress: 29/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:19<00:15,  1.53it/s]

Progress: 30/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:20<00:14,  1.55it/s]

Progress: 31/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:20<00:14,  1.55it/s]

Progress: 32/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:21<00:13,  1.55it/s]

Progress: 33/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:22<00:12,  1.55it/s]

Progress: 34/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:22<00:12,  1.54it/s]

Progress: 35/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:23<00:11,  1.54it/s]

Progress: 36/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:24<00:10,  1.55it/s]

Progress: 37/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:24<00:10,  1.56it/s]

Progress: 38/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:25<00:09,  1.55it/s]

Progress: 39/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:25<00:09,  1.55it/s]

Progress: 40/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:26<00:08,  1.54it/s]

Progress: 41/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:27<00:07,  1.50it/s]

Progress: 42/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:27<00:07,  1.53it/s]

Progress: 43/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:28<00:06,  1.54it/s]

Progress: 44/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:29<00:05,  1.54it/s]

Progress: 45/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:29<00:05,  1.54it/s]

Progress: 46/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:30<00:04,  1.54it/s]

Progress: 47/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:31<00:03,  1.53it/s]

Progress: 48/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:31<00:03,  1.54it/s]

Progress: 49/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:32<00:02,  1.55it/s]

Progress: 50/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:33<00:01,  1.55it/s]

Progress: 51/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:33<00:01,  1.54it/s]

Progress: 52/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:34<00:00,  1.54it/s]

Progress: 53/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:35<00:00,  1.54it/s]

Progress: 54/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.873900293255132
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.764521
holdout_test_accuracy_balanced                                             0.760417
holdout_test_roc_auc                                                       0.877701
holdout_test_f1                                                            0.836735
holdout_test_accuracy                                                      0.786667
cv_test_f1_macro_median                                                    0.813161
cv_test_accuracy_balanced_median                                           0.809598
cv_test_roc_auc_median                                                     0.905573
cv_test_f1_median                                                          0.869565
cv_test_accuracy_median                                                    0.830189
cv_test_precision_class_0_median                                           0.777778
cv_test_recall_class_0_median                                              0.736842
cv_test_f1_class_0_median                                                  0.756757

Model saved in ..\results\models_modelling4\AdaBoostClassifier_splashing_smotenc_opt-smotenc_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:33,  1.56it/s]

Progress: 1/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:33,  1.55it/s]

Progress: 2/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:32,  1.55it/s]

Progress: 3/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:32,  1.55it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:03<00:31,  1.53it/s]

Progress: 5/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:31,  1.53it/s]

Progress: 6/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:30,  1.55it/s]

Progress: 7/54.	Score: 0.8464285714285714.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:05<00:29,  1.56it/s]

Progress: 8/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:28,  1.55it/s]

Progress: 9/54.	Score: 0.7904490377761939.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:06<00:28,  1.55it/s]

Progress: 10/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:07<00:27,  1.54it/s]

Progress: 11/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:27,  1.53it/s]

Progress: 12/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:08<00:26,  1.55it/s]

Progress: 13/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:09<00:25,  1.56it/s]

Progress: 14/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:09<00:25,  1.55it/s]

Progress: 15/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:10<00:24,  1.55it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:10<00:23,  1.55it/s]

Progress: 17/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:11<00:23,  1.55it/s]

Progress: 18/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:12<00:22,  1.55it/s]

Progress: 19/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:12<00:21,  1.57it/s]

Progress: 20/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:13<00:21,  1.57it/s]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:14<00:20,  1.56it/s]

Progress: 22/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:14<00:19,  1.55it/s]

Progress: 23/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:15<00:19,  1.55it/s]

Progress: 24/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:16<00:18,  1.56it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:16<00:18,  1.52it/s]

Progress: 26/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:17<00:17,  1.53it/s]

Progress: 27/54.	Score: 0.7922705314009661.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:18<00:16,  1.53it/s]

Progress: 28/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:18<00:16,  1.52it/s]

Progress: 29/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:19<00:15,  1.53it/s]

Progress: 30/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:20<00:14,  1.55it/s]

Progress: 31/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:20<00:14,  1.55it/s]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:21<00:13,  1.56it/s]

Progress: 33/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:21<00:12,  1.56it/s]

Progress: 34/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:22<00:12,  1.55it/s]

Progress: 35/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:23<00:11,  1.55it/s]

Progress: 36/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:23<00:10,  1.56it/s]

Progress: 37/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:24<00:10,  1.58it/s]

Progress: 38/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:25<00:09,  1.56it/s]

Progress: 39/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:25<00:08,  1.56it/s]

Progress: 40/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:26<00:08,  1.56it/s]

Progress: 41/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:27<00:07,  1.54it/s]

Progress: 42/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:27<00:07,  1.56it/s]

Progress: 43/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:28<00:06,  1.57it/s]

Progress: 44/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:28<00:05,  1.57it/s]

Progress: 45/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:29<00:05,  1.56it/s]

Progress: 46/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:30<00:04,  1.56it/s]

Progress: 47/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:30<00:03,  1.55it/s]

Progress: 48/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:31<00:03,  1.56it/s]

Progress: 49/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:32<00:02,  1.57it/s]

Progress: 50/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:32<00:01,  1.57it/s]

Progress: 51/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:33<00:01,  1.56it/s]

Progress: 52/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:34<00:00,  1.55it/s]

Progress: 53/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:34<00:00,  1.55it/s]

Progress: 54/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8503207412687099
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.938182
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.820946
cv_test_accuracy_balanced_median                                           0.838828
cv_test_roc_auc_median                                                     0.941392
cv_test_f1_median                                                              0.75
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.891892

Model saved in ..\results\models_modelling4\AdaBoostClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<00:53,  1.01s/it]

Progress: 1/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<00:53,  1.02s/it]

Progress: 2/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:03<00:52,  1.02s/it]

Progress: 3/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:04<00:51,  1.04s/it]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:05<00:50,  1.04s/it]

Progress: 5/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:06<00:49,  1.04s/it]

Progress: 6/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:07<00:48,  1.03s/it]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:08<00:47,  1.02s/it]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:09<00:46,  1.02s/it]

Progress: 9/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:10<00:45,  1.03s/it]

Progress: 10/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:11<00:44,  1.03s/it]

Progress: 11/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:12<00:43,  1.03s/it]

Progress: 12/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:13<00:41,  1.02s/it]

Progress: 13/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:14<00:40,  1.02s/it]

Progress: 14/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:15<00:39,  1.02s/it]

Progress: 15/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:16<00:38,  1.03s/it]

Progress: 16/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:17<00:38,  1.03s/it]

Progress: 17/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:18<00:37,  1.05s/it]

Progress: 18/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:19<00:36,  1.04s/it]

Progress: 19/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:20<00:35,  1.03s/it]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:21<00:33,  1.03s/it]

Progress: 21/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:22<00:32,  1.03s/it]

Progress: 22/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:23<00:31,  1.03s/it]

Progress: 23/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:24<00:30,  1.03s/it]

Progress: 24/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:25<00:29,  1.02s/it]

Progress: 25/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:26<00:28,  1.02s/it]

Progress: 26/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:27<00:27,  1.02s/it]

Progress: 27/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:28<00:26,  1.02s/it]

Progress: 28/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:29<00:25,  1.03s/it]

Progress: 29/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:30<00:24,  1.03s/it]

Progress: 30/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:31<00:23,  1.02s/it]

Progress: 31/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:32<00:22,  1.02s/it]

Progress: 32/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:33<00:21,  1.02s/it]

Progress: 33/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:34<00:20,  1.02s/it]

Progress: 34/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:35<00:19,  1.03s/it]

Progress: 35/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:36<00:18,  1.04s/it]

Progress: 36/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:37<00:17,  1.03s/it]

Progress: 37/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:39<00:16,  1.02s/it]

Progress: 38/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:40<00:15,  1.02s/it]

Progress: 39/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:41<00:14,  1.02s/it]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:42<00:13,  1.03s/it]

Progress: 41/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:43<00:12,  1.03s/it]

Progress: 42/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:44<00:11,  1.02s/it]

Progress: 43/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:45<00:10,  1.02s/it]

Progress: 44/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:46<00:09,  1.02s/it]

Progress: 45/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:47<00:08,  1.02s/it]

Progress: 46/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:48<00:07,  1.03s/it]

Progress: 47/54.	Score: 0.9210031347962382.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:49<00:06,  1.03s/it]

Progress: 48/54.	Score: 0.9210031347962382.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:50<00:05,  1.02s/it]

Progress: 49/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:51<00:04,  1.02s/it]

Progress: 50/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:52<00:03,  1.02s/it]

Progress: 51/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:53<00:02,  1.02s/it]

Progress: 52/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:54<00:01,  1.02s/it]

Progress: 53/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:55<00:00,  1.03s/it]

Progress: 54/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.9210031347962382
Best params: {'k_neighbors': 9, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smotenc_opt-s...
holdout_test_f1_macro                                                      0.806892
holdout_test_accuracy_balanced                                             0.799769
holdout_test_roc_auc                                                       0.934799
holdout_test_f1                                                            0.868687
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.876935
cv_test_roc_auc_median                                                     0.948142
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.888889
cv_test_f1_class_0_median                                                  0.842105

Model saved in ..\results\models_modelling4\RandomForestClassifier_splashing_smotenc_opt-smotenc_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<00:53,  1.01s/it]

Progress: 1/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<00:53,  1.02s/it]

Progress: 2/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:03<00:51,  1.02s/it]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:04<00:51,  1.02s/it]

Progress: 4/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:05<00:50,  1.03s/it]

Progress: 5/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:06<00:49,  1.03s/it]

Progress: 6/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:07<00:48,  1.02s/it]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:08<00:46,  1.02s/it]

Progress: 8/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:09<00:45,  1.02s/it]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:10<00:44,  1.02s/it]

Progress: 10/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:11<00:44,  1.03s/it]

Progress: 11/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:12<00:43,  1.03s/it]

Progress: 12/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:13<00:41,  1.02s/it]

Progress: 13/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:14<00:40,  1.01s/it]

Progress: 14/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:15<00:39,  1.02s/it]

Progress: 15/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:16<00:38,  1.02s/it]

Progress: 16/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:17<00:38,  1.03s/it]

Progress: 17/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:18<00:37,  1.03s/it]

Progress: 18/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:19<00:35,  1.03s/it]

Progress: 19/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:20<00:34,  1.02s/it]

Progress: 20/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:21<00:33,  1.02s/it]

Progress: 21/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:22<00:32,  1.02s/it]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:23<00:31,  1.03s/it]

Progress: 23/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:24<00:31,  1.04s/it]

Progress: 24/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:25<00:29,  1.02s/it]

Progress: 25/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:26<00:28,  1.02s/it]

Progress: 26/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:27<00:27,  1.01s/it]

Progress: 27/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:28<00:26,  1.02s/it]

Progress: 28/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:29<00:25,  1.03s/it]

Progress: 29/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:30<00:24,  1.03s/it]

Progress: 30/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:31<00:23,  1.02s/it]

Progress: 31/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:32<00:22,  1.02s/it]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:33<00:21,  1.02s/it]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:34<00:20,  1.02s/it]

Progress: 34/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:35<00:19,  1.03s/it]

Progress: 35/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:36<00:18,  1.03s/it]

Progress: 36/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:37<00:17,  1.02s/it]

Progress: 37/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:38<00:16,  1.02s/it]

Progress: 38/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:39<00:15,  1.01s/it]

Progress: 39/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:40<00:14,  1.02s/it]

Progress: 40/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:41<00:13,  1.03s/it]

Progress: 41/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:43<00:12,  1.03s/it]

Progress: 42/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:43<00:11,  1.02s/it]

Progress: 43/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:44<00:10,  1.01s/it]

Progress: 44/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:46<00:09,  1.01s/it]

Progress: 45/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:47<00:08,  1.02s/it]

Progress: 46/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:48<00:07,  1.03s/it]

Progress: 47/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:49<00:06,  1.03s/it]

Progress: 48/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:50<00:05,  1.02s/it]

Progress: 49/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:51<00:04,  1.01s/it]

Progress: 50/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:52<00:03,  1.02s/it]

Progress: 51/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:53<00:02,  1.02s/it]

Progress: 52/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:54<00:01,  1.03s/it]

Progress: 53/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:55<00:00,  1.02s/it]

Progress: 54/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8590163934426229
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.900794
holdout_test_accuracy_balanced                                             0.913636
holdout_test_roc_auc                                                           0.98
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.935065

Model saved in ..\results\models_modelling4\RandomForestClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:22,  2.40it/s]

Progress: 1/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:18,  2.82it/s]

Progress: 2/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:18,  2.79it/s]

Progress: 3/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:17,  2.92it/s]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:16,  2.96it/s]

Progress: 5/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:16,  2.96it/s]

Progress: 6/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.03it/s]

Progress: 7/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:15,  3.05it/s]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:15,  2.97it/s]

Progress: 9/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  2.96it/s]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:14,  2.98it/s]

Progress: 11/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:14,  2.97it/s]

Progress: 12/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.02it/s]

Progress: 13/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:13,  3.06it/s]

Progress: 14/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:05<00:12,  3.03it/s]

Progress: 15/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  2.98it/s]

Progress: 16/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  2.96it/s]

Progress: 17/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:06<00:12,  2.97it/s]

Progress: 18/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:11,  3.03it/s]

Progress: 19/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:11,  3.06it/s]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:07<00:10,  3.07it/s]

Progress: 21/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:10,  2.99it/s]

Progress: 22/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  2.97it/s]

Progress: 23/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:08<00:10,  2.96it/s]

Progress: 24/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:08<00:09,  3.00it/s]

Progress: 25/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:09,  2.94it/s]

Progress: 26/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:09<00:09,  2.98it/s]

Progress: 27/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:09<00:08,  2.92it/s]

Progress: 28/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.93it/s]

Progress: 29/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:10<00:08,  2.93it/s]

Progress: 30/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:10<00:07,  2.99it/s]

Progress: 31/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.04it/s]

Progress: 32/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:11<00:06,  3.04it/s]

Progress: 33/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:11<00:06,  3.03it/s]

Progress: 34/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  2.82it/s]

Progress: 35/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:12<00:06,  2.84it/s]

Progress: 36/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:12<00:05,  2.92it/s]

Progress: 37/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  2.97it/s]

Progress: 38/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:13<00:05,  2.99it/s]

Progress: 39/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:13<00:04,  2.97it/s]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:04,  2.84it/s]

Progress: 41/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:14<00:04,  2.85it/s]

Progress: 42/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:14<00:03,  2.93it/s]

Progress: 43/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:14<00:03,  2.94it/s]

Progress: 44/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:15<00:03,  2.97it/s]

Progress: 45/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:15<00:02,  2.98it/s]

Progress: 46/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:15<00:02,  2.89it/s]

Progress: 47/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:16<00:02,  2.92it/s]

Progress: 48/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:16<00:01,  2.99it/s]

Progress: 49/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:16<00:01,  3.01it/s]

Progress: 50/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:17<00:00,  3.03it/s]

Progress: 51/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:17<00:00,  3.02it/s]

Progress: 52/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:17<00:00,  2.99it/s]

Progress: 53/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:18<00:00,  2.96it/s]

Progress: 54/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8962962962962964
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smotenc_opt-smotenc_d...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.939815
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.900155
cv_test_roc_auc_median                                                      0.94127
cv_test_f1_median                                                          0.927536
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.888889
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.864865

Model saved in ..\results\models_modelling4\LGBMClassifier_splashing_smotenc_opt-smotenc_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:16,  3.26it/s]

Progress: 1/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:16,  3.11it/s]

Progress: 2/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:17,  2.96it/s]

Progress: 3/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:16,  3.00it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:16,  3.00it/s]

Progress: 5/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:15,  3.01it/s]

Progress: 6/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.09it/s]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:14,  3.12it/s]

Progress: 8/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:14,  3.04it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  3.05it/s]

Progress: 10/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:14,  3.05it/s]

Progress: 11/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:13,  3.01it/s]

Progress: 12/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.09it/s]

Progress: 13/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:12,  3.12it/s]

Progress: 14/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:12,  3.13it/s]

Progress: 15/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  3.02it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  3.02it/s]

Progress: 17/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:11,  3.02it/s]

Progress: 18/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:11,  3.10it/s]

Progress: 19/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:10,  3.14it/s]

Progress: 20/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:10,  3.15it/s]

Progress: 21/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:10,  3.04it/s]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  3.04it/s]

Progress: 23/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.04it/s]

Progress: 24/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:08<00:09,  3.11it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:09,  3.03it/s]

Progress: 26/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.07it/s]

Progress: 27/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:09<00:08,  3.04it/s]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.95it/s]

Progress: 29/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:08,  2.97it/s]

Progress: 30/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:10<00:07,  3.06it/s]

Progress: 31/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.11it/s]

Progress: 32/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.13it/s]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:11<00:06,  3.10it/s]

Progress: 34/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  2.98it/s]

Progress: 35/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:06,  2.96it/s]

Progress: 36/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:12<00:05,  3.04it/s]

Progress: 37/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  3.09it/s]

Progress: 38/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.09it/s]

Progress: 39/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:13<00:04,  3.07it/s]

Progress: 40/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:04,  3.04it/s]

Progress: 41/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:04,  2.94it/s]

Progress: 42/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:14<00:03,  3.02it/s]

Progress: 43/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:14<00:03,  3.09it/s]

Progress: 44/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.12it/s]

Progress: 45/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:15<00:02,  3.11it/s]

Progress: 46/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:15<00:02,  3.06it/s]

Progress: 47/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:15<00:02,  2.98it/s]

Progress: 48/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:16<00:01,  3.04it/s]

Progress: 49/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:16<00:01,  3.09it/s]

Progress: 50/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:00,  3.10it/s]

Progress: 51/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:17<00:00,  3.10it/s]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:17<00:00,  3.07it/s]

Progress: 53/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.05it/s]

Progress: 54/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8590163934426229
Best params: {'k_neighbors': 4, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_opt-sm...
holdout_test_f1_macro                                                      0.933862
holdout_test_accuracy_balanced                                             0.947727
holdout_test_roc_auc                                                           0.99
holdout_test_f1                                                            0.904762
holdout_test_accuracy                                                      0.946667
cv_test_f1_macro_median                                                    0.876543
cv_test_accuracy_balanced_median                                           0.857143
cv_test_roc_auc_median                                                     0.979487
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.938272

Model saved in ..\results\models_modelling4\LGBMClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# For the notebook with Model optimization!

In [23]:
# def update_estimator_params(
#     ml_pipe:MLPipeline,
#     suggested_params:dict,
# ) -> dict:
#     """Update the estimator parameters based on the pipeline parameters.

#     Args:
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.
#         suggested_params: A dictionary containing the suggested Estimator hyperparameters.
    
#     Returns:
#         A dictionary containing the estimator parameters.
#     """
#     estimator_params = ml_pipe._pipeline_params['estimator_params']
#     estimator_params.update(suggested_params)
#     return estimator_params

# def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
#     """Objective function for logistic regression optimization using Optuna.

#     Args:
#         trial: An Optuna trial object used to suggest hyperparameters.
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.

#     Returns:
#         The score of the model based on the specified evaluation metric.
#     """
    
#     categorical_features = ('wettability', 'inclination')
    
#     random_state = ml_pipe._pipeline_params['random_state']
    
#     # sample params
#     C = trial.suggest_loguniform('C', 1e-4, 1e3)
    
#     # SMOTE params
#     add_smote = trial.suggest_categorical('add_smote', [True, False])
#     if add_smote:
#         is_smotenc = trial.suggest_categorical('is_smotenc', [True, False])
#         smote_params = {
#             'sampling_strategy': trial.suggest_categorical(
#                 'sampling_strategy', [0.6, 0.7, 0.8, 0.9, 1.0]
#             ),
#             'k_neighbors': trial.suggest_int('k_neighbors', 3, 10),
#             'random_state': random_state,
#         }
#     else:
#         is_smotenc = False
#         smote_params = None
#     if is_smotenc:
#         wettability_cat = trial.suggest_categorical('wettability_cat', [True, False])
#         if wettability_cat:
#             inclination_cat = trial.suggest_categorical('inclination_cat', [True, False])
#         else:
#             inclination_cat = True
        
        
#         mask = [wettability_cat, inclination_cat]
        
#         masked_features = [
#             feature for feature, mask_value in zip(categorical_features, mask) 
#             if mask_value
#         ]
#         smote_params = {
#             **smote_params,
#             'categorical_features': masked_features,
#         }

#     suggested_params = {
#         "C": C,
#     }
    
#     estimator_params = update_estimator_params(ml_pipe, suggested_params)

#     estimator = LogisticRegression(
#         **estimator_params,
#         random_state=random_state,
#     )

#     score = ml_pipe.step(
#         estimator=estimator,
#         add_smote=add_smote,
#         is_smotenc=is_smotenc,
#         smote_params=smote_params,
#     )
    
#     return score



# opt = OptunaOptimizer(
#     objective=partial(logreg_objective, ml_pipe=ml_pipe),
#     study_name="logreg_study",
#     direction="maximize",
# )

# opt.optimize(n_trials=200)

# best_params = opt.study.best_trial.params
# display(best_params)
# # estimator_params = update_estimator_params(ml_pipe, best_params)

# # estimator = LogisticRegression(
# #     **estimator_params,
# #     random_state=ml_pipe._pipeline_params['random_state'],
# # )