# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import logging

# Set logging level for PyTorch Tabular
logging.getLogger("pytorch_tabular").setLevel(logging.ERROR)

# Set logging level for PyTorch Lightning
logging.getLogger("pytorch_lightning").setLevel(logging.ERROR)

# Set logging level for Lightning Fabric
logging.getLogger("lightning_fabric").setLevel(logging.ERROR)

# Disable device availability messages
logging.getLogger("lightning.pytorch.utilities.rank_zero").setLevel(logging.FATAL)

import pandas as pd
import numpy as np

from pytorch_tabular.models import CategoryEmbeddingModelConfig, TabNetModelConfig

import optuna

from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    PytorchTabularEstimator,
    deep_update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

# from pytorch_lightning.loggers import MLFlowLogger
from pytorch_lightning.loggers import TensorBoardLogger

seed = RANDOM_STATE

# Fix error with save weights

# import torch
# # from omegaconf import DictConfig
# # from omegaconf.base import ContainerMetadata
# # import typing
# # torch.serialization.add_safe_globals([DictConfig, ContainerMetadata, typing.Any])
# import pytorch_tabular.utils.python_utils as pt_utils
# pt_utils.pl_load = lambda f, map_location: torch.load(f, map_location=map_location, weights_only=False)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
warnings.filterwarnings("ignore")

In [4]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1

# Settings

In [4]:
model_postfix = 'opt-model'

scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 500

save_model_and_metrics = True
metrics_file = "metrics_modelling4_6-neural_networks.xlsx"

## Optimization function

In [6]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    add_smote:bool,
    is_smotenc:bool,
    smote_params:dict,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    opt_cv_folds:int=5,
    seed:int=seed,
):
    
    estimator_params = estimator_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
        cv_folds=opt_cv_folds,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    print('raw best_params')
    display(best_params)
    
    if params_to_process:
        for param in params_to_process:
            if param == 'log2_size':
                keys = [k for k in best_params.keys() if param in k]
                sorted_keys = sorted(keys, key=lambda k: int(k.split("_")[1]))
                layer_sizes = [
                    2**best_params.pop(key)
                    for key in sorted_keys
                ]
                best_params['layers'] = '-'.join(map(str, layer_sizes))
            elif param == 'num_layers':
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params.pop(key)
            else: # Other cases
                # Find one key in best_params which contains param
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    suggested_estimator_params = {
        "model_config_params": best_params
    }
    best_estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_estimator_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

## MultiLayer Perceptron (MLP)

In [7]:

def MLP_objective(
    trial:optuna.trial.Trial, 
    ml_pipe:MLPipeline,
):
    
    num_layers = trial.suggest_int('num_layers', 1, 3) # number of hidden layers
    layer_sizes = [
        2**trial.suggest_int(f'layer_{i}_log2_size', 2, 7)
        for i in range(num_layers)
    ]
    layers = '-'.join(map(str, layer_sizes))
    # activation = trial.suggest_categorical('activation', ['ReLU', 'LeakyReLU', 'ELU'])
    dropout = trial.suggest_float('dropout', 0.0, 0.5)
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1, log=True)
    # use_batch_norm = trial.suggest_categorical('use_batch_norm', [True, False])
    # batch_norm_continuous_input = trial.suggest_categorical('batch_norm_continuous_input', [True, False])
    
    suggested_estimator_params = {
        "model_config_params": {
            'layers': layers,
            # 'activation': activation,
            'dropout': dropout,
            # 'batch_norm_continuous_input': batch_norm_continuous_input,
            # 'use_batch_norm': use_batch_norm,
            'learning_rate': learning_rate,
        }
    }
    
    estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

In [8]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

params_to_process = [
    'num_layers', # drop this param
    'log2_size', # process to get string of layer sizes
]

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # Other params SET in optuna
    "model_config_params": {
        'activation': 'LeakyReLU',
        'batch_norm_continuous_input': True, # We already have normalized features    
        'use_batch_norm': False, # For hidden layers
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'gpu',
        'devices': 1,
        'progress_bar': 'none',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=MLP_objective,
    n_trials=n_trials,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-28 13:38:02,288] A new study created in memory with name: model_study
[I 2025-04-28 13:38:51,857] Trial 0 finished with value: 0.8003274042002481 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.2993292420985183, 'learning_rate': 4.207988669606632e-05}. Best is trial 0 with value: 0.8003274042002481.
[I 2025-04-28 13:39:24,084] Trial 1 finished with value: 0.7813968759912614 and parameters: {'num_layers': 1, 'layer_0_log2_size': 2, 'dropout': 0.4330880728874676, 'learning_rate': 0.002537815508265664}. Best is trial 0 with value: 0.8003274042002481.
[I 2025-04-28 13:40:14,589] Trial 2 finished with value: 0.7101735331057573 and parameters: {'num_layers': 3, 'layer_0_log2_size': 2, 'layer_1_log2_size': 7, 'layer_2_log2_size': 6, 'dropout': 0.10616955533913808, 'learning_rate': 5.3370327626039544e-05}. Best is trial 0 with value: 0.8003274042002481.
[I 2025-04-28 13:41:01,181] Trial 3 finished with value: 0.581338499901601 and parameters: {'num_layers': 1, 'layer_0_log2_size': 3, 'dropout': 0.2623782158161189, 'learning_rate': 0.0005342937261279777}. Best is trial 0 with value: 0.8003274042002481.
[I 2025-04-28 13:41:49,243] Trial 4 finished with value: 0.5220996594531748 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.06974693032602092, 'learning_rate': 0.00014742753159914678}. Best is trial 0 with value: 0.8003274042002481.
[I 2025-04-28 13:42:35,753] Trial 5 finished with value: 0.8294674524836119 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 6, 'dropout': 0.09983689107917987, 'learning_rate': 0.0011400863701127321}. Best is trial 5 with value: 0.8294674524836119.
[I 2025-04-28 13:43:23,773] Trial 6 finished with value: 0.3902595214933243 and parameters: {'num_layers': 2, 'layer_0_log2_size': 2, 'layer_1_log2_size': 5, 'dropout': 0.08526206184364576, 'learning_rate': 1.8205657658407255e-05}. Best is trial 5 with value: 0.8294674524836119.
[I 2025-04-28 13:43:31,996] Trial 7 finished with value: 0.8534542714775272 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'layer_2_log2_size': 3, 'dropout': 0.048836057003191935, 'learning_rate': 0.005456725485601475}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:43:42,285] Trial 8 finished with value: 0.8160259824715848 and parameters: {'num_layers': 2, 'layer_0_log2_size': 2, 'layer_1_log2_size': 4, 'dropout': 0.017194260557609198, 'learning_rate': 0.04337920697490941}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:44:29,714] Trial 9 finished with value: 0.8447735979044297 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.15585553804470548, 'learning_rate': 0.0012030178871154666}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:44:49,321] Trial 10 finished with value: 0.8488396740590188 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 2, 'layer_2_log2_size': 2, 'dropout': 0.3694232604167318, 'learning_rate': 0.02182320840357852}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:45:05,658] Trial 11 finished with value: 0.7884204097273542 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 2, 'layer_2_log2_size': 2, 'dropout': 0.39588088761694007, 'learning_rate': 0.015422934063981618}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:45:12,731] Trial 12 finished with value: 0.2870542191676212 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 2, 'layer_2_log2_size': 2, 'dropout': 0.3479292819994465, 'learning_rate': 0.008350111228220668}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:45:22,858] Trial 13 finished with value: 0.7701838946164937 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'layer_2_log2_size': 3, 'dropout': 0.4960062421727993, 'learning_rate': 0.05195803225265041}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:45:40,205] Trial 14 finished with value: 0.83622914301476 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 3, 'layer_2_log2_size': 4, 'dropout': 0.21798334855263535, 'learning_rate': 0.008307495527720761}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:45:49,771] Trial 15 finished with value: 0.8286156594796893 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'layer_2_log2_size': 4, 'dropout': 0.20047798484102197, 'learning_rate': 0.09825198793805799}. Best is trial 7 with value: 0.8534542714775272.
[I 2025-04-28 13:46:17,017] Trial 16 finished with value: 0.869037954323144 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'layer_2_log2_size': 2, 'dropout': 0.3245372405489969, 'learning_rate': 0.0038275981090023876}. Best is trial 16 with value: 0.869037954323144.
[I 2025-04-28 13:46:33,871] Trial 17 finished with value: 0.8568643479853989 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'dropout': 0.3123504466782651, 'learning_rate': 0.003469705094608335}. Best is trial 16 with value: 0.869037954323144.
[I 2025-04-28 13:47:23,007] Trial 18 finished with value: 0.7756875532071443 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 5, 'dropout': 0.31491328943785335, 'learning_rate': 0.0002967095810581384}. Best is trial 16 with value: 0.869037954323144.
[I 2025-04-28 13:48:10,750] Trial 19 finished with value: 0.848993963922204 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 5, 'dropout': 0.4386408185869067, 'learning_rate': 0.002692990840562183}. Best is trial 16 with value: 0.869037954323144.
[I 2025-04-28 13:48:35,311] Trial 20 finished with value: 0.8814663015693492 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.27439323066509763, 'learning_rate': 0.0030356357951435422}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:48:56,938] Trial 21 finished with value: 0.8774416066797197 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.261962120025848, 'learning_rate': 0.0032947826523106512}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:49:30,446] Trial 22 finished with value: 0.8704694875127554 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.2279573025365632, 'learning_rate': 0.001716805231497902}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:50:19,233] Trial 23 finished with value: 0.8154578783498734 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 3, 'dropout': 0.2649312319829734, 'learning_rate': 0.0008323609460812727}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:51:09,418] Trial 24 finished with value: 0.8117644733205374 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 3, 'dropout': 0.19964732415940323, 'learning_rate': 0.0003688151284720268}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:51:50,654] Trial 25 finished with value: 0.8449686867060233 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 4, 'dropout': 0.15650606717405885, 'learning_rate': 0.0017132565640888384}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:52:39,763] Trial 26 finished with value: 0.5001742294681645 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 4, 'dropout': 0.2509037532794906, 'learning_rate': 0.00013411235472208757}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:52:49,221] Trial 27 finished with value: 0.845070073254276 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.13666492583884704, 'learning_rate': 0.01121369305017651}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:53:38,001] Trial 28 finished with value: 0.7851939245370952 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 3, 'dropout': 0.220975710994944, 'learning_rate': 0.0005850503246588153}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:53:51,816] Trial 29 finished with value: 0.8559335537071359 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 4, 'dropout': 0.28626453999367135, 'learning_rate': 0.005344567940048474}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:54:30,115] Trial 30 finished with value: 0.8674353225727554 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.17748423890229428, 'learning_rate': 0.001484705818497141}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:54:53,721] Trial 31 finished with value: 0.8426348802980413 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.3437936940559256, 'learning_rate': 0.004821742208673096}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:55:17,033] Trial 32 finished with value: 0.8522686226228435 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.29205166379841463, 'learning_rate': 0.0024603004354796267}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:55:26,647] Trial 33 finished with value: 0.8586921426769493 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 3, 'dropout': 0.23848245269968218, 'learning_rate': 0.023748449587085392}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:56:00,505] Trial 34 finished with value: 0.8678341440571146 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.33537122796705326, 'learning_rate': 0.0022132703243358596}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:56:42,468] Trial 35 finished with value: 0.856223775719512 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.3872072463393005, 'learning_rate': 0.003364212048332615}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:57:16,833] Trial 36 finished with value: 0.8563105459733367 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'layer_2_log2_size': 7, 'dropout': 0.2847187050396487, 'learning_rate': 0.0007351652624162357}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:58:03,155] Trial 37 finished with value: 0.3727124575882738 and parameters: {'num_layers': 1, 'layer_0_log2_size': 3, 'dropout': 0.2609732229875181, 'learning_rate': 0.00020214602716496356}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:58:52,307] Trial 38 finished with value: 0.6685008636532379 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 6, 'dropout': 0.4200264446466196, 'learning_rate': 8.089824404862198e-05}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 13:59:12,078] Trial 39 finished with value: 0.8396842388542491 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.3264967683927868, 'learning_rate': 0.0063478087036752924}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:00:00,362] Trial 40 finished with value: 0.847250926684698 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 5, 'dropout': 0.23955348624645623, 'learning_rate': 0.0013020944105728268}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:00:38,625] Trial 41 finished with value: 0.8573072090635019 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.339321605997125, 'learning_rate': 0.0019438101698510473}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:01:06,842] Trial 42 finished with value: 0.8565704774915301 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.3699472591615606, 'learning_rate': 0.003722738884263301}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:01:55,486] Trial 43 finished with value: 0.4569078823428116 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 3, 'dropout': 0.27196561868920277, 'learning_rate': 1.627971322865159e-05}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:02:32,768] Trial 44 finished with value: 0.8496846222194323 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'dropout': 0.2912493416550591, 'learning_rate': 0.000948633038772642}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:03:19,855] Trial 45 finished with value: 0.8484421473358081 and parameters: {'num_layers': 3, 'layer_0_log2_size': 5, 'layer_1_log2_size': 4, 'layer_2_log2_size': 5, 'dropout': 0.308514394269259, 'learning_rate': 0.002142462514225316}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:03:28,412] Trial 46 finished with value: 0.8547626940197954 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 4, 'dropout': 0.22754433768527038, 'learning_rate': 0.012830545822065682}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:03:39,431] Trial 47 finished with value: 0.8291032998482013 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 6, 'layer_2_log2_size': 5, 'dropout': 0.3661764172685276, 'learning_rate': 0.018946475196291515}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:03:50,203] Trial 48 finished with value: 0.8454339157056598 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.3235105686111102, 'learning_rate': 0.009047821108077475}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:04:39,402] Trial 49 finished with value: 0.836150484907922 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 3, 'dropout': 0.20109625043564114, 'learning_rate': 0.0004827459988124078}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:05:03,337] Trial 50 finished with value: 0.8217217379011492 and parameters: {'num_layers': 3, 'layer_0_log2_size': 5, 'layer_1_log2_size': 4, 'layer_2_log2_size': 3, 'dropout': 0.18045138099220204, 'learning_rate': 0.004514201780818136}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:05:46,252] Trial 51 finished with value: 0.8674353225727554 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.13032230242052528, 'learning_rate': 0.0012313654905709186}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:06:24,745] Trial 52 finished with value: 0.8707632099186144 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.16694037797110706, 'learning_rate': 0.0016155421093286956}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:06:52,727] Trial 53 finished with value: 0.856541933650778 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.09612558714669833, 'learning_rate': 0.002656345198550733}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:07:24,064] Trial 54 finished with value: 0.8318251948891264 and parameters: {'num_layers': 1, 'layer_0_log2_size': 3, 'dropout': 0.042581782918951816, 'learning_rate': 0.0072218839100466545}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:07:48,934] Trial 55 finished with value: 0.8696674995837738 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.17664026802990931, 'learning_rate': 0.0018247313500352586}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:08:35,995] Trial 56 finished with value: 0.4896151778111972 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.17815477148714706, 'learning_rate': 2.8723037120309836e-05}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:08:54,582] Trial 57 finished with value: 0.8798352327873641 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.15050806637560032, 'learning_rate': 0.0032375268582840156}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:09:38,409] Trial 58 finished with value: 0.8731368984020097 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.1288264312706819, 'learning_rate': 0.0007025133708898654}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:10:22,270] Trial 59 finished with value: 0.8696674995837738 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.10871869947452352, 'learning_rate': 0.0006965199586630276}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:11:10,213] Trial 60 finished with value: 0.8717221922631244 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.07139388268779828, 'learning_rate': 0.0003702428171668363}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:11:58,211] Trial 61 finished with value: 0.8472046368682875 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.07723515032026405, 'learning_rate': 0.00029954045025529376}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:12:45,894] Trial 62 finished with value: 0.875259665389977 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.05363694715612549, 'learning_rate': 0.0004015543680874044}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:13:33,420] Trial 63 finished with value: 0.874941907379218 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.006140027846881141, 'learning_rate': 0.0004096093818694547}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:14:19,268] Trial 64 finished with value: 0.8317705746885615 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.0018244315092710572, 'learning_rate': 0.000189182252653471}. Best is trial 20 with value: 0.8814663015693492.
[I 2025-04-28 14:15:06,393] Trial 65 finished with value: 0.8820939220312324 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.050042548500283675, 'learning_rate': 0.00044205682418629394}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:15:54,340] Trial 66 finished with value: 0.7416025120644569 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.04635673438230077, 'learning_rate': 0.00011065051525092814}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:16:41,571] Trial 67 finished with value: 0.8816824346950363 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.028740769344937984, 'learning_rate': 0.00046614392721361917}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:17:26,992] Trial 68 finished with value: 0.8777427831519162 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.031801687605923376, 'learning_rate': 0.0005135436062013428}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:18:14,476] Trial 69 finished with value: 0.8439324855139443 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.019051371675028073, 'learning_rate': 0.00024060435863271101}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:18:55,594] Trial 70 finished with value: 0.8770656634651555 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.02778783556928716, 'learning_rate': 0.001006177575784713}. Best is trial 65 with value: 0.8820939220312324.
[I 2025-04-28 14:19:35,483] Trial 71 finished with value: 0.8770133249191607 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.03838003558760317, 'learning_rate': 0.0009117304760915726}. Best is trial 65 with value: 0.8820939220312324.

raw best_params

{'num_layers': 1,
 'layer_0_log2_size': 7,
 'dropout': 0.04379983378244369,
 'learning_rate': 0.009487772841911948}

best_params

{'dropout': 0.04379983378244369,
 'learning_rate': 0.009487772841911948,
 'layers': '128'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "PytorchTabularEstimator"

                                                                                 0
target                                                                   splashing
model                             CategoryEmbeddingModel_splashing_smote_opt-model
holdout_test_f1_macro                                                         0.82
holdout_test_accuracy_balanced                                            0.810185
holdout_test_roc_auc                                                      0.911265
holdout_test_f1                                                               0.88
holdout_test_accuracy                                                         0.84
cv_test_f1_macro_median                                                   0.842262
cv_test_accuracy_balanced_median                                          0.859133
cv_test_roc_auc_median                                                    0.925697
cv_test_f1_median                                                         0.878788
cv_test_accuracy_median                                                   0.849057
cv_test_precision_class_0_median                                          0.761905
cv_test_recall_class_0_median                                             0.894737
cv_test_f1_class_0_median                                                 0.809524

Model saved in ..\results\models_modelling4\CategoryEmbeddingModel_splashing_smote_opt-model

In [9]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

params_to_process = [
    'num_layers', # drop this param
    'log2_size', # process to get string of layer sizes
]

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'activation': 'LeakyReLU',
        'batch_norm_continuous_input': True, # We already have normalized features    
        'use_batch_norm': False, # For hidden layers
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'gpu',
        'devices': 1,
        'progress_bar': 'none',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=MLP_objective,
    n_trials=n_trials,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-28 18:50:39,137] A new study created in memory with name: model_study
[I 2025-04-28 18:51:28,510] Trial 0 finished with value: 0.6150411034170871 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.2993292420985183, 'learning_rate': 4.207988669606632e-05}. Best is trial 0 with value: 0.6150411034170871.
[I 2025-04-28 18:52:14,716] Trial 1 finished with value: 0.801977214769256 and parameters: {'num_layers': 1, 'layer_0_log2_size': 2, 'dropout': 0.4330880728874676, 'learning_rate': 0.002537815508265664}. Best is trial 1 with value: 0.801977214769256.
[I 2025-04-28 18:52:56,442] Trial 2 finished with value: 0.6002371510928383 and parameters: {'num_layers': 3, 'layer_0_log2_size': 2, 'layer_1_log2_size': 7, 'layer_2_log2_size': 6, 'dropout': 0.10616955533913808, 'learning_rate': 5.3370327626039544e-05}. Best is trial 1 with value: 0.801977214769256.
[I 2025-04-28 18:53:42,190] Trial 3 finished with value: 0.5975988787818831 and parameters: {'num_layers': 1, 'layer_0_log2_size': 3, 'dropout': 0.2623782158161189, 'learning_rate': 0.0005342937261279777}. Best is trial 1 with value: 0.801977214769256.
[I 2025-04-28 18:54:28,746] Trial 4 finished with value: 0.6379873202126056 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.06974693032602092, 'learning_rate': 0.00014742753159914678}. Best is trial 1 with value: 0.801977214769256.
[I 2025-04-28 18:55:12,146] Trial 5 finished with value: 0.8485258020129379 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 6, 'dropout': 0.09983689107917987, 'learning_rate': 0.0011400863701127321}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:55:59,604] Trial 6 finished with value: 0.3408177987110336 and parameters: {'num_layers': 2, 'layer_0_log2_size': 2, 'layer_1_log2_size': 5, 'dropout': 0.08526206184364576, 'learning_rate': 1.8205657658407255e-05}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:56:09,816] Trial 7 finished with value: 0.8164817619136372 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'layer_2_log2_size': 3, 'dropout': 0.048836057003191935, 'learning_rate': 0.005456725485601475}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:56:19,220] Trial 8 finished with value: 0.7510398291572862 and parameters: {'num_layers': 2, 'layer_0_log2_size': 2, 'layer_1_log2_size': 4, 'dropout': 0.017194260557609198, 'learning_rate': 0.04337920697490941}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:57:06,785] Trial 9 finished with value: 0.838135823212356 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.15585553804470548, 'learning_rate': 0.0012030178871154666}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:57:23,009] Trial 10 finished with value: 0.8181135297608465 and parameters: {'num_layers': 3, 'layer_0_log2_size': 4, 'layer_1_log2_size': 2, 'layer_2_log2_size': 2, 'dropout': 0.186341918551015, 'learning_rate': 0.01617333092185683}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:58:11,694] Trial 11 finished with value: 0.8189353765255134 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.1673975881116182, 'learning_rate': 0.000942260292710256}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:59:00,286] Trial 12 finished with value: 0.5560011121089732 and parameters: {'num_layers': 2, 'layer_0_log2_size': 4, 'layer_1_log2_size': 3, 'dropout': 0.17292379631793203, 'learning_rate': 0.0003302215138678105}. Best is trial 5 with value: 0.8485258020129379.
[I 2025-04-28 18:59:26,936] Trial 13 finished with value: 0.8582402916717591 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.32059448652942835, 'learning_rate': 0.0030322671692095855}. Best is trial 13 with value: 0.8582402916717591.
[I 2025-04-28 18:59:36,965] Trial 14 finished with value: 0.8628912371045029 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'dropout': 0.35222343924640975, 'learning_rate': 0.008371292917424975}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 18:59:44,306] Trial 15 finished with value: 0.859609154689663 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.36504734107988973, 'learning_rate': 0.09639757903159533}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 18:59:53,482] Trial 16 finished with value: 0.7489824941133024 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'layer_2_log2_size': 7, 'dropout': 0.40739185950244894, 'learning_rate': 0.09511585593538852}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:00:02,608] Trial 17 finished with value: 0.8155631395683709 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'dropout': 0.4826689730327277, 'learning_rate': 0.017018728561304833}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:00:12,584] Trial 18 finished with value: 0.8519615739177983 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.37300502820426357, 'learning_rate': 0.015444267261455416}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:00:21,039] Trial 19 finished with value: 0.753525636218171 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.3490866024160897, 'learning_rate': 0.07534933229670161}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:00:31,517] Trial 20 finished with value: 0.8172010992491497 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'layer_2_log2_size': 5, 'dropout': 0.49879962954885393, 'learning_rate': 0.02922176856124598}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:00:50,717] Trial 21 finished with value: 0.8353800424909645 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.31259574882081825, 'learning_rate': 0.004932727940480199}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:01:03,873] Trial 22 finished with value: 0.846953510086205 and parameters: {'num_layers': 1, 'layer_0_log2_size': 7, 'dropout': 0.24283867117971641, 'learning_rate': 0.006741831816019809}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:01:41,174] Trial 23 finished with value: 0.84651532813326 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.37225923919419773, 'learning_rate': 0.0028767892002971767}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:01:57,628] Trial 24 finished with value: 0.8442963525057328 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.31204917874775995, 'learning_rate': 0.009754096163398446}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:02:38,305] Trial 25 finished with value: 0.8392564140297468 and parameters: {'num_layers': 1, 'layer_0_log2_size': 5, 'dropout': 0.4371158895275773, 'learning_rate': 0.0026525262052076197}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:02:50,113] Trial 26 finished with value: 0.8437025457153533 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 2, 'dropout': 0.2493797543280547, 'learning_rate': 0.0480727074929915}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:03:02,472] Trial 27 finished with value: 0.8518740079124434 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.3407434980706122, 'learning_rate': 0.02648658359432809}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:03:51,704] Trial 28 finished with value: 0.6231340801378288 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 3, 'dropout': 0.3941632983977434, 'learning_rate': 0.00024046426955620168}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:04:11,178] Trial 29 finished with value: 0.8564040074550494 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.29428320084483583, 'learning_rate': 0.001887156438272825}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:04:28,335] Trial 30 finished with value: 0.8475703408578589 and parameters: {'num_layers': 1, 'layer_0_log2_size': 6, 'dropout': 0.2849467777835606, 'learning_rate': 0.009395068114567714}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:04:53,175] Trial 31 finished with value: 0.8598261242787419 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.328649773722265, 'learning_rate': 0.0018601505931390308}. Best is trial 14 with value: 0.8628912371045029.
[I 2025-04-28 19:05:27,375] Trial 32 finished with value: 0.8643861036598333 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.34269795141705967, 'learning_rate': 0.0006755684203367474}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:06:06,350] Trial 33 finished with value: 0.8431733153031328 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.4355973617245396, 'learning_rate': 0.0005876834178605052}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:06:54,321] Trial 34 finished with value: 0.7970702477237325 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 7, 'dropout': 0.20798943575005513, 'learning_rate': 0.00010458762740665158}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:07:31,138] Trial 35 finished with value: 0.8466443862832275 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.3401974703234759, 'learning_rate': 0.0006154913472773898}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:08:01,112] Trial 36 finished with value: 0.7697702569837623 and parameters: {'num_layers': 3, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'layer_2_log2_size': 4, 'dropout': 0.46283346334865616, 'learning_rate': 0.001521257479429125}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:08:50,111] Trial 37 finished with value: 0.6229812460722041 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.4038834156355, 'learning_rate': 4.8734984220654695e-05}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:09:40,052] Trial 38 finished with value: 0.8051494498683663 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'layer_2_log2_size': 2, 'dropout': 0.2660707631417964, 'learning_rate': 0.00033006023764253723}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:10:29,220] Trial 39 finished with value: 0.6279324917730935 and parameters: {'num_layers': 2, 'layer_0_log2_size': 3, 'layer_1_log2_size': 4, 'dropout': 0.37544578603409995, 'learning_rate': 8.294779319277381e-05}. Best is trial 32 with value: 0.8643861036598333.
[I 2025-04-28 19:10:43,713] Trial 40 finished with value: 0.8728452000955421 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.22741834491748308, 'learning_rate': 0.004578239601840415}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:11:18,453] Trial 41 finished with value: 0.8542587553805063 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.279153832973912, 'learning_rate': 0.0008387456898379223}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:11:30,045] Trial 42 finished with value: 0.8582580304112056 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.22458258790702315, 'learning_rate': 0.004708950799223434}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:12:18,410] Trial 43 finished with value: 0.5858795710259945 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.13227659391876265, 'learning_rate': 1.145842220957927e-05}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:12:49,155] Trial 44 finished with value: 0.8390883091328888 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 4, 'dropout': 0.34905927252786473, 'learning_rate': 0.001789914458846625}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:13:01,293] Trial 45 finished with value: 0.8534722128983727 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.2169336216028646, 'learning_rate': 0.00441930713946654}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:13:18,565] Trial 46 finished with value: 0.7584552043563673 and parameters: {'num_layers': 2, 'layer_0_log2_size': 3, 'layer_1_log2_size': 7, 'dropout': 0.3266823056276795, 'learning_rate': 0.010469751348056814}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:14:08,971] Trial 47 finished with value: 0.8120706012753856 and parameters: {'num_layers': 3, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'layer_2_log2_size': 7, 'dropout': 0.42022013479495357, 'learning_rate': 0.00037662089688595427}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:14:38,697] Trial 48 finished with value: 0.8203474478358688 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 7, 'dropout': 0.36328688666940134, 'learning_rate': 0.001025818078638864}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:14:47,944] Trial 49 finished with value: 0.8477880414185044 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.39198073979890213, 'learning_rate': 0.024873378056315894}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:14:59,974] Trial 50 finished with value: 0.8405804426149969 and parameters: {'num_layers': 3, 'layer_0_log2_size': 4, 'layer_1_log2_size': 6, 'layer_2_log2_size': 4, 'dropout': 0.29843172467376533, 'learning_rate': 0.0534035917126705}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:15:16,625] Trial 51 finished with value: 0.8398512502757397 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.2236530945383952, 'learning_rate': 0.0034638172785337405}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:15:28,891] Trial 52 finished with value: 0.8610387647242591 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.18833422546190395, 'learning_rate': 0.006498138445597758}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:15:38,095] Trial 53 finished with value: 0.8629380577372233 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.14351917693531824, 'learning_rate': 0.007520674592427767}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:15:46,840] Trial 54 finished with value: 0.8577290233326484 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.14379119583374117, 'learning_rate': 0.007054063311677798}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:03,164] Trial 55 finished with value: 0.854368906392233 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.11847028164896828, 'learning_rate': 0.002167787511333674}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:12,308] Trial 56 finished with value: 0.8472512500965269 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 4, 'dropout': 0.08119495526904175, 'learning_rate': 0.01420257706979955}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:24,577] Trial 57 finished with value: 0.8610387647242591 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.19000859224415145, 'learning_rate': 0.006495617316591299}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:37,658] Trial 58 finished with value: 0.8094982826833617 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'dropout': 0.20083762638155347, 'learning_rate': 0.007366699072978636}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:47,586] Trial 59 finished with value: 0.8531937077969911 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 4, 'dropout': 0.1638482345695362, 'learning_rate': 0.012689347243178484}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:16:57,590] Trial 60 finished with value: 0.866495982610768 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 6, 'dropout': 0.18506835800819138, 'learning_rate': 0.020765501567498814}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:17:07,645] Trial 61 finished with value: 0.8584280510697664 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 6, 'dropout': 0.18307910667465574, 'learning_rate': 0.017882791526674807}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:17:16,720] Trial 62 finished with value: 0.8444528485080445 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'dropout': 0.19372525674037405, 'learning_rate': 0.02058197421568637}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:17:31,017] Trial 63 finished with value: 0.8191017446043289 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 5, 'dropout': 0.14919138470664756, 'learning_rate': 0.004074554188023362}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:17:41,090] Trial 64 finished with value: 0.8693577663970402 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 7, 'dropout': 0.23607280229260275, 'learning_rate': 0.03128326660694906}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:17:49,686] Trial 65 finished with value: 0.8411648220598625 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'dropout': 0.23720950728332707, 'learning_rate': 0.038367329852636564}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:18:00,504] Trial 66 finished with value: 0.8582326772886392 and parameters: {'num_layers': 2, 'layer_0_log2_size': 5, 'layer_1_log2_size': 7, 'dropout': 0.11642025042851324, 'learning_rate': 0.06320504471610895}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:18:10,137] Trial 67 finished with value: 0.8457351270126487 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 6, 'dropout': 0.25503607582689125, 'learning_rate': 0.03034576599814009}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:18:27,054] Trial 68 finished with value: 0.7220304250980931 and parameters: {'num_layers': 2, 'layer_0_log2_size': 2, 'layer_1_log2_size': 7, 'dropout': 0.1776761926256864, 'learning_rate': 0.010939903740346615}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:18:36,010] Trial 69 finished with value: 0.8462136849809614 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 7, 'dropout': 0.0594673617802932, 'learning_rate': 0.021622465874306707}. Best is trial 40 with value: 0.8728452000955421.
[I 2025-04-28 19:18:46,185] Trial 70 finished with value: 0.85314495501941 and parameters: {'num_layers': 2, 'layer_0_log2_size': 6, 'layer_1_log2_size': 7, 'dropout': 0.004641588896625026, 'learning_rate': 0.008409557685555014}. Best is trial 40 with value: 0.8728452000955421.

raw best_params

{'num_layers': 2,
 'layer_0_log2_size': 7,
 'layer_1_log2_size': 6,
 'dropout': 0.4124773666300698,
 'learning_rate': 0.012011447873654357}

best_params

{'dropout': 0.4124773666300698,
 'learning_rate': 0.012011447873654357,
 'layers': '128-64'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.859023
holdout_test_accuracy_balanced                                             0.847727
holdout_test_roc_auc                                                       0.959091
holdout_test_f1                                                            0.789474
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.974359
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                             0.9375
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.936709

Model saved in ..\results\models_modelling4\CategoryEmbeddingModel_no_fragmentation_smotenc_opt-model

Best choose:

- "activation": "LeakyReLU",
- "use_batch_norm": False,
- "batch_norm_continuous_input": True,

Params to optimize:
- dropout
- learning_rate
- layers

## Save same models, but on CPU

In [5]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # Other params SET in optuna
    "model_config_params": {
        'dropout': 0.04379983378244369,
        'learning_rate': 0.009487772841911948,
        'layers': '128',
        'activation': 'LeakyReLU',
        'batch_norm_continuous_input': True, # We already have normalized features    
        'use_batch_norm': False, # For hidden layers
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'cpu',
        'progress_bar': 'none',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "PytorchTabularEstimator"

                                                                                 0
target                                                                   splashing
model                             CategoryEmbeddingModel_splashing_smote_opt-model
holdout_test_f1_macro                                                     0.836601
holdout_test_accuracy_balanced                                            0.828704
holdout_test_roc_auc                                                      0.911265
holdout_test_f1                                                           0.888889
holdout_test_accuracy                                                     0.853333
cv_test_f1_macro_median                                                   0.860788
cv_test_accuracy_balanced_median                                          0.873839
cv_test_roc_auc_median                                                    0.919505
cv_test_f1_median                                                         0.892308
cv_test_accuracy_median                                                   0.867925
cv_test_precision_class_0_median                                          0.772727
cv_test_recall_class_0_median                                             0.894737
cv_test_f1_class_0_median                                                 0.829268

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_splashing_smote_opt-model

In [6]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # Other params SET in optuna
    "model_config_params": {
        'dropout': 0.4124773666300698,
        'learning_rate': 0.012011447873654357,
        'layers': '128-64',
        'activation': 'LeakyReLU',
        'batch_norm_continuous_input': True, # We already have normalized features    
        'use_batch_norm': False, # For hidden layers
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'cpu',
        'progress_bar': 'none',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.834656
holdout_test_accuracy_balanced                                             0.845455
holdout_test_roc_auc                                                           0.95
holdout_test_f1                                                            0.761905
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.915751
cv_test_roc_auc_median                                                     0.981685
cv_test_f1_median                                                          0.848485
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                               0.95
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.945946

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_no_fragmentation_smotenc_opt-model