Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-smote_opt-model'
add_smote = True
is_smotenc = False
common_smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 2500 # was checked with 1000 and 5000

save_model_and_metrics = True
metrics_file = "metrics_modelling4_4.1-opt_smote_no_ensembles.xlsx"

smote_params = {
    'splashing': {
        **common_smote_params,
        'k_neighbors': 7,
        'sampling_strategy': 0.9, # 0.8 for SMOTENC
    },
    'no_fragmentation': {
        **common_smote_params,
        'k_neighbors': 5,
        'sampling_strategy': 0.6,
    }
}

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    
    target_smote_params = smote_params[target]
    
    estimator_params = estimator_params.copy()
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=target_smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                # Remove gamma_type if it is float
                if (key=='gamma_type') and (best_params[key]=='float'):
                    best_params.pop(key)
                    continue
                        
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=target_smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}
params_to_process = ['penalty']

def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    
    # # NOTE: Does not work, since optuna requires static parameters ranges
    # solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # penalty_options = {
    #     'lbfgs': ['l2'],
    #     'liblinear': ['l1', 'l2'],
    #     'newton-cg': ['l2'],
    #     'newton-cholesky': ['l2'],
    #     'sag': ['l2'],
    #     'saga': ['l1', 'l2', 'elasticnet'],
    # }
    # penalty = trial.suggest_categorical('penalty', penalty_options[solver])
    # NOTE: warnings + inconvenient to create best model
    # solver_penalty_combinations = [
    #     ("liblinear", "l1"),
    #     ("liblinear", "l2"),
    #     ("saga", "l1"),
    #     ("saga", "l2"),
    #     ("saga", "elasticnet"),
    #     ("lbfgs", "l2"),
    #     ("newton-cg", "l2"),
    #     ("newton-cholesky", "l2"),
    #     ("sag", "l2"),
    # ]
    # solver, penalty = trial.suggest_categorical(
    #     'solver_penalty', solver_penalty_combinations
    # )
    
    solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # solver = trial.suggest_categorical('solver', ['lbfgs',])
    
    if solver == 'liblinear':
        penalty = trial.suggest_categorical('penalty_liblinear', ['l1', 'l2'])
    elif solver == 'saga':
        penalty = trial.suggest_categorical('penalty_saga', ['l1', 'l2', 'elasticnet'])
    else:
        penalty = trial.suggest_categorical('penalty_other', ['l2'])
    
    # If C is large, the penalty should be small
    C = trial.suggest_float('C', 1e-4, 1e3, log=True)
    
    l1_ratio = None
    if penalty == 'elasticnet':
        l1_ratio = trial.suggest_float('l1_ratio', 0., 1.)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "solver": solver,
        "penalty": penalty,
        "C": C,
        "l1_ratio": l1_ratio,
        "class_weight": class_weight,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 11:40:01,296] A new study created in memory with name: model_study
[I 2025-04-18 11:40:01,457] Trial 0 finished with value: 0.8101682090919139 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8101682090919139.
[I 2025-04-18 11:40:01,619] Trial 1 finished with value: 0.8226402532926312 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:01,793] Trial 2 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:01,955] Trial 3 finished with value: 0.7998648979486092 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,107] Trial 4 finished with value: 0.7987824376659214 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,272] Trial 5 finished with value: 0.7340724059474354 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,440] Trial 6 finished with value: 0.7961171260513297 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,608] Trial 7 finished with value: 0.7475048231593318 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,779] Trial 8 finished with value: 0.8019734227307652 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:02,936] Trial 9 finished with value: 0.7278869579264129 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,142] Trial 10 finished with value: 0.770224195625835 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.054522022569948085, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,301] Trial 11 finished with value: 0.8101682090919139 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.024262729145672, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,503] Trial 12 finished with value: 0.8069288014407415 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.9859049660282473, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,660] Trial 13 finished with value: 0.805802442380216 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.16283061772551938, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,826] Trial 14 finished with value: 0.8019734227307652 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 16.16837164311902, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:03,998] Trial 15 finished with value: 0.7343694271997891 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0026510161560213464, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:04,174] Trial 16 finished with value: 0.7987824376659214 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 241.77815686614423, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:04,336] Trial 17 finished with value: 0.8069288014407415 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.9890078482767913, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:04,491] Trial 18 finished with value: 0.7378315263251537 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.0019561610364886178, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:04,669] Trial 19 finished with value: 0.8069815117562804 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 3.931801630825414, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:04,823] Trial 20 finished with value: 0.7964536150164591 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.08452502957470454, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,007] Trial 21 finished with value: 0.8101682090919139 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.6595932976271162, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,185] Trial 22 finished with value: 0.7987824376659214 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 28.764800015565225, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,358] Trial 23 finished with value: 0.8101682090919139 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.603001448968451, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,545] Trial 24 finished with value: 0.8226402532926312 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.42389430602443406, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,706] Trial 25 finished with value: 0.8226402532926312 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.4028090859651169, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:05,884] Trial 26 finished with value: 0.809755621049705 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.383629173495379, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,042] Trial 27 finished with value: 0.7768354648421462 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.043355167767913406, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,212] Trial 28 finished with value: 0.8226402532926312 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.4094496184913195, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,362] Trial 29 finished with value: 0.7573899867670036 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.023409067734634727, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,547] Trial 30 finished with value: 0.8024002073603339 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.15891910029224204, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,695] Trial 31 finished with value: 0.8037098292967974 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.5406730716120122, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:06,859] Trial 32 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.16882117558654997, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,048] Trial 33 finished with value: 0.8037098292967974 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.6447269899211329, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,207] Trial 34 finished with value: 0.7340724059474354 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.006888348839520953, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,386] Trial 35 finished with value: 0.8024777623976664 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 5.842057656299061, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,563] Trial 36 finished with value: 0.7961171260513297 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 88.73115201684855, 'l1_ratio': 0.054123911748594655, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,730] Trial 37 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2858758288989802, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:07,895] Trial 38 finished with value: 0.8101682090919139 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.6944394146496626, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,043] Trial 39 finished with value: 0.7407811157833272 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.010723786294363857, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,216] Trial 40 finished with value: 0.7987824376659214 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 905.5230200461422, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,380] Trial 41 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.20765962610849215, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,542] Trial 42 finished with value: 0.7964536150164591 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.08712001504240759, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,705] Trial 43 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.3568940415642016, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:08,862] Trial 44 finished with value: 0.8037098292967974 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.923136582682845, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,014] Trial 45 finished with value: 0.7572450385696047 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.02920112541058139, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,180] Trial 46 finished with value: 0.7964536150164591 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.08334597063695871, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,347] Trial 47 finished with value: 0.8005405481989414 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 7.199334069307814, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,533] Trial 48 finished with value: 0.8101682090919139 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.9968914890835947, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,701] Trial 49 finished with value: 0.7277546901175338 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.0005639111644513547, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:09,864] Trial 50 finished with value: 0.7973215760549973 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.5505783917222083, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,018] Trial 51 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.33832850072514453, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,209] Trial 52 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2983935946804689, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,383] Trial 53 finished with value: 0.8069288014407415 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.9684158090984246, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,566] Trial 54 finished with value: 0.8024002073603339 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.15015915969814034, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,746] Trial 55 finished with value: 0.8019734227307652 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 12.71520974963953, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:10,945] Trial 56 finished with value: 0.7768354648421462 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.052991181680576836, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,110] Trial 57 finished with value: 0.8101682090919139 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 2.5769299374698824, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,289] Trial 58 finished with value: 0.796879385085519 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.10862723897852382, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,463] Trial 59 finished with value: 0.8194164881585978 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.31719761959099196, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,630] Trial 60 finished with value: 0.7973215760549973 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.5692825299440116, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,807] Trial 61 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2826961101090609, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:11,988] Trial 62 finished with value: 0.8069288014407415 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.2395156439309838, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,147] Trial 63 finished with value: 0.8189123635353298 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.4878804873794271, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,316] Trial 64 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2596749164509075, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,488] Trial 65 finished with value: 0.8037098292967974 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.8082159382070268, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,636] Trial 66 finished with value: 0.7638201203395653 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.03347029435006676, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,804] Trial 67 finished with value: 0.7997170182798624 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.11330061842016127, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:12,965] Trial 68 finished with value: 0.7406943848603593 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.011968665201567098, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,135] Trial 69 finished with value: 0.8005405481989414 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 3.566080009058975, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,299] Trial 70 finished with value: 0.8069288014407415 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.4816042815744181, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,482] Trial 71 finished with value: 0.8226402532926312 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.4024392701501793, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,635] Trial 72 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.39489706076767017, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,806] Trial 73 finished with value: 0.7865714991816651 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.07012879085323571, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:13,967] Trial 74 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2061023787250292, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:14,141] Trial 75 finished with value: 0.8037098292967974 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.7521281691940251, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:14,311] Trial 76 finished with value: 0.8024002073603339 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.14322303673547718, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:14,484] Trial 77 finished with value: 0.8194164881585978 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.3687002165537462, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:14,648] Trial 78 finished with value: 0.8101682090919139 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 2.365406927979818, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:14,820] Trial 79 finished with value: 0.8024777623976664 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 5.99074584612148, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:15,004] Trial 80 finished with value: 0.7973215760549973 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.2495846934333041, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:15,153] Trial 81 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.2685831254301992, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:15,316] Trial 82 finished with value: 0.8226402532926312 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.4199314546348062, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.
[I 2025-04-18 11:40:15,486] Trial 83 finished with value: 0.8226402532926312 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.45518549459872304, 'class_weight': None}. Best is trial 1 with value: 0.8226402532926312.

best_params

{'solver': 'lbfgs',
 'C': 0.47129737561107793,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_opt-smote_o...
holdout_test_f1_macro                                                      0.772036
holdout_test_accuracy_balanced                                              0.77662
holdout_test_roc_auc                                                       0.885031
holdout_test_f1                                                            0.829787
holdout_test_accuracy                                                      0.786667
cv_test_f1_macro_median                                                    0.807971
cv_test_accuracy_balanced_median                                           0.832817
cv_test_roc_auc_median                                                     0.877709
cv_test_f1_median                                                          0.848485
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.780488

Model saved in ..\results\models_modelling4\LogisticRegression_splashing_smote_opt-smote_opt-model

In [7]:
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 11:47:32,728] A new study created in memory with name: model_study
[I 2025-04-18 11:47:32,860] Trial 0 finished with value: 0.8219763971993025 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:32,994] Trial 1 finished with value: 0.7921977490316808 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,133] Trial 2 finished with value: 0.4233049487844008 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,263] Trial 3 finished with value: 0.7954947086214964 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,390] Trial 4 finished with value: 0.8161832968540547 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,517] Trial 5 finished with value: 0.7094325747528282 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,786] Trial 6 finished with value: 0.8112337811586782 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:33,929] Trial 7 finished with value: 0.719389632349068 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,064] Trial 8 finished with value: 0.8144440640122597 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,191] Trial 9 finished with value: 0.6987630722635816 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,343] Trial 10 finished with value: 0.8118192620616126 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.8666692466256958, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,470] Trial 11 finished with value: 0.8161832968540547 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 226.0888235578105, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,598] Trial 12 finished with value: 0.8161832968540547 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 946.0296440119475, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,726] Trial 13 finished with value: 0.8161832968540547 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 17.285284627691205, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:34,858] Trial 14 finished with value: 0.8209525579977279 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.667822930850185, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:35,000] Trial 15 finished with value: 0.802106586533207 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.5769671886663852, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:35,129] Trial 16 finished with value: 0.7403882247858476 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.029769597875852843, 'class_weight': None}. Best is trial 0 with value: 0.8219763971993025.
[I 2025-04-18 11:47:35,272] Trial 17 finished with value: 0.8290403136277128 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 2.2361909204290393, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:35,414] Trial 18 finished with value: 0.8118192620616126 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 4.226589570549454, 'class_weight': 'balanced'}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:35,544] Trial 19 finished with value: 0.7604774117251294 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.10211691721620035, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:35,673] Trial 20 finished with value: 0.6946806776569935 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.001308326952126753, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:35,800] Trial 21 finished with value: 0.808852795988776 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.9976168743718339, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:35,935] Trial 22 finished with value: 0.8290403136277128 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 2.5514240927611134, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,067] Trial 23 finished with value: 0.8159949269989537 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 54.20104063140321, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,198] Trial 24 finished with value: 0.8290403136277128 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 3.040948136955277, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,343] Trial 25 finished with value: 0.8208536840611006 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 27.02031815090036, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,475] Trial 26 finished with value: 0.7541284326934681 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.16508171506747188, 'class_weight': 'balanced'}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,622] Trial 27 finished with value: 0.8290403136277128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 2.6822300286687004, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,755] Trial 28 finished with value: 0.8190459612383533 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.97587567923447, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:36,880] Trial 29 finished with value: 0.8290403136277128 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.9969517004955681, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,013] Trial 30 finished with value: 0.8161832968540547 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 174.97757081792008, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,158] Trial 31 finished with value: 0.8290403136277128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 1.9617989677947854, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,301] Trial 32 finished with value: 0.8290403136277128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 1.9511066955439857, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,474] Trial 33 finished with value: 0.769764916599948 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.14557602171299283, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,738] Trial 34 finished with value: 0.8161832968540547 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 9.411451973924132, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:37,873] Trial 35 finished with value: 0.8008114011070513 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.3721587438938304, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:38,010] Trial 36 finished with value: 0.753045204814744 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.06748096424448867, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:38,228] Trial 37 finished with value: 0.8171612224487134 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 20.09841622092318, 'l1_ratio': 0.0006502443207018205, 'class_weight': 'balanced'}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:38,358] Trial 38 finished with value: 0.8223770808549254 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 68.01194923377379, 'class_weight': None}. Best is trial 17 with value: 0.8290403136277128.
[I 2025-04-18 11:47:38,492] Trial 39 finished with value: 0.8327520431605995 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 3.9284824999097823, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:38,626] Trial 40 finished with value: 0.8017312800431279 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.9877407551890823, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:38,761] Trial 41 finished with value: 0.8327520431605995 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 3.645694804624537, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:38,893] Trial 42 finished with value: 0.8190459612383533 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.7529580442471016, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,036] Trial 43 finished with value: 0.798487818865456 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.3451458525455267, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,166] Trial 44 finished with value: 0.8279170162916742 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 4.728462152046072, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,299] Trial 45 finished with value: 0.8208536840611006 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 20.007985454795996, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,436] Trial 46 finished with value: 0.8219763971993025 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.4489969067340365, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,571] Trial 47 finished with value: 0.8210420539162017 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 94.87684921001046, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,735] Trial 48 finished with value: 0.8137881177209288 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 9.632842727875616, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:39,876] Trial 49 finished with value: 0.8054796912609915 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.7083712825093867, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,003] Trial 50 finished with value: 0.8290403136277128 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 3.1299120408931778, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,146] Trial 51 finished with value: 0.8290403136277128 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 3.181724859239852, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,344] Trial 52 finished with value: 0.8208536840611006 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 29.687419361176342, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,470] Trial 53 finished with value: 0.8179100702978148 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 12.36567652084586, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,602] Trial 54 finished with value: 0.8151923667893971 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.2535257129197512, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,736] Trial 55 finished with value: 0.7855871850521173 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.2656743072317295, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,872] Trial 56 finished with value: 0.8290403136277128 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 2.774334099791001, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:40,998] Trial 57 finished with value: 0.8190459612383533 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 5.759295171845504, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,140] Trial 58 finished with value: 0.6821350137001267 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.0017482297534643285, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,282] Trial 59 finished with value: 0.802106586533207 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.6752756308681058, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,415] Trial 60 finished with value: 0.8179100702978148 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 13.10946447932627, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,543] Trial 61 finished with value: 0.8290403136277128 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 2.1786841938950943, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,670] Trial 62 finished with value: 0.8151923667893971 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.1842471008260653, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,805] Trial 63 finished with value: 0.8279170162916742 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 4.633519759537171, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:41,943] Trial 64 finished with value: 0.8208536840611006 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 33.70396271818596, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,084] Trial 65 finished with value: 0.8290403136277128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 1.9502001478545556, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,224] Trial 66 finished with value: 0.802106586533207 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.5430149021988517, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,350] Trial 67 finished with value: 0.7791769878970937 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.17843777733287758, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,610] Trial 68 finished with value: 0.8190214183993214 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 3.4290145739988103, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,742] Trial 69 finished with value: 0.7498542197499002 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.05964245695826903, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:42,873] Trial 70 finished with value: 0.8112337811586782 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 8.999924887679507, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,016] Trial 71 finished with value: 0.8219763971993025 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 1.7444961471420715, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,179] Trial 72 finished with value: 0.8279170162916742 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 4.987304268337697, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,316] Trial 73 finished with value: 0.808852795988776 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.9441814149474419, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,462] Trial 74 finished with value: 0.8290403136277128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 2.0177293646112755, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,594] Trial 75 finished with value: 0.7955708537594653 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.52119304234309, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,733] Trial 76 finished with value: 0.8190459612383533 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 8.0322807877234, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:43,869] Trial 77 finished with value: 0.8290403136277128 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 2.59639379880391, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:44,036] Trial 78 finished with value: 0.8179100702978148 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 15.261304485235096, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:44,266] Trial 79 finished with value: 0.8144440640122597 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 1.3513573863474222, 'l1_ratio': 0.9943662878292611, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:44,398] Trial 80 finished with value: 0.7634088963098398 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.24819711838284508, 'class_weight': 'balanced'}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:44,538] Trial 81 finished with value: 0.8054796912609915 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.8286902144278351, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.
[I 2025-04-18 11:47:44,694] Trial 82 finished with value: 0.8327520431605995 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 4.0317393335765495, 'class_weight': None}. Best is trial 39 with value: 0.8327520431605995.

best_params

{'solver': 'newton-cholesky',
 'C': 3.9284824999097823,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.798595
holdout_test_accuracy_balanced                                             0.834091
holdout_test_roc_auc                                                       0.949091
holdout_test_f1                                                            0.723404
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                     0.84043
cv_test_accuracy_balanced_median                                           0.874542
cv_test_roc_auc_median                                                      0.93956
cv_test_f1_median                                                          0.774194
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                            0.96875
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                   0.90411

Model saved in ..\results\models_modelling4\LogisticRegression_no_fragmentation_smote_opt-smote_opt-model

# KNClassifier

In [8]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['penalty']
params_to_process = None


def knn_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    n_neighbors = trial.suggest_int("n_neighbors", 1, 50)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    p = trial.suggest_int("p", 1, 2)  # 1=manhattan, 2=euclidean
    # leaf_size - affects the speed of the tree construction and search
    # algorithm - affects the speed of the search, for small datasets it is okay to use auto
    
    suggested_estimator_params = {
        "n_neighbors": n_neighbors,
        "weights": weights,
        "p": p,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 11:53:59,922] A new study created in memory with name: model_study
[I 2025-04-18 11:54:00,174] Trial 0 finished with value: 0.801645390136896 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.801645390136896.
[I 2025-04-18 11:54:00,413] Trial 1 finished with value: 0.805694867690666 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.805694867690666.
[I 2025-04-18 11:54:00,660] Trial 2 finished with value: 0.785590059640236 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.805694867690666.
[I 2025-04-18 11:54:00,911] Trial 3 finished with value: 0.7591023494245429 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.805694867690666.
[I 2025-04-18 11:54:01,165] Trial 4 finished with value: 0.777523868190684 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.805694867690666.
[I 2025-04-18 11:54:01,337] Trial 5 finished with value: 0.8455986385956183 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8455986385956183.
[I 2025-04-18 11:54:01,570] Trial 6 finished with value: 0.7942749164383345 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8455986385956183.
[I 2025-04-18 11:54:01,736] Trial 7 finished with value: 0.8357992192915907 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8455986385956183.
[I 2025-04-18 11:54:01,892] Trial 8 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8766242820614396.
[I 2025-04-18 11:54:02,051] Trial 9 finished with value: 0.8642704648948607 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8766242820614396.
[I 2025-04-18 11:54:02,245] Trial 10 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:02,423] Trial 11 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:02,581] Trial 12 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:02,745] Trial 13 finished with value: 0.8636605947615028 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:02,910] Trial 14 finished with value: 0.8636605947615028 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,084] Trial 15 finished with value: 0.8422374958658294 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,241] Trial 16 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,404] Trial 17 finished with value: 0.8595323370246714 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,568] Trial 18 finished with value: 0.8567275711922706 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,738] Trial 19 finished with value: 0.8632997913843569 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:03,920] Trial 20 finished with value: 0.8455986385956183 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,078] Trial 21 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,241] Trial 22 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,400] Trial 23 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,582] Trial 24 finished with value: 0.8560842053415315 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,747] Trial 25 finished with value: 0.8743648549215814 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:04,906] Trial 26 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,076] Trial 27 finished with value: 0.8566984841948144 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,241] Trial 28 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,485] Trial 29 finished with value: 0.7856065923333924 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,649] Trial 30 finished with value: 0.8636605947615028 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,807] Trial 31 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:05,970] Trial 32 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:06,135] Trial 33 finished with value: 0.8601310180555253 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:06,373] Trial 34 finished with value: 0.805694867690666 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:06,613] Trial 35 finished with value: 0.8485101727160714 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:06,797] Trial 36 finished with value: 0.8566984841948144 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,046] Trial 37 finished with value: 0.7836316685686434 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,213] Trial 38 finished with value: 0.8529720201451797 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,375] Trial 39 finished with value: 0.8595323370246714 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,613] Trial 40 finished with value: 0.8417839675556449 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,774] Trial 41 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:07,935] Trial 42 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,095] Trial 43 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,262] Trial 44 finished with value: 0.8636605947615028 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,422] Trial 45 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,589] Trial 46 finished with value: 0.8743648549215814 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,811] Trial 47 finished with value: 0.8553349444838446 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:08,981] Trial 48 finished with value: 0.8601310180555253 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,147] Trial 49 finished with value: 0.862578338777067 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,324] Trial 50 finished with value: 0.8346342195125531 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,484] Trial 51 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,646] Trial 52 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,809] Trial 53 finished with value: 0.8743648549215814 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:09,971] Trial 54 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:10,139] Trial 55 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:10,304] Trial 56 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:10,480] Trial 57 finished with value: 0.8556555785521123 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:10,719] Trial 58 finished with value: 0.7856065923333924 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:10,881] Trial 59 finished with value: 0.8595323370246714 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,062] Trial 60 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,221] Trial 61 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,386] Trial 62 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,544] Trial 63 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,711] Trial 64 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:11,879] Trial 65 finished with value: 0.8601310180555253 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,042] Trial 66 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,204] Trial 67 finished with value: 0.8743648549215814 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,440] Trial 68 finished with value: 0.8228700682596299 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,614] Trial 69 finished with value: 0.8589041765930111 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,775] Trial 70 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:12,939] Trial 71 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,111] Trial 72 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,284] Trial 73 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,449] Trial 74 finished with value: 0.8595323370246714 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,614] Trial 75 finished with value: 0.8601310180555253 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,777] Trial 76 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:13,935] Trial 77 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:14,173] Trial 78 finished with value: 0.8060859545748403 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:14,344] Trial 79 finished with value: 0.8485900915870713 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:14,512] Trial 80 finished with value: 0.8639041817230926 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:14,679] Trial 81 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:14,849] Trial 82 finished with value: 0.8632997913843569 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,007] Trial 83 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,199] Trial 84 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,374] Trial 85 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,540] Trial 86 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,703] Trial 87 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:15,862] Trial 88 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,027] Trial 89 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,270] Trial 90 finished with value: 0.8060859545748403 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,431] Trial 91 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,594] Trial 92 finished with value: 0.8766242820614396 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,758] Trial 93 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:16,925] Trial 94 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,086] Trial 95 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,248] Trial 96 finished with value: 0.873775890234047 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,412] Trial 97 finished with value: 0.8601310180555253 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,593] Trial 98 finished with value: 0.8763503449218782 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,777] Trial 99 finished with value: 0.8520216191537126 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:17,939] Trial 100 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:18,100] Trial 101 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-18 11:54:18,261] Trial 102 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.

best_params

{'n_neighbors': 1, 'weights': 'distance', 'p': 1}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smote_opt-smote...
holdout_test_f1_macro                                                        0.8333
holdout_test_accuracy_balanced                                             0.820602
holdout_test_roc_auc                                                       0.820602
holdout_test_f1                                                            0.891089
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.891641
cv_test_roc_auc_median                                                     0.891641
cv_test_f1_median                                                          0.923077
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.864865

Model saved in ..\results\models_modelling4\KNeighborsClassifier_splashing_smote_opt-smote_opt-model

In [9]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 12:02:07,219] A new study created in memory with name: model_study
[I 2025-04-18 12:02:07,447] Trial 0 finished with value: 0.7901378337109034 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7901378337109034.
[I 2025-04-18 12:02:07,654] Trial 1 finished with value: 0.8281425218668367 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:07,870] Trial 2 finished with value: 0.770901019268706 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,079] Trial 3 finished with value: 0.777411682244389 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,281] Trial 4 finished with value: 0.7755189473072269 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,419] Trial 5 finished with value: 0.8184278584220309 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,626] Trial 6 finished with value: 0.771458288841048 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,766] Trial 7 finished with value: 0.8184278584220309 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 1 with value: 0.8281425218668367.
[I 2025-04-18 12:02:08,893] Trial 8 finished with value: 0.8556839286515805 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,024] Trial 9 finished with value: 0.8222057546172424 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,157] Trial 10 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,290] Trial 11 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,423] Trial 12 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,574] Trial 13 finished with value: 0.8251751203635358 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,711] Trial 14 finished with value: 0.828979959678173 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,860] Trial 15 finished with value: 0.8237632781204905 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:09,996] Trial 16 finished with value: 0.8219898172041596 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,131] Trial 17 finished with value: 0.8556839286515805 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,278] Trial 18 finished with value: 0.8116135130777603 and parameters: {'n_neighbors': 39, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,419] Trial 19 finished with value: 0.8169757768221392 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,557] Trial 20 finished with value: 0.838039226377847 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,698] Trial 21 finished with value: 0.838039226377847 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,833] Trial 22 finished with value: 0.8403339300964251 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:10,968] Trial 23 finished with value: 0.8475723346144528 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,120] Trial 24 finished with value: 0.8409611241496057 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,256] Trial 25 finished with value: 0.8386963812999466 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,398] Trial 26 finished with value: 0.8222648743403013 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,535] Trial 27 finished with value: 0.8287136959513803 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,684] Trial 28 finished with value: 0.8308332139994208 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:11,899] Trial 29 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:12,043] Trial 30 finished with value: 0.8116227069529403 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:12,250] Trial 31 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:12,458] Trial 32 finished with value: 0.8281425218668367 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:12,669] Trial 33 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:12,878] Trial 34 finished with value: 0.8119355493380203 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:13,090] Trial 35 finished with value: 0.7771433964168207 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:13,309] Trial 36 finished with value: 0.7584524556275872 and parameters: {'n_neighbors': 37, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:13,515] Trial 37 finished with value: 0.8281425218668367 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:13,721] Trial 38 finished with value: 0.8418920342393187 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:13,951] Trial 39 finished with value: 0.7963767726221772 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:14,091] Trial 40 finished with value: 0.838039226377847 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:14,299] Trial 41 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:14,503] Trial 42 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:14,709] Trial 43 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:14,920] Trial 44 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,123] Trial 45 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,332] Trial 46 finished with value: 0.8078963313754729 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,467] Trial 47 finished with value: 0.8427873423193802 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,605] Trial 48 finished with value: 0.8277981906727957 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,818] Trial 49 finished with value: 0.7902650120887588 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:15,972] Trial 50 finished with value: 0.8237632781204905 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:16,196] Trial 51 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8556839286515805.
[I 2025-04-18 12:02:16,402] Trial 52 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:16,609] Trial 53 finished with value: 0.8228401185150792 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:16,822] Trial 54 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:16,960] Trial 55 finished with value: 0.8287136959513803 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:17,162] Trial 56 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:17,304] Trial 57 finished with value: 0.8308332139994208 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 1}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:17,449] Trial 58 finished with value: 0.8116227069529403 and parameters: {'n_neighbors': 35, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:17,588] Trial 59 finished with value: 0.828979959678173 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:17,801] Trial 60 finished with value: 0.8043372837601865 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 1}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:18,010] Trial 61 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:18,230] Trial 62 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:18,477] Trial 63 finished with value: 0.8228401185150792 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:18,684] Trial 64 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:18,897] Trial 65 finished with value: 0.8108707839963608 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,035] Trial 66 finished with value: 0.8427873423193802 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,174] Trial 67 finished with value: 0.8251751203635358 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,379] Trial 68 finished with value: 0.8148284884779115 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,525] Trial 69 finished with value: 0.8116227069529403 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,730] Trial 70 finished with value: 0.8198925006687493 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 1}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:19,939] Trial 71 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:20,150] Trial 72 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:20,358] Trial 73 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:20,581] Trial 74 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:20,791] Trial 75 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:20,992] Trial 76 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:21,200] Trial 77 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:21,408] Trial 78 finished with value: 0.8281425218668367 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:21,615] Trial 79 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:21,825] Trial 80 finished with value: 0.8108707839963608 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:22,030] Trial 81 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:22,238] Trial 82 finished with value: 0.8148284884779115 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:22,445] Trial 83 finished with value: 0.8228401185150792 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:22,681] Trial 84 finished with value: 0.7634807485661501 and parameters: {'n_neighbors': 44, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:22,889] Trial 85 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:23,097] Trial 86 finished with value: 0.7911121315819823 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:23,300] Trial 87 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:23,511] Trial 88 finished with value: 0.8148284884779115 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:23,717] Trial 89 finished with value: 0.8108707839963608 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:23,925] Trial 90 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:24,132] Trial 91 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:24,338] Trial 92 finished with value: 0.8228401185150792 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:24,545] Trial 93 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:24,759] Trial 94 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:24,979] Trial 95 finished with value: 0.8148284884779115 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:25,181] Trial 96 finished with value: 0.8315878394384176 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:25,387] Trial 97 finished with value: 0.8228401185150792 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:25,598] Trial 98 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:25,809] Trial 99 finished with value: 0.7911121315819823 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:26,016] Trial 100 finished with value: 0.8271615980762317 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:26,236] Trial 101 finished with value: 0.8609643666466287 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.
[I 2025-04-18 12:02:26,448] Trial 102 finished with value: 0.8463828848767845 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 52 with value: 0.8609643666466287.

best_params

{'n_neighbors': 3, 'weights': 'uniform', 'p': 2}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.839194
holdout_test_accuracy_balanced                                             0.861364
holdout_test_roc_auc                                                       0.911364
holdout_test_f1                                                            0.772727
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.882051
cv_test_roc_auc_median                                                     0.940476
cv_test_f1_median                                                          0.787879
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.918919

Model saved in ..\results\models_modelling4\KNeighborsClassifier_no_fragmentation_smote_opt-smote_opt-model

# SVC

In [6]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True, # Would beFalse for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']


def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-18 14:27:15,550] A new study created in memory with name: model_study
[I 2025-04-18 14:27:15,777] Trial 0 finished with value: 0.392616568979092 and parameters: {'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 0 with value: 0.392616568979092.
[I 2025-04-18 14:27:16,025] Trial 1 finished with value: 0.3193900243566663 and parameters: {'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 0 with value: 0.392616568979092.
[I 2025-04-18 14:27:16,178] Trial 2 finished with value: 0.8434883138156384 and parameters: {'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}. Best is trial 2 with value: 0.8434883138156384.
[I 2025-04-18 14:27:16,374] Trial 3 finished with value: 0.4194501950246622 and parameters: {'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}. Best is trial 2 with value: 0.8434883138156384.
[I 2025-04-18 14:27:16,548] Trial 4 finished with value: 0.8409278245172623 and parameters: {'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}. Best is trial 2 with value: 0.8434883138156384.
[I 2025-04-18 14:27:16,736] Trial 5 finished with value: 0.854586590821004 and parameters: {'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002273762810253686}. Best is trial 5 with value: 0.854586590821004.
[I 2025-04-18 14:27:16,924] Trial 6 finished with value: 0.7950621373453083 and parameters: {'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}. Best is trial 5 with value: 0.854586590821004.
[I 2025-04-18 14:27:17,176] Trial 7 finished with value: 0.8268786886258123 and parameters: {'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.854586590821004.
[I 2025-04-18 14:27:17,479] Trial 8 finished with value: 0.8256381925988334 and parameters: {'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}. Best is trial 5 with value: 0.854586590821004.
[I 2025-04-18 14:27:17,643] Trial 9 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}. Best is trial 9 with value: 0.8916745518012579.
[I 2025-04-18 14:27:17,815] Trial 10 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 3.319977760729009, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}. Best is trial 9 with value: 0.8916745518012579.
[I 2025-04-18 14:27:18,000] Trial 11 finished with value: 0.8983310512230602 and parameters: {'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7731722229182416, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:18,160] Trial 12 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 4.227037048440708, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:18,348] Trial 13 finished with value: 0.8546264216642367 and parameters: {'kernel': 'poly', 'C': 0.21162414884556216, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7853408064576318, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:18,573] Trial 14 finished with value: 0.8214389774315196 and parameters: {'kernel': 'poly', 'C': 15.142039581809946, 'class_weight': None, 'gamma_type': 'float', 'gamma': 2.0827600706085203, 'coef0': 0.4439875837140775, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:18,758] Trial 15 finished with value: 0.7666692071240305 and parameters: {'kernel': 'sigmoid', 'C': 0.18434865271268852, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9974597158548155}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:18,930] Trial 16 finished with value: 0.8371337215242406 and parameters: {'kernel': 'poly', 'C': 30.85106557676194, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.37985925452361524, 'coef0': 0.43910601384159637, 'degree': 5}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:19,097] Trial 17 finished with value: 0.8680706511117869 and parameters: {'kernel': 'poly', 'C': 5.940709675700833, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.04045191588988909, 'coef0': 0.6926452458423964, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:19,264] Trial 18 finished with value: 0.8744553477405671 and parameters: {'kernel': 'poly', 'C': 0.9032360273921896, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8626219710630426, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:19,500] Trial 19 finished with value: 0.7894197500876586 and parameters: {'kernel': 'sigmoid', 'C': 0.11496681839242444, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5529751012593238}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:19,774] Trial 20 finished with value: 0.392616568979092 and parameters: {'kernel': 'poly', 'C': 0.0011997072580708827, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.028659304016674842, 'coef0': 0.20179286701624122, 'degree': 4}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:19,968] Trial 21 finished with value: 0.8813729072268901 and parameters: {'kernel': 'poly', 'C': 3.0160247984327095, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7727342439152531, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:20,139] Trial 22 finished with value: 0.884186939760569 and parameters: {'kernel': 'poly', 'C': 28.540068208952828, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.682684976947565, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:20,315] Trial 23 finished with value: 0.8779975736438573 and parameters: {'kernel': 'poly', 'C': 2.454296248788125, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8595715516326194, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:20,485] Trial 24 finished with value: 0.8771188196861429 and parameters: {'kernel': 'poly', 'C': 8.935085151013782, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7003243665765008, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:20,660] Trial 25 finished with value: 0.8645390566558228 and parameters: {'kernel': 'poly', 'C': 1.110847358462562, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3194546623490381, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:21,114] Trial 26 finished with value: 0.8391459313005486 and parameters: {'kernel': 'poly', 'C': 44.809456363552705, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 6.208689679854005, 'coef0': 0.8604530976835578, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:21,312] Trial 27 finished with value: 0.776309005386112 and parameters: {'kernel': 'sigmoid', 'C': 0.04183344095035515, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.6104727782118268}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:21,500] Trial 28 finished with value: 0.859354117087686 and parameters: {'kernel': 'rbf', 'C': 864.5050473072474, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:21,679] Trial 29 finished with value: 0.8642916849798796 and parameters: {'kernel': 'rbf', 'C': 13.790065526987677, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.02298440362851696}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:21,866] Trial 30 finished with value: 0.8849616902850416 and parameters: {'kernel': 'poly', 'C': 1.6786402115198296, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7895688169547145, 'degree': 4}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,039] Trial 31 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 4.703248401436323, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6050334583449223, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,200] Trial 32 finished with value: 0.8983310512230602 and parameters: {'kernel': 'poly', 'C': 6.367385905884438, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5082337881181107, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,364] Trial 33 finished with value: 0.8545040949557755 and parameters: {'kernel': 'poly', 'C': 0.4923923482958272, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3229163020436373, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,539] Trial 34 finished with value: 0.8615108051385398 and parameters: {'kernel': 'poly', 'C': 14.942417579883267, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.920002726926155, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,719] Trial 35 finished with value: 0.8458283835321435 and parameters: {'kernel': 'rbf', 'C': 0.38949504821950687, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:22,886] Trial 36 finished with value: 0.8747312645558356 and parameters: {'kernel': 'poly', 'C': 1.6896868554111721, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.7297908907555094, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,102] Trial 37 finished with value: 0.8256381925988334 and parameters: {'kernel': 'linear', 'C': 56.77205408031014, 'class_weight': None}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,266] Trial 38 finished with value: 0.6409989842758798 and parameters: {'kernel': 'sigmoid', 'C': 10.63663823271254, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4571091340412785}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,448] Trial 39 finished with value: 0.850388289066933 and parameters: {'kernel': 'poly', 'C': 98.82915970095692, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.5363982555837048, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,603] Trial 40 finished with value: 0.8400539296307945 and parameters: {'kernel': 'linear', 'C': 0.9690071671173378, 'class_weight': None}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,765] Trial 41 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 4.054033423193185, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.631885206282052, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:23,943] Trial 42 finished with value: 0.8885098519585837 and parameters: {'kernel': 'poly', 'C': 7.830216810281363, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8056980681065122, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,102] Trial 43 finished with value: 0.8809677276703892 and parameters: {'kernel': 'poly', 'C': 20.33293473748852, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6308496543606212, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,265] Trial 44 finished with value: 0.392616568979092 and parameters: {'kernel': 'poly', 'C': 2.7402110216203712, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.0001514432402817994, 'coef0': 0.3568437221883033, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,435] Trial 45 finished with value: 0.8257561195178492 and parameters: {'kernel': 'poly', 'C': 5.220525721364697, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.005458575377312869, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,610] Trial 46 finished with value: 0.868122164724225 and parameters: {'kernel': 'rbf', 'C': 1.5684437390415205, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,767] Trial 47 finished with value: 0.8434883138156384 and parameters: {'kernel': 'linear', 'C': 0.32159935719867067, 'class_weight': 'balanced'}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:24,994] Trial 48 finished with value: 0.8542133554313092 and parameters: {'kernel': 'poly', 'C': 153.15322112458065, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.3091495272284552, 'coef0': 0.5276897566734643, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:25,152] Trial 49 finished with value: 0.8656383551484428 and parameters: {'kernel': 'poly', 'C': 21.7075001176016, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9196964601195501, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:25,361] Trial 50 finished with value: 0.392616568979092 and parameters: {'kernel': 'sigmoid', 'C': 0.8562526746243159, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.0029934082273291125, 'coef0': 0.7350595177234636}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:25,545] Trial 51 finished with value: 0.8916745518012579 and parameters: {'kernel': 'poly', 'C': 3.9932931547041823, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5871458932762585, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:25,701] Trial 52 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 5.200867382426188, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.645293632599576, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:25,875] Trial 53 finished with value: 0.8809677276703892 and parameters: {'kernel': 'poly', 'C': 39.547566038203264, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6730724483164451, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,035] Trial 54 finished with value: 0.8711988438598757 and parameters: {'kernel': 'poly', 'C': 7.852288568792262, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4730461317800019, 'degree': 5}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,218] Trial 55 finished with value: 0.8779975736438573 and parameters: {'kernel': 'poly', 'C': 2.493990714792995, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8162385026971775, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,386] Trial 56 finished with value: 0.8809677276703892 and parameters: {'kernel': 'poly', 'C': 6.889513662365389, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.745380972566541, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,551] Trial 57 finished with value: 0.847052498932751 and parameters: {'kernel': 'poly', 'C': 0.1113237338445461, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.20824897172503493, 'coef0': 0.656966951796685, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,719] Trial 58 finished with value: 0.8811127823007953 and parameters: {'kernel': 'poly', 'C': 13.066988298846333, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5609726554826311, 'degree': 3}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:26,883] Trial 59 finished with value: 0.8667086802399933 and parameters: {'kernel': 'poly', 'C': 27.150557871246747, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.9325098524350828, 'degree': 4}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,036] Trial 60 finished with value: 0.8367707703068561 and parameters: {'kernel': 'linear', 'C': 1.3526076363306383, 'class_weight': None}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,187] Trial 61 finished with value: 0.8813729072268901 and parameters: {'kernel': 'poly', 'C': 4.256239673493956, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3947919642696747, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,368] Trial 62 finished with value: 0.8512657694854767 and parameters: {'kernel': 'poly', 'C': 0.623898255036352, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5881614541384339, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,522] Trial 63 finished with value: 0.8710800141575342 and parameters: {'kernel': 'poly', 'C': 2.5210929272810993, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.513637185322811, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,687] Trial 64 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 4.837406406663839, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7275897695547243, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:27,859] Trial 65 finished with value: 0.8442023756641539 and parameters: {'kernel': 'poly', 'C': 9.496216839082502, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.006598330166759558, 'coef0': 0.7080408507372998, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,021] Trial 66 finished with value: 0.884186939760569 and parameters: {'kernel': 'rbf', 'C': 18.44948518506982, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,188] Trial 67 finished with value: 0.6145440901914443 and parameters: {'kernel': 'sigmoid', 'C': 3.3002448579673778, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.8408658708095809}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,369] Trial 68 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 6.874233765139078, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.755393980278343, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,536] Trial 69 finished with value: 0.392616568979092 and parameters: {'kernel': 'poly', 'C': 0.001977467399271586, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7696180503209878, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,688] Trial 70 finished with value: 0.8983310512230602 and parameters: {'kernel': 'poly', 'C': 6.033322756930139, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7607172482173077, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:28,864] Trial 71 finished with value: 0.8983310512230602 and parameters: {'kernel': 'poly', 'C': 5.9250290820871045, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7645893664796799, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:29,042] Trial 72 finished with value: 0.8983310512230602 and parameters: {'kernel': 'poly', 'C': 5.611766931566089, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8215050584212653, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.
[I 2025-04-18 14:27:29,190] Trial 73 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 6.234629766538798, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.892660042898969, 'degree': 2}. Best is trial 11 with value: 0.8983310512230602.

best_params

{'kernel': 'poly',
 'C': 14.776793472739397,
 'class_weight': None,
 'gamma': 0.08988540769636998,
 'coef0': 0.8134676675793495,
 'degree': 2}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                        0
target                                                          splashing
model                             SVC_splashing_smote_opt-smote_opt-model
holdout_test_f1_macro                                                0.79
holdout_test_accuracy_balanced                                    0.78125
holdout_test_roc_auc                                              0.89429
holdout_test_f1                                                      0.86
holdout_test_accuracy                                            0.813333
cv_test_f1_macro_median                                          0.898584
cv_test_accuracy_balanced_median                                 0.903251
cv_test_roc_auc_median                                           0.922601
cv_test_f1_median                                                0.925373
cv_test_accuracy_median                                           0.90566
cv_test_precision_class_0_median                                     0.85
cv_test_recall_class_0_median                                    0.894737
cv_test_f1_class_0_median                                        0.871795

Model saved in ..\results\models_modelling4\SVC_splashing_smote_opt-smote_opt-model

In [6]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True, # Would be False for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']

def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=500,
    seed=21,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-18 15:04:34,247] A new study created in memory with name: model_study
[I 2025-04-18 15:04:34,411] Trial 0 finished with value: 0.7081493505844338 and parameters: {'kernel': 'sigmoid', 'C': 0.017200322569383943, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.06957095461260054}. Best is trial 0 with value: 0.7081493505844338.
[I 2025-04-18 15:04:34,628] Trial 1 finished with value: 0.8264580342904377 and parameters: {'kernel': 'linear', 'C': 152.1240458771676, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8264580342904377.
[I 2025-04-18 15:04:34,753] Trial 2 finished with value: 0.7553041972774495 and parameters: {'kernel': 'linear', 'C': 0.04207446825995604, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8264580342904377.
[I 2025-04-18 15:04:34,892] Trial 3 finished with value: 0.7703212141287935 and parameters: {'kernel': 'linear', 'C': 0.05054268043577859, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8264580342904377.
[I 2025-04-18 15:04:35,035] Trial 4 finished with value: 0.5921332333735966 and parameters: {'kernel': 'sigmoid', 'C': 124.66836974089675, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8101575494926372}. Best is trial 1 with value: 0.8264580342904377.
[I 2025-04-18 15:04:35,187] Trial 5 finished with value: 0.8534926527970216 and parameters: {'kernel': 'rbf', 'C': 142.34323346004942, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:35,328] Trial 6 finished with value: 0.8436501537166989 and parameters: {'kernel': 'linear', 'C': 3.4893664517416547, 'class_weight': None}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:35,503] Trial 7 finished with value: 0.8160947241264225 and parameters: {'kernel': 'linear', 'C': 82.43990345883874, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:35,673] Trial 8 finished with value: 0.4233049487844008 and parameters: {'kernel': 'rbf', 'C': 0.011898133534060652, 'class_weight': None, 'gamma_type': 'float', 'gamma': 1.0492807664612955}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:35,805] Trial 9 finished with value: 0.8136532381507128 and parameters: {'kernel': 'linear', 'C': 0.17423146642890194, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:35,954] Trial 10 finished with value: 0.8394517589556193 and parameters: {'kernel': 'rbf', 'C': 5.407228438802247, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 5 with value: 0.8534926527970216.
[I 2025-04-18 15:04:36,091] Trial 11 finished with value: 0.8716707394189781 and parameters: {'kernel': 'poly', 'C': 4.693691230600619, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.9703502685820661, 'degree': 2}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:36,408] Trial 12 finished with value: 0.8513848427052364 and parameters: {'kernel': 'poly', 'C': 857.3539493827856, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.9940645764348965, 'degree': 2}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:36,551] Trial 13 finished with value: 0.8363060958432449 and parameters: {'kernel': 'poly', 'C': 18.659489904643017, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.5055815220811511, 'degree': 5}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:36,727] Trial 14 finished with value: 0.4233049487844008 and parameters: {'kernel': 'rbf', 'C': 0.0014692663866354555, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:36,860] Trial 15 finished with value: 0.8164071835482714 and parameters: {'kernel': 'poly', 'C': 0.5415011410386406, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.652377352692131, 'degree': 2}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,008] Trial 16 finished with value: 0.21003657418751756 and parameters: {'kernel': 'poly', 'C': 16.013911787612738, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00013776736545287972, 'coef0': 0.17561682399328427, 'degree': 3}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,159] Trial 17 finished with value: 0.8319711075873574 and parameters: {'kernel': 'rbf', 'C': 837.8460521114868, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,323] Trial 18 finished with value: 0.8280875238116664 and parameters: {'kernel': 'rbf', 'C': 1.3264859461050402, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,483] Trial 19 finished with value: 0.8425558256346884 and parameters: {'kernel': 'poly', 'C': 30.78892856488765, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.9707587873750887, 'degree': 4}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,635] Trial 20 finished with value: 0.4233049487844008 and parameters: {'kernel': 'sigmoid', 'C': 0.6760539100943742, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.001364229040425913, 'coef0': 0.27509393674673316}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:37,962] Trial 21 finished with value: 0.8513848427052364 and parameters: {'kernel': 'poly', 'C': 946.4497880442256, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.9889496929531943, 'degree': 2}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:38,153] Trial 22 finished with value: 0.8560458596543888 and parameters: {'kernel': 'poly', 'C': 261.3115768988613, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.7703302225184192, 'degree': 2}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:38,312] Trial 23 finished with value: 0.8369813182168632 and parameters: {'kernel': 'poly', 'C': 331.3293644256131, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.7595535869271977, 'degree': 3}. Best is trial 11 with value: 0.8716707394189781.
[I 2025-04-18 15:04:38,463] Trial 24 finished with value: 0.883809384886521 and parameters: {'kernel': 'poly', 'C': 45.424155167372916, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8026373821604789, 'degree': 2}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:38,596] Trial 25 finished with value: 0.8749245447230839 and parameters: {'kernel': 'poly', 'C': 5.929151808342966, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7998087093460107, 'degree': 2}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:38,744] Trial 26 finished with value: 0.857648136943771 and parameters: {'kernel': 'poly', 'C': 5.715402193647237, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5982439163337571, 'degree': 3}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:38,888] Trial 27 finished with value: 0.883809384886521 and parameters: {'kernel': 'poly', 'C': 40.074504924566114, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8571729349844823, 'degree': 2}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:39,030] Trial 28 finished with value: 0.8656570279192971 and parameters: {'kernel': 'poly', 'C': 35.05420181727688, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8302050602079845, 'degree': 3}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:39,162] Trial 29 finished with value: 0.8795397521267004 and parameters: {'kernel': 'poly', 'C': 14.811459677300956, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.655604839214653, 'degree': 2}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:39,291] Trial 30 finished with value: 0.6624723239737255 and parameters: {'kernel': 'sigmoid', 'C': 60.35135528381528, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6575123343741706}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:39,425] Trial 31 finished with value: 0.8755077553372485 and parameters: {'kernel': 'poly', 'C': 11.547046217856119, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8384459335907356, 'degree': 2}. Best is trial 24 with value: 0.883809384886521.
[I 2025-04-18 15:04:39,627] Trial 32 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 17.463245987810147, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8704211614621142, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:39,848] Trial 33 finished with value: 0.8789033317686866 and parameters: {'kernel': 'poly', 'C': 46.587649855916105, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8925884097050668, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:39,996] Trial 34 finished with value: 0.8502722349213868 and parameters: {'kernel': 'poly', 'C': 1.856933300598513, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6972581070633197, 'degree': 3}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,150] Trial 35 finished with value: 0.8795397521267004 and parameters: {'kernel': 'poly', 'C': 15.864752949676943, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5750966096605383, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,302] Trial 36 finished with value: 0.6552587453203048 and parameters: {'kernel': 'sigmoid', 'C': 355.60888137446267, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4003453567961933}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,444] Trial 37 finished with value: 0.8396781982437568 and parameters: {'kernel': 'poly', 'C': 106.97717831906837, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7088057853874286, 'degree': 4}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,630] Trial 38 finished with value: 0.8755077553372485 and parameters: {'kernel': 'poly', 'C': 9.749890277165232, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8889709517427087, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,814] Trial 39 finished with value: 0.8212771034456886 and parameters: {'kernel': 'linear', 'C': 0.23733877961477537, 'class_weight': 'balanced'}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:40,990] Trial 40 finished with value: 0.8676058078239548 and parameters: {'kernel': 'poly', 'C': 2.3907445539717678, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8953030390154334, 'degree': 3}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:41,146] Trial 41 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 24.36942160383144, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5566213786276168, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:41,294] Trial 42 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 31.06592695008391, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.49813951857416633, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:41,463] Trial 43 finished with value: 0.8848061125159542 and parameters: {'kernel': 'poly', 'C': 31.270534193586208, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.41745923214706154, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:41,711] Trial 44 finished with value: 0.8495386482502771 and parameters: {'kernel': 'linear', 'C': 170.49383434026996, 'class_weight': None}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:41,865] Trial 45 finished with value: 0.8675044528192337 and parameters: {'kernel': 'poly', 'C': 100.8978254828585, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.38465096933341086, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,216] Trial 46 finished with value: 0.8597195590413464 and parameters: {'kernel': 'poly', 'C': 25.72206726344821, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 8.440125907052783, 'coef0': 0.40817077999472395, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,364] Trial 47 finished with value: 0.6526622321203276 and parameters: {'kernel': 'sigmoid', 'C': 75.40645300829692, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5267923376058803}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,510] Trial 48 finished with value: 0.8675044528192337 and parameters: {'kernel': 'poly', 'C': 185.25622730675553, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.45998977587286927, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,662] Trial 49 finished with value: 0.8532503777831639 and parameters: {'kernel': 'linear', 'C': 7.296251241522585, 'class_weight': None}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,807] Trial 50 finished with value: 0.822871786603275 and parameters: {'kernel': 'poly', 'C': 3.369138820013344, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.27444568378179335, 'degree': 3}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:43,968] Trial 51 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 51.33552217398618, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.32685811256110303, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,116] Trial 52 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 71.16065495406289, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3469122623574254, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,286] Trial 53 finished with value: 0.8799767201561546 and parameters: {'kernel': 'poly', 'C': 23.463270222132238, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2997273608255038, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,451] Trial 54 finished with value: 0.848891695161619 and parameters: {'kernel': 'rbf', 'C': 77.97827549713085, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,620] Trial 55 finished with value: 0.4233049487844008 and parameters: {'kernel': 'poly', 'C': 0.0170880183388371, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.04589266156983126, 'coef0': 0.012980192678273661, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,801] Trial 56 finished with value: 0.8799767201561546 and parameters: {'kernel': 'poly', 'C': 28.846046274181518, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.32407442460019786, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:44,970] Trial 57 finished with value: 0.832321094608515 and parameters: {'kernel': 'poly', 'C': 446.88707386970157, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.1571225641281701, 'degree': 5}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,149] Trial 58 finished with value: 0.8675044528192337 and parameters: {'kernel': 'poly', 'C': 153.45041341850344, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4621269623929681, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,318] Trial 59 finished with value: 0.8545668496369059 and parameters: {'kernel': 'rbf', 'C': 9.747835948434783, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0340385731791092}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,504] Trial 60 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 58.80486335711335, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.22414384118891217, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,645] Trial 61 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 57.113083926843835, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.20760866440442308, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,784] Trial 62 finished with value: 0.8848061125159542 and parameters: {'kernel': 'poly', 'C': 48.78598464479594, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.13986925882400936, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:45,947] Trial 63 finished with value: 0.8621924012848015 and parameters: {'kernel': 'poly', 'C': 570.5661551557471, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2073868225768781, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,094] Trial 64 finished with value: 0.8882332485739732 and parameters: {'kernel': 'poly', 'C': 71.2215300863798, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.21403277125876208, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,254] Trial 65 finished with value: 0.8724105059370679 and parameters: {'kernel': 'poly', 'C': 207.5564268749994, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3408202681420422, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,385] Trial 66 finished with value: 0.67673024127297 and parameters: {'kernel': 'sigmoid', 'C': 20.292395640597576, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.24062810759586262}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,529] Trial 67 finished with value: 0.8847033823322425 and parameters: {'kernel': 'poly', 'C': 115.99927919059049, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.13526196646671634, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,667] Trial 68 finished with value: 0.4233049487844008 and parameters: {'kernel': 'poly', 'C': 0.001921822937896203, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.07876791060419808, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,805] Trial 69 finished with value: 0.8436501537166989 and parameters: {'kernel': 'linear', 'C': 3.935002822403128, 'class_weight': None}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:46,945] Trial 70 finished with value: 0.8468275820766514 and parameters: {'kernel': 'poly', 'C': 55.73253528423368, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.36152352667815507, 'degree': 4}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:47,088] Trial 71 finished with value: 0.8847033823322425 and parameters: {'kernel': 'poly', 'C': 73.98729096124191, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.21788010038041492, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:47,242] Trial 72 finished with value: 0.867108074414354 and parameters: {'kernel': 'poly', 'C': 265.5006398791684, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.25213634667550106, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:47,379] Trial 73 finished with value: 0.8753615127525382 and parameters: {'kernel': 'poly', 'C': 13.567564061313309, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.18778203960706277, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.
[I 2025-04-18 15:04:47,520] Trial 74 finished with value: 0.8848061125159542 and parameters: {'kernel': 'poly', 'C': 40.515837654183656, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.30064760603633656, 'degree': 2}. Best is trial 32 with value: 0.8882332485739732.

best_params

{'kernel': 'poly',
 'C': 17.463245987810147,
 'class_weight': None,
 'coef0': 0.8704211614621142,
 'degree': 2,
 'gamma': 'auto'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                               0
target                                                          no_fragmentation
model                             SVC_no_fragmentation_smote_opt-smote_opt-model
holdout_test_f1_macro                                                   0.829545
holdout_test_accuracy_balanced                                          0.829545
holdout_test_roc_auc                                                    0.949091
holdout_test_f1                                                             0.75
holdout_test_accuracy                                                   0.866667
cv_test_f1_macro_median                                                  0.90293
cv_test_accuracy_balanced_median                                         0.90293
cv_test_roc_auc_median                                                  0.956044
cv_test_f1_median                                                       0.857143
cv_test_accuracy_median                                                 0.924528
cv_test_precision_class_0_median                                         0.96875
cv_test_recall_class_0_median                                           0.897436
cv_test_f1_class_0_median                                               0.945946

Model saved in ..\results\models_modelling4\SVC_no_fragmentation_smote_opt-smote_opt-model