Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'optuna-opt-mean-smote_default-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 400

save_model_and_metrics = True
metrics_file = 'metrics_modelling4_smotenc_mean_opt.xlsx'

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int=n_trials,
    step_scoring_average:str=step_scoring_average,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    
    smote_params = smote_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
        seed=seed,
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:47:53,648] A new study created in memory with name: smote_study
[I 2025-04-16 00:47:53,992] Trial 0 finished with value: 0.8068955952248212 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8068955952248212.
[I 2025-04-16 00:47:54,096] Trial 1 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:47:54,202] Trial 2 finished with value: 0.8074201035939587 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:47:54,308] Trial 3 finished with value: 0.8087537607513812 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:47:54,411] Trial 4 finished with value: 0.8068384611533034 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:47:54,514] Trial 5 finished with value: 0.8053427303242218 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:47:54,624] Trial 6 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:54,732] Trial 7 finished with value: 0.8113830440145984 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:54,833] Trial 8 finished with value: 0.8053501190675637 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:54,935] Trial 9 finished with value: 0.8010217000767076 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,045] Trial 10 finished with value: 0.802875485873124 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,169] Trial 11 finished with value: 0.814998436851892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,282] Trial 12 finished with value: 0.8126049084942002 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,427] Trial 13 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,535] Trial 14 finished with value: 0.8069855520521557 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,648] Trial 15 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,763] Trial 16 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,873] Trial 17 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:55,983] Trial 18 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:56,095] Trial 19 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:56,208] Trial 20 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:56,323] Trial 21 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:56,431] Trial 22 finished with value: 0.814998436851892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:47:56,546] Trial 23 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:56,660] Trial 24 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:56,773] Trial 25 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:56,880] Trial 26 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,026] Trial 27 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,136] Trial 28 finished with value: 0.8075842330830095 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,244] Trial 29 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,356] Trial 30 finished with value: 0.8025734233923184 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.76}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,485] Trial 31 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,596] Trial 32 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,715] Trial 33 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,823] Trial 34 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:57,937] Trial 35 finished with value: 0.8069492369479698 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,050] Trial 36 finished with value: 0.8085337192767287 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,202] Trial 37 finished with value: 0.8061574155477392 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,310] Trial 38 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,416] Trial 39 finished with value: 0.8053501190675637 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,524] Trial 40 finished with value: 0.8061476556952193 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,640] Trial 41 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,755] Trial 42 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,873] Trial 43 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:58,993] Trial 44 finished with value: 0.8042962512235992 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,115] Trial 45 finished with value: 0.8142786468962709 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,227] Trial 46 finished with value: 0.8010269395080135 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,347] Trial 47 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,462] Trial 48 finished with value: 0.8109484924727954 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,613] Trial 49 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,749] Trial 50 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,867] Trial 51 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:47:59,997] Trial 52 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,118] Trial 53 finished with value: 0.8142786468962709 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,249] Trial 54 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,363] Trial 55 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,478] Trial 56 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,595] Trial 57 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,707] Trial 58 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,828] Trial 59 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:00,942] Trial 60 finished with value: 0.8117736761083343 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.71}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,065] Trial 61 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,192] Trial 62 finished with value: 0.8010269395080135 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,348] Trial 63 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,463] Trial 64 finished with value: 0.8098725704212288 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,577] Trial 65 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,692] Trial 66 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,808] Trial 67 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:01,920] Trial 68 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,031] Trial 69 finished with value: 0.8077871906702357 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,143] Trial 70 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,265] Trial 71 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,379] Trial 72 finished with value: 0.8081643440955125 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,492] Trial 73 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,606] Trial 74 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,727] Trial 75 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,843] Trial 76 finished with value: 0.811406589032057 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:02,972] Trial 77 finished with value: 0.8035608434674104 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,101] Trial 78 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,214] Trial 79 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,325] Trial 80 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,435] Trial 81 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,546] Trial 82 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,696] Trial 83 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,810] Trial 84 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:03,923] Trial 85 finished with value: 0.8069855520521557 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,062] Trial 86 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,176] Trial 87 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,287] Trial 88 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,404] Trial 89 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,523] Trial 90 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,637] Trial 91 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,755] Trial 92 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,870] Trial 93 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:04,980] Trial 94 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,091] Trial 95 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,203] Trial 96 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,316] Trial 97 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,428] Trial 98 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,539] Trial 99 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,654] Trial 100 finished with value: 0.8036137004097457 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,809] Trial 101 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:05,920] Trial 102 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.64}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smotenc_optuna-op...
holdout_test_f1_macro                                                      0.777184
holdout_test_accuracy_balanced                                             0.770833
holdout_test_roc_auc                                                       0.885802
holdout_test_f1                                                            0.848485
holdout_test_accuracy                                                           0.8
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

Model saved in ../results/models_modelling4/LogisticRegression_splashing_smotenc_optuna-opt-mean-smote_default-model

In [7]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:48:39,863] A new study created in memory with name: smote_study
[I 2025-04-16 00:48:39,965] Trial 0 finished with value: 0.8068955952248212 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8068955952248212.
[I 2025-04-16 00:48:40,065] Trial 1 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:48:40,162] Trial 2 finished with value: 0.8074201035939587 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:48:40,262] Trial 3 finished with value: 0.8087537607513812 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:48:40,363] Trial 4 finished with value: 0.8068384611533034 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:48:40,461] Trial 5 finished with value: 0.8053427303242218 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8093303573473086.
[I 2025-04-16 00:48:40,559] Trial 6 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:40,656] Trial 7 finished with value: 0.8113830440145984 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:40,772] Trial 8 finished with value: 0.8053501190675637 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:40,874] Trial 9 finished with value: 0.8010217000767076 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:40,977] Trial 10 finished with value: 0.802875485873124 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,080] Trial 11 finished with value: 0.814998436851892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,186] Trial 12 finished with value: 0.8126049084942002 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,292] Trial 13 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,393] Trial 14 finished with value: 0.8069855520521557 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,498] Trial 15 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,600] Trial 16 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,739] Trial 17 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,840] Trial 18 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:41,941] Trial 19 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:42,044] Trial 20 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:42,148] Trial 21 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:42,254] Trial 22 finished with value: 0.814998436851892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 6 with value: 0.8153695294526967.
[I 2025-04-16 00:48:42,356] Trial 23 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,459] Trial 24 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,566] Trial 25 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,675] Trial 26 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,776] Trial 27 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,891] Trial 28 finished with value: 0.8075842330830095 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:42,995] Trial 29 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,101] Trial 30 finished with value: 0.8025734233923184 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.76}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,206] Trial 31 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,310] Trial 32 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,411] Trial 33 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,513] Trial 34 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,654] Trial 35 finished with value: 0.8069492369479698 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,756] Trial 36 finished with value: 0.8085337192767287 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,863] Trial 37 finished with value: 0.8061574155477392 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:43,968] Trial 38 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,073] Trial 39 finished with value: 0.8053501190675637 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,177] Trial 40 finished with value: 0.8061476556952193 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,279] Trial 41 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,383] Trial 42 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,486] Trial 43 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,590] Trial 44 finished with value: 0.8042962512235992 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,694] Trial 45 finished with value: 0.8142786468962709 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,809] Trial 46 finished with value: 0.8010269395080135 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:44,911] Trial 47 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,014] Trial 48 finished with value: 0.8109484924727954 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,117] Trial 49 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,220] Trial 50 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,323] Trial 51 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,425] Trial 52 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,528] Trial 53 finished with value: 0.8142786468962709 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,666] Trial 54 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,769] Trial 55 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,873] Trial 56 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:45,977] Trial 57 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,079] Trial 58 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,183] Trial 59 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,287] Trial 60 finished with value: 0.8117736761083343 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.71}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,390] Trial 61 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,494] Trial 62 finished with value: 0.8010269395080135 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,607] Trial 63 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,710] Trial 64 finished with value: 0.8098725704212288 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,814] Trial 65 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:46,916] Trial 66 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,019] Trial 67 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,123] Trial 68 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,226] Trial 69 finished with value: 0.8077871906702357 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,332] Trial 70 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,438] Trial 71 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,579] Trial 72 finished with value: 0.8081643440955125 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,682] Trial 73 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,781] Trial 74 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,885] Trial 75 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:47,987] Trial 76 finished with value: 0.811406589032057 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,095] Trial 77 finished with value: 0.8035608434674104 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,202] Trial 78 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,320] Trial 79 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,427] Trial 80 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,531] Trial 81 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,637] Trial 82 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,740] Trial 83 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,840] Trial 84 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:48,943] Trial 85 finished with value: 0.8069855520521557 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,048] Trial 86 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,151] Trial 87 finished with value: 0.8114962692574578 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,253] Trial 88 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,356] Trial 89 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,460] Trial 90 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,602] Trial 91 finished with value: 0.8178946727747087 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,704] Trial 92 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,807] Trial 93 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:49,920] Trial 94 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,022] Trial 95 finished with value: 0.8074860985911175 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,127] Trial 96 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,231] Trial 97 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,337] Trial 98 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,440] Trial 99 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,552] Trial 100 finished with value: 0.8036137004097457 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,661] Trial 101 finished with value: 0.8172197142134794 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 23 with value: 0.8182701087803969.
[I 2025-04-16 00:48:50,770] Trial 102 finished with value: 0.8182701087803969 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 23 with value: 0.8182701087803969.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.64}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smotenc_optuna-op...
holdout_test_f1_macro                                                      0.777184
holdout_test_accuracy_balanced                                             0.770833
holdout_test_roc_auc                                                       0.885802
holdout_test_f1                                                            0.848485
holdout_test_accuracy                                                           0.8
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

Model saved in ../results/models_modelling4/LogisticRegression_splashing_smotenc_optuna-opt-mean-smote_default-model

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:49:23,692] A new study created in memory with name: smote_study
[I 2025-04-16 00:49:23,786] Trial 0 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.7893690960867744.
[I 2025-04-16 00:49:23,876] Trial 1 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.7961089219778902.
[I 2025-04-16 00:49:23,964] Trial 2 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.7961089219778902.
[I 2025-04-16 00:49:24,055] Trial 3 finished with value: 0.7917448628083663 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.7961089219778902.
[I 2025-04-16 00:49:24,152] Trial 4 finished with value: 0.7927358172501057 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.7961089219778902.
[I 2025-04-16 00:49:24,246] Trial 5 finished with value: 0.7917448628083663 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.7961089219778902.
[I 2025-04-16 00:49:24,336] Trial 6 finished with value: 0.8091977187867118 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,428] Trial 7 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,521] Trial 8 finished with value: 0.7926459322449665 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,619] Trial 9 finished with value: 0.7960126534082977 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,760] Trial 10 finished with value: 0.8091426381832775 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,858] Trial 11 finished with value: 0.8091426381832775 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:24,954] Trial 12 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:25,050] Trial 13 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:25,144] Trial 14 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 6 with value: 0.8091977187867118.
[I 2025-04-16 00:49:25,240] Trial 15 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 15 with value: 0.8092389067528699.
[I 2025-04-16 00:49:25,334] Trial 16 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 15 with value: 0.8092389067528699.
[I 2025-04-16 00:49:25,427] Trial 17 finished with value: 0.8025477779007352 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.71}. Best is trial 15 with value: 0.8092389067528699.
[I 2025-04-16 00:49:25,521] Trial 18 finished with value: 0.7957086668873955 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 15 with value: 0.8092389067528699.
[I 2025-04-16 00:49:25,613] Trial 19 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 15 with value: 0.8092389067528699.
[I 2025-04-16 00:49:25,708] Trial 20 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:25,802] Trial 21 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:25,899] Trial 22 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:25,995] Trial 23 finished with value: 0.8091426381832775 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.7}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,103] Trial 24 finished with value: 0.8056766318977224 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,201] Trial 25 finished with value: 0.7995749282634453 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,298] Trial 26 finished with value: 0.8060768869882171 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,397] Trial 27 finished with value: 0.796019036972751 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,527] Trial 28 finished with value: 0.8025477779007352 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,633] Trial 29 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,730] Trial 30 finished with value: 0.7957086668873955 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,824] Trial 31 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:26,921] Trial 32 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,017] Trial 33 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,115] Trial 34 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6699999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,212] Trial 35 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,308] Trial 36 finished with value: 0.8059208826285197 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6599999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,404] Trial 37 finished with value: 0.8091977187867118 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.69}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,509] Trial 38 finished with value: 0.7927358172501057 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,605] Trial 39 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,702] Trial 40 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,797] Trial 41 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,894] Trial 42 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:27,990] Trial 43 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,084] Trial 44 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,214] Trial 45 finished with value: 0.7995749282634453 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,307] Trial 46 finished with value: 0.7923419457240641 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,404] Trial 47 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6699999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,499] Trial 48 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,595] Trial 49 finished with value: 0.8056766318977224 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,696] Trial 50 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6599999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,794] Trial 51 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:28,892] Trial 52 finished with value: 0.796019036972751 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,023] Trial 53 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,121] Trial 54 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,217] Trial 55 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,312] Trial 56 finished with value: 0.8091977187867118 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,407] Trial 57 finished with value: 0.794744356616779 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,500] Trial 58 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,634] Trial 59 finished with value: 0.8058246140589272 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,728] Trial 60 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,823] Trial 61 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:29,918] Trial 62 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,024] Trial 63 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,121] Trial 64 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,216] Trial 65 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6699999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,310] Trial 66 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,408] Trial 67 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 10, 'sampling_strategy': 1.0}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,500] Trial 68 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,594] Trial 69 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,687] Trial 70 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,780] Trial 71 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,873] Trial 72 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:30,964] Trial 73 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6599999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,059] Trial 74 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,189] Trial 75 finished with value: 0.8058246140589272 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.69}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,286] Trial 76 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,384] Trial 77 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,484] Trial 78 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8099999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,578] Trial 79 finished with value: 0.8028517644216374 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6699999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,674] Trial 80 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,767] Trial 81 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,862] Trial 82 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:31,955] Trial 83 finished with value: 0.8091426381832775 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,048] Trial 84 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,142] Trial 85 finished with value: 0.8023997957395304 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,240] Trial 86 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,339] Trial 87 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,435] Trial 88 finished with value: 0.8091977187867118 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,530] Trial 89 finished with value: 0.7923419457240641 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,627] Trial 90 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,723] Trial 91 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,820] Trial 92 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:32,917] Trial 93 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,013] Trial 94 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,155] Trial 95 finished with value: 0.8090497366255069 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,249] Trial 96 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,341] Trial 97 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.61}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,433] Trial 98 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,527] Trial 99 finished with value: 0.8027037822604326 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6599999999999999}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,619] Trial 100 finished with value: 0.8092389067528699 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,712] Trial 101 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,805] Trial 102 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 20 with value: 0.812515742911062.
[I 2025-04-16 00:49:33,897] Trial 103 finished with value: 0.812515742911062 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 20 with value: 0.812515742911062.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.64}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.785539
holdout_test_accuracy_balanced                                                0.825
holdout_test_roc_auc                                                       0.952727
holdout_test_f1                                                            0.708333
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.869231
cv_test_roc_auc_median                                                     0.945055
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.820513
cv_test_f1_class_0_median                                                  0.888889

Model saved in ../results/models_modelling4/LogisticRegression_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# KNClassifier

In [9]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:50:03,040] A new study created in memory with name: smote_study
[I 2025-04-16 00:50:03,207] Trial 0 finished with value: 0.833176217119686 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.833176217119686.
[I 2025-04-16 00:50:03,332] Trial 1 finished with value: 0.8366591229825184 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:03,460] Trial 2 finished with value: 0.8344734678470631 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:03,586] Trial 3 finished with value: 0.8327111603202334 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:03,716] Trial 4 finished with value: 0.8295692621139823 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:03,846] Trial 5 finished with value: 0.8281833636366075 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:03,977] Trial 6 finished with value: 0.8311143357143546 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:04,103] Trial 7 finished with value: 0.8247857425288379 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:04,229] Trial 8 finished with value: 0.8351983659277551 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:04,353] Trial 9 finished with value: 0.834799246485345 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8366591229825184.
[I 2025-04-16 00:50:04,480] Trial 10 finished with value: 0.8520810774742892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 10 with value: 0.8520810774742892.
[I 2025-04-16 00:50:04,610] Trial 11 finished with value: 0.8520221277912794 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 10 with value: 0.8520810774742892.
[I 2025-04-16 00:50:04,743] Trial 12 finished with value: 0.8510723981404867 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 10 with value: 0.8520810774742892.
[I 2025-04-16 00:50:04,874] Trial 13 finished with value: 0.8510723981404867 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 10 with value: 0.8520810774742892.
[I 2025-04-16 00:50:05,002] Trial 14 finished with value: 0.8292835257788436 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 10 with value: 0.8520810774742892.
[I 2025-04-16 00:50:05,134] Trial 15 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,306] Trial 16 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,441] Trial 17 finished with value: 0.8302720840660435 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,574] Trial 18 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,708] Trial 19 finished with value: 0.8560376964470118 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,843] Trial 20 finished with value: 0.8390765124924072 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:05,986] Trial 21 finished with value: 0.8531391533145201 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,121] Trial 22 finished with value: 0.8558240919878938 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,254] Trial 23 finished with value: 0.8337206910773841 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,384] Trial 24 finished with value: 0.8474357352199255 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,517] Trial 25 finished with value: 0.8441046010113932 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,646] Trial 26 finished with value: 0.8366591229825184 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,774] Trial 27 finished with value: 0.8348628229259806 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:06,905] Trial 28 finished with value: 0.8435215400650963 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.76}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,041] Trial 29 finished with value: 0.8524751564660754 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,176] Trial 30 finished with value: 0.8500059824236158 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,311] Trial 31 finished with value: 0.8560376964470118 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,446] Trial 32 finished with value: 0.833983575903422 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,581] Trial 33 finished with value: 0.8535084726124803 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.99}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,716] Trial 34 finished with value: 0.8332970918348482 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:07,881] Trial 35 finished with value: 0.8544691285465785 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,012] Trial 36 finished with value: 0.8302720840660435 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,145] Trial 37 finished with value: 0.8441046010113932 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,277] Trial 38 finished with value: 0.8553157616286237 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,407] Trial 39 finished with value: 0.8392450827577232 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,539] Trial 40 finished with value: 0.8340893881137622 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 15 with value: 0.8577308673938092.
[I 2025-04-16 00:50:08,674] Trial 41 finished with value: 0.8588877870130666 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:08,808] Trial 42 finished with value: 0.8500059824236158 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:08,940] Trial 43 finished with value: 0.8440156864415955 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:09,075] Trial 44 finished with value: 0.8401948214141944 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:09,211] Trial 45 finished with value: 0.8346385431179312 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:09,344] Trial 46 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:09,477] Trial 47 finished with value: 0.8386598728399198 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 41 with value: 0.8588877870130666.
[I 2025-04-16 00:50:09,611] Trial 48 finished with value: 0.8613703804709048 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:09,741] Trial 49 finished with value: 0.8454154583269801 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.73}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:09,870] Trial 50 finished with value: 0.8348679295108994 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.71}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,000] Trial 51 finished with value: 0.8418297791374989 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,132] Trial 52 finished with value: 0.8374289563047953 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,267] Trial 53 finished with value: 0.8461557150439366 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,452] Trial 54 finished with value: 0.8409536326855866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8099999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,588] Trial 55 finished with value: 0.8368729748346152 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,724] Trial 56 finished with value: 0.8329261659432217 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,857] Trial 57 finished with value: 0.8400542124986116 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:10,991] Trial 58 finished with value: 0.8483470173494368 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,121] Trial 59 finished with value: 0.84738879116938 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,251] Trial 60 finished with value: 0.8455741639903743 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,382] Trial 61 finished with value: 0.8500059824236158 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,514] Trial 62 finished with value: 0.8315051601914868 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,645] Trial 63 finished with value: 0.8553157616286237 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,783] Trial 64 finished with value: 0.844795008599607 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:11,918] Trial 65 finished with value: 0.8441046010113932 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,049] Trial 66 finished with value: 0.8315051601914868 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,181] Trial 67 finished with value: 0.8435215400650963 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,312] Trial 68 finished with value: 0.8474357352199255 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,444] Trial 69 finished with value: 0.8368729748346152 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,572] Trial 70 finished with value: 0.8400542124986116 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,705] Trial 71 finished with value: 0.8531798879607954 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:12,875] Trial 72 finished with value: 0.8322170139437342 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,007] Trial 73 finished with value: 0.8500059824236158 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,143] Trial 74 finished with value: 0.8560376964470118 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,278] Trial 75 finished with value: 0.849492021801724 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,410] Trial 76 finished with value: 0.8399287731503167 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,550] Trial 77 finished with value: 0.8302720840660435 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,697] Trial 78 finished with value: 0.8398650628991425 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,837] Trial 79 finished with value: 0.8608673402111474 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:13,978] Trial 80 finished with value: 0.845576611607519 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,131] Trial 81 finished with value: 0.8348679295108994 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.71}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,271] Trial 82 finished with value: 0.839138932717557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.77}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,451] Trial 83 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,596] Trial 84 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,736] Trial 85 finished with value: 0.84738879116938 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:14,877] Trial 86 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,008] Trial 87 finished with value: 0.8335092365935894 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,140] Trial 88 finished with value: 0.8488420771405417 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,271] Trial 89 finished with value: 0.846258296920001 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,401] Trial 90 finished with value: 0.8319585390149477 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,532] Trial 91 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,665] Trial 92 finished with value: 0.8577308673938092 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,796] Trial 93 finished with value: 0.837946303809674 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:15,927] Trial 94 finished with value: 0.8608673402111474 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,062] Trial 95 finished with value: 0.8489558400436203 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.75}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,197] Trial 96 finished with value: 0.8540578605382146 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,334] Trial 97 finished with value: 0.839138932717557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.77}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,470] Trial 98 finished with value: 0.8608673402111474 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,606] Trial 99 finished with value: 0.8510449419365599 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,781] Trial 100 finished with value: 0.8608673402111474 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:16,927] Trial 101 finished with value: 0.8396917578485279 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.69}. Best is trial 48 with value: 0.8613703804709048.
[I 2025-04-16 00:50:17,062] Trial 102 finished with value: 0.8608673402111474 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 48 with value: 0.8613703804709048.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.73}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smotenc_optuna-...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.883488
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.844575
cv_test_accuracy_balanced_median                                           0.870743
cv_test_roc_auc_median                                                     0.930075
cv_test_f1_median                                                          0.870968
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.777778
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.818182

Model saved in ../results/models_modelling4/KNeighborsClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [10]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:50:58,286] A new study created in memory with name: smote_study
[I 2025-04-16 00:50:58,414] Trial 0 finished with value: 0.8121592476536206 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8121592476536206.
[I 2025-04-16 00:50:58,537] Trial 1 finished with value: 0.8212452005407724 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8212452005407724.
[I 2025-04-16 00:50:58,653] Trial 2 finished with value: 0.8239651236730726 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8239651236730726.
[I 2025-04-16 00:50:58,777] Trial 3 finished with value: 0.8191221072565593 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.8239651236730726.
[I 2025-04-16 00:50:58,916] Trial 4 finished with value: 0.8034919521746071 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 2 with value: 0.8239651236730726.
[I 2025-04-16 00:50:59,038] Trial 5 finished with value: 0.806155302510302 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 2 with value: 0.8239651236730726.
[I 2025-04-16 00:50:59,158] Trial 6 finished with value: 0.820306302993222 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8239651236730726.
[I 2025-04-16 00:50:59,278] Trial 7 finished with value: 0.8412327840745791 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:50:59,400] Trial 8 finished with value: 0.8147254660433801 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:50:59,520] Trial 9 finished with value: 0.8091805248721717 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:50:59,645] Trial 10 finished with value: 0.8197981983161726 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:50:59,770] Trial 11 finished with value: 0.8319933825571384 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:50:59,933] Trial 12 finished with value: 0.8143202124630167 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,057] Trial 13 finished with value: 0.8319770453440689 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,176] Trial 14 finished with value: 0.8162503142311996 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,296] Trial 15 finished with value: 0.8303463309284993 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,419] Trial 16 finished with value: 0.8160517067414903 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,545] Trial 17 finished with value: 0.8027731426988988 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,669] Trial 18 finished with value: 0.8253785363432053 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,792] Trial 19 finished with value: 0.8150772802401052 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:00,914] Trial 20 finished with value: 0.8091805248721717 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,035] Trial 21 finished with value: 0.8306411618470033 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,159] Trial 22 finished with value: 0.8088944004160744 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,283] Trial 23 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,409] Trial 24 finished with value: 0.8191078807741684 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,531] Trial 25 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,655] Trial 26 finished with value: 0.8029834766624088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,777] Trial 27 finished with value: 0.8092663443151954 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:01,903] Trial 28 finished with value: 0.8128522526532775 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,028] Trial 29 finished with value: 0.825031571619664 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,153] Trial 30 finished with value: 0.8067119904418395 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,276] Trial 31 finished with value: 0.8319933825571384 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,406] Trial 32 finished with value: 0.8186684242977403 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,533] Trial 33 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,696] Trial 34 finished with value: 0.8033885078222198 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.83}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,825] Trial 35 finished with value: 0.8092631228614117 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:02,947] Trial 36 finished with value: 0.8029834766624088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,074] Trial 37 finished with value: 0.8031321839933894 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,210] Trial 38 finished with value: 0.814281021734863 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,332] Trial 39 finished with value: 0.8067702633615051 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,452] Trial 40 finished with value: 0.813771185035569 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,573] Trial 41 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,696] Trial 42 finished with value: 0.81506862664341 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,816] Trial 43 finished with value: 0.8186684242977403 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:03,935] Trial 44 finished with value: 0.813565404079346 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,055] Trial 45 finished with value: 0.8239651236730726 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,177] Trial 46 finished with value: 0.8138537146094762 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,299] Trial 47 finished with value: 0.8119304518201851 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,427] Trial 48 finished with value: 0.8148022041502135 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,556] Trial 49 finished with value: 0.8127368454821398 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,681] Trial 50 finished with value: 0.8136600575855668 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,806] Trial 51 finished with value: 0.827794598788741 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:04,931] Trial 52 finished with value: 0.8198802314930623 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,053] Trial 53 finished with value: 0.8303463309284993 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,178] Trial 54 finished with value: 0.827794598788741 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,300] Trial 55 finished with value: 0.8217003127446169 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,421] Trial 56 finished with value: 0.8067702633615051 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,582] Trial 57 finished with value: 0.8198802314930623 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,708] Trial 58 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,833] Trial 59 finished with value: 0.8197981983161726 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:05,961] Trial 60 finished with value: 0.8088944004160744 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,086] Trial 61 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,213] Trial 62 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,339] Trial 63 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,466] Trial 64 finished with value: 0.8145450621427851 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,587] Trial 65 finished with value: 0.8217003127446169 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,708] Trial 66 finished with value: 0.8119304518201851 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,831] Trial 67 finished with value: 0.8077583277070809 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:06,967] Trial 68 finished with value: 0.8311970010977204 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,089] Trial 69 finished with value: 0.825031571619664 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,213] Trial 70 finished with value: 0.8246016654077754 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.64}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,334] Trial 71 finished with value: 0.827794598788741 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,461] Trial 72 finished with value: 0.8217003127446169 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,588] Trial 73 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,719] Trial 74 finished with value: 0.8306411618470033 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,846] Trial 75 finished with value: 0.8029834766624088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:07,970] Trial 76 finished with value: 0.820997650526531 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,094] Trial 77 finished with value: 0.8099694710132946 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,217] Trial 78 finished with value: 0.8171894709180864 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,342] Trial 79 finished with value: 0.8311970010977204 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,498] Trial 80 finished with value: 0.8217003127446169 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,623] Trial 81 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,749] Trial 82 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:08,874] Trial 83 finished with value: 0.814281021734863 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,004] Trial 84 finished with value: 0.8107175484104382 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,127] Trial 85 finished with value: 0.8029834766624088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,249] Trial 86 finished with value: 0.8319933825571384 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,373] Trial 87 finished with value: 0.8319770453440689 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,495] Trial 88 finished with value: 0.8232211940820235 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,619] Trial 89 finished with value: 0.8077491338319012 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,747] Trial 90 finished with value: 0.806862695712325 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:09,874] Trial 91 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,012] Trial 92 finished with value: 0.8386273889448395 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,142] Trial 93 finished with value: 0.8311970010977204 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,268] Trial 94 finished with value: 0.827794598788741 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,396] Trial 95 finished with value: 0.8306411618470033 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,518] Trial 96 finished with value: 0.8186684242977403 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,640] Trial 97 finished with value: 0.8029834766624088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,766] Trial 98 finished with value: 0.820997650526531 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:10,892] Trial 99 finished with value: 0.8207113341530332 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:11,019] Trial 100 finished with value: 0.8160517067414903 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:11,144] Trial 101 finished with value: 0.835260667781508 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:11,312] Trial 102 finished with value: 0.8386273889448395 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:11,434] Trial 103 finished with value: 0.8386273889448395 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.
[I 2025-04-16 00:51:11,558] Trial 104 finished with value: 0.8386273889448395 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8412327840745791.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.63}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smotenc_...
holdout_test_f1_macro                                                      0.834656
holdout_test_accuracy_balanced                                             0.845455
holdout_test_roc_auc                                                       0.945455
holdout_test_f1                                                            0.761905
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.847115
cv_test_accuracy_balanced_median                                           0.848718
cv_test_roc_auc_median                                                     0.931319
cv_test_f1_median                                                          0.774194
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.921053
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.923077

Model saved in ../results/models_modelling4/KNeighborsClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# SVC

In [11]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:51:49,207] A new study created in memory with name: smote_study
[I 2025-04-16 00:51:49,354] Trial 0 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8620559168302458.
[I 2025-04-16 00:51:49,490] Trial 1 finished with value: 0.8606024698993406 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8620559168302458.
[I 2025-04-16 00:51:49,618] Trial 2 finished with value: 0.8588694020675373 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8620559168302458.
[I 2025-04-16 00:51:49,761] Trial 3 finished with value: 0.8500846768064889 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8620559168302458.
[I 2025-04-16 00:51:49,903] Trial 4 finished with value: 0.8642617849079628 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,048] Trial 5 finished with value: 0.8426913812094119 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,179] Trial 6 finished with value: 0.8489446000725444 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,310] Trial 7 finished with value: 0.8597425632251888 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,444] Trial 8 finished with value: 0.8531163386980645 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,573] Trial 9 finished with value: 0.863247581545024 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 4 with value: 0.8642617849079628.
[I 2025-04-16 00:51:50,721] Trial 10 finished with value: 0.8645390566558228 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 10 with value: 0.8645390566558228.
[I 2025-04-16 00:51:50,867] Trial 11 finished with value: 0.8645390566558228 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 10 with value: 0.8645390566558228.
[I 2025-04-16 00:51:51,015] Trial 12 finished with value: 0.8645390566558228 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 10 with value: 0.8645390566558228.
[I 2025-04-16 00:51:51,150] Trial 13 finished with value: 0.8557057570292727 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 10 with value: 0.8645390566558228.
[I 2025-04-16 00:51:51,285] Trial 14 finished with value: 0.8515387879100551 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 10 with value: 0.8645390566558228.
[I 2025-04-16 00:51:51,426] Trial 15 finished with value: 0.864569301764469 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 15 with value: 0.864569301764469.
[I 2025-04-16 00:51:51,570] Trial 16 finished with value: 0.8714733233695012 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 16 with value: 0.8714733233695012.
[I 2025-04-16 00:51:51,755] Trial 17 finished with value: 0.8536711014975948 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 16 with value: 0.8714733233695012.
[I 2025-04-16 00:51:51,901] Trial 18 finished with value: 0.8606024698993406 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 16 with value: 0.8714733233695012.
[I 2025-04-16 00:51:52,047] Trial 19 finished with value: 0.8714733233695012 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 16 with value: 0.8714733233695012.
[I 2025-04-16 00:51:52,194] Trial 20 finished with value: 0.8615088623441158 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 16 with value: 0.8714733233695012.
[I 2025-04-16 00:51:52,339] Trial 21 finished with value: 0.8749408312116287 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:52,486] Trial 22 finished with value: 0.8500838074157402 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:52,629] Trial 23 finished with value: 0.8616312399664935 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:52,768] Trial 24 finished with value: 0.8449130153170329 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:52,905] Trial 25 finished with value: 0.8606539838311243 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,046] Trial 26 finished with value: 0.8643479680986202 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,190] Trial 27 finished with value: 0.8527569764019205 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,338] Trial 28 finished with value: 0.8615088623441158 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,487] Trial 29 finished with value: 0.857436388082566 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,632] Trial 30 finished with value: 0.8606311425267705 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,779] Trial 31 finished with value: 0.8749408312116287 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:53,927] Trial 32 finished with value: 0.8599267602094968 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,075] Trial 33 finished with value: 0.8615674347241168 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,222] Trial 34 finished with value: 0.8573275181942843 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,402] Trial 35 finished with value: 0.8715896725663523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,543] Trial 36 finished with value: 0.8577809725868143 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,685] Trial 37 finished with value: 0.8565789181869242 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,838] Trial 38 finished with value: 0.8563051072124634 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:54,983] Trial 39 finished with value: 0.8502461828503478 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,136] Trial 40 finished with value: 0.8602300255766643 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,285] Trial 41 finished with value: 0.8615674347241168 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,437] Trial 42 finished with value: 0.8682319186995251 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,585] Trial 43 finished with value: 0.849101776369807 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,736] Trial 44 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:55,885] Trial 45 finished with value: 0.8616312399664935 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,032] Trial 46 finished with value: 0.864569301764469 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,172] Trial 47 finished with value: 0.8675449442319012 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,320] Trial 48 finished with value: 0.8500838074157402 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,472] Trial 49 finished with value: 0.8568013740765663 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,619] Trial 50 finished with value: 0.856648822325963 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,771] Trial 51 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:56,924] Trial 52 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,076] Trial 53 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,259] Trial 54 finished with value: 0.8527946384135093 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,410] Trial 55 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,560] Trial 56 finished with value: 0.8642617849079628 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,713] Trial 57 finished with value: 0.8609523809166487 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.99}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:57,861] Trial 58 finished with value: 0.8552448857338 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,004] Trial 59 finished with value: 0.8447881207439893 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.72}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,160] Trial 60 finished with value: 0.8573275181942843 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,312] Trial 61 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,473] Trial 62 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,627] Trial 63 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,782] Trial 64 finished with value: 0.8500846768064889 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:58,933] Trial 65 finished with value: 0.8568892838835275 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,085] Trial 66 finished with value: 0.864569301764469 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,236] Trial 67 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,386] Trial 68 finished with value: 0.8616312399664935 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,531] Trial 69 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,675] Trial 70 finished with value: 0.8606024698993406 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:51:59,831] Trial 71 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,018] Trial 72 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,168] Trial 73 finished with value: 0.8615088623441158 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,319] Trial 74 finished with value: 0.8527569764019205 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,470] Trial 75 finished with value: 0.86393149885375 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,629] Trial 76 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.99}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,778] Trial 77 finished with value: 0.8573275181942843 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:00,927] Trial 78 finished with value: 0.8536711014975948 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,077] Trial 79 finished with value: 0.8682319186995251 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,225] Trial 80 finished with value: 0.8456268516247369 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,373] Trial 81 finished with value: 0.8615088623441158 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,524] Trial 82 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,675] Trial 83 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.99}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,825] Trial 84 finished with value: 0.8581301290752962 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:01,981] Trial 85 finished with value: 0.8614294456785646 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,136] Trial 86 finished with value: 0.8573275181942843 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,289] Trial 87 finished with value: 0.8615674347241168 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,480] Trial 88 finished with value: 0.8682319186995251 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,635] Trial 89 finished with value: 0.8527946384135093 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,784] Trial 90 finished with value: 0.860333828631271 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:02,934] Trial 91 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,084] Trial 92 finished with value: 0.8615088623441158 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,232] Trial 93 finished with value: 0.8620559168302458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,399] Trial 94 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,555] Trial 95 finished with value: 0.8685595704557482 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.99}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,708] Trial 96 finished with value: 0.8536711014975948 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:03,862] Trial 97 finished with value: 0.8714733233695012 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:04,014] Trial 98 finished with value: 0.8615674347241168 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:04,163] Trial 99 finished with value: 0.8611953940159417 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:04,313] Trial 100 finished with value: 0.8682319186995251 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 21 with value: 0.8749408312116287.
[I 2025-04-16 00:52:04,463] Trial 101 finished with value: 0.8573275181942843 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 21 with value: 0.8749408312116287.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                                  0
target                                                                    splashing
model                             SVC_splashing_smotenc_optuna-opt-mean-smote_de...
holdout_test_f1_macro                                                      0.810348
holdout_test_accuracy_balanced                                              0.80787
holdout_test_roc_auc                                                       0.893519
holdout_test_f1                                                            0.865979
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.844575
cv_test_accuracy_balanced_median                                           0.870743
cv_test_roc_auc_median                                                     0.934985
cv_test_f1_median                                                          0.878788
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.761905
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.818182

Model saved in ../results/models_modelling4/SVC_splashing_smotenc_optuna-opt-mean-smote_default-model

In [12]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:52:49,663] A new study created in memory with name: smote_study
[I 2025-04-16 00:52:49,810] Trial 0 finished with value: 0.832140607661619 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.832140607661619.
[I 2025-04-16 00:52:49,945] Trial 1 finished with value: 0.8346658965165396 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:52:50,069] Trial 2 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,210] Trial 3 finished with value: 0.836698142857439 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,343] Trial 4 finished with value: 0.8208641644069442 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,484] Trial 5 finished with value: 0.8333424804018349 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,613] Trial 6 finished with value: 0.822033544985681 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,747] Trial 7 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:50,884] Trial 8 finished with value: 0.8266016203917054 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,014] Trial 9 finished with value: 0.831322710594135 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,139] Trial 10 finished with value: 0.8149467255835907 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,312] Trial 11 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,441] Trial 12 finished with value: 0.8324328681933874 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,581] Trial 13 finished with value: 0.8379705293004892 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,711] Trial 14 finished with value: 0.8289450459554699 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.65}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,848] Trial 15 finished with value: 0.8379705293004892 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:51,981] Trial 16 finished with value: 0.8367617965408639 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,116] Trial 17 finished with value: 0.8275077217284676 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,252] Trial 18 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,394] Trial 19 finished with value: 0.824255318605644 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,533] Trial 20 finished with value: 0.8266729757776873 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.72}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,701] Trial 21 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,832] Trial 22 finished with value: 0.8275824351240454 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:52,967] Trial 23 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,093] Trial 24 finished with value: 0.8300303229065639 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,228] Trial 25 finished with value: 0.8379705293004892 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,359] Trial 26 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6699999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,489] Trial 27 finished with value: 0.8266729757776873 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.72}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,616] Trial 28 finished with value: 0.8294604224699222 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,747] Trial 29 finished with value: 0.8310254840791576 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:53,878] Trial 30 finished with value: 0.8296148551267238 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,019] Trial 31 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,150] Trial 32 finished with value: 0.8364674346939464 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,276] Trial 33 finished with value: 0.8322985197047057 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.63}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,408] Trial 34 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,550] Trial 35 finished with value: 0.836698142857439 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,680] Trial 36 finished with value: 0.830076196662892 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,809] Trial 37 finished with value: 0.8322985197047057 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.62}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:54,944] Trial 38 finished with value: 0.8276453885881853 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:55,075] Trial 39 finished with value: 0.8182933007850759 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:55,211] Trial 40 finished with value: 0.8379705293004892 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 2 with value: 0.8432794192989314.
[I 2025-04-16 00:52:55,349] Trial 41 finished with value: 0.8457500554435455 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:55,482] Trial 42 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:55,611] Trial 43 finished with value: 0.830076196662892 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:55,747] Trial 44 finished with value: 0.8457500554435455 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:55,882] Trial 45 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,015] Trial 46 finished with value: 0.8186190419677715 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,148] Trial 47 finished with value: 0.8299448063141102 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,285] Trial 48 finished with value: 0.827626442961885 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,416] Trial 49 finished with value: 0.830076196662892 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,554] Trial 50 finished with value: 0.8231392797834417 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,683] Trial 51 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,815] Trial 52 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:56,947] Trial 53 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,085] Trial 54 finished with value: 0.824255318605644 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,216] Trial 55 finished with value: 0.8364674346939464 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,360] Trial 56 finished with value: 0.8333424804018349 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,494] Trial 57 finished with value: 0.8356273813052513 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.73}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,663] Trial 58 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,794] Trial 59 finished with value: 0.8378055647373438 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.61}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:57,927] Trial 60 finished with value: 0.8275824351240454 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,059] Trial 61 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,192] Trial 62 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,323] Trial 63 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,454] Trial 64 finished with value: 0.8350405335360696 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,596] Trial 65 finished with value: 0.8377661515886378 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,729] Trial 66 finished with value: 0.834808568998026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:58,872] Trial 67 finished with value: 0.8277411770095353 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,000] Trial 68 finished with value: 0.8149467255835907 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,132] Trial 69 finished with value: 0.8457500554435455 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,263] Trial 70 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,394] Trial 71 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,527] Trial 72 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,662] Trial 73 finished with value: 0.8266016203917054 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.72}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,795] Trial 74 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:52:59,926] Trial 75 finished with value: 0.8364674346939464 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,063] Trial 76 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,193] Trial 77 finished with value: 0.8411258819319919 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,332] Trial 78 finished with value: 0.8254865350997209 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,463] Trial 79 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,593] Trial 80 finished with value: 0.8303452921618677 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,728] Trial 81 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,864] Trial 82 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:00,994] Trial 83 finished with value: 0.8377661515886378 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,126] Trial 84 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,256] Trial 85 finished with value: 0.8347372136120443 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,389] Trial 86 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,520] Trial 87 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,654] Trial 88 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,784] Trial 89 finished with value: 0.8324328681933874 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:01,922] Trial 90 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,054] Trial 91 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,188] Trial 92 finished with value: 0.8377661515886378 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,324] Trial 93 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,456] Trial 94 finished with value: 0.8398819377118559 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,591] Trial 95 finished with value: 0.8423943929879414 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,723] Trial 96 finished with value: 0.8347372136120443 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:02,891] Trial 97 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:03,037] Trial 98 finished with value: 0.8333472935229546 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:03,163] Trial 99 finished with value: 0.822033544985681 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:03,294] Trial 100 finished with value: 0.830076196662892 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:03,426] Trial 101 finished with value: 0.8432794192989314 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 41 with value: 0.8457500554435455.
[I 2025-04-16 00:53:03,557] Trial 102 finished with value: 0.8344080831502685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 41 with value: 0.8457500554435455.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.72}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smotenc_optuna-opt-mean-s...
holdout_test_f1_macro                                                      0.843227
holdout_test_accuracy_balanced                                             0.877273
holdout_test_roc_auc                                                       0.952727
holdout_test_f1                                                            0.782609
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.961538
cv_test_f1_median                                                               0.8
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.906667

Model saved in ../results/models_modelling4/SVC_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# CatBoost

In [13]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:53:44,548] A new study created in memory with name: smote_study
[I 2025-04-16 00:53:49,297] Trial 0 finished with value: 0.8800298923107119 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8800298923107119.
[I 2025-04-16 00:53:53,786] Trial 1 finished with value: 0.8835594406678464 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8835594406678464.
[I 2025-04-16 00:53:58,011] Trial 2 finished with value: 0.8900278404468924 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:02,517] Trial 3 finished with value: 0.8755977547957539 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:06,972] Trial 4 finished with value: 0.8866947989672991 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:11,638] Trial 5 finished with value: 0.8754250699675528 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:16,023] Trial 6 finished with value: 0.8862297467781091 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:20,287] Trial 7 finished with value: 0.8894943751221386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 2 with value: 0.8900278404468924.
[I 2025-04-16 00:54:24,667] Trial 8 finished with value: 0.8901204639041203 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:28,917] Trial 9 finished with value: 0.8899525199185186 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:33,289] Trial 10 finished with value: 0.8861741423991966 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:37,496] Trial 11 finished with value: 0.8862291581655238 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:41,821] Trial 12 finished with value: 0.8901204639041203 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:46,165] Trial 13 finished with value: 0.8829479923267545 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8}. Best is trial 8 with value: 0.8901204639041203.
[I 2025-04-16 00:54:50,698] Trial 14 finished with value: 0.8975267778751981 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:54:55,165] Trial 15 finished with value: 0.8900899396777107 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:54:59,470] Trial 16 finished with value: 0.8933659647112737 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:03,901] Trial 17 finished with value: 0.8865909155469858 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:08,299] Trial 18 finished with value: 0.8901601194008781 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:12,606] Trial 19 finished with value: 0.8861896871493344 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:17,087] Trial 20 finished with value: 0.8791835081395784 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9299999999999999}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:21,546] Trial 21 finished with value: 0.8901204639041203 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:26,077] Trial 22 finished with value: 0.8901984469204585 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:30,495] Trial 23 finished with value: 0.8894780132856238 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:34,933] Trial 24 finished with value: 0.8943732558709623 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:39,458] Trial 25 finished with value: 0.8910666943530196 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:43,879] Trial 26 finished with value: 0.8903075955314143 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:48,354] Trial 27 finished with value: 0.886664672311183 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 14 with value: 0.8975267778751981.
[I 2025-04-16 00:55:52,675] Trial 28 finished with value: 0.9010123441671973 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:55:57,114] Trial 29 finished with value: 0.8830651311475416 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:01,500] Trial 30 finished with value: 0.8829479923267545 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:05,831] Trial 31 finished with value: 0.9010123441671973 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:10,226] Trial 32 finished with value: 0.8862291581655238 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:14,457] Trial 33 finished with value: 0.890232532357593 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:18,946] Trial 34 finished with value: 0.8862291581655238 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:23,461] Trial 35 finished with value: 0.8900899396777107 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:27,769] Trial 36 finished with value: 0.8835594406678464 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:32,135] Trial 37 finished with value: 0.8861735537866113 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.88}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:36,467] Trial 38 finished with value: 0.8939694228425344 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:40,835] Trial 39 finished with value: 0.8938371438885487 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:45,254] Trial 40 finished with value: 0.8910920900321928 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:49,497] Trial 41 finished with value: 0.8939694228425344 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:53,772] Trial 42 finished with value: 0.8938994300360276 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:56:58,083] Trial 43 finished with value: 0.8862297467781091 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.74}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:02,334] Trial 44 finished with value: 0.8932871614434633 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:06,645] Trial 45 finished with value: 0.886119071402055 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:10,815] Trial 46 finished with value: 0.8924301858666178 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:15,296] Trial 47 finished with value: 0.890232532357593 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:19,383] Trial 48 finished with value: 0.8895129061020475 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:23,547] Trial 49 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:27,788] Trial 50 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:32,028] Trial 51 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:36,320] Trial 52 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:40,493] Trial 53 finished with value: 0.8967991256534901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:44,727] Trial 54 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:48,949] Trial 55 finished with value: 0.8996246320752542 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:53,081] Trial 56 finished with value: 0.8895499795010512 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:57:57,312] Trial 57 finished with value: 0.8862688136622817 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:01,505] Trial 58 finished with value: 0.8928358536994662 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.65}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:05,811] Trial 59 finished with value: 0.8928697087051715 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:10,026] Trial 60 finished with value: 0.8897538491286385 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:14,305] Trial 61 finished with value: 0.8929078199148937 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:18,619] Trial 62 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:22,831] Trial 63 finished with value: 0.8929451202114628 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6599999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:27,089] Trial 64 finished with value: 0.8928290166470834 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:31,598] Trial 65 finished with value: 0.8871686248022338 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:35,782] Trial 66 finished with value: 0.8895869985793664 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:40,104] Trial 67 finished with value: 0.8901204639041203 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:44,307] Trial 68 finished with value: 0.8899525199185186 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:48,624] Trial 69 finished with value: 0.8894780132856238 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:53,011] Trial 70 finished with value: 0.8938994300360276 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:58:57,291] Trial 71 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:59:01,597] Trial 72 finished with value: 0.8929078199148937 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:59:05,790] Trial 73 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:59:10,240] Trial 74 finished with value: 0.8895499795010512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:59:14,476] Trial 75 finished with value: 0.9001678684458742 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.72}. Best is trial 28 with value: 0.9010123441671973.
[I 2025-04-16 00:59:18,727] Trial 76 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:22,989] Trial 77 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:27,267] Trial 78 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:31,546] Trial 79 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:35,836] Trial 80 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:40,096] Trial 81 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:44,417] Trial 82 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:48,782] Trial 83 finished with value: 0.8897538491286385 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:52,966] Trial 84 finished with value: 0.8861896871493344 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 00:59:57,221] Trial 85 finished with value: 0.8965290535767431 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:01,517] Trial 86 finished with value: 0.8901204639041203 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:05,753] Trial 87 finished with value: 0.8938371438885487 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:09,998] Trial 88 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:14,293] Trial 89 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:18,728] Trial 90 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:23,062] Trial 91 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:27,437] Trial 92 finished with value: 0.8859648267650041 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:31,828] Trial 93 finished with value: 0.8894780132856238 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:36,044] Trial 94 finished with value: 0.8929451202114628 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.73}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:40,347] Trial 95 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:44,661] Trial 96 finished with value: 0.8965290535767431 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:48,977] Trial 97 finished with value: 0.9001678684458742 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.72}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:53,308] Trial 98 finished with value: 0.8897538491286385 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:00:57,604] Trial 99 finished with value: 0.8938371438885487 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:01:01,903] Trial 100 finished with value: 0.8926742781482914 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:01:06,206] Trial 101 finished with value: 0.8859648267650041 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:01:10,482] Trial 102 finished with value: 0.903687463550203 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 76 with value: 0.903687463550203.
[I 2025-04-16 01:01:14,922] Trial 103 finished with value: 0.8929451202114628 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.73}. Best is trial 76 with value: 0.903687463550203.

best_params

{'k_neighbors': 7, 'sampling_strategy': 0.75}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smotenc_optuna-op...
holdout_test_f1_macro                                                          0.85
holdout_test_accuracy_balanced                                              0.83912
holdout_test_roc_auc                                                       0.958333
holdout_test_f1                                                                 0.9
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.898584
cv_test_accuracy_balanced_median                                           0.903251
cv_test_roc_auc_median                                                      0.94582
cv_test_f1_median                                                          0.925373
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                               0.85
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.871795

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [14]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 01:22:16,385] A new study created in memory with name: smote_study
[I 2025-04-16 01:22:21,201] Trial 0 finished with value: 0.8481424870661538 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8481424870661538.
[I 2025-04-16 01:22:25,667] Trial 1 finished with value: 0.8500371673615249 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8500371673615249.
[I 2025-04-16 01:22:29,975] Trial 2 finished with value: 0.8504523830569923 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8504523830569923.
[I 2025-04-16 01:22:34,602] Trial 3 finished with value: 0.8522647763143156 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8522647763143156.
[I 2025-04-16 01:22:39,180] Trial 4 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8522647763143156.
[I 2025-04-16 01:22:43,790] Trial 5 finished with value: 0.8484886151175817 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.8522647763143156.
[I 2025-04-16 01:22:48,168] Trial 6 finished with value: 0.853701856327365 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:22:52,509] Trial 7 finished with value: 0.846916956319311 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:22:56,993] Trial 8 finished with value: 0.8503580732749975 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:23:01,336] Trial 9 finished with value: 0.837456431267316 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:23:05,593] Trial 10 finished with value: 0.8422676732118991 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:23:09,923] Trial 11 finished with value: 0.841529602259943 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 6 with value: 0.853701856327365.
[I 2025-04-16 01:23:14,540] Trial 12 finished with value: 0.8559197961366102 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:19,176] Trial 13 finished with value: 0.8559197961366102 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:23,774] Trial 14 finished with value: 0.8559197961366102 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:28,313] Trial 15 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:32,837] Trial 16 finished with value: 0.8350891332989525 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:37,459] Trial 17 finished with value: 0.8410685333277972 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:41,867] Trial 18 finished with value: 0.8507489476988879 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:46,370] Trial 19 finished with value: 0.83986967934559 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:50,901] Trial 20 finished with value: 0.8350891332989525 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:23:55,438] Trial 21 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:00,061] Trial 22 finished with value: 0.8467853725724631 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:04,729] Trial 23 finished with value: 0.8431398014655004 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:09,244] Trial 24 finished with value: 0.8469877949840424 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:13,731] Trial 25 finished with value: 0.8488016804981581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:18,442] Trial 26 finished with value: 0.8343281813698816 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:22,890] Trial 27 finished with value: 0.8455194680009609 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:27,425] Trial 28 finished with value: 0.8473481022554618 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:32,083] Trial 29 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:36,729] Trial 30 finished with value: 0.8488016804981581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 12 with value: 0.8559197961366102.
[I 2025-04-16 01:24:40,975] Trial 31 finished with value: 0.8576917220683828 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:24:45,182] Trial 32 finished with value: 0.8411211202331561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:24:49,755] Trial 33 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:24:54,291] Trial 34 finished with value: 0.841529602259943 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.83}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:24:58,833] Trial 35 finished with value: 0.8417803136651604 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:03,411] Trial 36 finished with value: 0.8385606097103325 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:07,857] Trial 37 finished with value: 0.8502395897731042 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:12,400] Trial 38 finished with value: 0.844667937228846 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:17,060] Trial 39 finished with value: 0.8467853725724631 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:21,313] Trial 40 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:25,621] Trial 41 finished with value: 0.853701856327365 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:29,934] Trial 42 finished with value: 0.8449567383179623 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.69}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:34,171] Trial 43 finished with value: 0.8481603583516565 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:38,510] Trial 44 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:42,770] Trial 45 finished with value: 0.8522810173114933 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:47,006] Trial 46 finished with value: 0.8444956693858164 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:51,326] Trial 47 finished with value: 0.837802757641068 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:25:55,989] Trial 48 finished with value: 0.8402422963339351 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:00,404] Trial 49 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.71}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:04,793] Trial 50 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:09,168] Trial 51 finished with value: 0.8467853725724631 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:13,419] Trial 52 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:17,640] Trial 53 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:22,029] Trial 54 finished with value: 0.8429979292430245 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6599999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:26,314] Trial 55 finished with value: 0.841529602259943 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:30,587] Trial 56 finished with value: 0.8444956693858164 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:35,130] Trial 57 finished with value: 0.8476469884160467 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:39,729] Trial 58 finished with value: 0.8343281813698816 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:44,161] Trial 59 finished with value: 0.8538122904756386 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:48,667] Trial 60 finished with value: 0.8484855351268343 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:52,996] Trial 61 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:26:57,307] Trial 62 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:01,682] Trial 63 finished with value: 0.8444956693858164 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:05,845] Trial 64 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:10,189] Trial 65 finished with value: 0.8343281813698816 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6699999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:14,663] Trial 66 finished with value: 0.8488016804981581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:19,328] Trial 67 finished with value: 0.8419877457683518 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:23,895] Trial 68 finished with value: 0.8536094687160845 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:28,119] Trial 69 finished with value: 0.8411211202331561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:32,721] Trial 70 finished with value: 0.8500371673615249 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:36,973] Trial 71 finished with value: 0.8522810173114933 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:41,228] Trial 72 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:45,481] Trial 73 finished with value: 0.841529602259943 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:49,824] Trial 74 finished with value: 0.8467853725724631 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:54,052] Trial 75 finished with value: 0.8419903598461043 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:27:58,639] Trial 76 finished with value: 0.8488016804981581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:02,986] Trial 77 finished with value: 0.854439927279321 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:07,538] Trial 78 finished with value: 0.8469877949840424 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:11,713] Trial 79 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:16,032] Trial 80 finished with value: 0.8419903598461043 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:20,393] Trial 81 finished with value: 0.8444956693858164 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:24,747] Trial 82 finished with value: 0.841529602259943 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:29,030] Trial 83 finished with value: 0.8538771975963224 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:33,388] Trial 84 finished with value: 0.8430799293080938 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:38,006] Trial 85 finished with value: 0.8542498145846673 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:42,348] Trial 86 finished with value: 0.8467853725724631 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:46,641] Trial 87 finished with value: 0.8540270331025427 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:50,983] Trial 88 finished with value: 0.8451795198000868 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:28:55,599] Trial 89 finished with value: 0.8453745444401388 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:00,230] Trial 90 finished with value: 0.83986967934559 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:04,489] Trial 91 finished with value: 0.8576917220683828 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:08,767] Trial 92 finished with value: 0.8411211202331561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:13,135] Trial 93 finished with value: 0.8457701794061782 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6599999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:17,465] Trial 94 finished with value: 0.8466100313035057 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.61}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:21,731] Trial 95 finished with value: 0.8508226785266483 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:26,061] Trial 96 finished with value: 0.8481603583516565 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:30,412] Trial 97 finished with value: 0.8412438745967545 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:34,577] Trial 98 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:38,925] Trial 99 finished with value: 0.8379008820724161 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:43,183] Trial 100 finished with value: 0.8444956693858164 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:47,467] Trial 101 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.
[I 2025-04-16 01:29:51,877] Trial 102 finished with value: 0.857664640925761 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 31 with value: 0.8576917220683828.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.61}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.916089
holdout_test_accuracy_balanced                                             0.922727
holdout_test_roc_auc                                                       0.987273
holdout_test_f1                                                            0.878049
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                     0.90293
cv_test_accuracy_balanced_median                                           0.892857
cv_test_roc_auc_median                                                     0.974359
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                      0.95

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# XGBoost

In [15]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 01:51:53,440] A new study created in memory with name: smote_study
[I 2025-04-16 01:51:55,180] Trial 0 finished with value: 0.8784203918741195 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8784203918741195.
[I 2025-04-16 01:51:56,987] Trial 1 finished with value: 0.8779950228452413 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8784203918741195.
[I 2025-04-16 01:51:58,709] Trial 2 finished with value: 0.8554353174694594 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8784203918741195.
[I 2025-04-16 01:52:00,423] Trial 3 finished with value: 0.8885832532610579 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:02,162] Trial 4 finished with value: 0.877905444109132 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:03,906] Trial 5 finished with value: 0.8740319013260002 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:05,575] Trial 6 finished with value: 0.8745731806656044 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:07,310] Trial 7 finished with value: 0.8847689976330214 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:09,058] Trial 8 finished with value: 0.8716010718015748 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:10,735] Trial 9 finished with value: 0.8786122696483522 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:12,529] Trial 10 finished with value: 0.8659203030193507 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:14,251] Trial 11 finished with value: 0.8773705099353463 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:15,978] Trial 12 finished with value: 0.8708638121192639 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:17,688] Trial 13 finished with value: 0.8752265163134233 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:19,553] Trial 14 finished with value: 0.8775767384359098 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:21,284] Trial 15 finished with value: 0.8796468535647094 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:23,023] Trial 16 finished with value: 0.8661873528956298 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:24,721] Trial 17 finished with value: 0.8639198682582423 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:26,472] Trial 18 finished with value: 0.8763906958705567 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:28,208] Trial 19 finished with value: 0.8863100282389678 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:29,931] Trial 20 finished with value: 0.8885832532610579 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:31,655] Trial 21 finished with value: 0.8885832532610579 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:33,360] Trial 22 finished with value: 0.8885832532610579 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:35,087] Trial 23 finished with value: 0.8827825994425407 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:36,821] Trial 24 finished with value: 0.8711311719845592 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:38,550] Trial 25 finished with value: 0.8775244793610942 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:40,270] Trial 26 finished with value: 0.8714502636820617 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 3 with value: 0.8885832532610579.
[I 2025-04-16 01:52:42,030] Trial 27 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:43,749] Trial 28 finished with value: 0.8824488173783844 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:45,461] Trial 29 finished with value: 0.880018260277019 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.82}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:47,157] Trial 30 finished with value: 0.882622071125765 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.97}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:48,909] Trial 31 finished with value: 0.8894849856251262 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:50,566] Trial 32 finished with value: 0.8854193793548116 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:52,298] Trial 33 finished with value: 0.8762445872139478 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 27 with value: 0.8895145720531173.
[I 2025-04-16 01:52:54,036] Trial 34 finished with value: 0.8936701866805251 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:52:55,754] Trial 35 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:52:57,500] Trial 36 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:52:59,192] Trial 37 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:00,891] Trial 38 finished with value: 0.8729741787533006 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:02,689] Trial 39 finished with value: 0.8749206685123482 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:04,421] Trial 40 finished with value: 0.875563949242041 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:06,146] Trial 41 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:07,865] Trial 42 finished with value: 0.8790908494306094 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:09,595] Trial 43 finished with value: 0.8886860063990556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:11,297] Trial 44 finished with value: 0.8932834961247778 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:13,065] Trial 45 finished with value: 0.8855646636652141 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8899999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:14,784] Trial 46 finished with value: 0.877905444109132 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:16,469] Trial 47 finished with value: 0.8708098182281087 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:18,227] Trial 48 finished with value: 0.8762445872139478 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:20,117] Trial 49 finished with value: 0.8854193793548116 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:21,840] Trial 50 finished with value: 0.8765574435452599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:23,582] Trial 51 finished with value: 0.8723244516886337 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:25,403] Trial 52 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:27,072] Trial 53 finished with value: 0.8863016251164615 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:28,839] Trial 54 finished with value: 0.8816792434591328 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:30,583] Trial 55 finished with value: 0.8789013067247637 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:32,339] Trial 56 finished with value: 0.8626504692118883 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:34,088] Trial 57 finished with value: 0.8757640061124309 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:35,809] Trial 58 finished with value: 0.8633733699305458 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:37,492] Trial 59 finished with value: 0.8779426719914983 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.73}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:39,329] Trial 60 finished with value: 0.8824441794841349 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:41,249] Trial 61 finished with value: 0.8895145720531173 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:43,119] Trial 62 finished with value: 0.8853104673194959 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:45,064] Trial 63 finished with value: 0.8749553201456994 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:46,832] Trial 64 finished with value: 0.8777062886886127 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 34 with value: 0.8936701866805251.
[I 2025-04-16 01:53:48,572] Trial 65 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:50,374] Trial 66 finished with value: 0.8829732616940731 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:52,131] Trial 67 finished with value: 0.877865921076985 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:53,898] Trial 68 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:55,623] Trial 69 finished with value: 0.8728584504534267 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:57,342] Trial 70 finished with value: 0.8664436354929848 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:53:59,088] Trial 71 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:00,899] Trial 72 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:02,604] Trial 73 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:04,351] Trial 74 finished with value: 0.8790284887231425 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:06,089] Trial 75 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:07,781] Trial 76 finished with value: 0.8554167104380603 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:09,539] Trial 77 finished with value: 0.8789013067247637 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:11,285] Trial 78 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:13,087] Trial 79 finished with value: 0.8720356482793271 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:14,807] Trial 80 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:16,517] Trial 81 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:18,225] Trial 82 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:20,146] Trial 83 finished with value: 0.8900883012629072 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:21,840] Trial 84 finished with value: 0.8789013067247637 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:23,562] Trial 85 finished with value: 0.8762445872139478 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:25,264] Trial 86 finished with value: 0.8554167104380603 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:27,001] Trial 87 finished with value: 0.8884023948354498 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:28,747] Trial 88 finished with value: 0.8749206685123482 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:30,478] Trial 89 finished with value: 0.8728584504534267 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:32,225] Trial 90 finished with value: 0.885764810789242 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:33,961] Trial 91 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:35,708] Trial 92 finished with value: 0.8884023948354498 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:37,430] Trial 93 finished with value: 0.8774207094621467 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:39,198] Trial 94 finished with value: 0.8762445872139478 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:40,927] Trial 95 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:42,654] Trial 96 finished with value: 0.8829381993859071 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:44,369] Trial 97 finished with value: 0.8728584504534267 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:46,116] Trial 98 finished with value: 0.8884023948354498 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:47,961] Trial 99 finished with value: 0.8779950228452413 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:49,913] Trial 100 finished with value: 0.8749206685123482 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:51,610] Trial 101 finished with value: 0.8728584504534267 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 65 with value: 0.8978784711108675.
[I 2025-04-16 01:54:53,291] Trial 102 finished with value: 0.8978784711108675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 65 with value: 0.8978784711108675.

best_params

{'k_neighbors': 7, 'sampling_strategy': 0.83}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smotenc_optuna-opt-mea...
holdout_test_f1_macro                                                          0.88
holdout_test_accuracy_balanced                                             0.868056
holdout_test_roc_auc                                                       0.939429
holdout_test_f1                                                                0.92
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.831746
cv_test_accuracy_balanced_median                                           0.844444
cv_test_roc_auc_median                                                     0.950464
cv_test_f1_median                                                          0.885714
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.823529
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.780488

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [16]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:03:21,035] A new study created in memory with name: smote_study
[I 2025-04-16 02:03:22,650] Trial 0 finished with value: 0.847831651690411 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.847831651690411.
[I 2025-04-16 02:03:24,217] Trial 1 finished with value: 0.8286555540633209 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.847831651690411.
[I 2025-04-16 02:03:25,738] Trial 2 finished with value: 0.8403178155590403 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.847831651690411.
[I 2025-04-16 02:03:27,314] Trial 3 finished with value: 0.834343507224908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.847831651690411.
[I 2025-04-16 02:03:28,882] Trial 4 finished with value: 0.832581533017551 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.847831651690411.
[I 2025-04-16 02:03:30,382] Trial 5 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:31,947] Trial 6 finished with value: 0.8265889576373447 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:33,444] Trial 7 finished with value: 0.8336069722907835 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:35,020] Trial 8 finished with value: 0.8252873213820494 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:36,617] Trial 9 finished with value: 0.8304962952473801 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:38,133] Trial 10 finished with value: 0.8226515469536195 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:39,712] Trial 11 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:41,261] Trial 12 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:42,849] Trial 13 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:44,424] Trial 14 finished with value: 0.8263325445541805 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:45,957] Trial 15 finished with value: 0.8336833998140205 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:47,550] Trial 16 finished with value: 0.8257095347665421 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:49,130] Trial 17 finished with value: 0.8457262162202576 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.85}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:50,622] Trial 18 finished with value: 0.8401522687657812 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:52,201] Trial 19 finished with value: 0.8276250625670682 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:53,730] Trial 20 finished with value: 0.8427200221674408 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:55,292] Trial 21 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:56,849] Trial 22 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:58,391] Trial 23 finished with value: 0.82122321156176 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:03:59,945] Trial 24 finished with value: 0.8380184494953749 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:01,470] Trial 25 finished with value: 0.83597429096245 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:03,044] Trial 26 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:04,569] Trial 27 finished with value: 0.8309459886047744 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:06,163] Trial 28 finished with value: 0.8328558851059881 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:07,724] Trial 29 finished with value: 0.8267862199626003 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:09,269] Trial 30 finished with value: 0.8343352114294575 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:10,869] Trial 31 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:12,420] Trial 32 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:13,983] Trial 33 finished with value: 0.8377075375376791 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:15,531] Trial 34 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:17,078] Trial 35 finished with value: 0.828637462335151 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:18,627] Trial 36 finished with value: 0.8367795734731219 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:20,356] Trial 37 finished with value: 0.8336833998140205 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:21,908] Trial 38 finished with value: 0.8457262162202576 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.85}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:23,477] Trial 39 finished with value: 0.8291264611903895 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:25,035] Trial 40 finished with value: 0.8297763120606908 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:26,566] Trial 41 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:28,148] Trial 42 finished with value: 0.8302611295669667 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:29,696] Trial 43 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:31,257] Trial 44 finished with value: 0.822066272306522 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:32,831] Trial 45 finished with value: 0.834343507224908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:34,389] Trial 46 finished with value: 0.8350976612664943 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:35,988] Trial 47 finished with value: 0.8270585691126271 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:37,530] Trial 48 finished with value: 0.815596090145165 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:39,090] Trial 49 finished with value: 0.8297763120606908 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:40,612] Trial 50 finished with value: 0.8304962952473801 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:42,173] Trial 51 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:43,717] Trial 52 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:45,270] Trial 53 finished with value: 0.8367795734731219 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:46,901] Trial 54 finished with value: 0.8310923101061453 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:48,545] Trial 55 finished with value: 0.8426502445482473 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:50,123] Trial 56 finished with value: 0.8220625719356722 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:51,677] Trial 57 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:53,228] Trial 58 finished with value: 0.8210105299633252 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:54,754] Trial 59 finished with value: 0.8416801656319545 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:56,366] Trial 60 finished with value: 0.834343507224908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:57,874] Trial 61 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:04:59,428] Trial 62 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:00,987] Trial 63 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:02,551] Trial 64 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:04,153] Trial 65 finished with value: 0.8148071266077811 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:05,687] Trial 66 finished with value: 0.8302611295669667 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:07,288] Trial 67 finished with value: 0.8275887069726932 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:08,815] Trial 68 finished with value: 0.8276250625670682 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:10,334] Trial 69 finished with value: 0.834343507224908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:11,900] Trial 70 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:13,409] Trial 71 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:14,993] Trial 72 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:16,539] Trial 73 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:18,066] Trial 74 finished with value: 0.8401723528213125 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.83}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:19,805] Trial 75 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:21,422] Trial 76 finished with value: 0.8276250625670682 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:22,964] Trial 77 finished with value: 0.8148071266077811 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:24,593] Trial 78 finished with value: 0.8367795734731219 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:26,149] Trial 79 finished with value: 0.8390557697093554 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:27,650] Trial 80 finished with value: 0.8380184494953749 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:29,201] Trial 81 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:30,754] Trial 82 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:32,339] Trial 83 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:33,928] Trial 84 finished with value: 0.8297763120606908 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:35,470] Trial 85 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:37,023] Trial 86 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:38,545] Trial 87 finished with value: 0.8276250625670682 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:40,129] Trial 88 finished with value: 0.8315541152810908 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:41,646] Trial 89 finished with value: 0.8367795734731219 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:43,308] Trial 90 finished with value: 0.8054513168614755 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:44,927] Trial 91 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:46,458] Trial 92 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:48,007] Trial 93 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:49,565] Trial 94 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:51,090] Trial 95 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:52,646] Trial 96 finished with value: 0.8254897079936915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:54,183] Trial 97 finished with value: 0.837710778660522 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:55,819] Trial 98 finished with value: 0.8426502445482473 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:57,401] Trial 99 finished with value: 0.8310923101061453 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:05:58,961] Trial 100 finished with value: 0.8302611295669667 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:06:00,582] Trial 101 finished with value: 0.8524053964334841 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:06:02,115] Trial 102 finished with value: 0.849697686901382 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8524053964334841.
[I 2025-04-16 02:06:03,665] Trial 103 finished with value: 0.8379145818288327 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 5 with value: 0.8524053964334841.

best_params

{'k_neighbors': 3, 'sampling_strategy': 0.99}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smotenc_optuna-...
holdout_test_f1_macro                                                      0.882524
holdout_test_accuracy_balanced                                             0.888636
holdout_test_roc_auc                                                       0.977273
holdout_test_f1                                                            0.829268
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.968864
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.944444
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# AdaBoost

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:13:50,556] A new study created in memory with name: smote_study
[I 2025-04-16 02:13:50,854] Trial 0 finished with value: 0.8465841046344754 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8465841046344754.
[I 2025-04-16 02:13:51,146] Trial 1 finished with value: 0.8522359242923272 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:51,429] Trial 2 finished with value: 0.8507884917610742 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:51,716] Trial 3 finished with value: 0.8275714960645149 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:52,004] Trial 4 finished with value: 0.8442622531338235 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:52,294] Trial 5 finished with value: 0.8495113296746812 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:52,574] Trial 6 finished with value: 0.8149187452758883 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:52,853] Trial 7 finished with value: 0.834339008231306 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:53,136] Trial 8 finished with value: 0.830994791649556 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:53,426] Trial 9 finished with value: 0.8367626057441367 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:53,713] Trial 10 finished with value: 0.83720568383085 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:53,995] Trial 11 finished with value: 0.8462644706190271 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8522359242923272.
[I 2025-04-16 02:13:54,285] Trial 12 finished with value: 0.8539077512299327 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 12 with value: 0.8539077512299327.
[I 2025-04-16 02:13:54,577] Trial 13 finished with value: 0.835261706626743 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 12 with value: 0.8539077512299327.
[I 2025-04-16 02:13:54,865] Trial 14 finished with value: 0.8348901580087122 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8539077512299327.
[I 2025-04-16 02:13:55,155] Trial 15 finished with value: 0.8169158259657137 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8539077512299327.
[I 2025-04-16 02:13:55,444] Trial 16 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 16 with value: 0.8651214017222523.
[I 2025-04-16 02:13:55,733] Trial 17 finished with value: 0.8241434715466249 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.76}. Best is trial 16 with value: 0.8651214017222523.
[I 2025-04-16 02:13:56,026] Trial 18 finished with value: 0.8541636029237237 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 16 with value: 0.8651214017222523.
[I 2025-04-16 02:13:56,324] Trial 19 finished with value: 0.8824950436596544 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:56,618] Trial 20 finished with value: 0.8602529013824622 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:56,912] Trial 21 finished with value: 0.829712969181951 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:57,201] Trial 22 finished with value: 0.8545589032638171 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:57,501] Trial 23 finished with value: 0.8602529013824622 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:57,798] Trial 24 finished with value: 0.8458423767805332 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:58,089] Trial 25 finished with value: 0.8490350761603477 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.88}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:58,382] Trial 26 finished with value: 0.8411853277586631 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:58,681] Trial 27 finished with value: 0.8400281653582702 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:58,973] Trial 28 finished with value: 0.8541636029237237 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:59,266] Trial 29 finished with value: 0.822126655136431 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:59,564] Trial 30 finished with value: 0.8455393712692321 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:13:59,858] Trial 31 finished with value: 0.8602529013824622 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:00,149] Trial 32 finished with value: 0.8609773364720495 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:00,441] Trial 33 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:00,734] Trial 34 finished with value: 0.8526562314937886 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:01,021] Trial 35 finished with value: 0.8463992852917579 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:01,312] Trial 36 finished with value: 0.854310203362492 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:01,613] Trial 37 finished with value: 0.8490722984740737 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:01,901] Trial 38 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:02,191] Trial 39 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:02,490] Trial 40 finished with value: 0.8617248285224005 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.73}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:02,804] Trial 41 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:03,115] Trial 42 finished with value: 0.8319074503713015 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:03,414] Trial 43 finished with value: 0.8439311543315994 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:03,706] Trial 44 finished with value: 0.8595607533310733 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.71}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:04,000] Trial 45 finished with value: 0.8331762582052351 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:04,321] Trial 46 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:04,614] Trial 47 finished with value: 0.8417767771304102 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:04,903] Trial 48 finished with value: 0.8607118049351749 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:05,194] Trial 49 finished with value: 0.8450603425556797 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:05,487] Trial 50 finished with value: 0.8463992852917579 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:05,783] Trial 51 finished with value: 0.8336999630326739 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:06,085] Trial 52 finished with value: 0.8373896099047684 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:06,393] Trial 53 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:06,736] Trial 54 finished with value: 0.8301238140743852 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.73}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:07,035] Trial 55 finished with value: 0.83720568383085 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:07,335] Trial 56 finished with value: 0.840452098303266 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:07,636] Trial 57 finished with value: 0.8460644229014486 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:07,936] Trial 58 finished with value: 0.8319074503713015 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:08,236] Trial 59 finished with value: 0.8438507239107788 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:08,537] Trial 60 finished with value: 0.835261706626743 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:08,844] Trial 61 finished with value: 0.8526562314937886 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:09,187] Trial 62 finished with value: 0.8453943041362402 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:09,484] Trial 63 finished with value: 0.8406073318619643 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:09,774] Trial 64 finished with value: 0.8195377725612728 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.75}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:10,070] Trial 65 finished with value: 0.8524922353721383 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:10,362] Trial 66 finished with value: 0.8310887157396178 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:10,655] Trial 67 finished with value: 0.8229972443678483 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:10,945] Trial 68 finished with value: 0.8336999630326739 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:11,232] Trial 69 finished with value: 0.8319074503713015 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:11,520] Trial 70 finished with value: 0.8188998823751108 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.69}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:11,816] Trial 71 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:12,105] Trial 72 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:12,395] Trial 73 finished with value: 0.850450219369934 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:12,682] Trial 74 finished with value: 0.8454372048083431 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.76}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:12,969] Trial 75 finished with value: 0.8420113712387575 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:13,260] Trial 76 finished with value: 0.8432711426714198 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:13,551] Trial 77 finished with value: 0.8425866631165684 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:13,844] Trial 78 finished with value: 0.8463444114418271 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:14,132] Trial 79 finished with value: 0.8193255515731048 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:14,423] Trial 80 finished with value: 0.8483130937604163 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:14,713] Trial 81 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:15,000] Trial 82 finished with value: 0.8677471813484617 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:15,287] Trial 83 finished with value: 0.8315957678294205 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:15,577] Trial 84 finished with value: 0.8417767771304102 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:15,864] Trial 85 finished with value: 0.8348901580087122 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:16,153] Trial 86 finished with value: 0.8493426793770418 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:16,446] Trial 87 finished with value: 0.836677913261777 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:16,735] Trial 88 finished with value: 0.8300275279896993 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:17,024] Trial 89 finished with value: 0.850450219369934 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:17,311] Trial 90 finished with value: 0.8454372048083431 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.76}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:17,604] Trial 91 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:17,895] Trial 92 finished with value: 0.835261706626743 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:18,183] Trial 93 finished with value: 0.8319074503713015 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:18,472] Trial 94 finished with value: 0.8336999630326739 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:18,762] Trial 95 finished with value: 0.8443206158979216 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:19,058] Trial 96 finished with value: 0.853972664684594 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:19,348] Trial 97 finished with value: 0.8310887157396178 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:19,639] Trial 98 finished with value: 0.8315957678294205 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:19,956] Trial 99 finished with value: 0.8400281653582702 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:20,257] Trial 100 finished with value: 0.8453943041362402 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:20,548] Trial 101 finished with value: 0.8651214017222523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:20,866] Trial 102 finished with value: 0.8526562314937886 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 19 with value: 0.8824950436596544.
[I 2025-04-16 02:14:21,161] Trial 103 finished with value: 0.8425866631165684 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 19 with value: 0.8824950436596544.

best_params

{'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smotenc_optuna-op...
holdout_test_f1_macro                                                      0.781171
holdout_test_accuracy_balanced                                             0.778935
holdout_test_roc_auc                                                       0.853009
holdout_test_f1                                                            0.845361
holdout_test_accuracy                                                           0.8
cv_test_f1_macro_median                                                    0.781238
cv_test_accuracy_balanced_median                                            0.80031
cv_test_roc_auc_median                                                     0.890476
cv_test_f1_median                                                          0.835821
cv_test_accuracy_median                                                    0.792453
cv_test_precision_class_0_median                                           0.684211
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                   0.73913

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:15:48,522] A new study created in memory with name: smote_study
[I 2025-04-16 02:15:48,820] Trial 0 finished with value: 0.8100472350174143 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8100472350174143.
[I 2025-04-16 02:15:49,104] Trial 1 finished with value: 0.8327141252068964 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:49,382] Trial 2 finished with value: 0.8221280786372585 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:49,668] Trial 3 finished with value: 0.8084962750878398 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:50,006] Trial 4 finished with value: 0.8299048683403927 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:50,293] Trial 5 finished with value: 0.8044046015926742 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:50,571] Trial 6 finished with value: 0.8182346178478511 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:50,847] Trial 7 finished with value: 0.8246675874864303 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:51,128] Trial 8 finished with value: 0.8133564598382481 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:51,406] Trial 9 finished with value: 0.8304811412143512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:51,690] Trial 10 finished with value: 0.8021409533472753 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:51,973] Trial 11 finished with value: 0.8105781683665841 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:52,269] Trial 12 finished with value: 0.8226522786854052 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:52,562] Trial 13 finished with value: 0.8082407954260331 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:52,846] Trial 14 finished with value: 0.8233525943958598 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:53,135] Trial 15 finished with value: 0.7981816561816922 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:53,420] Trial 16 finished with value: 0.8105000703191515 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:53,709] Trial 17 finished with value: 0.8193319040324146 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:53,997] Trial 18 finished with value: 0.8229457370024216 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:54,281] Trial 19 finished with value: 0.8133972644596712 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:54,563] Trial 20 finished with value: 0.8029249416083105 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.73}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:54,851] Trial 21 finished with value: 0.817091576511645 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:55,140] Trial 22 finished with value: 0.8154958181660119 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:55,436] Trial 23 finished with value: 0.821661306990156 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:55,718] Trial 24 finished with value: 0.8152793699185735 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:56,004] Trial 25 finished with value: 0.8056565102860154 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:56,294] Trial 26 finished with value: 0.813384161517681 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:56,582] Trial 27 finished with value: 0.8080601063630671 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:56,866] Trial 28 finished with value: 0.8153635695950933 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.76}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:57,147] Trial 29 finished with value: 0.8293138975339992 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:57,429] Trial 30 finished with value: 0.8172831644240349 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 1 with value: 0.8327141252068964.
[I 2025-04-16 02:15:57,710] Trial 31 finished with value: 0.8336112508944098 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:57,989] Trial 32 finished with value: 0.830340891742629 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:58,267] Trial 33 finished with value: 0.8245281126041981 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:58,554] Trial 34 finished with value: 0.8207793703679229 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:58,831] Trial 35 finished with value: 0.811079888561388 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:59,113] Trial 36 finished with value: 0.8153988941303868 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:59,393] Trial 37 finished with value: 0.8245184060123252 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:59,672] Trial 38 finished with value: 0.810792324476129 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.62}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:15:59,953] Trial 39 finished with value: 0.8246675874864303 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:16:00,239] Trial 40 finished with value: 0.8304811412143512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:16:00,523] Trial 41 finished with value: 0.8304811412143512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:16:00,805] Trial 42 finished with value: 0.8249096867691706 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 31 with value: 0.8336112508944098.
[I 2025-04-16 02:16:01,088] Trial 43 finished with value: 0.8361608305285156 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:01,372] Trial 44 finished with value: 0.8361608305285156 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:01,656] Trial 45 finished with value: 0.8082982476042646 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:01,940] Trial 46 finished with value: 0.8059850939644738 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:02,225] Trial 47 finished with value: 0.8223729843013581 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:02,508] Trial 48 finished with value: 0.8105781683665841 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:02,804] Trial 49 finished with value: 0.8105000703191515 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:03,089] Trial 50 finished with value: 0.8206375227866486 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:03,372] Trial 51 finished with value: 0.8290967320473003 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:03,655] Trial 52 finished with value: 0.8030902110699759 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:03,938] Trial 53 finished with value: 0.8157090731783013 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.72}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:04,224] Trial 54 finished with value: 0.8120391059929075 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:04,508] Trial 55 finished with value: 0.8092452228556051 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:04,795] Trial 56 finished with value: 0.8163134095562812 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:05,075] Trial 57 finished with value: 0.8050735547248122 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:05,361] Trial 58 finished with value: 0.8077120436258688 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:05,645] Trial 59 finished with value: 0.817270129214838 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.72}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:05,937] Trial 60 finished with value: 0.8223729843013581 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:06,229] Trial 61 finished with value: 0.8304811412143512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:06,510] Trial 62 finished with value: 0.8141095901162715 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:06,796] Trial 63 finished with value: 0.8082982476042646 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:07,080] Trial 64 finished with value: 0.8216849647453871 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.72}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:07,374] Trial 65 finished with value: 0.8082407954260331 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:07,659] Trial 66 finished with value: 0.8053751881134311 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:07,960] Trial 67 finished with value: 0.8295613217848806 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:08,243] Trial 68 finished with value: 0.8219790223042184 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:08,526] Trial 69 finished with value: 0.8207793703679229 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:08,814] Trial 70 finished with value: 0.8056565102860154 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:09,096] Trial 71 finished with value: 0.8304811412143512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:09,389] Trial 72 finished with value: 0.8191332720953801 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:09,675] Trial 73 finished with value: 0.8343934390343676 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 43 with value: 0.8361608305285156.
[I 2025-04-16 02:16:09,968] Trial 74 finished with value: 0.8444620558273187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:10,251] Trial 75 finished with value: 0.8444620558273187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:10,536] Trial 76 finished with value: 0.806982189227507 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:10,837] Trial 77 finished with value: 0.8268301902905584 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:11,135] Trial 78 finished with value: 0.8444620558273187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:11,422] Trial 79 finished with value: 0.8212159378049709 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:11,707] Trial 80 finished with value: 0.8119238492520948 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:11,998] Trial 81 finished with value: 0.8332346708225639 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:12,295] Trial 82 finished with value: 0.8249523620376926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:12,580] Trial 83 finished with value: 0.8192378148644756 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:12,865] Trial 84 finished with value: 0.8268301902905584 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:13,157] Trial 85 finished with value: 0.8212159378049709 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:13,445] Trial 86 finished with value: 0.785730494785259 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:13,730] Trial 87 finished with value: 0.8192378148644756 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:14,021] Trial 88 finished with value: 0.81906561374071 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:14,309] Trial 89 finished with value: 0.8325046661128227 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:14,594] Trial 90 finished with value: 0.8258695775799324 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:14,881] Trial 91 finished with value: 0.8107228598258026 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:15,175] Trial 92 finished with value: 0.8284124913425251 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:15,461] Trial 93 finished with value: 0.8239612202186005 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:15,748] Trial 94 finished with value: 0.8130881133670972 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:16,033] Trial 95 finished with value: 0.8120391059929075 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:16,318] Trial 96 finished with value: 0.8296307888556288 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:16,603] Trial 97 finished with value: 0.8133564598382481 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:16,889] Trial 98 finished with value: 0.8145044747958148 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:17,179] Trial 99 finished with value: 0.8444620558273187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:17,477] Trial 100 finished with value: 0.8119238492520948 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:17,807] Trial 101 finished with value: 0.8192378148644756 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:18,120] Trial 102 finished with value: 0.8096349984927242 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 74 with value: 0.8444620558273187.
[I 2025-04-16 02:16:18,409] Trial 103 finished with value: 0.8332346708225639 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 74 with value: 0.8444620558273187.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.77}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.942273
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.820946
cv_test_accuracy_balanced_median                                           0.851648
cv_test_roc_auc_median                                                     0.923077
cv_test_f1_median                                                              0.75
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.891892

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:17:44,399] A new study created in memory with name: smote_study
[I 2025-04-16 02:17:44,899] Trial 0 finished with value: 0.863786377358881 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.863786377358881.
[I 2025-04-16 02:17:45,381] Trial 1 finished with value: 0.8665822336614083 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8665822336614083.
[I 2025-04-16 02:17:45,853] Trial 2 finished with value: 0.865402513971099 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8665822336614083.
[I 2025-04-16 02:17:46,344] Trial 3 finished with value: 0.8727387197319347 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8727387197319347.
[I 2025-04-16 02:17:46,828] Trial 4 finished with value: 0.8677002312310957 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8727387197319347.
[I 2025-04-16 02:17:47,320] Trial 5 finished with value: 0.8702787633949537 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.8727387197319347.
[I 2025-04-16 02:17:47,792] Trial 6 finished with value: 0.8723029384456659 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.8727387197319347.
[I 2025-04-16 02:17:48,274] Trial 7 finished with value: 0.8701425210352234 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 3 with value: 0.8727387197319347.
[I 2025-04-16 02:17:48,756] Trial 8 finished with value: 0.8729793445841789 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 8 with value: 0.8729793445841789.
[I 2025-04-16 02:17:49,230] Trial 9 finished with value: 0.8694382199340717 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 8 with value: 0.8729793445841789.
[I 2025-04-16 02:17:49,711] Trial 10 finished with value: 0.8824065006949916 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:50,193] Trial 11 finished with value: 0.873377881491683 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.78}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:50,677] Trial 12 finished with value: 0.875869455125019 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:51,155] Trial 13 finished with value: 0.875869455125019 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:51,630] Trial 14 finished with value: 0.8635857078077757 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:52,115] Trial 15 finished with value: 0.8597534936542895 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:52,597] Trial 16 finished with value: 0.8824065006949916 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 10 with value: 0.8824065006949916.
[I 2025-04-16 02:17:53,081] Trial 17 finished with value: 0.8837339452002632 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 17 with value: 0.8837339452002632.
[I 2025-04-16 02:17:53,569] Trial 18 finished with value: 0.8898626877908822 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:54,058] Trial 19 finished with value: 0.8843618780837644 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:54,545] Trial 20 finished with value: 0.8825783591138487 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:55,033] Trial 21 finished with value: 0.864652982862205 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:55,521] Trial 22 finished with value: 0.8843618780837644 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:56,011] Trial 23 finished with value: 0.8628386927340129 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:56,494] Trial 24 finished with value: 0.877743575195372 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:56,992] Trial 25 finished with value: 0.8666513404662225 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:57,478] Trial 26 finished with value: 0.8778462044479214 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:57,972] Trial 27 finished with value: 0.8676128655194221 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:58,463] Trial 28 finished with value: 0.8684272158020405 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:58,963] Trial 29 finished with value: 0.8841163842106828 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:59,448] Trial 30 finished with value: 0.8815699085388903 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.82}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:17:59,942] Trial 31 finished with value: 0.8841163842106828 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:18:00,429] Trial 32 finished with value: 0.8843618780837644 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:18:00,922] Trial 33 finished with value: 0.8833122274167119 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:18:01,410] Trial 34 finished with value: 0.8843618780837644 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:18:01,930] Trial 35 finished with value: 0.8665822336614083 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 18 with value: 0.8898626877908822.
[I 2025-04-16 02:18:02,429] Trial 36 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:02,925] Trial 37 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:03,416] Trial 38 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:03,915] Trial 39 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:04,408] Trial 40 finished with value: 0.8677265799574269 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:04,902] Trial 41 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:05,402] Trial 42 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:05,892] Trial 43 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 36 with value: 0.8975377638967614.
[I 2025-04-16 02:18:06,385] Trial 44 finished with value: 0.8979194081455805 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:06,877] Trial 45 finished with value: 0.8804495888093892 and parameters: {'k_neighbors': 10, 'sampling_strategy': 1.0}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:07,371] Trial 46 finished with value: 0.8979194081455805 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:07,861] Trial 47 finished with value: 0.8968828654938411 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:08,356] Trial 48 finished with value: 0.8979194081455805 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:08,847] Trial 49 finished with value: 0.8968828654938411 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:09,342] Trial 50 finished with value: 0.8743414247225957 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:09,832] Trial 51 finished with value: 0.8904094836562636 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:10,326] Trial 52 finished with value: 0.886324550597652 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:10,818] Trial 53 finished with value: 0.8979194081455805 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:11,313] Trial 54 finished with value: 0.8747128532371347 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:11,788] Trial 55 finished with value: 0.8806919070951997 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:12,284] Trial 56 finished with value: 0.8834115926239287 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:12,771] Trial 57 finished with value: 0.8774776013076506 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:13,262] Trial 58 finished with value: 0.8898054925092305 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:13,747] Trial 59 finished with value: 0.87312956870793 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.71}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:14,236] Trial 60 finished with value: 0.8721057692069677 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:14,734] Trial 61 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:15,240] Trial 62 finished with value: 0.8677265799574269 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:15,738] Trial 63 finished with value: 0.8857444197294705 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:16,225] Trial 64 finished with value: 0.8837339452002632 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:16,715] Trial 65 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:17,207] Trial 66 finished with value: 0.8747128532371347 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:17,698] Trial 67 finished with value: 0.8912512444243609 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.99}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:18,188] Trial 68 finished with value: 0.8898626877908822 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:18,685] Trial 69 finished with value: 0.8904094836562636 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:19,173] Trial 70 finished with value: 0.8715514076945886 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:19,669] Trial 71 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:20,170] Trial 72 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:20,670] Trial 73 finished with value: 0.8744550087148296 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:21,200] Trial 74 finished with value: 0.8937509622335913 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:21,693] Trial 75 finished with value: 0.8968828654938411 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:22,177] Trial 76 finished with value: 0.8927184916457669 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:22,663] Trial 77 finished with value: 0.8692258692699345 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:23,158] Trial 78 finished with value: 0.8625530492050896 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:23,652] Trial 79 finished with value: 0.8834115926239287 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:24,147] Trial 80 finished with value: 0.8937509622335913 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:24,638] Trial 81 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:25,171] Trial 82 finished with value: 0.8677265799574269 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:25,663] Trial 83 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:26,154] Trial 84 finished with value: 0.8625530492050896 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:26,646] Trial 85 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:27,137] Trial 86 finished with value: 0.8891647822860553 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:27,638] Trial 87 finished with value: 0.8693124992627592 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.99}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:28,135] Trial 88 finished with value: 0.8979194081455805 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:28,624] Trial 89 finished with value: 0.8702343518726802 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:29,113] Trial 90 finished with value: 0.8653625310478225 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:29,604] Trial 91 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:30,098] Trial 92 finished with value: 0.886324550597652 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:30,590] Trial 93 finished with value: 0.8834115926239287 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:31,088] Trial 94 finished with value: 0.8791551617497788 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:31,581] Trial 95 finished with value: 0.8968828654938411 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:32,072] Trial 96 finished with value: 0.8677265799574269 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:32,560] Trial 97 finished with value: 0.8684272158020405 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:33,050] Trial 98 finished with value: 0.859358685063169 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:33,543] Trial 99 finished with value: 0.886324550597652 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:34,027] Trial 100 finished with value: 0.8764863582519619 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:34,519] Trial 101 finished with value: 0.8975377638967614 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 44 with value: 0.8979194081455805.
[I 2025-04-16 02:18:35,011] Trial 102 finished with value: 0.8904094836562636 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8979194081455805.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.98}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smotenc_optun...
holdout_test_f1_macro                                                      0.806892
holdout_test_accuracy_balanced                                             0.799769
holdout_test_roc_auc                                                       0.934028
holdout_test_f1                                                            0.868687
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.887302
cv_test_roc_auc_median                                                     0.940402
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                              0.875
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.842105

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:21:04,797] A new study created in memory with name: smote_study
[I 2025-04-16 02:21:05,310] Trial 0 finished with value: 0.8418425587679417 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:05,808] Trial 1 finished with value: 0.8243094663104128 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:06,297] Trial 2 finished with value: 0.8275366133875924 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:06,806] Trial 3 finished with value: 0.833939373764748 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:07,299] Trial 4 finished with value: 0.8385083288612777 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:07,798] Trial 5 finished with value: 0.8119302208362876 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:08,278] Trial 6 finished with value: 0.8230955879426496 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:08,757] Trial 7 finished with value: 0.831066479629323 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:09,255] Trial 8 finished with value: 0.8249230598770323 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:09,736] Trial 9 finished with value: 0.8183220480312471 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:10,235] Trial 10 finished with value: 0.8354484330967026 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:10,735] Trial 11 finished with value: 0.8385083288612777 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:11,239] Trial 12 finished with value: 0.8340575248896052 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:11,723] Trial 13 finished with value: 0.8372065722398678 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:12,204] Trial 14 finished with value: 0.8312817088736413 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:12,704] Trial 15 finished with value: 0.8314747632471816 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:13,238] Trial 16 finished with value: 0.8172135021700503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:13,756] Trial 17 finished with value: 0.8331945395431261 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:14,263] Trial 18 finished with value: 0.8178977851226917 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:14,790] Trial 19 finished with value: 0.8333412071991427 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 0 with value: 0.8418425587679417.
[I 2025-04-16 02:21:15,309] Trial 20 finished with value: 0.8425760677536319 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8425760677536319.
[I 2025-04-16 02:21:15,803] Trial 21 finished with value: 0.8425760677536319 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8425760677536319.
[I 2025-04-16 02:21:16,306] Trial 22 finished with value: 0.8425760677536319 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8425760677536319.
[I 2025-04-16 02:21:16,811] Trial 23 finished with value: 0.8456782527242259 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:17,306] Trial 24 finished with value: 0.8303798356370831 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.85}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:17,808] Trial 25 finished with value: 0.8456782527242259 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:18,308] Trial 26 finished with value: 0.833939373764748 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:18,802] Trial 27 finished with value: 0.829583819000959 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:19,294] Trial 28 finished with value: 0.8189956229638705 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:19,803] Trial 29 finished with value: 0.8372511843037486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.97}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:20,300] Trial 30 finished with value: 0.8183220480312471 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:20,812] Trial 31 finished with value: 0.8425760677536319 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:21,315] Trial 32 finished with value: 0.8425760677536319 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 23 with value: 0.8456782527242259.
[I 2025-04-16 02:21:21,819] Trial 33 finished with value: 0.8520981541063473 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:22,323] Trial 34 finished with value: 0.8246983559237897 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:22,843] Trial 35 finished with value: 0.8224832731798718 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:23,353] Trial 36 finished with value: 0.8206948383464869 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:23,850] Trial 37 finished with value: 0.8378156772910472 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:24,353] Trial 38 finished with value: 0.822131750914908 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8899999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:24,859] Trial 39 finished with value: 0.833939373764748 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:25,363] Trial 40 finished with value: 0.8431578835686866 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:25,858] Trial 41 finished with value: 0.8431578835686866 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:26,358] Trial 42 finished with value: 0.8411138794918462 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:26,858] Trial 43 finished with value: 0.8241749554062691 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:27,373] Trial 44 finished with value: 0.8258940514022818 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:27,876] Trial 45 finished with value: 0.8359073597978713 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:28,371] Trial 46 finished with value: 0.8472924806471929 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:28,858] Trial 47 finished with value: 0.8269897472160085 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:29,361] Trial 48 finished with value: 0.8378156772910472 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:29,856] Trial 49 finished with value: 0.8189536416739619 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:30,365] Trial 50 finished with value: 0.8365308453129193 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:30,870] Trial 51 finished with value: 0.8385524995886146 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:31,370] Trial 52 finished with value: 0.8172135021700503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:31,875] Trial 53 finished with value: 0.8431578835686866 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:32,378] Trial 54 finished with value: 0.8520981541063473 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:32,856] Trial 55 finished with value: 0.8334826708234707 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:33,369] Trial 56 finished with value: 0.8388493586117229 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:33,875] Trial 57 finished with value: 0.830171268512424 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:34,383] Trial 58 finished with value: 0.8340614349428268 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.99}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:34,901] Trial 59 finished with value: 0.8388493586117229 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:35,395] Trial 60 finished with value: 0.8434512352124608 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:35,886] Trial 61 finished with value: 0.8434512352124608 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:36,384] Trial 62 finished with value: 0.8434512352124608 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:36,879] Trial 63 finished with value: 0.8241363861101664 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:37,376] Trial 64 finished with value: 0.8275879654177393 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:37,870] Trial 65 finished with value: 0.8335724360875884 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:38,374] Trial 66 finished with value: 0.8266768801577563 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:38,867] Trial 67 finished with value: 0.8380296050483024 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:39,361] Trial 68 finished with value: 0.8176025465010982 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:39,857] Trial 69 finished with value: 0.833529731792318 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:40,362] Trial 70 finished with value: 0.8454215431303493 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:40,853] Trial 71 finished with value: 0.8370162612228901 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.76}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:41,347] Trial 72 finished with value: 0.8239663075993315 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:41,837] Trial 73 finished with value: 0.8372065722398678 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:42,329] Trial 74 finished with value: 0.8304100166395114 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.78}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:42,813] Trial 75 finished with value: 0.8280314396889076 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:43,346] Trial 76 finished with value: 0.829583819000959 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:43,845] Trial 77 finished with value: 0.8369728748804004 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:44,339] Trial 78 finished with value: 0.8348103005573834 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:44,831] Trial 79 finished with value: 0.8350247068889172 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:45,324] Trial 80 finished with value: 0.8317892405032327 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:45,811] Trial 81 finished with value: 0.8434512352124608 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:46,300] Trial 82 finished with value: 0.8296627154504941 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:46,818] Trial 83 finished with value: 0.8384627343244971 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:47,315] Trial 84 finished with value: 0.8183220480312471 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:47,821] Trial 85 finished with value: 0.8345854455332253 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.96}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:48,317] Trial 86 finished with value: 0.8223650188397286 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:48,806] Trial 87 finished with value: 0.8275879654177393 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:49,300] Trial 88 finished with value: 0.8074113710104376 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:49,800] Trial 89 finished with value: 0.8456782527242259 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:50,297] Trial 90 finished with value: 0.8258571424945068 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:50,806] Trial 91 finished with value: 0.8258940514022818 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:51,305] Trial 92 finished with value: 0.8278517366443735 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:51,812] Trial 93 finished with value: 0.8456782527242259 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:52,317] Trial 94 finished with value: 0.830171268512424 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:52,820] Trial 95 finished with value: 0.8340614349428268 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.99}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:53,325] Trial 96 finished with value: 0.8328839777923144 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:53,831] Trial 97 finished with value: 0.8258571424945068 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:54,343] Trial 98 finished with value: 0.8411138794918462 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:54,838] Trial 99 finished with value: 0.8472778218313101 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:55,335] Trial 100 finished with value: 0.830171268512424 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:55,845] Trial 101 finished with value: 0.8338572816759255 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 33 with value: 0.8520981541063473.
[I 2025-04-16 02:21:56,346] Trial 102 finished with value: 0.822131750914908 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8899999999999999}. Best is trial 33 with value: 0.8520981541063473.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.96}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.916089
holdout_test_accuracy_balanced                                             0.922727
holdout_test_roc_auc                                                       0.983636
holdout_test_f1                                                            0.878049
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.936709

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:24:26,593] A new study created in memory with name: smote_study
[I 2025-04-16 02:24:28,643] Trial 0 finished with value: 0.8781883373901153 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8781883373901153.
[I 2025-04-16 02:24:30,543] Trial 1 finished with value: 0.8612341097674941 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8781883373901153.
[I 2025-04-16 02:24:32,327] Trial 2 finished with value: 0.8753705038533592 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8781883373901153.
[I 2025-04-16 02:24:34,405] Trial 3 finished with value: 0.8808793523323549 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8808793523323549.
[I 2025-04-16 02:24:36,425] Trial 4 finished with value: 0.8714197607450326 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8808793523323549.
[I 2025-04-16 02:24:38,468] Trial 5 finished with value: 0.8846998757715624 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:40,327] Trial 6 finished with value: 0.8598552678902761 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:42,139] Trial 7 finished with value: 0.8755389236073318 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:44,069] Trial 8 finished with value: 0.8678703890908325 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:45,847] Trial 9 finished with value: 0.8579946768837752 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:47,834] Trial 10 finished with value: 0.86380127521037 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:49,845] Trial 11 finished with value: 0.8846998757715624 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:51,887] Trial 12 finished with value: 0.8740054391872772 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:53,998] Trial 13 finished with value: 0.8717339113529842 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 5 with value: 0.8846998757715624.
[I 2025-04-16 02:24:55,898] Trial 14 finished with value: 0.8904800388034416 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:24:57,704] Trial 15 finished with value: 0.8608550800221214 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:24:59,577] Trial 16 finished with value: 0.8753125256769011 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.76}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:01,398] Trial 17 finished with value: 0.8626604195320253 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:03,375] Trial 18 finished with value: 0.8740860679372019 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:05,292] Trial 19 finished with value: 0.8638789005031623 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:07,273] Trial 20 finished with value: 0.8754561836448788 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:09,377] Trial 21 finished with value: 0.8808793523323549 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:11,331] Trial 22 finished with value: 0.8678490454232699 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:13,367] Trial 23 finished with value: 0.856108017334731 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:15,320] Trial 24 finished with value: 0.8649499442399574 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:17,287] Trial 25 finished with value: 0.8694717050089266 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:19,083] Trial 26 finished with value: 0.8622556932457269 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:21,055] Trial 27 finished with value: 0.8670427547982484 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:22,863] Trial 28 finished with value: 0.8784973923122286 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:24,937] Trial 29 finished with value: 0.8765909560724167 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.97}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:26,845] Trial 30 finished with value: 0.8869373758185156 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:28,744] Trial 31 finished with value: 0.8794372953882454 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:30,683] Trial 32 finished with value: 0.8634678521678852 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 14 with value: 0.8904800388034416.
[I 2025-04-16 02:25:32,627] Trial 33 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:34,384] Trial 34 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:36,224] Trial 35 finished with value: 0.8717439104355941 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.76}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:38,188] Trial 36 finished with value: 0.8826051359295531 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:40,038] Trial 37 finished with value: 0.8642109878863903 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.71}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:41,822] Trial 38 finished with value: 0.866342712231034 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:43,819] Trial 39 finished with value: 0.884251202896864 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:45,738] Trial 40 finished with value: 0.8748347093303147 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8899999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:47,786] Trial 41 finished with value: 0.8765909560724167 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.97}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:49,695] Trial 42 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:51,614] Trial 43 finished with value: 0.8679015589957659 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:53,527] Trial 44 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:55,476] Trial 45 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:57,416] Trial 46 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:25:59,350] Trial 47 finished with value: 0.8762851790289675 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:01,318] Trial 48 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:03,328] Trial 49 finished with value: 0.8753514363382575 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:05,291] Trial 50 finished with value: 0.876058942243762 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:07,197] Trial 51 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:09,107] Trial 52 finished with value: 0.8719918934509671 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:10,960] Trial 53 finished with value: 0.8675459368056665 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:12,849] Trial 54 finished with value: 0.8738750106549001 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:14,666] Trial 55 finished with value: 0.8608550800221214 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:16,614] Trial 56 finished with value: 0.884251202896864 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:18,431] Trial 57 finished with value: 0.8781462725619672 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:20,326] Trial 58 finished with value: 0.8591954431397509 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:22,187] Trial 59 finished with value: 0.8686515348363547 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:24,154] Trial 60 finished with value: 0.8822659116103112 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:26,123] Trial 61 finished with value: 0.8869373758185156 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:28,059] Trial 62 finished with value: 0.8649189206287938 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:29,913] Trial 63 finished with value: 0.868374252206131 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:31,872] Trial 64 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:33,802] Trial 65 finished with value: 0.8754561836448788 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:35,659] Trial 66 finished with value: 0.8672084337783154 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:37,547] Trial 67 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:39,520] Trial 68 finished with value: 0.8720929400331634 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:41,420] Trial 69 finished with value: 0.8778384118456783 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:43,334] Trial 70 finished with value: 0.8638789005031623 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:45,256] Trial 71 finished with value: 0.8869373758185156 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:47,141] Trial 72 finished with value: 0.8649189206287938 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:49,055] Trial 73 finished with value: 0.875888353632142 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:51,058] Trial 74 finished with value: 0.8833069251440915 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:53,033] Trial 75 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:54,965] Trial 76 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:56,898] Trial 77 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:26:58,780] Trial 78 finished with value: 0.8678703890908325 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:00,774] Trial 79 finished with value: 0.8678490454232699 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:02,727] Trial 80 finished with value: 0.8675459368056665 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:04,648] Trial 81 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:06,625] Trial 82 finished with value: 0.8649189206287938 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:08,521] Trial 83 finished with value: 0.8679015589957659 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:10,485] Trial 84 finished with value: 0.8765037271104353 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:12,398] Trial 85 finished with value: 0.8678703890908325 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:14,290] Trial 86 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:16,243] Trial 87 finished with value: 0.8698046345226332 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:18,243] Trial 88 finished with value: 0.8822659116103112 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:20,209] Trial 89 finished with value: 0.8834466985240436 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:22,086] Trial 90 finished with value: 0.8762851790289675 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:23,996] Trial 91 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:25,979] Trial 92 finished with value: 0.8649189206287938 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:27,903] Trial 93 finished with value: 0.8678703890908325 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:29,801] Trial 94 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:31,714] Trial 95 finished with value: 0.8539908307798117 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:33,663] Trial 96 finished with value: 0.8826051359295531 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:35,596] Trial 97 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:37,486] Trial 98 finished with value: 0.8679015589957659 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:39,353] Trial 99 finished with value: 0.876058942243762 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:41,319] Trial 100 finished with value: 0.8615137269822145 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:43,254] Trial 101 finished with value: 0.8750153797863585 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:45,152] Trial 102 finished with value: 0.8964182740614431 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 33 with value: 0.8964182740614431.
[I 2025-04-16 02:27:47,131] Trial 103 finished with value: 0.8698046345226332 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 33 with value: 0.8964182740614431.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.83}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smotenc_optuna-opt-me...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.948688
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.879545
cv_test_accuracy_balanced_median                                           0.888545
cv_test_roc_auc_median                                                     0.952012
cv_test_f1_median                                                          0.914286
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                      0.85

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smotenc_optuna-opt-mean-smote_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:39:43,748] A new study created in memory with name: smote_study
[I 2025-04-16 02:39:46,904] Trial 0 finished with value: 0.844034830222273 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.844034830222273.
[I 2025-04-16 02:39:49,970] Trial 1 finished with value: 0.8592114748564038 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:39:52,598] Trial 2 finished with value: 0.8338970611481458 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:39:55,486] Trial 3 finished with value: 0.8478415427275516 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:39:58,575] Trial 4 finished with value: 0.8402413822939901 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:01,711] Trial 5 finished with value: 0.8506898193175295 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:04,373] Trial 6 finished with value: 0.8351769905603936 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:07,056] Trial 7 finished with value: 0.836090003894084 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:09,997] Trial 8 finished with value: 0.8411225834608251 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:12,701] Trial 9 finished with value: 0.8343317409603939 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:15,592] Trial 10 finished with value: 0.8544933831156445 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:18,493] Trial 11 finished with value: 0.8454696771725635 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:21,510] Trial 12 finished with value: 0.8261066957758133 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8592114748564038.
[I 2025-04-16 02:40:24,593] Trial 13 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:27,683] Trial 14 finished with value: 0.8545440014135997 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:30,707] Trial 15 finished with value: 0.8248137100616892 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:33,606] Trial 16 finished with value: 0.8298941391052519 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:36,492] Trial 17 finished with value: 0.8367808334660801 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:39,546] Trial 18 finished with value: 0.838541025936423 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:42,239] Trial 19 finished with value: 0.8279529915407783 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.75}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:44,834] Trial 20 finished with value: 0.8305962714100886 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.61}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:47,935] Trial 21 finished with value: 0.8578790626879516 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:50,999] Trial 22 finished with value: 0.8442349476447737 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:54,037] Trial 23 finished with value: 0.8303821358375438 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:40:56,959] Trial 24 finished with value: 0.8521630441507669 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:00,064] Trial 25 finished with value: 0.8194803008782737 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:03,088] Trial 26 finished with value: 0.8454494053313734 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:06,173] Trial 27 finished with value: 0.8323117483776998 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:08,984] Trial 28 finished with value: 0.8335586589659556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:12,151] Trial 29 finished with value: 0.8271150652100927 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:15,131] Trial 30 finished with value: 0.836418212115188 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:18,198] Trial 31 finished with value: 0.8545440014135997 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:21,227] Trial 32 finished with value: 0.8392939492063244 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:24,404] Trial 33 finished with value: 0.8351609532504274 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:27,420] Trial 34 finished with value: 0.8479086669310087 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:30,529] Trial 35 finished with value: 0.8429032115400038 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:33,857] Trial 36 finished with value: 0.8271216951389022 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:36,715] Trial 37 finished with value: 0.8369120824811397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:39,741] Trial 38 finished with value: 0.8402413822939901 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:42,791] Trial 39 finished with value: 0.8275698760667031 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:45,756] Trial 40 finished with value: 0.836418212115188 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:48,872] Trial 41 finished with value: 0.8448370395550729 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:51,926] Trial 42 finished with value: 0.8392939492063244 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:54,776] Trial 43 finished with value: 0.8329933901366414 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:41:57,909] Trial 44 finished with value: 0.8428176842506768 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:00,995] Trial 45 finished with value: 0.8578790626879516 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:04,250] Trial 46 finished with value: 0.8335476968019478 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:07,194] Trial 47 finished with value: 0.8341561758790148 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:09,957] Trial 48 finished with value: 0.8403811355908737 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:13,049] Trial 49 finished with value: 0.8454494053313734 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:15,924] Trial 50 finished with value: 0.8442349476447737 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:19,046] Trial 51 finished with value: 0.8448370395550729 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:22,166] Trial 52 finished with value: 0.8429032115400038 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:25,344] Trial 53 finished with value: 0.8194803008782737 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:28,367] Trial 54 finished with value: 0.825465820292093 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:31,186] Trial 55 finished with value: 0.8278651116162573 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8099999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:34,221] Trial 56 finished with value: 0.8454494053313734 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:37,309] Trial 57 finished with value: 0.8550540827720605 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:40,149] Trial 58 finished with value: 0.8342135201627616 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.78}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:42,928] Trial 59 finished with value: 0.8342135201627616 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:46,216] Trial 60 finished with value: 0.8237759572674551 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:49,333] Trial 61 finished with value: 0.8550540827720605 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:52,263] Trial 62 finished with value: 0.8421617636700525 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:55,235] Trial 63 finished with value: 0.8349923244137593 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:42:58,128] Trial 64 finished with value: 0.8369120824811397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:01,176] Trial 65 finished with value: 0.8323486541702091 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:04,222] Trial 66 finished with value: 0.8367808334660801 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:07,106] Trial 67 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:10,012] Trial 68 finished with value: 0.8454696771725635 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:13,074] Trial 69 finished with value: 0.8349923244137593 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:15,756] Trial 70 finished with value: 0.8445944345813325 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:18,666] Trial 71 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:21,735] Trial 72 finished with value: 0.8396241587274497 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:24,808] Trial 73 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:27,710] Trial 74 finished with value: 0.8341561758790148 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:30,668] Trial 75 finished with value: 0.8241162505608838 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:33,674] Trial 76 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:36,665] Trial 77 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:39,829] Trial 78 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:42,847] Trial 79 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:45,919] Trial 80 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:48,950] Trial 81 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:52,035] Trial 82 finished with value: 0.8396241587274497 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:54,976] Trial 83 finished with value: 0.8341561758790148 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.82}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:43:58,033] Trial 84 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:00,977] Trial 85 finished with value: 0.8369120824811397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:03,978] Trial 86 finished with value: 0.8349923244137593 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:06,914] Trial 87 finished with value: 0.8303834871945373 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:09,800] Trial 88 finished with value: 0.8278651116162573 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8099999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:12,812] Trial 89 finished with value: 0.8396241587274497 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:15,634] Trial 90 finished with value: 0.8363041648775102 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:18,644] Trial 91 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:21,540] Trial 92 finished with value: 0.8303834871945373 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:24,681] Trial 93 finished with value: 0.8369120824811397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:27,731] Trial 94 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:30,842] Trial 95 finished with value: 0.82111961296615 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:33,828] Trial 96 finished with value: 0.8363041648775102 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:36,753] Trial 97 finished with value: 0.8337496576526462 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:39,529] Trial 98 finished with value: 0.8544933831156445 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:42,663] Trial 99 finished with value: 0.8594096878302582 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:45,814] Trial 100 finished with value: 0.8328716218749131 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8899999999999999}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:48,870] Trial 101 finished with value: 0.8303834871945373 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8594096878302582.
[I 2025-04-16 02:44:51,794] Trial 102 finished with value: 0.845439195697201 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8594096878302582.

best_params

{'k_neighbors': 10, 'sampling_strategy': 0.86}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_optuna...
holdout_test_f1_macro                                                      0.916089
holdout_test_accuracy_balanced                                             0.922727
holdout_test_roc_auc                                                           0.98
holdout_test_f1                                                            0.878049
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                     0.967521
cv_test_f1_median                                                          0.846154
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.947368

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smotenc_optuna-opt-mean-smote_default-model