Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 2500 # was checked with 1000 and 5000

save_model_and_metrics = True

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    seed:int=seed,
):
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}
params_to_process = ['penalty']

def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    
    # # NOTE: Does not work, since optuna requires static parameters ranges
    # solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # penalty_options = {
    #     'lbfgs': ['l2'],
    #     'liblinear': ['l1', 'l2'],
    #     'newton-cg': ['l2'],
    #     'newton-cholesky': ['l2'],
    #     'sag': ['l2'],
    #     'saga': ['l1', 'l2', 'elasticnet'],
    # }
    # penalty = trial.suggest_categorical('penalty', penalty_options[solver])
    # NOTE: warnings + inconvenient to create best model
    # solver_penalty_combinations = [
    #     ("liblinear", "l1"),
    #     ("liblinear", "l2"),
    #     ("saga", "l1"),
    #     ("saga", "l2"),
    #     ("saga", "elasticnet"),
    #     ("lbfgs", "l2"),
    #     ("newton-cg", "l2"),
    #     ("newton-cholesky", "l2"),
    #     ("sag", "l2"),
    # ]
    # solver, penalty = trial.suggest_categorical(
    #     'solver_penalty', solver_penalty_combinations
    # )
    
    solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # solver = trial.suggest_categorical('solver', ['lbfgs',])
    
    if solver == 'liblinear':
        penalty = trial.suggest_categorical('penalty_liblinear', ['l1', 'l2'])
    elif solver == 'saga':
        penalty = trial.suggest_categorical('penalty_saga', ['l1', 'l2', 'elasticnet'])
    else:
        penalty = trial.suggest_categorical('penalty_other', ['l2'])
    
    # If C is large, the penalty should be small
    C = trial.suggest_float('C', 1e-4, 1e3, log=True)
    
    l1_ratio = None
    if penalty == 'elasticnet':
        l1_ratio = trial.suggest_float('l1_ratio', 0., 1.)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "solver": solver,
        "penalty": penalty,
        "C": C,
        "l1_ratio": l1_ratio,
        "class_weight": class_weight,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 12:56:53,227] A new study created in memory with name: model_study
[I 2025-04-15 12:56:53,549] Trial 0 finished with value: 0.8029405104685957 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8029405104685957.
[I 2025-04-15 12:56:53,802] Trial 1 finished with value: 0.8080013100655117 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:54,093] Trial 2 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:54,349] Trial 3 finished with value: 0.798987972720532 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:54,606] Trial 4 finished with value: 0.8052137373589094 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:54,864] Trial 5 finished with value: 0.7508267704088138 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:55,138] Trial 6 finished with value: 0.8052137373589094 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:55,407] Trial 7 finished with value: 0.7641269622804342 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:55,669] Trial 8 finished with value: 0.8052137373589094 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:55,927] Trial 9 finished with value: 0.7442569817355229 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:56,202] Trial 10 finished with value: 0.7869272115862841 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.054522022569948085, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:56,478] Trial 11 finished with value: 0.8052137373589094 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 528.6800608490643, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:56,737] Trial 12 finished with value: 0.8052137373589094 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 425.33697175851336, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:57,012] Trial 13 finished with value: 0.8052137373589094 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 17.051371288602613, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:57,277] Trial 14 finished with value: 0.8068955952248212 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.342988497641889, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:57,549] Trial 15 finished with value: 0.8080013100655117 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.6977657864007571, 'class_weight': None}. Best is trial 1 with value: 0.8080013100655117.
[I 2025-04-15 12:56:57,834] Trial 16 finished with value: 0.8194164881585978 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.15947545233607524, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:58,104] Trial 17 finished with value: 0.7509691766343302 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0021492223708130657, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:58,372] Trial 18 finished with value: 0.8161438742915051 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.17332915226111342, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:58,632] Trial 19 finished with value: 0.7958374177932664 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.11877521724552643, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:58,890] Trial 20 finished with value: 0.7443141158070407 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.001624171955137326, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:59,159] Trial 21 finished with value: 0.8128465710771021 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.256235426070564, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:59,431] Trial 22 finished with value: 0.8088836306564623 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 4.575692132703617, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:59,687] Trial 23 finished with value: 0.7926102864196821 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.09233419851448578, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:56:59,925] Trial 24 finished with value: 0.8052137373589094 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 47.450427598911325, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:00,198] Trial 25 finished with value: 0.8128465710771021 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.187120192696614, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:00,470] Trial 26 finished with value: 0.767351723023992 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.02705835424080456, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:00,751] Trial 27 finished with value: 0.8194164881585978 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.15663100543009723, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:00,997] Trial 28 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.208444306365902, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:01,234] Trial 29 finished with value: 0.754203050018786 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.009419397995107794, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:01,480] Trial 30 finished with value: 0.7477444158907725 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.0020733697359909264, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:01,732] Trial 31 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.18129664284646513, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:01,980] Trial 32 finished with value: 0.8080013100655117 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.6358901880345773, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:02,215] Trial 33 finished with value: 0.7804917579981652 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.042997509111852905, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:02,451] Trial 34 finished with value: 0.8118515774451909 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.3836985125437585, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:02,698] Trial 35 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.2654532382450376, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:02,933] Trial 36 finished with value: 0.8068955952248212 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.2875218620157376, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:03,165] Trial 37 finished with value: 0.7574910318781963 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.010166989486501075, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:03,405] Trial 38 finished with value: 0.7926102864196821 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.09200143184056397, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:03,636] Trial 39 finished with value: 0.767351723023992 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.02311798915080294, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:03,870] Trial 40 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.28979246178010004, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:04,123] Trial 41 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.18645149059693156, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:04,362] Trial 42 finished with value: 0.8080013100655117 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.6533456184192091, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:04,600] Trial 43 finished with value: 0.7869272115862841 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.055334176736639096, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:04,830] Trial 44 finished with value: 0.8159940282655498 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.13774072667563808, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:05,066] Trial 45 finished with value: 0.8068955952248212 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.0883794965172489, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:05,298] Trial 46 finished with value: 0.7510370678104267 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.004263131327770479, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:05,570] Trial 47 finished with value: 0.7873341904454811 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.05528383181678336, 'l1_ratio': 0.041994011296772604, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:05,819] Trial 48 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.2100948023093433, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:06,049] Trial 49 finished with value: 0.7410322209919651 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.0005639111644513547, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:06,299] Trial 50 finished with value: 0.7608247089781809 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.014809271937409501, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:06,543] Trial 51 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.33463478588007367, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:06,791] Trial 52 finished with value: 0.8029405104685957 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 1.89301929160307, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:07,037] Trial 53 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.1922084462662213, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:07,283] Trial 54 finished with value: 0.7926102864196821 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.09977251402395236, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:07,526] Trial 55 finished with value: 0.8052137373589094 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 9.009730556170723, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:07,756] Trial 56 finished with value: 0.8080013100655117 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.46883705978339396, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:07,993] Trial 57 finished with value: 0.8029405104685957 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.9935766564696538, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:08,243] Trial 58 finished with value: 0.777222450275076 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.03532152246947522, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:08,494] Trial 59 finished with value: 0.7926102864196821 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.08148341312715365, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:08,733] Trial 60 finished with value: 0.8068955952248212 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.9222437123244991, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:08,969] Trial 61 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.21556069884387494, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:09,204] Trial 62 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.3313279912934194, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:09,439] Trial 63 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.27846017508621873, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:09,675] Trial 64 finished with value: 0.8080013100655117 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4888795239996051, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:09,915] Trial 65 finished with value: 0.8161438742915051 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.1668558172190112, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:10,149] Trial 66 finished with value: 0.777222450275076 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.03719903175180669, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:10,386] Trial 67 finished with value: 0.7926102864196821 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.06752679470376259, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:10,645] Trial 68 finished with value: 0.8052137373589094 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 240.904073200264, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:10,884] Trial 69 finished with value: 0.7608247089781809 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.016394421531004125, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:11,124] Trial 70 finished with value: 0.8112202822094557 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.7789833340897874, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:11,361] Trial 71 finished with value: 0.7958374177932664 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.12608431477878884, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:11,598] Trial 72 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.21782178487226064, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:11,835] Trial 73 finished with value: 0.8080013100655117 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.5088143648113296, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:12,075] Trial 74 finished with value: 0.8161438742915051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.32006731717873144, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:12,311] Trial 75 finished with value: 0.7958374177932664 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.11682546754921774, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:12,542] Trial 76 finished with value: 0.7926102864196821 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.066173251496779, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:12,796] Trial 77 finished with value: 0.8052137373589094 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 3.21733227769208, 'class_weight': None}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:13,033] Trial 78 finished with value: 0.8194164881585978 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.1489759585626702, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:13,279] Trial 79 finished with value: 0.770593127693968 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.03125981400151674, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.
[I 2025-04-15 12:57:13,517] Trial 80 finished with value: 0.8029405104685957 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.7474411083621388, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8194164881585978.

best_params

{'solver': 'sag',
 'C': 0.15947545233607524,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                               0
target                                                                 splashing
model                             LogisticRegression_splashing_smotenc_opt-model
holdout_test_f1_macro                                                   0.762526
holdout_test_accuracy_balanced                                          0.774306
holdout_test_roc_auc                                                    0.892747
holdout_test_f1                                                         0.813187
holdout_test_accuracy                                                   0.773333
cv_test_f1_macro_median                                                 0.802827
cv_test_accuracy_balanced_median                                        0.818111
cv_test_roc_auc_median                                                  0.874603
cv_test_f1_median                                                       0.833333
cv_test_accuracy_median                                                 0.811321
cv_test_precision_class_0_median                                        0.666667
cv_test_recall_class_0_median                                           0.894737
cv_test_f1_class_0_median                                               0.761905

Model saved in ..\results\models_modelling4\LogisticRegression_splashing_smotenc_opt-model

In [7]:
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 13:07:21,585] A new study created in memory with name: model_study
[I 2025-04-15 13:07:21,790] Trial 0 finished with value: 0.7956187818822562 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.7956187818822562.
[I 2025-04-15 13:07:22,035] Trial 1 finished with value: 0.7823513803955141 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.7956187818822562.
[I 2025-04-15 13:07:22,237] Trial 2 finished with value: 0.4233049487844008 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.7956187818822562.
[I 2025-04-15 13:07:22,449] Trial 3 finished with value: 0.7828346772451799 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7956187818822562.
[I 2025-04-15 13:07:22,684] Trial 4 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:22,892] Trial 5 finished with value: 0.6789922432701222 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:23,259] Trial 6 finished with value: 0.8082457724380243 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:23,466] Trial 7 finished with value: 0.7257827601999474 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:23,675] Trial 8 finished with value: 0.8037916023565363 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:23,882] Trial 9 finished with value: 0.6801262113129842 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:24,114] Trial 10 finished with value: 0.8082457724380243 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 339.09030772940355, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:24,485] Trial 11 finished with value: 0.8082457724380243 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 225.76341561444747, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:24,864] Trial 12 finished with value: 0.8047797661524693 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 35.668189318213685, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:25,072] Trial 13 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 920.0567882290983, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:25,280] Trial 14 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 984.0801045784625, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:25,491] Trial 15 finished with value: 0.8047797661524693 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 6.710520506428811, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:25,706] Trial 16 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 921.0395859763895, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:25,967] Trial 17 finished with value: 0.8017532747521017 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 84.91274168473814, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:26,179] Trial 18 finished with value: 0.8037916023565363 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.93172666180029, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:26,401] Trial 19 finished with value: 0.7480765304193128 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.06285591342420138, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:26,606] Trial 20 finished with value: 0.4233049487844008 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.001980697601550351, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:26,817] Trial 21 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 802.1987365630888, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:27,036] Trial 22 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 198.6392630241442, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:27,244] Trial 23 finished with value: 0.8082457724380243 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 854.1145747726621, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:27,451] Trial 24 finished with value: 0.8082457724380243 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 39.53976388163104, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:27,663] Trial 25 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 155.6851810990243, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:27,870] Trial 26 finished with value: 0.8028270588502571 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 2.1930187986890664, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:28,096] Trial 27 finished with value: 0.8017532747521017 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 27.14110743633125, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:28,313] Trial 28 finished with value: 0.8047797661524693 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 312.4958687906974, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:28,523] Trial 29 finished with value: 0.7956187818822562 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.8832850698022066, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:28,788] Trial 30 finished with value: 0.8047797661524693 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 136.7460646601702, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:29,000] Trial 31 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 795.6002679837567, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:29,222] Trial 32 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 674.6194407735293, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:29,439] Trial 33 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 334.50630893757324, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:29,647] Trial 34 finished with value: 0.7923626286200387 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.42142637614838546, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:29,870] Trial 35 finished with value: 0.8082457724380243 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 989.7331986256619, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:30,109] Trial 36 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 77.70577696629755, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:30,322] Trial 37 finished with value: 0.8047797661524693 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 19.521030080607154, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:30,547] Trial 38 finished with value: 0.8082457724380243 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 398.4993965217616, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:30,786] Trial 39 finished with value: 0.4233049487844008 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.0008966462592588161, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:30,998] Trial 40 finished with value: 0.7480765304193128 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.09089588095656304, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:31,215] Trial 41 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 107.33855808596579, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:31,427] Trial 42 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 527.8185677644072, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:31,756] Trial 43 finished with value: 0.8082457724380243 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 883.9053925319445, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:31,973] Trial 44 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 226.21675841566855, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:32,186] Trial 45 finished with value: 0.8017532747521017 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 67.47765544561051, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:32,412] Trial 46 finished with value: 0.8082457724380243 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 496.152623839011, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:32,622] Trial 47 finished with value: 0.8047797661524693 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 14.380101067706342, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:32,982] Trial 48 finished with value: 0.8047797661524693 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 212.32295774649504, 'l1_ratio': 0.0039728600933803815, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:33,194] Trial 49 finished with value: 0.8017532747521017 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 4.134437008770605, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:33,406] Trial 50 finished with value: 0.8017532747521017 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 52.56447527792911, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:33,617] Trial 51 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 150.36914784929718, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:33,827] Trial 52 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 404.5380050189213, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:34,036] Trial 53 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 245.50436780430394, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:34,257] Trial 54 finished with value: 0.8082457724380243 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 510.41633556589574, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:34,465] Trial 55 finished with value: 0.7989368060066065 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.8385307837830331, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:34,732] Trial 56 finished with value: 0.8047797661524693 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 147.69502875026774, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:34,942] Trial 57 finished with value: 0.8017532747521017 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 38.200615488583104, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:35,155] Trial 58 finished with value: 0.8017532747521017 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 95.4088261918396, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:35,365] Trial 59 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 273.63277376191655, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:35,598] Trial 60 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 884.9302638727336, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:35,815] Trial 61 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 163.84363660316006, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:36,058] Trial 62 finished with value: 0.8082457724380243 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 507.4646170547818, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:36,276] Trial 63 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 314.63719395349506, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:36,493] Trial 64 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 968.9078407016783, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:36,714] Trial 65 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 68.55071332194056, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:37,057] Trial 66 finished with value: 0.8082457724380243 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 565.6581895438982, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:37,272] Trial 67 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 179.89552806065603, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:37,485] Trial 68 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 331.33269863419616, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:37,700] Trial 69 finished with value: 0.7600731303544614 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.15985006037745855, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:37,925] Trial 70 finished with value: 0.8017532747521017 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 114.96810864741153, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:38,133] Trial 71 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 636.2295508266847, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:38,341] Trial 72 finished with value: 0.4233049487844008 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.008348721504885864, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:38,547] Trial 73 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 687.0593788289029, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:38,757] Trial 74 finished with value: 0.7982872684665464 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 23.09189793747074, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:38,967] Trial 75 finished with value: 0.8082457724380243 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 969.7962847485626, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:39,177] Trial 76 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 378.6892047900205, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:39,389] Trial 77 finished with value: 0.6801262113129842 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0003592201925391139, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:39,598] Trial 78 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 225.95921750025522, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:39,818] Trial 79 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 632.5958976833052, 'class_weight': None}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:40,033] Trial 80 finished with value: 0.8082457724380243 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 52.058900669315214, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.
[I 2025-04-15 13:07:40,242] Trial 81 finished with value: 0.8113740223354587 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 384.40518594797913, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.8113740223354587.

best_params

{'solver': 'liblinear',
 'C': 377.1313111077982,
 'class_weight': None,
 'penalty': 'l1'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.816176
holdout_test_accuracy_balanced                                             0.859091
holdout_test_roc_auc                                                       0.958182
holdout_test_f1                                                                0.75
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.814035
cv_test_accuracy_balanced_median                                           0.828755
cv_test_roc_auc_median                                                     0.930403
cv_test_f1_median                                                          0.733333
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                             0.9375
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.891892

Model saved in ..\results\models_modelling4\LogisticRegression_no_fragmentation_smotenc_opt-model

# KNClassifier

In [8]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['penalty']
params_to_process = None


def knn_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    n_neighbors = trial.suggest_int("n_neighbors", 1, 50)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    p = trial.suggest_int("p", 1, 2)  # 1=manhattan, 2=euclidean
    # leaf_size - affects the speed of the tree construction and search
    # algorithm - affects the speed of the search, for small datasets it is okay to use auto
    
    suggested_estimator_params = {
        "n_neighbors": n_neighbors,
        "weights": weights,
        "p": p,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 13:17:14,246] A new study created in memory with name: model_study
[I 2025-04-15 13:17:14,560] Trial 0 finished with value: 0.7939480467480491 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7939480467480491.
[I 2025-04-15 13:17:14,898] Trial 1 finished with value: 0.7999263344348188 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.7999263344348188.
[I 2025-04-15 13:17:15,213] Trial 2 finished with value: 0.7854062872511908 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.7999263344348188.
[I 2025-04-15 13:17:15,525] Trial 3 finished with value: 0.7457746630196448 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.7999263344348188.
[I 2025-04-15 13:17:15,832] Trial 4 finished with value: 0.7713643389026997 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.7999263344348188.
[I 2025-04-15 13:17:16,067] Trial 5 finished with value: 0.8690983065354881 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8690983065354881.
[I 2025-04-15 13:17:16,372] Trial 6 finished with value: 0.7800749969569731 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8690983065354881.
[I 2025-04-15 13:17:16,609] Trial 7 finished with value: 0.865602685413139 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8690983065354881.
[I 2025-04-15 13:17:16,836] Trial 8 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8720072251447111.
[I 2025-04-15 13:17:17,082] Trial 9 finished with value: 0.8471689833009622 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8720072251447111.
[I 2025-04-15 13:17:17,314] Trial 10 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:17,543] Trial 11 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:17,774] Trial 12 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:18,006] Trial 13 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:18,240] Trial 14 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:18,487] Trial 15 finished with value: 0.8431095975963924 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:18,716] Trial 16 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:18,953] Trial 17 finished with value: 0.870443625724456 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:19,204] Trial 18 finished with value: 0.8463425535223895 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:19,445] Trial 19 finished with value: 0.8649940340553368 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:19,689] Trial 20 finished with value: 0.865031671428074 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:19,919] Trial 21 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:20,154] Trial 22 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:20,384] Trial 23 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:20,623] Trial 24 finished with value: 0.846918985049977 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:20,857] Trial 25 finished with value: 0.8668107899964138 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:21,087] Trial 26 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:21,338] Trial 27 finished with value: 0.858231785850642 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:21,575] Trial 28 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:21,884] Trial 29 finished with value: 0.7778148152742755 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:22,120] Trial 30 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:22,352] Trial 31 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:22,585] Trial 32 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:22,821] Trial 33 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:23,124] Trial 34 finished with value: 0.7999263344348188 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:23,431] Trial 35 finished with value: 0.8485137021747363 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:23,680] Trial 36 finished with value: 0.858231785850642 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:23,998] Trial 37 finished with value: 0.769408119309026 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:24,238] Trial 38 finished with value: 0.8356651243724299 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:24,471] Trial 39 finished with value: 0.870443625724456 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:24,770] Trial 40 finished with value: 0.8396143874361242 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:24,995] Trial 41 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:25,227] Trial 42 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:25,453] Trial 43 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:25,703] Trial 44 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:25,935] Trial 45 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:26,167] Trial 46 finished with value: 0.8668107899964138 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:26,407] Trial 47 finished with value: 0.8685421957288789 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:26,641] Trial 48 finished with value: 0.8612223985518234 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:26,875] Trial 49 finished with value: 0.856956473622633 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:27,120] Trial 50 finished with value: 0.8431095975963924 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:27,350] Trial 51 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:27,577] Trial 52 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:27,819] Trial 53 finished with value: 0.8668107899964138 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:28,059] Trial 54 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:28,291] Trial 55 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:28,523] Trial 56 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:28,768] Trial 57 finished with value: 0.8569495558317639 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:29,076] Trial 58 finished with value: 0.7778148152742755 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:29,309] Trial 59 finished with value: 0.870443625724456 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:29,542] Trial 60 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:29,770] Trial 61 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:30,013] Trial 62 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:30,247] Trial 63 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:30,482] Trial 64 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:30,720] Trial 65 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:30,953] Trial 66 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:31,188] Trial 67 finished with value: 0.8668107899964138 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:31,530] Trial 68 finished with value: 0.8374839399264464 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:31,775] Trial 69 finished with value: 0.8672305736837803 and parameters: {'n_neighbors': 34, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:32,006] Trial 70 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:32,250] Trial 71 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:32,482] Trial 72 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:32,708] Trial 73 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:32,939] Trial 74 finished with value: 0.870443625724456 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:33,172] Trial 75 finished with value: 0.8612223985518234 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:33,402] Trial 76 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:33,631] Trial 77 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:33,931] Trial 78 finished with value: 0.816616250613026 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:34,171] Trial 79 finished with value: 0.8546355327669095 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:34,423] Trial 80 finished with value: 0.8430542008420083 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:34,651] Trial 81 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:34,892] Trial 82 finished with value: 0.8612150679234295 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:35,120] Trial 83 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:35,354] Trial 84 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:35,585] Trial 85 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:35,818] Trial 86 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:36,050] Trial 87 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:36,277] Trial 88 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:36,517] Trial 89 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:36,821] Trial 90 finished with value: 0.816616250613026 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:37,051] Trial 91 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:37,285] Trial 92 finished with value: 0.8720072251447111 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:37,518] Trial 93 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:37,749] Trial 94 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:37,979] Trial 95 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:38,214] Trial 96 finished with value: 0.8809181617089333 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:38,450] Trial 97 finished with value: 0.8606271128184824 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:38,701] Trial 98 finished with value: 0.8859578022350384 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:38,944] Trial 99 finished with value: 0.8685421957288789 and parameters: {'n_neighbors': 29, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:39,173] Trial 100 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:39,402] Trial 101 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 13:17:39,632] Trial 102 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.

best_params

{'n_neighbors': 1, 'weights': 'distance', 'p': 1}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                 0
target                                                                   splashing
model                             KNeighborsClassifier_splashing_smotenc_opt-model
holdout_test_f1_macro                                                       0.8333
holdout_test_accuracy_balanced                                            0.820602
holdout_test_roc_auc                                                      0.820602
holdout_test_f1                                                           0.891089
holdout_test_accuracy                                                     0.853333
cv_test_f1_macro_median                                                   0.900563
cv_test_accuracy_balanced_median                                          0.894737
cv_test_roc_auc_median                                                    0.894737
cv_test_f1_median                                                         0.927536
cv_test_accuracy_median                                                    0.90566
cv_test_precision_class_0_median                                          0.857143
cv_test_recall_class_0_median                                             0.842105
cv_test_f1_class_0_median                                                 0.878049

Model saved in ..\results\models_modelling4\KNeighborsClassifier_splashing_smotenc_opt-model

In [9]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 13:28:15,088] A new study created in memory with name: model_study
[I 2025-04-15 13:28:15,376] Trial 0 finished with value: 0.7586106248304578 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7586106248304578.
[I 2025-04-15 13:28:15,665] Trial 1 finished with value: 0.8014367348413305 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8014367348413305.
[I 2025-04-15 13:28:15,963] Trial 2 finished with value: 0.7300499179946813 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8014367348413305.
[I 2025-04-15 13:28:16,281] Trial 3 finished with value: 0.7043589478250861 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8014367348413305.
[I 2025-04-15 13:28:16,570] Trial 4 finished with value: 0.7634877494230409 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8014367348413305.
[I 2025-04-15 13:28:16,791] Trial 5 finished with value: 0.8197584577078102 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8197584577078102.
[I 2025-04-15 13:28:17,079] Trial 6 finished with value: 0.7363071565954369 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8197584577078102.
[I 2025-04-15 13:28:17,300] Trial 7 finished with value: 0.8227633569665913 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 7 with value: 0.8227633569665913.
[I 2025-04-15 13:28:17,511] Trial 8 finished with value: 0.8414398257098158 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:17,728] Trial 9 finished with value: 0.8205250988011696 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:17,942] Trial 10 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:18,154] Trial 11 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:18,372] Trial 12 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:18,600] Trial 13 finished with value: 0.811240914956308 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:18,817] Trial 14 finished with value: 0.8252627347627914 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:19,047] Trial 15 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:19,276] Trial 16 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:19,505] Trial 17 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 40, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:19,736] Trial 18 finished with value: 0.8271498079120584 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:19,962] Trial 19 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:20,185] Trial 20 finished with value: 0.8295064976844421 and parameters: {'n_neighbors': 22, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:20,419] Trial 21 finished with value: 0.8271498079120584 and parameters: {'n_neighbors': 49, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:20,664] Trial 22 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:20,894] Trial 23 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 39, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:21,122] Trial 24 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:21,399] Trial 25 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:21,628] Trial 26 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:21,851] Trial 27 finished with value: 0.8212873517056755 and parameters: {'n_neighbors': 27, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:22,083] Trial 28 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 36, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:22,378] Trial 29 finished with value: 0.7842295467766084 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:22,609] Trial 30 finished with value: 0.8271498079120584 and parameters: {'n_neighbors': 48, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:22,863] Trial 31 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:23,091] Trial 32 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 42, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:23,323] Trial 33 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:23,620] Trial 34 finished with value: 0.7367831994679286 and parameters: {'n_neighbors': 47, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:23,923] Trial 35 finished with value: 0.7356912745146956 and parameters: {'n_neighbors': 40, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:24,186] Trial 36 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 33, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:24,491] Trial 37 finished with value: 0.7043589478250861 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:24,723] Trial 38 finished with value: 0.8271498079120584 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:24,957] Trial 39 finished with value: 0.8227633569665913 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:25,251] Trial 40 finished with value: 0.7614367939019998 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:25,480] Trial 41 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:25,710] Trial 42 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:25,933] Trial 43 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 38, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:26,160] Trial 44 finished with value: 0.8302687505889477 and parameters: {'n_neighbors': 44, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:26,375] Trial 45 finished with value: 0.8414398257098158 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:26,587] Trial 46 finished with value: 0.8414398257098158 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:26,806] Trial 47 finished with value: 0.8391848561330154 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:27,033] Trial 48 finished with value: 0.8252627347627914 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:27,255] Trial 49 finished with value: 0.8334564559047857 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:27,467] Trial 50 finished with value: 0.8334564559047857 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:27,683] Trial 51 finished with value: 0.8334564559047857 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:27,902] Trial 52 finished with value: 0.8334564559047857 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:28,120] Trial 53 finished with value: 0.836782976053964 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:28,337] Trial 54 finished with value: 0.836782976053964 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:28,556] Trial 55 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:28,774] Trial 56 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:28,990] Trial 57 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:29,218] Trial 58 finished with value: 0.8384866491651538 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:29,506] Trial 59 finished with value: 0.7565609027934573 and parameters: {'n_neighbors': 17, 'weights': 'uniform', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:29,718] Trial 60 finished with value: 0.8323944749118602 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:29,935] Trial 61 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:30,150] Trial 62 finished with value: 0.835336816452678 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:30,365] Trial 63 finished with value: 0.836782976053964 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:30,578] Trial 64 finished with value: 0.8365464867669866 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:30,796] Trial 65 finished with value: 0.8286606920215086 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:31,016] Trial 66 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:31,228] Trial 67 finished with value: 0.8323944749118602 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:31,452] Trial 68 finished with value: 0.8277488328080425 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:31,672] Trial 69 finished with value: 0.8170588279442137 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:31,891] Trial 70 finished with value: 0.8251269960272634 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:32,109] Trial 71 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:32,326] Trial 72 finished with value: 0.8388705124469235 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8414398257098158.
[I 2025-04-15 13:28:32,541] Trial 73 finished with value: 0.8422740924945923 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 1}. Best is trial 73 with value: 0.8422740924945923.
[I 2025-04-15 13:28:32,755] Trial 74 finished with value: 0.8422740924945923 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 1}. Best is trial 73 with value: 0.8422740924945923.
[I 2025-04-15 13:28:32,970] Trial 75 finished with value: 0.8422740924945923 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 1}. Best is trial 73 with value: 0.8422740924945923.
[I 2025-04-15 13:28:33,184] Trial 76 finished with value: 0.8391848561330154 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 73 with value: 0.8422740924945923.
[I 2025-04-15 13:28:33,472] Trial 77 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:33,764] Trial 78 finished with value: 0.8223486471019978 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:34,038] Trial 79 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:34,320] Trial 80 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:34,607] Trial 81 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:34,892] Trial 82 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:35,177] Trial 83 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:35,464] Trial 84 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:35,761] Trial 85 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:36,048] Trial 86 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:36,331] Trial 87 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:36,617] Trial 88 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:36,902] Trial 89 finished with value: 0.8223486471019978 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:37,194] Trial 90 finished with value: 0.8014367348413305 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:37,480] Trial 91 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:37,768] Trial 92 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:38,063] Trial 93 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:38,340] Trial 94 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:38,620] Trial 95 finished with value: 0.8071580420085098 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:38,900] Trial 96 finished with value: 0.8223486471019978 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:39,182] Trial 97 finished with value: 0.8014367348413305 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:39,464] Trial 98 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:39,749] Trial 99 finished with value: 0.7927137816548374 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:40,046] Trial 100 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:40,362] Trial 101 finished with value: 0.8288179587366137 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.
[I 2025-04-15 13:28:40,646] Trial 102 finished with value: 0.854359327045551 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 77 with value: 0.854359327045551.

best_params

{'n_neighbors': 3, 'weights': 'uniform', 'p': 2}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smotenc_...
holdout_test_f1_macro                                                      0.820691
holdout_test_accuracy_balanced                                             0.836364
holdout_test_roc_auc                                                       0.902727
holdout_test_f1                                                            0.744186
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.847115
cv_test_accuracy_balanced_median                                           0.854396
cv_test_roc_auc_median                                                     0.934982
cv_test_f1_median                                                          0.774194
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.918919

Model saved in ..\results\models_modelling4\KNeighborsClassifier_no_fragmentation_smotenc_opt-model

# SVC

In [6]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True, # Would beFalse for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']


def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=n_trials,
    seed=21,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 13:57:30,026] A new study created in memory with name: model_study
[I 2025-04-15 13:57:30,391] Trial 0 finished with value: 0.7510726087608125 and parameters: {'kernel': 'sigmoid', 'C': 0.017200322569383943, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.06957095461260054}. Best is trial 0 with value: 0.7510726087608125.
[I 2025-04-15 13:57:30,837] Trial 1 finished with value: 0.8068068712470016 and parameters: {'kernel': 'linear', 'C': 152.1240458771676, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8068068712470016.
[I 2025-04-15 13:57:31,082] Trial 2 finished with value: 0.8308180959707042 and parameters: {'kernel': 'linear', 'C': 0.04207446825995604, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8308180959707042.
[I 2025-04-15 13:57:31,326] Trial 3 finished with value: 0.8308180959707042 and parameters: {'kernel': 'linear', 'C': 0.05054268043577859, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8308180959707042.
[I 2025-04-15 13:57:31,570] Trial 4 finished with value: 0.6154809421679566 and parameters: {'kernel': 'sigmoid', 'C': 124.66836974089675, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8101575494926372}. Best is trial 2 with value: 0.8308180959707042.
[I 2025-04-15 13:57:31,820] Trial 5 finished with value: 0.8701299254036903 and parameters: {'kernel': 'rbf', 'C': 142.34323346004942, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 5 with value: 0.8701299254036903.
[I 2025-04-15 13:57:32,061] Trial 6 finished with value: 0.8105603306266022 and parameters: {'kernel': 'linear', 'C': 3.4893664517416547, 'class_weight': None}. Best is trial 5 with value: 0.8701299254036903.
[I 2025-04-15 13:57:32,431] Trial 7 finished with value: 0.8100422130027515 and parameters: {'kernel': 'linear', 'C': 82.43990345883874, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8701299254036903.
[I 2025-04-15 13:57:32,755] Trial 8 finished with value: 0.8217361162692356 and parameters: {'kernel': 'rbf', 'C': 0.011898133534060652, 'class_weight': None, 'gamma_type': 'float', 'gamma': 1.0492807664612955}. Best is trial 5 with value: 0.8701299254036903.
[I 2025-04-15 13:57:33,020] Trial 9 finished with value: 0.8364127012859603 and parameters: {'kernel': 'linear', 'C': 0.17423146642890194, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8701299254036903.
[I 2025-04-15 13:57:33,397] Trial 10 finished with value: 0.8910428934842968 and parameters: {'kernel': 'rbf', 'C': 5.407228438802247, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:33,653] Trial 11 finished with value: 0.8879972572779947 and parameters: {'kernel': 'rbf', 'C': 4.693691230600619, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:33,908] Trial 12 finished with value: 0.8714868612507919 and parameters: {'kernel': 'rbf', 'C': 3.5096622613856283, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:34,159] Trial 13 finished with value: 0.46207416422738856 and parameters: {'kernel': 'poly', 'C': 0.0013032467401225857, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9738461993839926, 'degree': 5}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:34,447] Trial 14 finished with value: 0.8898137071498687 and parameters: {'kernel': 'rbf', 'C': 10.83025947205154, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:34,699] Trial 15 finished with value: 0.8801414483972232 and parameters: {'kernel': 'rbf', 'C': 16.631161814266807, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:35,013] Trial 16 finished with value: 0.8742343059434666 and parameters: {'kernel': 'poly', 'C': 903.1745946682223, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2128753363728374, 'degree': 2}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:35,333] Trial 17 finished with value: 0.5391473509494925 and parameters: {'kernel': 'rbf', 'C': 0.641185692778057, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.00013776736545287972}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:35,588] Trial 18 finished with value: 0.8838046368550844 and parameters: {'kernel': 'rbf', 'C': 21.606601571971847, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:35,859] Trial 19 finished with value: 0.8620204950368952 and parameters: {'kernel': 'rbf', 'C': 0.7098830722451398, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:36,103] Trial 20 finished with value: 0.6465468398504761 and parameters: {'kernel': 'sigmoid', 'C': 11.714984313490708, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5069513781282213}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:36,358] Trial 21 finished with value: 0.8714868612507919 and parameters: {'kernel': 'rbf', 'C': 3.4461658069809142, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:36,615] Trial 22 finished with value: 0.8649110973639978 and parameters: {'kernel': 'rbf', 'C': 1.6349342961683357, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:36,869] Trial 23 finished with value: 0.8789508423455926 and parameters: {'kernel': 'rbf', 'C': 32.109458756553245, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:37,125] Trial 24 finished with value: 0.5391473509494925 and parameters: {'kernel': 'poly', 'C': 0.28401057646250705, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.0009686057297733395, 'coef0': 0.5219897247902975, 'degree': 5}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:37,405] Trial 25 finished with value: 0.863247068368353 and parameters: {'kernel': 'rbf', 'C': 703.9842911697316, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 10 with value: 0.8910428934842968.
[I 2025-04-15 13:57:37,662] Trial 26 finished with value: 0.8941653372979593 and parameters: {'kernel': 'rbf', 'C': 5.923104641090013, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:37,914] Trial 27 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 8.602265399152618, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:38,170] Trial 28 finished with value: 0.868293920192178 and parameters: {'kernel': 'rbf', 'C': 55.90386637242426, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:38,426] Trial 29 finished with value: 0.6592343888265414 and parameters: {'kernel': 'sigmoid', 'C': 1.1584177251809682, 'class_weight': None, 'gamma_type': 'float', 'gamma': 6.248990160537605, 'coef0': 0.2743942387331329}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:38,674] Trial 30 finished with value: 0.8624148345908985 and parameters: {'kernel': 'poly', 'C': 0.23927948634590127, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7250702762396277, 'degree': 2}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:38,929] Trial 31 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 12.030568541363252, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:39,183] Trial 32 finished with value: 0.8941653372979593 and parameters: {'kernel': 'rbf', 'C': 6.302513488921194, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:39,453] Trial 33 finished with value: 0.8898137071498687 and parameters: {'kernel': 'rbf', 'C': 9.474573491469956, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:39,710] Trial 34 finished with value: 0.8649110973639978 and parameters: {'kernel': 'rbf', 'C': 1.8822823539081368, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:39,958] Trial 35 finished with value: 0.6887384530847437 and parameters: {'kernel': 'sigmoid', 'C': 270.98071243408094, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.01028680522359593}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:40,212] Trial 36 finished with value: 0.868293920192178 and parameters: {'kernel': 'rbf', 'C': 50.07736806307136, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:40,465] Trial 37 finished with value: 0.8830609085246243 and parameters: {'kernel': 'rbf', 'C': 28.25986309910222, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:40,722] Trial 38 finished with value: 0.8068512279379076 and parameters: {'kernel': 'linear', 'C': 9.144078383632026, 'class_weight': None}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:40,969] Trial 39 finished with value: 0.7003076281017456 and parameters: {'kernel': 'sigmoid', 'C': 316.7335305523716, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.29656250603776146}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:41,229] Trial 40 finished with value: 0.8649110973639978 and parameters: {'kernel': 'rbf', 'C': 2.0261190006941012, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:41,481] Trial 41 finished with value: 0.8908841714591899 and parameters: {'kernel': 'rbf', 'C': 5.757093938768285, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:41,748] Trial 42 finished with value: 0.8941653372979593 and parameters: {'kernel': 'rbf', 'C': 6.090149864073378, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:42,004] Trial 43 finished with value: 0.882232008184362 and parameters: {'kernel': 'rbf', 'C': 41.24000382493182, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:42,285] Trial 44 finished with value: 0.8048962430807424 and parameters: {'kernel': 'rbf', 'C': 0.3908610774849388, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.01681279721904529}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:42,527] Trial 45 finished with value: 0.830016833918285 and parameters: {'kernel': 'linear', 'C': 0.12568736812472855, 'class_weight': None}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:42,779] Trial 46 finished with value: 0.8685122364003866 and parameters: {'kernel': 'rbf', 'C': 87.21856090820198, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:43,035] Trial 47 finished with value: 0.8864510136024081 and parameters: {'kernel': 'rbf', 'C': 5.737781435452561, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:43,283] Trial 48 finished with value: 0.8801414483972232 and parameters: {'kernel': 'rbf', 'C': 16.33756622996414, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:43,523] Trial 49 finished with value: 0.8879528142438381 and parameters: {'kernel': 'poly', 'C': 2.4789658812705935, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7029893885525039, 'degree': 4}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:43,770] Trial 50 finished with value: 0.8271066915499689 and parameters: {'kernel': 'linear', 'C': 0.07402239200472799, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:44,026] Trial 51 finished with value: 0.8910428934842968 and parameters: {'kernel': 'rbf', 'C': 5.5162446019256715, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:44,281] Trial 52 finished with value: 0.8657659932361748 and parameters: {'kernel': 'rbf', 'C': 1.0126080203416261, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:44,530] Trial 53 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 7.735012471656939, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:44,775] Trial 54 finished with value: 0.8801414483972232 and parameters: {'kernel': 'rbf', 'C': 17.460658047675768, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:45,025] Trial 55 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 8.35985746596678, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:45,281] Trial 56 finished with value: 0.8714868612507919 and parameters: {'kernel': 'rbf', 'C': 3.143703523258269, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:45,578] Trial 57 finished with value: 0.805495813663262 and parameters: {'kernel': 'rbf', 'C': 0.0042170373084173506, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:45,830] Trial 58 finished with value: 0.8830609085246243 and parameters: {'kernel': 'rbf', 'C': 23.796939747675175, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:46,109] Trial 59 finished with value: 0.8390674580725601 and parameters: {'kernel': 'rbf', 'C': 0.5064229903459043, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.038976583810018395}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:46,357] Trial 60 finished with value: 0.6163169214332351 and parameters: {'kernel': 'sigmoid', 'C': 13.16397286563553, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9723075067182702}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:46,610] Trial 61 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 7.930956722207901, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:46,875] Trial 62 finished with value: 0.8813729072268901 and parameters: {'kernel': 'rbf', 'C': 3.8751769991336484, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:47,129] Trial 63 finished with value: 0.8615599387187215 and parameters: {'kernel': 'rbf', 'C': 1.3975722163301245, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:47,380] Trial 64 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 7.644185507539126, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:47,617] Trial 65 finished with value: 0.8714074445852408 and parameters: {'kernel': 'poly', 'C': 2.627043362817422, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.40009730601767324, 'degree': 3}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:47,867] Trial 66 finished with value: 0.8712651070058681 and parameters: {'kernel': 'rbf', 'C': 62.71880036912933, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:48,132] Trial 67 finished with value: 0.8789508423455926 and parameters: {'kernel': 'rbf', 'C': 34.18709831924093, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:48,381] Trial 68 finished with value: 0.8804293032720513 and parameters: {'kernel': 'rbf', 'C': 12.740117707103499, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:48,750] Trial 69 finished with value: 0.8068068712470016 and parameters: {'kernel': 'linear', 'C': 130.91858692823504, 'class_weight': None}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:49,002] Trial 70 finished with value: 0.8879972572779947 and parameters: {'kernel': 'rbf', 'C': 4.637648348111229, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:49,249] Trial 71 finished with value: 0.8941653372979593 and parameters: {'kernel': 'rbf', 'C': 6.8236451008686245, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:49,495] Trial 72 finished with value: 0.8838046368550844 and parameters: {'kernel': 'rbf', 'C': 20.52536345554348, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:49,745] Trial 73 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 7.883035742553281, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:50,003] Trial 74 finished with value: 0.8620204950368952 and parameters: {'kernel': 'rbf', 'C': 0.8631743292759342, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:50,295] Trial 75 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 12.296488406640998, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.14014553292454993}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:50,539] Trial 76 finished with value: 0.6370665224022413 and parameters: {'kernel': 'sigmoid', 'C': 3.950974270902005, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6006861600597682}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:50,796] Trial 77 finished with value: 0.8649110973639978 and parameters: {'kernel': 'rbf', 'C': 1.4891818979709317, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:51,035] Trial 78 finished with value: 0.8680634178588001 and parameters: {'kernel': 'poly', 'C': 6.301863009074866, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.16057095398029697, 'degree': 3}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:51,288] Trial 79 finished with value: 0.8611017939223415 and parameters: {'kernel': 'rbf', 'C': 2.556761944450298, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:51,533] Trial 80 finished with value: 0.8830609085246243 and parameters: {'kernel': 'rbf', 'C': 28.32382284183041, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:51,785] Trial 81 finished with value: 0.893834563141168 and parameters: {'kernel': 'rbf', 'C': 8.414406371660826, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.
[I 2025-04-15 13:57:52,035] Trial 82 finished with value: 0.8838046368550844 and parameters: {'kernel': 'rbf', 'C': 18.017018757647364, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 26 with value: 0.8941653372979593.

best_params

{'kernel': 'poly',
 'C': 26.972626232440984,
 'class_weight': 'balanced',
 'coef0': 0.08285683438096408,
 'degree': 2,
 'gamma': 'auto'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                0
target                                                  splashing
model                             SVC_splashing_smotenc_opt-model
holdout_test_f1_macro                                    0.806892
holdout_test_accuracy_balanced                           0.799769
holdout_test_roc_auc                                      0.88966
holdout_test_f1                                          0.868687
holdout_test_accuracy                                    0.826667
cv_test_f1_macro_median                                  0.860788
cv_test_accuracy_balanced_median                         0.873839
cv_test_roc_auc_median                                   0.927245
cv_test_f1_median                                        0.892308
cv_test_accuracy_median                                  0.867925
cv_test_precision_class_0_median                         0.772727
cv_test_recall_class_0_median                            0.894737
cv_test_f1_class_0_median                                0.829268

Model saved in ..\results\models_modelling4\SVC_splashing_smotenc_opt-model

In [7]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True, # Would be False for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']

def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=1400,
    seed=seed,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 14:09:58,403] A new study created in memory with name: model_study
[I 2025-04-15 14:09:58,700] Trial 0 finished with value: 0.7781891103664085 and parameters: {'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 0 with value: 0.7781891103664085.
[I 2025-04-15 14:09:58,991] Trial 1 finished with value: 0.7781891103664085 and parameters: {'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 0 with value: 0.7781891103664085.
[I 2025-04-15 14:09:59,229] Trial 2 finished with value: 0.8121906074737367 and parameters: {'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}. Best is trial 2 with value: 0.8121906074737367.
[I 2025-04-15 14:09:59,500] Trial 3 finished with value: 0.4488692799808544 and parameters: {'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}. Best is trial 2 with value: 0.8121906074737367.
[I 2025-04-15 14:09:59,724] Trial 4 finished with value: 0.8114297563097361 and parameters: {'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}. Best is trial 2 with value: 0.8121906074737367.
[I 2025-04-15 14:09:59,961] Trial 5 finished with value: 0.8324295251341328 and parameters: {'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002273762810253686}. Best is trial 5 with value: 0.8324295251341328.
[I 2025-04-15 14:10:00,181] Trial 6 finished with value: 0.7557910250830118 and parameters: {'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}. Best is trial 5 with value: 0.8324295251341328.
[I 2025-04-15 14:10:00,482] Trial 7 finished with value: 0.8029132054939458 and parameters: {'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8324295251341328.
[I 2025-04-15 14:10:00,897] Trial 8 finished with value: 0.8094476243355403 and parameters: {'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}. Best is trial 5 with value: 0.8324295251341328.
[I 2025-04-15 14:10:01,137] Trial 9 finished with value: 0.8527908521231469 and parameters: {'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}. Best is trial 9 with value: 0.8527908521231469.
[I 2025-04-15 14:10:01,395] Trial 10 finished with value: 0.8566774171077837 and parameters: {'kernel': 'poly', 'C': 3.319977760729009, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}. Best is trial 10 with value: 0.8566774171077837.
[I 2025-04-15 14:10:01,638] Trial 11 finished with value: 0.8675319131935216 and parameters: {'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7731722229182416, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:01,880] Trial 12 finished with value: 0.8508287832099991 and parameters: {'kernel': 'poly', 'C': 1.292746743685531, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:02,104] Trial 13 finished with value: 0.86694497810686 and parameters: {'kernel': 'poly', 'C': 7.919002349981097, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7715705399695951, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:02,335] Trial 14 finished with value: 0.7750603103484919 and parameters: {'kernel': 'poly', 'C': 0.14829568688709063, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4335670893449538, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:02,588] Trial 15 finished with value: 0.6073964749193979 and parameters: {'kernel': 'sigmoid', 'C': 14.149414630497244, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9939907887626555}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:02,841] Trial 16 finished with value: 0.8403978501602237 and parameters: {'kernel': 'poly', 'C': 23.933652285348465, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4538369993080359, 'degree': 5}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:03,091] Trial 17 finished with value: 0.8031911607647204 and parameters: {'kernel': 'poly', 'C': 0.11379002495661215, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7402035056687171, 'degree': 3}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:03,339] Trial 18 finished with value: 0.5032657077289482 and parameters: {'kernel': 'poly', 'C': 0.0011639521730508326, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6373426212165589, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:03,579] Trial 19 finished with value: 0.6611557571825947 and parameters: {'kernel': 'sigmoid', 'C': 33.069560657932584, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.30265277515821437}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:03,823] Trial 20 finished with value: 0.8370107965618997 and parameters: {'kernel': 'poly', 'C': 0.6565938261351317, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8707119702985572, 'degree': 3}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:04,079] Trial 21 finished with value: 0.8566774171077837 and parameters: {'kernel': 'poly', 'C': 3.1781743272608174, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7668134831732524, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:04,320] Trial 22 finished with value: 0.86034402372521 and parameters: {'kernel': 'poly', 'C': 3.4452813986579547, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6220673287226692, 'degree': 2}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:04,574] Trial 23 finished with value: 0.8084915546588357 and parameters: {'kernel': 'poly', 'C': 0.19380971111025908, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6060744628061054, 'degree': 3}. Best is trial 11 with value: 0.8675319131935216.
[I 2025-04-15 14:10:04,831] Trial 24 finished with value: 0.8754760515531876 and parameters: {'kernel': 'poly', 'C': 10.721640591501329, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6387087851251154, 'degree': 2}. Best is trial 24 with value: 0.8754760515531876.
[I 2025-04-15 14:10:05,086] Trial 25 finished with value: 0.8328997488385792 and parameters: {'kernel': 'poly', 'C': 58.92155719746452, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8921293594091383, 'degree': 4}. Best is trial 24 with value: 0.8754760515531876.
[I 2025-04-15 14:10:05,334] Trial 26 finished with value: 0.8904711060825681 and parameters: {'kernel': 'poly', 'C': 11.389804904985334, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.519860428537622, 'degree': 2}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:05,593] Trial 27 finished with value: 0.6459890559893743 and parameters: {'kernel': 'sigmoid', 'C': 1.6873716779928432, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.3128415686093575}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:05,868] Trial 28 finished with value: 0.835688332502739 and parameters: {'kernel': 'rbf', 'C': 582.4554343216083, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:06,109] Trial 29 finished with value: 0.8691428863231884 and parameters: {'kernel': 'rbf', 'C': 11.392242197385725, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:06,355] Trial 30 finished with value: 0.8784502456305479 and parameters: {'kernel': 'rbf', 'C': 15.985810779564975, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:06,594] Trial 31 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 20.635780611989333, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:06,832] Trial 32 finished with value: 0.8437663575868556 and parameters: {'kernel': 'rbf', 'C': 62.84048775490931, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:07,067] Trial 33 finished with value: 0.8644823960995041 and parameters: {'kernel': 'rbf', 'C': 35.880051865081484, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:07,316] Trial 34 finished with value: 0.837909959468085 and parameters: {'kernel': 'rbf', 'C': 130.95480883984632, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:07,553] Trial 35 finished with value: 0.8784502456305479 and parameters: {'kernel': 'rbf', 'C': 17.41797136581807, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:07,800] Trial 36 finished with value: 0.8793226249950324 and parameters: {'kernel': 'rbf', 'C': 26.35959931321514, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:08,040] Trial 37 finished with value: 0.8369813182168632 and parameters: {'kernel': 'rbf', 'C': 243.68078197465442, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:08,276] Trial 38 finished with value: 0.8644823960995041 and parameters: {'kernel': 'rbf', 'C': 32.822899702931686, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:08,528] Trial 39 finished with value: 0.8086819600864751 and parameters: {'kernel': 'rbf', 'C': 0.3252487714042576, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:08,818] Trial 40 finished with value: 0.7881539437573919 and parameters: {'kernel': 'rbf', 'C': 0.025852997924946792, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:09,053] Trial 41 finished with value: 0.8784502456305479 and parameters: {'kernel': 'rbf', 'C': 15.204571585873097, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:09,289] Trial 42 finished with value: 0.837909959468085 and parameters: {'kernel': 'rbf', 'C': 112.16736879249913, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:09,557] Trial 43 finished with value: 0.8460262599663521 and parameters: {'kernel': 'rbf', 'C': 21.34238045002178, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 6.383996108902289}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:09,781] Trial 44 finished with value: 0.8040564171210284 and parameters: {'kernel': 'linear', 'C': 2.244557959445233, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:10,030] Trial 45 finished with value: 0.8523039461309632 and parameters: {'kernel': 'rbf', 'C': 6.941522787616335, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:10,267] Trial 46 finished with value: 0.8437663575868556 and parameters: {'kernel': 'rbf', 'C': 67.17891089263401, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:10,507] Trial 47 finished with value: 0.8369813182168632 and parameters: {'kernel': 'rbf', 'C': 464.59417263633054, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:10,734] Trial 48 finished with value: 0.8040564171210284 and parameters: {'kernel': 'linear', 'C': 4.769834681597323, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:10,990] Trial 49 finished with value: 0.8431981476481906 and parameters: {'kernel': 'rbf', 'C': 274.94701641653836, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 3.5229697635047326}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:11,220] Trial 50 finished with value: 0.7119877133940004 and parameters: {'kernel': 'sigmoid', 'C': 976.5658136500584, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.006115592974872075}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:11,454] Trial 51 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 20.93496173250266, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:11,701] Trial 52 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 20.04481747259336, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:11,952] Trial 53 finished with value: 0.8608549377126591 and parameters: {'kernel': 'rbf', 'C': 38.574174476075235, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:12,197] Trial 54 finished with value: 0.8641326756936828 and parameters: {'kernel': 'rbf', 'C': 10.137385960032393, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:12,448] Trial 55 finished with value: 0.8257156163632848 and parameters: {'kernel': 'rbf', 'C': 0.8539267365887504, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:12,774] Trial 56 finished with value: 0.8094476243355403 and parameters: {'kernel': 'linear', 'C': 158.06060406420514, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:13,013] Trial 57 finished with value: 0.8838950790889698 and parameters: {'kernel': 'rbf', 'C': 22.900357691032074, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.08318037758997444}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:13,259] Trial 58 finished with value: 0.8531345272383586 and parameters: {'kernel': 'rbf', 'C': 5.046050761548509, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.07814174800097899}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:13,496] Trial 59 finished with value: 0.6736313587681482 and parameters: {'kernel': 'sigmoid', 'C': 52.235899119136704, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.3215973159621764, 'coef0': 0.2812178703760208}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:13,759] Trial 60 finished with value: 0.7554298948962778 and parameters: {'kernel': 'rbf', 'C': 2.1813560044785434, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.006089724538164114}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:14,040] Trial 61 finished with value: 0.7363631881531082 and parameters: {'kernel': 'rbf', 'C': 20.346518526507765, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00011657876615611406}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:14,292] Trial 62 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 24.641827296392634, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:14,525] Trial 63 finished with value: 0.837909959468085 and parameters: {'kernel': 'rbf', 'C': 109.80257472435486, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:14,762] Trial 64 finished with value: 0.8695963297848665 and parameters: {'kernel': 'rbf', 'C': 28.982694904803285, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:15,002] Trial 65 finished with value: 0.8551750367921448 and parameters: {'kernel': 'rbf', 'C': 10.187446159932588, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.5666962544754532}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:15,235] Trial 66 finished with value: 0.8075422755249196 and parameters: {'kernel': 'linear', 'C': 7.702880550601442, 'class_weight': 'balanced'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:15,469] Trial 67 finished with value: 0.8446949988380774 and parameters: {'kernel': 'rbf', 'C': 48.427547878972064, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:15,697] Trial 68 finished with value: 0.811893811534344 and parameters: {'kernel': 'poly', 'C': 3.358997721190604, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.17753271833162731, 'degree': 5}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:15,924] Trial 69 finished with value: 0.6414974997312717 and parameters: {'kernel': 'sigmoid', 'C': 97.17179437236814, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.48949001736781866}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:16,155] Trial 70 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 20.48212068119214, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:16,400] Trial 71 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 23.519642706683015, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:16,646] Trial 72 finished with value: 0.8691428863231884 and parameters: {'kernel': 'rbf', 'C': 13.961928634758452, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:16,882] Trial 73 finished with value: 0.8437663575868556 and parameters: {'kernel': 'rbf', 'C': 78.65953845740057, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:17,125] Trial 74 finished with value: 0.887191637702755 and parameters: {'kernel': 'rbf', 'C': 23.71601286292721, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:17,391] Trial 75 finished with value: 0.8331938748874246 and parameters: {'kernel': 'rbf', 'C': 173.6943941477145, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:17,670] Trial 76 finished with value: 0.834757031341023 and parameters: {'kernel': 'poly', 'C': 49.4980473776612, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.36888023851434193, 'degree': 4}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:17,922] Trial 77 finished with value: 0.8479001321895895 and parameters: {'kernel': 'rbf', 'C': 5.295258541518984, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.
[I 2025-04-15 14:10:18,158] Trial 78 finished with value: 0.8644823960995041 and parameters: {'kernel': 'rbf', 'C': 36.44520448376019, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 26 with value: 0.8904711060825681.

best_params

{'kernel': 'poly',
 'C': 27.620566418088167,
 'class_weight': 'balanced',
 'coef0': 0.48744430071806377,
 'degree': 2,
 'gamma': 'auto'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                       0
target                                                  no_fragmentation
model                             SVC_no_fragmentation_smotenc_opt-model
holdout_test_f1_macro                                           0.863636
holdout_test_accuracy_balanced                                  0.863636
holdout_test_roc_auc                                            0.919091
holdout_test_f1                                                      0.8
holdout_test_accuracy                                           0.893333
cv_test_f1_macro_median                                          0.90293
cv_test_accuracy_balanced_median                                 0.90293
cv_test_roc_auc_median                                          0.956044
cv_test_f1_median                                               0.857143
cv_test_accuracy_median                                         0.924528
cv_test_precision_class_0_median                                0.971429
cv_test_recall_class_0_median                                   0.897436
cv_test_f1_class_0_median                                       0.945946

Model saved in ..\results\models_modelling4\SVC_no_fragmentation_smotenc_opt-model