Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

base_estimator_params - redundant thing in logging! - SOLVED!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 1500 # checked with 15 and 100

save_model_and_metrics = True
metrics_file = "metrics_modelling4_3.2-smotenc_with_ensembles.xlsx"

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    base_estimator:Type[BaseEstimator]=None,
    base_estimator_params:dict=None,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    base_estimator_params_list:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    
    estimator_params = estimator_params.copy()
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    # Process base_estimator_params
    if base_estimator_params_list:
        best_params_base_estimator = {}
        for param in base_estimator_params_list:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params_base_estimator[param] = best_params.pop(key)
        print('best_params for main estimator')
        display(best_params)
        print('best_params for base estimator')
        display(best_params_base_estimator)
        if base_estimator_params is None:
            base_estimator_params = best_params_base_estimator
        else:
            base_estimator_params = base_estimator_params.copy()
            base_estimator_params.update(best_params_base_estimator)
    else:
        print('best_params')
        display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params, # Would be None if base_estimator_params_list is not provided
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# CatBoost

In [6]:
estimator = CatBoostClassifier
target = 'splashing'
# TODO: Try with GPU!
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

def catboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "iterations": trial.suggest_int("iterations", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 3, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "grow_policy": trial.suggest_categorical("grow_policy", ["SymmetricTree", "Depthwise", "Lossguide"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"]),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", ["Balanced", "SqrtBalanced", None]),
    }
    
    if suggested_estimator_params['bootstrap_type'] == 'Bernoulli':
        suggested_estimator_params['subsample'] = trial.suggest_float(
            "subsample", 0.5, 1.0
        )
        
    if suggested_estimator_params['bootstrap_type'] == 'Bayesian':
        suggested_estimator_params['bagging_temperature'] = (
            trial.suggest_float("bagging_temperature", 0.0, 1.0)
        )

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:21:38,366] A new study created in memory with name: model_study
[I 2025-04-15 20:21:48,265] Trial 0 finished with value: 0.8979727970346036 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:21:51,946] Trial 1 finished with value: 0.8763002839921522 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:22:02,028] Trial 2 finished with value: 0.8648043986116568 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:22:05,810] Trial 3 finished with value: 0.8896022628933086 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:22:07,535] Trial 4 finished with value: 0.8975527065729464 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:22:10,803] Trial 5 finished with value: 0.8894338302370012 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 0 with value: 0.8979727970346036.
[I 2025-04-15 20:22:12,504] Trial 6 finished with value: 0.9005497204584492 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 6 with value: 0.9005497204584492.
[I 2025-04-15 20:22:22,274] Trial 7 finished with value: 0.888786443162337 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 6 with value: 0.9005497204584492.
[I 2025-04-15 20:22:37,797] Trial 8 finished with value: 0.8721347469772792 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 6 with value: 0.9005497204584492.
[I 2025-04-15 20:22:38,937] Trial 9 finished with value: 0.870553167572891 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 6 with value: 0.9005497204584492.
[I 2025-04-15 20:22:41,324] Trial 10 finished with value: 0.9045212212844851 and parameters: {'iterations': 652, 'learning_rate': 0.03357104002950685, 'depth': 5, 'l2_leaf_reg': 0.0011799062523159302, 'random_strength': 0.5025312176747964, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.06569066558371356}. Best is trial 10 with value: 0.9045212212844851.
[I 2025-04-15 20:22:43,845] Trial 11 finished with value: 0.8975601028521005 and parameters: {'iterations': 684, 'learning_rate': 0.041036604073704505, 'depth': 5, 'l2_leaf_reg': 0.0013038995056776346, 'random_strength': 0.4818963296633298, 'border_count': 156, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.04526040455071449}. Best is trial 10 with value: 0.9045212212844851.
[I 2025-04-15 20:22:46,321] Trial 12 finished with value: 0.8937521962539622 and parameters: {'iterations': 682, 'learning_rate': 0.05105823178669681, 'depth': 5, 'l2_leaf_reg': 0.004943615564347662, 'random_strength': 0.5396201068027978, 'border_count': 123, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.12076466504046209}. Best is trial 10 with value: 0.9045212212844851.
[I 2025-04-15 20:22:50,218] Trial 13 finished with value: 0.9006299155458887 and parameters: {'iterations': 1000, 'learning_rate': 0.012595613571747825, 'depth': 5, 'l2_leaf_reg': 0.001391644503957576, 'random_strength': 0.40095596968204394, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.3466000885357207}. Best is trial 10 with value: 0.9045212212844851.
[I 2025-04-15 20:22:52,810] Trial 14 finished with value: 0.8878440830427736 and parameters: {'iterations': 1000, 'learning_rate': 0.01109910491075193, 'depth': 3, 'l2_leaf_reg': 0.0068054850960643145, 'random_strength': 0.3348250458011287, 'border_count': 185, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.45158061713159064}. Best is trial 10 with value: 0.9045212212844851.

best_params

{'iterations': 652,
 'learning_rate': 0.03357104002950685,
 'depth': 5,
 'l2_leaf_reg': 0.0011799062523159302,
 'random_strength': 0.5025312176747964,
 'border_count': 153,
 'grow_policy': 'SymmetricTree',
 'bootstrap_type': 'Bayesian',
 'auto_class_weights': 'Balanced',
 'bagging_temperature': 0.06569066558371356}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                               0
target                                                                 splashing
model                             CatBoostClassifier_splashing_smotenc_opt-model
holdout_test_f1_macro                                                   0.882261
holdout_test_accuracy_balanced                                          0.876157
holdout_test_roc_auc                                                    0.962191
holdout_test_f1                                                         0.918367
holdout_test_accuracy                                                   0.893333
cv_test_f1_macro_median                                                 0.896201
cv_test_accuracy_balanced_median                                        0.900155
cv_test_roc_auc_median                                                  0.965944
cv_test_f1_median                                                       0.925373
cv_test_accuracy_median                                                  0.90566
cv_test_precision_class_0_median                                            0.85
cv_test_recall_class_0_median                                           0.894737
cv_test_f1_class_0_median                                               0.864865

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smotenc_opt-model

In [7]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:22:55,981] A new study created in memory with name: model_study
[I 2025-04-15 20:23:05,310] Trial 0 finished with value: 0.866948705602559 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:08,666] Trial 1 finished with value: 0.8480628015076063 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:18,222] Trial 2 finished with value: 0.8305968265327002 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:21,968] Trial 3 finished with value: 0.847410028941123 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:23,666] Trial 4 finished with value: 0.8600538819360851 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:26,883] Trial 5 finished with value: 0.8460356862205385 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:28,678] Trial 6 finished with value: 0.8612503109174963 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 0 with value: 0.866948705602559.
[I 2025-04-15 20:23:37,871] Trial 7 finished with value: 0.8680410235323646 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:23:52,786] Trial 8 finished with value: 0.8404324090285888 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:23:53,870] Trial 9 finished with value: 0.8384379681597414 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:23:55,321] Trial 10 finished with value: 0.8566162612057528 and parameters: {'iterations': 70, 'learning_rate': 0.07767314798840616, 'depth': 10, 'l2_leaf_reg': 0.7803665684896557, 'random_strength': 0.9834247540824036, 'border_count': 226, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.012311169564937496}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:24:15,242] Trial 11 finished with value: 0.8276756831571543 and parameters: {'iterations': 626, 'learning_rate': 0.2202345038276801, 'depth': 9, 'l2_leaf_reg': 0.870381435733321, 'random_strength': 0.4818963296633298, 'border_count': 178, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:24:30,602] Trial 12 finished with value: 0.8327495319674411 and parameters: {'iterations': 379, 'learning_rate': 0.07296579300249419, 'depth': 9, 'l2_leaf_reg': 0.2730834958148281, 'random_strength': 0.4960413121697144, 'border_count': 204, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:24:49,712] Trial 13 finished with value: 0.851951095252642 and parameters: {'iterations': 684, 'learning_rate': 0.291683220689374, 'depth': 9, 'l2_leaf_reg': 1.5790504900294149, 'random_strength': 0.63669592790689, 'border_count': 123, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 7 with value: 0.8680410235323646.
[I 2025-04-15 20:25:11,300] Trial 14 finished with value: 0.8509231059652941 and parameters: {'iterations': 968, 'learning_rate': 0.056577951807451586, 'depth': 8, 'l2_leaf_reg': 0.18449491053356515, 'random_strength': 0.2893853823038997, 'border_count': 151, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 7 with value: 0.8680410235323646.

best_params

{'iterations': 203,
 'learning_rate': 0.20089716820180242,
 'depth': 9,
 'l2_leaf_reg': 0.34167643418329696,
 'random_strength': 0.8714605901877177,
 'border_count': 212,
 'grow_policy': 'Depthwise',
 'bootstrap_type': 'Bernoulli',
 'auto_class_weights': None,
 'subsample': 0.9090073829612466}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.965909
holdout_test_accuracy_balanced                                             0.965909
holdout_test_roc_auc                                                       0.993636
holdout_test_f1                                                                0.95
holdout_test_accuracy                                                      0.973333
cv_test_f1_macro_median                                                    0.881326
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                     0.958974
cv_test_f1_median                                                          0.827586
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smotenc_opt-model

# XGBoost

In [8]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {
    'n_jobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 132/240 # For splashing

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [scale_pos_weight, 1.0]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:25:19,584] A new study created in memory with name: model_study
[I 2025-04-15 20:25:19,815] Trial 0 finished with value: 0.7486105055440758 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 0.55}. Best is trial 0 with value: 0.7486105055440758.
[I 2025-04-15 20:25:20,253] Trial 1 finished with value: 0.833262255581093 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:20,478] Trial 2 finished with value: 0.7514365300108291 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:20,892] Trial 3 finished with value: 0.8296058174573174 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:21,096] Trial 4 finished with value: 0.741766023327011 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:21,631] Trial 5 finished with value: 0.8108321448335556 and parameters: {'n_estimators': 926, 'learning_rate': 0.0016565580440884786, 'max_depth': 2, 'min_child_weight': 1, 'gamma': 1.6266516538163218, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:21,792] Trial 6 finished with value: 0.7568007455916567 and parameters: {'n_estimators': 184, 'learning_rate': 0.09708210658008556, 'max_depth': 1, 'min_child_weight': 20, 'gamma': 3.861223846483287, 'subsample': 0.5993578407670862, 'colsample_bytree': 0.5027610585618012, 'reg_alpha': 1.8274508859816028, 'reg_lambda': 0.6720930050156113, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:21,940] Trial 7 finished with value: 0.26121337827326935 and parameters: {'n_estimators': 120, 'learning_rate': 0.007726148927746463, 'max_depth': 2, 'min_child_weight': 18, 'gamma': 3.1164906341377896, 'subsample': 0.6654490124263246, 'colsample_bytree': 0.5317791751430119, 'reg_alpha': 0.017535949529764425, 'reg_lambda': 0.01998634077852888, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:22,315] Trial 8 finished with value: 0.7449923277849271 and parameters: {'n_estimators': 893, 'learning_rate': 0.014782014634883782, 'max_depth': 2, 'min_child_weight': 15, 'gamma': 3.803925243084487, 'subsample': 0.7806385987847482, 'colsample_bytree': 0.8854835899772805, 'reg_alpha': 0.09444574254983566, 'reg_lambda': 0.12329098365270515, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:22,510] Trial 9 finished with value: 0.26121337827326935 and parameters: {'n_estimators': 152, 'learning_rate': 0.0011963380170058652, 'max_depth': 7, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.833262255581093.
[I 2025-04-15 20:25:22,924] Trial 10 finished with value: 0.8579729250808625 and parameters: {'n_estimators': 671, 'learning_rate': 0.05406128459617322, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.658087572237882, 'subsample': 0.5193625999805915, 'colsample_bytree': 0.8271882613853767, 'reg_alpha': 0.31356971313563664, 'reg_lambda': 0.0016185820655420032, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8579729250808625.
[I 2025-04-15 20:25:23,346] Trial 11 finished with value: 0.8474572609129839 and parameters: {'n_estimators': 687, 'learning_rate': 0.05326260658481708, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.7125799686887835, 'subsample': 0.5062719837848048, 'colsample_bytree': 0.8201950992447397, 'reg_alpha': 0.30044011198977605, 'reg_lambda': 0.0010951175441624634, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8579729250808625.
[I 2025-04-15 20:25:23,761] Trial 12 finished with value: 0.8586349951304408 and parameters: {'n_estimators': 671, 'learning_rate': 0.05011092496777477, 'max_depth': 5, 'min_child_weight': 1, 'gamma': 1.7381671524829143, 'subsample': 0.516792942467236, 'colsample_bytree': 0.8687726793294727, 'reg_alpha': 0.37947060877945143, 'reg_lambda': 0.0014775862080349449, 'scale_pos_weight': 1.0}. Best is trial 12 with value: 0.8586349951304408.
[I 2025-04-15 20:25:24,152] Trial 13 finished with value: 0.8349817072110018 and parameters: {'n_estimators': 672, 'learning_rate': 0.025390067826799, 'max_depth': 6, 'min_child_weight': 5, 'gamma': 1.8419430354275477, 'subsample': 0.5100656723353845, 'colsample_bytree': 0.9002256231167883, 'reg_alpha': 0.4893501922734305, 'reg_lambda': 0.0011534279870999457, 'scale_pos_weight': 1.0}. Best is trial 12 with value: 0.8586349951304408.
[I 2025-04-15 20:25:24,504] Trial 14 finished with value: 0.7966174507368219 and parameters: {'n_estimators': 615, 'learning_rate': 0.033104775910188546, 'max_depth': 6, 'min_child_weight': 3, 'gamma': 1.9780137919149408, 'subsample': 0.5073279768645609, 'colsample_bytree': 0.8933139358849993, 'reg_alpha': 7.5349332296701546, 'reg_lambda': 0.0041312908860572485, 'scale_pos_weight': 1.0}. Best is trial 12 with value: 0.8586349951304408.

best_params

{'n_estimators': 671,
 'learning_rate': 0.05011092496777477,
 'max_depth': 5,
 'min_child_weight': 1,
 'gamma': 1.7381671524829143,
 'subsample': 0.516792942467236,
 'colsample_bytree': 0.8687726793294727,
 'reg_alpha': 0.37947060877945143,
 'reg_lambda': 0.0014775862080349449,
 'scale_pos_weight': 1.0}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                          0
target                                                            splashing
model                             XGBClassifier_splashing_smotenc_opt-model
holdout_test_f1_macro                                                0.8333
holdout_test_accuracy_balanced                                     0.820602
holdout_test_roc_auc                                               0.915123
holdout_test_f1                                                    0.891089
holdout_test_accuracy                                              0.853333
cv_test_f1_macro_median                                             0.82623
cv_test_accuracy_balanced_median                                   0.856037
cv_test_roc_auc_median                                              0.95356
cv_test_f1_median                                                  0.865672
cv_test_accuracy_median                                            0.830189
cv_test_precision_class_0_median                                   0.714286
cv_test_recall_class_0_median                                      0.842105
cv_test_f1_class_0_median                                               0.8

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smotenc_opt-model

In [9]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {
    'n_jobs': 1,
}
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 273/99 # For no_fragmentation

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [1.0, scale_pos_weight]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:25:25,264] A new study created in memory with name: model_study
[I 2025-04-15 20:25:25,503] Trial 0 finished with value: 0.8114114872452022 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 1.0}. Best is trial 0 with value: 0.8114114872452022.
[I 2025-04-15 20:25:25,946] Trial 1 finished with value: 0.8538290905215415 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:26,187] Trial 2 finished with value: 0.7799626280334158 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:26,614] Trial 3 finished with value: 0.8425850252417876 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:26,822] Trial 4 finished with value: 0.8088766250091027 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:27,361] Trial 5 finished with value: 0.7403476936616957 and parameters: {'n_estimators': 926, 'learning_rate': 0.0016565580440884786, 'max_depth': 2, 'min_child_weight': 1, 'gamma': 1.6266516538163218, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:27,522] Trial 6 finished with value: 0.7063114263300629 and parameters: {'n_estimators': 184, 'learning_rate': 0.09708210658008556, 'max_depth': 1, 'min_child_weight': 20, 'gamma': 3.861223846483287, 'subsample': 0.5993578407670862, 'colsample_bytree': 0.5027610585618012, 'reg_alpha': 1.8274508859816028, 'reg_lambda': 0.6720930050156113, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:27,669] Trial 7 finished with value: 0.7878131238359639 and parameters: {'n_estimators': 120, 'learning_rate': 0.007726148927746463, 'max_depth': 2, 'min_child_weight': 18, 'gamma': 3.1164906341377896, 'subsample': 0.6654490124263246, 'colsample_bytree': 0.5317791751430119, 'reg_alpha': 0.017535949529764425, 'reg_lambda': 0.01998634077852888, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:28,117] Trial 8 finished with value: 0.8043803075940398 and parameters: {'n_estimators': 893, 'learning_rate': 0.014782014634883782, 'max_depth': 2, 'min_child_weight': 15, 'gamma': 3.803925243084487, 'subsample': 0.7806385987847482, 'colsample_bytree': 0.8854835899772805, 'reg_alpha': 0.09444574254983566, 'reg_lambda': 0.12329098365270515, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:28,320] Trial 9 finished with value: 0.81763198119207 and parameters: {'n_estimators': 152, 'learning_rate': 0.0011963380170058652, 'max_depth': 7, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:28,734] Trial 10 finished with value: 0.8129977387589867 and parameters: {'n_estimators': 671, 'learning_rate': 0.05406128459617322, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.658087572237882, 'subsample': 0.5193625999805915, 'colsample_bytree': 0.8271882613853767, 'reg_alpha': 0.31356971313563664, 'reg_lambda': 0.0016185820655420032, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:29,126] Trial 11 finished with value: 0.8266555345710184 and parameters: {'n_estimators': 733, 'learning_rate': 0.2479368227400565, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.11239512174811128, 'subsample': 0.8773233048862263, 'colsample_bytree': 0.713556152816666, 'reg_alpha': 0.00421149961829754, 'reg_lambda': 0.007300358083644766, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:29,628] Trial 12 finished with value: 0.8329853861556892 and parameters: {'n_estimators': 984, 'learning_rate': 0.11749951817818961, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.09937908421467717, 'subsample': 0.8690956945751528, 'colsample_bytree': 0.7071019514729291, 'reg_alpha': 0.008101324842116031, 'reg_lambda': 0.023359795726456155, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:29,992] Trial 13 finished with value: 0.831090210790239 and parameters: {'n_estimators': 745, 'learning_rate': 0.27454073293051257, 'max_depth': 7, 'min_child_weight': 8, 'gamma': 1.5611746796105823, 'subsample': 0.8223368426340427, 'colsample_bytree': 0.8782120024359525, 'reg_alpha': 0.0011103309681743958, 'reg_lambda': 0.0029292771595525544, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8538290905215415.
[I 2025-04-15 20:25:30,383] Trial 14 finished with value: 0.8245587052722649 and parameters: {'n_estimators': 612, 'learning_rate': 0.04005201416577278, 'max_depth': 8, 'min_child_weight': 4, 'gamma': 0.7446888008874483, 'subsample': 0.967241078658621, 'colsample_bytree': 0.6765922688439263, 'reg_alpha': 0.020066557429341072, 'reg_lambda': 0.042533224253568314, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8538290905215415.

best_params

{'n_estimators': 972,
 'learning_rate': 0.11536162338241392,
 'max_depth': 3,
 'min_child_weight': 4,
 'gamma': 0.9170225492671691,
 'subsample': 0.6521211214797689,
 'colsample_bytree': 0.762378215816119,
 'reg_alpha': 0.05342937261279776,
 'reg_lambda': 0.014618962793704957,
 'scale_pos_weight': 1.0}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                 0
target                                                            no_fragmentation
model                             XGBClassifier_no_fragmentation_smotenc_opt-model
holdout_test_f1_macro                                                     0.867725
holdout_test_accuracy_balanced                                            0.879545
holdout_test_roc_auc                                                      0.967273
holdout_test_f1                                                           0.809524
holdout_test_accuracy                                                     0.893333
cv_test_f1_macro_median                                                    0.90293
cv_test_accuracy_balanced_median                                          0.907692
cv_test_roc_auc_median                                                    0.957875
cv_test_f1_median                                                         0.857143
cv_test_accuracy_median                                                   0.924528
cv_test_precision_class_0_median                                          0.948718
cv_test_recall_class_0_median                                             0.948718
cv_test_f1_class_0_median                                                 0.948718

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smotenc_opt-model

# AdaBoost

In [10]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

def adaboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_base_estimator_params = {
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20), # Closed to min_child_weight
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }
    base_estimator_params = update_estimator_params(
        ml_pipe,
        suggested_base_estimator_params,
        estimator_type='base',
    )

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        base_estimator=ml_pipe._pipeline_params['base_estimator'],
        estimator_params=estimator_params,
        base_estimator_params=base_estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:25:31,179] A new study created in memory with name: model_study
[I 2025-04-15 20:25:32,460] Trial 0 finished with value: 0.8507160628845644 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.8507160628845644.
[I 2025-04-15 20:25:38,496] Trial 1 finished with value: 0.8969014813437421 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:40,155] Trial 2 finished with value: 0.879173993077129 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:41,597] Trial 3 finished with value: 0.865621889505049 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:47,604] Trial 4 finished with value: 0.8832214289556648 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:48,727] Trial 5 finished with value: 0.8955613707406654 and parameters: {'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': None, 'n_estimators': 166, 'learning_rate': 0.016850517723339092}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:51,088] Trial 6 finished with value: 0.8389722422841027 and parameters: {'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 6, 'class_weight': None, 'n_estimators': 544, 'learning_rate': 0.02260828676373495}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:54,077] Trial 7 finished with value: 0.8884950091661029 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 16, 'class_weight': None, 'n_estimators': 618, 'learning_rate': 0.19212959255386391}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:55,703] Trial 8 finished with value: 0.8414585051604833 and parameters: {'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'class_weight': 'balanced', 'n_estimators': 308, 'learning_rate': 0.11294923622078903}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:25:56,609] Trial 9 finished with value: 0.8957182247799379 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 120, 'learning_rate': 0.27838036931305016}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:26:02,816] Trial 10 finished with value: 0.8934102776290975 and parameters: {'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 20, 'class_weight': 'balanced', 'n_estimators': 912, 'learning_rate': 0.0014588903991150821}. Best is trial 1 with value: 0.8969014813437421.
[I 2025-04-15 20:26:08,293] Trial 11 finished with value: 0.9072111804996247 and parameters: {'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 736, 'learning_rate': 0.005645483834891396}. Best is trial 11 with value: 0.9072111804996247.
[I 2025-04-15 20:26:13,592] Trial 12 finished with value: 0.8678390385938437 and parameters: {'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 18, 'class_weight': 'balanced', 'n_estimators': 752, 'learning_rate': 0.0044146113011532505}. Best is trial 11 with value: 0.9072111804996247.
[I 2025-04-15 20:26:19,461] Trial 13 finished with value: 0.9012149763471237 and parameters: {'max_depth': 7, 'min_samples_split': 15, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 771, 'learning_rate': 0.004785557749423611}. Best is trial 11 with value: 0.9072111804996247.
[I 2025-04-15 20:26:24,683] Trial 14 finished with value: 0.8794641887648925 and parameters: {'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 10, 'class_weight': 'balanced', 'n_estimators': 693, 'learning_rate': 0.007033818418048322}. Best is trial 11 with value: 0.9072111804996247.

best_params for main estimator

{'n_estimators': 736, 'learning_rate': 0.005645483834891396}

best_params for base estimator

{'max_depth': 6,
 'min_samples_split': 12,
 'min_samples_leaf': 11,
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                               0
target                                                                 splashing
model                             AdaBoostClassifier_splashing_smotenc_opt-model
holdout_test_f1_macro                                                   0.842105
holdout_test_accuracy_balanced                                          0.844907
holdout_test_roc_auc                                                    0.911265
holdout_test_f1                                                         0.884211
holdout_test_accuracy                                                   0.853333
cv_test_f1_macro_median                                                  0.87381
cv_test_accuracy_balanced_median                                        0.865325
cv_test_roc_auc_median                                                  0.948916
cv_test_f1_median                                                       0.914286
cv_test_accuracy_median                                                 0.886792
cv_test_precision_class_0_median                                            0.85
cv_test_recall_class_0_median                                           0.842105
cv_test_f1_class_0_median                                               0.833333

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smotenc_opt-model

In [11]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:26:33,185] A new study created in memory with name: model_study
[I 2025-04-15 20:26:34,622] Trial 0 finished with value: 0.8345971796237147 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.8345971796237147.
[I 2025-04-15 20:26:41,372] Trial 1 finished with value: 0.862339213823628 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:43,189] Trial 2 finished with value: 0.8485114965440316 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:44,709] Trial 3 finished with value: 0.8564648771472368 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:51,448] Trial 4 finished with value: 0.8392752887042608 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:52,681] Trial 5 finished with value: 0.8151305147722573 and parameters: {'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': None, 'n_estimators': 166, 'learning_rate': 0.016850517723339092}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:55,100] Trial 6 finished with value: 0.8242166084862982 and parameters: {'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 6, 'class_weight': None, 'n_estimators': 544, 'learning_rate': 0.02260828676373495}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:58,229] Trial 7 finished with value: 0.8323149200436925 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 16, 'class_weight': None, 'n_estimators': 618, 'learning_rate': 0.19212959255386391}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:26:59,895] Trial 8 finished with value: 0.8067653651331235 and parameters: {'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'class_weight': 'balanced', 'n_estimators': 308, 'learning_rate': 0.11294923622078903}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:00,843] Trial 9 finished with value: 0.8360057035242698 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 120, 'learning_rate': 0.27838036931305016}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:07,879] Trial 10 finished with value: 0.8424209758472304 and parameters: {'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 20, 'class_weight': 'balanced', 'n_estimators': 912, 'learning_rate': 0.0014588903991150821}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:14,427] Trial 11 finished with value: 0.8271251131461396 and parameters: {'max_depth': 8, 'min_samples_split': 12, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 736, 'learning_rate': 0.005645483834891396}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:17,872] Trial 12 finished with value: 0.8502086382371409 and parameters: {'max_depth': 7, 'min_samples_split': 14, 'min_samples_leaf': 20, 'class_weight': 'balanced', 'n_estimators': 392, 'learning_rate': 0.005709158341226741}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:24,298] Trial 13 finished with value: 0.8296036866475881 and parameters: {'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 783, 'learning_rate': 0.004785557749423611}. Best is trial 1 with value: 0.862339213823628.
[I 2025-04-15 20:27:30,396] Trial 14 finished with value: 0.8633466044595222 and parameters: {'max_depth': 6, 'min_samples_split': 16, 'min_samples_leaf': 16, 'class_weight': 'balanced', 'n_estimators': 691, 'learning_rate': 0.044962275651963673}. Best is trial 14 with value: 0.8633466044595222.

best_params for main estimator

{'n_estimators': 691, 'learning_rate': 0.044962275651963673}

best_params for base estimator

{'max_depth': 6,
 'min_samples_split': 16,
 'min_samples_leaf': 16,
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.890351
holdout_test_accuracy_balanced                                             0.865909
holdout_test_roc_auc                                                       0.989091
holdout_test_f1                                                            0.833333
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.876543
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.940171
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.938272

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smotenc_opt-model

# Random Forest

In [12]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def rf_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int('min_samples_leaf', 1, 20),
        "max_features": trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        "bootstrap": trial.suggest_categorical('bootstrap', [True, False]),
        "criterion": trial.suggest_categorical('criterion', ['gini', 'entropy']),
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:27:39,801] A new study created in memory with name: model_study
[I 2025-04-15 20:27:41,652] Trial 0 finished with value: 0.8487431694259776 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8487431694259776.
[I 2025-04-15 20:27:42,829] Trial 1 finished with value: 0.8636788686102108 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8636788686102108.
[I 2025-04-15 20:27:43,917] Trial 2 finished with value: 0.8721794555153125 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:27:45,702] Trial 3 finished with value: 0.8608910888356153 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:27:49,327] Trial 4 finished with value: 0.8549882618733932 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:27:51,580] Trial 5 finished with value: 0.8637517780080088 and parameters: {'n_estimators': 566, 'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:27:53,068] Trial 6 finished with value: 0.8675014893155176 and parameters: {'n_estimators': 390, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:27:56,023] Trial 7 finished with value: 0.8592144316168042 and parameters: {'n_estimators': 728, 'max_depth': 16, 'min_samples_split': 12, 'min_samples_leaf': 16, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:28:00,916] Trial 8 finished with value: 0.8425011442832364 and parameters: {'n_estimators': 913, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': None, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:28:01,857] Trial 9 finished with value: 0.8590627954980954 and parameters: {'n_estimators': 227, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:28:02,405] Trial 10 finished with value: 0.8719229311156808 and parameters: {'n_estimators': 72, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:28:02,960] Trial 11 finished with value: 0.871335324278074 and parameters: {'n_estimators': 86, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8721794555153125.
[I 2025-04-15 20:28:03,426] Trial 12 finished with value: 0.8752982646987137 and parameters: {'n_estimators': 61, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 12 with value: 0.8752982646987137.
[I 2025-04-15 20:28:04,695] Trial 13 finished with value: 0.8708988028614283 and parameters: {'n_estimators': 223, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 12 with value: 0.8752982646987137.
[I 2025-04-15 20:28:05,201] Trial 14 finished with value: 0.8709924845438106 and parameters: {'n_estimators': 74, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 12 with value: 0.8752982646987137.

best_params

{'n_estimators': 61,
 'max_depth': 11,
 'min_samples_split': 7,
 'min_samples_leaf': 6,
 'max_features': None,
 'bootstrap': True,
 'criterion': 'gini',
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smotenc_opt-m...
holdout_test_f1_macro                                                      0.813397
holdout_test_accuracy_balanced                                             0.815972
holdout_test_roc_auc                                                        0.89892
holdout_test_f1                                                            0.863158
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.858018
cv_test_accuracy_balanced_median                                           0.862229
cv_test_roc_auc_median                                                     0.942857
cv_test_f1_median                                                          0.892308
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.772727
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.820513

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smotenc_opt-model

In [13]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:28:06,037] A new study created in memory with name: model_study
[I 2025-04-15 20:28:07,871] Trial 0 finished with value: 0.8182302909663546 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8182302909663546.
[I 2025-04-15 20:28:09,066] Trial 1 finished with value: 0.8229463755470151 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8229463755470151.
[I 2025-04-15 20:28:10,187] Trial 2 finished with value: 0.8347131366800328 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:11,996] Trial 3 finished with value: 0.8248659583527521 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:15,856] Trial 4 finished with value: 0.8177364999057934 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:18,087] Trial 5 finished with value: 0.8334883767868304 and parameters: {'n_estimators': 566, 'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:19,647] Trial 6 finished with value: 0.8235944410969539 and parameters: {'n_estimators': 390, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:22,884] Trial 7 finished with value: 0.8182302909663546 and parameters: {'n_estimators': 728, 'max_depth': 16, 'min_samples_split': 12, 'min_samples_leaf': 16, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:28,303] Trial 8 finished with value: 0.7744299884519561 and parameters: {'n_estimators': 913, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': None, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:29,337] Trial 9 finished with value: 0.823210354467381 and parameters: {'n_estimators': 227, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:29,911] Trial 10 finished with value: 0.8190536375459884 and parameters: {'n_estimators': 72, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:32,836] Trial 11 finished with value: 0.824473624948953 and parameters: {'n_estimators': 646, 'max_depth': 9, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:35,735] Trial 12 finished with value: 0.8307363848526581 and parameters: {'n_estimators': 627, 'max_depth': 14, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:36,891] Trial 13 finished with value: 0.8259838222083467 and parameters: {'n_estimators': 247, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8347131366800328.
[I 2025-04-15 20:28:37,481] Trial 14 finished with value: 0.8286426552619327 and parameters: {'n_estimators': 74, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 3, 'max_features': None, 'bootstrap': True, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8347131366800328.

best_params

{'n_estimators': 239,
 'max_depth': 11,
 'min_samples_split': 13,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'bootstrap': False,
 'criterion': 'gini',
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.918496
holdout_test_accuracy_balanced                                             0.938636
holdout_test_roc_auc                                                       0.981818
holdout_test_f1                                                            0.883721
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.929915
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smotenc_opt-model

# LightGBM

In [14]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def lgbm_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        # "max_depth": trial.suggest_int("max_depth", 1, 10),
        "num_leaves": trial.suggest_int("num_leaves", 4, 512), # more important than max_depth
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "min_split_gain": trial.suggest_float("gamma", 0., 5.), # gamma from XGBoost
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0), # colsample_bytree from XGBoost
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "boosting_type": trial.suggest_categorical("boosting_type", ["gbdt", "dart"]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:28:39,615] A new study created in memory with name: model_study
[I 2025-04-15 20:28:46,558] Trial 0 finished with value: 0.866358020058759 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:28:49,991] Trial 1 finished with value: 0.7736113542816143 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:28:57,511] Trial 2 finished with value: 0.8467891039830976 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:28:57,904] Trial 3 finished with value: 0.7544429045246154 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:00,209] Trial 4 finished with value: 0.815434562759317 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:04,786] Trial 5 finished with value: 0.804671404581122 and parameters: {'n_estimators': 784, 'learning_rate': 0.0031062960067335336, 'num_leaves': 6, 'min_child_samples': 83, 'min_child_weight': 15, 'gamma': 3.6450358402049368, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 0.02715581955282941, 'reg_lambda': 0.0029072088906598446, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:06,941] Trial 6 finished with value: 0.7641884559540868 and parameters: {'n_estimators': 345, 'learning_rate': 0.006390259853593126, 'num_leaves': 375, 'min_child_samples': 66, 'min_child_weight': 18, 'gamma': 2.3610746258097466, 'subsample': 0.5597971229691509, 'colsample_bytree': 0.8566223936114975, 'reg_alpha': 1.1044350847124695, 'reg_lambda': 0.17583640270008521, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:07,578] Trial 7 finished with value: 0.7584768624902257 and parameters: {'n_estimators': 74, 'learning_rate': 0.0018503766823590125, 'num_leaves': 19, 'min_child_samples': 66, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:09,684] Trial 8 finished with value: 0.7818358943345226 and parameters: {'n_estimators': 934, 'learning_rate': 0.1004181390102536, 'num_leaves': 326, 'min_child_samples': 88, 'min_child_weight': 17, 'gamma': 0.9328502944301792, 'subsample': 0.9462794992449889, 'colsample_bytree': 0.7696711209578253, 'reg_alpha': 1.6973078532467012, 'reg_lambda': 3.840300419098857, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:24,142] Trial 9 finished with value: 0.7963100842106193 and parameters: {'n_estimators': 827, 'learning_rate': 0.13556076855136892, 'num_leaves': 7, 'min_child_samples': 54, 'min_child_weight': 9, 'gamma': 1.1105390523536514, 'subsample': 0.5599326836668415, 'colsample_bytree': 0.668807585701814, 'reg_alpha': 5.910698619088545, 'reg_lambda': 0.019625093208439862, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:38,845] Trial 10 finished with value: 0.8548646921818869 and parameters: {'n_estimators': 459, 'learning_rate': 0.024229331857231067, 'num_leaves': 497, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.19362599980591533, 'subsample': 0.6806559982209047, 'colsample_bytree': 0.9880699499289975, 'reg_alpha': 0.002442728047335305, 'reg_lambda': 9.32074575706793, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:29:54,693] Trial 11 finished with value: 0.8647373814166252 and parameters: {'n_estimators': 470, 'learning_rate': 0.028590636776905248, 'num_leaves': 508, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.023282959757244676, 'subsample': 0.635785829160606, 'colsample_bytree': 0.9855358228725425, 'reg_alpha': 0.002451549269448794, 'reg_lambda': 9.809283812582127, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:30:08,052] Trial 12 finished with value: 0.852715406205718 and parameters: {'n_estimators': 563, 'learning_rate': 0.04495858406811302, 'num_leaves': 506, 'min_child_samples': 37, 'min_child_weight': 4, 'gamma': 0.015731367398853613, 'subsample': 0.5027646013938348, 'colsample_bytree': 0.9923621651686552, 'reg_alpha': 0.23079754987887785, 'reg_lambda': 1.0200817331216896, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:30:13,237] Trial 13 finished with value: 0.741902277713419 and parameters: {'n_estimators': 364, 'learning_rate': 0.010863628845878923, 'num_leaves': 428, 'min_child_samples': 100, 'min_child_weight': 4, 'gamma': 0.41288079901745023, 'subsample': 0.6693564987154327, 'colsample_bytree': 0.8949828442656665, 'reg_alpha': 0.002177346441761874, 'reg_lambda': 8.127212968528958, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.
[I 2025-04-15 20:30:25,904] Trial 14 finished with value: 0.8167059532109724 and parameters: {'n_estimators': 680, 'learning_rate': 0.05295247083145226, 'num_leaves': 426, 'min_child_samples': 34, 'min_child_weight': 13, 'gamma': 1.9554712350507772, 'subsample': 0.6457038976411733, 'colsample_bytree': 0.8197342331354389, 'reg_alpha': 0.19209905921187967, 'reg_lambda': 0.4858765646932784, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.866358020058759.

best_params

{'n_estimators': 406,
 'learning_rate': 0.22648248189516848,
 'num_leaves': 376,
 'min_child_samples': 62,
 'min_child_weight': 4,
 'gamma': 0.7799726016810132,
 'subsample': 0.5290418060840998,
 'colsample_bytree': 0.9330880728874675,
 'reg_alpha': 0.2537815508265665,
 'reg_lambda': 0.679657809075816,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                           0
target                                                             splashing
model                             LGBMClassifier_splashing_smotenc_opt-model
holdout_test_f1_macro                                               0.863609
holdout_test_accuracy_balanced                                      0.849537
holdout_test_roc_auc                                                0.935571
holdout_test_f1                                                     0.910891
holdout_test_accuracy                                                   0.88
cv_test_f1_macro_median                                             0.821013
cv_test_accuracy_balanced_median                                    0.832817
cv_test_roc_auc_median                                              0.947619
cv_test_f1_median                                                   0.865672
cv_test_accuracy_median                                             0.830189
cv_test_precision_class_0_median                                        0.75
cv_test_recall_class_0_median                                       0.894737
cv_test_f1_class_0_median                                           0.780488

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smotenc_opt-model

In [15]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:30:35,410] A new study created in memory with name: model_study
[I 2025-04-15 20:30:40,299] Trial 0 finished with value: 0.8481478466949124 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:42,915] Trial 1 finished with value: 0.7784842389114137 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:46,725] Trial 2 finished with value: 0.7989762459354601 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:47,009] Trial 3 finished with value: 0.7870636331328095 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:48,821] Trial 4 finished with value: 0.7939656091676219 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:52,033] Trial 5 finished with value: 0.7916901991303364 and parameters: {'n_estimators': 784, 'learning_rate': 0.0031062960067335336, 'num_leaves': 6, 'min_child_samples': 83, 'min_child_weight': 15, 'gamma': 3.6450358402049368, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 0.02715581955282941, 'reg_lambda': 0.0029072088906598446, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:53,925] Trial 6 finished with value: 0.7855554808987619 and parameters: {'n_estimators': 345, 'learning_rate': 0.006390259853593126, 'num_leaves': 375, 'min_child_samples': 66, 'min_child_weight': 18, 'gamma': 2.3610746258097466, 'subsample': 0.5597971229691509, 'colsample_bytree': 0.8566223936114975, 'reg_alpha': 1.1044350847124695, 'reg_lambda': 0.17583640270008521, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:54,501] Trial 7 finished with value: 0.7878916939836333 and parameters: {'n_estimators': 74, 'learning_rate': 0.0018503766823590125, 'num_leaves': 19, 'min_child_samples': 66, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:30:56,209] Trial 8 finished with value: 0.7970297758738075 and parameters: {'n_estimators': 934, 'learning_rate': 0.1004181390102536, 'num_leaves': 326, 'min_child_samples': 88, 'min_child_weight': 17, 'gamma': 0.9328502944301792, 'subsample': 0.9462794992449889, 'colsample_bytree': 0.7696711209578253, 'reg_alpha': 1.6973078532467012, 'reg_lambda': 3.840300419098857, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:05,680] Trial 9 finished with value: 0.8090380883329867 and parameters: {'n_estimators': 827, 'learning_rate': 0.13556076855136892, 'num_leaves': 7, 'min_child_samples': 54, 'min_child_weight': 9, 'gamma': 1.1105390523536514, 'subsample': 0.5599326836668415, 'colsample_bytree': 0.668807585701814, 'reg_alpha': 5.910698619088545, 'reg_lambda': 0.019625093208439862, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:14,364] Trial 10 finished with value: 0.816568585334422 and parameters: {'n_estimators': 459, 'learning_rate': 0.024229331857231067, 'num_leaves': 497, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.19362599980591533, 'subsample': 0.6806559982209047, 'colsample_bytree': 0.9880699499289975, 'reg_alpha': 0.002442728047335305, 'reg_lambda': 9.32074575706793, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:23,690] Trial 11 finished with value: 0.823353875546741 and parameters: {'n_estimators': 470, 'learning_rate': 0.028590636776905248, 'num_leaves': 508, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.023282959757244676, 'subsample': 0.635785829160606, 'colsample_bytree': 0.9855358228725425, 'reg_alpha': 0.002451549269448794, 'reg_lambda': 9.809283812582127, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:31,837] Trial 12 finished with value: 0.8344311605444668 and parameters: {'n_estimators': 563, 'learning_rate': 0.04495858406811302, 'num_leaves': 506, 'min_child_samples': 37, 'min_child_weight': 4, 'gamma': 0.015731367398853613, 'subsample': 0.5027646013938348, 'colsample_bytree': 0.9923621651686552, 'reg_alpha': 0.23079754987887785, 'reg_lambda': 1.0200817331216896, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:41,418] Trial 13 finished with value: 0.8309026447732334 and parameters: {'n_estimators': 652, 'learning_rate': 0.05782720496168289, 'num_leaves': 428, 'min_child_samples': 34, 'min_child_weight': 4, 'gamma': 0.41288079901745023, 'subsample': 0.5183366045836427, 'colsample_bytree': 0.8949828442656665, 'reg_alpha': 0.25527610124679395, 'reg_lambda': 0.6100934206581569, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.
[I 2025-04-15 20:31:45,541] Trial 14 finished with value: 0.811480693992482 and parameters: {'n_estimators': 347, 'learning_rate': 0.052096535869519144, 'num_leaves': 426, 'min_child_samples': 39, 'min_child_weight': 13, 'gamma': 1.9554712350507772, 'subsample': 0.6527912737408437, 'colsample_bytree': 0.8197342331354389, 'reg_alpha': 0.19209905921187967, 'reg_lambda': 0.36717604911374263, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8481478466949124.

best_params

{'n_estimators': 406,
 'learning_rate': 0.22648248189516848,
 'num_leaves': 376,
 'min_child_samples': 62,
 'min_child_weight': 4,
 'gamma': 0.7799726016810132,
 'subsample': 0.5290418060840998,
 'colsample_bytree': 0.9330880728874675,
 'reg_alpha': 0.2537815508265665,
 'reg_lambda': 0.679657809075816,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_opt-model
holdout_test_f1_macro                                                      0.871355
holdout_test_accuracy_balanced                                             0.895455
holdout_test_roc_auc                                                       0.981818
holdout_test_f1                                                            0.818182
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                     0.90293
cv_test_accuracy_balanced_median                                            0.90293
cv_test_roc_auc_median                                                     0.974359
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.948718
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.947368

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smotenc_opt-model