Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = False
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 1000 # was checked with 1000 and 5000

save_model_and_metrics = False

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
):
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}
params_to_process = ['penalty']

def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    
    # # NOTE: Does not work, since optuna requires static parameters ranges
    # solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # penalty_options = {
    #     'lbfgs': ['l2'],
    #     'liblinear': ['l1', 'l2'],
    #     'newton-cg': ['l2'],
    #     'newton-cholesky': ['l2'],
    #     'sag': ['l2'],
    #     'saga': ['l1', 'l2', 'elasticnet'],
    # }
    # penalty = trial.suggest_categorical('penalty', penalty_options[solver])
    # NOTE: warnings + inconvenient to create best model
    # solver_penalty_combinations = [
    #     ("liblinear", "l1"),
    #     ("liblinear", "l2"),
    #     ("saga", "l1"),
    #     ("saga", "l2"),
    #     ("saga", "elasticnet"),
    #     ("lbfgs", "l2"),
    #     ("newton-cg", "l2"),
    #     ("newton-cholesky", "l2"),
    #     ("sag", "l2"),
    # ]
    # solver, penalty = trial.suggest_categorical(
    #     'solver_penalty', solver_penalty_combinations
    # )
    
    solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # solver = trial.suggest_categorical('solver', ['lbfgs',])
    
    if solver == 'liblinear':
        penalty = trial.suggest_categorical('penalty_liblinear', ['l1', 'l2'])
    elif solver == 'saga':
        penalty = trial.suggest_categorical('penalty_saga', ['l1', 'l2', 'elasticnet'])
    else:
        penalty = trial.suggest_categorical('penalty_other', ['l2'])
    
    # If C is large, the penalty should be small
    C = trial.suggest_float('C', 1e-4, 1e3, log=True)
    
    l1_ratio = None
    if penalty == 'elasticnet':
        l1_ratio = trial.suggest_float('l1_ratio', 0., 1.)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "solver": solver,
        "penalty": penalty,
        "C": C,
        "l1_ratio": l1_ratio,
        "class_weight": class_weight,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-14 22:06:13,851] A new study created in memory with name: model_study
[I 2025-04-14 22:06:13,907] Trial 0 finished with value: 0.7985639090256361 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 22:06:13,966] Trial 1 finished with value: 0.7941608217143109 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 22:06:14,018] Trial 2 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 22:06:14,072] Trial 3 finished with value: 0.797286337918985 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 22:06:14,125] Trial 4 finished with value: 0.8051764214045931 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 4 with value: 0.8051764214045931.
[I 2025-04-14 22:06:14,180] Trial 5 finished with value: 0.7472954252138893 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 4 with value: 0.8051764214045931.
[I 2025-04-14 22:06:14,240] Trial 6 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,294] Trial 7 finished with value: 0.7611608284370048 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,349] Trial 8 finished with value: 0.8092959761471556 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,403] Trial 9 finished with value: 0.7440757557883121 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,465] Trial 10 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 612.0117715317909, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,528] Trial 11 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 812.2968586165572, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,589] Trial 12 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 44.18006281079643, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,652] Trial 13 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 53.997004500496224, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,713] Trial 14 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 82.8316016194943, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,775] Trial 15 finished with value: 0.8043578522466602 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 6.710520506428847, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,837] Trial 16 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 862.7281076174387, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,895] Trial 17 finished with value: 0.8011388801027161 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 9.634842407301047, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:14,952] Trial 18 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 154.28126375129878, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,007] Trial 19 finished with value: 0.7147720923839032 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.05277899450558773, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,061] Trial 20 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.0019806976015503477, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,121] Trial 21 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 793.8857365594376, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,183] Trial 22 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 219.31135888519634, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,245] Trial 23 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 25.510987556759318, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,305] Trial 24 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 258.3620661216836, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,366] Trial 25 finished with value: 0.8011388801027161 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 2.5427324308248602, 'l1_ratio': 0.03880691701978933, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,424] Trial 26 finished with value: 0.8108339592997184 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 670.8607617954096, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,486] Trial 27 finished with value: 0.8076324033935517 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 21.875400062405905, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,544] Trial 28 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 127.61786566762798, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,599] Trial 29 finished with value: 0.8054944185887905 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.657889434458531, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,657] Trial 30 finished with value: 0.8070196325242648 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.3693501869209362, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,719] Trial 31 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 24.60210090566989, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,781] Trial 32 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 55.444174075582346, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,843] Trial 33 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 991.2188844464986, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,903] Trial 34 finished with value: 0.8051764214045931 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 326.9005065843657, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:15,963] Trial 35 finished with value: 0.8011388801027161 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.356386770573319, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,018] Trial 36 finished with value: 0.8069855520521557 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.7671853381937119, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,075] Trial 37 finished with value: 0.7523053213470348 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.11784084260431638, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,135] Trial 38 finished with value: 0.8083849775543257 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 104.47008439705394, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,196] Trial 39 finished with value: 0.8108339592997184 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 332.20768073311547, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,254] Trial 40 finished with value: 0.8076324033935517 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 45.48108914098549, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,316] Trial 41 finished with value: 0.8076324033935517 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 46.29829692045701, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,377] Trial 42 finished with value: 0.8043578522466602 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 14.644895489802087, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,440] Trial 43 finished with value: 0.8011388801027161 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 6.437774317247896, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,504] Trial 44 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 80.80022488898723, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,561] Trial 45 finished with value: 0.8083849775543257 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 471.34177634275824, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,618] Trial 46 finished with value: 0.8108339592997184 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 175.51679075546247, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,683] Trial 47 finished with value: 0.8011388801027161 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 4.92508850455539, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,746] Trial 48 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 404.87118172795107, 'l1_ratio': 0.9991380019669489, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,801] Trial 49 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.0004062648427292201, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,861] Trial 50 finished with value: 0.8091931765214193 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.8916958583368253, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,922] Trial 51 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 59.64793340371888, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:16,984] Trial 52 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 112.68149098711169, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:17,045] Trial 53 finished with value: 0.8011388801027161 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 13.370634009504629, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:17,108] Trial 54 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 32.12497696807618, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 22:06:17,170] Trial 55 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 162.5069104968723, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[W 2025-04-14 22:06:17,209] Trial 56 failed with parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 507.3510292017766, 'class_weight': 'balanced'} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "/var/folders/dv/7ymr80q90cs45p34fgkdmj0c0000gn/T/ipykernel_80904/3407078681.py", line 71, in logreg_objective
    score = ml_pipe.step(
            ^^^^^^^^^^^^^
  File "/Users/vulf/Git/Hub/Drop_wall_impact/notebooks/../utils_functionality/models/modelling4_utils.py", line 341, in step
    metrics = self.get_cv_metrics(
              ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/Git/Hub/Drop_wall_impact/notebooks/../utils_functionality/models/modelling4_utils.py", line 563, in get_cv_metrics
    cv_results = cross_validate(
                 ^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 266, in cross_validate
    results = parallel(
              ^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 708, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, error_score)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 767, in _score
    scores = scorer(estimator, X_test, y_test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 115, in __call__
    score = scorer._score(cached_call, estimator, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 276, in _score
    y_pred = method_caller(estimator, "predict", X)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/metrics/_scorer.py", line 73, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/imblearn/pipeline.py", line 452, in predict
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 800, in transform
    Xs = self._fit_transform(
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py", line 658, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 63, in __call__
    return super().__call__(iterable_with_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/joblib/parallel.py", line 1863, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/joblib/parallel.py", line 1792, in _get_sequential_output
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/parallel.py", line 123, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/pipeline.py", line 876, in _transform_one
    res = transformer.transform(X)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 992, in transform
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/utils/validation.py", line 752, in check_array
    dtype_orig = getattr(array, "dtype", None)

KeyboardInterrupt:

In [7]:
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-14 21:43:17,913] A new study created in memory with name: model_study
[I 2025-04-14 21:43:17,962] Trial 0 finished with value: 0.8397856760138982 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,012] Trial 1 finished with value: 0.8027588628638668 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,056] Trial 2 finished with value: 0.4233049487844008 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,102] Trial 3 finished with value: 0.7911634439518859 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,148] Trial 4 finished with value: 0.8041450241851706 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,195] Trial 5 finished with value: 0.7101944867137514 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,311] Trial 6 finished with value: 0.8038814873616754 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,357] Trial 7 finished with value: 0.7162615239628565 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,403] Trial 8 finished with value: 0.8389828678891506 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,450] Trial 9 finished with value: 0.7027598982205824 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,505] Trial 10 finished with value: 0.7927422008145589 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.8666692466256958, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,554] Trial 11 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 10.143487196996828, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,602] Trial 12 finished with value: 0.812515742911062 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.6327525396615056, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,651] Trial 13 finished with value: 0.8041450241851706 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 810.5159286019858, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,697] Trial 14 finished with value: 0.8217069937807342 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 41.088344411941925, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,745] Trial 15 finished with value: 0.7553687870563394 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.0372597498604139, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 21:43:18,797] Trial 16 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.724106746978989, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:18,849] Trial 17 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.095084119182575, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:18,901] Trial 18 finished with value: 0.751333847002101 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.08756325508970042, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:18,947] Trial 19 finished with value: 0.7058880066067941 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.0024162747940151587, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:19,003] Trial 20 finished with value: 0.8053486507069412 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 129.7722129415162, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:19,057] Trial 21 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.2132003115413115, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 21:43:19,116] Trial 22 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.8783531560274382, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,171] Trial 23 finished with value: 0.8373759056160653 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 15.303575401434081, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,224] Trial 24 finished with value: 0.7861038159067716 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.23387991022843746, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,270] Trial 25 finished with value: 0.823203012055543 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.1344494087951653, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,387] Trial 26 finished with value: 0.7957150504518486 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 5.295881990201866, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,464] Trial 27 finished with value: 0.8129853203141331 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 60.76935561647131, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,512] Trial 28 finished with value: 0.764321884872908 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.12927445165859106, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,563] Trial 29 finished with value: 0.8060768869882171 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.5144042098751197, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,611] Trial 30 finished with value: 0.8397856760138982 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.5561018720408164, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,667] Trial 31 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.8712800590967085, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,722] Trial 32 finished with value: 0.8264230783613948 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 25.316725538800213, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,776] Trial 33 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.7221260582895894, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 21:43:19,831] Trial 34 finished with value: 0.8450545594789775 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 5.435591249239913, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:19,886] Trial 35 finished with value: 0.8053486507069412 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 136.63824111037857, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:19,939] Trial 36 finished with value: 0.823203012055543 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.816964373947913, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:19,994] Trial 37 finished with value: 0.7957150504518486 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 6.659970275930177, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,042] Trial 38 finished with value: 0.7794397535150646 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.2153110037721488, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,097] Trial 39 finished with value: 0.8264230783613948 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 24.35599927753569, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,153] Trial 40 finished with value: 0.8009378735983896 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 129.41869004589753, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,206] Trial 41 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.7122157144133734, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,259] Trial 42 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.157250346127057, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,313] Trial 43 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 12.097509864736578, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,364] Trial 44 finished with value: 0.832833811324452 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.3542365384722908, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,417] Trial 45 finished with value: 0.8027588628638668 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.4966907276767269, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,473] Trial 46 finished with value: 0.8360731605957052 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 6.752958044247071, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,633] Trial 47 finished with value: 0.8217069937807342 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 2.193740731166382, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,689] Trial 48 finished with value: 0.7975711524350583 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 21.194244633210136, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,738] Trial 49 finished with value: 0.7027598982205824 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0005639111644513537, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,785] Trial 50 finished with value: 0.7567771390686735 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.08059991173771112, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,839] Trial 51 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.2811507683257304, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,893] Trial 52 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.327120493705326, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:20,947] Trial 53 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 10.564040915095697, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,000] Trial 54 finished with value: 0.823203012055543 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 1.0126144081915616, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,052] Trial 55 finished with value: 0.8129853203141331 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 46.83818698981929, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,107] Trial 56 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.597273588251652, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,161] Trial 57 finished with value: 0.7993857581360823 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.36753899263985235, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,209] Trial 58 finished with value: 0.8406750578217989 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.360169940577772, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,261] Trial 59 finished with value: 0.7893690960867744 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 3.0551997320669275, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,314] Trial 60 finished with value: 0.812515742911062 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.6495644164002591, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,366] Trial 61 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.0293760265596825, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,419] Trial 62 finished with value: 0.8354048098646316 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 7.827934261405636, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,471] Trial 63 finished with value: 0.823203012055543 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 1.0836456620816417, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,524] Trial 64 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.9179812448793645, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,577] Trial 65 finished with value: 0.8317761482305938 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 15.80974552873053, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,625] Trial 66 finished with value: 0.8053486507069412 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 4.748326038221667, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,678] Trial 67 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 1.6402327691754006, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,727] Trial 68 finished with value: 0.7927742618629319 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.27481098957995026, 'l1_ratio': 0.041137171506509196, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,781] Trial 69 finished with value: 0.8217069937807342 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 36.51964751460303, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,835] Trial 70 finished with value: 0.8053486507069412 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 78.6815191291605, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,888] Trial 71 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.457168209983347, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,941] Trial 72 finished with value: 0.8450545594789775 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 4.783308972200041, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:21,995] Trial 73 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 11.096779287733991, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,048] Trial 74 finished with value: 0.8450545594789775 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 4.820194047290271, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,101] Trial 75 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 4.591796285663789, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,151] Trial 76 finished with value: 0.823203012055543 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.8745550170582032, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,200] Trial 77 finished with value: 0.7975711524350583 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 19.244148069789457, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,254] Trial 78 finished with value: 0.8354048098646316 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 8.352755620955527, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,303] Trial 79 finished with value: 0.832833811324452 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.4720023658482115, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,349] Trial 80 finished with value: 0.8053486507069412 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 4.028832162541991, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,403] Trial 81 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.6738068880830195, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 21:43:22,456] Trial 82 finished with value: 0.8450545594789775 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 5.659872181925421, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.

best_params

{'solver': 'lbfgs',
 'C': 3.62369856229918,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                              0
target                                                         no_fragmentation
model                             LogisticRegression_no_fragmentation_opt-model
holdout_test_f1_macro                                                  0.798595
holdout_test_accuracy_balanced                                         0.834091
holdout_test_roc_auc                                                   0.943636
holdout_test_f1                                                        0.723404
holdout_test_accuracy                                                  0.826667
cv_test_f1_macro_median                                                0.865709
cv_test_accuracy_balanced_median                                       0.882051
cv_test_roc_auc_median                                                 0.938462
cv_test_f1_median                                                        0.8125
cv_test_accuracy_median                                                0.886792
cv_test_precision_class_0_median                                       0.969697
cv_test_recall_class_0_median                                          0.871795
cv_test_f1_class_0_median                                              0.918919

# KNClassifier

In [ ]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['penalty']
params_to_process = None


def knn_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    n_neighbors = trial.suggest_int("n_neighbors", 1, 50)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    p = trial.suggest_int("p", 1, 2)  # 1=manhattan, 2=euclidean
    # leaf_size - affects the speed of the tree construction and search
    # algorithm - affects the speed of the search, for small datasets it is okay to use auto
    
    suggested_estimator_params = {
        "n_neighbors": n_neighbors,
        "weights": weights,
        "p": p,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-14 21:44:14,171] A new study created in memory with name: model_study
[I 2025-04-14 21:44:14,266] Trial 0 finished with value: 0.7712834391009027 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7712834391009027.
[I 2025-04-14 21:44:14,353] Trial 1 finished with value: 0.8008110983626221 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8008110983626221.
[I 2025-04-14 21:44:14,444] Trial 2 finished with value: 0.73226117633208 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8008110983626221.
[I 2025-04-14 21:44:14,538] Trial 3 finished with value: 0.7563818520550063 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8008110983626221.
[I 2025-04-14 21:44:14,627] Trial 4 finished with value: 0.7848640826258931 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8008110983626221.
[I 2025-04-14 21:44:14,692] Trial 5 finished with value: 0.8440350398624317 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8440350398624317.
[I 2025-04-14 21:44:14,782] Trial 6 finished with value: 0.7232557994812624 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8440350398624317.
[I 2025-04-14 21:44:14,847] Trial 7 finished with value: 0.8440350398624317 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8440350398624317.
[I 2025-04-14 21:44:14,904] Trial 8 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8737777980087608.
[I 2025-04-14 21:44:14,966] Trial 9 finished with value: 0.8567297510864592 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8737777980087608.
[I 2025-04-14 21:44:15,025] Trial 10 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,083] Trial 11 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,141] Trial 12 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,203] Trial 13 finished with value: 0.8609197320077738 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,266] Trial 14 finished with value: 0.8609197320077738 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,338] Trial 15 finished with value: 0.8258525036162437 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,397] Trial 16 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,459] Trial 17 finished with value: 0.8681134973988025 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,523] Trial 18 finished with value: 0.8530975458532689 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,589] Trial 19 finished with value: 0.847744332842855 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,659] Trial 20 finished with value: 0.8432895358825486 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,720] Trial 21 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,780] Trial 22 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,839] Trial 23 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,902] Trial 24 finished with value: 0.8529910739293582 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:15,964] Trial 25 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,023] Trial 26 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,089] Trial 27 finished with value: 0.8452595388555979 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,150] Trial 28 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,252] Trial 29 finished with value: 0.8054503524253719 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,315] Trial 30 finished with value: 0.8609197320077738 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,374] Trial 31 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,435] Trial 32 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,498] Trial 33 finished with value: 0.8601504381287354 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,587] Trial 34 finished with value: 0.8008110983626221 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,676] Trial 35 finished with value: 0.8461187690449214 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,742] Trial 36 finished with value: 0.8452595388555979 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,839] Trial 37 finished with value: 0.7508192545304906 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,904] Trial 38 finished with value: 0.8529910739293582 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:16,965] Trial 39 finished with value: 0.8681134973988025 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,054] Trial 40 finished with value: 0.8329751614962039 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,113] Trial 41 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,173] Trial 42 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,232] Trial 43 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,294] Trial 44 finished with value: 0.8609197320077738 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8824052609894479.
[I 2025-04-14 21:44:17,355] Trial 45 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,417] Trial 46 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,484] Trial 47 finished with value: 0.8393880562729409 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,546] Trial 48 finished with value: 0.8650587189808622 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,608] Trial 49 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,680] Trial 50 finished with value: 0.82903374128024 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,740] Trial 51 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,801] Trial 52 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,862] Trial 53 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,923] Trial 54 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:17,987] Trial 55 finished with value: 0.8529910739293582 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,047] Trial 56 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,108] Trial 57 finished with value: 0.8758621423574441 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,171] Trial 58 finished with value: 0.8601504381287354 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,260] Trial 59 finished with value: 0.8461187690449214 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,324] Trial 60 finished with value: 0.8530975458532689 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,386] Trial 61 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,446] Trial 62 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,506] Trial 63 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,570] Trial 64 finished with value: 0.8530975458532689 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,630] Trial 65 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,692] Trial 66 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,758] Trial 67 finished with value: 0.8529910739293582 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,819] Trial 68 finished with value: 0.8681134973988025 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,881] Trial 69 finished with value: 0.8650587189808622 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:18,941] Trial 70 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,001] Trial 71 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,063] Trial 72 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,124] Trial 73 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,184] Trial 74 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,246] Trial 75 finished with value: 0.8681134973988025 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,307] Trial 76 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,396] Trial 77 finished with value: 0.828087028274745 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,466] Trial 78 finished with value: 0.8372006418375995 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,529] Trial 79 finished with value: 0.8650587189808622 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,589] Trial 80 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,651] Trial 81 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,712] Trial 82 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,771] Trial 83 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,833] Trial 84 finished with value: 0.8681134973988025 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,894] Trial 85 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:19,955] Trial 86 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,018] Trial 87 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,080] Trial 88 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,168] Trial 89 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,241] Trial 90 finished with value: 0.827850646122619 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'p': 1}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,302] Trial 91 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,363] Trial 92 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,425] Trial 93 finished with value: 0.8709479249335043 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,488] Trial 94 finished with value: 0.8601504381287354 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,549] Trial 95 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,611] Trial 96 finished with value: 0.8737777980087608 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,673] Trial 97 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,734] Trial 98 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,797] Trial 99 finished with value: 0.8530975458532689 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,857] Trial 100 finished with value: 0.8824052609894479 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,918] Trial 101 finished with value: 0.8914115363728973 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.
[I 2025-04-14 21:44:20,981] Trial 102 finished with value: 0.879194508039092 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8914115363728973.

best_params

{'n_neighbors': 3, 'weights': 'distance', 'p': 2}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                         0
target                                                           splashing
model                             KNeighborsClassifier_splashing_opt-model
holdout_test_f1_macro                                             0.836601
holdout_test_accuracy_balanced                                    0.828704
holdout_test_roc_auc                                              0.881173
holdout_test_f1                                                   0.888889
holdout_test_accuracy                                             0.853333
cv_test_f1_macro_median                                           0.876935
cv_test_accuracy_balanced_median                                  0.876935
cv_test_roc_auc_median                                            0.944361
cv_test_f1_median                                                 0.911765
cv_test_accuracy_median                                           0.886792
cv_test_precision_class_0_median                                  0.842105
cv_test_recall_class_0_median                                     0.842105
cv_test_f1_class_0_median                                         0.842105

In [ ]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-14 21:45:22,424] A new study created in memory with name: model_study
[I 2025-04-14 21:45:22,507] Trial 0 finished with value: 0.7701654488774984 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7701654488774984.
[I 2025-04-14 21:45:22,586] Trial 1 finished with value: 0.8156628959108977 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:22,670] Trial 2 finished with value: 0.7104448022241227 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:22,755] Trial 3 finished with value: 0.7299310684038487 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:22,834] Trial 4 finished with value: 0.7481827842300584 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:22,892] Trial 5 finished with value: 0.8142835613679844 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:22,977] Trial 6 finished with value: 0.7316514235428276 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8156628959108977.
[I 2025-04-14 21:45:23,034] Trial 7 finished with value: 0.8213995004399995 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 7 with value: 0.8213995004399995.
[I 2025-04-14 21:45:23,082] Trial 8 finished with value: 0.8359107463730838 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,134] Trial 9 finished with value: 0.8046342332618802 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,197] Trial 10 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,248] Trial 11 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,298] Trial 12 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,351] Trial 13 finished with value: 0.8203471132042559 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8359107463730838.
[I 2025-04-14 21:45:23,405] Trial 14 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,459] Trial 15 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,522] Trial 16 finished with value: 0.8091199790366185 and parameters: {'n_neighbors': 45, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,575] Trial 17 finished with value: 0.8216165137277376 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,638] Trial 18 finished with value: 0.8287948112392335 and parameters: {'n_neighbors': 39, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,702] Trial 19 finished with value: 0.820023700419663 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,760] Trial 20 finished with value: 0.8051118019194414 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'p': 1}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,875] Trial 21 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 14 with value: 0.8384628280554148.
[I 2025-04-14 21:45:23,928] Trial 22 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:23,981] Trial 23 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,036] Trial 24 finished with value: 0.8255658358798312 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,088] Trial 25 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,143] Trial 26 finished with value: 0.8255658358798312 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,196] Trial 27 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,252] Trial 28 finished with value: 0.8106229591355107 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,332] Trial 29 finished with value: 0.8371407716610817 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,389] Trial 30 finished with value: 0.8110868216456263 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,443] Trial 31 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,495] Trial 32 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,550] Trial 33 finished with value: 0.8171889040869944 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,632] Trial 34 finished with value: 0.8119082426329646 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,710] Trial 35 finished with value: 0.8180018522286964 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,766] Trial 36 finished with value: 0.8255658358798312 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,855] Trial 37 finished with value: 0.7379953118005432 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,908] Trial 38 finished with value: 0.8203471132042559 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:24,967] Trial 39 finished with value: 0.8126769152047959 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,053] Trial 40 finished with value: 0.7525566405485983 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'p': 1}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,106] Trial 41 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,158] Trial 42 finished with value: 0.8309005357435781 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,210] Trial 43 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,264] Trial 44 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,313] Trial 45 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,366] Trial 46 finished with value: 0.8171889040869944 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,420] Trial 47 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,477] Trial 48 finished with value: 0.820022769236583 and parameters: {'n_neighbors': 17, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,529] Trial 49 finished with value: 0.8309005357435781 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,582] Trial 50 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,635] Trial 51 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,688] Trial 52 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,741] Trial 53 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,795] Trial 54 finished with value: 0.8216165137277376 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,846] Trial 55 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,902] Trial 56 finished with value: 0.8255658358798312 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:25,957] Trial 57 finished with value: 0.8409903492681295 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 1}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,011] Trial 58 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,093] Trial 59 finished with value: 0.8431352962676149 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,143] Trial 60 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,195] Trial 61 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,249] Trial 62 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,303] Trial 63 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,355] Trial 64 finished with value: 0.8359107463730838 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,410] Trial 65 finished with value: 0.8171889040869944 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,464] Trial 66 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,516] Trial 67 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,568] Trial 68 finished with value: 0.8309005357435781 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,626] Trial 69 finished with value: 0.811707432803565 and parameters: {'n_neighbors': 23, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,681] Trial 70 finished with value: 0.8203471132042559 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,734] Trial 71 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,786] Trial 72 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,838] Trial 73 finished with value: 0.8359107463730838 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,892] Trial 74 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:26,945] Trial 75 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,025] Trial 76 finished with value: 0.8191271250663181 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,080] Trial 77 finished with value: 0.8216165137277376 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,142] Trial 78 finished with value: 0.8255218936806017 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,197] Trial 79 finished with value: 0.8255658358798312 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,256] Trial 80 finished with value: 0.8135806562724713 and parameters: {'n_neighbors': 25, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,310] Trial 81 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,363] Trial 82 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,415] Trial 83 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,466] Trial 84 finished with value: 0.8359107463730838 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,530] Trial 85 finished with value: 0.8130457159980696 and parameters: {'n_neighbors': 46, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,584] Trial 86 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,665] Trial 87 finished with value: 0.8071497369353906 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,716] Trial 88 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,769] Trial 89 finished with value: 0.8240073990118522 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 1}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,822] Trial 90 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,876] Trial 91 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,929] Trial 92 finished with value: 0.8449232196123485 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:27,983] Trial 93 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,034] Trial 94 finished with value: 0.8268717548577573 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,088] Trial 95 finished with value: 0.8384628280554148 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,142] Trial 96 finished with value: 0.8216165137277376 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,195] Trial 97 finished with value: 0.8359107463730838 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,249] Trial 98 finished with value: 0.828784699831708 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,304] Trial 99 finished with value: 0.8324513064491343 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,385] Trial 100 finished with value: 0.8180018522286964 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,439] Trial 101 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.
[I 2025-04-14 21:45:28,492] Trial 102 finished with value: 0.845131731658418 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 22 with value: 0.845131731658418.

best_params

{'n_neighbors': 5, 'weights': 'distance', 'p': 1}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                0
target                                                           no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_opt-model
holdout_test_f1_macro                                                    0.890351
holdout_test_accuracy_balanced                                           0.865909
holdout_test_roc_auc                                                     0.972727
holdout_test_f1                                                          0.833333
holdout_test_accuracy                                                        0.92
cv_test_f1_macro_median                                                  0.833856
cv_test_accuracy_balanced_median                                         0.841575
cv_test_roc_auc_median                                                    0.93956
cv_test_f1_median                                                        0.758621
cv_test_accuracy_median                                                  0.867925
cv_test_precision_class_0_median                                         0.904762
cv_test_recall_class_0_median                                            0.948718
cv_test_f1_class_0_median                                                0.909091

# SVC

In [6]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True, # Would beFalse for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']


def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=n_trials,
)

In [ ]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True, # Would be False for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-14 23:51:59,608] A new study created in memory with name: model_study
[I 2025-04-14 23:51:59,670] Trial 0 finished with value: 0.4233049487844008 and parameters: {'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 0 with value: 0.4233049487844008.
[I 2025-04-14 23:51:59,741] Trial 1 finished with value: 0.6016942035676301 and parameters: {'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 1 with value: 0.6016942035676301.
[I 2025-04-14 23:51:59,792] Trial 2 finished with value: 0.8126333274927476 and parameters: {'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}. Best is trial 2 with value: 0.8126333274927476.

{'probability': False, 'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}
{'probability': False, 'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}

[I 2025-04-14 23:51:59,852] Trial 3 finished with value: 0.3598147546087732 and parameters: {'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}. Best is trial 2 with value: 0.8126333274927476.
[I 2025-04-14 23:51:59,908] Trial 4 finished with value: 0.7970029887348734 and parameters: {'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}. Best is trial 2 with value: 0.8126333274927476.
[I 2025-04-14 23:51:59,963] Trial 5 finished with value: 0.8360531418283557 and parameters: {'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002273762810253686}. Best is trial 5 with value: 0.8360531418283557.
[I 2025-04-14 23:52:00,013] Trial 6 finished with value: 0.4233049487844008 and parameters: {'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}. Best is trial 5 with value: 0.8360531418283557.

{'probability': False, 'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}
{'probability': False, 'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma': 0.002273762810253686}
{'probability': False, 'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}
{'probability': False, 'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}

[I 2025-04-14 23:52:00,095] Trial 7 finished with value: 0.8155624544304209 and parameters: {'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8360531418283557.
[I 2025-04-14 23:52:00,190] Trial 8 finished with value: 0.8154601629443344 and parameters: {'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}. Best is trial 5 with value: 0.8360531418283557.
[I 2025-04-14 23:52:00,238] Trial 9 finished with value: 0.8458685850271029 and parameters: {'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}. Best is trial 9 with value: 0.8458685850271029.
[I 2025-04-14 23:52:00,293] Trial 10 finished with value: 0.8429135011964434 and parameters: {'kernel': 'poly', 'C': 3.319977760729008, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}. Best is trial 9 with value: 0.8458685850271029.

{'probability': False, 'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}
{'probability': False, 'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 3.319977760729008, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.7731722229182417, 'degree': 2}

[I 2025-04-14 23:52:00,351] Trial 11 finished with value: 0.8466307261118248 and parameters: {'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7731722229182417, 'degree': 2}. Best is trial 11 with value: 0.8466307261118248.
[I 2025-04-14 23:52:00,408] Trial 12 finished with value: 0.8466307261118249 and parameters: {'kernel': 'poly', 'C': 4.227037048440708, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}. Best is trial 12 with value: 0.8466307261118249.
[I 2025-04-14 23:52:00,468] Trial 13 finished with value: 0.6985677837885549 and parameters: {'kernel': 'poly', 'C': 0.21162414884556205, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4687052188878424, 'degree': 2}. Best is trial 12 with value: 0.8466307261118249.
[I 2025-04-14 23:52:00,527] Trial 14 finished with value: 0.8870956746492266 and parameters: {'kernel': 'poly', 'C': 13.135929435146066, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5261968434186639, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 4.227037048440708, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 0.21162414884556205, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.4687052188878424, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.135929435146066, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.5261968434186639, 'degree': 2}
{'probability': False, 'kernel': 'sigmoid', 'C': 19.8396110427838, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.40095596968204394}

[I 2025-04-14 23:52:00,582] Trial 15 finished with value: 0.680135978211717 and parameters: {'kernel': 'sigmoid', 'C': 19.8396110427838, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.40095596968204394}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:00,643] Trial 16 finished with value: 0.4478610983405504 and parameters: {'kernel': 'poly', 'C': 0.09671126207558609, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2771626218769963, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:00,724] Trial 17 finished with value: 0.8474506281070238 and parameters: {'kernel': 'poly', 'C': 31.476071912073454, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.616027730846257, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:00,787] Trial 18 finished with value: 0.85061502540609 and parameters: {'kernel': 'poly', 'C': 58.72905739406304, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.58893281276592, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 0.09671126207558609, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.2771626218769963, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 31.476071912073454, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.616027730846257, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 58.72905739406304, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.58893281276592, 'degree': 3}
{'probability': False, 'kernel': 'sigmoid', 'C': 0.0010676790422275248, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.31380535742629734}

[I 2025-04-14 23:52:00,848] Trial 19 finished with value: 0.4233049487844008 and parameters: {'kernel': 'sigmoid', 'C': 0.0010676790422275248, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.31380535742629734}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:00,906] Trial 20 finished with value: 0.8474506281070238 and parameters: {'kernel': 'poly', 'C': 32.06146892569261, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5959881987733058, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:00,962] Trial 21 finished with value: 0.8557882825666809 and parameters: {'kernel': 'poly', 'C': 26.200369145529198, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6048456513126098, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,019] Trial 22 finished with value: 0.8226475607807419 and parameters: {'kernel': 'poly', 'C': 909.5629597962662, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5380867568331372, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 32.06146892569261, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.5959881987733058, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 26.200369145529198, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.6048456513126098, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 909.5629597962662, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.5380867568331372, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 1.266782529932709, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.7097732125996608, 'degree': 3}

[I 2025-04-14 23:52:01,075] Trial 23 finished with value: 0.826088410611605 and parameters: {'kernel': 'poly', 'C': 1.266782529932709, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7097732125996608, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,141] Trial 24 finished with value: 0.8397710263607853 and parameters: {'kernel': 'poly', 'C': 14.408404959189813, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.45244577507169453, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,199] Trial 25 finished with value: 0.85061502540609 and parameters: {'kernel': 'poly', 'C': 78.52731855049453, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.976448659922462, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,256] Trial 26 finished with value: 0.8404842241857369 and parameters: {'kernel': 'poly', 'C': 1.2211789950989649, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.3470238538045015, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 14.408404959189813, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.45244577507169453, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 78.52731855049453, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.976448659922462, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 1.2211789950989649, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.3470238538045015, 'degree': 2}
{'probability': False, 'kernel': 'sigmoid', 'C': 63.37763247010478, 'class_weight': None, 'gamma': 6.873386171431708, 'coef0': 0.20289171522503113}

[I 2025-04-14 23:52:01,314] Trial 27 finished with value: 0.6753369972282968 and parameters: {'kernel': 'sigmoid', 'C': 63.37763247010478, 'class_weight': None, 'gamma_type': 'float', 'gamma': 6.873386171431708, 'coef0': 0.20289171522503113}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,373] Trial 28 finished with value: 0.8396781982437568 and parameters: {'kernel': 'rbf', 'C': 731.099506518017, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,428] Trial 29 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 13.15432685404433, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,484] Trial 30 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 13.790065526987622, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 731.099506518017, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 13.15432685404433, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 13.790065526987622, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 11.553231802316837, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:01,539] Trial 31 finished with value: 0.8575205805213596 and parameters: {'kernel': 'rbf', 'C': 11.553231802316837, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,597] Trial 32 finished with value: 0.8106553105113014 and parameters: {'kernel': 'rbf', 'C': 2.075849296239219, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,654] Trial 33 finished with value: 0.8438318166725415 and parameters: {'kernel': 'rbf', 'C': 8.520331209133287, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,720] Trial 34 finished with value: 0.8246404893294039 and parameters: {'kernel': 'rbf', 'C': 0.3635416872076314, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 2.075849296239219, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 8.520331209133287, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 0.3635416872076314, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 10.94246414181654, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:01,780] Trial 35 finished with value: 0.8619444442088119 and parameters: {'kernel': 'rbf', 'C': 10.94246414181654, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,840] Trial 36 finished with value: 0.8308721619204533 and parameters: {'kernel': 'rbf', 'C': 2.394091485756988, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,899] Trial 37 finished with value: 0.8560357951125741 and parameters: {'kernel': 'rbf', 'C': 183.20082851570092, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:01,967] Trial 38 finished with value: 0.76621096488023 and parameters: {'kernel': 'rbf', 'C': 0.5844149420764065, 'class_weight': None, 'gamma_type': 'float', 'gamma': 7.065451494771245}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 2.394091485756988, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 183.20082851570092, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 0.5844149420764065, 'class_weight': None, 'gamma': 7.065451494771245}
{'probability': False, 'kernel': 'rbf', 'C': 10.92744330465532, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:02,027] Trial 39 finished with value: 0.8645236244245744 and parameters: {'kernel': 'rbf', 'C': 10.92744330465532, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,099] Trial 40 finished with value: 0.775825195159171 and parameters: {'kernel': 'rbf', 'C': 0.04000356921403401, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,155] Trial 41 finished with value: 0.8686742164101836 and parameters: {'kernel': 'rbf', 'C': 9.174666190502615, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,212] Trial 42 finished with value: 0.8618491648390127 and parameters: {'kernel': 'rbf', 'C': 7.538727403771719, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 0.04000356921403401, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 9.174666190502615, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 7.538727403771719, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 44.58128862439938, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:02,271] Trial 43 finished with value: 0.8605367463067533 and parameters: {'kernel': 'rbf', 'C': 44.58128862439938, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,325] Trial 44 finished with value: 0.8230259176813852 and parameters: {'kernel': 'linear', 'C': 3.7606234306092072, 'class_weight': 'balanced'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,382] Trial 45 finished with value: 0.8465121333165021 and parameters: {'kernel': 'rbf', 'C': 106.20454643852652, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,441] Trial 46 finished with value: 0.871852602710134 and parameters: {'kernel': 'rbf', 'C': 15.55481809662672, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'linear', 'C': 3.7606234306092072, 'class_weight': 'balanced'}
{'probability': False, 'kernel': 'rbf', 'C': 106.20454643852652, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 15.55481809662672, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'linear', 'C': 19.37621504925882, 'class_weight': 'balanced'}

[I 2025-04-14 23:52:02,561] Trial 47 finished with value: 0.8234683606195867 and parameters: {'kernel': 'linear', 'C': 19.37621504925882, 'class_weight': 'balanced'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,631] Trial 48 finished with value: 0.8308721619204533 and parameters: {'kernel': 'rbf', 'C': 2.363422544316472, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,690] Trial 49 finished with value: 0.8438285012441847 and parameters: {'kernel': 'rbf', 'C': 326.8119647213362, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,753] Trial 50 finished with value: 0.2673900315409749 and parameters: {'kernel': 'sigmoid', 'C': 5.917641415693132, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00010729462466702077, 'coef0': 0.03604997864525583}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 2.363422544316472, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 326.8119647213362, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'sigmoid', 'C': 5.917641415693132, 'class_weight': 'balanced', 'gamma': 0.00010729462466702077, 'coef0': 0.03604997864525583}
{'probability': False, 'kernel': 'rbf', 'C': 17.449049421149137, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:02,811] Trial 51 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 17.449049421149137, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,870] Trial 52 finished with value: 0.8605367463067533 and parameters: {'kernel': 'rbf', 'C': 34.74056803380048, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,927] Trial 53 finished with value: 0.868809520587919 and parameters: {'kernel': 'rbf', 'C': 20.633970354946, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:02,985] Trial 54 finished with value: 0.8551260021382695 and parameters: {'kernel': 'rbf', 'C': 156.0460178959855, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 34.74056803380048, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 20.633970354946, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 156.0460178959855, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 20.768662201241984, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:03,043] Trial 55 finished with value: 0.8654427994245876 and parameters: {'kernel': 'rbf', 'C': 20.768662201241984, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,110] Trial 56 finished with value: 0.8234683606195867 and parameters: {'kernel': 'linear', 'C': 24.60640360136324, 'class_weight': 'balanced'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,170] Trial 57 finished with value: 0.8605367463067533 and parameters: {'kernel': 'rbf', 'C': 45.12431757778141, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,228] Trial 58 finished with value: 0.5952956684895897 and parameters: {'kernel': 'sigmoid', 'C': 4.521354149694563, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8658880281075071}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'linear', 'C': 24.60640360136324, 'class_weight': 'balanced'}
{'probability': False, 'kernel': 'rbf', 'C': 45.12431757778141, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'sigmoid', 'C': 4.521354149694563, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.8658880281075071}
{'probability': False, 'kernel': 'rbf', 'C': 103.30672064248806, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:03,287] Trial 59 finished with value: 0.8465121333165021 and parameters: {'kernel': 'rbf', 'C': 103.30672064248806, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,346] Trial 60 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 19.808966714070895, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,404] Trial 61 finished with value: 0.8605367463067533 and parameters: {'kernel': 'rbf', 'C': 24.549557876940025, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,461] Trial 62 finished with value: 0.8618491648390127 and parameters: {'kernel': 'rbf', 'C': 6.450240743000624, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 19.808966714070895, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 24.549557876940025, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 6.450240743000624, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 18.669291781256515, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:03,521] Trial 63 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 18.669291781256515, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,580] Trial 64 finished with value: 0.8605367463067533 and parameters: {'kernel': 'rbf', 'C': 46.06700461403682, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,640] Trial 65 finished with value: 0.8240788476202731 and parameters: {'kernel': 'rbf', 'C': 3.063742345225851, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,695] Trial 66 finished with value: 0.8113567235597838 and parameters: {'kernel': 'linear', 'C': 1.6860857156134752, 'class_weight': 'balanced'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 46.06700461403682, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'rbf', 'C': 3.063742345225851, 'class_weight': 'balanced', 'gamma': 'scale'}
{'probability': False, 'kernel': 'linear', 'C': 1.6860857156134752, 'class_weight': 'balanced'}
{'probability': False, 'kernel': 'rbf', 'C': 16.50143330733476, 'class_weight': 'balanced', 'gamma': 'scale'}

[I 2025-04-14 23:52:03,755] Trial 67 finished with value: 0.871852602710134 and parameters: {'kernel': 'rbf', 'C': 16.50143330733476, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,816] Trial 68 finished with value: 0.8283835202922253 and parameters: {'kernel': 'poly', 'C': 17.173273050821294, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.18445006258166863, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,874] Trial 69 finished with value: 0.5959646306992591 and parameters: {'kernel': 'sigmoid', 'C': 214.95150927160836, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8722651778310345}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:03,934] Trial 70 finished with value: 0.8765767925368123 and parameters: {'kernel': 'rbf', 'C': 75.41141551585864, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.060232341798408695}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 17.173273050821294, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.18445006258166863, 'degree': 5}
{'probability': False, 'kernel': 'sigmoid', 'C': 214.95150927160836, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.8722651778310345}
{'probability': False, 'kernel': 'rbf', 'C': 75.41141551585864, 'class_weight': 'balanced', 'gamma': 0.060232341798408695}
{'probability': False, 'kernel': 'rbf', 'C': 83.11836779102458, 'class_weight': 'balanced', 'gamma': 0.09071113362572715}

[I 2025-04-14 23:52:03,994] Trial 71 finished with value: 0.8686230626076294 and parameters: {'kernel': 'rbf', 'C': 83.11836779102458, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.09071113362572715}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,054] Trial 72 finished with value: 0.8637196823329075 and parameters: {'kernel': 'rbf', 'C': 34.825662368823565, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.4204687873881336}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,114] Trial 73 finished with value: 0.8722914651628564 and parameters: {'kernel': 'rbf', 'C': 524.769271834299, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.01385013758225868}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,178] Trial 74 finished with value: 0.8663754635851868 and parameters: {'kernel': 'rbf', 'C': 402.39031904677387, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.009409928767796063}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 34.825662368823565, 'class_weight': 'balanced', 'gamma': 0.4204687873881336}
{'probability': False, 'kernel': 'rbf', 'C': 524.769271834299, 'class_weight': 'balanced', 'gamma': 0.01385013758225868}
{'probability': False, 'kernel': 'rbf', 'C': 402.39031904677387, 'class_weight': 'balanced', 'gamma': 0.009409928767796063}
{'probability': False, 'kernel': 'rbf', 'C': 54.8671891241866, 'class_weight': 'balanced', 'gamma': 0.4667170195332378}

[I 2025-04-14 23:52:04,239] Trial 75 finished with value: 0.8566804092455678 and parameters: {'kernel': 'rbf', 'C': 54.8671891241866, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.4667170195332378}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,299] Trial 76 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 751.6502146592875, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.009190562980438672, 'coef0': 0.6818296529694197, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,358] Trial 77 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 986.4457088221999, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.008734713966418905, 'coef0': 0.705846844992829, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,417] Trial 78 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 488.34023200531624, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.011748227809485541, 'coef0': 0.6825606904346999, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 751.6502146592875, 'class_weight': 'balanced', 'gamma': 0.009190562980438672, 'coef0': 0.6818296529694197, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 986.4457088221999, 'class_weight': 'balanced', 'gamma': 0.008734713966418905, 'coef0': 0.705846844992829, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 488.34023200531624, 'class_weight': 'balanced', 'gamma': 0.011748227809485541, 'coef0': 0.6825606904346999, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 732.24296323595, 'class_weight': 'balanced', 'gamma': 0.010194346458576985, 'coef0': 0.68910927484323, 'degree': 5}

[I 2025-04-14 23:52:04,476] Trial 79 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 732.24296323595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.010194346458576985, 'coef0': 0.68910927484323, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,536] Trial 80 finished with value: 0.8390717377157834 and parameters: {'kernel': 'poly', 'C': 960.5660496686886, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002712777735863727, 'coef0': 0.5213961931257549, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,594] Trial 81 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 363.25086606818553, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.013282948696909885, 'coef0': 0.6941132175583161, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,657] Trial 82 finished with value: 0.8677110764624499 and parameters: {'kernel': 'poly', 'C': 490.80573178016004, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.04076642684398302, 'coef0': 0.8463621280281995, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 960.5660496686886, 'class_weight': 'balanced', 'gamma': 0.002712777735863727, 'coef0': 0.5213961931257549, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 363.25086606818553, 'class_weight': 'balanced', 'gamma': 0.013282948696909885, 'coef0': 0.6941132175583161, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 490.80573178016004, 'class_weight': 'balanced', 'gamma': 0.04076642684398302, 'coef0': 0.8463621280281995, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 590.8016210135518, 'class_weight': 'balanced', 'gamma': 0.014109466630918154, 'coef0': 0.8181384807676647, 'degree': 4}

[I 2025-04-14 23:52:04,717] Trial 83 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 590.8016210135518, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.014109466630918154, 'coef0': 0.8181384807676647, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,777] Trial 84 finished with value: 0.8390717377157834 and parameters: {'kernel': 'poly', 'C': 251.46750078674475, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0035391318773557215, 'coef0': 0.6641225568490682, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,840] Trial 85 finished with value: 0.8125515403650863 and parameters: {'kernel': 'poly', 'C': 484.3602673984085, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.15954073803586652, 'coef0': 0.748318813285656, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:04,900] Trial 86 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 135.4488484521029, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.020879921290750298, 'coef0': 0.9155397717506049, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 251.46750078674475, 'class_weight': 'balanced', 'gamma': 0.0035391318773557215, 'coef0': 0.6641225568490682, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 484.3602673984085, 'class_weight': 'balanced', 'gamma': 0.15954073803586652, 'coef0': 0.748318813285656, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 135.4488484521029, 'class_weight': 'balanced', 'gamma': 0.020879921290750298, 'coef0': 0.9155397717506049, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 245.03977764868122, 'class_weight': 'balanced', 'gamma': 0.004847975392345501, 'coef0': 0.8002699634480883, 'degree': 4}

[I 2025-04-14 23:52:04,959] Trial 87 finished with value: 0.8617515220833862 and parameters: {'kernel': 'poly', 'C': 245.03977764868122, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.004847975392345501, 'coef0': 0.8002699634480883, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,020] Trial 88 finished with value: 0.817052936633414 and parameters: {'kernel': 'poly', 'C': 604.646303662487, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.001091248294092157, 'coef0': 0.5489481667477661, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,079] Trial 89 finished with value: 0.8673893258739758 and parameters: {'kernel': 'poly', 'C': 858.9333520382957, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.02657412404125212, 'coef0': 0.652551267676139, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,140] Trial 90 finished with value: 0.8434918030040703 and parameters: {'kernel': 'poly', 'C': 113.29439396502227, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.18652217418376232, 'coef0': 0.4656948431980059, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 604.646303662487, 'class_weight': 'balanced', 'gamma': 0.001091248294092157, 'coef0': 0.5489481667477661, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 858.9333520382957, 'class_weight': 'balanced', 'gamma': 0.02657412404125212, 'coef0': 0.652551267676139, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 113.29439396502227, 'class_weight': 'balanced', 'gamma': 0.18652217418376232, 'coef0': 0.4656948431980059, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 621.5333619862448, 'class_weight': 'balanced', 'gamma': 0.006746890460044022, 'coef0': 0.7366479901496067, 'degree': 5}

[I 2025-04-14 23:52:05,199] Trial 91 finished with value: 0.8767547419990146 and parameters: {'kernel': 'poly', 'C': 621.5333619862448, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.006746890460044022, 'coef0': 0.7366479901496067, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,259] Trial 92 finished with value: 0.8598642293835592 and parameters: {'kernel': 'poly', 'C': 296.83080682558267, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.006048075568732424, 'coef0': 0.7438011437789178, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,318] Trial 93 finished with value: 0.8629139141459403 and parameters: {'kernel': 'poly', 'C': 187.5410714434079, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.02520793763568516, 'coef0': 0.7361524264787265, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,378] Trial 94 finished with value: 0.8133412071005274 and parameters: {'kernel': 'poly', 'C': 429.7965300726966, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0010759112808755894, 'coef0': 0.6489446844599686, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 296.83080682558267, 'class_weight': 'balanced', 'gamma': 0.006048075568732424, 'coef0': 0.7438011437789178, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 187.5410714434079, 'class_weight': 'balanced', 'gamma': 0.02520793763568516, 'coef0': 0.7361524264787265, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 429.7965300726966, 'class_weight': 'balanced', 'gamma': 0.0010759112808755894, 'coef0': 0.6489446844599686, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 539.0230198201108, 'class_weight': 'balanced', 'gamma': 0.007614021991859796, 'coef0': 0.7717225717230424, 'degree': 4}

[I 2025-04-14 23:52:05,439] Trial 95 finished with value: 0.8767547419990146 and parameters: {'kernel': 'poly', 'C': 539.0230198201108, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.007614021991859796, 'coef0': 0.7717225717230424, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,500] Trial 96 finished with value: 0.8577010939756742 and parameters: {'kernel': 'poly', 'C': 744.5212998535345, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.005907958653238416, 'coef0': 0.7778873461278873, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,565] Trial 97 finished with value: 0.8649524877647641 and parameters: {'kernel': 'poly', 'C': 978.0916434833756, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.03128490371192303, 'coef0': 0.9151924597569938, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,637] Trial 98 finished with value: 0.8187995320436396 and parameters: {'kernel': 'linear', 'C': 66.78577479117432, 'class_weight': 'balanced'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 744.5212998535345, 'class_weight': 'balanced', 'gamma': 0.005907958653238416, 'coef0': 0.7778873461278873, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 978.0916434833756, 'class_weight': None, 'gamma': 0.03128490371192303, 'coef0': 0.9151924597569938, 'degree': 3}
{'probability': False, 'kernel': 'linear', 'C': 66.78577479117432, 'class_weight': 'balanced'}
{'probability': False, 'kernel': 'sigmoid', 'C': 0.0014087956406772853, 'class_weight': 'balanced', 'gamma': 0.0018489834061451145, 'coef0': 0.8154547928636652}

[I 2025-04-14 23:52:05,710] Trial 99 finished with value: 0.2673900315409749 and parameters: {'kernel': 'sigmoid', 'C': 0.0014087956406772853, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0018489834061451145, 'coef0': 0.8154547928636652}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,776] Trial 100 finished with value: 0.8027426005550462 and parameters: {'kernel': 'poly', 'C': 608.229867184155, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00034973882590429075, 'coef0': 0.578754381284642, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:05,851] Trial 101 finished with value: 0.8598642293835592 and parameters: {'kernel': 'poly', 'C': 300.54712418218406, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00765583907583103, 'coef0': 0.6289097414855309, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 608.229867184155, 'class_weight': 'balanced', 'gamma': 0.00034973882590429075, 'coef0': 0.578754381284642, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 300.54712418218406, 'class_weight': 'balanced', 'gamma': 0.00765583907583103, 'coef0': 0.6289097414855309, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 556.4080025962231, 'class_weight': 'balanced', 'gamma': 0.014778828152220605, 'coef0': 0.7072322604507564, 'degree': 4}

[I 2025-04-14 23:52:05,922] Trial 102 finished with value: 0.8688407200735322 and parameters: {'kernel': 'poly', 'C': 556.4080025962231, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.014778828152220605, 'coef0': 0.7072322604507564, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,073] Trial 103 finished with value: 0.8084846196017608 and parameters: {'kernel': 'poly', 'C': 355.3339543556968, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0035568044387503284, 'coef0': 0.4187700691949113, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,142] Trial 104 finished with value: 0.8584900504584881 and parameters: {'kernel': 'poly', 'C': 147.30859350512003, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.06652662440315364, 'coef0': 0.562219768919497, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 355.3339543556968, 'class_weight': 'balanced', 'gamma': 0.0035568044387503284, 'coef0': 0.4187700691949113, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 147.30859350512003, 'class_weight': 'balanced', 'gamma': 0.06652662440315364, 'coef0': 0.562219768919497, 'degree': 3}
{'probability': False, 'kernel': 'poly', 'C': 214.1178749638425, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.4863057454118116, 'degree': 2}

[I 2025-04-14 23:52:06,208] Trial 105 finished with value: 0.863204034442461 and parameters: {'kernel': 'poly', 'C': 214.1178749638425, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4863057454118116, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,278] Trial 106 finished with value: 0.8640354366260957 and parameters: {'kernel': 'rbf', 'C': 460.04809593140453, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.05872366043834755}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,344] Trial 107 finished with value: 0.8681408731772472 and parameters: {'kernel': 'poly', 'C': 680.1284685548754, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0164870911842447, 'coef0': 0.7689128308589923, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 460.04809593140453, 'class_weight': 'balanced', 'gamma': 0.05872366043834755}
{'probability': False, 'kernel': 'poly', 'C': 680.1284685548754, 'class_weight': 'balanced', 'gamma': 0.0164870911842447, 'coef0': 0.7689128308589923, 'degree': 4}
{'probability': False, 'kernel': 'rbf', 'C': 0.0778179108770783, 'class_weight': 'balanced', 'gamma': 'auto'}

[I 2025-04-14 23:52:06,415] Trial 108 finished with value: 0.7801025542679679 and parameters: {'kernel': 'rbf', 'C': 0.0778179108770783, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,490] Trial 109 finished with value: 0.79356701509088 and parameters: {'kernel': 'poly', 'C': 8.500747065252224, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.007319672675787036, 'coef0': 0.6795664208898538, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,542] Trial 110 finished with value: 0.8198215684252835 and parameters: {'kernel': 'linear', 'C': 0.7454931608660339, 'class_weight': None}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,602] Trial 111 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 831.9552938608497, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.012984141598276645, 'coef0': 0.7255289310795348, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 8.500747065252224, 'class_weight': 'balanced', 'gamma': 0.007319672675787036, 'coef0': 0.6795664208898538, 'degree': 3}
{'probability': False, 'kernel': 'linear', 'C': 0.7454931608660339, 'class_weight': None}
{'probability': False, 'kernel': 'poly', 'C': 831.9552938608497, 'class_weight': 'balanced', 'gamma': 0.012984141598276645, 'coef0': 0.7255289310795348, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 710.496836978165, 'class_weight': 'balanced', 'gamma': 0.009745568160679225, 'coef0': 0.6242687102241917, 'degree': 5}

[I 2025-04-14 23:52:06,671] Trial 112 finished with value: 0.8722914651628564 and parameters: {'kernel': 'poly', 'C': 710.496836978165, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.009745568160679225, 'coef0': 0.6242687102241917, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,731] Trial 113 finished with value: 0.8205123778994531 and parameters: {'kernel': 'poly', 'C': 318.5653038653707, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0020255429179416567, 'coef0': 0.6871879980694213, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,792] Trial 114 finished with value: 0.8520425020510769 and parameters: {'kernel': 'poly', 'C': 452.5491452888511, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.04118347975916727, 'coef0': 0.7855019598411336, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,854] Trial 115 finished with value: 0.8145253350286339 and parameters: {'kernel': 'rbf', 'C': 29.704555290353564, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0046811195354831735}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 318.5653038653707, 'class_weight': 'balanced', 'gamma': 0.0020255429179416567, 'coef0': 0.6871879980694213, 'degree': 5}
{'probability': False, 'kernel': 'poly', 'C': 452.5491452888511, 'class_weight': 'balanced', 'gamma': 0.04118347975916727, 'coef0': 0.7855019598411336, 'degree': 5}
{'probability': False, 'kernel': 'rbf', 'C': 29.704555290353564, 'class_weight': 'balanced', 'gamma': 0.0046811195354831735}
{'probability': False, 'kernel': 'sigmoid', 'C': 731.9069203046379, 'class_weight': 'balanced', 'gamma': 0.010517555117553559, 'coef0': 0.839411599361573}

[I 2025-04-14 23:52:06,916] Trial 116 finished with value: 0.7131388888895313 and parameters: {'kernel': 'sigmoid', 'C': 731.9069203046379, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.010517555117553559, 'coef0': 0.839411599361573}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:06,979] Trial 117 finished with value: 0.838748072200622 and parameters: {'kernel': 'poly', 'C': 93.08252955290891, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.8935654755122736, 'degree': 5}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,042] Trial 118 finished with value: 0.863717009489795 and parameters: {'kernel': 'rbf', 'C': 997.57805571413, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.01947697114243863}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,106] Trial 119 finished with value: 0.8189111144119213 and parameters: {'kernel': 'poly', 'C': 254.37663358494657, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.5088801648712235, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 93.08252955290891, 'class_weight': 'balanced', 'gamma': 'auto', 'coef0': 0.8935654755122736, 'degree': 5}
{'probability': False, 'kernel': 'rbf', 'C': 997.57805571413, 'class_weight': 'balanced', 'gamma': 0.01947697114243863}
{'probability': False, 'kernel': 'poly', 'C': 254.37663358494657, 'class_weight': 'balanced', 'gamma': 'scale', 'coef0': 0.5088801648712235, 'degree': 4}
{'probability': False, 'kernel': 'rbf', 'C': 189.73329094403257, 'class_weight': 'balanced', 'gamma': 0.003005904273858143}

[I 2025-04-14 23:52:07,169] Trial 120 finished with value: 0.8244224672666466 and parameters: {'kernel': 'rbf', 'C': 189.73329094403257, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.003005904273858143}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,231] Trial 121 finished with value: 0.8767547419990146 and parameters: {'kernel': 'poly', 'C': 410.37713595119584, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.010396606273225058, 'coef0': 0.7161264448529869, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,290] Trial 122 finished with value: 0.8767547419990146 and parameters: {'kernel': 'poly', 'C': 507.68063283487606, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00807272670158321, 'coef0': 0.7093768728159994, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,378] Trial 123 finished with value: 0.8032816129859676 and parameters: {'kernel': 'poly', 'C': 358.02844090490566, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 1.7660434604689654, 'coef0': 0.7448417819164375, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 410.37713595119584, 'class_weight': 'balanced', 'gamma': 0.010396606273225058, 'coef0': 0.7161264448529869, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 507.68063283487606, 'class_weight': 'balanced', 'gamma': 0.00807272670158321, 'coef0': 0.7093768728159994, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 358.02844090490566, 'class_weight': 'balanced', 'gamma': 1.7660434604689654, 'coef0': 0.7448417819164375, 'degree': 4}

[I 2025-04-14 23:52:07,439] Trial 124 finished with value: 0.8587262180430619 and parameters: {'kernel': 'poly', 'C': 531.6686417046781, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.006842288251329677, 'coef0': 0.6464304160477191, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,502] Trial 125 finished with value: 0.8041049597316886 and parameters: {'kernel': 'poly', 'C': 11.477282691487414, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.009213747973294321, 'coef0': 0.6081391045718103, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,573] Trial 126 finished with value: 0.8447586272873195 and parameters: {'kernel': 'rbf', 'C': 138.13480589166167, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 531.6686417046781, 'class_weight': 'balanced', 'gamma': 0.006842288251329677, 'coef0': 0.6464304160477191, 'degree': 4}
{'probability': False, 'kernel': 'poly', 'C': 11.477282691487414, 'class_weight': 'balanced', 'gamma': 0.009213747973294321, 'coef0': 0.6081391045718103, 'degree': 4}
{'probability': False, 'kernel': 'rbf', 'C': 138.13480589166167, 'class_weight': None, 'gamma': 'scale'}
{'probability': False, 'kernel': 'poly', 'C': 537.4710371308134, 'class_weight': 'balanced', 'gamma': 0.01954076386274602, 'coef0': 0.7114177358814768, 'degree': 4}

[I 2025-04-14 23:52:07,639] Trial 127 finished with value: 0.8681408731772472 and parameters: {'kernel': 'poly', 'C': 537.4710371308134, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.01954076386274602, 'coef0': 0.7114177358814768, 'degree': 4}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,703] Trial 128 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 36.07418140026668, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,769] Trial 129 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 36.21999213227248, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,829] Trial 130 finished with value: 0.8654427994245876 and parameters: {'kernel': 'rbf', 'C': 44.94775827404789, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 36.07418140026668, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 36.21999213227248, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 44.94775827404789, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 36.69295718481956, 'class_weight': 'balanced', 'gamma': 'auto'}

[I 2025-04-14 23:52:07,888] Trial 131 finished with value: 0.8722953789918103 and parameters: {'kernel': 'rbf', 'C': 36.69295718481956, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:07,945] Trial 132 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 24.78940937234207, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,001] Trial 133 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 33.64945602710513, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,058] Trial 134 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 24.32691894354879, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 24.78940937234207, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 33.64945602710513, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 24.32691894354879, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 24.58816871945361, 'class_weight': 'balanced', 'gamma': 'auto'}

[I 2025-04-14 23:52:08,116] Trial 135 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 24.58816871945361, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,173] Trial 136 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 23.815818016198357, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,230] Trial 137 finished with value: 0.8730469262950817 and parameters: {'kernel': 'rbf', 'C': 22.065461442726566, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,287] Trial 138 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 22.77779616535172, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 23.815818016198357, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 22.065461442726566, 'class_weight': 'balanced', 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 22.77779616535172, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 24.354918401060814, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:08,344] Trial 139 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 24.354918401060814, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,402] Trial 140 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 25.041136040182053, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,458] Trial 141 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 23.890126316772303, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,514] Trial 142 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 58.24465677537013, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 25.041136040182053, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 23.890126316772303, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 58.24465677537013, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 14.039089524759786, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:08,570] Trial 143 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 14.039089524759786, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,627] Trial 144 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 25.372656529653554, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,684] Trial 145 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 25.858926932265305, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,740] Trial 146 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 67.23407591120306, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 25.372656529653554, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 25.858926932265305, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 67.23407591120306, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 11.590595009433793, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:08,797] Trial 147 finished with value: 0.8575205805213596 and parameters: {'kernel': 'rbf', 'C': 11.590595009433793, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,855] Trial 148 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 30.153061953068114, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,911] Trial 149 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 49.18608163221372, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:08,967] Trial 150 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 15.479836871204297, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 30.153061953068114, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 49.18608163221372, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 15.479836871204297, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 30.022369030778805, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:09,023] Trial 151 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 30.022369030778805, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,080] Trial 152 finished with value: 0.8773677503474744 and parameters: {'kernel': 'rbf', 'C': 32.08917582970552, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,143] Trial 153 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.523321223107352, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,199] Trial 154 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.97628940677337, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 32.08917582970552, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 29.523321223107352, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 29.97628940677337, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 45.586929381675375, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:09,257] Trial 155 finished with value: 0.8604303037985639 and parameters: {'kernel': 'rbf', 'C': 45.586929381675375, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,379] Trial 156 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 16.074550858807804, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,436] Trial 157 finished with value: 0.8531769930343572 and parameters: {'kernel': 'rbf', 'C': 74.92969528649607, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 16.074550858807804, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 74.92969528649607, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 8.967874632336537, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:09,493] Trial 158 finished with value: 0.8438318166725415 and parameters: {'kernel': 'rbf', 'C': 8.967874632336537, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,551] Trial 159 finished with value: 0.8449663355620274 and parameters: {'kernel': 'rbf', 'C': 6.4131654505187, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,622] Trial 160 finished with value: 0.8154601629443344 and parameters: {'kernel': 'linear', 'C': 55.10827020267385, 'class_weight': None}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,678] Trial 161 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.32936314306874, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 6.4131654505187, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'linear', 'C': 55.10827020267385, 'class_weight': None}
{'probability': False, 'kernel': 'rbf', 'C': 29.32936314306874, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 30.601918716858453, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:09,734] Trial 162 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 30.601918716858453, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,792] Trial 163 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 16.985176167180754, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,848] Trial 164 finished with value: 0.860900598553503 and parameters: {'kernel': 'rbf', 'C': 41.61657501716596, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:09,905] Trial 165 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 19.692997190121424, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 16.985176167180754, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 41.61657501716596, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 19.692997190121424, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'sigmoid', 'C': 11.839990685489957, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9542713066235111}

[I 2025-04-14 23:52:09,960] Trial 166 finished with value: 0.6540222444960647 and parameters: {'kernel': 'sigmoid', 'C': 11.839990685489957, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9542713066235111}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,019] Trial 167 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.76982777122871, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,075] Trial 168 finished with value: 0.8531769930343572 and parameters: {'kernel': 'rbf', 'C': 75.83306238070074, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,131] Trial 169 finished with value: 0.8644304647952337 and parameters: {'kernel': 'rbf', 'C': 39.28110613535757, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 27.76982777122871, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 75.83306238070074, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 39.28110613535757, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 0.35019831154163933, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:10,191] Trial 170 finished with value: 0.7438481140150396 and parameters: {'kernel': 'rbf', 'C': 0.35019831154163933, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,249] Trial 171 finished with value: 0.8725599621295481 and parameters: {'kernel': 'rbf', 'C': 32.50620503182927, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,305] Trial 172 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 28.011957066085362, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,362] Trial 173 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 20.007811830835642, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 32.50620503182927, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 28.011957066085362, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 20.007811830835642, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 54.65878160676007, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:10,420] Trial 174 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 54.65878160676007, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,477] Trial 175 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.465920818060628, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,534] Trial 176 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 18.952447115133538, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,592] Trial 177 finished with value: 0.8531769930343572 and parameters: {'kernel': 'rbf', 'C': 94.87179657348224, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 27.465920818060628, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 18.952447115133538, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 94.87179657348224, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 14.607764587591403, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:10,651] Trial 178 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 14.607764587591403, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,711] Trial 179 finished with value: 0.8481774083062685 and parameters: {'kernel': 'rbf', 'C': 10.077318389021563, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,769] Trial 180 finished with value: 0.860900598553503 and parameters: {'kernel': 'rbf', 'C': 40.21517507029225, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,827] Trial 181 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.52172598795311, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 10.077318389021563, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 40.21517507029225, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 27.52172598795311, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 32.305320607413734, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:10,888] Trial 182 finished with value: 0.8725599621295481 and parameters: {'kernel': 'rbf', 'C': 32.305320607413734, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:10,947] Trial 183 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 22.20062042585942, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,007] Trial 184 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 53.84338562864912, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,064] Trial 185 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.53560128264082, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 22.20062042585942, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 53.84338562864912, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 29.53560128264082, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'linear', 'C': 37.1122491362188, 'class_weight': None}

[I 2025-04-14 23:52:11,133] Trial 186 finished with value: 0.8154601629443344 and parameters: {'kernel': 'linear', 'C': 37.1122491362188, 'class_weight': None}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,200] Trial 187 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 13.985917908004172, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,257] Trial 188 finished with value: 0.672466358666486 and parameters: {'kernel': 'sigmoid', 'C': 20.215966208855225, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.35703661739455794}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,317] Trial 189 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 48.43090840344527, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 13.985917908004172, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'sigmoid', 'C': 20.215966208855225, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.35703661739455794}
{'probability': False, 'kernel': 'rbf', 'C': 48.43090840344527, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 30.75531885524106, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:11,376] Trial 190 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 30.75531885524106, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,435] Trial 191 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 25.655312079369796, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,494] Trial 192 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 17.56216677506501, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,552] Trial 193 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 28.89412362733134, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 25.655312079369796, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 17.56216677506501, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 28.89412362733134, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 41.96500485458631, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:11,610] Trial 194 finished with value: 0.860900598553503 and parameters: {'kernel': 'rbf', 'C': 41.96500485458631, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,668] Trial 195 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 22.646098986385393, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,731] Trial 196 finished with value: 0.4233049487844008 and parameters: {'kernel': 'rbf', 'C': 0.014252513750040361, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,791] Trial 197 finished with value: 0.8407896240955386 and parameters: {'kernel': 'rbf', 'C': 4.850943601634671, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 22.646098986385393, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 0.014252513750040361, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 4.850943601634671, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 12.642982061134962, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:11,851] Trial 198 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 12.642982061134962, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,909] Trial 199 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 66.24705595154906, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:11,966] Trial 200 finished with value: 0.8690741037256569 and parameters: {'kernel': 'rbf', 'C': 34.01502416552673, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,024] Trial 201 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 23.63401269424097, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 66.24705595154906, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 34.01502416552673, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 23.63401269424097, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 28.58543903826421, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:12,084] Trial 202 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 28.58543903826421, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,144] Trial 203 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 16.59444754058146, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,202] Trial 204 finished with value: 0.8570635826352326 and parameters: {'kernel': 'rbf', 'C': 44.313425459251064, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,260] Trial 205 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 28.291403804378007, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 16.59444754058146, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 44.313425459251064, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 28.291403804378007, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'poly', 'C': 21.17841792583351, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9997864553615555, 'degree': 3}

[I 2025-04-14 23:52:12,321] Trial 206 finished with value: 0.8611650444353255 and parameters: {'kernel': 'poly', 'C': 21.17841792583351, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9997864553615555, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,450] Trial 207 finished with value: 0.8565437141976887 and parameters: {'kernel': 'rbf', 'C': 55.66327179511993, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,508] Trial 208 finished with value: 0.8605934488769632 and parameters: {'kernel': 'rbf', 'C': 36.222521062880716, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 55.66327179511993, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 36.222521062880716, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'poly', 'C': 16.617301155607688, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.27229927344298316, 'degree': 2}

[I 2025-04-14 23:52:12,568] Trial 209 finished with value: 0.8609810970844437 and parameters: {'kernel': 'poly', 'C': 16.617301155607688, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.27229927344298316, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,626] Trial 210 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.27441651464114, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,683] Trial 211 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.349708163955654, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,740] Trial 212 finished with value: 0.8690741037256569 and parameters: {'kernel': 'rbf', 'C': 33.533816653323775, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 27.27441651464114, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 27.349708163955654, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 33.533816653323775, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 20.80897182877128, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:12,797] Trial 213 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 20.80897182877128, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,856] Trial 214 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 13.73343536197773, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,914] Trial 215 finished with value: 0.8604303037985639 and parameters: {'kernel': 'rbf', 'C': 44.80247438954987, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:12,970] Trial 216 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 23.022605941528774, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 13.73343536197773, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 44.80247438954987, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 23.022605941528774, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'poly', 'C': 29.93265104946683, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.4192273989034079, 'degree': 3}

[I 2025-04-14 23:52:13,027] Trial 217 finished with value: 0.8509804943487546 and parameters: {'kernel': 'poly', 'C': 29.93265104946683, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4192273989034079, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,092] Trial 218 finished with value: 0.860900598553503 and parameters: {'kernel': 'rbf', 'C': 41.34390420756904, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,146] Trial 219 finished with value: 0.8154601629443344 and parameters: {'kernel': 'linear', 'C': 8.484411281403085, 'class_weight': None}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,203] Trial 220 finished with value: 0.6628194530518583 and parameters: {'kernel': 'sigmoid', 'C': 71.27694294185683, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.12792482308414937}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 41.34390420756904, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'linear', 'C': 8.484411281403085, 'class_weight': None}
{'probability': False, 'kernel': 'sigmoid', 'C': 71.27694294185683, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.12792482308414937}
{'probability': False, 'kernel': 'rbf', 'C': 25.192586253445267, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:13,261] Trial 221 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 25.192586253445267, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,319] Trial 222 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.83377486056557, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,374] Trial 223 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 16.979793772371305, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,431] Trial 224 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 26.630792389364892, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 29.83377486056557, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 16.979793772371305, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 26.630792389364892, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 36.434080071235066, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:13,489] Trial 225 finished with value: 0.8605934488769632 and parameters: {'kernel': 'rbf', 'C': 36.434080071235066, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,546] Trial 226 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 21.103814080368096, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,604] Trial 227 finished with value: 0.8396781982437568 and parameters: {'kernel': 'rbf', 'C': 420.0209414655204, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,663] Trial 228 finished with value: 0.85061502540609 and parameters: {'kernel': 'poly', 'C': 55.274231468240764, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9345044875680236, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 21.103814080368096, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 420.0209414655204, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'poly', 'C': 55.274231468240764, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9345044875680236, 'degree': 3}
{'probability': False, 'kernel': 'rbf', 'C': 19.366973894080044, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:13,722] Trial 229 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 19.366973894080044, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,786] Trial 230 finished with value: 0.6138864376487777 and parameters: {'kernel': 'rbf', 'C': 34.57492459803407, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.00034185997922462084}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,843] Trial 231 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 23.58619335739135, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:13,900] Trial 232 finished with value: 0.8646949106770562 and parameters: {'kernel': 'rbf', 'C': 13.791121424095483, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 34.57492459803407, 'class_weight': None, 'gamma': 0.00034185997922462084}
{'probability': False, 'kernel': 'rbf', 'C': 23.58619335739135, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 13.791121424095483, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 27.200404431964497, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:13,958] Trial 233 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 27.200404431964497, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,015] Trial 234 finished with value: 0.8683672270612368 and parameters: {'kernel': 'rbf', 'C': 18.93112727490513, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,072] Trial 235 finished with value: 0.860900598553503 and parameters: {'kernel': 'rbf', 'C': 40.2331013557456, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,129] Trial 236 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 24.916566046067867, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 18.93112727490513, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 40.2331013557456, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 24.916566046067867, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'poly', 'C': 16.970452793798977, 'class_weight': None, 'gamma': 0.1865273236054845, 'coef0': 0.8395764271498799, 'degree': 3}

[I 2025-04-14 23:52:14,190] Trial 237 finished with value: 0.8474506281070238 and parameters: {'kernel': 'poly', 'C': 16.970452793798977, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.1865273236054845, 'coef0': 0.8395764271498799, 'degree': 3}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,248] Trial 238 finished with value: 0.8773677503474744 and parameters: {'kernel': 'rbf', 'C': 31.235564781667907, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,304] Trial 239 finished with value: 0.8639601700402945 and parameters: {'kernel': 'rbf', 'C': 34.401685574678794, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,360] Trial 240 finished with value: 0.8604303037985639 and parameters: {'kernel': 'rbf', 'C': 44.51710574880995, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 31.235564781667907, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 34.401685574678794, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 44.51710574880995, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 30.448411161429792, 'class_weight': None, 'gamma': 'auto'}

[I 2025-04-14 23:52:14,418] Trial 241 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 30.448411161429792, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,476] Trial 242 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 22.54720202359266, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,533] Trial 243 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 29.782078341180075, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,589] Trial 244 finished with value: 0.8734172365755322 and parameters: {'kernel': 'rbf', 'C': 21.539583107351195, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'rbf', 'C': 22.54720202359266, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 29.782078341180075, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 21.539583107351195, 'class_weight': None, 'gamma': 'auto'}
{'probability': False, 'kernel': 'rbf', 'C': 51.33656926141939, 'class_weight': None, 'gamma': 0.0006651537879867745}

[I 2025-04-14 23:52:14,653] Trial 245 finished with value: 0.7889904790189138 and parameters: {'kernel': 'rbf', 'C': 51.33656926141939, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.0006651537879867745}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,711] Trial 246 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 10.899045976296588, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8757593860067583, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,775] Trial 247 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.616895046045906, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8689553804804371, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,833] Trial 248 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.31459572244277, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8567699627238253, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 10.899045976296588, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8757593860067583, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.616895046045906, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8689553804804371, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.31459572244277, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8567699627238253, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 10.830590910320478, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8714397317189997, 'degree': 2}

[I 2025-04-14 23:52:14,894] Trial 249 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 10.830590910320478, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8714397317189997, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:14,954] Trial 250 finished with value: 0.8429265248241379 and parameters: {'kernel': 'poly', 'C': 5.418478232382826, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.10804509283182033, 'coef0': 0.8771726029241492, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,011] Trial 251 finished with value: 0.8505964242653518 and parameters: {'kernel': 'poly', 'C': 7.645083050820829, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8082569609416327, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,069] Trial 252 finished with value: 0.8505964242653518 and parameters: {'kernel': 'poly', 'C': 7.702763250637201, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8972288949439001, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 5.418478232382826, 'class_weight': None, 'gamma': 0.10804509283182033, 'coef0': 0.8771726029241492, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 7.645083050820829, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8082569609416327, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 7.702763250637201, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8972288949439001, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 10.816014845656577, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8589786875637153, 'degree': 2}

[I 2025-04-14 23:52:15,129] Trial 253 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 10.816014845656577, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8589786875637153, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,194] Trial 254 finished with value: 0.872880442314604 and parameters: {'kernel': 'poly', 'C': 10.500863187822532, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.4866352000767608, 'coef0': 0.8548074672078695, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,252] Trial 255 finished with value: 0.8658569326184892 and parameters: {'kernel': 'poly', 'C': 10.125941094743094, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8282674978879362, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,309] Trial 256 finished with value: 0.8658569326184892 and parameters: {'kernel': 'poly', 'C': 10.586796796430718, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7931629517083777, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 10.500863187822532, 'class_weight': None, 'gamma': 0.4866352000767608, 'coef0': 0.8548074672078695, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 10.125941094743094, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8282674978879362, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 10.586796796430718, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.7931629517083777, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.305749184701469, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8766174450545418, 'degree': 2}

[I 2025-04-14 23:52:15,370] Trial 257 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 13.305749184701469, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8766174450545418, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,497] Trial 258 finished with value: 0.872787879510177 and parameters: {'kernel': 'poly', 'C': 11.055717130851967, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.29562826186375524, 'coef0': 0.8742982817166409, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,555] Trial 259 finished with value: 0.8558233832966585 and parameters: {'kernel': 'poly', 'C': 6.346769194610414, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9434489248353441, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 11.055717130851967, 'class_weight': None, 'gamma': 0.29562826186375524, 'coef0': 0.8742982817166409, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 6.346769194610414, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9434489248353441, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.757068702656301, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9020069244748506, 'degree': 2}

[I 2025-04-14 23:52:15,615] Trial 260 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.757068702656301, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9020069244748506, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,674] Trial 261 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.715888809303971, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.907512689949339, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,733] Trial 262 finished with value: 0.8520873274392525 and parameters: {'kernel': 'poly', 'C': 9.102756182292952, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.07627499114286251, 'coef0': 0.917053920700701, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,790] Trial 263 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.08238368635916, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8592240619584074, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.715888809303971, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.907512689949339, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 9.102756182292952, 'class_weight': None, 'gamma': 0.07627499114286251, 'coef0': 0.917053920700701, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.08238368635916, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8592240619584074, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.229666358610844, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.89437695919679, 'degree': 2}

[I 2025-04-14 23:52:15,857] Trial 264 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.229666358610844, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.89437695919679, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,917] Trial 265 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.891531159955894, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9010843509806312, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:15,975] Trial 266 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.96275739661852, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8893934460102775, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,033] Trial 267 finished with value: 0.8011605902530536 and parameters: {'kernel': 'poly', 'C': 3.8211882571392377, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.040516718786782306, 'coef0': 0.8881237080446651, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.891531159955894, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9010843509806312, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.96275739661852, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8893934460102775, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 3.8211882571392377, 'class_weight': None, 'gamma': 0.040516718786782306, 'coef0': 0.8881237080446651, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.386951203769364, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8587396568241932, 'degree': 2}

[I 2025-04-14 23:52:16,090] Trial 268 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.386951203769364, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8587396568241932, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,149] Trial 269 finished with value: 0.8558233832966585 and parameters: {'kernel': 'poly', 'C': 7.086980253299003, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8639800329251128, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,206] Trial 270 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.657793216709626, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9065225328809795, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,267] Trial 271 finished with value: 0.7003823415799924 and parameters: {'kernel': 'poly', 'C': 13.187413470293267, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.0013091603579816367, 'coef0': 0.91008895586241, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 7.086980253299003, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8639800329251128, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.657793216709626, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9065225328809795, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.187413470293267, 'class_weight': None, 'gamma': 0.0013091603579816367, 'coef0': 0.91008895586241, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 9.51688892281589, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8628484703353416, 'degree': 2}

[I 2025-04-14 23:52:16,325] Trial 272 finished with value: 0.8658569326184892 and parameters: {'kernel': 'poly', 'C': 9.51688892281589, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8628484703353416, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,385] Trial 273 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.720984537523218, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.931322884861543, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,443] Trial 274 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.29306574595813, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9295997626068058, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,503] Trial 275 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.655296502089803, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9362258534786045, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.720984537523218, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.931322884861543, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.29306574595813, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9295997626068058, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.655296502089803, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9362258534786045, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 7.524216342786322, 'class_weight': None, 'gamma': 1.0243542857752888, 'coef0': 0.9295348412573199, 'degree': 2}

[I 2025-04-14 23:52:16,573] Trial 276 finished with value: 0.8693505760728735 and parameters: {'kernel': 'poly', 'C': 7.524216342786322, 'class_weight': None, 'gamma_type': 'float', 'gamma': 1.0243542857752888, 'coef0': 0.9295348412573199, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,633] Trial 277 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.739944062063165, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8940024610087753, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,690] Trial 278 finished with value: 0.8508131726671527 and parameters: {'kernel': 'poly', 'C': 5.429485543164978, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8945195287945977, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,748] Trial 279 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.611148183503483, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9668299060342767, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.739944062063165, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8940024610087753, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 5.429485543164978, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8945195287945977, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.611148183503483, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9668299060342767, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.773898419660444, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9636860385124538, 'degree': 2}

[I 2025-04-14 23:52:16,807] Trial 280 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.773898419660444, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9636860385124538, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,866] Trial 281 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.673581162530537, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9554128300585532, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,926] Trial 282 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.879966881776634, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9668428732030991, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:16,985] Trial 283 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.250227317191715, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9732180759877029, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.673581162530537, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9554128300585532, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.879966881776634, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9668428732030991, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.250227317191715, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9732180759877029, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 11.963258041196138, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.966919152984293, 'degree': 2}

[I 2025-04-14 23:52:17,047] Trial 284 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 11.963258041196138, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.966919152984293, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,108] Trial 285 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.301056822016703, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9714270198277711, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,169] Trial 286 finished with value: 0.8611959156693366 and parameters: {'kernel': 'poly', 'C': 8.75914626621431, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9559514163018782, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,228] Trial 287 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.133626364115873, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9943021851902748, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.301056822016703, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9714270198277711, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 8.75914626621431, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9559514163018782, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 12.133626364115873, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9943021851902748, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 9.88779922911823, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9736451929123882, 'degree': 2}

[I 2025-04-14 23:52:17,290] Trial 288 finished with value: 0.8710838916497962 and parameters: {'kernel': 'poly', 'C': 9.88779922911823, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9736451929123882, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,353] Trial 289 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 12.347743862119522, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9275371015444155, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,410] Trial 290 finished with value: 0.8558233832966585 and parameters: {'kernel': 'poly', 'C': 6.714550718673106, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9483636902375632, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,467] Trial 291 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 13.095881235949397, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8928763100457288, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 12.347743862119522, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9275371015444155, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 6.714550718673106, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9483636902375632, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.095881235949397, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8928763100457288, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 8.935215075984095, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9145176886245451, 'degree': 2}

[I 2025-04-14 23:52:17,525] Trial 292 finished with value: 0.8658569326184892 and parameters: {'kernel': 'poly', 'C': 8.935215075984095, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9145176886245451, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,585] Trial 293 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 13.714965146455887, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9550122303526158, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,645] Trial 294 finished with value: 0.8505964242653518 and parameters: {'kernel': 'poly', 'C': 7.678258793747142, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9374353815764253, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,706] Trial 295 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 13.085291150047384, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9086887246283899, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 13.714965146455887, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9550122303526158, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 7.678258793747142, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9374353815764253, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.085291150047384, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9086887246283899, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 9.643300639988459, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8785076611416786, 'degree': 2}

[I 2025-04-14 23:52:17,768] Trial 296 finished with value: 0.8658569326184892 and parameters: {'kernel': 'poly', 'C': 9.643300639988459, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8785076611416786, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,829] Trial 297 finished with value: 0.8521061583812768 and parameters: {'kernel': 'poly', 'C': 5.818113224340252, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9839130335529036, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,890] Trial 298 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 13.826246970439835, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.848188873413308, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:17,950] Trial 299 finished with value: 0.8782582218054927 and parameters: {'kernel': 'poly', 'C': 10.296217131018246, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.957136274898944, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 5.818113224340252, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9839130335529036, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 13.826246970439835, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.848188873413308, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 10.296217131018246, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.957136274898944, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 15.669617356942982, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9284153910076138, 'degree': 2}

[I 2025-04-14 23:52:18,012] Trial 300 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 15.669617356942982, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9284153910076138, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,074] Trial 301 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 15.23781114692982, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9043586577304755, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,135] Trial 302 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 16.48550266591709, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8993369780793108, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,196] Trial 303 finished with value: 0.8385239017248766 and parameters: {'kernel': 'poly', 'C': 2.952858254551116, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9023656297073891, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 15.23781114692982, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9043586577304755, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 16.48550266591709, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8993369780793108, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 2.952858254551116, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.9023656297073891, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 15.724956833658473, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8808680061344845, 'degree': 2}

[I 2025-04-14 23:52:18,256] Trial 304 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 15.724956833658473, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8808680061344845, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,318] Trial 305 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 14.813066484757773, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8790291685828211, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,378] Trial 306 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 15.618283680448743, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.875313016627218, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.
[I 2025-04-14 23:52:18,439] Trial 307 finished with value: 0.8820456651349314 and parameters: {'kernel': 'poly', 'C': 15.681425651922781, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8698375866879595, 'degree': 2}. Best is trial 14 with value: 0.8870956746492266.

{'probability': False, 'kernel': 'poly', 'C': 14.813066484757773, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8790291685828211, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 15.618283680448743, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.875313016627218, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 15.681425651922781, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8698375866879595, 'degree': 2}
{'probability': False, 'kernel': 'poly', 'C': 15.877764323826812, 'class_weight': None, 'gamma': 'auto', 'coef0': 0.8605262094022169, 'degree': 2}