Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-smote_default-model'
add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
n_trials = 50

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=best_params,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )
    
    
def optimize_smote_grid(
    target:str,
    estimator:object,
    estimator_params:dict,
    param_grid:dict=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=True,
):
    """
    Optimize the SMOTE parameters with GridSearchOptimizer for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics
    )
    
    if param_grid is None:
        param_grid = {
        'sampling_strategy': [0.6, 0.7, 0.8, 0.9, 1.0, 'auto'],
        'k_neighbors': list(range(2,11)),
    }
    opt = GridSearchOptimizer(
        objective=partial(pure_smote_objective, ml_pipe=ml_pipe),
        param_grid=param_grid,
        verbose=True,
    )

    opt.optimize()
    best_params = opt.best_params

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=best_params,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    n_trials=n_trials,
    save_model_and_metrics=False,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-13 13:51:52,892] A new study created in memory with name: smote_study
[I 2025-04-13 13:51:53,058] Trial 0 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.7795918367346939.
[I 2025-04-13 13:51:53,218] Trial 1 finished with value: 0.7826336975273146 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.7826336975273146.
[I 2025-04-13 13:51:53,390] Trial 2 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 2 with value: 0.800925925925926.
[I 2025-04-13 13:51:53,551] Trial 3 finished with value: 0.7826336975273146 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 2 with value: 0.800925925925926.
[I 2025-04-13 13:51:53,710] Trial 4 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:53,870] Trial 5 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,034] Trial 6 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,186] Trial 7 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,352] Trial 8 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,504] Trial 9 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,671] Trial 10 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:54,842] Trial 11 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,005] Trial 12 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,177] Trial 13 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,337] Trial 14 finished with value: 0.7980769230769231 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,522] Trial 15 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,686] Trial 16 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:55,840] Trial 17 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:56,005] Trial 18 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:56,154] Trial 19 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:56,305] Trial 20 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:56,483] Trial 21 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8055555555555556.
[I 2025-04-13 13:51:56,684] Trial 22 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:56,854] Trial 23 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,024] Trial 24 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,189] Trial 25 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,353] Trial 26 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,511] Trial 27 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,694] Trial 28 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:57,859] Trial 29 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,028] Trial 30 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,185] Trial 31 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,345] Trial 32 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,512] Trial 33 finished with value: 0.7888707037643208 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,680] Trial 34 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:58,844] Trial 35 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,008] Trial 36 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,169] Trial 37 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,327] Trial 38 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,484] Trial 39 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,644] Trial 40 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,828] Trial 41 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:51:59,993] Trial 42 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,154] Trial 43 finished with value: 0.7795918367346939 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,315] Trial 44 finished with value: 0.8088888888888889 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,476] Trial 45 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,642] Trial 46 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,794] Trial 47 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:00,961] Trial 48 finished with value: 0.8055555555555556 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 22 with value: 0.8088888888888889.
[I 2025-04-13 13:52:01,122] Trial 49 finished with value: 0.800925925925926 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9}. Best is trial 22 with value: 0.8088888888888889.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.6}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.883488
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

In [7]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:09,  5.68it/s]

Progress: 1/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:08,  6.32it/s]

Progress: 2/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:08,  6.12it/s]

Progress: 3/54.	Score: 0.7865416436845009.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:08,  6.24it/s]

Progress: 4/54.	Score: 0.7865416436845009.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:00<00:07,  6.38it/s]

Progress: 5/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:00<00:07,  6.47it/s]

Progress: 6/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:07,  6.53it/s]

Progress: 7/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:07,  6.29it/s]

Progress: 8/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:01<00:07,  6.28it/s]

Progress: 9/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:01<00:06,  6.35it/s]

Progress: 10/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:01<00:06,  6.29it/s]

Progress: 11/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:06,  6.35it/s]

Progress: 12/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:02<00:06,  6.45it/s]

Progress: 13/54.	Score: 0.8023529411764707.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:02<00:06,  6.40it/s]

Progress: 14/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:02<00:06,  6.37it/s]

Progress: 15/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:02<00:05,  6.45it/s]

Progress: 16/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:02<00:05,  6.60it/s]

Progress: 17/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:02<00:05,  6.62it/s]

Progress: 18/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:02<00:05,  6.63it/s]

Progress: 19/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:03<00:05,  6.36it/s]

Progress: 20/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:03<00:05,  5.93it/s]

Progress: 21/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:03<00:05,  6.13it/s]

Progress: 22/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:03<00:04,  6.29it/s]

Progress: 23/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:03<00:04,  6.39it/s]

Progress: 24/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:03<00:04,  6.47it/s]

Progress: 25/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:04<00:04,  6.52it/s]

Progress: 26/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:04<00:04,  6.56it/s]

Progress: 27/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:04<00:03,  6.52it/s]

Progress: 28/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:04<00:03,  6.36it/s]

Progress: 29/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:04<00:03,  6.42it/s]

Progress: 30/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:04<00:03,  6.51it/s]

Progress: 31/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:05<00:03,  6.55it/s]

Progress: 32/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:05<00:03,  6.59it/s]

Progress: 33/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:05<00:03,  6.61it/s]

Progress: 34/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:05<00:02,  6.49it/s]

Progress: 35/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:05<00:02,  6.54it/s]

Progress: 36/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:05<00:02,  6.57it/s]

Progress: 37/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:05<00:02,  6.59it/s]

Progress: 38/54.	Score: 0.7826336975273146.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:06<00:02,  6.62it/s]

Progress: 39/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:06<00:02,  6.63it/s]

Progress: 40/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:06<00:02,  6.39it/s]

Progress: 41/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:06<00:01,  6.34it/s]

Progress: 42/54.	Score: 0.7888707037643208.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:06<00:01,  6.13it/s]

Progress: 43/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:06<00:01,  6.28it/s]

Progress: 44/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:07<00:01,  6.39it/s]

Progress: 45/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:07<00:01,  6.54it/s]

Progress: 46/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:07<00:01,  6.58it/s]

Progress: 47/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:07<00:00,  6.40it/s]

Progress: 48/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:07<00:00,  6.42it/s]

Progress: 49/54.	Score: 0.7795918367346939.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:07<00:00,  6.28it/s]

Progress: 50/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:07<00:00,  6.37it/s]

Progress: 51/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:08<00:00,  6.27it/s]

Progress: 52/54.	Score: 0.800925925925926.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:08<00:00,  6.39it/s]

Progress: 53/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:08<00:00,  6.37it/s]

Progress: 54/54.	Score: 0.8055555555555556.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8088888888888889
Best params: {'k_neighbors': 9, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.883488
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.763393
cv_test_accuracy_balanced_median                                            0.77709
cv_test_roc_auc_median                                                     0.874613
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                    0.773585
cv_test_precision_class_0_median                                           0.652174
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.714286

Model saved in ..\results\models_modelling4\LogisticRegression_splashing_smote_opt-smote_default-model

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:07,  7.55it/s]

Progress: 1/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:06,  7.85it/s]

Progress: 2/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:06,  7.36it/s]

Progress: 3/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:06,  7.37it/s]

Progress: 4/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:00<00:06,  7.38it/s]

Progress: 5/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:00<00:06,  7.26it/s]

Progress: 6/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:00<00:06,  6.93it/s]

Progress: 7/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 8/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:07,  6.16it/s]

Optimizing parameters:  19%|█▊        | 10/54 [00:01<00:07,  5.93it/s]

Progress: 9/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:06,  6.44it/s]

Progress: 11/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  26%|██▌       | 14/54 [00:02<00:05,  6.75it/s]

Progress: 13/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  30%|██▉       | 16/54 [00:02<00:05,  7.34it/s]

Progress: 15/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  33%|███▎      | 18/54 [00:02<00:04,  7.47it/s]

Progress: 17/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:02<00:04,  7.48it/s]

Progress: 19/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  41%|████      | 22/54 [00:03<00:04,  6.95it/s]

Progress: 21/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  44%|████▍     | 24/54 [00:03<00:04,  7.04it/s]

Progress: 23/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  48%|████▊     | 26/54 [00:03<00:04,  6.65it/s]

Progress: 25/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 26/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:04<00:03,  7.03it/s]

Progress: 27/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:04<00:03,  7.17it/s]

Progress: 29/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:04<00:02,  7.39it/s]

Progress: 31/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:04<00:02,  7.30it/s]

Progress: 33/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:05<00:02,  7.35it/s]

Progress: 35/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  70%|███████   | 38/54 [00:05<00:02,  7.23it/s]

Progress: 37/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 38/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:05<00:02,  7.17it/s]

Progress: 39/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 40/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:06<00:01,  6.65it/s]

Progress: 41/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 42/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:06<00:01,  7.05it/s]

Progress: 43/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:06<00:01,  7.28it/s]

Progress: 45/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:06<00:00,  7.57it/s]

Progress: 47/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:07<00:00,  7.65it/s]

Progress: 49/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 50/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:07<00:00,  7.84it/s]

Progress: 51/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 54/54 [00:07<00:00,  7.08it/s]

Progress: 53/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
Progress: 54/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8392857142857143
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.785539
holdout_test_accuracy_balanced                                                0.825
holdout_test_roc_auc                                                       0.955455
holdout_test_f1                                                            0.708333
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.864469
cv_test_roc_auc_median                                                     0.946886
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.794872
cv_test_f1_class_0_median                                                  0.885714

Model saved in ..\results\models_modelling4\LogisticRegression_no_fragmentation_smote_opt-smote_default-model

# KNClassifier

In [9]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:11,  4.61it/s]

Progress: 1/54.	Score: 0.7857142857142857.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:12,  4.08it/s]

Progress: 2/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:11,  4.31it/s]

Progress: 3/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:11,  4.28it/s]

Progress: 4/54.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:11,  4.29it/s]

Progress: 5/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:10,  4.41it/s]

Progress: 6/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:10,  4.45it/s]

Progress: 7/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:10,  4.39it/s]

Progress: 8/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:10,  4.41it/s]

Progress: 9/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:09,  4.43it/s]

Progress: 10/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:09,  4.50it/s]

Progress: 11/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:02<00:09,  4.53it/s]

Progress: 12/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:02<00:09,  4.53it/s]

Progress: 13/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:08,  4.55it/s]

Progress: 14/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:08,  4.51it/s]

Progress: 15/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:08,  4.60it/s]

Progress: 16/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:03<00:08,  4.51it/s]

Progress: 17/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:04<00:08,  4.28it/s]

Progress: 18/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:04<00:08,  4.23it/s]

Progress: 19/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:08,  4.25it/s]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:04<00:07,  4.27it/s]

Progress: 21/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:05<00:07,  4.17it/s]

Progress: 22/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:05<00:07,  4.20it/s]

Progress: 23/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:05<00:06,  4.32it/s]

Progress: 24/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:05<00:07,  4.13it/s]

Progress: 25/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:06<00:06,  4.09it/s]

Progress: 26/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:06<00:06,  4.03it/s]

Progress: 27/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:06<00:06,  3.95it/s]

Progress: 28/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:06<00:06,  3.97it/s]

Progress: 29/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:07<00:05,  4.07it/s]

Progress: 30/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:07<00:05,  4.20it/s]

Progress: 31/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:07<00:05,  4.16it/s]

Progress: 32/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:07<00:05,  4.19it/s]

Progress: 33/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:07<00:04,  4.14it/s]

Progress: 34/54.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:08<00:04,  4.11it/s]

Progress: 35/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:08<00:04,  4.14it/s]

Progress: 36/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:08<00:04,  4.09it/s]

Progress: 37/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:08<00:03,  4.15it/s]

Progress: 38/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:09<00:03,  4.19it/s]

Progress: 39/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:09<00:03,  4.21it/s]

Progress: 40/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:09<00:03,  4.24it/s]

Progress: 41/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:09<00:02,  4.16it/s]

Progress: 42/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:10<00:02,  4.03it/s]

Progress: 43/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:10<00:02,  4.01it/s]

Progress: 44/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:10<00:02,  4.07it/s]

Progress: 45/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:10<00:01,  4.07it/s]

Progress: 46/54.	Score: 0.7980769230769231.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:11<00:01,  4.13it/s]

Progress: 47/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:11<00:01,  4.09it/s]

Progress: 48/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:11<00:01,  3.98it/s]

Progress: 49/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:11<00:00,  4.11it/s]

Progress: 50/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:12<00:00,  4.10it/s]

Progress: 51/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:12<00:00,  4.17it/s]

Progress: 52/54.	Score: 0.8088888888888889.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:12<00:00,  4.19it/s]

Progress: 53/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:12<00:00,  4.21it/s]

Progress: 54/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8683385579937304
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smote_opt-smote...
holdout_test_f1_macro                                                      0.810348
holdout_test_accuracy_balanced                                              0.80787
holdout_test_roc_auc                                                       0.874228
holdout_test_f1                                                            0.865979
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.835913
cv_test_accuracy_balanced_median                                           0.844427
cv_test_roc_auc_median                                                     0.918731
cv_test_f1_median                                                          0.882353
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                               0.75
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.790698

Model saved in ..\results\models_modelling4\KNeighborsClassifier_splashing_smote_opt-smote_default-model

In [10]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:10,  5.02it/s]

Progress: 1/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:10,  5.00it/s]

Progress: 2/54.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:10,  4.96it/s]

Progress: 3/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:10,  4.87it/s]

Progress: 4/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:10,  4.81it/s]

Progress: 5/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:10,  4.59it/s]

Progress: 6/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:09,  4.71it/s]

Progress: 7/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:10,  4.47it/s]

Progress: 8/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:01<00:10,  4.43it/s]

Progress: 9/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:10,  4.35it/s]

Progress: 10/54.	Score: 0.7658802177858439.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:09,  4.35it/s]

Progress: 11/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:02<00:09,  4.46it/s]

Progress: 12/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:02<00:08,  4.56it/s]

Progress: 13/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:08,  4.58it/s]

Progress: 14/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 15/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:08,  4.73it/s]

Progress: 16/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:03<00:08,  4.59it/s]

Progress: 17/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:03<00:07,  4.66it/s]

Progress: 18/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:04<00:07,  4.66it/s]

Progress: 19/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:07,  4.63it/s]

Progress: 20/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:04<00:07,  4.52it/s]

Progress: 21/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:04<00:07,  4.31it/s]

Progress: 22/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:05<00:07,  4.34it/s]

Progress: 23/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:05<00:06,  4.52it/s]

Progress: 24/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:05<00:06,  4.43it/s]

Progress: 25/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  50%|█████     | 27/54 [00:05<00:05,  4.64it/s]

Progress: 26/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 27/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:06<00:05,  4.78it/s]

Progress: 28/54.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 29/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:06<00:05,  4.50it/s]

Progress: 30/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:06<00:04,  4.67it/s]

Progress: 31/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.7881773399014779.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:07<00:04,  4.73it/s]

Progress: 33/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:07<00:04,  4.64it/s]

Progress: 34/54.	Score: 0.7904490377761939.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:07<00:04,  4.71it/s]

Progress: 35/54.	Score: 0.8089668615984404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:07<00:03,  4.77it/s]

Progress: 36/54.	Score: 0.8089668615984404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:08<00:03,  4.73it/s]

Progress: 37/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:08<00:03,  4.73it/s]

Progress: 38/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 39/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:08<00:02,  4.91it/s]

Progress: 40/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.
Progress: 41/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:09<00:02,  4.82it/s]

Progress: 42/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:09<00:02,  4.68it/s]

Progress: 43/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:09<00:02,  4.52it/s]

Progress: 44/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.
Progress: 45/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:10<00:01,  4.81it/s]

Progress: 46/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 47/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  91%|█████████ | 49/54 [00:10<00:01,  4.82it/s]

Progress: 48/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.
Progress: 49/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:10<00:00,  4.83it/s]

Progress: 50/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:10<00:00,  4.70it/s]

Progress: 51/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.8464285714285714.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:11<00:00,  4.78it/s]

Progress: 53/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:11<00:00,  4.65it/s]

Progress: 54/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8699334543254689
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.780518
holdout_test_accuracy_balanced                                             0.809091
holdout_test_roc_auc                                                       0.937273
holdout_test_f1                                                            0.695652
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.928571
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.918919

Model saved in ..\results\models_modelling4\KNeighborsClassifier_no_fragmentation_smote_opt-smote_default-model

# SVC

In [11]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:11,  4.44it/s]

Progress: 1/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:11,  4.51it/s]

Progress: 2/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:11,  4.36it/s]

Progress: 3/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:11,  4.34it/s]

Progress: 4/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:12,  4.05it/s]

Progress: 5/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:10,  4.34it/s]

Progress: 6/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.
Progress: 7/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:10,  4.34it/s]

Progress: 8/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:10,  4.33it/s]

Progress: 9/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:10,  4.38it/s]

Progress: 10/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:09,  4.33it/s]

Progress: 11/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:02<00:09,  4.37it/s]

Progress: 12/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.
Progress: 13/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:09,  4.42it/s]

Progress: 14/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:08,  4.46it/s]

Progress: 15/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:08,  4.42it/s]

Progress: 16/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:03<00:08,  4.39it/s]

Progress: 17/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:04<00:08,  4.44it/s]

Progress: 18/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:04<00:07,  4.56it/s]

Progress: 19/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:07,  4.64it/s]

Progress: 20/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:04<00:07,  4.54it/s]

Progress: 21/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:04<00:06,  4.59it/s]

Progress: 22/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:05<00:06,  4.55it/s]

Progress: 23/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  46%|████▋     | 25/54 [00:05<00:06,  4.58it/s]

Progress: 24/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.
Progress: 25/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:05<00:06,  4.46it/s]

Progress: 26/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:06<00:06,  4.47it/s]

Progress: 27/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:06<00:05,  4.43it/s]

Progress: 28/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:06<00:05,  4.30it/s]

Progress: 29/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:07<00:05,  4.49it/s]

Progress: 30/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.
Progress: 31/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:07<00:04,  4.54it/s]

Progress: 32/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:07<00:04,  4.49it/s]

Progress: 33/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:07<00:04,  4.37it/s]

Progress: 34/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:07<00:04,  4.21it/s]

Progress: 35/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:08<00:04,  4.09it/s]

Progress: 36/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:08<00:04,  4.25it/s]

Progress: 37/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:08<00:03,  4.35it/s]

Progress: 38/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:08<00:03,  4.30it/s]

Progress: 39/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:09<00:03,  4.14it/s]

Progress: 40/54.	Score: 0.833976833976834.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:09<00:03,  4.13it/s]

Progress: 41/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:09<00:03,  3.88it/s]

Progress: 42/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:09<00:02,  4.04it/s]

Progress: 43/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:10<00:02,  4.16it/s]

Progress: 44/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:10<00:02,  4.20it/s]

Progress: 45/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:10<00:01,  4.19it/s]

Progress: 46/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:10<00:01,  4.14it/s]

Progress: 47/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  91%|█████████ | 49/54 [00:11<00:01,  4.35it/s]

Progress: 48/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.
Progress: 49/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:11<00:00,  4.32it/s]

Progress: 50/54.	Score: 0.8485576923076923.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:11<00:00,  4.41it/s]

Progress: 51/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:12<00:00,  4.00it/s]

Progress: 52/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:12<00:00,  4.05it/s]

Progress: 53/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:12<00:00,  4.30it/s]

Progress: 54/54.	Score: 0.8566666666666667.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.875222816399287
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                            0
target                                                              splashing
model                             SVC_splashing_smote_opt-smote_default-model
holdout_test_f1_macro                                                0.793956
holdout_test_accuracy_balanced                                       0.789352
holdout_test_roc_auc                                                 0.893519
holdout_test_f1                                                      0.857143
holdout_test_accuracy                                                0.813333
cv_test_f1_macro_median                                              0.863049
cv_test_accuracy_balanced_median                                     0.885449
cv_test_roc_auc_median                                               0.922601
cv_test_f1_median                                                    0.888889
cv_test_accuracy_median                                              0.867925
cv_test_precision_class_0_median                                         0.75
cv_test_recall_class_0_median                                        0.894737
cv_test_f1_class_0_median                                            0.837209

Model saved in ..\results\models_modelling4\SVC_splashing_smote_opt-smote_default-model

In [12]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:09,  5.33it/s]

Progress: 1/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:10,  4.78it/s]

Progress: 2/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.
Progress: 3/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:10,  4.60it/s]

Progress: 4/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:10,  4.46it/s]

Progress: 5/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:10,  4.43it/s]

Progress: 6/54.	Score: 0.8392857142857143.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.
Progress: 7/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:09,  4.60it/s]

Progress: 8/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:09,  4.69it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:09,  4.60it/s]

Progress: 11/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  24%|██▍       | 13/54 [00:02<00:08,  4.62it/s]

Progress: 12/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.
Progress: 13/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:08,  4.61it/s]

Progress: 14/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:08,  4.62it/s]

Progress: 15/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:03<00:08,  4.52it/s]

Progress: 16/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:03<00:08,  4.48it/s]

Progress: 17/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:03<00:08,  4.39it/s]

Progress: 18/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:04<00:07,  4.54it/s]

Progress: 19/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:04<00:07,  4.67it/s]

Progress: 21/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:04<00:07,  4.44it/s]

Progress: 22/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:05<00:07,  4.39it/s]

Progress: 23/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  46%|████▋     | 25/54 [00:05<00:06,  4.69it/s]

Progress: 24/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.
Progress: 25/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:05<00:06,  4.66it/s]

Progress: 26/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:05<00:05,  4.65it/s]

Progress: 27/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:06<00:05,  4.64it/s]

Progress: 28/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:06<00:05,  4.49it/s]

Progress: 29/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:06<00:05,  4.56it/s]

Progress: 30/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.
Progress: 31/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:07<00:04,  4.67it/s]

Progress: 32/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:07<00:04,  4.65it/s]

Progress: 33/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:07<00:04,  4.62it/s]

Progress: 34/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:07<00:04,  4.60it/s]

Progress: 35/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:07<00:03,  4.63it/s]

Progress: 36/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:08<00:03,  4.59it/s]

Progress: 37/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:08<00:03,  4.64it/s]

Progress: 38/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 39/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:08<00:02,  4.67it/s]

Progress: 40/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:08<00:02,  4.64it/s]

Progress: 41/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:09<00:02,  4.75it/s]

Progress: 42/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.
Progress: 43/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:09<00:01,  4.81it/s]

Progress: 44/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.
Progress: 45/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:10<00:01,  4.80it/s]

Progress: 46/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:10<00:01,  4.73it/s]

Progress: 47/54.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  91%|█████████ | 49/54 [00:10<00:01,  4.71it/s]

Progress: 48/54.	Score: 0.8635477582846003.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.
Progress: 49/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:11<00:00,  4.80it/s]

Progress: 50/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 51/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:11<00:00,  4.71it/s]

Progress: 52/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 53/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:11<00:00,  4.60it/s]

Progress: 54/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8650345260514751
Best params: {'k_neighbors': 9, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smote_opt-smote_default-m...
holdout_test_f1_macro                                                      0.857143
holdout_test_accuracy_balanced                                             0.886364
holdout_test_roc_auc                                                           0.95
holdout_test_f1                                                                 0.8
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                           0.877289
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                               0.8
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.901408

Model saved in ..\results\models_modelling4\SVC_no_fragmentation_smote_opt-smote_default-model

# CatBoost

In [13]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:09<08:30,  9.63s/it]

Progress: 1/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:18<08:08,  9.39s/it]

Progress: 2/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:31<09:09, 10.77s/it]

Progress: 3/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:40<08:38, 10.36s/it]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:51<08:25, 10.31s/it]

Progress: 5/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [01:00<08:00, 10.01s/it]

Progress: 6/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [01:09<07:38,  9.76s/it]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [01:19<07:21,  9.61s/it]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [01:28<07:05,  9.45s/it]

Progress: 9/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [01:37<06:57,  9.49s/it]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [01:47<06:46,  9.44s/it]

Progress: 11/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [01:57<06:42,  9.59s/it]

Progress: 12/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [02:08<06:54, 10.12s/it]

Progress: 13/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [02:18<06:43, 10.09s/it]

Progress: 14/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [02:29<06:47, 10.44s/it]

Progress: 15/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [02:42<06:58, 11.01s/it]

Progress: 16/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [02:53<06:54, 11.20s/it]

Progress: 17/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [03:04<06:41, 11.16s/it]

Progress: 18/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [03:14<06:20, 10.87s/it]

Progress: 19/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [03:24<05:57, 10.52s/it]

Progress: 20/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [03:34<05:40, 10.31s/it]

Progress: 21/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [03:44<05:26, 10.20s/it]

Progress: 22/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [03:54<05:15, 10.19s/it]

Progress: 23/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [04:04<05:04, 10.16s/it]

Progress: 24/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [04:14<04:51, 10.06s/it]

Progress: 25/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [04:24<04:39,  9.97s/it]

Progress: 26/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [04:34<04:28,  9.95s/it]

Progress: 27/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [04:44<04:19,  9.97s/it]

Progress: 28/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [04:54<04:10, 10.03s/it]

Progress: 29/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [05:04<04:02, 10.12s/it]

Progress: 30/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [05:14<03:51, 10.06s/it]

Progress: 31/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [05:24<03:40, 10.02s/it]

Progress: 32/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [05:34<03:31, 10.08s/it]

Progress: 33/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [05:44<03:21, 10.06s/it]

Progress: 34/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [05:55<03:12, 10.13s/it]

Progress: 35/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [06:05<03:03, 10.18s/it]

Progress: 36/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [06:15<02:51, 10.09s/it]

Progress: 37/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [06:25<02:40, 10.01s/it]

Progress: 38/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [06:35<02:30, 10.01s/it]

Progress: 39/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [06:45<02:20, 10.05s/it]

Progress: 40/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [06:55<02:11, 10.12s/it]

Progress: 41/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [07:05<02:01, 10.14s/it]

Progress: 42/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [07:15<01:50, 10.05s/it]

Progress: 43/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [07:25<01:39, 10.00s/it]

Progress: 44/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [07:35<01:29,  9.97s/it]

Progress: 45/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [07:45<01:20, 10.12s/it]

Progress: 46/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [07:56<01:11, 10.17s/it]

Progress: 47/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [08:06<01:01, 10.20s/it]

Progress: 48/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [08:17<00:51, 10.37s/it]

Progress: 49/54.	Score: 0.9004629629629629.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [08:28<00:42, 10.62s/it]

Progress: 50/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [08:39<00:32, 10.81s/it]

Progress: 51/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [08:50<00:21, 10.76s/it]

Progress: 52/54.	Score: 0.8990384615384615.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [09:01<00:10, 10.76s/it]

Progress: 53/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [09:11<00:00, 10.22s/it]

Progress: 54/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.9004629629629629
Best params: {'k_neighbors': 10, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.846814
holdout_test_accuracy_balanced                                             0.831019
holdout_test_roc_auc                                                       0.959877
holdout_test_f1                                                            0.901961
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.891641
cv_test_roc_auc_median                                                     0.950464
cv_test_f1_median                                                          0.927536
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.888889
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.864865

Model saved in ..\results\models_modelling4\CatBoostClassifier_splashing_smote_opt-smote_default-model

In [14]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:10<08:55, 10.10s/it]

Progress: 1/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:20<08:47, 10.14s/it]

Progress: 2/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:30<08:35, 10.10s/it]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:40<08:28, 10.16s/it]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:50<08:19, 10.20s/it]

Progress: 5/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [01:01<08:12, 10.27s/it]

Progress: 6/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [01:11<07:58, 10.18s/it]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [01:21<07:46, 10.14s/it]

Progress: 8/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [01:31<07:38, 10.18s/it]

Progress: 9/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [01:42<07:31, 10.27s/it]

Progress: 10/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [01:52<07:23, 10.31s/it]

Progress: 11/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [02:02<07:14, 10.36s/it]

Progress: 12/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [02:12<07:01, 10.27s/it]

Progress: 13/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [02:23<06:51, 10.28s/it]

Progress: 14/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [02:33<06:39, 10.23s/it]

Progress: 15/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [02:43<06:31, 10.31s/it]

Progress: 16/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [02:54<06:24, 10.38s/it]

Progress: 17/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [03:05<06:15, 10.44s/it]

Progress: 18/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [03:15<06:01, 10.31s/it]

Progress: 19/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [03:25<05:52, 10.37s/it]

Progress: 20/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [03:36<05:44, 10.45s/it]

Progress: 21/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [03:46<05:34, 10.45s/it]

Progress: 22/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [03:56<05:22, 10.40s/it]

Progress: 23/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [04:07<05:14, 10.49s/it]

Progress: 24/54.	Score: 0.8768328445747801.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [04:18<05:04, 10.49s/it]

Progress: 25/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [04:28<04:51, 10.40s/it]

Progress: 26/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [04:38<04:39, 10.36s/it]

Progress: 27/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [04:49<04:30, 10.40s/it]

Progress: 28/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [04:59<04:20, 10.42s/it]

Progress: 29/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [05:09<04:09, 10.41s/it]

Progress: 30/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [05:19<03:56, 10.27s/it]

Progress: 31/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [05:29<03:44, 10.19s/it]

Progress: 32/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [05:40<03:34, 10.23s/it]

Progress: 33/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [05:50<03:25, 10.26s/it]

Progress: 34/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [06:00<03:16, 10.32s/it]

Progress: 35/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [06:11<03:05, 10.30s/it]

Progress: 36/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [06:21<02:53, 10.20s/it]

Progress: 37/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [06:31<02:43, 10.22s/it]

Progress: 38/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [06:41<02:33, 10.26s/it]

Progress: 39/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [06:52<02:24, 10.29s/it]

Progress: 40/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [07:02<02:14, 10.36s/it]

Progress: 41/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [07:13<02:04, 10.37s/it]

Progress: 42/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [07:22<01:52, 10.22s/it]

Progress: 43/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [07:33<01:42, 10.26s/it]

Progress: 44/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [07:43<01:32, 10.31s/it]

Progress: 45/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [07:53<01:22, 10.26s/it]

Progress: 46/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [08:04<01:12, 10.30s/it]

Progress: 47/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [08:14<01:01, 10.33s/it]

Progress: 48/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [08:24<00:51, 10.27s/it]

Progress: 49/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [08:34<00:40, 10.24s/it]

Progress: 50/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [08:45<00:30, 10.26s/it]

Progress: 51/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [08:55<00:20, 10.33s/it]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [09:06<00:10, 10.37s/it]

Progress: 53/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [09:16<00:00, 10.31s/it]

Progress: 54/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8768328445747801
Best params: {'k_neighbors': 5, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.933862
holdout_test_accuracy_balanced                                             0.947727
holdout_test_roc_auc                                                       0.987273
holdout_test_f1                                                            0.904762
holdout_test_accuracy                                                      0.946667
cv_test_f1_macro_median                                                    0.925457
cv_test_accuracy_balanced_median                                           0.915751
cv_test_roc_auc_median                                                     0.977778
cv_test_f1_median                                                          0.888889
cv_test_accuracy_median                                                    0.943396
cv_test_precision_class_0_median                                               0.95
cv_test_recall_class_0_median                                              0.974359
cv_test_f1_class_0_median                                                  0.961039

Model saved in ..\results\models_modelling4\CatBoostClassifier_no_fragmentation_smote_opt-smote_default-model

# XGBoost

In [15]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:18,  2.88it/s]

Progress: 1/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:18,  2.88it/s]

Progress: 2/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:18,  2.83it/s]

Progress: 3/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:18,  2.76it/s]

Progress: 4/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:17,  2.79it/s]

Progress: 5/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:17,  2.78it/s]

Progress: 6/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:16,  2.83it/s]

Progress: 7/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:17,  2.65it/s]

Progress: 8/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:16,  2.71it/s]

Progress: 9/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:16,  2.71it/s]

Progress: 10/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:15,  2.75it/s]

Progress: 11/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:15,  2.79it/s]

Progress: 12/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:15,  2.62it/s]

Progress: 13/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:05<00:14,  2.70it/s]

Progress: 14/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:05<00:14,  2.74it/s]

Progress: 15/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:13,  2.72it/s]

Progress: 16/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:06<00:13,  2.77it/s]

Progress: 17/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:06<00:12,  2.79it/s]

Progress: 18/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:12,  2.83it/s]

Progress: 19/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:07<00:12,  2.75it/s]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:07<00:11,  2.78it/s]

Progress: 21/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:11,  2.75it/s]

Progress: 22/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:08<00:11,  2.76it/s]

Progress: 23/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:08<00:10,  2.75it/s]

Progress: 24/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:09<00:10,  2.81it/s]

Progress: 25/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:09<00:09,  2.83it/s]

Progress: 26/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:09<00:09,  2.84it/s]

Progress: 27/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:10<00:09,  2.79it/s]

Progress: 28/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:10<00:08,  2.82it/s]

Progress: 29/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:10<00:08,  2.84it/s]

Progress: 30/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:11<00:08,  2.87it/s]

Progress: 31/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:11<00:07,  2.89it/s]

Progress: 32/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:11<00:08,  2.59it/s]

Progress: 33/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:12<00:07,  2.62it/s]

Progress: 34/54.	Score: 0.875222816399287.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:12<00:07,  2.68it/s]

Progress: 35/54.	Score: 0.8990384615384615.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:13<00:06,  2.72it/s]

Progress: 36/54.	Score: 0.8990384615384615.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:13<00:06,  2.78it/s]

Progress: 37/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:13<00:06,  2.62it/s]

Progress: 38/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:14<00:05,  2.68it/s]

Progress: 39/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:14<00:05,  2.71it/s]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:14<00:04,  2.75it/s]

Progress: 41/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:15<00:04,  2.78it/s]

Progress: 42/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:15<00:03,  2.83it/s]

Progress: 43/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:15<00:03,  2.86it/s]

Progress: 44/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:16<00:03,  2.87it/s]

Progress: 45/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:16<00:02,  2.80it/s]

Progress: 46/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:16<00:02,  2.82it/s]

Progress: 47/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:17<00:02,  2.83it/s]

Progress: 48/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:17<00:01,  2.87it/s]

Progress: 49/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:18<00:01,  2.88it/s]

Progress: 50/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:18<00:01,  2.86it/s]

Progress: 51/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:18<00:00,  2.81it/s]

Progress: 52/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:19<00:00,  2.83it/s]

Progress: 53/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:19<00:00,  2.78it/s]

Progress: 54/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8990384615384615
Best params: {'k_neighbors': 7, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smote_opt-smote_defaul...
holdout_test_f1_macro                                                      0.852826
holdout_test_accuracy_balanced                                             0.847222
holdout_test_roc_auc                                                       0.947145
holdout_test_f1                                                            0.897959
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                           0.856037
cv_test_roc_auc_median                                                     0.946032
cv_test_f1_median                                                          0.901408
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                               0.85
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                       0.8

Model saved in ..\results\models_modelling4\XGBClassifier_splashing_smote_opt-smote_default-model

In [16]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:22,  2.40it/s]

Progress: 1/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:19,  2.70it/s]

Progress: 2/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:17,  2.85it/s]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:17,  2.94it/s]

Progress: 4/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:16,  2.97it/s]

Progress: 5/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:15,  3.00it/s]

Progress: 6/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  2.99it/s]

Progress: 7/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:15,  3.00it/s]

Progress: 8/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:14,  3.03it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  3.04it/s]

Progress: 10/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:14,  3.04it/s]

Progress: 11/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:13,  3.05it/s]

Progress: 12/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.00it/s]

Progress: 13/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:13,  3.02it/s]

Progress: 14/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:05<00:12,  3.04it/s]

Progress: 15/54.	Score: 0.8167613636363636.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  3.05it/s]

Progress: 16/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  3.05it/s]

Progress: 17/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:06<00:11,  3.02it/s]

Progress: 18/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:11,  3.00it/s]

Progress: 19/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:11,  2.95it/s]

Progress: 20/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:07<00:11,  2.99it/s]

Progress: 21/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:10,  3.01it/s]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  2.96it/s]

Progress: 23/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:08<00:10,  2.96it/s]

Progress: 24/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:08<00:09,  2.93it/s]

Progress: 25/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:10,  2.75it/s]

Progress: 26/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:09<00:10,  2.47it/s]

Progress: 27/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:09<00:09,  2.61it/s]

Progress: 28/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:10<00:09,  2.64it/s]

Progress: 29/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:10<00:08,  2.67it/s]

Progress: 30/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:10<00:08,  2.68it/s]

Progress: 31/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:11<00:08,  2.68it/s]

Progress: 32/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:11<00:07,  2.67it/s]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:11<00:07,  2.68it/s]

Progress: 34/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:12<00:06,  2.73it/s]

Progress: 35/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:12<00:06,  2.75it/s]

Progress: 36/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:12<00:06,  2.71it/s]

Progress: 37/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:13<00:05,  2.73it/s]

Progress: 38/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:13<00:05,  2.75it/s]

Progress: 39/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:14<00:05,  2.57it/s]

Progress: 40/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:14<00:05,  2.54it/s]

Progress: 41/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:14<00:04,  2.59it/s]

Progress: 42/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:15<00:04,  2.62it/s]

Progress: 43/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:15<00:03,  2.68it/s]

Progress: 44/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:15<00:03,  2.72it/s]

Progress: 45/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:16<00:02,  2.76it/s]

Progress: 46/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:16<00:02,  2.79it/s]

Progress: 47/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:17<00:02,  2.80it/s]

Progress: 48/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:17<00:01,  2.75it/s]

Progress: 49/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:17<00:01,  2.77it/s]

Progress: 50/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:18<00:01,  2.80it/s]

Progress: 51/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:18<00:00,  2.81it/s]

Progress: 52/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:18<00:00,  2.80it/s]

Progress: 53/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:19<00:00,  2.82it/s]

Progress: 54/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8516218081435472
Best params: {'k_neighbors': 8, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smote_opt-smote...
holdout_test_f1_macro                                                      0.882524
holdout_test_accuracy_balanced                                             0.888636
holdout_test_roc_auc                                                       0.981818
holdout_test_f1                                                            0.829268
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.976068
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.936709

Model saved in ..\results\models_modelling4\XGBClassifier_no_fragmentation_smote_opt-smote_default-model

# AdaBoost

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:32,  1.63it/s]

Progress: 1/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:32,  1.62it/s]

Progress: 2/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:31,  1.64it/s]

Progress: 3/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:30,  1.62it/s]

Progress: 4/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:03<00:29,  1.64it/s]

Progress: 5/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:29,  1.62it/s]

Progress: 6/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:28,  1.65it/s]

Progress: 7/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:04<00:27,  1.66it/s]

Progress: 8/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:27,  1.66it/s]

Progress: 9/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:06<00:26,  1.65it/s]

Progress: 10/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:06<00:26,  1.65it/s]

Progress: 11/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:25,  1.65it/s]

Progress: 12/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:07<00:25,  1.63it/s]

Progress: 13/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:08<00:24,  1.61it/s]

Progress: 14/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:09<00:24,  1.60it/s]

Progress: 15/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:09<00:23,  1.61it/s]

Progress: 16/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:10<00:22,  1.62it/s]

Progress: 17/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:11<00:22,  1.64it/s]

Progress: 18/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:11<00:21,  1.62it/s]

Progress: 19/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:12<00:20,  1.63it/s]

Progress: 20/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:12<00:19,  1.65it/s]

Progress: 21/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:13<00:19,  1.66it/s]

Progress: 22/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:14<00:18,  1.67it/s]

Progress: 23/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:14<00:18,  1.63it/s]

Progress: 24/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:15<00:17,  1.65it/s]

Progress: 25/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:15<00:17,  1.64it/s]

Progress: 26/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:16<00:16,  1.63it/s]

Progress: 27/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:17<00:15,  1.63it/s]

Progress: 28/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:17<00:15,  1.62it/s]

Progress: 29/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:18<00:14,  1.63it/s]

Progress: 30/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:18<00:14,  1.63it/s]

Progress: 31/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:19<00:13,  1.65it/s]

Progress: 32/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:20<00:12,  1.66it/s]

Progress: 33/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:20<00:11,  1.67it/s]

Progress: 34/54.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:21<00:11,  1.66it/s]

Progress: 35/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:21<00:10,  1.67it/s]

Progress: 36/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:22<00:10,  1.69it/s]

Progress: 37/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:23<00:09,  1.69it/s]

Progress: 38/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:23<00:08,  1.68it/s]

Progress: 39/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:24<00:08,  1.68it/s]

Progress: 40/54.	Score: 0.8210590383444918.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:24<00:07,  1.68it/s]

Progress: 41/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:25<00:07,  1.66it/s]

Progress: 42/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:26<00:06,  1.67it/s]

Progress: 43/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:26<00:05,  1.67it/s]

Progress: 44/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:27<00:05,  1.64it/s]

Progress: 45/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:27<00:04,  1.62it/s]

Progress: 46/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:28<00:04,  1.62it/s]

Progress: 47/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:29<00:03,  1.63it/s]

Progress: 48/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:29<00:03,  1.65it/s]

Progress: 49/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:30<00:02,  1.67it/s]

Progress: 50/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:30<00:01,  1.67it/s]

Progress: 51/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:31<00:01,  1.67it/s]

Progress: 52/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:32<00:00,  1.67it/s]

Progress: 53/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:32<00:00,  1.65it/s]

Progress: 54/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.873900293255132
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.751994
holdout_test_accuracy_balanced                                                 0.75
holdout_test_roc_auc                                                       0.854552
holdout_test_f1                                                            0.824742
holdout_test_accuracy                                                      0.773333
cv_test_f1_macro_median                                                    0.794892
cv_test_accuracy_balanced_median                                           0.794892
cv_test_roc_auc_median                                                     0.891641
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.736842
cv_test_recall_class_0_median                                              0.736842
cv_test_f1_class_0_median                                                  0.736842

Model saved in ..\results\models_modelling4\AdaBoostClassifier_splashing_smote_opt-smote_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:30,  1.72it/s]

Progress: 1/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:30,  1.72it/s]

Progress: 2/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:30,  1.67it/s]

Progress: 3/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:29,  1.69it/s]

Progress: 4/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:02<00:29,  1.69it/s]

Progress: 5/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:28,  1.69it/s]

Progress: 6/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:27,  1.70it/s]

Progress: 7/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:04<00:27,  1.69it/s]

Progress: 8/54.	Score: 0.8031250000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:26,  1.70it/s]

Progress: 9/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:05<00:25,  1.70it/s]

Progress: 10/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:06<00:25,  1.70it/s]

Progress: 11/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:24,  1.70it/s]

Progress: 12/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:07<00:23,  1.72it/s]

Progress: 13/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:08<00:23,  1.72it/s]

Progress: 14/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:08<00:22,  1.72it/s]

Progress: 15/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:09<00:22,  1.72it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:09<00:21,  1.72it/s]

Progress: 17/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:10<00:21,  1.70it/s]

Progress: 18/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:11<00:20,  1.72it/s]

Progress: 19/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:11<00:19,  1.73it/s]

Progress: 20/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:12<00:19,  1.71it/s]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:12<00:18,  1.71it/s]

Progress: 22/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:13<00:18,  1.71it/s]

Progress: 23/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:14<00:17,  1.70it/s]

Progress: 24/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:14<00:16,  1.71it/s]

Progress: 25/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:15<00:16,  1.72it/s]

Progress: 26/54.	Score: 0.7777777777777777.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:15<00:15,  1.73it/s]

Progress: 27/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:16<00:15,  1.73it/s]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:16<00:14,  1.72it/s]

Progress: 29/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:17<00:14,  1.71it/s]

Progress: 30/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:18<00:13,  1.73it/s]

Progress: 31/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:18<00:12,  1.74it/s]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:19<00:12,  1.73it/s]

Progress: 33/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:19<00:11,  1.67it/s]

Progress: 34/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:20<00:11,  1.69it/s]

Progress: 35/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:21<00:10,  1.68it/s]

Progress: 36/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:21<00:09,  1.71it/s]

Progress: 37/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:22<00:09,  1.72it/s]

Progress: 38/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:22<00:08,  1.73it/s]

Progress: 39/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:23<00:08,  1.71it/s]

Progress: 40/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:23<00:07,  1.71it/s]

Progress: 41/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:24<00:07,  1.71it/s]

Progress: 42/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:25<00:06,  1.73it/s]

Progress: 43/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:25<00:05,  1.73it/s]

Progress: 44/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:26<00:05,  1.74it/s]

Progress: 45/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:26<00:04,  1.73it/s]

Progress: 46/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:27<00:04,  1.68it/s]

Progress: 47/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:28<00:03,  1.67it/s]

Progress: 48/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:28<00:03,  1.66it/s]

Progress: 49/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:29<00:02,  1.69it/s]

Progress: 50/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:29<00:01,  1.70it/s]

Progress: 51/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:30<00:01,  1.70it/s]

Progress: 52/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:31<00:00,  1.70it/s]

Progress: 53/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:31<00:00,  1.71it/s]

Progress: 54/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8576271186440678
Best params: {'k_neighbors': 6, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.853293
holdout_test_accuracy_balanced                                             0.870455
holdout_test_roc_auc                                                       0.949091
holdout_test_f1                                                            0.790698
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.854396
cv_test_roc_auc_median                                                     0.925824
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.923077

Model saved in ..\results\models_modelling4\AdaBoostClassifier_no_fragmentation_smote_opt-smote_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:51,  1.03it/s]

Progress: 1/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:50,  1.04it/s]

Progress: 2/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:02<00:49,  1.04it/s]

Progress: 3/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:03<00:48,  1.02it/s]

Progress: 4/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:04<00:48,  1.02it/s]

Progress: 5/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:05<00:47,  1.01it/s]

Progress: 6/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:06<00:45,  1.03it/s]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:07<00:44,  1.03it/s]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:08<00:43,  1.03it/s]

Progress: 9/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:09<00:42,  1.03it/s]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:10<00:42,  1.02it/s]

Progress: 11/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:11<00:41,  1.01it/s]

Progress: 12/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:12<00:39,  1.03it/s]

Progress: 13/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:13<00:38,  1.03it/s]

Progress: 14/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:14<00:37,  1.03it/s]

Progress: 15/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:15<00:36,  1.03it/s]

Progress: 16/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:16<00:36,  1.02it/s]

Progress: 17/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:17<00:35,  1.02it/s]

Progress: 18/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:18<00:34,  1.02it/s]

Progress: 19/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:19<00:33,  1.02it/s]

Progress: 20/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:20<00:32,  1.02it/s]

Progress: 21/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:21<00:31,  1.03it/s]

Progress: 22/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:22<00:30,  1.02it/s]

Progress: 23/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:23<00:29,  1.02it/s]

Progress: 24/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:24<00:28,  1.03it/s]

Progress: 25/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:25<00:27,  1.03it/s]

Progress: 26/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:26<00:26,  1.03it/s]

Progress: 27/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:27<00:25,  1.02it/s]

Progress: 28/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:28<00:24,  1.02it/s]

Progress: 29/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:29<00:23,  1.01it/s]

Progress: 30/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:30<00:22,  1.03it/s]

Progress: 31/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:31<00:21,  1.03it/s]

Progress: 32/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:32<00:20,  1.03it/s]

Progress: 33/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:33<00:19,  1.03it/s]

Progress: 34/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:34<00:18,  1.01it/s]

Progress: 35/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:35<00:17,  1.02it/s]

Progress: 36/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:36<00:16,  1.02it/s]

Progress: 37/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:37<00:15,  1.02it/s]

Progress: 38/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:38<00:14,  1.02it/s]

Progress: 39/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:39<00:13,  1.02it/s]

Progress: 40/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:40<00:12,  1.01it/s]

Progress: 41/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:41<00:11,  1.00it/s]

Progress: 42/54.	Score: 0.8313725490196078.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:42<00:10,  1.01it/s]

Progress: 43/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:43<00:09,  1.02it/s]

Progress: 44/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:44<00:08,  1.02it/s]

Progress: 45/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:44<00:07,  1.02it/s]

Progress: 46/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:45<00:06,  1.01it/s]

Progress: 47/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:46<00:05,  1.01it/s]

Progress: 48/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:47<00:04,  1.02it/s]

Progress: 49/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:48<00:03,  1.01it/s]

Progress: 50/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:49<00:02,  1.02it/s]

Progress: 51/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:50<00:01,  1.02it/s]

Progress: 52/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:51<00:00,  1.02it/s]

Progress: 53/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:52<00:00,  1.02it/s]

Progress: 54/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8962962962962964
Best params: {'k_neighbors': 4, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smote_opt-smo...
holdout_test_f1_macro                                                        0.8333
holdout_test_accuracy_balanced                                             0.820602
holdout_test_roc_auc                                                       0.956404
holdout_test_f1                                                            0.891089
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.891641
cv_test_roc_auc_median                                                     0.948413
cv_test_f1_median                                                          0.927536
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.882353
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.864865

Model saved in ..\results\models_modelling4\RandomForestClassifier_splashing_smote_opt-smote_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:51,  1.02it/s]

Progress: 1/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:49,  1.04it/s]

Progress: 2/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:02<00:49,  1.03it/s]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:03<00:48,  1.03it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:04<00:48,  1.02it/s]

Progress: 5/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:05<00:47,  1.02it/s]

Progress: 6/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:06<00:45,  1.03it/s]

Progress: 7/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:07<00:45,  1.02it/s]

Progress: 8/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:08<00:44,  1.02it/s]

Progress: 9/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:09<00:43,  1.02it/s]

Progress: 10/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:10<00:42,  1.02it/s]

Progress: 11/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:11<00:41,  1.01it/s]

Progress: 12/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:12<00:40,  1.02it/s]

Progress: 13/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:13<00:38,  1.03it/s]

Progress: 14/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:14<00:38,  1.02it/s]

Progress: 15/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:15<00:37,  1.02it/s]

Progress: 16/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:16<00:36,  1.02it/s]

Progress: 17/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:17<00:35,  1.01it/s]

Progress: 18/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:18<00:34,  1.02it/s]

Progress: 19/54.	Score: 0.8687499999999999.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:19<00:33,  1.03it/s]

Progress: 20/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:20<00:32,  1.03it/s]

Progress: 21/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:21<00:31,  1.03it/s]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:22<00:30,  1.00it/s]

Progress: 23/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:23<00:29,  1.01it/s]

Progress: 24/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:24<00:28,  1.02it/s]

Progress: 25/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:25<00:27,  1.03it/s]

Progress: 26/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:26<00:26,  1.03it/s]

Progress: 27/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:27<00:25,  1.02it/s]

Progress: 28/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:28<00:24,  1.01it/s]

Progress: 29/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:29<00:23,  1.01it/s]

Progress: 30/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:30<00:22,  1.03it/s]

Progress: 31/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:31<00:21,  1.03it/s]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:32<00:20,  1.02it/s]

Progress: 33/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:33<00:19,  1.02it/s]

Progress: 34/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:34<00:18,  1.02it/s]

Progress: 35/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:35<00:17,  1.01it/s]

Progress: 36/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:36<00:16,  1.03it/s]

Progress: 37/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:37<00:15,  1.03it/s]

Progress: 38/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:38<00:14,  1.03it/s]

Progress: 39/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:39<00:13,  1.02it/s]

Progress: 40/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:40<00:12,  1.01it/s]

Progress: 41/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:41<00:11,  1.01it/s]

Progress: 42/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:42<00:10,  1.03it/s]

Progress: 43/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:43<00:09,  1.03it/s]

Progress: 44/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:44<00:08,  1.03it/s]

Progress: 45/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:45<00:07,  1.03it/s]

Progress: 46/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:46<00:06,  1.02it/s]

Progress: 47/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:47<00:05,  1.01it/s]

Progress: 48/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:48<00:04,  1.01it/s]

Progress: 49/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:48<00:03,  1.02it/s]

Progress: 50/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:49<00:02,  1.02it/s]

Progress: 51/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:50<00:01,  1.02it/s]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:51<00:00,  1.02it/s]

Progress: 53/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:52<00:00,  1.02it/s]

Progress: 54/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8687499999999999
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smote_...
holdout_test_f1_macro                                                      0.897727
holdout_test_accuracy_balanced                                             0.897727
holdout_test_roc_auc                                                       0.980455
holdout_test_f1                                                                0.85
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                     0.946154
cv_test_f1_median                                                          0.846154
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                      0.95

Model saved in ..\results\models_modelling4\RandomForestClassifier_no_fragmentation_smote_opt-smote_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:23,  2.23it/s]

Progress: 1/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:17,  2.98it/s]

Progress: 2/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:15,  3.20it/s]

Progress: 3/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:15,  3.29it/s]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:15,  3.16it/s]

Progress: 5/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:14,  3.25it/s]

Progress: 6/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:14,  3.33it/s]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:13,  3.37it/s]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:13,  3.42it/s]

Progress: 9/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:12,  3.44it/s]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:12,  3.43it/s]

Progress: 11/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:12,  3.32it/s]

Progress: 12/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:11,  3.44it/s]

Progress: 13/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:11,  3.46it/s]

Progress: 14/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:11,  3.41it/s]

Progress: 15/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:11,  3.40it/s]

Progress: 16/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:11,  3.36it/s]

Progress: 17/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:10,  3.35it/s]

Progress: 18/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:10,  3.35it/s]

Progress: 19/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:09,  3.41it/s]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:09,  3.46it/s]

Progress: 21/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:09,  3.46it/s]

Progress: 22/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:09,  3.15it/s]

Progress: 23/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.18it/s]

Progress: 24/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:08,  3.31it/s]

Progress: 25/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:07<00:08,  3.30it/s]

Progress: 26/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.13it/s]

Progress: 27/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:08,  3.24it/s]

Progress: 28/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:08<00:07,  3.20it/s]

Progress: 29/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:07,  3.09it/s]

Progress: 30/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:07,  3.23it/s]

Progress: 31/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:09<00:06,  3.33it/s]

Progress: 32/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.24it/s]

Progress: 33/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:06,  3.23it/s]

Progress: 34/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:10<00:05,  3.28it/s]

Progress: 35/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:10<00:05,  3.35it/s]

Progress: 36/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:04,  3.43it/s]

Progress: 37/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:11<00:04,  3.51it/s]

Progress: 38/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:11<00:04,  3.54it/s]

Progress: 39/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:03,  3.53it/s]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:12<00:03,  3.41it/s]

Progress: 41/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:12<00:03,  3.39it/s]

Progress: 42/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:12<00:03,  3.45it/s]

Progress: 43/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:13<00:02,  3.53it/s]

Progress: 44/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:13<00:02,  3.50it/s]

Progress: 45/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:13<00:02,  3.52it/s]

Progress: 46/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  3.50it/s]

Progress: 47/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:14<00:01,  3.37it/s]

Progress: 48/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:14<00:01,  3.47it/s]

Progress: 49/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:14<00:01,  3.38it/s]

Progress: 50/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:15<00:00,  3.36it/s]

Progress: 51/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:15<00:00,  3.40it/s]

Progress: 52/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:15<00:00,  3.39it/s]

Progress: 53/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:16<00:00,  3.34it/s]

Progress: 54/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8962962962962964
Best params: {'k_neighbors': 7, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smote_opt-smote_defau...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.951775
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.898584
cv_test_accuracy_balanced_median                                           0.903251
cv_test_roc_auc_median                                                      0.95873
cv_test_f1_median                                                          0.923077
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.871795

Model saved in ..\results\models_modelling4\LGBMClassifier_splashing_smote_opt-smote_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:13,  3.98it/s]

Progress: 1/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:14,  3.71it/s]

Progress: 2/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:14,  3.54it/s]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:14,  3.51it/s]

Progress: 4/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:14,  3.32it/s]

Progress: 5/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:15,  3.10it/s]

Progress: 6/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:14,  3.29it/s]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:13,  3.48it/s]

Progress: 8/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:12,  3.56it/s]

Progress: 9/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:12,  3.57it/s]

Progress: 10/54.	Score: 0.8585858585858586.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:12,  3.47it/s]

Progress: 11/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:12,  3.32it/s]

Progress: 12/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:12,  3.34it/s]

Progress: 13/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:11,  3.48it/s]

Progress: 14/54.	Score: 0.8585858585858586.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:10,  3.56it/s]

Progress: 15/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:10,  3.58it/s]

Progress: 16/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:04<00:10,  3.53it/s]

Progress: 17/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:10,  3.50it/s]

Progress: 18/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:10,  3.48it/s]

Progress: 19/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:05<00:09,  3.52it/s]

Progress: 20/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:09,  3.48it/s]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:09,  3.52it/s]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:08,  3.53it/s]

Progress: 23/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:06<00:08,  3.56it/s]

Progress: 24/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:07,  3.63it/s]

Progress: 25/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:07<00:07,  3.69it/s]

Progress: 26/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:07<00:07,  3.54it/s]

Progress: 27/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:07,  3.51it/s]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:08<00:07,  3.52it/s]

Progress: 29/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:08<00:06,  3.54it/s]

Progress: 30/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:08<00:06,  3.64it/s]

Progress: 31/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:09<00:06,  3.60it/s]

Progress: 32/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:09<00:05,  3.63it/s]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:09<00:06,  3.33it/s]

Progress: 34/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:10<00:05,  3.24it/s]

Progress: 35/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:10<00:05,  3.32it/s]

Progress: 36/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:10<00:04,  3.49it/s]

Progress: 37/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:10<00:04,  3.41it/s]

Progress: 38/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:11<00:04,  3.43it/s]

Progress: 39/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:11<00:03,  3.53it/s]

Progress: 40/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:11<00:03,  3.51it/s]

Progress: 41/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:12<00:03,  3.40it/s]

Progress: 42/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:12<00:03,  3.53it/s]

Progress: 43/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:12<00:02,  3.56it/s]

Progress: 44/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:12<00:02,  3.54it/s]

Progress: 45/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:13<00:02,  3.55it/s]

Progress: 46/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:13<00:01,  3.51it/s]

Progress: 47/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:13<00:01,  3.53it/s]

Progress: 48/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:14<00:01,  3.54it/s]

Progress: 49/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:14<00:01,  3.49it/s]

Progress: 50/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:14<00:00,  3.51it/s]

Progress: 51/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:14<00:00,  3.54it/s]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:15<00:00,  3.51it/s]

Progress: 53/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:15<00:00,  3.49it/s]

Progress: 54/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8585858585858586
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smote_opt-smot...
holdout_test_f1_macro                                                      0.885894
holdout_test_accuracy_balanced                                             0.904545
holdout_test_roc_auc                                                       0.980909
holdout_test_f1                                                            0.837209
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.958974
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.944444
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.939759

Model saved in ..\results\models_modelling4\LGBMClassifier_no_fragmentation_smote_opt-smote_default-model

# For the notebook with Model optimization!

In [23]:
# def update_estimator_params(
#     ml_pipe:MLPipeline,
#     suggested_params:dict,
# ) -> dict:
#     """Update the estimator parameters based on the pipeline parameters.

#     Args:
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.
#         suggested_params: A dictionary containing the suggested Estimator hyperparameters.
    
#     Returns:
#         A dictionary containing the estimator parameters.
#     """
#     estimator_params = ml_pipe._pipeline_params['estimator_params']
#     estimator_params.update(suggested_params)
#     return estimator_params

# def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
#     """Objective function for logistic regression optimization using Optuna.

#     Args:
#         trial: An Optuna trial object used to suggest hyperparameters.
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.

#     Returns:
#         The score of the model based on the specified evaluation metric.
#     """
    
#     categorical_features = ('wettability', 'inclination')
    
#     random_state = ml_pipe._pipeline_params['random_state']
    
#     # sample params
#     C = trial.suggest_loguniform('C', 1e-4, 1e3)
    
#     # SMOTE params
#     add_smote = trial.suggest_categorical('add_smote', [True, False])
#     if add_smote:
#         is_smotenc = trial.suggest_categorical('is_smotenc', [True, False])
#         smote_params = {
#             'sampling_strategy': trial.suggest_categorical(
#                 'sampling_strategy', [0.6, 0.7, 0.8, 0.9, 1.0]
#             ),
#             'k_neighbors': trial.suggest_int('k_neighbors', 3, 10),
#             'random_state': random_state,
#         }
#     else:
#         is_smotenc = False
#         smote_params = None
#     if is_smotenc:
#         wettability_cat = trial.suggest_categorical('wettability_cat', [True, False])
#         if wettability_cat:
#             inclination_cat = trial.suggest_categorical('inclination_cat', [True, False])
#         else:
#             inclination_cat = True
        
        
#         mask = [wettability_cat, inclination_cat]
        
#         masked_features = [
#             feature for feature, mask_value in zip(categorical_features, mask) 
#             if mask_value
#         ]
#         smote_params = {
#             **smote_params,
#             'categorical_features': masked_features,
#         }

#     suggested_params = {
#         "C": C,
#     }
    
#     estimator_params = update_estimator_params(ml_pipe, suggested_params)

#     estimator = LogisticRegression(
#         **estimator_params,
#         random_state=random_state,
#     )

#     score = ml_pipe.step(
#         estimator=estimator,
#         add_smote=add_smote,
#         is_smotenc=is_smotenc,
#         smote_params=smote_params,
#     )
    
#     return score



# opt = OptunaOptimizer(
#     objective=partial(logreg_objective, ml_pipe=ml_pipe),
#     study_name="logreg_study",
#     direction="maximize",
# )

# opt.optimize(n_trials=200)

# best_params = opt.study.best_trial.params
# display(best_params)
# # estimator_params = update_estimator_params(ml_pipe, best_params)

# # estimator = LogisticRegression(
# #     **estimator_params,
# #     random_state=ml_pipe._pipeline_params['random_state'],
# # )