Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'grid-opt-mean-smote_default-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 50 # test only

save_model_and_metrics = True
metrics_file = 'metrics_modelling4_smotenc_mean_opt.xlsx'

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    
    smote_params = smote_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
        seed=seed,
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )
    
    
def optimize_smote_grid(
    target:str,
    estimator:object,
    estimator_params:dict,
    param_grid:dict=None,
    step_scoring_average:str=step_scoring_average,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
):
    """
    Optimize the SMOTE parameters with GridSearchOptimizer for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    smote_params = smote_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    if param_grid is None:
        param_grid = {
        'sampling_strategy': [0.6, 0.7, 0.8, 0.9, 1.0, 'auto'],
        'k_neighbors': list(range(2,11)),
    }
    opt = GridSearchOptimizer(
        objective=partial(pure_smote_objective, ml_pipe=ml_pipe),
        param_grid=param_grid,
        verbose=True,
    )

    opt.optimize()
    best_params = opt.best_params

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
        metrics_file=metrics_file,
        
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    n_trials=n_trials,
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 22:21:58,719] A new study created in memory with name: smote_study
[I 2025-04-15 22:21:59,064] Trial 0 finished with value: 0.799204684219129 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.799204684219129.
[I 2025-04-15 22:21:59,172] Trial 1 finished with value: 0.8082274269002464 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.8082274269002464.
[I 2025-04-15 22:21:59,279] Trial 2 finished with value: 0.7997594024534191 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.8082274269002464.
[I 2025-04-15 22:21:59,399] Trial 3 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 3 with value: 0.8082591916442389.
[I 2025-04-15 22:21:59,524] Trial 4 finished with value: 0.8142513697328472 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8142513697328472.
[I 2025-04-15 22:21:59,647] Trial 5 finished with value: 0.810120355968379 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9}. Best is trial 4 with value: 0.8142513697328472.
[I 2025-04-15 22:21:59,774] Trial 6 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:21:59,884] Trial 7 finished with value: 0.8074099884247954 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,005] Trial 8 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,131] Trial 9 finished with value: 0.8067395699846246 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,273] Trial 10 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,421] Trial 11 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,553] Trial 12 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,689] Trial 13 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,844] Trial 14 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:00,961] Trial 15 finished with value: 0.8125539803935411 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,085] Trial 16 finished with value: 0.8101682090919139 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,201] Trial 17 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,332] Trial 18 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,449] Trial 19 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,582] Trial 20 finished with value: 0.8101682090919139 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,708] Trial 21 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,841] Trial 22 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:01,969] Trial 23 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,157] Trial 24 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,278] Trial 25 finished with value: 0.8082274269002464 and parameters: {'k_neighbors': 3, 'sampling_strategy': 1.0}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,419] Trial 26 finished with value: 0.8125539803935411 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,537] Trial 27 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,650] Trial 28 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,764] Trial 29 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,874] Trial 30 finished with value: 0.8133509107440033 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:02,989] Trial 31 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,102] Trial 32 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,225] Trial 33 finished with value: 0.8068955952248212 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,339] Trial 34 finished with value: 0.806231221777267 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,455] Trial 35 finished with value: 0.8068955952248212 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,570] Trial 36 finished with value: 0.8142513697328472 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,714] Trial 37 finished with value: 0.8093641330260226 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,834] Trial 38 finished with value: 0.8121609733029641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:03,947] Trial 39 finished with value: 0.8077871906702357 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,058] Trial 40 finished with value: 0.8074099884247954 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,176] Trial 41 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,306] Trial 42 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,447] Trial 43 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,570] Trial 44 finished with value: 0.8153695294526967 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,696] Trial 45 finished with value: 0.8194560778465503 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,826] Trial 46 finished with value: 0.8082591916442389 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:04,948] Trial 47 finished with value: 0.810120355968379 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:05,095] Trial 48 finished with value: 0.8062820536447555 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8194560778465503.
[I 2025-04-15 22:22:05,225] Trial 49 finished with value: 0.8093303573473086 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 6 with value: 0.8194560778465503.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.7}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smotenc_grid-opt-...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                          0.875
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.799242
cv_test_accuracy_balanced_median                                           0.816667
cv_test_roc_auc_median                                                     0.876161
cv_test_f1_median                                                           0.84375
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.833333
cv_test_f1_class_0_median                                                      0.75

In [7]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:09,  5.43it/s]

Progress: 1/54.	Score: 0.8065845885618185.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.
Progress: 2/54.	Score: 0.8091164906318441.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:06,  7.34it/s]

Progress: 3/54.	Score: 0.800064285698787.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.
Progress: 4/54.	Score: 0.8037343402625998.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:  11%|█         | 6/54 [00:00<00:06,  7.69it/s]

Progress: 5/54.	Score: 0.8016290818856123.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.
Progress: 6/54.	Score: 0.8016290818856123.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  15%|█▍        | 8/54 [00:01<00:05,  7.77it/s]

Progress: 7/54.	Score: 0.8074099884247954.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 8/54.	Score: 0.806231221777267.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  19%|█▊        | 10/54 [00:01<00:05,  7.42it/s]

Progress: 9/54.	Score: 0.8102033525876331.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.800573917974022.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:06,  6.75it/s]

Progress: 11/54.	Score: 0.8082274269002464.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.8082274269002464.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  26%|██▌       | 14/54 [00:01<00:05,  7.71it/s]

Progress: 13/54.	Score: 0.8062820536447555.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.8153695294526967.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  30%|██▉       | 16/54 [00:02<00:04,  7.64it/s]

Progress: 15/54.	Score: 0.8125539803935411.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8093641330260226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  33%|███▎      | 18/54 [00:02<00:04,  7.81it/s]

Progress: 17/54.	Score: 0.8107461054884604.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8107461054884604.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:02<00:04,  8.10it/s]

Progress: 19/54.	Score: 0.799204684219129.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8194560778465503.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  41%|████      | 22/54 [00:02<00:04,  7.74it/s]

Progress: 21/54.	Score: 0.8133509107440033.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  44%|████▍     | 24/54 [00:03<00:03,  8.06it/s]

Progress: 23/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  48%|████▊     | 26/54 [00:03<00:03,  7.93it/s]

Progress: 25/54.	Score: 0.8142513697328472.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 26/54.	Score: 0.8082591916442389.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:03<00:03,  8.24it/s]

Progress: 27/54.	Score: 0.8025734233923184.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:03<00:02,  8.11it/s]

Progress: 29/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.8068955952248212.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:04<00:02,  8.54it/s]

Progress: 31/54.	Score: 0.8067395699846246.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.8121609733029641.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:04<00:02,  7.88it/s]

Progress: 33/54.	Score: 0.805698512068353.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.810120355968379.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:04<00:02,  7.24it/s]

Progress: 35/54.	Score: 0.8036137004097457.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.8036137004097457.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  70%|███████   | 38/54 [00:04<00:02,  7.90it/s]

Progress: 37/54.	Score: 0.8069855520521557.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 38/54.	Score: 0.8077871906702357.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:05<00:01,  7.90it/s]

Progress: 39/54.	Score: 0.8125202047148272.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 40/54.	Score: 0.8101682090919139.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:05<00:01,  8.08it/s]

Progress: 41/54.	Score: 0.8035608434674104.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 42/54.	Score: 0.8035608434674104.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:05<00:01,  8.28it/s]

Progress: 43/54.	Score: 0.8098725704212288.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.8154355244498557.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:05<00:01,  7.94it/s]

Progress: 45/54.	Score: 0.8093303573473086.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8061476556952193.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:06<00:00,  8.02it/s]

Progress: 47/54.	Score: 0.7997594024534191.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.7997594024534191.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:06<00:00,  8.29it/s]

Progress: 49/54.	Score: 0.802875485873124.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 50/54.	Score: 0.8089711259354457.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:06<00:00,  8.31it/s]

Progress: 51/54.	Score: 0.8093303573473086.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.8125202047148272.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 54/54 [00:06<00:00,  7.84it/s]

Progress: 53/54.	Score: 0.8094222068421109.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
Progress: 54/54.	Score: 0.8094222068421109.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8194560778465503
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx

std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

TypeError: SMOTENC.__init__() missing 1 required positional argument: 'categorical_features'

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:05,  9.61it/s]

Progress: 1/54.	Score: 0.8062660571155801.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.
Progress: 2/54.	Score: 0.7960602249389092.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:03, 14.26it/s]

Progress: 3/54.	Score: 0.7927422008145589.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.
Progress: 4/54.	Score: 0.7927422008145589.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:00<00:03, 15.65it/s]

Progress: 5/54.	Score: 0.796816734439261.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.
Progress: 6/54.	Score: 0.796816734439261.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:00<00:02, 16.43it/s]

Progress: 7/54.	Score: 0.8023586077733721.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 8/54.	Score: 0.7993857581360823.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:00<00:02, 16.71it/s]

Progress: 9/54.	Score: 0.7961089219778902.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.7972483300592221.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:00<00:02, 16.94it/s]

Progress: 11/54.	Score: 0.7939509888308464.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.7939509888308464.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:00<00:02, 16.87it/s]

Progress: 13/54.	Score: 0.7957150504518486.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.7927422008145589.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:00<00:02, 16.65it/s]

Progress: 15/54.	Score: 0.7972547136236753.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8032013300443362.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:01<00:02, 16.82it/s]

Progress: 17/54.	Score: 0.7999039888159605.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.7999039888159605.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:01<00:02, 16.67it/s]

Progress: 19/54.	Score: 0.808852795988776.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8054796912609915.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:01<00:01, 16.84it/s]

Progress: 21/54.	Score: 0.7986888172352199.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.8033217581139477.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:01<00:01, 16.89it/s]

Progress: 23/54.	Score: 0.7953914760068441.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.7953914760068441.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:01<00:01, 17.13it/s]

Progress: 25/54.	Score: 0.8027588628638668.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 26/54.	Score: 0.7993857581360823.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:01<00:01, 17.14it/s]

Progress: 27/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.7934436297114765.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:01<00:01, 17.22it/s]

Progress: 29/54.	Score: 0.7934436297114765.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.7934436297114765.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:01<00:01, 17.34it/s]

Progress: 31/54.	Score: 0.7957150504518486.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.7961089219778902.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:01<00:01, 17.42it/s]

Progress: 33/54.	Score: 0.7927422008145589.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.7893627125223212.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:02<00:01, 17.37it/s]

Progress: 35/54.	Score: 0.7934436297114765.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.7934436297114765.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:02<00:00, 17.48it/s]

Progress: 37/54.	Score: 0.8023586077733721.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 38/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:02<00:00, 17.49it/s]

Progress: 39/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 40/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:02<00:00, 17.57it/s]

Progress: 41/54.	Score: 0.7861307045414084.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 42/54.	Score: 0.7861307045414084.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:02<00:00, 17.42it/s]

Progress: 43/54.	Score: 0.7990266910117458.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.7961089219778902.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:02<00:00, 15.60it/s]

Progress: 45/54.	Score: 0.8005251662174142.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:02<00:00, 16.08it/s]

Progress: 46/54.	Score: 0.7927358172501057.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 47/54.	Score: 0.7927358172501057.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.7927358172501057.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:02<00:00, 16.46it/s]

Progress: 49/54.	Score: 0.8023099107343911.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:03<00:00, 16.74it/s]

Progress: 50/54.	Score: 0.7926459322449665.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 51/54.	Score: 0.7926459322449665.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:03<00:00, 16.94it/s]

Progress: 53/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:03<00:00, 16.78it/s]

Progress: 54/54.	Score: 0.7893690960867744.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.808852795988776
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.785539
holdout_test_accuracy_balanced                                                0.825
holdout_test_roc_auc                                                       0.955455
holdout_test_f1                                                            0.708333
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.864469
cv_test_roc_auc_median                                                     0.941392
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.794872
cv_test_f1_class_0_median                                                  0.885714

Model saved in ../results/models_modelling4/LogisticRegression_no_fragmentation_smote_opt-smote_default-model

# KNClassifier

In [9]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   0%|          | 0/54 [00:00<?, ?it/s]

Progress: 1/54.	Score: 0.8180722346645078.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:05, 10.32it/s]

Progress: 2/54.	Score: 0.8279365948932688.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.
Progress: 3/54.	Score: 0.83310329516443.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:04, 10.52it/s]

Progress: 4/54.	Score: 0.8297885987849042.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:  11%|█         | 6/54 [00:00<00:04, 10.50it/s]

Progress: 5/54.	Score: 0.8351350590091783.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.
Progress: 6/54.	Score: 0.8351350590091783.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.
Progress: 7/54.	Score: 0.8337572412361947.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:00<00:04, 10.54it/s]

Progress: 8/54.	Score: 0.8401778988546086.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 9/54.	Score: 0.8441863358984809.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:00<00:04, 10.54it/s]

Progress: 10/54.	Score: 0.8459796123855117.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:03, 10.57it/s]

Progress: 11/54.	Score: 0.8417729524917613.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.8417729524917613.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.
Progress: 13/54.	Score: 0.825839058792076.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:01<00:03, 10.62it/s]

Progress: 14/54.	Score: 0.832649308677899.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 15/54.	Score: 0.8440161692847291.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:01<00:03, 10.66it/s]

Progress: 16/54.	Score: 0.8438212500883867.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  33%|███▎      | 18/54 [00:01<00:03, 10.74it/s]

Progress: 17/54.	Score: 0.8319057751429321.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8319057751429321.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.
Progress: 19/54.	Score: 0.8298095065021007.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:01<00:03, 10.76it/s]

Progress: 20/54.	Score: 0.8368120053079144.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.
Progress: 21/54.	Score: 0.844851130968462.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:02<00:02, 10.77it/s]

Progress: 22/54.	Score: 0.8413461056408372.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.
Progress: 23/54.	Score: 0.8459147856420387.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:02<00:02, 10.12it/s]

Progress: 24/54.	Score: 0.8459147856420387.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.
Progress: 25/54.	Score: 0.8291697628757652.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:02<00:02, 10.31it/s]

Progress: 26/54.	Score: 0.8469295748601737.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:02<00:02, 10.44it/s]

Progress: 27/54.	Score: 0.8410665574860728.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.8456693087605666.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 29/54.	Score: 0.8383564056502072.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:02<00:02, 10.50it/s]

Progress: 30/54.	Score: 0.8383564056502072.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.
Progress: 31/54.	Score: 0.8248384982061546.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:03<00:02, 10.60it/s]

Progress: 32/54.	Score: 0.8310722558857159.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:03<00:01, 10.69it/s]

Progress: 33/54.	Score: 0.833137470823986.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.8228700682596299.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 35/54.	Score: 0.8336996165218232.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:03<00:01, 10.68it/s]

Progress: 36/54.	Score: 0.8336996165218232.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.
Progress: 37/54.	Score: 0.8369338965136903.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:03<00:01, 10.72it/s]

Progress: 38/54.	Score: 0.826272825282062.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:03<00:01, 10.79it/s]

Progress: 39/54.	Score: 0.833710028140952.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 40/54.	Score: 0.8495164779212498.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.
Progress: 41/54.	Score: 0.8505423796235594.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:03<00:01, 10.81it/s]

Progress: 42/54.	Score: 0.8505423796235594.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.
Progress: 43/54.	Score: 0.8248384982061546.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:04<00:00, 10.84it/s]

Progress: 44/54.	Score: 0.8414216970940787.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:04<00:00, 10.82it/s]

Progress: 45/54.	Score: 0.848035438827285.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8411715628843247.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 47/54.	Score: 0.8459232567317317.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:04<00:00, 10.78it/s]

Progress: 48/54.	Score: 0.8459232567317317.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.
Progress: 49/54.	Score: 0.8213940312193869.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:04<00:00, 10.79it/s]

Progress: 50/54.	Score: 0.8454857755223885.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:04<00:00, 10.80it/s]

Progress: 51/54.	Score: 0.8515966376404391.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.8294773532459994.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 53/54.	Score: 0.8312927384273531.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:05<00:00, 10.65it/s]

Progress: 54/54.	Score: 0.8312927384273531.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8515966376404391
Best params: {'k_neighbors': 10, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smote_opt-smote...
holdout_test_f1_macro                                                      0.842105
holdout_test_accuracy_balanced                                             0.844907
holdout_test_roc_auc                                                       0.874228
holdout_test_f1                                                            0.884211
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.842262
cv_test_accuracy_balanced_median                                           0.859133
cv_test_roc_auc_median                                                     0.923375
cv_test_f1_median                                                             0.875
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                            0.73913
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.809524

Model saved in ../results/models_modelling4/KNeighborsClassifier_splashing_smote_opt-smote_default-model

In [10]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:06,  7.80it/s]

Progress: 1/54.	Score: 0.814851263882084.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:04, 10.62it/s]

Progress: 2/54.	Score: 0.8199990438296406.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.
Progress: 3/54.	Score: 0.8140473726654197.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.
Progress: 4/54.	Score: 0.8177950671811559.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:00<00:04, 11.26it/s]

Progress: 5/54.	Score: 0.81497740452424.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.
Progress: 6/54.	Score: 0.81497740452424.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:00<00:04, 11.47it/s]

Progress: 7/54.	Score: 0.8112955848193684.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  17%|█▋        | 9/54 [00:00<00:03, 11.63it/s]

Progress: 8/54.	Score: 0.8092020858581263.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.
Progress: 9/54.	Score: 0.8003630393220955.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.7981650921640223.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:00<00:03, 11.70it/s]

Progress: 11/54.	Score: 0.821424649833779.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.821424649833779.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:01<00:03, 11.77it/s]

Progress: 13/54.	Score: 0.8171535110305357.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  28%|██▊       | 15/54 [00:01<00:03, 11.81it/s]

Progress: 14/54.	Score: 0.8225452806638073.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.
Progress: 15/54.	Score: 0.8224762664422018.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8271866356360195.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:01<00:03, 11.19it/s]

Progress: 17/54.	Score: 0.7962187789644363.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.7962187789644363.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:01<00:03, 11.39it/s]

Progress: 19/54.	Score: 0.8148284884779115.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  39%|███▉      | 21/54 [00:01<00:02, 11.47it/s]

Progress: 20/54.	Score: 0.8389939328535673.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.
Progress: 21/54.	Score: 0.8298382512578318.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.8266529480984557.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:02<00:02, 11.49it/s]

Progress: 23/54.	Score: 0.8220011086912677.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.8220011086912677.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:02<00:02, 11.64it/s]

Progress: 25/54.	Score: 0.7974768147251645.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  50%|█████     | 27/54 [00:02<00:02, 11.78it/s]

Progress: 26/54.	Score: 0.8073437932545442.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 27/54.	Score: 0.8108782493751668.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:02<00:02, 11.04it/s]

Progress: 28/54.	Score: 0.8246817927394942.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.
Progress: 29/54.	Score: 0.8277725934634778.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.8277725934634778.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  61%|██████    | 33/54 [00:02<00:01, 11.44it/s]

Progress: 31/54.	Score: 0.8024502118449678.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.7985547269776317.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 33/54.	Score: 0.8095886371577994.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:03<00:01, 11.53it/s]

Progress: 34/54.	Score: 0.7959636701888516.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.
Progress: 35/54.	Score: 0.7980446953777415.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.7980446953777415.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:03<00:01, 11.79it/s]

Progress: 37/54.	Score: 0.8321906018985509.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 38/54.	Score: 0.8280206995651517.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 39/54.	Score: 0.8208119751893571.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:03<00:01, 11.83it/s]

Progress: 40/54.	Score: 0.827948904117448.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.
Progress: 41/54.	Score: 0.815227499141305.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 42/54.	Score: 0.815227499141305.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:03<00:00, 12.01it/s]

Progress: 43/54.	Score: 0.8148324545414348.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.8332232492079399.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.
Progress: 45/54.	Score: 0.8194685713908062.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:04<00:00, 12.08it/s]

Progress: 46/54.	Score: 0.8228317724690155.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.
Progress: 47/54.	Score: 0.8320097290888265.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.8320097290888265.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:04<00:00, 12.17it/s]

Progress: 49/54.	Score: 0.8321683287424805.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 50/54.	Score: 0.8242993160347581.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 51/54.	Score: 0.8206440729641564.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters: 100%|██████████| 54/54 [00:04<00:00, 11.67it/s]

Progress: 52/54.	Score: 0.8212607030476814.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 53/54.	Score: 0.8160498617310364.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
Progress: 54/54.	Score: 0.8160498617310364.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8389939328535673
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.944545
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.861722
cv_test_roc_auc_median                                                      0.93956
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.918919

Model saved in ../results/models_modelling4/KNeighborsClassifier_no_fragmentation_smote_opt-smote_default-model

# SVC

In [11]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:05,  9.91it/s]

Progress: 1/54.	Score: 0.8520810728898827.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:05,  9.83it/s]

Progress: 2/54.	Score: 0.846006538274569.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:05,  9.67it/s]

Progress: 3/54.	Score: 0.846006538274569.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:05,  9.47it/s]

Progress: 4/54.	Score: 0.8506550322426673.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:00<00:05,  9.33it/s]

Progress: 5/54.	Score: 0.8472527972227851.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:00<00:05,  9.24it/s]

Progress: 6/54.	Score: 0.8472527972227851.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  15%|█▍        | 8/54 [00:00<00:04,  9.61it/s]

Progress: 7/54.	Score: 0.8552448857338.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 8/54.	Score: 0.8449130153170329.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  19%|█▊        | 10/54 [00:01<00:05,  8.55it/s]

Progress: 9/54.	Score: 0.8455205731191057.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.8459033326566575.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:04,  8.77it/s]

Progress: 11/54.	Score: 0.8497805420485726.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.8497805420485726.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  26%|██▌       | 14/54 [00:01<00:04,  9.37it/s]

Progress: 13/54.	Score: 0.8472906521950906.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.8640781853603501.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  30%|██▉       | 16/54 [00:01<00:04,  8.19it/s]

Progress: 15/54.	Score: 0.8606106775182226.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8573275181942843.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  33%|███▎      | 18/54 [00:02<00:04,  8.56it/s]

Progress: 17/54.	Score: 0.8583958942626603.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8583958942626603.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:02<00:03,  9.12it/s]

Progress: 19/54.	Score: 0.8594769598696101.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.8632048496269116.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  41%|████      | 22/54 [00:02<00:03,  9.13it/s]

Progress: 21/54.	Score: 0.8639748051666516.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.8644329499630317.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  44%|████▍     | 24/54 [00:02<00:03,  9.06it/s]

Progress: 23/54.	Score: 0.8584340913596809.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.8584340913596809.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  48%|████▊     | 26/54 [00:02<00:02,  9.50it/s]

Progress: 25/54.	Score: 0.8515387879100551.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.
Progress: 26/54.	Score: 0.8559280383431279.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:03<00:02,  9.28it/s]

Progress: 27/54.	Score: 0.8645390566558228.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.8540675859786729.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:03<00:02,  9.17it/s]

Progress: 29/54.	Score: 0.8502582825370165.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.8502582825370165.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:03<00:02,  9.50it/s]

Progress: 31/54.	Score: 0.8515387879100551.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.
Progress: 32/54.	Score: 0.8521840077237168.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:03<00:02,  9.37it/s]

Progress: 33/54.	Score: 0.8563861831395079.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.8616838761220708.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:04<00:02,  8.49it/s]

Progress: 35/54.	Score: 0.8574773170039502.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.8574773170039502.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  70%|███████   | 38/54 [00:04<00:01,  9.14it/s]

Progress: 37/54.	Score: 0.8586471207536821.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.
Progress: 38/54.	Score: 0.8552448857338.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:04<00:01,  9.16it/s]

Progress: 39/54.	Score: 0.8677710474040525.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.
Progress: 40/54.	Score: 0.8611065634286442.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:04<00:01,  8.77it/s]

Progress: 41/54.	Score: 0.858441587365076.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.
Progress: 42/54.	Score: 0.858441587365076.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:04<00:01,  9.20it/s]

Progress: 43/54.	Score: 0.8515387879100551.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.8591732648714.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:05<00:00,  9.14it/s]

Progress: 45/54.	Score: 0.8601226182730018.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8523568224135235.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:05<00:00,  9.00it/s]

Progress: 47/54.	Score: 0.8578418617067302.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.8578418617067302.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:05<00:00,  9.41it/s]

Progress: 49/54.	Score: 0.8511048180514317.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.
Progress: 50/54.	Score: 0.8631016440090001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:05<00:00,  9.29it/s]

Progress: 51/54.	Score: 0.8641207427026755.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.
Progress: 52/54.	Score: 0.8527152217479583.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters: 100%|██████████| 54/54 [00:06<00:00,  8.99it/s]

Progress: 53/54.	Score: 0.868152502033974.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.
Progress: 54/54.	Score: 0.868152502033974.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.868152502033974
Best params: {'k_neighbors': 10, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                            0
target                                                              splashing
model                             SVC_splashing_smote_opt-smote_default-model
holdout_test_f1_macro                                                0.813397
holdout_test_accuracy_balanced                                       0.815972
holdout_test_roc_auc                                                 0.904321
holdout_test_f1                                                      0.863158
holdout_test_accuracy                                                0.826667
cv_test_f1_macro_median                                               0.82623
cv_test_accuracy_balanced_median                                     0.856037
cv_test_roc_auc_median                                               0.922601
cv_test_f1_median                                                    0.861538
cv_test_accuracy_median                                              0.830189
cv_test_precision_class_0_median                                     0.727273
cv_test_recall_class_0_median                                        0.894737
cv_test_f1_class_0_median                                                 0.8

Model saved in ../results/models_modelling4/SVC_splashing_smote_opt-smote_default-model

In [12]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   0%|          | 0/54 [00:00<?, ?it/s]

Progress: 1/54.	Score: 0.8162029215024607.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:04, 10.42it/s]

Progress: 2/54.	Score: 0.8193705892710429.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.
Progress: 3/54.	Score: 0.8157247515014502.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:00<00:04, 10.09it/s]

Progress: 4/54.	Score: 0.8307568246871634.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.
Progress: 5/54.	Score: 0.8305292099469742.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  15%|█▍        | 8/54 [00:00<00:04, 10.17it/s]

Progress: 6/54.	Score: 0.8305292099469742.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.
Progress: 7/54.	Score: 0.8191747429074645.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.
Progress: 8/54.	Score: 0.8322985197047057.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  19%|█▊        | 10/54 [00:00<00:04, 10.09it/s]

Progress: 9/54.	Score: 0.8193831882202813.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.
Progress: 10/54.	Score: 0.8226600243784734.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  22%|██▏       | 12/54 [00:01<00:04,  9.93it/s]

Progress: 11/54.	Score: 0.8285213616709418.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.
Progress: 12/54.	Score: 0.8285213616709418.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  26%|██▌       | 14/54 [00:01<00:04,  9.79it/s]

Progress: 13/54.	Score: 0.8290968844812091.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.
Progress: 14/54.	Score: 0.8442887799684738.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  30%|██▉       | 16/54 [00:01<00:03,  9.63it/s]

Progress: 15/54.	Score: 0.8408912983813985.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.
Progress: 16/54.	Score: 0.8338615447241615.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  33%|███▎      | 18/54 [00:01<00:04,  8.60it/s]

Progress: 17/54.	Score: 0.8231253119115706.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.
Progress: 18/54.	Score: 0.8231253119115706.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  37%|███▋      | 20/54 [00:02<00:03,  9.28it/s]

Progress: 19/54.	Score: 0.8251212760039304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.
Progress: 20/54.	Score: 0.825140344916634.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  41%|████      | 22/54 [00:02<00:03,  9.26it/s]

Progress: 21/54.	Score: 0.8227522239991012.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.
Progress: 22/54.	Score: 0.835417443819811.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  44%|████▍     | 24/54 [00:02<00:03,  9.29it/s]

Progress: 23/54.	Score: 0.8420383259106587.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.
Progress: 24/54.	Score: 0.8420383259106587.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.
Progress: 25/54.	Score: 0.8139029573871112.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:02<00:02, 10.05it/s]

Progress: 26/54.	Score: 0.824167932106136.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.
Progress: 27/54.	Score: 0.8309935801323588.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.
Progress: 28/54.	Score: 0.835417443819811.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:03<00:02,  9.79it/s]

Progress: 29/54.	Score: 0.835417443819811.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.
Progress: 30/54.	Score: 0.835417443819811.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.
Progress: 31/54.	Score: 0.8224560578860418.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:03<00:01, 10.08it/s]

Progress: 32/54.	Score: 0.8100413135239511.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.
Progress: 33/54.	Score: 0.8219518855752577.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.
Progress: 34/54.	Score: 0.8219518855752577.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:03<00:01,  9.83it/s]

Progress: 35/54.	Score: 0.8194753878409092.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.
Progress: 36/54.	Score: 0.8194753878409092.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.
Progress: 37/54.	Score: 0.8288840166867963.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:04<00:01,  9.96it/s]

Progress: 38/54.	Score: 0.8254865350997209.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.
Progress: 39/54.	Score: 0.8346658965165396.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:04<00:01,  8.86it/s]

Progress: 40/54.	Score: 0.8364674346939464.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.
Progress: 41/54.	Score: 0.8398649162810218.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:04<00:01,  9.73it/s]

Progress: 42/54.	Score: 0.8398649162810218.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.
Progress: 43/54.	Score: 0.8255634112274117.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.
Progress: 44/54.	Score: 0.831759840195847.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:04<00:00,  8.97it/s]

Progress: 45/54.	Score: 0.8280875238116663.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.
Progress: 46/54.	Score: 0.8333422879011856.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:05<00:00,  9.25it/s]

Progress: 47/54.	Score: 0.8307906119770434.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.
Progress: 48/54.	Score: 0.8307906119770434.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.
Progress: 49/54.	Score: 0.8213549966694066.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:05<00:00,  9.92it/s]

Progress: 50/54.	Score: 0.8246730207937569.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.
Progress: 51/54.	Score: 0.8232122791718505.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:05<00:00,  9.63it/s]

Progress: 52/54.	Score: 0.8309935801323588.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.
Progress: 53/54.	Score: 0.8309935801323588.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:05<00:00,  9.63it/s]

Progress: 54/54.	Score: 0.8309935801323588.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8442887799684738
Best params: {'k_neighbors': 4, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smote_opt-smote_default-m...
holdout_test_f1_macro                                                        0.8333
holdout_test_accuracy_balanced                                             0.884091
holdout_test_roc_auc                                                       0.951818
holdout_test_f1                                                             0.77551
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.956044
cv_test_f1_median                                                               0.8
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.906667

Model saved in ../results/models_modelling4/SVC_no_fragmentation_smote_opt-smote_default-model

# CatBoost

In [13]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:03<03:29,  3.96s/it]

Progress: 1/54.	Score: 0.8923575133738559.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:07<03:25,  3.96s/it]

Progress: 2/54.	Score: 0.8896242988759354.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:11<03:23,  3.99s/it]

Progress: 3/54.	Score: 0.8861741423991966.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:16<03:23,  4.06s/it]

Progress: 4/54.	Score: 0.8790434290094277.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:20<03:23,  4.16s/it]

Progress: 5/54.	Score: 0.8832648653479857.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:24<03:22,  4.22s/it]

Progress: 6/54.	Score: 0.8832648653479857.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:28<03:13,  4.12s/it]

Progress: 7/54.	Score: 0.8855659959845384.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:32<03:07,  4.08s/it]

Progress: 8/54.	Score: 0.8894573017231349.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:36<03:03,  4.09s/it]

Progress: 9/54.	Score: 0.8862297467781091.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:41<03:02,  4.14s/it]

Progress: 10/54.	Score: 0.8865144674793642.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:45<03:00,  4.19s/it]

Progress: 11/54.	Score: 0.8865144674793642.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:49<02:57,  4.23s/it]

Progress: 12/54.	Score: 0.8865144674793642.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:53<02:49,  4.14s/it]

Progress: 13/54.	Score: 0.8967610144437679.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:57<02:44,  4.11s/it]

Progress: 14/54.	Score: 0.8901399089003652.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [01:01<02:40,  4.11s/it]

Progress: 15/54.	Score: 0.8934412852396475.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [01:06<02:38,  4.16s/it]

Progress: 16/54.	Score: 0.8828157133727688.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [01:10<02:36,  4.24s/it]

Progress: 17/54.	Score: 0.8828157133727688.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [01:14<02:33,  4.28s/it]

Progress: 18/54.	Score: 0.8828157133727688.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [01:18<02:25,  4.15s/it]

Progress: 19/54.	Score: 0.8895499795010512.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [01:22<02:20,  4.12s/it]

Progress: 20/54.	Score: 0.8892756146817032.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [01:26<02:15,  4.12s/it]

Progress: 21/54.	Score: 0.8867029840004585.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [01:30<02:09,  4.05s/it]

Progress: 22/54.	Score: 0.89084267225742.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [01:34<02:02,  3.96s/it]

Progress: 23/54.	Score: 0.8862291581655238.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [01:38<01:57,  3.92s/it]

Progress: 24/54.	Score: 0.8862291581655238.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [01:41<01:49,  3.78s/it]

Progress: 25/54.	Score: 0.8929253130840841.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [01:45<01:43,  3.70s/it]

Progress: 26/54.	Score: 0.8937990075102028.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [01:48<01:38,  3.64s/it]

Progress: 27/54.	Score: 0.8865077036671748.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [01:52<01:34,  3.62s/it]

Progress: 28/54.	Score: 0.879315787093564.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [01:56<01:31,  3.66s/it]

Progress: 29/54.	Score: 0.8867070191113652.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [01:59<01:29,  3.72s/it]

Progress: 30/54.	Score: 0.8867070191113652.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [02:03<01:23,  3.64s/it]

Progress: 31/54.	Score: 0.8856216003634511.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [02:06<01:18,  3.58s/it]

Progress: 32/54.	Score: 0.8860574502222319.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [02:10<01:15,  3.59s/it]

Progress: 33/54.	Score: 0.8861735537866113.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [02:14<01:11,  3.60s/it]

Progress: 34/54.	Score: 0.8838846780537299.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [02:17<01:09,  3.66s/it]

Progress: 35/54.	Score: 0.8836431115560058.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [02:21<01:06,  3.70s/it]

Progress: 36/54.	Score: 0.8836431115560058.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [02:25<01:01,  3.62s/it]

Progress: 37/54.	Score: 0.8855489278706893.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [02:28<00:57,  3.57s/it]

Progress: 38/54.	Score: 0.886067450412234.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [02:32<00:53,  3.55s/it]

Progress: 39/54.	Score: 0.8787062358063222.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [02:35<00:50,  3.59s/it]

Progress: 40/54.	Score: 0.8870229322401555.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [02:39<00:47,  3.65s/it]

Progress: 41/54.	Score: 0.887192441213015.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [02:43<00:44,  3.69s/it]

Progress: 42/54.	Score: 0.887192441213015.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [02:46<00:39,  3.62s/it]

Progress: 43/54.	Score: 0.8924301858666178.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [02:50<00:35,  3.59s/it]

Progress: 44/54.	Score: 0.8969111941069629.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [02:53<00:32,  3.60s/it]

Progress: 45/54.	Score: 0.8935511843652245.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [02:57<00:29,  3.68s/it]

Progress: 46/54.	Score: 0.8974989541783811.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [03:01<00:26,  3.78s/it]

Progress: 47/54.	Score: 0.8896974863175285.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [03:05<00:22,  3.81s/it]

Progress: 48/54.	Score: 0.8896974863175285.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [03:09<00:18,  3.71s/it]

Progress: 49/54.	Score: 0.8856243152379276.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [03:12<00:14,  3.66s/it]

Progress: 50/54.	Score: 0.8931534737319762.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [03:16<00:10,  3.62s/it]

Progress: 51/54.	Score: 0.8966154338879342.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [03:19<00:07,  3.66s/it]

Progress: 52/54.	Score: 0.8980714863873075.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [03:24<00:03,  3.79s/it]

Progress: 53/54.	Score: 0.8941411137645385.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [03:28<00:00,  3.85s/it]

Progress: 54/54.	Score: 0.8941411137645385.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8980714863873075
Best params: {'k_neighbors': 10, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.882261
holdout_test_accuracy_balanced                                             0.876157
holdout_test_roc_auc                                                       0.953704
holdout_test_f1                                                            0.918367
holdout_test_accuracy                                                      0.893333
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.887302
cv_test_roc_auc_median                                                     0.952012
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.842105

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smote_opt-smote_default-model

In [14]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:03<03:19,  3.76s/it]

Progress: 1/54.	Score: 0.8390464193190196.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:07<03:18,  3.82s/it]

Progress: 2/54.	Score: 0.8487522205026211.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:11<03:17,  3.87s/it]

Progress: 3/54.	Score: 0.8385766936314659.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:15<03:16,  3.93s/it]

Progress: 4/54.	Score: 0.8414596673972936.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:19<03:13,  3.96s/it]

Progress: 5/54.	Score: 0.8391394233144648.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:23<03:12,  4.01s/it]

Progress: 6/54.	Score: 0.8391394233144648.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:27<03:03,  3.91s/it]

Progress: 7/54.	Score: 0.8516616345010904.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:31<02:59,  3.91s/it]

Progress: 8/54.	Score: 0.851219689118581.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:35<02:57,  3.93s/it]

Progress: 9/54.	Score: 0.8423790589168686.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:39<02:56,  4.02s/it]

Progress: 10/54.	Score: 0.8391394233144648.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:43<02:56,  4.10s/it]

Progress: 11/54.	Score: 0.8405977620993098.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:47<02:51,  4.09s/it]

Progress: 12/54.	Score: 0.8405977620993098.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:51<02:43,  4.00s/it]

Progress: 13/54.	Score: 0.8540752981903791.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:55<02:37,  3.94s/it]

Progress: 14/54.	Score: 0.8591557272339417.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:59<02:32,  3.92s/it]

Progress: 15/54.	Score: 0.8429893145420415.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [01:03<02:29,  3.93s/it]

Progress: 16/54.	Score: 0.853977173759031.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [01:07<02:27,  3.99s/it]

Progress: 17/54.	Score: 0.8520036159437082.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [01:11<02:25,  4.03s/it]

Progress: 18/54.	Score: 0.8520036159437082.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [01:15<02:17,  3.92s/it]

Progress: 19/54.	Score: 0.8555830265314074.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [01:19<02:13,  3.93s/it]

Progress: 20/54.	Score: 0.8536142292582333.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [01:23<02:09,  3.92s/it]

Progress: 21/54.	Score: 0.8409291027226841.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [01:26<02:05,  3.92s/it]

Progress: 22/54.	Score: 0.8517955832019688.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [01:30<02:01,  3.92s/it]

Progress: 23/54.	Score: 0.8575993344571023.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [01:34<01:57,  3.93s/it]

Progress: 24/54.	Score: 0.8575993344571023.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [01:38<01:52,  3.89s/it]

Progress: 25/54.	Score: 0.8375712706989421.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [01:42<01:50,  3.95s/it]

Progress: 26/54.	Score: 0.8263156929352599.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [01:46<01:49,  4.04s/it]

Progress: 27/54.	Score: 0.8330351956557575.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [01:50<01:43,  3.99s/it]

Progress: 28/54.	Score: 0.8333078364813937.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [01:54<01:39,  3.98s/it]

Progress: 29/54.	Score: 0.8383180471108994.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [01:58<01:35,  3.97s/it]

Progress: 30/54.	Score: 0.8383180471108994.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [02:02<01:29,  3.88s/it]

Progress: 31/54.	Score: 0.8594087073737945.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [02:06<01:25,  3.87s/it]

Progress: 32/54.	Score: 0.8442348680640593.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [02:10<01:20,  3.85s/it]

Progress: 33/54.	Score: 0.8428596356110117.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [02:13<01:17,  3.86s/it]

Progress: 34/54.	Score: 0.8467853725724631.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [02:17<01:14,  3.91s/it]

Progress: 35/54.	Score: 0.8472939521571297.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [02:21<01:10,  3.92s/it]

Progress: 36/54.	Score: 0.8472939521571297.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [02:25<01:05,  3.83s/it]

Progress: 37/54.	Score: 0.8489466040589801.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [02:29<01:00,  3.79s/it]

Progress: 38/54.	Score: 0.8452337403377724.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [02:33<00:57,  3.82s/it]

Progress: 39/54.	Score: 0.8507752383134809.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [02:36<00:53,  3.82s/it]

Progress: 40/54.	Score: 0.8507752383134809.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [02:40<00:50,  3.87s/it]

Progress: 41/54.	Score: 0.850334021782413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [02:44<00:46,  3.90s/it]

Progress: 42/54.	Score: 0.850334021782413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [02:48<00:42,  3.82s/it]

Progress: 43/54.	Score: 0.8518320804899145.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [02:52<00:38,  3.83s/it]

Progress: 44/54.	Score: 0.8396380218243784.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [02:56<00:34,  3.85s/it]

Progress: 45/54.	Score: 0.8507489476988879.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [03:00<00:30,  3.84s/it]

Progress: 46/54.	Score: 0.8417049435289005.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [03:04<00:27,  3.91s/it]

Progress: 47/54.	Score: 0.8470822269933509.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [03:08<00:23,  3.93s/it]

Progress: 48/54.	Score: 0.8470822269933509.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [03:11<00:19,  3.84s/it]

Progress: 49/54.	Score: 0.8425765213144315.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [03:15<00:15,  3.84s/it]

Progress: 50/54.	Score: 0.8462497240320863.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [03:19<00:11,  3.83s/it]

Progress: 51/54.	Score: 0.8429979292430245.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [03:23<00:07,  3.87s/it]

Progress: 52/54.	Score: 0.852908144235646.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [03:27<00:03,  3.91s/it]

Progress: 53/54.	Score: 0.8476469884160467.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [03:31<00:00,  3.91s/it]

Progress: 54/54.	Score: 0.8476469884160467.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8594087073737945
Best params: {'k_neighbors': 7, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.897727
holdout_test_accuracy_balanced                                             0.897727
holdout_test_roc_auc                                                       0.985455
holdout_test_f1                                                                0.85
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                     0.969231
cv_test_f1_median                                                          0.846154
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                               0.95
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                      0.95

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smote_opt-smote_default-model

# XGBoost

In [15]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:19,  2.74it/s]

Progress: 1/54.	Score: 0.887800237173798.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:20,  2.59it/s]

Progress: 2/54.	Score: 0.8752519471493049.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:17,  2.88it/s]

Progress: 3/54.	Score: 0.872067916058979.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:16,  2.99it/s]

Progress: 4/54.	Score: 0.879245969531097.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:15,  3.25it/s]

Progress: 5/54.	Score: 0.8796575407062758.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:16,  2.86it/s]

Progress: 6/54.	Score: 0.8796575407062758.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.05it/s]

Progress: 7/54.	Score: 0.887620591537839.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:14,  3.15it/s]

Progress: 8/54.	Score: 0.8657958842294696.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:13,  3.28it/s]

Progress: 9/54.	Score: 0.8784246451806094.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:13,  3.38it/s]

Progress: 10/54.	Score: 0.8849209226409372.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:13,  3.28it/s]

Progress: 11/54.	Score: 0.8718906934704831.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:12,  3.34it/s]

Progress: 12/54.	Score: 0.8718906934704831.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:11,  3.43it/s]

Progress: 13/54.	Score: 0.8775363983709391.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:11,  3.48it/s]

Progress: 14/54.	Score: 0.8860088629851485.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:11,  3.54it/s]

Progress: 15/54.	Score: 0.8898010858367187.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:10,  3.60it/s]

Progress: 16/54.	Score: 0.872190702969825.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:10,  3.55it/s]

Progress: 17/54.	Score: 0.8637805414987371.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:10,  3.49it/s]

Progress: 18/54.	Score: 0.8637805414987371.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:10,  3.48it/s]

Progress: 19/54.	Score: 0.8814430012194674.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:10,  3.14it/s]

Progress: 20/54.	Score: 0.8641326472962102.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:11,  2.92it/s]

Progress: 21/54.	Score: 0.8742576587869785.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:11,  2.80it/s]

Progress: 22/54.	Score: 0.8828881803237063.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:11,  2.77it/s]

Progress: 23/54.	Score: 0.892480763438457.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:10,  2.89it/s]

Progress: 24/54.	Score: 0.892480763438457.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:09,  3.03it/s]

Progress: 25/54.	Score: 0.8783525777455836.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:08,  3.18it/s]

Progress: 26/54.	Score: 0.8856688482197489.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.12it/s]

Progress: 27/54.	Score: 0.8767178169182627.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:07,  3.28it/s]

Progress: 28/54.	Score: 0.8945563527969086.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:07,  3.30it/s]

Progress: 29/54.	Score: 0.8780628106667846.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:07,  3.10it/s]

Progress: 30/54.	Score: 0.8780628106667846.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:07,  3.22it/s]

Progress: 31/54.	Score: 0.8789580621986179.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:06,  3.36it/s]

Progress: 32/54.	Score: 0.8739836480071957.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.45it/s]

Progress: 33/54.	Score: 0.8782348690628025.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:06,  3.25it/s]

Progress: 34/54.	Score: 0.8763587256433534.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:10<00:05,  3.17it/s]

Progress: 35/54.	Score: 0.8978508961792794.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:06,  2.88it/s]

Progress: 36/54.	Score: 0.8978508961792794.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:05,  2.97it/s]

Progress: 37/54.	Score: 0.8700379387113479.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  3.11it/s]

Progress: 38/54.	Score: 0.8731666429419448.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.19it/s]

Progress: 39/54.	Score: 0.8843482555522544.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:04,  3.26it/s]

Progress: 40/54.	Score: 0.8615786654348592.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:12<00:03,  3.35it/s]

Progress: 41/54.	Score: 0.874485777802745.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:03,  3.41it/s]

Progress: 42/54.	Score: 0.874485777802745.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:13<00:03,  3.46it/s]

Progress: 43/54.	Score: 0.87063374528602.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:13<00:02,  3.48it/s]

Progress: 44/54.	Score: 0.8781572562578068.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.31it/s]

Progress: 45/54.	Score: 0.863788475941088.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:14<00:02,  3.40it/s]

Progress: 46/54.	Score: 0.8814806475549652.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  3.43it/s]

Progress: 47/54.	Score: 0.8710454743729211.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:14<00:01,  3.27it/s]

Progress: 48/54.	Score: 0.8710454743729211.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:15<00:01,  3.14it/s]

Progress: 49/54.	Score: 0.8748057728570624.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:15<00:01,  2.93it/s]

Progress: 50/54.	Score: 0.8813607543796353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:01,  2.88it/s]

Progress: 51/54.	Score: 0.8823874278832988.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:16<00:00,  2.78it/s]

Progress: 52/54.	Score: 0.8794701140374187.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:16<00:00,  2.76it/s]

Progress: 53/54.	Score: 0.8899261617913552.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.15it/s]

Progress: 54/54.	Score: 0.8899261617913552.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8978508961792794
Best params: {'k_neighbors': 7, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smote_opt-smote_defaul...
holdout_test_f1_macro                                                      0.852826
holdout_test_accuracy_balanced                                             0.847222
holdout_test_roc_auc                                                       0.947145
holdout_test_f1                                                            0.897959
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.850704
cv_test_accuracy_balanced_median                                           0.856037
cv_test_roc_auc_median                                                     0.946032
cv_test_f1_median                                                          0.901408
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                               0.85
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                       0.8

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smote_opt-smote_default-model

In [16]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:13,  3.79it/s]

Progress: 1/54.	Score: 0.8146533912331584.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:15,  3.35it/s]

Progress: 2/54.	Score: 0.8319091584613657.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:15,  3.30it/s]

Progress: 3/54.	Score: 0.8465548148087059.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:15,  3.19it/s]

Progress: 4/54.	Score: 0.822907436936293.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:15,  3.19it/s]

Progress: 5/54.	Score: 0.8297738020135181.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:16,  2.90it/s]

Progress: 6/54.	Score: 0.8297738020135181.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.00it/s]

Progress: 7/54.	Score: 0.8249908650974807.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:15,  2.98it/s]

Progress: 8/54.	Score: 0.8187180559088.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:14,  3.00it/s]

Progress: 9/54.	Score: 0.8371541701933631.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  3.02it/s]

Progress: 10/54.	Score: 0.8385996704299539.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:13,  3.08it/s]

Progress: 11/54.	Score: 0.8351289886541711.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:13,  3.15it/s]

Progress: 12/54.	Score: 0.8351289886541711.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.06it/s]

Progress: 13/54.	Score: 0.8225202640792506.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:13,  2.94it/s]

Progress: 14/54.	Score: 0.8404068578096983.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:13,  3.00it/s]

Progress: 15/54.	Score: 0.8372477805395044.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  3.03it/s]

Progress: 16/54.	Score: 0.8126119858584813.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  2.98it/s]

Progress: 17/54.	Score: 0.830112260738061.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:11,  3.16it/s]

Progress: 18/54.	Score: 0.830112260738061.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:10,  3.32it/s]

Progress: 19/54.	Score: 0.8324587276981351.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:09,  3.46it/s]

Progress: 20/54.	Score: 0.8347750043176905.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:09,  3.54it/s]

Progress: 21/54.	Score: 0.8271738107631125.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:06<00:08,  3.68it/s]

Progress: 22/54.	Score: 0.8478957961443727.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:08,  3.50it/s]

Progress: 23/54.	Score: 0.8303099500860233.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:08,  3.60it/s]

Progress: 24/54.	Score: 0.8303099500860233.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:07<00:07,  3.65it/s]

Progress: 25/54.	Score: 0.8228740520816257.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:08,  3.29it/s]

Progress: 26/54.	Score: 0.8300010757269864.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:09,  2.79it/s]

Progress: 27/54.	Score: 0.8253001532721832.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:08<00:09,  2.82it/s]

Progress: 28/54.	Score: 0.8132606063331794.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.87it/s]

Progress: 29/54.	Score: 0.8163774797325527.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:07,  3.05it/s]

Progress: 30/54.	Score: 0.8163774797325527.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:09<00:07,  3.20it/s]

Progress: 31/54.	Score: 0.8345077735883516.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:06,  3.31it/s]

Progress: 32/54.	Score: 0.8228462860195229.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.21it/s]

Progress: 33/54.	Score: 0.8433743133126654.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:10<00:06,  3.25it/s]

Progress: 34/54.	Score: 0.8271216951389022.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:05,  3.35it/s]

Progress: 35/54.	Score: 0.8342171435385788.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:05,  3.50it/s]

Progress: 36/54.	Score: 0.8342171435385788.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:11<00:05,  3.29it/s]

Progress: 37/54.	Score: 0.8427490568187573.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:11<00:05,  3.16it/s]

Progress: 38/54.	Score: 0.8322868237957203.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.11it/s]

Progress: 39/54.	Score: 0.8309710820658099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:12<00:04,  3.22it/s]

Progress: 40/54.	Score: 0.8532747710032924.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:12<00:04,  3.24it/s]

Progress: 41/54.	Score: 0.8379816001807543.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:03,  3.26it/s]

Progress: 42/54.	Score: 0.8379816001807543.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:13<00:03,  3.36it/s]

Progress: 43/54.	Score: 0.8246780693167797.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:13<00:02,  3.41it/s]

Progress: 44/54.	Score: 0.8323727789787025.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.46it/s]

Progress: 45/54.	Score: 0.8179027712791578.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:14<00:02,  3.48it/s]

Progress: 46/54.	Score: 0.8250343716844367.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:14<00:02,  3.50it/s]

Progress: 47/54.	Score: 0.8340623129366472.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:14<00:01,  3.62it/s]

Progress: 48/54.	Score: 0.8340623129366472.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:15<00:01,  3.72it/s]

Progress: 49/54.	Score: 0.8469623023685744.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:15<00:01,  3.64it/s]

Progress: 50/54.	Score: 0.8212318488960682.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:15<00:00,  3.64it/s]

Progress: 51/54.	Score: 0.8294095541538598.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:16<00:00,  3.18it/s]

Progress: 52/54.	Score: 0.8352634556217104.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:16<00:00,  2.86it/s]

Progress: 53/54.	Score: 0.8234044702235207.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:16<00:00,  3.19it/s]

Progress: 54/54.	Score: 0.8234044702235207.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8532747710032924
Best params: {'k_neighbors': 8, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smote_opt-smote...
holdout_test_f1_macro                                                      0.882524
holdout_test_accuracy_balanced                                             0.888636
holdout_test_roc_auc                                                       0.981818
holdout_test_f1                                                            0.829268
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.976068
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.936709

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smote_opt-smote_default-model

# AdaBoost

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:13,  3.80it/s]

Progress: 1/54.	Score: 0.8319529223221993.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:13,  3.76it/s]

Progress: 2/54.	Score: 0.8248921831081331.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:13,  3.72it/s]

Progress: 3/54.	Score: 0.8370039905878414.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:13,  3.70it/s]

Progress: 4/54.	Score: 0.8299223435476849.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:13,  3.70it/s]

Progress: 5/54.	Score: 0.8428281564453002.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:12,  3.69it/s]

Progress: 6/54.	Score: 0.8428281564453002.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:12,  3.75it/s]

Progress: 7/54.	Score: 0.8369549942506945.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:12,  3.77it/s]

Progress: 8/54.	Score: 0.8547548945911606.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:11,  3.78it/s]

Progress: 9/54.	Score: 0.8287793465080929.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:11,  3.76it/s]

Progress: 10/54.	Score: 0.8337935131593033.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:11,  3.75it/s]

Progress: 11/54.	Score: 0.8090098898867842.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:11,  3.73it/s]

Progress: 12/54.	Score: 0.8090098898867842.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:10,  3.74it/s]

Progress: 13/54.	Score: 0.8429187934837487.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:10,  3.74it/s]

Progress: 14/54.	Score: 0.833106934947163.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:10,  3.71it/s]

Progress: 15/54.	Score: 0.8367445662359021.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:10,  3.70it/s]

Progress: 16/54.	Score: 0.8439806891702032.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:04<00:10,  3.67it/s]

Progress: 17/54.	Score: 0.8526804385178769.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:04<00:09,  3.65it/s]

Progress: 18/54.	Score: 0.8526804385178769.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:05<00:09,  3.53it/s]

Progress: 19/54.	Score: 0.8509611300826094.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:05<00:09,  3.60it/s]

Progress: 20/54.	Score: 0.855767192022482.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:05<00:09,  3.63it/s]

Progress: 21/54.	Score: 0.8346869804544162.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:05<00:08,  3.65it/s]

Progress: 22/54.	Score: 0.8391818399830357.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:08,  3.66it/s]

Progress: 23/54.	Score: 0.8489748230601967.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:06<00:08,  3.67it/s]

Progress: 24/54.	Score: 0.8489748230601967.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:06<00:07,  3.72it/s]

Progress: 25/54.	Score: 0.8397275802404781.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:07<00:07,  3.75it/s]

Progress: 26/54.	Score: 0.8277416672101828.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:07<00:07,  3.76it/s]

Progress: 27/54.	Score: 0.8414696950364794.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:07<00:06,  3.76it/s]

Progress: 28/54.	Score: 0.82510670939837.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:07<00:06,  3.74it/s]

Progress: 29/54.	Score: 0.8319776267763884.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:08<00:06,  3.73it/s]

Progress: 30/54.	Score: 0.8319776267763884.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:08<00:06,  3.77it/s]

Progress: 31/54.	Score: 0.8257563451668013.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:08<00:05,  3.78it/s]

Progress: 32/54.	Score: 0.853804687111536.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:08<00:05,  3.78it/s]

Progress: 33/54.	Score: 0.8288621474201046.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:09<00:05,  3.77it/s]

Progress: 34/54.	Score: 0.8347199478101571.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:09<00:05,  3.75it/s]

Progress: 35/54.	Score: 0.843316337794579.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:09<00:04,  3.75it/s]

Progress: 36/54.	Score: 0.843316337794579.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:09<00:04,  3.77it/s]

Progress: 37/54.	Score: 0.839367909651504.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:10<00:04,  3.79it/s]

Progress: 38/54.	Score: 0.8484365229599258.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:10<00:03,  3.78it/s]

Progress: 39/54.	Score: 0.8290743468371673.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:10<00:03,  3.77it/s]

Progress: 40/54.	Score: 0.8154744336880887.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:11<00:03,  3.74it/s]

Progress: 41/54.	Score: 0.8473246107917217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:11<00:03,  3.73it/s]

Progress: 42/54.	Score: 0.8473246107917217.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:11<00:02,  3.77it/s]

Progress: 43/54.	Score: 0.8615329974498369.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:11<00:02,  3.79it/s]

Progress: 44/54.	Score: 0.8437528887590728.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:12<00:02,  3.79it/s]

Progress: 45/54.	Score: 0.8307612573710121.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:12<00:02,  3.77it/s]

Progress: 46/54.	Score: 0.834674275540916.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:12<00:01,  3.60it/s]

Progress: 47/54.	Score: 0.827559027044411.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:12<00:01,  3.63it/s]

Progress: 48/54.	Score: 0.827559027044411.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:13<00:01,  3.69it/s]

Progress: 49/54.	Score: 0.8466100167633094.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:13<00:01,  3.73it/s]

Progress: 50/54.	Score: 0.8408225053744861.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:13<00:00,  3.75it/s]

Progress: 51/54.	Score: 0.8661782507252772.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:13<00:00,  3.74it/s]

Progress: 52/54.	Score: 0.8747470964630196.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:14<00:00,  3.74it/s]

Progress: 53/54.	Score: 0.8313481430425677.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:14<00:00,  3.73it/s]

Progress: 54/54.	Score: 0.8313481430425677.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8747470964630196
Best params: {'k_neighbors': 10, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smote_opt-smote_d...
holdout_test_f1_macro                                                      0.784689
holdout_test_accuracy_balanced                                             0.787037
holdout_test_roc_auc                                                       0.859182
holdout_test_f1                                                            0.842105
holdout_test_accuracy                                                           0.8
cv_test_f1_macro_median                                                    0.813161
cv_test_accuracy_balanced_median                                           0.824303
cv_test_roc_auc_median                                                     0.902477
cv_test_f1_median                                                          0.869565
cv_test_accuracy_median                                                    0.830189
cv_test_precision_class_0_median                                           0.736842
cv_test_recall_class_0_median                                              0.736842
cv_test_f1_class_0_median                                                  0.772727

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smote_opt-smote_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:13,  3.86it/s]

Progress: 1/54.	Score: 0.8245053452863278.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:13,  3.88it/s]

Progress: 2/54.	Score: 0.8077997915379358.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:13,  3.87it/s]

Progress: 3/54.	Score: 0.8044139377361119.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:13,  3.84it/s]

Progress: 4/54.	Score: 0.8224070261802284.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:12,  3.82it/s]

Progress: 5/54.	Score: 0.8131362234219887.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:12,  3.81it/s]

Progress: 6/54.	Score: 0.8131362234219887.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:01<00:12,  3.85it/s]

Progress: 7/54.	Score: 0.8003369874442325.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:11,  3.86it/s]

Progress: 8/54.	Score: 0.8140922195587643.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:11,  3.85it/s]

Progress: 9/54.	Score: 0.8291974561157142.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:02<00:11,  3.83it/s]

Progress: 10/54.	Score: 0.7854894322047237.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:02<00:11,  3.81it/s]

Progress: 11/54.	Score: 0.8097273611358765.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:11,  3.61it/s]

Progress: 12/54.	Score: 0.8097273611358765.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:03<00:11,  3.69it/s]

Progress: 13/54.	Score: 0.8220140906193618.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:03<00:10,  3.74it/s]

Progress: 14/54.	Score: 0.7991364034549269.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:03<00:10,  3.78it/s]

Progress: 15/54.	Score: 0.8292151513576698.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:04<00:10,  3.78it/s]

Progress: 16/54.	Score: 0.821062948542109.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:04<00:09,  3.78it/s]

Progress: 17/54.	Score: 0.8281237626012464.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:04<00:09,  3.78it/s]

Progress: 18/54.	Score: 0.8281237626012464.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:04<00:09,  3.83it/s]

Progress: 19/54.	Score: 0.8094128362171009.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:05<00:08,  3.85it/s]

Progress: 20/54.	Score: 0.7852106093380665.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:05<00:08,  3.84it/s]

Progress: 21/54.	Score: 0.8193117540377423.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:05<00:08,  3.83it/s]

Progress: 22/54.	Score: 0.8024194316568504.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:06<00:08,  3.81it/s]

Progress: 23/54.	Score: 0.8218551033300344.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:06<00:07,  3.79it/s]

Progress: 24/54.	Score: 0.8218551033300344.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:06<00:07,  3.83it/s]

Progress: 25/54.	Score: 0.8420123745121898.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:06<00:07,  3.85it/s]

Progress: 26/54.	Score: 0.7987463047876417.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:07<00:07,  3.85it/s]

Progress: 27/54.	Score: 0.8114283264596273.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:07<00:06,  3.84it/s]

Progress: 28/54.	Score: 0.8305242769353587.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:07<00:06,  3.81it/s]

Progress: 29/54.	Score: 0.8063701855092132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:07<00:06,  3.80it/s]

Progress: 30/54.	Score: 0.8063701855092132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:08<00:06,  3.83it/s]

Progress: 31/54.	Score: 0.8016465357479181.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:08<00:05,  3.76it/s]

Progress: 32/54.	Score: 0.8267888220770426.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:08<00:05,  3.76it/s]

Progress: 33/54.	Score: 0.8044455245513509.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:08<00:05,  3.58it/s]

Progress: 34/54.	Score: 0.8190855771724884.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:09<00:05,  3.60it/s]

Progress: 35/54.	Score: 0.805307615173852.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:09<00:04,  3.64it/s]

Progress: 36/54.	Score: 0.805307615173852.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:09<00:04,  3.71it/s]

Progress: 37/54.	Score: 0.8243583650525946.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:10<00:04,  3.74it/s]

Progress: 38/54.	Score: 0.8093660721749797.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:10<00:04,  3.74it/s]

Progress: 39/54.	Score: 0.8088480330646727.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:10<00:03,  3.74it/s]

Progress: 40/54.	Score: 0.8139452843906538.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:10<00:03,  3.71it/s]

Progress: 41/54.	Score: 0.8162883830707405.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:11<00:03,  3.71it/s]

Progress: 42/54.	Score: 0.8162883830707405.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:11<00:02,  3.76it/s]

Progress: 43/54.	Score: 0.823732217087959.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:11<00:02,  3.76it/s]

Progress: 44/54.	Score: 0.7960527310591647.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:11<00:02,  3.78it/s]

Progress: 45/54.	Score: 0.8146755045018583.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:12<00:02,  3.78it/s]

Progress: 46/54.	Score: 0.8036356516549278.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:12<00:01,  3.77it/s]

Progress: 47/54.	Score: 0.8123683290596094.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:12<00:01,  3.76it/s]

Progress: 48/54.	Score: 0.8123683290596094.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:12<00:01,  3.81it/s]

Progress: 49/54.	Score: 0.8266118912820991.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:13<00:01,  3.83it/s]

Progress: 50/54.	Score: 0.8042215853976662.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:13<00:00,  3.83it/s]

Progress: 51/54.	Score: 0.8028908902035609.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:13<00:00,  3.82it/s]

Progress: 52/54.	Score: 0.8074278770677488.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:14<00:00,  3.80it/s]

Progress: 53/54.	Score: 0.8170346980510904.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:14<00:00,  3.78it/s]

Progress: 54/54.	Score: 0.8170346980510904.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8420123745121898
Best params: {'k_neighbors': 6, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.853293
holdout_test_accuracy_balanced                                             0.870455
holdout_test_roc_auc                                                       0.949091
holdout_test_f1                                                            0.790698
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.854396
cv_test_accuracy_balanced_median                                           0.854396
cv_test_roc_auc_median                                                     0.925824
cv_test_f1_median                                                          0.785714
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.923077

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smote_opt-smote_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:24,  2.15it/s]

Progress: 1/54.	Score: 0.8761021498738637.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:23,  2.17it/s]

Progress: 2/54.	Score: 0.8622661202474073.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:23,  2.16it/s]

Progress: 3/54.	Score: 0.8607922230114748.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:23,  2.16it/s]

Progress: 4/54.	Score: 0.8680855979824889.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:02<00:22,  2.14it/s]

Progress: 5/54.	Score: 0.8647271266337251.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:22,  2.14it/s]

Progress: 6/54.	Score: 0.8647271266337251.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:03<00:21,  2.17it/s]

Progress: 7/54.	Score: 0.8721954177885811.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:03<00:21,  2.18it/s]

Progress: 8/54.	Score: 0.8701076343422286.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:04<00:20,  2.17it/s]

Progress: 9/54.	Score: 0.8672863180035832.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:04<00:20,  2.16it/s]

Progress: 10/54.	Score: 0.8919612353209029.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:05<00:20,  2.15it/s]

Progress: 11/54.	Score: 0.8738817968557401.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:05<00:19,  2.13it/s]

Progress: 12/54.	Score: 0.8738817968557401.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:06<00:19,  2.16it/s]

Progress: 13/54.	Score: 0.8687166007395459.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:06<00:18,  2.16it/s]

Progress: 14/54.	Score: 0.8781843514026096.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:07<00:18,  2.07it/s]

Progress: 15/54.	Score: 0.8690216586975328.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:07<00:18,  2.09it/s]

Progress: 16/54.	Score: 0.8740705747628683.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:07<00:17,  2.10it/s]

Progress: 17/54.	Score: 0.8859686533510033.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:08<00:17,  2.10it/s]

Progress: 18/54.	Score: 0.8859686533510033.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:08<00:16,  2.13it/s]

Progress: 19/54.	Score: 0.8835234612558206.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:09<00:15,  2.15it/s]

Progress: 20/54.	Score: 0.861275259954068.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:09<00:15,  2.15it/s]

Progress: 21/54.	Score: 0.8687983309850128.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:10<00:14,  2.15it/s]

Progress: 22/54.	Score: 0.8895461353740091.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:10<00:14,  2.13it/s]

Progress: 23/54.	Score: 0.8638539712558758.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:11<00:14,  2.13it/s]

Progress: 24/54.	Score: 0.8638539712558758.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:11<00:13,  2.15it/s]

Progress: 25/54.	Score: 0.8578652419753017.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:12<00:12,  2.16it/s]

Progress: 26/54.	Score: 0.864486175913499.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:12<00:12,  2.17it/s]

Progress: 27/54.	Score: 0.8597218272236654.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:13<00:12,  2.15it/s]

Progress: 28/54.	Score: 0.8643883129525914.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:13<00:11,  2.14it/s]

Progress: 29/54.	Score: 0.8757617415473246.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:14<00:11,  2.14it/s]

Progress: 30/54.	Score: 0.8757617415473246.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:14<00:10,  2.16it/s]

Progress: 31/54.	Score: 0.8708167357801037.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:14<00:10,  2.17it/s]

Progress: 32/54.	Score: 0.8800175527217727.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:15<00:09,  2.17it/s]

Progress: 33/54.	Score: 0.8848598225237928.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:15<00:09,  2.11it/s]

Progress: 34/54.	Score: 0.8909028263234996.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:16<00:08,  2.12it/s]

Progress: 35/54.	Score: 0.8672339109686862.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:16<00:08,  2.12it/s]

Progress: 36/54.	Score: 0.8672339109686862.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:17<00:07,  2.16it/s]

Progress: 37/54.	Score: 0.8681033977264354.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:17<00:07,  2.18it/s]

Progress: 38/54.	Score: 0.8549240587543748.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:18<00:06,  2.19it/s]

Progress: 39/54.	Score: 0.8676647641769953.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:18<00:06,  2.18it/s]

Progress: 40/54.	Score: 0.8558601302263137.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:19<00:06,  2.16it/s]

Progress: 41/54.	Score: 0.8534422812994438.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:19<00:05,  2.13it/s]

Progress: 42/54.	Score: 0.8534422812994438.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:20<00:05,  2.14it/s]

Progress: 43/54.	Score: 0.8641564511022638.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:20<00:04,  2.13it/s]

Progress: 44/54.	Score: 0.8549817732171435.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:21<00:04,  2.11it/s]

Progress: 45/54.	Score: 0.8716666234532129.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:21<00:03,  2.11it/s]

Progress: 46/54.	Score: 0.8789464097347396.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:21<00:03,  2.09it/s]

Progress: 47/54.	Score: 0.8723554881469328.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:22<00:02,  2.09it/s]

Progress: 48/54.	Score: 0.8723554881469328.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:22<00:02,  2.11it/s]

Progress: 49/54.	Score: 0.869239240113938.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:23<00:01,  2.12it/s]

Progress: 50/54.	Score: 0.8752206995375966.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:23<00:01,  2.12it/s]

Progress: 51/54.	Score: 0.8652937009608394.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:24<00:00,  2.12it/s]

Progress: 52/54.	Score: 0.859239350791707.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:24<00:00,  2.12it/s]

Progress: 53/54.	Score: 0.8749664481884958.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:25<00:00,  2.14it/s]

Progress: 54/54.	Score: 0.8749664481884958.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8919612353209029
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smote_opt-smo...
holdout_test_f1_macro                                                          0.82
holdout_test_accuracy_balanced                                             0.810185
holdout_test_roc_auc                                                       0.953318
holdout_test_f1                                                                0.88
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                     0.87381
cv_test_accuracy_balanced_median                                            0.87381
cv_test_roc_auc_median                                                     0.946032
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.833333
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.833333

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smote_opt-smote_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:25,  2.11it/s]

Progress: 1/54.	Score: 0.8149045536409275.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:24,  2.15it/s]

Progress: 2/54.	Score: 0.812783932725985.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:23,  2.16it/s]

Progress: 3/54.	Score: 0.829047201891158.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:23,  2.15it/s]

Progress: 4/54.	Score: 0.8377009501949034.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:02<00:22,  2.14it/s]

Progress: 5/54.	Score: 0.8376545171003797.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:22,  2.13it/s]

Progress: 6/54.	Score: 0.8376545171003797.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:03<00:21,  2.16it/s]

Progress: 7/54.	Score: 0.8378618192779176.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:03<00:21,  2.18it/s]

Progress: 8/54.	Score: 0.8251627103830307.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:04<00:20,  2.18it/s]

Progress: 9/54.	Score: 0.8341813798855712.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:04<00:20,  2.17it/s]

Progress: 10/54.	Score: 0.8250869988441856.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:05<00:19,  2.15it/s]

Progress: 11/54.	Score: 0.8401925021163178.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:05<00:19,  2.14it/s]

Progress: 12/54.	Score: 0.8401925021163178.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:06<00:19,  2.12it/s]

Progress: 13/54.	Score: 0.8400145833541431.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:06<00:18,  2.14it/s]

Progress: 14/54.	Score: 0.8446794541258745.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:06<00:18,  2.15it/s]

Progress: 15/54.	Score: 0.8381746030441521.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:07<00:17,  2.14it/s]

Progress: 16/54.	Score: 0.849389583354143.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:07<00:17,  2.13it/s]

Progress: 17/54.	Score: 0.8216447264690842.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:08<00:16,  2.12it/s]

Progress: 18/54.	Score: 0.8216447264690842.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:08<00:16,  2.15it/s]

Progress: 19/54.	Score: 0.8296683067641274.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:09<00:15,  2.17it/s]

Progress: 20/54.	Score: 0.8141557316188328.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:09<00:15,  2.16it/s]

Progress: 21/54.	Score: 0.838272045206124.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:10<00:14,  2.15it/s]

Progress: 22/54.	Score: 0.8425762934413845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:10<00:14,  2.13it/s]

Progress: 23/54.	Score: 0.8349643461868624.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:11<00:14,  2.13it/s]

Progress: 24/54.	Score: 0.8349643461868624.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:11<00:13,  2.16it/s]

Progress: 25/54.	Score: 0.8062006024358022.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:12<00:12,  2.18it/s]

Progress: 26/54.	Score: 0.8180915574394719.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:12<00:12,  2.19it/s]

Progress: 27/54.	Score: 0.8365400070829566.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:12<00:11,  2.18it/s]

Progress: 28/54.	Score: 0.8380675462832426.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:13<00:11,  2.16it/s]

Progress: 29/54.	Score: 0.8348635169858942.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:13<00:11,  2.15it/s]

Progress: 30/54.	Score: 0.8348635169858942.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:14<00:10,  2.16it/s]

Progress: 31/54.	Score: 0.843652886684407.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:14<00:10,  2.18it/s]

Progress: 32/54.	Score: 0.8310654778274162.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:15<00:09,  2.18it/s]

Progress: 33/54.	Score: 0.8299556889119434.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:15<00:09,  2.19it/s]

Progress: 34/54.	Score: 0.8437898259686715.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:16<00:08,  2.17it/s]

Progress: 35/54.	Score: 0.8210941002042339.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:16<00:08,  2.15it/s]

Progress: 36/54.	Score: 0.8210941002042339.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:17<00:07,  2.18it/s]

Progress: 37/54.	Score: 0.8252712005736199.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:17<00:07,  2.19it/s]

Progress: 38/54.	Score: 0.836262796401968.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:18<00:06,  2.19it/s]

Progress: 39/54.	Score: 0.8513563724457978.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:18<00:06,  2.19it/s]

Progress: 40/54.	Score: 0.8546165423854502.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:19<00:06,  2.11it/s]

Progress: 41/54.	Score: 0.8277077910872188.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:19<00:05,  2.11it/s]

Progress: 42/54.	Score: 0.8277077910872188.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:19<00:05,  2.15it/s]

Progress: 43/54.	Score: 0.8225036414346937.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:20<00:04,  2.16it/s]

Progress: 44/54.	Score: 0.8247846187007168.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:20<00:04,  2.14it/s]

Progress: 45/54.	Score: 0.8109742497640806.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:21<00:03,  2.13it/s]

Progress: 46/54.	Score: 0.8218432047809557.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:21<00:03,  2.13it/s]

Progress: 47/54.	Score: 0.8342802877691692.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:22<00:02,  2.13it/s]

Progress: 48/54.	Score: 0.8342802877691692.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:22<00:02,  2.16it/s]

Progress: 49/54.	Score: 0.8205178964918934.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:23<00:01,  2.18it/s]

Progress: 50/54.	Score: 0.8387914431578579.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:23<00:01,  2.18it/s]

Progress: 51/54.	Score: 0.8480627264656869.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:24<00:00,  2.16it/s]

Progress: 52/54.	Score: 0.8384696875227908.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:24<00:00,  2.14it/s]

Progress: 53/54.	Score: 0.8396692434963686.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:25<00:00,  2.15it/s]

Progress: 54/54.	Score: 0.8396692434963686.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8546165423854502
Best params: {'k_neighbors': 8, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smote_...
holdout_test_f1_macro                                                      0.885894
holdout_test_accuracy_balanced                                             0.904545
holdout_test_roc_auc                                                       0.977727
holdout_test_f1                                                            0.837209
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.932479
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smote_opt-smote_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<01:04,  1.22s/it]

Progress: 1/54.	Score: 0.873621653679684.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<01:03,  1.23s/it]

Progress: 2/54.	Score: 0.8751419293571506.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:03<01:06,  1.31s/it]

Progress: 3/54.	Score: 0.8467280706811317.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:05<01:08,  1.36s/it]

Progress: 4/54.	Score: 0.8749973523252714.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:06<01:09,  1.43s/it]

Progress: 5/54.	Score: 0.886330697741549.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:08<01:14,  1.55s/it]

Progress: 6/54.	Score: 0.886330697741549.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:09<01:07,  1.43s/it]

Progress: 7/54.	Score: 0.8591570298202902.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:11<01:03,  1.38s/it]

Progress: 8/54.	Score: 0.8815778235217776.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:12<01:02,  1.38s/it]

Progress: 9/54.	Score: 0.8596305108921201.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:13<01:01,  1.41s/it]

Progress: 10/54.	Score: 0.8705543737999412.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:15<01:02,  1.46s/it]

Progress: 11/54.	Score: 0.8758737419163747.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:16<00:58,  1.39s/it]

Progress: 12/54.	Score: 0.8758737419163747.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:17<00:54,  1.33s/it]

Progress: 13/54.	Score: 0.8779136699761624.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:19<00:52,  1.31s/it]

Progress: 14/54.	Score: 0.8716476178687353.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:20<00:51,  1.33s/it]

Progress: 15/54.	Score: 0.8718215115623835.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:22<00:51,  1.36s/it]

Progress: 16/54.	Score: 0.8819278010644445.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:23<00:53,  1.43s/it]

Progress: 17/54.	Score: 0.8686340530371245.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:25<00:52,  1.45s/it]

Progress: 18/54.	Score: 0.8686340530371245.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:26<00:48,  1.38s/it]

Progress: 19/54.	Score: 0.8673790814566678.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:27<00:46,  1.37s/it]

Progress: 20/54.	Score: 0.8636704314755589.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:28<00:44,  1.35s/it]

Progress: 21/54.	Score: 0.8676986811475406.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:30<00:43,  1.35s/it]

Progress: 22/54.	Score: 0.8757146626493925.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:31<00:43,  1.40s/it]

Progress: 23/54.	Score: 0.8673310126770978.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:33<00:42,  1.40s/it]

Progress: 24/54.	Score: 0.8673310126770978.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:34<00:38,  1.34s/it]

Progress: 25/54.	Score: 0.8701966126202139.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:35<00:36,  1.32s/it]

Progress: 26/54.	Score: 0.8641094462158291.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:37<00:36,  1.35s/it]

Progress: 27/54.	Score: 0.8549724878026735.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:38<00:35,  1.36s/it]

Progress: 28/54.	Score: 0.8691159490938725.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:39<00:34,  1.38s/it]

Progress: 29/54.	Score: 0.8724876356990305.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:41<00:34,  1.43s/it]

Progress: 30/54.	Score: 0.8724876356990305.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:42<00:31,  1.37s/it]

Progress: 31/54.	Score: 0.8629722282665793.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:43<00:29,  1.32s/it]

Progress: 32/54.	Score: 0.8762631386958432.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:45<00:28,  1.35s/it]

Progress: 33/54.	Score: 0.8822812888335964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:46<00:27,  1.36s/it]

Progress: 34/54.	Score: 0.8736311833513855.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:48<00:26,  1.42s/it]

Progress: 35/54.	Score: 0.8579558110519606.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:49<00:25,  1.43s/it]

Progress: 36/54.	Score: 0.8579558110519606.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:50<00:23,  1.37s/it]

Progress: 37/54.	Score: 0.8753918386275418.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:52<00:22,  1.38s/it]

Progress: 38/54.	Score: 0.8608963737469304.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:53<00:20,  1.37s/it]

Progress: 39/54.	Score: 0.8730437374960702.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:55<00:19,  1.40s/it]

Progress: 40/54.	Score: 0.8541363383014537.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:56<00:18,  1.45s/it]

Progress: 41/54.	Score: 0.8655423857481994.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:58<00:17,  1.48s/it]

Progress: 42/54.	Score: 0.8655423857481994.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:59<00:15,  1.40s/it]

Progress: 43/54.	Score: 0.8711565810942433.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [01:00<00:13,  1.35s/it]

Progress: 44/54.	Score: 0.8681184690145928.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [01:02<00:12,  1.36s/it]

Progress: 45/54.	Score: 0.875619600157971.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [01:03<00:11,  1.39s/it]

Progress: 46/54.	Score: 0.8750871726439355.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [01:04<00:09,  1.37s/it]

Progress: 47/54.	Score: 0.8797970114916229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [01:06<00:08,  1.43s/it]

Progress: 48/54.	Score: 0.8797970114916229.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [01:07<00:06,  1.37s/it]

Progress: 49/54.	Score: 0.8668615368472192.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [01:08<00:05,  1.33s/it]

Progress: 50/54.	Score: 0.8591270823008832.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [01:10<00:04,  1.33s/it]

Progress: 51/54.	Score: 0.878666318114262.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [01:11<00:02,  1.33s/it]

Progress: 52/54.	Score: 0.8829256147055036.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [01:13<00:01,  1.42s/it]

Progress: 53/54.	Score: 0.8903045305248443.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [01:14<00:00,  1.39s/it]

Progress: 54/54.	Score: 0.8903045305248443.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8903045305248443
Best params: {'k_neighbors': 10, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smote_opt-smote_defau...
holdout_test_f1_macro                                                      0.863609
holdout_test_accuracy_balanced                                             0.849537
holdout_test_roc_auc                                                       0.950617
holdout_test_f1                                                            0.910891
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.879545
cv_test_accuracy_balanced_median                                           0.888545
cv_test_roc_auc_median                                                     0.958204
cv_test_f1_median                                                          0.909091
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.809524
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                      0.85

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smote_opt-smote_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<01:16,  1.43s/it]

Progress: 1/54.	Score: 0.835952781988868.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<01:15,  1.46s/it]

Progress: 2/54.	Score: 0.8441589295381977.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:04<01:18,  1.54s/it]

Progress: 3/54.	Score: 0.8505753697722849.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:06<01:20,  1.60s/it]

Progress: 4/54.	Score: 0.8327600750256402.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:08<01:22,  1.68s/it]

Progress: 5/54.	Score: 0.8438012174833079.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:09<01:20,  1.67s/it]

Progress: 6/54.	Score: 0.8438012174833079.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:11<01:14,  1.59s/it]

Progress: 7/54.	Score: 0.8340778093616809.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:12<01:11,  1.56s/it]

Progress: 8/54.	Score: 0.8374828957147458.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:13<01:07,  1.50s/it]

Progress: 9/54.	Score: 0.8518857142375514.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:15<01:06,  1.52s/it]

Progress: 10/54.	Score: 0.863221626940189.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:17<01:06,  1.55s/it]

Progress: 11/54.	Score: 0.8269598185455334.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:19<01:09,  1.67s/it]

Progress: 12/54.	Score: 0.8269598185455334.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:20<01:03,  1.55s/it]

Progress: 13/54.	Score: 0.8345176723060851.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:21<01:00,  1.50s/it]

Progress: 14/54.	Score: 0.8590734119907035.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:23<00:58,  1.51s/it]

Progress: 15/54.	Score: 0.849897993071956.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:24<00:58,  1.53s/it]

Progress: 16/54.	Score: 0.8237660326832981.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:26<00:58,  1.58s/it]

Progress: 17/54.	Score: 0.8353952086127909.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:28<00:58,  1.63s/it]

Progress: 18/54.	Score: 0.8353952086127909.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:29<00:54,  1.56s/it]

Progress: 19/54.	Score: 0.8223909832900251.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:31<00:51,  1.52s/it]

Progress: 20/54.	Score: 0.8316121298798725.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:32<00:50,  1.53s/it]

Progress: 21/54.	Score: 0.8535975753100183.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:34<00:49,  1.56s/it]

Progress: 22/54.	Score: 0.8523728206113625.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:36<00:50,  1.62s/it]

Progress: 23/54.	Score: 0.8615225283169387.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:37<00:50,  1.67s/it]

Progress: 24/54.	Score: 0.8615225283169387.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:39<00:46,  1.59s/it]

Progress: 25/54.	Score: 0.8190243682922306.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:40<00:43,  1.56s/it]

Progress: 26/54.	Score: 0.837382919552037.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:42<00:42,  1.57s/it]

Progress: 27/54.	Score: 0.8223358436993857.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:44<00:41,  1.60s/it]

Progress: 28/54.	Score: 0.8271539046411662.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:45<00:41,  1.65s/it]

Progress: 29/54.	Score: 0.8259165830811596.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:47<00:40,  1.69s/it]

Progress: 30/54.	Score: 0.8259165830811596.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:48<00:36,  1.57s/it]

Progress: 31/54.	Score: 0.833475723275724.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:50<00:33,  1.51s/it]

Progress: 32/54.	Score: 0.8325623448762915.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:51<00:31,  1.49s/it]

Progress: 33/54.	Score: 0.8545038069634673.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:53<00:30,  1.53s/it]

Progress: 34/54.	Score: 0.8497835410338442.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:55<00:29,  1.58s/it]

Progress: 35/54.	Score: 0.8533604230853413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:56<00:28,  1.57s/it]

Progress: 36/54.	Score: 0.8533604230853413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:58<00:25,  1.52s/it]

Progress: 37/54.	Score: 0.8338970611481459.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:59<00:23,  1.49s/it]

Progress: 38/54.	Score: 0.8448226192569945.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [01:00<00:22,  1.51s/it]

Progress: 39/54.	Score: 0.847365165236709.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [01:02<00:21,  1.52s/it]

Progress: 40/54.	Score: 0.84888583581434.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [01:04<00:20,  1.56s/it]

Progress: 41/54.	Score: 0.8400127503327341.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [01:05<00:19,  1.61s/it]

Progress: 42/54.	Score: 0.8400127503327341.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [01:07<00:16,  1.54s/it]

Progress: 43/54.	Score: 0.8362843499985682.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [01:08<00:15,  1.52s/it]

Progress: 44/54.	Score: 0.8436233563583119.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [01:10<00:13,  1.56s/it]

Progress: 45/54.	Score: 0.8352123798280403.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [01:11<00:12,  1.55s/it]

Progress: 46/54.	Score: 0.828707680749208.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [01:13<00:11,  1.65s/it]

Progress: 47/54.	Score: 0.8303021436806487.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [01:15<00:10,  1.72s/it]

Progress: 48/54.	Score: 0.8303021436806487.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [01:17<00:08,  1.62s/it]

Progress: 49/54.	Score: 0.8271831986380305.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [01:18<00:06,  1.58s/it]

Progress: 50/54.	Score: 0.8380795077034737.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [01:19<00:04,  1.52s/it]

Progress: 51/54.	Score: 0.8351345830931743.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [01:21<00:03,  1.51s/it]

Progress: 52/54.	Score: 0.8457892220568972.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [01:23<00:01,  1.62s/it]

Progress: 53/54.	Score: 0.8152994320308105.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [01:25<00:00,  1.58s/it]

Progress: 54/54.	Score: 0.8152994320308105.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.863221626940189
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smote_opt-smot...
holdout_test_f1_macro                                                      0.885894
holdout_test_accuracy_balanced                                             0.904545
holdout_test_roc_auc                                                       0.980909
holdout_test_f1                                                            0.837209
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.958974
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.944444
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.939759

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smote_opt-smote_default-model

# For the notebook with Model optimization!

In [23]:
# def update_estimator_params(
#     ml_pipe:MLPipeline,
#     suggested_params:dict,
# ) -> dict:
#     """Update the estimator parameters based on the pipeline parameters.

#     Args:
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.
#         suggested_params: A dictionary containing the suggested Estimator hyperparameters.
    
#     Returns:
#         A dictionary containing the estimator parameters.
#     """
#     estimator_params = ml_pipe._pipeline_params['estimator_params']
#     estimator_params.update(suggested_params)
#     return estimator_params

# def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
#     """Objective function for logistic regression optimization using Optuna.

#     Args:
#         trial: An Optuna trial object used to suggest hyperparameters.
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.

#     Returns:
#         The score of the model based on the specified evaluation metric.
#     """
    
#     categorical_features = ('wettability', 'inclination')
    
#     random_state = ml_pipe._pipeline_params['random_state']
    
#     # sample params
#     C = trial.suggest_loguniform('C', 1e-4, 1e3)
    
#     # SMOTE params
#     add_smote = trial.suggest_categorical('add_smote', [True, False])
#     if add_smote:
#         is_smotenc = trial.suggest_categorical('is_smotenc', [True, False])
#         smote_params = {
#             'sampling_strategy': trial.suggest_categorical(
#                 'sampling_strategy', [0.6, 0.7, 0.8, 0.9, 1.0]
#             ),
#             'k_neighbors': trial.suggest_int('k_neighbors', 3, 10),
#             'random_state': random_state,
#         }
#     else:
#         is_smotenc = False
#         smote_params = None
#     if is_smotenc:
#         wettability_cat = trial.suggest_categorical('wettability_cat', [True, False])
#         if wettability_cat:
#             inclination_cat = trial.suggest_categorical('inclination_cat', [True, False])
#         else:
#             inclination_cat = True
        
        
#         mask = [wettability_cat, inclination_cat]
        
#         masked_features = [
#             feature for feature, mask_value in zip(categorical_features, mask) 
#             if mask_value
#         ]
#         smote_params = {
#             **smote_params,
#             'categorical_features': masked_features,
#         }

#     suggested_params = {
#         "C": C,
#     }
    
#     estimator_params = update_estimator_params(ml_pipe, suggested_params)

#     estimator = LogisticRegression(
#         **estimator_params,
#         random_state=random_state,
#     )

#     score = ml_pipe.step(
#         estimator=estimator,
#         add_smote=add_smote,
#         is_smotenc=is_smotenc,
#         smote_params=smote_params,
#     )
    
#     return score



# opt = OptunaOptimizer(
#     objective=partial(logreg_objective, ml_pipe=ml_pipe),
#     study_name="logreg_study",
#     direction="maximize",
# )

# opt.optimize(n_trials=200)

# best_params = opt.study.best_trial.params
# display(best_params)
# # estimator_params = update_estimator_params(ml_pipe, best_params)

# # estimator = LogisticRegression(
# #     **estimator_params,
# #     random_state=ml_pipe._pipeline_params['random_state'],
# # )