# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from pytorch_tabular.models import CategoryEmbeddingModelConfig, TabNetModelConfig

from pathlib import Path
import sys

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    PytorchTabularEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

# from pytorch_lightning.loggers import MLFlowLogger
from pytorch_lightning.loggers import TensorBoardLogger

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'first_launch'

scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
# n_trials = 1500 # checked with 15 and 100

save_model_and_metrics = True
metrics_file = "metrics_modelling4_6-neural_networks.xlsx"

In [5]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'layers': '128-64-32',
        'activation': 'LeakyReLU',
        # 'activation_config': {'negative_slope': 0.01},
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        # 'output_dir': Path("..", "results", "models_modelling4"), # take from ml_pipe
        # 'log_target': 'wandb',
        # 'logger_name': 'default',
        # 'checkpoints': 'f1_macro',
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

2025-04-25 15:37:34,613 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:37:34,628 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:37:34,632 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:37:34,650 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:37:34,683 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:37:34,735 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:37:53,276 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:37:53,277 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:37:53,372 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:37:53,381 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:37:53,383 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:37:53,393 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:37:53,406 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:37:53,420 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:38:15,560 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:38:15,561 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:38:15,619 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:38:15,629 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:38:15,632 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:38:15,641 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:38:15,662 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:38:15,669 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:38:27,731 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:38:27,732 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:38:27,782 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:38:27,791 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:38:27,794 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:38:27,804 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:38:27,832 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:38:27,866 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:38:35,654 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:38:35,659 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:38:35,928 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:38:36,219 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:38:36,375 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:38:36,424 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:38:36,442 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:38:36,614 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:38:57,028 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:38:57,029 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:38:57,098 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:38:57,108 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:38:57,112 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:38:57,122 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:38:57,135 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:38:57,142 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:03,668 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:03,669 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:39:03,768 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:03,776 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:03,779 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:03,789 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:03,804 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:03,810 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:13,289 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:13,290 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:39:13,346 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:13,354 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:13,357 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:13,368 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:13,388 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:13,396 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (5) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:36,436 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:36,438 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                                    splashing
model                             CategoryEmbeddingModel_splashing_smote_first_l...
holdout_test_f1_macro                                                      0.823391
holdout_test_accuracy_balanced                                             0.818287
holdout_test_roc_auc                                                       0.903549
holdout_test_f1                                                            0.877551
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.842262
cv_test_accuracy_balanced_median                                           0.859133
cv_test_roc_auc_median                                                     0.934985
cv_test_f1_median                                                             0.875
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.777778
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.809524

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_splashing_smote_first_launch

In [6]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'activation': 'LeakyReLU',
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

2025-04-25 15:39:36,870 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:36,908 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:36,911 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:36,929 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:36,981 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:37,038 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:43,806 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:43,807 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:39:43,863 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:43,871 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:43,874 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:43,885 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:43,898 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:43,904 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:48,662 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:48,663 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:39:48,724 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:48,733 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:48,736 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:48,747 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:48,761 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:48,770 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:39:56,047 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:39:56,048 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:39:56,118 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:39:56,128 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:39:56,131 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:39:56,145 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:39:56,158 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:39:56,165 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:40:16,672 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:40:16,674 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:40:16,737 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:40:16,747 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:40:16,750 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:40:16,761 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:40:16,782 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:40:16,814 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:40:24,690 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:40:24,691 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:40:24,745 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:40:24,755 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:40:24,758 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:40:24,769 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:40:25,030 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:40:25,037 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:40:31,687 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:40:31,688 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:40:31,743 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:40:31,752 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:40:31,754 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:40:31,768 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:40:31,781 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:40:31,788 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:40:39,918 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:40:39,921 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 15:40:40,351 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 15:40:40,403 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 15:40:40,429 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 15:40:40,469 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 15:40:40,604 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 15:40:40,642 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 15:40:55,201 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 15:40:55,204 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.853293
holdout_test_accuracy_balanced                                             0.870455
holdout_test_roc_auc                                                       0.969091
holdout_test_f1                                                            0.790698
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.902564
cv_test_roc_auc_median                                                     0.964103
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.971429
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.931507

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_no_fragmentation_smotenc_first_launch