# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from pytorch_tabular.models import CategoryEmbeddingModelConfig, TabNetModelConfig

import optuna

from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    PytorchTabularEstimator,
    deep_update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

# from pytorch_lightning.loggers import MLFlowLogger
from pytorch_lightning.loggers import TensorBoardLogger

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'

scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 3 # make about hundred

save_model_and_metrics = False
metrics_file = "metrics_modelling4_6-neural_networks.xlsx"

## Optimization function

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    add_smote:bool,
    is_smotenc:bool,
    smote_params:dict,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    opt_cv_folds:int=3,
    seed:int=seed,
):
    
    estimator_params = estimator_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
        cv_folds=opt_cv_folds,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    print('raw best_params')
    display(best_params)
    
    if params_to_process:
        for param in params_to_process:
            if param == 'log2_size':
                keys = [k for k in best_params.keys() if param in k]
                sorted_keys = sorted(keys, key=lambda k: int(k.split("_")[1]))
                layer_sizes = [
                    2**best_params.pop(key)
                    for key in sorted_keys
                ]
                best_params['layers'] = '-'.join(map(str, layer_sizes))
            elif param == 'num_layers':
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params.pop(key)
            else: # Other cases
                # Find one key in best_params which contains param
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    suggested_estimator_params = {
        "model_config_params": best_params
    }
    best_estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_estimator_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

## MultiLayer Perceptron (MLP)

In [6]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

params_to_process = [
    'num_layers', # drop this param
    'log2_size', # process to get string of layer sizes
]

def MLP_objective(
    trial:optuna.trial.Trial, 
    ml_pipe:MLPipeline,
):
    
    num_layers = trial.suggest_int('num_layers', 1, 3) # number of hidden layers
    layer_sizes = [
        2**trial.suggest_int(f'layer_{i}_log2_size', 0, 7)
        for i in range(num_layers)
    ]
    layers = '-'.join(map(str, layer_sizes))
    activation = trial.suggest_categorical('activation', ['ReLU', 'LeakyReLU', 'ELU'])
    dropout = trial.suggest_float('dropout', 0.0, 0.5)
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1, log=True)
    use_batch_norm = trial.suggest_categorical('use_batch_norm', [True, False])
    batch_norm_continuous_input = trial.suggest_categorical('batch_norm_continuous_input', [True, False])
    
    suggested_estimator_params = {
        "model_config_params": {
            'layers': layers,
            'activation': activation,
            'dropout': dropout,
            'batch_norm_continuous_input': batch_norm_continuous_input,
            'use_batch_norm': use_batch_norm,
            'learning_rate': learning_rate,
        }
    }
    
    estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # SET in optuna
    # "model_config_params": {
    #     'layers': '128-64-32',
    #     'activation': 'LeakyReLU',
    #     'dropout': 0.2,
    #     'batch_norm_continuous_input': True, # We already have normalized features    
    #     'use_batch_norm': False, # For hidden layers
    #     'learning_rate': 1e-3,
    # },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

# ml_pipe = MLPipeline(
#     target=target,
#     estimator=estimator,
#     estimator_params=estimator_params,
#     model_postfix=model_postfix,
#     add_smote=add_smote,
#     is_smotenc=is_smotenc,
#     smote_params=smote_params,
#     metrics_file=metrics_file,
# )

# ml_pipe.run(
#     save_model_and_metrics=save_model_and_metrics,
# )

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=MLP_objective,
    n_trials=n_trials,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-26 23:19:07,348] A new study created in memory with name: model_study

2025-04-26 23:19:07,363 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:07,375 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:07,379 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:07,388 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:07,403 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:07,418 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:09,188 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:09,189 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:09,218 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:09,229 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:09,232 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:09,242 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:09,291 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:09,304 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:10,796 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:10,797 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:10,827 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:10,836 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:10,838 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:10,849 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:10,862 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:10,868 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:13,287 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:13,288 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-26 23:19:13,307] Trial 0 finished with value: 0.8527356568931058 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'activation': 'ReLU', 'dropout': 0.02904180608409973, 'learning_rate': 0.029154431891537533, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8527356568931058.

2025-04-26 23:19:13,319 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:13,328 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:13,330 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:13,340 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:13,353 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:13,361 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:14,093 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:14,094 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:14,123 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:14,133 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:14,135 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:14,145 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:14,158 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:14,164 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

`Trainer.fit` stopped: `max_epochs=200` reached.

2025-04-26 23:19:25,766 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:25,767 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:25,794 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:25,803 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:25,805 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:25,815 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:25,864 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:25,874 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:26,473 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:26,474 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-26 23:19:26,491] Trial 1 finished with value: 0.42598120508568266 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 1, 'layer_2_log2_size': 1, 'activation': 'LeakyReLU', 'dropout': 0.14561457009902096, 'learning_rate': 0.0028016351587162596, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8527356568931058.

2025-04-26 23:19:26,502 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:26,511 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:26,514 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:26,523 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:26,537 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:26,544 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:28,338 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:28,338 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:28,367 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:28,377 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:28,380 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:28,390 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:28,403 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:28,410 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:31,707 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:31,708 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:31,738 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:31,749 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:31,751 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:31,761 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:31,775 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:31,781 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:33,749 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:33,751 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-26 23:19:33,774] Trial 2 finished with value: 0.7685154423526517 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 4, 'layer_2_log2_size': 4, 'activation': 'LeakyReLU', 'dropout': 0.03252579649263976, 'learning_rate': 0.06245139574743072, 'use_batch_norm': True, 'batch_norm_continuous_input': True}. Best is trial 0 with value: 0.8527356568931058.

raw best_params

{'num_layers': 2,
 'layer_0_log2_size': 7,
 'layer_1_log2_size': 5,
 'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False}

best_params

{'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False,
 'layers': '128-32'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

2025-04-26 23:19:33,846 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:33,858 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:33,862 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:33,873 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:33,887 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:33,894 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:38,894 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:38,894 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:38,943 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:38,952 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:38,955 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:38,964 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:38,977 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:38,983 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:43,083 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:43,085 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:43,138 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:43,151 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:43,154 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:43,164 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:43,186 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:43,194 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:44,728 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:44,729 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:44,788 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:44,797 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:44,800 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:44,811 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:44,824 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:44,830 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:47,425 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:47,426 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:47,517 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:47,526 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:47,528 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:47,539 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:47,552 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:47,558 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:50,020 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:50,021 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:50,113 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:50,123 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:50,126 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:50,135 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:50,150 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:50,157 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:52,515 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:52,515 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:52,564 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:52,573 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:52,575 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:52,585 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:52,598 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:52,604 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:55,293 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:55,294 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-26 23:19:55,343 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-26 23:19:55,352 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-26 23:19:55,355 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-26 23:19:55,364 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-26 23:19:55,378 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-26 23:19:55,386 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-26 23:19:57,629 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-26 23:19:57,630 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                 0
target                                                                   splashing
model                             CategoryEmbeddingModel_splashing_smote_opt-model
holdout_test_f1_macro                                                         0.85
holdout_test_accuracy_balanced                                             0.83912
holdout_test_roc_auc                                                       0.91358
holdout_test_f1                                                                0.9
holdout_test_accuracy                                                     0.866667
cv_test_f1_macro_median                                                   0.839394
cv_test_accuracy_balanced_median                                          0.847523
cv_test_roc_auc_median                                                    0.941176
cv_test_f1_median                                                         0.888889
cv_test_accuracy_median                                                   0.849057
cv_test_precision_class_0_median                                          0.857143
cv_test_recall_class_0_median                                             0.842105
cv_test_f1_class_0_median                                                      0.8

In [6]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'activation': 'LeakyReLU',
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
    metrics_file=metrics_file,
)

ml_pipe.run(
    save_model_and_metrics=save_model_and_metrics,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

2025-04-25 18:02:48,071 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:48,085 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:48,088 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:48,106 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:48,132 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:48,140 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:52,514 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:52,515 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:52,570 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:52,580 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:52,582 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:52,592 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:52,605 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:52,611 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:02:58,037 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:02:58,038 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:02:58,092 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:02:58,101 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:02:58,103 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:02:58,113 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:02:58,126 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:02:58,132 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:04,271 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:04,275 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:04,671 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:04,685 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:04,691 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:04,765 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:04,910 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:04,988 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:25,639 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:25,640 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:25,702 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:25,712 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:25,714 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:25,726 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:26,011 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:26,018 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:35,392 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:35,393 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:35,445 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:35,454 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:35,457 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:35,466 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:35,481 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:35,487 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:03:43,112 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:03:43,113 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:03:43,165 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:03:43,174 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:03:43,177 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:03:43,186 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:03:43,199 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:03:43,205 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:04:01,072 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:04:01,076 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-25 18:04:01,190 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-25 18:04:01,213 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-25 18:04:01,218 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-25 18:04:01,234 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-25 18:04:01,264 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-25 18:04:01,278 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │ 11.4 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 11.4 K
Non-trainable params: 0
Total params: 11.4 K
Total estimated model params size (MB): 0
Modules in train mode: 19
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (6) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-25 18:04:07,897 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-25 18:04:07,898 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.853293
holdout_test_accuracy_balanced                                             0.870455
holdout_test_roc_auc                                                           0.97
holdout_test_f1                                                            0.790698
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.902564
cv_test_roc_auc_median                                                     0.965812
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.971429
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.931507

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_no_fragmentation_smotenc_first_launch