Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

base_estimator_params - redundant thing in logging! - SOLVED!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 1500 # checked with 15 and 100

save_model_and_metrics = True
metrics_file = "metrics_modelling4_2.2-pure_smote_with_ensembles.xlsx"

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    base_estimator:Type[BaseEstimator]=None,
    base_estimator_params:dict=None,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    base_estimator_params_list:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    
    estimator_params = estimator_params.copy()
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    # Process base_estimator_params
    if base_estimator_params_list:
        best_params_base_estimator = {}
        for param in base_estimator_params_list:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params_base_estimator[param] = best_params.pop(key)
        print('best_params for main estimator')
        display(best_params)
        print('best_params for base estimator')
        display(best_params_base_estimator)
        if base_estimator_params is None:
            base_estimator_params = best_params_base_estimator
        else:
            base_estimator_params = base_estimator_params.copy()
            base_estimator_params.update(best_params_base_estimator)
    else:
        print('best_params')
        display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        base_estimator=base_estimator,
        base_estimator_params=base_estimator_params, # Would be None if base_estimator_params_list is not provided
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# CatBoost

In [6]:
estimator = CatBoostClassifier
target = 'splashing'
# TODO: Try with GPU!
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

def catboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "iterations": trial.suggest_int("iterations", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 3, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "grow_policy": trial.suggest_categorical("grow_policy", ["SymmetricTree", "Depthwise", "Lossguide"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"]),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", ["Balanced", "SqrtBalanced", None]),
    }
    
    if suggested_estimator_params['bootstrap_type'] == 'Bernoulli':
        suggested_estimator_params['subsample'] = trial.suggest_float(
            "subsample", 0.5, 1.0
        )
        
    if suggested_estimator_params['bootstrap_type'] == 'Bayesian':
        suggested_estimator_params['bagging_temperature'] = (
            trial.suggest_float("bagging_temperature", 0.0, 1.0)
        )

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:21:30,698] A new study created in memory with name: model_study
[I 2025-04-15 20:21:37,714] Trial 0 finished with value: 0.8788453856583421 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8788453856583421.
[I 2025-04-15 20:21:41,229] Trial 1 finished with value: 0.8889425016414505 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 1 with value: 0.8889425016414505.
[I 2025-04-15 20:21:51,839] Trial 2 finished with value: 0.8725962524773413 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 1 with value: 0.8889425016414505.
[I 2025-04-15 20:21:55,650] Trial 3 finished with value: 0.8900446899655081 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 3 with value: 0.8900446899655081.
[I 2025-04-15 20:21:57,458] Trial 4 finished with value: 0.8945547731189574 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 4 with value: 0.8945547731189574.
[I 2025-04-15 20:22:00,752] Trial 5 finished with value: 0.8850905591733955 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 4 with value: 0.8945547731189574.
[I 2025-04-15 20:22:02,686] Trial 6 finished with value: 0.9040339121149098 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:12,111] Trial 7 finished with value: 0.8741000748550597 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:27,791] Trial 8 finished with value: 0.8652861394156824 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:29,020] Trial 9 finished with value: 0.8737651190201366 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:31,427] Trial 10 finished with value: 0.8934195956812656 and parameters: {'iterations': 652, 'learning_rate': 0.03357104002950685, 'depth': 5, 'l2_leaf_reg': 0.0011799062523159302, 'random_strength': 0.5025312176747964, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.06569066558371356}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:33,640] Trial 11 finished with value: 0.9001029965399174 and parameters: {'iterations': 727, 'learning_rate': 0.0073749081572081895, 'depth': 5, 'l2_leaf_reg': 0.0013119764983343123, 'random_strength': 0.9930825760518938, 'border_count': 34, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.214371635598811}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:36,069] Trial 12 finished with value: 0.900665881661609 and parameters: {'iterations': 750, 'learning_rate': 0.05105823178669681, 'depth': 5, 'l2_leaf_reg': 0.006683150038358297, 'random_strength': 0.9841534006656731, 'border_count': 100, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.2215616556304191}. Best is trial 6 with value: 0.9040339121149098.
[I 2025-04-15 20:22:39,345] Trial 13 finished with value: 0.9045571874002054 and parameters: {'iterations': 1000, 'learning_rate': 0.06022034590553757, 'depth': 5, 'l2_leaf_reg': 0.0065909712392981335, 'random_strength': 0.40095596968204394, 'border_count': 102, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.38060929899144225}. Best is trial 13 with value: 0.9045571874002054.
[I 2025-04-15 20:22:43,494] Trial 14 finished with value: 0.8967606333019182 and parameters: {'iterations': 1000, 'learning_rate': 0.07275076927195358, 'depth': 6, 'l2_leaf_reg': 0.007014792137864262, 'random_strength': 0.368076402373047, 'border_count': 127, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.5199585884085265}. Best is trial 13 with value: 0.9045571874002054.

best_params

{'iterations': 1000,
 'learning_rate': 0.06022034590553757,
 'depth': 5,
 'l2_leaf_reg': 0.0065909712392981335,
 'random_strength': 0.40095596968204394,
 'border_count': 102,
 'grow_policy': 'SymmetricTree',
 'bootstrap_type': 'Bayesian',
 'auto_class_weights': 'Balanced',
 'bagging_temperature': 0.38060929899144225}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                             0
target                                                               splashing
model                             CatBoostClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                                 0.882261
holdout_test_accuracy_balanced                                        0.876157
holdout_test_roc_auc                                                  0.957562
holdout_test_f1                                                       0.918367
holdout_test_accuracy                                                 0.893333
cv_test_f1_macro_median                                               0.898584
cv_test_accuracy_balanced_median                                      0.903251
cv_test_roc_auc_median                                                0.958204
cv_test_f1_median                                                     0.925373
cv_test_accuracy_median                                                0.90566
cv_test_precision_class_0_median                                          0.85
cv_test_recall_class_0_median                                         0.894737
cv_test_f1_class_0_median                                             0.871795

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smote_opt-model

In [7]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:22:47,788] A new study created in memory with name: model_study
[I 2025-04-15 20:22:57,794] Trial 0 finished with value: 0.8419324527019028 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8419324527019028.
[I 2025-04-15 20:23:01,214] Trial 1 finished with value: 0.8567647997561406 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 1 with value: 0.8567647997561406.
[I 2025-04-15 20:23:11,067] Trial 2 finished with value: 0.8383569024074005 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 1 with value: 0.8567647997561406.
[I 2025-04-15 20:23:14,957] Trial 3 finished with value: 0.8545957061602287 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 1 with value: 0.8567647997561406.
[I 2025-04-15 20:23:16,772] Trial 4 finished with value: 0.8581711347408352 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 4 with value: 0.8581711347408352.
[I 2025-04-15 20:23:20,274] Trial 5 finished with value: 0.8461413039599345 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 4 with value: 0.8581711347408352.
[I 2025-04-15 20:23:22,179] Trial 6 finished with value: 0.8722295554335029 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:31,349] Trial 7 finished with value: 0.8312936875318148 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:47,041] Trial 8 finished with value: 0.8567647997561406 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:48,227] Trial 9 finished with value: 0.8385765885496765 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:50,656] Trial 10 finished with value: 0.857294491002941 and parameters: {'iterations': 652, 'learning_rate': 0.03357104002950685, 'depth': 5, 'l2_leaf_reg': 0.0011799062523159302, 'random_strength': 0.5025312176747964, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.06569066558371356}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:52,955] Trial 11 finished with value: 0.866218867899393 and parameters: {'iterations': 727, 'learning_rate': 0.0073749081572081895, 'depth': 5, 'l2_leaf_reg': 0.0013119764983343123, 'random_strength': 0.9930825760518938, 'border_count': 34, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.214371635598811}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:55,677] Trial 12 finished with value: 0.856847898005732 and parameters: {'iterations': 750, 'learning_rate': 0.05105823178669681, 'depth': 5, 'l2_leaf_reg': 0.006683150038358297, 'random_strength': 0.9841534006656731, 'border_count': 100, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.2215616556304191}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:23:58,716] Trial 13 finished with value: 0.8495896043140468 and parameters: {'iterations': 1000, 'learning_rate': 0.01078382443857064, 'depth': 5, 'l2_leaf_reg': 0.0012068354828379609, 'random_strength': 0.6071134534463066, 'border_count': 36, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.38060929899144225}. Best is trial 6 with value: 0.8722295554335029.
[I 2025-04-15 20:24:01,132] Trial 14 finished with value: 0.8482123290721351 and parameters: {'iterations': 561, 'learning_rate': 0.012238194113034407, 'depth': 6, 'l2_leaf_reg': 0.007014792137864262, 'random_strength': 0.3339780712953955, 'border_count': 85, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.4485480568900761}. Best is trial 6 with value: 0.8722295554335029.

best_params

{'iterations': 519,
 'learning_rate': 0.019718442220616167,
 'depth': 6,
 'l2_leaf_reg': 0.0012637946338082875,
 'random_strength': 0.10789142699330445,
 'border_count': 39,
 'grow_policy': 'SymmetricTree',
 'bootstrap_type': 'Bayesian',
 'auto_class_weights': 'Balanced',
 'bagging_temperature': 0.289751452913768}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.913375
holdout_test_accuracy_balanced                                             0.906818
holdout_test_roc_auc                                                       0.984545
holdout_test_f1                                                            0.871795
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                     0.90293
cv_test_accuracy_balanced_median                                           0.900183
cv_test_roc_auc_median                                                     0.981197
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.948718
cv_test_recall_class_0_median                                              0.974359
cv_test_f1_class_0_median                                                      0.95

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smote_opt-model

# XGBoost

In [8]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {
    'n_jobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 132/240 # For splashing

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [scale_pos_weight, 1.0]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:24:03,764] A new study created in memory with name: model_study
[I 2025-04-15 20:24:03,969] Trial 0 finished with value: 0.751780256501701 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 0.55}. Best is trial 0 with value: 0.751780256501701.
[I 2025-04-15 20:24:04,405] Trial 1 finished with value: 0.8268852139678102 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:04,608] Trial 2 finished with value: 0.7514365300108291 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:05,045] Trial 3 finished with value: 0.8260590652461239 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:05,235] Trial 4 finished with value: 0.7482337324549032 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:05,781] Trial 5 finished with value: 0.8014061662222185 and parameters: {'n_estimators': 926, 'learning_rate': 0.0016565580440884786, 'max_depth': 2, 'min_child_weight': 1, 'gamma': 1.6266516538163218, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:05,917] Trial 6 finished with value: 0.7557226559857513 and parameters: {'n_estimators': 184, 'learning_rate': 0.09708210658008556, 'max_depth': 1, 'min_child_weight': 20, 'gamma': 3.861223846483287, 'subsample': 0.5993578407670862, 'colsample_bytree': 0.5027610585618012, 'reg_alpha': 1.8274508859816028, 'reg_lambda': 0.6720930050156113, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:06,043] Trial 7 finished with value: 0.26121337827326935 and parameters: {'n_estimators': 120, 'learning_rate': 0.007726148927746463, 'max_depth': 2, 'min_child_weight': 18, 'gamma': 3.1164906341377896, 'subsample': 0.6654490124263246, 'colsample_bytree': 0.5317791751430119, 'reg_alpha': 0.017535949529764425, 'reg_lambda': 0.01998634077852888, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:06,399] Trial 8 finished with value: 0.7449923277849271 and parameters: {'n_estimators': 893, 'learning_rate': 0.014782014634883782, 'max_depth': 2, 'min_child_weight': 15, 'gamma': 3.803925243084487, 'subsample': 0.7806385987847482, 'colsample_bytree': 0.8854835899772805, 'reg_alpha': 0.09444574254983566, 'reg_lambda': 0.12329098365270515, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:06,564] Trial 9 finished with value: 0.26121337827326935 and parameters: {'n_estimators': 152, 'learning_rate': 0.0011963380170058652, 'max_depth': 7, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'scale_pos_weight': 0.55}. Best is trial 1 with value: 0.8268852139678102.
[I 2025-04-15 20:24:06,936] Trial 10 finished with value: 0.8542079280790495 and parameters: {'n_estimators': 671, 'learning_rate': 0.05406128459617322, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.658087572237882, 'subsample': 0.5193625999805915, 'colsample_bytree': 0.8271882613853767, 'reg_alpha': 0.31356971313563664, 'reg_lambda': 0.0016185820655420032, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8542079280790495.
[I 2025-04-15 20:24:07,332] Trial 11 finished with value: 0.8393700724088751 and parameters: {'n_estimators': 687, 'learning_rate': 0.05326260658481708, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.7125799686887835, 'subsample': 0.5062719837848048, 'colsample_bytree': 0.8201950992447397, 'reg_alpha': 0.30044011198977605, 'reg_lambda': 0.0010951175441624634, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8542079280790495.
[I 2025-04-15 20:24:07,801] Trial 12 finished with value: 0.8513050239062323 and parameters: {'n_estimators': 671, 'learning_rate': 0.05011092496777477, 'max_depth': 5, 'min_child_weight': 1, 'gamma': 1.7381671524829143, 'subsample': 0.516792942467236, 'colsample_bytree': 0.8687726793294727, 'reg_alpha': 0.37947060877945143, 'reg_lambda': 0.0014775862080349449, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8542079280790495.
[I 2025-04-15 20:24:08,171] Trial 13 finished with value: 0.8381150901374462 and parameters: {'n_estimators': 672, 'learning_rate': 0.025390067826799, 'max_depth': 6, 'min_child_weight': 5, 'gamma': 1.8419430354275477, 'subsample': 0.5100656723353845, 'colsample_bytree': 0.9002256231167883, 'reg_alpha': 0.4893501922734305, 'reg_lambda': 0.0011534279870999457, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8542079280790495.
[I 2025-04-15 20:24:08,501] Trial 14 finished with value: 0.7933821089810721 and parameters: {'n_estimators': 615, 'learning_rate': 0.033104775910188546, 'max_depth': 6, 'min_child_weight': 3, 'gamma': 1.9780137919149408, 'subsample': 0.5073279768645609, 'colsample_bytree': 0.8933139358849993, 'reg_alpha': 7.5349332296701546, 'reg_lambda': 0.0041312908860572485, 'scale_pos_weight': 1.0}. Best is trial 10 with value: 0.8542079280790495.

best_params

{'n_estimators': 671,
 'learning_rate': 0.05406128459617322,
 'max_depth': 4,
 'min_child_weight': 1,
 'gamma': 1.658087572237882,
 'subsample': 0.5193625999805915,
 'colsample_bytree': 0.8271882613853767,
 'reg_alpha': 0.31356971313563664,
 'reg_lambda': 0.0016185820655420032,
 'scale_pos_weight': 1.0}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                        0
target                                                          splashing
model                             XGBClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                            0.810348
holdout_test_accuracy_balanced                                    0.80787
holdout_test_roc_auc                                             0.922068
holdout_test_f1                                                  0.865979
holdout_test_accuracy                                            0.826667
cv_test_f1_macro_median                                          0.817451
cv_test_accuracy_balanced_median                                 0.841331
cv_test_roc_auc_median                                           0.941176
cv_test_f1_median                                                0.865672
cv_test_accuracy_median                                          0.830189
cv_test_precision_class_0_median                                     0.75
cv_test_recall_class_0_median                                    0.894737
cv_test_f1_class_0_median                                        0.782609

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smote_opt-model

In [9]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {
    'n_jobs': 1,
}
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 273/99 # For no_fragmentation

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [1.0, scale_pos_weight]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:24:09,252] A new study created in memory with name: model_study
[I 2025-04-15 20:24:09,467] Trial 0 finished with value: 0.8103606040406041 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 1.0}. Best is trial 0 with value: 0.8103606040406041.
[I 2025-04-15 20:24:09,888] Trial 1 finished with value: 0.8448348837400322 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:10,134] Trial 2 finished with value: 0.7731733979542277 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 5, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:10,602] Trial 3 finished with value: 0.8371800904217874 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:10,801] Trial 4 finished with value: 0.7928947377822756 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 4, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:11,324] Trial 5 finished with value: 0.7332350409146289 and parameters: {'n_estimators': 926, 'learning_rate': 0.0016565580440884786, 'max_depth': 2, 'min_child_weight': 1, 'gamma': 1.6266516538163218, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:11,458] Trial 6 finished with value: 0.7104299626083985 and parameters: {'n_estimators': 184, 'learning_rate': 0.09708210658008556, 'max_depth': 1, 'min_child_weight': 20, 'gamma': 3.861223846483287, 'subsample': 0.5993578407670862, 'colsample_bytree': 0.5027610585618012, 'reg_alpha': 1.8274508859816028, 'reg_lambda': 0.6720930050156113, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:11,577] Trial 7 finished with value: 0.7866289959078575 and parameters: {'n_estimators': 120, 'learning_rate': 0.007726148927746463, 'max_depth': 2, 'min_child_weight': 18, 'gamma': 3.1164906341377896, 'subsample': 0.6654490124263246, 'colsample_bytree': 0.5317791751430119, 'reg_alpha': 0.017535949529764425, 'reg_lambda': 0.01998634077852888, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:11,963] Trial 8 finished with value: 0.7906630599452711 and parameters: {'n_estimators': 893, 'learning_rate': 0.014782014634883782, 'max_depth': 2, 'min_child_weight': 15, 'gamma': 3.803925243084487, 'subsample': 0.7806385987847482, 'colsample_bytree': 0.8854835899772805, 'reg_alpha': 0.09444574254983566, 'reg_lambda': 0.12329098365270515, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:12,167] Trial 9 finished with value: 0.8119103126691238 and parameters: {'n_estimators': 152, 'learning_rate': 0.0011963380170058652, 'max_depth': 7, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:12,631] Trial 10 finished with value: 0.8221699836701822 and parameters: {'n_estimators': 671, 'learning_rate': 0.05406128459617322, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.658087572237882, 'subsample': 0.5193625999805915, 'colsample_bytree': 0.8271882613853767, 'reg_alpha': 0.31356971313563664, 'reg_lambda': 0.0016185820655420032, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:13,009] Trial 11 finished with value: 0.8398356331775708 and parameters: {'n_estimators': 733, 'learning_rate': 0.2479368227400565, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.11239512174811128, 'subsample': 0.8773233048862263, 'colsample_bytree': 0.713556152816666, 'reg_alpha': 0.00421149961829754, 'reg_lambda': 0.007300358083644766, 'scale_pos_weight': 2.757575757575758}. Best is trial 1 with value: 0.8448348837400322.
[I 2025-04-15 20:24:13,409] Trial 12 finished with value: 0.8530048420944534 and parameters: {'n_estimators': 708, 'learning_rate': 0.11749951817818961, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.07693558434914828, 'subsample': 0.9236541593937218, 'colsample_bytree': 0.7071019514729291, 'reg_alpha': 0.008101324842116031, 'reg_lambda': 0.0021730658340439915, 'scale_pos_weight': 2.757575757575758}. Best is trial 12 with value: 0.8530048420944534.
[I 2025-04-15 20:24:13,771] Trial 13 finished with value: 0.8466911520810171 and parameters: {'n_estimators': 745, 'learning_rate': 0.08236088585568294, 'max_depth': 6, 'min_child_weight': 5, 'gamma': 1.5611746796105823, 'subsample': 0.9989520987752952, 'colsample_bytree': 0.6654564209034074, 'reg_alpha': 0.01523180665425264, 'reg_lambda': 0.0011791456250406795, 'scale_pos_weight': 2.757575757575758}. Best is trial 12 with value: 0.8530048420944534.
[I 2025-04-15 20:24:14,141] Trial 14 finished with value: 0.8454723831785914 and parameters: {'n_estimators': 612, 'learning_rate': 0.03451704834246063, 'max_depth': 7, 'min_child_weight': 4, 'gamma': 1.6076881739585187, 'subsample': 0.9926960960796222, 'colsample_bytree': 0.6321255096900481, 'reg_alpha': 0.010545671573281484, 'reg_lambda': 0.0011065136021091012, 'scale_pos_weight': 2.757575757575758}. Best is trial 12 with value: 0.8530048420944534.

best_params

{'n_estimators': 708,
 'learning_rate': 0.11749951817818961,
 'max_depth': 10,
 'min_child_weight': 6,
 'gamma': 0.07693558434914828,
 'subsample': 0.9236541593937218,
 'colsample_bytree': 0.7071019514729291,
 'reg_alpha': 0.008101324842116031,
 'reg_lambda': 0.0021730658340439915,
 'scale_pos_weight': 2.757575757575758}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                               0
target                                                          no_fragmentation
model                             XGBClassifier_no_fragmentation_smote_opt-model
holdout_test_f1_macro                                                   0.867725
holdout_test_accuracy_balanced                                          0.879545
holdout_test_roc_auc                                                        0.97
holdout_test_f1                                                         0.809524
holdout_test_accuracy                                                   0.893333
cv_test_f1_macro_median                                                 0.861538
cv_test_accuracy_balanced_median                                         0.89011
cv_test_roc_auc_median                                                  0.967521
cv_test_f1_median                                                            0.8
cv_test_accuracy_median                                                 0.888889
cv_test_precision_class_0_median                                        0.947368
cv_test_recall_class_0_median                                           0.923077
cv_test_f1_class_0_median                                                  0.925

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smote_opt-model

# AdaBoost

In [10]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

def adaboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_base_estimator_params = {
        "max_depth": trial.suggest_int("max_depth", 1, 10),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 1, 20), # Closed to min_child_weight
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }
    base_estimator_params = update_estimator_params(
        ml_pipe,
        suggested_base_estimator_params,
        estimator_type='base',
    )

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        base_estimator=ml_pipe._pipeline_params['base_estimator'],
        estimator_params=estimator_params,
        base_estimator_params=base_estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:24:14,963] A new study created in memory with name: model_study
[I 2025-04-15 20:24:16,344] Trial 0 finished with value: 0.8644623227823021 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.8644623227823021.
[I 2025-04-15 20:24:22,959] Trial 1 finished with value: 0.8765088953337681 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.8765088953337681.
[I 2025-04-15 20:24:24,682] Trial 2 finished with value: 0.871533285109738 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 1 with value: 0.8765088953337681.
[I 2025-04-15 20:24:26,218] Trial 3 finished with value: 0.8540069146858542 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 1 with value: 0.8765088953337681.
[I 2025-04-15 20:24:32,705] Trial 4 finished with value: 0.890334507678708 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:34,062] Trial 5 finished with value: 0.8731064230531962 and parameters: {'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': None, 'n_estimators': 166, 'learning_rate': 0.016850517723339092}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:36,520] Trial 6 finished with value: 0.8354162679809874 and parameters: {'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 6, 'class_weight': None, 'n_estimators': 544, 'learning_rate': 0.02260828676373495}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:39,828] Trial 7 finished with value: 0.8667060712807368 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 16, 'class_weight': None, 'n_estimators': 618, 'learning_rate': 0.19212959255386391}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:41,574] Trial 8 finished with value: 0.8553294766505836 and parameters: {'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'class_weight': 'balanced', 'n_estimators': 308, 'learning_rate': 0.11294923622078903}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:42,524] Trial 9 finished with value: 0.8866799412768748 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 120, 'learning_rate': 0.27838036931305016}. Best is trial 4 with value: 0.890334507678708.
[I 2025-04-15 20:24:49,115] Trial 10 finished with value: 0.9008335678385359 and parameters: {'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 20, 'class_weight': None, 'n_estimators': 985, 'learning_rate': 0.06549696903275597}. Best is trial 10 with value: 0.9008335678385359.
[I 2025-04-15 20:24:55,817] Trial 11 finished with value: 0.8909816608890371 and parameters: {'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 19, 'class_weight': None, 'n_estimators': 997, 'learning_rate': 0.07102087637064715}. Best is trial 10 with value: 0.9008335678385359.
[I 2025-04-15 20:25:02,462] Trial 12 finished with value: 0.8900272001374155 and parameters: {'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 20, 'class_weight': None, 'n_estimators': 996, 'learning_rate': 0.06547170860814318}. Best is trial 10 with value: 0.9008335678385359.
[I 2025-04-15 20:25:07,566] Trial 13 finished with value: 0.8935298551179028 and parameters: {'max_depth': 7, 'min_samples_split': 12, 'min_samples_leaf': 20, 'class_weight': None, 'n_estimators': 777, 'learning_rate': 0.06220954568267263}. Best is trial 10 with value: 0.9008335678385359.
[I 2025-04-15 20:25:12,604] Trial 14 finished with value: 0.8857672442789727 and parameters: {'max_depth': 10, 'min_samples_split': 14, 'min_samples_leaf': 18, 'class_weight': None, 'n_estimators': 759, 'learning_rate': 0.01059931888758693}. Best is trial 10 with value: 0.9008335678385359.

best_params for main estimator

{'n_estimators': 985, 'learning_rate': 0.06549696903275597}

best_params for base estimator

{'max_depth': 7,
 'min_samples_split': 2,
 'min_samples_leaf': 20,
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                             0
target                                                               splashing
model                             AdaBoostClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                                 0.802991
holdout_test_accuracy_balanced                                        0.791667
holdout_test_roc_auc                                                  0.881173
holdout_test_f1                                                       0.871287
holdout_test_accuracy                                                 0.826667
cv_test_f1_macro_median                                               0.898584
cv_test_accuracy_balanced_median                                      0.903251
cv_test_roc_auc_median                                                0.948916
cv_test_f1_median                                                     0.925373
cv_test_accuracy_median                                                0.90566
cv_test_precision_class_0_median                                          0.85
cv_test_recall_class_0_median                                         0.894737
cv_test_f1_class_0_median                                             0.871795

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smote_opt-model

In [11]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}
base_estimator = DecisionTreeClassifier
base_estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None
base_estimator_params_list = [
    'max_depth',
    'min_samples_split',
    'min_samples_leaf',
    'class_weight'
]

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    base_estimator=base_estimator,
    base_estimator_params=base_estimator_params,
    params_to_process=params_to_process,
    base_estimator_params_list=base_estimator_params_list,
    objective=adaboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:25:22,994] A new study created in memory with name: model_study
[I 2025-04-15 20:25:24,314] Trial 0 finished with value: 0.8408603407295698 and parameters: {'max_depth': 4, 'min_samples_split': 20, 'min_samples_leaf': 15, 'class_weight': None, 'n_estimators': 198, 'learning_rate': 0.0013927723945289009}. Best is trial 0 with value: 0.8408603407295698.
[I 2025-04-15 20:25:31,194] Trial 1 finished with value: 0.8554033035197184 and parameters: {'max_depth': 9, 'min_samples_split': 13, 'min_samples_leaf': 15, 'class_weight': 'balanced', 'n_estimators': 841, 'learning_rate': 0.0033572967053517922}. Best is trial 1 with value: 0.8554033035197184.
[I 2025-04-15 20:25:32,935] Trial 2 finished with value: 0.8436237087550891 and parameters: {'max_depth': 2, 'min_samples_split': 5, 'min_samples_leaf': 7, 'class_weight': None, 'n_estimators': 326, 'learning_rate': 0.032781876533976156}. Best is trial 1 with value: 0.8554033035197184.
[I 2025-04-15 20:25:34,383] Trial 3 finished with value: 0.8617103411997574 and parameters: {'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 239, 'learning_rate': 0.018785426399210624}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:41,095] Trial 4 finished with value: 0.851999154782469 and parameters: {'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 13, 'class_weight': None, 'n_estimators': 952, 'learning_rate': 0.24659691172104828}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:42,494] Trial 5 finished with value: 0.8022994232312809 and parameters: {'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'class_weight': None, 'n_estimators': 166, 'learning_rate': 0.016850517723339092}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:44,929] Trial 6 finished with value: 0.8372103684542174 and parameters: {'max_depth': 1, 'min_samples_split': 19, 'min_samples_leaf': 6, 'class_weight': None, 'n_estimators': 544, 'learning_rate': 0.02260828676373495}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:48,031] Trial 7 finished with value: 0.8407086340404771 and parameters: {'max_depth': 2, 'min_samples_split': 20, 'min_samples_leaf': 16, 'class_weight': None, 'n_estimators': 618, 'learning_rate': 0.19212959255386391}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:49,681] Trial 8 finished with value: 0.8167311977056652 and parameters: {'max_depth': 1, 'min_samples_split': 5, 'min_samples_leaf': 1, 'class_weight': 'balanced', 'n_estimators': 308, 'learning_rate': 0.11294923622078903}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:50,618] Trial 9 finished with value: 0.8261274535022363 and parameters: {'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 11, 'class_weight': 'balanced', 'n_estimators': 120, 'learning_rate': 0.27838036931305016}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:25:53,731] Trial 10 finished with value: 0.8400341918043329 and parameters: {'max_depth': 6, 'min_samples_split': 12, 'min_samples_leaf': 20, 'class_weight': 'balanced', 'n_estimators': 404, 'learning_rate': 0.007108886859512743}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:26:00,517] Trial 11 finished with value: 0.8560396284071123 and parameters: {'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 8, 'class_weight': 'balanced', 'n_estimators': 783, 'learning_rate': 0.0022369518530097115}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:26:06,598] Trial 12 finished with value: 0.837494563654781 and parameters: {'max_depth': 10, 'min_samples_split': 16, 'min_samples_leaf': 7, 'class_weight': 'balanced', 'n_estimators': 722, 'learning_rate': 0.0010476871191388998}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:26:12,687] Trial 13 finished with value: 0.8245563902563305 and parameters: {'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 9, 'class_weight': 'balanced', 'n_estimators': 720, 'learning_rate': 0.007505939949895844}. Best is trial 3 with value: 0.8617103411997574.
[I 2025-04-15 20:26:16,173] Trial 14 finished with value: 0.8207067420072713 and parameters: {'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 4, 'class_weight': 'balanced', 'n_estimators': 462, 'learning_rate': 0.044962275651963673}. Best is trial 3 with value: 0.8617103411997574.

best_params for main estimator

{'n_estimators': 239, 'learning_rate': 0.018785426399210624}

best_params for base estimator

{'max_depth': 2,
 'min_samples_split': 7,
 'min_samples_leaf': 8,
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.891551
holdout_test_accuracy_balanced                                             0.936364
holdout_test_roc_auc                                                       0.963636
holdout_test_f1                                                            0.851064
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.881326
cv_test_accuracy_balanced_median                                           0.897436
cv_test_roc_auc_median                                                     0.958974
cv_test_f1_median                                                          0.827586
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.969697
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.933333

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smote_opt-model

# Random Forest

In [12]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def rf_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "max_depth": trial.suggest_int("max_depth", 2, 20),
        "min_samples_split": trial.suggest_int("min_samples_split", 2, 20),
        "min_samples_leaf": trial.suggest_int('min_samples_leaf', 1, 20),
        "max_features": trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),
        "bootstrap": trial.suggest_categorical('bootstrap', [True, False]),
        "criterion": trial.suggest_categorical('criterion', ['gini', 'entropy']),
        "class_weight": trial.suggest_categorical('class_weight', [None, 'balanced'])
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:26:18,506] A new study created in memory with name: model_study
[I 2025-04-15 20:26:20,108] Trial 0 finished with value: 0.8354563185744841 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8354563185744841.
[I 2025-04-15 20:26:21,192] Trial 1 finished with value: 0.863569201181926 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 1 with value: 0.863569201181926.
[I 2025-04-15 20:26:22,148] Trial 2 finished with value: 0.8702590351921765 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:23,694] Trial 3 finished with value: 0.8475999958002619 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:26,871] Trial 4 finished with value: 0.8549271272351875 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:28,824] Trial 5 finished with value: 0.8464220779189725 and parameters: {'n_estimators': 566, 'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:30,196] Trial 6 finished with value: 0.8641461066969507 and parameters: {'n_estimators': 390, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:32,924] Trial 7 finished with value: 0.8627147521066528 and parameters: {'n_estimators': 728, 'max_depth': 16, 'min_samples_split': 12, 'min_samples_leaf': 16, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:37,333] Trial 8 finished with value: 0.8359697005369069 and parameters: {'n_estimators': 913, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': None, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:38,213] Trial 9 finished with value: 0.8561061748563332 and parameters: {'n_estimators': 227, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8702590351921765.
[I 2025-04-15 20:26:38,641] Trial 10 finished with value: 0.8722246151170435 and parameters: {'n_estimators': 72, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.8722246151170435.
[I 2025-04-15 20:26:39,189] Trial 11 finished with value: 0.864659520113525 and parameters: {'n_estimators': 86, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.8722246151170435.
[I 2025-04-15 20:26:39,575] Trial 12 finished with value: 0.8680348536965578 and parameters: {'n_estimators': 61, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.8722246151170435.
[I 2025-04-15 20:26:40,732] Trial 13 finished with value: 0.8579038450060769 and parameters: {'n_estimators': 223, 'max_depth': 14, 'min_samples_split': 20, 'min_samples_leaf': 4, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.8722246151170435.
[I 2025-04-15 20:26:41,642] Trial 14 finished with value: 0.8691371498958828 and parameters: {'n_estimators': 178, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 10, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 10 with value: 0.8722246151170435.

best_params

{'n_estimators': 72,
 'max_depth': 11,
 'min_samples_split': 2,
 'min_samples_leaf': 7,
 'max_features': None,
 'bootstrap': True,
 'criterion': 'gini',
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                 0
target                                                                   splashing
model                             RandomForestClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                                     0.829027
holdout_test_accuracy_balanced                                            0.834491
holdout_test_roc_auc                                                       0.89892
holdout_test_f1                                                            0.87234
holdout_test_accuracy                                                         0.84
cv_test_f1_macro_median                                                   0.835913
cv_test_accuracy_balanced_median                                          0.856037
cv_test_roc_auc_median                                                    0.947619
cv_test_f1_median                                                         0.882353
cv_test_accuracy_median                                                   0.849057
cv_test_precision_class_0_median                                          0.789474
cv_test_recall_class_0_median                                             0.842105
cv_test_f1_class_0_median                                                      0.8

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smote_opt-model

In [13]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=rf_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:26:42,581] A new study created in memory with name: model_study
[I 2025-04-15 20:26:44,266] Trial 0 finished with value: 0.8246542150819938 and parameters: {'n_estimators': 406, 'max_depth': 20, 'min_samples_split': 15, 'min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 0 with value: 0.8246542150819938.
[I 2025-04-15 20:26:45,349] Trial 1 finished with value: 0.8254165514795991 and parameters: {'n_estimators': 251, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt', 'bootstrap': True, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8254165514795991.
[I 2025-04-15 20:26:46,407] Trial 2 finished with value: 0.8294019176118625 and parameters: {'n_estimators': 239, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8294019176118625.
[I 2025-04-15 20:26:48,063] Trial 3 finished with value: 0.8366780071117488 and parameters: {'n_estimators': 468, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:26:51,457] Trial 4 finished with value: 0.823210354467381 and parameters: {'n_estimators': 943, 'max_depth': 19, 'min_samples_split': 13, 'min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:26:53,491] Trial 5 finished with value: 0.8291374672014913 and parameters: {'n_estimators': 566, 'max_depth': 4, 'min_samples_split': 17, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:26:54,906] Trial 6 finished with value: 0.8239541080776728 and parameters: {'n_estimators': 390, 'max_depth': 4, 'min_samples_split': 18, 'min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:26:57,731] Trial 7 finished with value: 0.8275416191369914 and parameters: {'n_estimators': 728, 'max_depth': 16, 'min_samples_split': 12, 'min_samples_leaf': 16, 'max_features': 'log2', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:27:02,605] Trial 8 finished with value: 0.7914566632659792 and parameters: {'n_estimators': 913, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 16, 'max_features': None, 'bootstrap': False, 'criterion': 'gini', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:27:03,516] Trial 9 finished with value: 0.823210354467381 and parameters: {'n_estimators': 227, 'max_depth': 18, 'min_samples_split': 12, 'min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'entropy', 'class_weight': 'balanced'}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:27:06,757] Trial 10 finished with value: 0.8181119824980182 and parameters: {'n_estimators': 618, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 3 with value: 0.8366780071117488.
[I 2025-04-15 20:27:07,167] Trial 11 finished with value: 0.8494276927763327 and parameters: {'n_estimators': 85, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 11 with value: 0.8494276927763327.
[I 2025-04-15 20:27:07,520] Trial 12 finished with value: 0.8324363527186662 and parameters: {'n_estimators': 73, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 11 with value: 0.8494276927763327.
[I 2025-04-15 20:27:07,876] Trial 13 finished with value: 0.828592429523982 and parameters: {'n_estimators': 73, 'max_depth': 13, 'min_samples_split': 7, 'min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': False, 'criterion': 'gini', 'class_weight': 'balanced'}. Best is trial 11 with value: 0.8494276927763327.
[I 2025-04-15 20:27:11,605] Trial 14 finished with value: 0.8228776396675104 and parameters: {'n_estimators': 722, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': None, 'bootstrap': True, 'criterion': 'gini', 'class_weight': None}. Best is trial 11 with value: 0.8494276927763327.

best_params

{'n_estimators': 85,
 'max_depth': 13,
 'min_samples_split': 7,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'bootstrap': False,
 'criterion': 'gini',
 'class_weight': 'balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smote_...
holdout_test_f1_macro                                                      0.888889
holdout_test_accuracy_balanced                                             0.920455
holdout_test_roc_auc                                                       0.971818
holdout_test_f1                                                            0.844444
holdout_test_accuracy                                                      0.906667
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.949634
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.936709

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smote_opt-model

# LightGBM

In [14]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
# params_to_process = ['gamma']
params_to_process = None

def lgbm_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        # "max_depth": trial.suggest_int("max_depth", 1, 10),
        "num_leaves": trial.suggest_int("num_leaves", 4, 512), # more important than max_depth
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "min_split_gain": trial.suggest_float("gamma", 0., 5.), # gamma from XGBoost
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0), # colsample_bytree from XGBoost
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "boosting_type": trial.suggest_categorical("boosting_type", ["gbdt", "dart"]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 20:27:12,419] A new study created in memory with name: model_study
[I 2025-04-15 20:27:17,054] Trial 0 finished with value: 0.8590852129479377 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:19,332] Trial 1 finished with value: 0.7915149965991307 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:24,210] Trial 2 finished with value: 0.8517509646525545 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:24,437] Trial 3 finished with value: 0.7545973205629138 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:25,907] Trial 4 finished with value: 0.8225523777288688 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:28,800] Trial 5 finished with value: 0.8125037629757621 and parameters: {'n_estimators': 784, 'learning_rate': 0.0031062960067335336, 'num_leaves': 6, 'min_child_samples': 83, 'min_child_weight': 15, 'gamma': 3.6450358402049368, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 0.02715581955282941, 'reg_lambda': 0.0029072088906598446, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:30,155] Trial 6 finished with value: 0.7553112550701134 and parameters: {'n_estimators': 345, 'learning_rate': 0.006390259853593126, 'num_leaves': 375, 'min_child_samples': 66, 'min_child_weight': 18, 'gamma': 2.3610746258097466, 'subsample': 0.5597971229691509, 'colsample_bytree': 0.8566223936114975, 'reg_alpha': 1.1044350847124695, 'reg_lambda': 0.17583640270008521, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:30,557] Trial 7 finished with value: 0.7558345599632054 and parameters: {'n_estimators': 74, 'learning_rate': 0.0018503766823590125, 'num_leaves': 19, 'min_child_samples': 66, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:31,863] Trial 8 finished with value: 0.7858060840724805 and parameters: {'n_estimators': 934, 'learning_rate': 0.1004181390102536, 'num_leaves': 326, 'min_child_samples': 88, 'min_child_weight': 17, 'gamma': 0.9328502944301792, 'subsample': 0.9462794992449889, 'colsample_bytree': 0.7696711209578253, 'reg_alpha': 1.6973078532467012, 'reg_lambda': 3.840300419098857, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:43,511] Trial 9 finished with value: 0.8066418879847209 and parameters: {'n_estimators': 827, 'learning_rate': 0.13556076855136892, 'num_leaves': 7, 'min_child_samples': 54, 'min_child_weight': 9, 'gamma': 1.1105390523536514, 'subsample': 0.5599326836668415, 'colsample_bytree': 0.668807585701814, 'reg_alpha': 5.910698619088545, 'reg_lambda': 0.019625093208439862, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:27:55,434] Trial 10 finished with value: 0.8390159085343144 and parameters: {'n_estimators': 459, 'learning_rate': 0.024229331857231067, 'num_leaves': 497, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.19362599980591533, 'subsample': 0.6806559982209047, 'colsample_bytree': 0.9880699499289975, 'reg_alpha': 0.002442728047335305, 'reg_lambda': 9.32074575706793, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:28:06,733] Trial 11 finished with value: 0.8460318891435632 and parameters: {'n_estimators': 613, 'learning_rate': 0.024608798343624772, 'num_leaves': 413, 'min_child_samples': 28, 'min_child_weight': 1, 'gamma': 4.990655590599451, 'subsample': 0.6851652267716883, 'colsample_bytree': 0.9598575621732366, 'reg_alpha': 0.2615464863334877, 'reg_lambda': 0.001125553859273183, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:28:08,959] Trial 12 finished with value: 0.8553896417005389 and parameters: {'n_estimators': 563, 'learning_rate': 0.010356231998349546, 'num_leaves': 259, 'min_child_samples': 26, 'min_child_weight': 4, 'gamma': 4.741199884881518, 'subsample': 0.5138482364469852, 'colsample_bytree': 0.884414920567027, 'reg_alpha': 0.21523287945934125, 'reg_lambda': 0.009251661446922315, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:28:14,328] Trial 13 finished with value: 0.8461192829404407 and parameters: {'n_estimators': 411, 'learning_rate': 0.07690934849890223, 'num_leaves': 239, 'min_child_samples': 40, 'min_child_weight': 4, 'gamma': 3.815954555522642, 'subsample': 0.5185580791449883, 'colsample_bytree': 0.8147701894425597, 'reg_alpha': 0.2408617379264137, 'reg_lambda': 0.03465743419765041, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8590852129479377.
[I 2025-04-15 20:28:16,382] Trial 14 finished with value: 0.7796573243171059 and parameters: {'n_estimators': 576, 'learning_rate': 0.00882729463162712, 'num_leaves': 224, 'min_child_samples': 99, 'min_child_weight': 13, 'gamma': 0.22300679446913618, 'subsample': 0.6324680265592507, 'colsample_bytree': 0.9097657125358328, 'reg_alpha': 0.19209905921187967, 'reg_lambda': 0.49327279404801977, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8590852129479377.

best_params

{'n_estimators': 406,
 'learning_rate': 0.22648248189516848,
 'num_leaves': 376,
 'min_child_samples': 62,
 'min_child_weight': 4,
 'gamma': 0.7799726016810132,
 'subsample': 0.5290418060840998,
 'colsample_bytree': 0.9330880728874675,
 'reg_alpha': 0.2537815508265665,
 'reg_lambda': 0.679657809075816,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                         0
target                                                           splashing
model                             LGBMClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                                 0.88
holdout_test_accuracy_balanced                                    0.868056
holdout_test_roc_auc                                              0.925154
holdout_test_f1                                                       0.92
holdout_test_accuracy                                             0.893333
cv_test_f1_macro_median                                           0.839394
cv_test_accuracy_balanced_median                                  0.847523
cv_test_roc_auc_median                                            0.948916
cv_test_f1_median                                                 0.882353
cv_test_accuracy_median                                           0.849057
cv_test_precision_class_0_median                                  0.761905
cv_test_recall_class_0_median                                     0.842105
cv_test_f1_class_0_median                                              0.8

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smote_opt-model

In [15]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
    'deterministic':True,
    'force_col_wise':True,
    'njobs': 1,
}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=lgbm_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 20:28:23,730] A new study created in memory with name: model_study
[I 2025-04-15 20:28:28,533] Trial 0 finished with value: 0.8459725380293233 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'num_leaves': 376, 'min_child_samples': 62, 'min_child_weight': 4, 'gamma': 0.7799726016810132, 'subsample': 0.5290418060840998, 'colsample_bytree': 0.9330880728874675, 'reg_alpha': 0.2537815508265665, 'reg_lambda': 0.679657809075816, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:31,434] Trial 1 finished with value: 0.7957123980199758 and parameters: {'n_estimators': 222, 'learning_rate': 0.002846526357761094, 'num_leaves': 158, 'min_child_samples': 55, 'min_child_weight': 9, 'gamma': 1.4561457009902097, 'subsample': 0.8059264473611898, 'colsample_bytree': 0.569746930326021, 'reg_alpha': 0.01474275315991467, 'reg_lambda': 0.029204338471814112, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:36,223] Trial 2 finished with value: 0.8162912005726177 and parameters: {'n_estimators': 613, 'learning_rate': 0.0013033567475147442, 'num_leaves': 313, 'min_child_samples': 21, 'min_child_weight': 2, 'gamma': 4.7444276862666666, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306, 'reg_alpha': 0.01653693718282442, 'reg_lambda': 0.002458603276328005, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:36,463] Trial 3 finished with value: 0.782972618588408 and parameters: {'n_estimators': 82, 'learning_rate': 0.1788532743297921, 'num_leaves': 135, 'min_child_samples': 68, 'min_child_weight': 7, 'gamma': 2.600340105889054, 'subsample': 0.7733551396716398, 'colsample_bytree': 0.5924272277627636, 'reg_alpha': 7.556810141274429, 'reg_lambda': 1.2604664585649468, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:38,403] Trial 4 finished with value: 0.8043685186871095 and parameters: {'n_estimators': 134, 'learning_rate': 0.0030582523213789677, 'num_leaves': 27, 'min_child_samples': 36, 'min_child_weight': 8, 'gamma': 1.3567451588694794, 'subsample': 0.9143687545759647, 'colsample_bytree': 0.6783766633467947, 'reg_alpha': 0.013296521457299506, 'reg_lambda': 0.14817820606039092, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:42,796] Trial 5 finished with value: 0.8244388773289658 and parameters: {'n_estimators': 784, 'learning_rate': 0.0031062960067335336, 'num_leaves': 6, 'min_child_samples': 83, 'min_child_weight': 15, 'gamma': 3.6450358402049368, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.5370223258670452, 'reg_alpha': 0.02715581955282941, 'reg_lambda': 0.0029072088906598446, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:45,234] Trial 6 finished with value: 0.7864657280062116 and parameters: {'n_estimators': 345, 'learning_rate': 0.006390259853593126, 'num_leaves': 375, 'min_child_samples': 66, 'min_child_weight': 18, 'gamma': 2.3610746258097466, 'subsample': 0.5597971229691509, 'colsample_bytree': 0.8566223936114975, 'reg_alpha': 1.1044350847124695, 'reg_lambda': 0.17583640270008521, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:45,876] Trial 7 finished with value: 0.7968677677643109 and parameters: {'n_estimators': 74, 'learning_rate': 0.0018503766823590125, 'num_leaves': 19, 'min_child_samples': 66, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'boosting_type': 'gbdt', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:28:47,791] Trial 8 finished with value: 0.8025279991708442 and parameters: {'n_estimators': 934, 'learning_rate': 0.1004181390102536, 'num_leaves': 326, 'min_child_samples': 88, 'min_child_weight': 17, 'gamma': 0.9328502944301792, 'subsample': 0.9462794992449889, 'colsample_bytree': 0.7696711209578253, 'reg_alpha': 1.6973078532467012, 'reg_lambda': 3.840300419098857, 'boosting_type': 'gbdt', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:29:05,404] Trial 9 finished with value: 0.8102708152697782 and parameters: {'n_estimators': 827, 'learning_rate': 0.13556076855136892, 'num_leaves': 7, 'min_child_samples': 54, 'min_child_weight': 9, 'gamma': 1.1105390523536514, 'subsample': 0.5599326836668415, 'colsample_bytree': 0.668807585701814, 'reg_alpha': 5.910698619088545, 'reg_lambda': 0.019625093208439862, 'boosting_type': 'dart', 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:29:20,131] Trial 10 finished with value: 0.8306143112258783 and parameters: {'n_estimators': 459, 'learning_rate': 0.024229331857231067, 'num_leaves': 497, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.19362599980591533, 'subsample': 0.6806559982209047, 'colsample_bytree': 0.9880699499289975, 'reg_alpha': 0.002442728047335305, 'reg_lambda': 9.32074575706793, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:29:37,345] Trial 11 finished with value: 0.8259532942767256 and parameters: {'n_estimators': 470, 'learning_rate': 0.028590636776905248, 'num_leaves': 508, 'min_child_samples': 6, 'min_child_weight': 1, 'gamma': 0.023282959757244676, 'subsample': 0.635785829160606, 'colsample_bytree': 0.9855358228725425, 'reg_alpha': 0.002451549269448794, 'reg_lambda': 9.809283812582127, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:29:50,017] Trial 12 finished with value: 0.8453912863291956 and parameters: {'n_estimators': 515, 'learning_rate': 0.0411489141676439, 'num_leaves': 506, 'min_child_samples': 37, 'min_child_weight': 4, 'gamma': 0.015731367398853613, 'subsample': 0.6688535751258982, 'colsample_bytree': 0.9924858415781249, 'reg_alpha': 0.23079754987887785, 'reg_lambda': 1.031097813941783, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 0 with value: 0.8459725380293233.
[I 2025-04-15 20:30:04,676] Trial 13 finished with value: 0.8546327257463864 and parameters: {'n_estimators': 601, 'learning_rate': 0.059264825631768776, 'num_leaves': 428, 'min_child_samples': 34, 'min_child_weight': 4, 'gamma': 0.41288079901745023, 'subsample': 0.5128708720920837, 'colsample_bytree': 0.8949828442656665, 'reg_alpha': 0.25527610124679395, 'reg_lambda': 0.6100934206581569, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 13 with value: 0.8546327257463864.
[I 2025-04-15 20:30:18,481] Trial 14 finished with value: 0.833576803493291 and parameters: {'n_estimators': 650, 'learning_rate': 0.06484407171565494, 'num_leaves': 412, 'min_child_samples': 36, 'min_child_weight': 13, 'gamma': 1.9554712350507772, 'subsample': 0.5023700598265446, 'colsample_bytree': 0.85693279380428, 'reg_alpha': 0.19209905921187967, 'reg_lambda': 0.36717604911374263, 'boosting_type': 'dart', 'class_weight': None}. Best is trial 13 with value: 0.8546327257463864.

best_params

{'n_estimators': 601,
 'learning_rate': 0.059264825631768776,
 'num_leaves': 428,
 'min_child_samples': 34,
 'min_child_weight': 4,
 'gamma': 0.41288079901745023,
 'subsample': 0.5128708720920837,
 'colsample_bytree': 0.8949828442656665,
 'reg_alpha': 0.25527610124679395,
 'reg_lambda': 0.6100934206581569,
 'boosting_type': 'dart',
 'class_weight': None}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                0
target                                                           no_fragmentation
model                             LGBMClassifier_no_fragmentation_smote_opt-model
holdout_test_f1_macro                                                    0.857143
holdout_test_accuracy_balanced                                           0.886364
holdout_test_roc_auc                                                         0.97
holdout_test_f1                                                               0.8
holdout_test_accuracy                                                        0.88
cv_test_f1_macro_median                                                  0.898077
cv_test_accuracy_balanced_median                                         0.900183
cv_test_roc_auc_median                                                    0.97094
cv_test_f1_median                                                        0.846154
cv_test_accuracy_median                                                  0.924528
cv_test_precision_class_0_median                                         0.948718
cv_test_recall_class_0_median                                            0.923077
cv_test_f1_class_0_median                                                0.947368

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smote_opt-model