# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

from pytorch_tabular.models import CategoryEmbeddingModelConfig, TabNetModelConfig

import optuna

from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    PytorchTabularEstimator,
    deep_update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

# from pytorch_lightning.loggers import MLFlowLogger
from pytorch_lightning.loggers import TensorBoardLogger

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [4]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1

# Settings

In [4]:
model_postfix = 'opt-model'

scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 300 # make 300

save_model_and_metrics = True
metrics_file = "metrics_modelling4_6-neural_networks.xlsx"

## Optimization function

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    add_smote:bool,
    is_smotenc:bool,
    smote_params:dict,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    opt_cv_folds:int=3,
    seed:int=seed,
):
    
    estimator_params = estimator_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
        cv_folds=opt_cv_folds,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    print('raw best_params')
    display(best_params)
    
    if params_to_process:
        for param in params_to_process:
            if param == 'log2_size':
                keys = [k for k in best_params.keys() if param in k]
                sorted_keys = sorted(keys, key=lambda k: int(k.split("_")[1]))
                layer_sizes = [
                    2**best_params.pop(key)
                    for key in sorted_keys
                ]
                best_params['layers'] = '-'.join(map(str, layer_sizes))
            elif param == 'num_layers':
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params.pop(key)
            else: # Other cases
                # Find one key in best_params which contains param
                key = next((k for k in best_params.keys() if param in k), None)
                if key:
                    best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    suggested_estimator_params = {
        "model_config_params": best_params
    }
    best_estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_estimator_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

## MultiLayer Perceptron (MLP)

In [6]:

def MLP_objective(
    trial:optuna.trial.Trial, 
    ml_pipe:MLPipeline,
):
    
    num_layers = trial.suggest_int('num_layers', 1, 3) # number of hidden layers
    layer_sizes = [
        2**trial.suggest_int(f'layer_{i}_log2_size', 0, 7)
        for i in range(num_layers)
    ]
    layers = '-'.join(map(str, layer_sizes))
    activation = trial.suggest_categorical('activation', ['ReLU', 'LeakyReLU', 'ELU'])
    dropout = trial.suggest_float('dropout', 0.0, 0.5)
    learning_rate = trial.suggest_float('learning_rate', 1e-5, 1e-1, log=True)
    use_batch_norm = trial.suggest_categorical('use_batch_norm', [True, False])
    batch_norm_continuous_input = trial.suggest_categorical('batch_norm_continuous_input', [True, False])
    
    suggested_estimator_params = {
        "model_config_params": {
            'layers': layers,
            'activation': activation,
            'dropout': dropout,
            'batch_norm_continuous_input': batch_norm_continuous_input,
            'use_batch_norm': use_batch_norm,
            'learning_rate': learning_rate,
        }
    }
    
    estimator_params = deep_update_estimator_params(
        ml_pipe=ml_pipe,
        suggested_params=suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

In [7]:
estimator = PytorchTabularEstimator
target = "splashing"

add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}

params_to_process = [
    'num_layers', # drop this param
    'log2_size', # process to get string of layer sizes
]

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # SET in optuna
    # "model_config_params": {
    #     'layers': '128-64-32',
    #     'activation': 'LeakyReLU',
    #     'dropout': 0.2,
    #     'batch_norm_continuous_input': True, # We already have normalized features    
    #     'use_batch_norm': False, # For hidden layers
    #     'learning_rate': 1e-3,
    # },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 300,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'gpu',
        'devices': 1,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=MLP_objective,
    n_trials=n_trials,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-27 01:00:33,843] A new study created in memory with name: model_study

2025-04-27 01:00:33,859 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:33,874 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:33,879 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:33,889 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:33,907 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:33,922 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:36,144 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:36,145 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:00:36,179 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:36,189 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:36,192 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:36,202 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:36,214 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:36,221 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:38,037 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:38,038 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:00:38,066 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:38,076 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:38,079 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:38,090 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:38,103 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:38,110 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:41,024 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:41,025 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:00:41,043] Trial 0 finished with value: 0.8527356568931058 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'activation': 'ReLU', 'dropout': 0.02904180608409973, 'learning_rate': 0.029154431891537533, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8527356568931058.

2025-04-27 01:00:41,055 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:41,065 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:41,067 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:41,077 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:41,090 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:41,098 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:42,006 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:42,007 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:00:42,035 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:42,044 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:42,046 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:42,056 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:42,069 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:42,075 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:57,606 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:57,607 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:00:57,635 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:57,644 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:57,647 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:57,656 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:57,669 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:57,676 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:00:58,424 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:00:58,426 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:00:58,445] Trial 1 finished with value: 0.42922332979982064 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 1, 'layer_2_log2_size': 1, 'activation': 'LeakyReLU', 'dropout': 0.14561457009902096, 'learning_rate': 0.0028016351587162596, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8527356568931058.

2025-04-27 01:00:58,457 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:00:58,466 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:00:58,468 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:00:58,478 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:00:58,493 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:00:58,500 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:00,500 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:00,501 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:00,532 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:00,541 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:00,543 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:00,554 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:00,568 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:00,575 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:04,341 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:04,342 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:04,371 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:04,380 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:04,383 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:04,395 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:04,408 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:04,414 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:06,472 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:06,473 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:01:06,493] Trial 2 finished with value: 0.7685154423526517 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 4, 'layer_2_log2_size': 4, 'activation': 'LeakyReLU', 'dropout': 0.03252579649263976, 'learning_rate': 0.06245139574743072, 'use_batch_norm': True, 'batch_norm_continuous_input': True}. Best is trial 0 with value: 0.8527356568931058.

raw best_params

{'num_layers': 2,
 'layer_0_log2_size': 7,
 'layer_1_log2_size': 5,
 'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False}

best_params

{'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False,
 'layers': '128-32'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

2025-04-27 01:01:06,550 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:06,560 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:06,563 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:06,574 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:06,586 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:06,593 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:09,352 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:09,353 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:09,400 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:09,409 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:09,412 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:09,423 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:09,436 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:09,442 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:14,024 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:14,025 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:14,074 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:14,083 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:14,086 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:14,096 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:14,108 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:14,115 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:15,680 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:15,681 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:15,728 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:15,737 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:15,740 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:15,750 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:15,762 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:15,770 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:18,657 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:18,658 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:18,705 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:18,714 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:18,716 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:18,725 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:18,739 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:18,746 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:21,720 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:21,721 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:21,769 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:21,779 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:21,781 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:21,791 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:21,805 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:21,811 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:24,557 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:24,558 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:24,607 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:24,616 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:24,619 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:24,629 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:24,642 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:24,649 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:27,737 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:27,738 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:27,796 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:27,806 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:27,809 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:27,821 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:27,838 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:27,846 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:30,309 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:30,310 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                 0
target                                                                   splashing
model                             CategoryEmbeddingModel_splashing_smote_opt-model
holdout_test_f1_macro                                                         0.85
holdout_test_accuracy_balanced                                             0.83912
holdout_test_roc_auc                                                       0.91358
holdout_test_f1                                                                0.9
holdout_test_accuracy                                                     0.866667
cv_test_f1_macro_median                                                   0.839394
cv_test_accuracy_balanced_median                                          0.847523
cv_test_roc_auc_median                                                    0.941176
cv_test_f1_median                                                         0.888889
cv_test_accuracy_median                                                   0.849057
cv_test_precision_class_0_median                                          0.857143
cv_test_recall_class_0_median                                             0.842105
cv_test_f1_class_0_median                                                      0.8

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_splashing_smote_opt-model

In [8]:
estimator = PytorchTabularEstimator
target = "no_fragmentation"

add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}

params_to_process = [
    'num_layers', # drop this param
    'log2_size', # process to get string of layer sizes
]

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    "model_config_params": {
        'activation': 'LeakyReLU',
        'dropout': 0.2,
        'batch_norm_continuous_input': True, # We have normalized features
        'learning_rate': 1e-3,
    },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 200,
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

estimator_params = {
    "model_class": CategoryEmbeddingModelConfig,
    # SET in optuna
    # "model_config_params": {
    #     'layers': '128-64-32',
    #     'activation': 'LeakyReLU',
    #     'dropout': 0.2,
    #     'batch_norm_continuous_input': True, # We already have normalized features    
    #     'use_batch_norm': False, # For hidden layers
    #     'learning_rate': 1e-3,
    # },
    # "data_config_params": {},
    "trainer_config_params": {
        'max_epochs': 300,
        'batch_size': 300, # let's condiser whole dataset
        'early_stopping': 'valid_loss',
        'early_stopping_patience': 10,
        'accelerator': 'gpu',
        'devices': 1,
    },
    "optimizer_config_params": {
        'optimizer': 'Adam',
        'lr_scheduler': 'ReduceLROnPlateau',
        'lr_scheduler_params': {
            'patience': 5,
            'factor': 0.5,
        },
    },
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=MLP_objective,
    n_trials=n_trials,
    add_smote=add_smote,
    is_smotenc=is_smotenc,
    smote_params=smote_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-27 01:01:30,670] A new study created in memory with name: model_study

2025-04-27 01:01:30,769 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:30,827 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:30,833 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:30,853 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:30,884 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:30,898 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:32,575 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:32,576 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:32,607 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:32,616 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:32,619 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:32,630 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:32,643 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:32,649 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:35,176 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:35,190 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:35,230 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:35,242 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:35,245 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:35,259 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:35,282 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:35,296 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:01:39,282 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:39,283 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:01:39,302] Trial 0 finished with value: 0.8622818039209864 and parameters: {'num_layers': 2, 'layer_0_log2_size': 7, 'layer_1_log2_size': 5, 'activation': 'ReLU', 'dropout': 0.02904180608409973, 'learning_rate': 0.029154431891537533, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8622818039209864.

2025-04-27 01:01:39,320 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:39,331 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:39,334 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:39,349 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:39,367 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:39,379 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

`Trainer.fit` stopped: `max_epochs=300` reached.

2025-04-27 01:01:59,678 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:01:59,679 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:01:59,715 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:01:59,726 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:01:59,729 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:01:59,760 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:01:59,793 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:01:59,800 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:13,805 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:13,806 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:13,840 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:13,850 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:13,853 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:13,870 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:13,893 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:13,922 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │     28 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │      6 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 34
Non-trainable params: 0
Total params: 34
Total estimated model params size (MB): 0
Modules in train mode: 17
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:27,053 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:27,054 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:02:27,082] Trial 1 finished with value: 0.8269088278867401 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 1, 'layer_2_log2_size': 1, 'activation': 'LeakyReLU', 'dropout': 0.14561457009902096, 'learning_rate': 0.0028016351587162596, 'use_batch_norm': False, 'batch_norm_continuous_input': False}. Best is trial 0 with value: 0.8622818039209864.

2025-04-27 01:02:27,106 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:27,121 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:27,125 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:27,138 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:27,153 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:27,164 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:31,555 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:31,556 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:31,590 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:31,602 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:31,604 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:31,617 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:31,632 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:31,639 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:34,673 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:34,674 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:34,709 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:34,720 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:34,723 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:34,733 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:34,754 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:34,761 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │    386 │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │     14 │ train │
│ 2 │ head             │ LinearHead                │     34 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 434
Non-trainable params: 0
Total params: 434
Total estimated model params size (MB): 0
Modules in train mode: 25
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (1) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:37,047 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:37,048 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

[I 2025-04-27 01:02:37,068] Trial 2 finished with value: 0.8329835156784618 and parameters: {'num_layers': 3, 'layer_0_log2_size': 1, 'layer_1_log2_size': 4, 'layer_2_log2_size': 4, 'activation': 'LeakyReLU', 'dropout': 0.03252579649263976, 'learning_rate': 0.06245139574743072, 'use_batch_norm': True, 'batch_norm_continuous_input': True}. Best is trial 0 with value: 0.8622818039209864.

raw best_params

{'num_layers': 2,
 'layer_0_log2_size': 7,
 'layer_1_log2_size': 5,
 'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False}

best_params

{'activation': 'ReLU',
 'dropout': 0.02904180608409973,
 'learning_rate': 0.029154431891537533,
 'use_batch_norm': False,
 'batch_norm_continuous_input': False,
 'layers': '128-32'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

2025-04-27 01:02:37,163 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:37,177 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:37,179 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:37,192 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:37,210 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:37,218 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:40,078 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:40,079 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:40,141 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:40,150 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:40,153 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:40,165 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:40,182 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:40,191 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:41,852 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:41,853 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:41,910 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:41,919 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:41,923 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:41,934 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:41,950 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:41,960 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:44,321 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:44,322 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:44,377 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:44,387 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:44,390 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:44,430 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:44,455 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:44,466 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:46,106 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:46,107 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:46,165 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:46,174 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:46,178 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:46,190 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:46,211 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:46,218 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:51,402 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:51,403 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:51,458 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:51,469 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:51,472 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:51,485 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:51,499 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:51,509 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:53,181 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:53,182 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:53,239 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:53,254 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:53,258 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:53,280 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:53,321 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:53,327 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:56,939 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:56,940 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

2025-04-27 01:02:57,021 - {pytorch_tabular.tabular_model:146} - INFO - Experiment Tracking is turned off

Seed set to 42

2025-04-27 01:02:57,042 - {pytorch_tabular.tabular_model:548} - INFO - Preparing the DataLoaders

2025-04-27 01:02:57,045 - {pytorch_tabular.tabular_datamodule:522} - INFO - Setting up the datamodule for
classification task

2025-04-27 01:02:57,055 - {pytorch_tabular.tabular_model:599} - INFO - Preparing the Model: CategoryEmbeddingModel

2025-04-27 01:02:57,069 - {pytorch_tabular.tabular_model:342} - INFO - Preparing the Trainer

GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

2025-04-27 01:02:57,076 - {pytorch_tabular.tabular_model:678} - INFO - Training Started

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/vulf/Git/Hub/Drop_wall_impact/notebooks/saved_models exists and is not empty.

┏━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┓
┃   ┃ Name             ┃ Type                      ┃ Params ┃ Mode  ┃
┡━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━┩
│ 0 │ _backbone        │ CategoryEmbeddingBackbone │  5.2 K │ train │
│ 1 │ _embedding_layer │ Embedding1dLayer          │      0 │ train │
│ 2 │ head             │ LinearHead                │     66 │ train │
│ 3 │ loss             │ CrossEntropyLoss          │      0 │ train │
└───┴──────────────────┴───────────────────────────┴────────┴───────┘

Trainable params: 5.2 K
Non-trainable params: 0
Total params: 5.2 K
Total estimated model params size (MB): 0
Modules in train mode: 14
Modules in eval mode: 0

Output()

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/trainer/conn
ectors/data_connector.py:424: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider
increasing the value of the `num_workers` argument` to `num_workers=9` in the `DataLoader` to improve performance.

/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/pytorch_lightning/loops/fit_lo
op.py:298: The number of training batches (2) is smaller than the logging interval Trainer(log_every_n_steps=50).
Set a lower value for log_every_n_steps if you want to see logs for the training epoch.

2025-04-27 01:02:58,803 - {pytorch_tabular.tabular_model:689} - INFO - Training the model completed

2025-04-27 01:02:58,804 - {pytorch_tabular.tabular_model:1529} - INFO - Loading the best model

no summary in estimator class "PytorchTabularEstimator"

                                                                                  0
target                                                             no_fragmentation
model                             CategoryEmbeddingModel_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.860566
holdout_test_accuracy_balanced                                             0.902273
holdout_test_roc_auc                                                       0.958182
holdout_test_f1                                                            0.808511
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.870098
cv_test_accuracy_balanced_median                                           0.915385
cv_test_roc_auc_median                                                     0.969231
cv_test_f1_median                                                          0.823529
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.965517
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.933333

Model saved in ../results/models_modelling4/CategoryEmbeddingModel_no_fragmentation_smotenc_opt-model