Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = True
is_smotenc = True
smote_params = {
    'categorical_features': (
        'wettability',
        'inclination',
    ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 2500 # was checked with 1000 and 5000

save_model_and_metrics = True

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    seed:int=seed,
):
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}
params_to_process = ['penalty']

def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    
    # # NOTE: Does not work, since optuna requires static parameters ranges
    # solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # penalty_options = {
    #     'lbfgs': ['l2'],
    #     'liblinear': ['l1', 'l2'],
    #     'newton-cg': ['l2'],
    #     'newton-cholesky': ['l2'],
    #     'sag': ['l2'],
    #     'saga': ['l1', 'l2', 'elasticnet'],
    # }
    # penalty = trial.suggest_categorical('penalty', penalty_options[solver])
    # NOTE: warnings + inconvenient to create best model
    # solver_penalty_combinations = [
    #     ("liblinear", "l1"),
    #     ("liblinear", "l2"),
    #     ("saga", "l1"),
    #     ("saga", "l2"),
    #     ("saga", "elasticnet"),
    #     ("lbfgs", "l2"),
    #     ("newton-cg", "l2"),
    #     ("newton-cholesky", "l2"),
    #     ("sag", "l2"),
    # ]
    # solver, penalty = trial.suggest_categorical(
    #     'solver_penalty', solver_penalty_combinations
    # )
    
    solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # solver = trial.suggest_categorical('solver', ['lbfgs',])
    
    if solver == 'liblinear':
        penalty = trial.suggest_categorical('penalty_liblinear', ['l1', 'l2'])
    elif solver == 'saga':
        penalty = trial.suggest_categorical('penalty_saga', ['l1', 'l2', 'elasticnet'])
    else:
        penalty = trial.suggest_categorical('penalty_other', ['l2'])
    
    # If C is large, the penalty should be small
    C = trial.suggest_float('C', 1e-4, 1e3, log=True)
    
    l1_ratio = None
    if penalty == 'elasticnet':
        l1_ratio = trial.suggest_float('l1_ratio', 0., 1.)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "solver": solver,
        "penalty": penalty,
        "C": C,
        "l1_ratio": l1_ratio,
        "class_weight": class_weight,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 11:26:05,329] A new study created in memory with name: model_study
[I 2025-04-15 11:26:05,482] Trial 0 finished with value: 0.8080335848738224 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8080335848738224.
[I 2025-04-15 11:26:05,640] Trial 1 finished with value: 0.8161809420899051 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:05,785] Trial 2 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:05,934] Trial 3 finished with value: 0.8030685635144312 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,082] Trial 4 finished with value: 0.7956049307200141 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,234] Trial 5 finished with value: 0.7545886399274148 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,397] Trial 6 finished with value: 0.7956049307200141 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,549] Trial 7 finished with value: 0.7541302129979706 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,718] Trial 8 finished with value: 0.807131965776461 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:06,867] Trial 9 finished with value: 0.7344948796148068 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,032] Trial 10 finished with value: 0.7840121154699745 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.054522022569948085, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,197] Trial 11 finished with value: 0.8115108741561415 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.024262729145672, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,359] Trial 12 finished with value: 0.8112729925249947 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 2.3366017100986745, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,516] Trial 13 finished with value: 0.809755621049705 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.20187914978598492, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,676] Trial 14 finished with value: 0.7956049307200141 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 36.21278944421456, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,832] Trial 15 finished with value: 0.7956049307200141 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 689.5395183453928, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:07,990] Trial 16 finished with value: 0.7443572055189381 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0031666600942618474, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,143] Trial 17 finished with value: 0.8080335848738224 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.834497161176626, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,306] Trial 18 finished with value: 0.807131965776461 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 8.809523406698156, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,460] Trial 19 finished with value: 0.7344546994543757 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.001579164198027733, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,616] Trial 20 finished with value: 0.7970571657235513 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.08288429700474592, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,788] Trial 21 finished with value: 0.8080335848738224 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.2177122714284185, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:08,953] Trial 22 finished with value: 0.807131965776461 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 5.038897088553281, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,112] Trial 23 finished with value: 0.8124821841572762 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.686064035336115, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,276] Trial 24 finished with value: 0.7956049307200141 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 62.651656704699455, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,440] Trial 25 finished with value: 0.8086648801095574 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.7852095388872282, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,597] Trial 26 finished with value: 0.8161809420899051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4314535267538374, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,754] Trial 27 finished with value: 0.809755621049705 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.20943979848685879, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:09,907] Trial 28 finished with value: 0.7808773479067941 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.045142470276666805, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,065] Trial 29 finished with value: 0.8086648801095574 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.7166993698489783, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,220] Trial 30 finished with value: 0.7606572270437816 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.023409067734634727, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,378] Trial 31 finished with value: 0.807131965776461 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 3.6291739343129428, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,529] Trial 32 finished with value: 0.8124821841572762 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.569372008558274, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,678] Trial 33 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.31801975390227694, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,828] Trial 34 finished with value: 0.810219224433909 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.1814054390181931, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:10,987] Trial 35 finished with value: 0.8161809420899051 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.43543725059828586, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,136] Trial 36 finished with value: 0.8004796256165995 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.1007384604606347, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,295] Trial 37 finished with value: 0.7475085540385756 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.010951641268200394, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,442] Trial 38 finished with value: 0.8161809420899051 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.4596440123131963, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,585] Trial 39 finished with value: 0.7956049307200141 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 22.924058986468637, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,733] Trial 40 finished with value: 0.727953832495356 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.0006600494480521361, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:11,876] Trial 41 finished with value: 0.8129571769558716 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.38475883181156695, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,023] Trial 42 finished with value: 0.8070406879509238 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.12756530930390958, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,173] Trial 43 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.3420274836625704, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,323] Trial 44 finished with value: 0.663901122069728 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.03104843835236254, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,469] Trial 45 finished with value: 0.8039013415351984 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 1.4146397775251844, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,617] Trial 46 finished with value: 0.7904835475901875 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.07260864243580041, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,762] Trial 47 finished with value: 0.7475085540385756 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.010402994810435653, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:12,914] Trial 48 finished with value: 0.807131965776461 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.540112869604054, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,080] Trial 49 finished with value: 0.7995678711406539 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 19.082895922229394, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,244] Trial 50 finished with value: 0.8129571769558716 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.3409893601489712, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,390] Trial 51 finished with value: 0.8129571769558716 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.3880483806128748, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,537] Trial 52 finished with value: 0.8080335848738224 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.5860820357775993, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,679] Trial 53 finished with value: 0.8064737262346294 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.19560248664580387, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,826] Trial 54 finished with value: 0.8080335848738224 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 2.604858649528325, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:13,977] Trial 55 finished with value: 0.8048146127298782 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.9455376495909198, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,121] Trial 56 finished with value: 0.8161809420899051 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.4320711613758267, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,273] Trial 57 finished with value: 0.7840121154699745 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.048887581464452864, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,421] Trial 58 finished with value: 0.8100742744306304 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.15984232383733896, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,568] Trial 59 finished with value: 0.7951807355399455 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.612658366259897, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,727] Trial 60 finished with value: 0.8070406879509238 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.10404196572353586, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:14,871] Trial 61 finished with value: 0.8161809420899051 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.4153202631691209, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,016] Trial 62 finished with value: 0.809755621049705 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.2555942985850803, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,162] Trial 63 finished with value: 0.8080335848738224 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.0432234720346107, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,321] Trial 64 finished with value: 0.8080335848738224 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 2.79651691815593, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,471] Trial 65 finished with value: 0.8161809420899051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4859843394110168, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,620] Trial 66 finished with value: 0.8161809420899051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4861814872790588, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,768] Trial 67 finished with value: 0.7956049307200141 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 102.92461464660482, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:15,922] Trial 68 finished with value: 0.8080335848738224 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.6016254636187592, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,069] Trial 69 finished with value: 0.7904835475901875 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.07264228761842285, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,225] Trial 70 finished with value: 0.807131965776461 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.9365939777907615, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,375] Trial 71 finished with value: 0.8124821841572762 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.5950411980602689, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,523] Trial 72 finished with value: 0.8161809420899051 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4533584476789148, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,674] Trial 73 finished with value: 0.8048146127298782 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.9839182109740214, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,824] Trial 74 finished with value: 0.8136847498946528 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.15357757666987382, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:16,976] Trial 75 finished with value: 0.809755621049705 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.21488641676949016, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,125] Trial 76 finished with value: 0.8112729925249947 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 2.3345102917753286, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,276] Trial 77 finished with value: 0.8124821841572762 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.5804160477448838, 'class_weight': None}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,437] Trial 78 finished with value: 0.809755621049705 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.2672394234209044, 'l1_ratio': 0.019653954487053427, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,588] Trial 79 finished with value: 0.7677123196939494 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.03127092298419136, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,741] Trial 80 finished with value: 0.8048146127298782 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.8930954967925689, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.
[I 2025-04-15 11:26:17,890] Trial 81 finished with value: 0.8124821841572762 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.4979609344673838, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8161809420899051.

best_params

{'solver': 'lbfgs',
 'C': 0.47129737561107793,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                             0
target                                                               splashing
model                             LogisticRegression_splashing_smote_opt-model
holdout_test_f1_macro                                                 0.759479
holdout_test_accuracy_balanced                                        0.766204
holdout_test_roc_auc                                                  0.886574
holdout_test_f1                                                       0.817204
holdout_test_accuracy                                                 0.773333
cv_test_f1_macro_median                                               0.799242
cv_test_accuracy_balanced_median                                      0.816667
cv_test_roc_auc_median                                                0.868421
cv_test_f1_median                                                      0.84375
cv_test_accuracy_median                                               0.811321
cv_test_precision_class_0_median                                      0.681818
cv_test_recall_class_0_median                                         0.894737
cv_test_f1_class_0_median                                             0.755556

Model saved in ..\results\models_modelling4\LogisticRegression_splashing_smote_opt-model

In [7]:
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
    'max_iter': 1000,
}

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 11:33:12,355] A new study created in memory with name: model_study
[I 2025-04-15 11:33:12,481] Trial 0 finished with value: 0.802106586533207 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.802106586533207.
[I 2025-04-15 11:33:12,619] Trial 1 finished with value: 0.7922274233971268 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.802106586533207.
[I 2025-04-15 11:33:12,747] Trial 2 finished with value: 0.4233049487844008 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.802106586533207.
[I 2025-04-15 11:33:12,873] Trial 3 finished with value: 0.7953914760068441 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.802106586533207.
[I 2025-04-15 11:33:13,014] Trial 4 finished with value: 0.807747922754787 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 4 with value: 0.807747922754787.
[I 2025-04-15 11:33:13,149] Trial 5 finished with value: 0.7040669559778456 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 4 with value: 0.807747922754787.
[I 2025-04-15 11:33:13,450] Trial 6 finished with value: 0.807747922754787 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.807747922754787.
[I 2025-04-15 11:33:13,580] Trial 7 finished with value: 0.7183792652710382 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 4 with value: 0.807747922754787.
[I 2025-04-15 11:33:13,710] Trial 8 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:13,835] Trial 9 finished with value: 0.6893601787367194 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:13,968] Trial 10 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 12.739177323811454, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,098] Trial 11 finished with value: 0.8136753640448223 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 16.75612337400509, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,227] Trial 12 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 7.875267957724121, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,376] Trial 13 finished with value: 0.807747922754787 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 824.2209069195276, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,506] Trial 14 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 83.39155840103841, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,637] Trial 15 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 3.3753979070724456, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,767] Trial 16 finished with value: 0.7480765304193128 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.0777906083832051, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:14,925] Trial 17 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 28.107599205702194, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:15,126] Trial 18 finished with value: 0.8048043089915012 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 163.85390565627344, 'class_weight': 'balanced'}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:15,254] Trial 19 finished with value: 0.7953914760068441 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.006093541066907, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:15,379] Trial 20 finished with value: 0.6915379072269889 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.002584726071671304, 'class_weight': None}. Best is trial 8 with value: 0.813774649167046.
[I 2025-04-15 11:33:15,508] Trial 21 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.5706235157060515, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:15,637] Trial 22 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 2.917018720879541, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:15,766] Trial 23 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 8.240538975567002, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:15,898] Trial 24 finished with value: 0.7762175049836938 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.2612641937918274, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,033] Trial 25 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 12.382559364308138, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,177] Trial 26 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 156.15898037181802, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,305] Trial 27 finished with value: 0.7480765304193128 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.07751905701794538, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,439] Trial 28 finished with value: 0.8084525408982813 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 3.3446985269859013, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,563] Trial 29 finished with value: 0.802106586533207 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.2823837698074592, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,695] Trial 30 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 42.0659805954551, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,826] Trial 31 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 8.033256765670297, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:16,956] Trial 32 finished with value: 0.8117705650226316 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 5.892904686013198, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,087] Trial 33 finished with value: 0.7953914760068441 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.9647584189127217, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,229] Trial 34 finished with value: 0.8136753640448223 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 19.49814867397855, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,370] Trial 35 finished with value: 0.7922274233971268 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.4756940210848812, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,496] Trial 36 finished with value: 0.807747922754787 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 194.12786030392556, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,778] Trial 37 finished with value: 0.807747922754787 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 43.10090144105687, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:17,907] Trial 38 finished with value: 0.7666459739230586 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.17345231159148936, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,047] Trial 39 finished with value: 0.807747922754787 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 684.133125701928, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,180] Trial 40 finished with value: 0.8050794361704968 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 2.17243564745614, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,312] Trial 41 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.320931571984918, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,444] Trial 42 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 88.50392335082113, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,575] Trial 43 finished with value: 0.8136753640448223 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 16.81879143333394, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,707] Trial 44 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.179911310976262, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,832] Trial 45 finished with value: 0.8017312800431279 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.6227158784854954, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:18,994] Trial 46 finished with value: 0.8084525408982813 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 4.763122682144302, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,123] Trial 47 finished with value: 0.802106586533207 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.776115639661585, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,254] Trial 48 finished with value: 0.6893601787367194 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0004965037413489236, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,398] Trial 49 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 26.76011660900902, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,541] Trial 50 finished with value: 0.813774649167046 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 12.370771298725652, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,673] Trial 51 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 69.92132823190185, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,805] Trial 52 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.481994597138733, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:19,935] Trial 53 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.402598104010069, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,063] Trial 54 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 4.606953708179216, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,193] Trial 55 finished with value: 0.802106586533207 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 1.4373832065091945, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,325] Trial 56 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.544377532290275, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,458] Trial 57 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 28.697151084067247, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,586] Trial 58 finished with value: 0.7966655972705946 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.7238939887055758, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,718] Trial 59 finished with value: 0.8084525408982813 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 2.298258221177699, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,858] Trial 60 finished with value: 0.7791769878970937 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.27071938067091184, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:20,989] Trial 61 finished with value: 0.8117705650226316 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 5.025143180647941, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,119] Trial 62 finished with value: 0.8136753640448223 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 16.484857494837488, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,250] Trial 63 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 2.9676722219915703, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,381] Trial 64 finished with value: 0.813774649167046 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 7.488999359549287, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,518] Trial 65 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 112.55672915301908, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,663] Trial 66 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 43.900468856904276, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:21,789] Trial 67 finished with value: 0.807747922754787 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 10.347082369807824, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,021] Trial 68 finished with value: 0.8093440993752117 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 25.921140516793702, 'l1_ratio': 0.004736115997585499, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,149] Trial 69 finished with value: 0.7183317462634351 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.015346211012105346, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,280] Trial 70 finished with value: 0.807747922754787 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 244.68638026872065, 'class_weight': None}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,411] Trial 71 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 4.323342985446306, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,543] Trial 72 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.377807410431207, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,673] Trial 73 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.742757269953188, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,803] Trial 74 finished with value: 0.8084525408982813 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 2.934874777623604, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:22,934] Trial 75 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 7.160956790548117, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:23,066] Trial 76 finished with value: 0.8151436697504161 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.474791496316405, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:23,201] Trial 77 finished with value: 0.7988092453048312 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.1207219589507762, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:23,331] Trial 78 finished with value: 0.802106586533207 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 1.9770700098074647, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:23,462] Trial 79 finished with value: 0.8136753640448223 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 19.06405137851401, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.
[I 2025-04-15 11:33:23,593] Trial 80 finished with value: 0.8048043089915012 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 62.320486443872554, 'class_weight': 'balanced'}. Best is trial 21 with value: 0.8151436697504161.

best_params

{'solver': 'newton-cholesky',
 'C': 6.5706235157060515,
 'class_weight': 'balanced',
 'penalty': 'l2'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_opt-...
holdout_test_f1_macro                                                      0.802991
holdout_test_accuracy_balanced                                                 0.85
holdout_test_roc_auc                                                       0.950909
holdout_test_f1                                                            0.734694
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.864469
cv_test_roc_auc_median                                                     0.943223
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                            0.96875
cv_test_recall_class_0_median                                              0.820513
cv_test_f1_class_0_median                                                  0.888889

Model saved in ..\results\models_modelling4\LogisticRegression_no_fragmentation_smote_opt-model

# KNClassifier

In [8]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['penalty']
params_to_process = None


def knn_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    n_neighbors = trial.suggest_int("n_neighbors", 1, 50)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    p = trial.suggest_int("p", 1, 2)  # 1=manhattan, 2=euclidean
    # leaf_size - affects the speed of the tree construction and search
    # algorithm - affects the speed of the search, for small datasets it is okay to use auto
    
    suggested_estimator_params = {
        "n_neighbors": n_neighbors,
        "weights": weights,
        "p": p,
    }
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 11:39:33,575] A new study created in memory with name: model_study
[I 2025-04-15 11:39:33,832] Trial 0 finished with value: 0.7977895578771674 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7977895578771674.
[I 2025-04-15 11:39:34,062] Trial 1 finished with value: 0.8009871998340693 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8009871998340693.
[I 2025-04-15 11:39:34,298] Trial 2 finished with value: 0.7824376182535576 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.8009871998340693.
[I 2025-04-15 11:39:34,532] Trial 3 finished with value: 0.7635110652728538 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8009871998340693.
[I 2025-04-15 11:39:34,792] Trial 4 finished with value: 0.7825674250841211 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.8009871998340693.
[I 2025-04-15 11:39:34,989] Trial 5 finished with value: 0.8543923760490821 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8543923760490821.
[I 2025-04-15 11:39:35,267] Trial 6 finished with value: 0.7743139967881191 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8543923760490821.
[I 2025-04-15 11:39:35,444] Trial 7 finished with value: 0.8507664096571582 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8543923760490821.
[I 2025-04-15 11:39:35,613] Trial 8 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8799321891385213.
[I 2025-04-15 11:39:35,795] Trial 9 finished with value: 0.8491667120255134 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8799321891385213.
[I 2025-04-15 11:39:35,988] Trial 10 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:36,159] Trial 11 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:36,326] Trial 12 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:36,511] Trial 13 finished with value: 0.8576045007599552 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:36,690] Trial 14 finished with value: 0.8576045007599552 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:36,892] Trial 15 finished with value: 0.8467872288929409 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,059] Trial 16 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,234] Trial 17 finished with value: 0.8705406255038426 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,402] Trial 18 finished with value: 0.854052066635934 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,567] Trial 19 finished with value: 0.8604534946523686 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,737] Trial 20 finished with value: 0.8460838116990829 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:37,916] Trial 21 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:38,112] Trial 22 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:38,295] Trial 23 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:38,474] Trial 24 finished with value: 0.85395117383495 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:38,658] Trial 25 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:38,841] Trial 26 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,025] Trial 27 finished with value: 0.8546721037494199 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,195] Trial 28 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,423] Trial 29 finished with value: 0.7892051871464459 and parameters: {'n_neighbors': 14, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,575] Trial 30 finished with value: 0.8576045007599552 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,724] Trial 31 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:39,877] Trial 32 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:40,031] Trial 33 finished with value: 0.8603898200158628 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:40,274] Trial 34 finished with value: 0.8009871998340693 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:40,488] Trial 35 finished with value: 0.8554970667980663 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:40,646] Trial 36 finished with value: 0.8546721037494199 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:40,876] Trial 37 finished with value: 0.7765382440862095 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,042] Trial 38 finished with value: 0.8430973548557505 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,226] Trial 39 finished with value: 0.8705406255038426 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,480] Trial 40 finished with value: 0.8414528303536037 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 1}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,632] Trial 41 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,790] Trial 42 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:41,944] Trial 43 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:42,104] Trial 44 finished with value: 0.8576045007599552 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 10 with value: 0.8861999280905666.
[I 2025-04-15 11:39:42,260] Trial 45 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:42,435] Trial 46 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:42,600] Trial 47 finished with value: 0.8567987575770146 and parameters: {'n_neighbors': 28, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:42,770] Trial 48 finished with value: 0.8713242849741147 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:42,954] Trial 49 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:43,148] Trial 50 finished with value: 0.8433197210508135 and parameters: {'n_neighbors': 50, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:43,321] Trial 51 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:43,493] Trial 52 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:43,675] Trial 53 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:43,856] Trial 54 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:44,027] Trial 55 finished with value: 0.85395117383495 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:44,212] Trial 56 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:44,396] Trial 57 finished with value: 0.877212285776247 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 1}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:44,596] Trial 58 finished with value: 0.8603898200158628 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:44,846] Trial 59 finished with value: 0.8554970667980663 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,011] Trial 60 finished with value: 0.8466455165292928 and parameters: {'n_neighbors': 15, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,171] Trial 61 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,331] Trial 62 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,492] Trial 63 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,666] Trial 64 finished with value: 0.8640193604101091 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:45,833] Trial 65 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,017] Trial 66 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,184] Trial 67 finished with value: 0.8538174200892514 and parameters: {'n_neighbors': 18, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,357] Trial 68 finished with value: 0.8705406255038426 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,537] Trial 69 finished with value: 0.8713242849741147 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,727] Trial 70 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:46,910] Trial 71 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,073] Trial 72 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,244] Trial 73 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,406] Trial 74 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,568] Trial 75 finished with value: 0.8705406255038426 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,733] Trial 76 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:47,967] Trial 77 finished with value: 0.828087028274745 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,140] Trial 78 finished with value: 0.8504224924007155 and parameters: {'n_neighbors': 37, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,299] Trial 79 finished with value: 0.8713242849741147 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,463] Trial 80 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,625] Trial 81 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,794] Trial 82 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:48,967] Trial 83 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:49,130] Trial 84 finished with value: 0.8705406255038426 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:49,296] Trial 85 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:49,453] Trial 86 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:49,615] Trial 87 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:49,772] Trial 88 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,015] Trial 89 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,197] Trial 90 finished with value: 0.8509930197398065 and parameters: {'n_neighbors': 43, 'weights': 'distance', 'p': 1}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,370] Trial 91 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,567] Trial 92 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,758] Trial 93 finished with value: 0.8741269050020135 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:50,934] Trial 94 finished with value: 0.8603898200158628 and parameters: {'n_neighbors': 8, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:51,129] Trial 95 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:51,306] Trial 96 finished with value: 0.8799321891385213 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:51,488] Trial 97 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:51,659] Trial 98 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:51,853] Trial 99 finished with value: 0.8640193604101091 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:52,013] Trial 100 finished with value: 0.8861999280905666 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:52,172] Trial 101 finished with value: 0.8912347801235433 and parameters: {'n_neighbors': 3, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.
[I 2025-04-15 11:39:52,370] Trial 102 finished with value: 0.8850362082094582 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 45 with value: 0.8912347801235433.

best_params

{'n_neighbors': 2, 'weights': 'distance', 'p': 1}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                               0
target                                                                 splashing
model                             KNeighborsClassifier_splashing_smote_opt-model
holdout_test_f1_macro                                                     0.8333
holdout_test_accuracy_balanced                                          0.820602
holdout_test_roc_auc                                                    0.880015
holdout_test_f1                                                         0.891089
holdout_test_accuracy                                                   0.853333
cv_test_f1_macro_median                                                 0.896201
cv_test_accuracy_balanced_median                                        0.891641
cv_test_roc_auc_median                                                  0.916541
cv_test_f1_median                                                       0.923077
cv_test_accuracy_median                                                  0.90566
cv_test_precision_class_0_median                                        0.842105
cv_test_recall_class_0_median                                           0.842105
cv_test_f1_class_0_median                                               0.864865

Model saved in ..\results\models_modelling4\KNeighborsClassifier_splashing_smote_opt-model

In [9]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=knn_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 11:47:25,188] A new study created in memory with name: model_study
[I 2025-04-15 11:47:25,402] Trial 0 finished with value: 0.7495331386902663 and parameters: {'n_neighbors': 19, 'weights': 'uniform', 'p': 2}. Best is trial 0 with value: 0.7495331386902663.
[I 2025-04-15 11:47:25,624] Trial 1 finished with value: 0.7939749558884351 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.7939749558884351.
[I 2025-04-15 11:47:25,831] Trial 2 finished with value: 0.7300499179946813 and parameters: {'n_neighbors': 31, 'weights': 'uniform', 'p': 2}. Best is trial 1 with value: 0.7939749558884351.
[I 2025-04-15 11:47:26,052] Trial 3 finished with value: 0.7201734561003093 and parameters: {'n_neighbors': 42, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.7939749558884351.
[I 2025-04-15 11:47:26,276] Trial 4 finished with value: 0.7674836215380793 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 1}. Best is trial 1 with value: 0.7939749558884351.
[I 2025-04-15 11:47:26,417] Trial 5 finished with value: 0.8215097472745904 and parameters: {'n_neighbors': 31, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8215097472745904.
[I 2025-04-15 11:47:26,622] Trial 6 finished with value: 0.7406217752251957 and parameters: {'n_neighbors': 23, 'weights': 'uniform', 'p': 2}. Best is trial 5 with value: 0.8215097472745904.
[I 2025-04-15 11:47:26,758] Trial 7 finished with value: 0.8215097472745904 and parameters: {'n_neighbors': 30, 'weights': 'distance', 'p': 1}. Best is trial 5 with value: 0.8215097472745904.
[I 2025-04-15 11:47:26,882] Trial 8 finished with value: 0.8481797470849909 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,014] Trial 9 finished with value: 0.8261248561866411 and parameters: {'n_neighbors': 16, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,146] Trial 10 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 2, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,276] Trial 11 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,405] Trial 12 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,545] Trial 13 finished with value: 0.818164280957134 and parameters: {'n_neighbors': 10, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,690] Trial 14 finished with value: 0.8320391143086457 and parameters: {'n_neighbors': 7, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,840] Trial 15 finished with value: 0.825889248931769 and parameters: {'n_neighbors': 47, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:27,978] Trial 16 finished with value: 0.8178670544421569 and parameters: {'n_neighbors': 11, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,114] Trial 17 finished with value: 0.8481797470849909 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,263] Trial 18 finished with value: 0.8250434432688358 and parameters: {'n_neighbors': 39, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,408] Trial 19 finished with value: 0.8293678772945066 and parameters: {'n_neighbors': 24, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,548] Trial 20 finished with value: 0.8264375410371905 and parameters: {'n_neighbors': 13, 'weights': 'distance', 'p': 1}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,681] Trial 21 finished with value: 0.8481797470849909 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,815] Trial 22 finished with value: 0.8344098491300757 and parameters: {'n_neighbors': 6, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:28,948] Trial 23 finished with value: 0.8347827894416046 and parameters: {'n_neighbors': 5, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,087] Trial 24 finished with value: 0.8305881330227994 and parameters: {'n_neighbors': 14, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,229] Trial 25 finished with value: 0.834967634679978 and parameters: {'n_neighbors': 20, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,363] Trial 26 finished with value: 0.8481797470849909 and parameters: {'n_neighbors': 4, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,498] Trial 27 finished with value: 0.8121257115974075 and parameters: {'n_neighbors': 9, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,635] Trial 28 finished with value: 0.8215787839750436 and parameters: {'n_neighbors': 12, 'weights': 'distance', 'p': 2}. Best is trial 8 with value: 0.8481797470849909.
[I 2025-04-15 11:47:29,859] Trial 29 finished with value: 0.8564247029246947 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:30,067] Trial 30 finished with value: 0.7731449080688357 and parameters: {'n_neighbors': 16, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:30,272] Trial 31 finished with value: 0.8564247029246947 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:30,479] Trial 32 finished with value: 0.7939749558884351 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:30,681] Trial 33 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:30,889] Trial 34 finished with value: 0.7663808094117669 and parameters: {'n_neighbors': 20, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:31,084] Trial 35 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:31,292] Trial 36 finished with value: 0.7812044002441898 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:31,511] Trial 37 finished with value: 0.7009993710050139 and parameters: {'n_neighbors': 35, 'weights': 'uniform', 'p': 1}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:31,719] Trial 38 finished with value: 0.7367643482083255 and parameters: {'n_neighbors': 27, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:31,932] Trial 39 finished with value: 0.8445390687753636 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 1}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:32,150] Trial 40 finished with value: 0.7832451598178825 and parameters: {'n_neighbors': 18, 'weights': 'uniform', 'p': 2}. Best is trial 29 with value: 0.8564247029246947.
[I 2025-04-15 11:47:32,351] Trial 41 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:32,560] Trial 42 finished with value: 0.7968174367205935 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:32,762] Trial 43 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:32,964] Trial 44 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:33,169] Trial 45 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:33,371] Trial 46 finished with value: 0.7968174367205935 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:33,575] Trial 47 finished with value: 0.7897286052152158 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:33,772] Trial 48 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:33,973] Trial 49 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:34,210] Trial 50 finished with value: 0.7245772764647114 and parameters: {'n_neighbors': 50, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:34,412] Trial 51 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:34,610] Trial 52 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:34,812] Trial 53 finished with value: 0.8263968021387615 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:35,019] Trial 54 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:35,239] Trial 55 finished with value: 0.7915053976636605 and parameters: {'n_neighbors': 11, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:35,437] Trial 56 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:35,642] Trial 57 finished with value: 0.7947578539217998 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'p': 1}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:35,845] Trial 58 finished with value: 0.8263968021387615 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:36,045] Trial 59 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:36,260] Trial 60 finished with value: 0.7748885802315894 and parameters: {'n_neighbors': 15, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:36,468] Trial 61 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:36,670] Trial 62 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:36,870] Trial 63 finished with value: 0.7968174367205935 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:37,077] Trial 64 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:37,281] Trial 65 finished with value: 0.8263968021387615 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:37,485] Trial 66 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:37,686] Trial 67 finished with value: 0.7939749558884351 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:37,893] Trial 68 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:38,099] Trial 69 finished with value: 0.7884531237871613 and parameters: {'n_neighbors': 12, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:38,308] Trial 70 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:38,528] Trial 71 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:38,720] Trial 72 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:38,923] Trial 73 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:39,129] Trial 74 finished with value: 0.7939749558884351 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:39,337] Trial 75 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:39,537] Trial 76 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:39,737] Trial 77 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:39,941] Trial 78 finished with value: 0.7897286052152158 and parameters: {'n_neighbors': 10, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:40,142] Trial 79 finished with value: 0.8263968021387615 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:40,338] Trial 80 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:40,544] Trial 81 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:40,770] Trial 82 finished with value: 0.7330237807181696 and parameters: {'n_neighbors': 40, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:40,971] Trial 83 finished with value: 0.8564247029246947 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:41,174] Trial 84 finished with value: 0.7968174367205935 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:41,383] Trial 85 finished with value: 0.7265487436871808 and parameters: {'n_neighbors': 33, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:41,584] Trial 86 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:41,786] Trial 87 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:41,989] Trial 88 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:42,195] Trial 89 finished with value: 0.7947578539217998 and parameters: {'n_neighbors': 9, 'weights': 'uniform', 'p': 1}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:42,398] Trial 90 finished with value: 0.8220011086912677 and parameters: {'n_neighbors': 5, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:42,601] Trial 91 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:42,831] Trial 92 finished with value: 0.7367643482083255 and parameters: {'n_neighbors': 27, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:43,026] Trial 93 finished with value: 0.8323793512351626 and parameters: {'n_neighbors': 1, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:43,227] Trial 94 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:43,428] Trial 95 finished with value: 0.8564247029246947 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:43,633] Trial 96 finished with value: 0.8263968021387615 and parameters: {'n_neighbors': 6, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:43,844] Trial 97 finished with value: 0.7939749558884351 and parameters: {'n_neighbors': 8, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:44,044] Trial 98 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:44,248] Trial 99 finished with value: 0.7968174367205935 and parameters: {'n_neighbors': 7, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:44,450] Trial 100 finished with value: 0.8564247029246947 and parameters: {'n_neighbors': 4, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:44,650] Trial 101 finished with value: 0.834356807238654 and parameters: {'n_neighbors': 2, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.
[I 2025-04-15 11:47:44,853] Trial 102 finished with value: 0.8604526068065811 and parameters: {'n_neighbors': 3, 'weights': 'uniform', 'p': 2}. Best is trial 41 with value: 0.8604526068065811.

best_params

{'n_neighbors': 3, 'weights': 'uniform', 'p': 2}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.811873
holdout_test_accuracy_balanced                                             0.843182
holdout_test_roc_auc                                                       0.903182
holdout_test_f1                                                             0.73913
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.865709
cv_test_accuracy_balanced_median                                           0.887363
cv_test_roc_auc_median                                                      0.92674
cv_test_f1_median                                                            0.8125
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.918919

Model saved in ..\results\models_modelling4\KNeighborsClassifier_no_fragmentation_smote_opt-model

# SVC

In [10]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True, # Would beFalse for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']


def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=n_trials,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 11:56:50,131] A new study created in memory with name: model_study
[I 2025-04-15 11:56:50,362] Trial 0 finished with value: 0.8080241913509035 and parameters: {'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 0 with value: 0.8080241913509035.
[I 2025-04-15 11:56:50,592] Trial 1 finished with value: 0.8080241913509035 and parameters: {'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 0 with value: 0.8080241913509035.
[I 2025-04-15 11:56:50,744] Trial 2 finished with value: 0.8296865496001313 and parameters: {'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}. Best is trial 2 with value: 0.8296865496001313.
[I 2025-04-15 11:56:50,918] Trial 3 finished with value: 0.42602998654463675 and parameters: {'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}. Best is trial 2 with value: 0.8296865496001313.
[I 2025-04-15 11:56:51,082] Trial 4 finished with value: 0.8377033061764697 and parameters: {'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}. Best is trial 4 with value: 0.8377033061764697.
[I 2025-04-15 11:56:51,282] Trial 5 finished with value: 0.8578745726804143 and parameters: {'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002273762810253686}. Best is trial 5 with value: 0.8578745726804143.
[I 2025-04-15 11:56:51,442] Trial 6 finished with value: 0.8046176381971862 and parameters: {'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}. Best is trial 5 with value: 0.8578745726804143.
[I 2025-04-15 11:56:51,667] Trial 7 finished with value: 0.8188536223022468 and parameters: {'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8578745726804143.
[I 2025-04-15 11:56:51,945] Trial 8 finished with value: 0.8188536223022468 and parameters: {'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}. Best is trial 5 with value: 0.8578745726804143.
[I 2025-04-15 11:56:52,097] Trial 9 finished with value: 0.8712607580786406 and parameters: {'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}. Best is trial 9 with value: 0.8712607580786406.
[I 2025-04-15 11:56:52,259] Trial 10 finished with value: 0.8749769450979129 and parameters: {'kernel': 'poly', 'C': 3.319977760729009, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}. Best is trial 10 with value: 0.8749769450979129.
[I 2025-04-15 11:56:52,419] Trial 11 finished with value: 0.8914738736354602 and parameters: {'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7731722229182416, 'degree': 2}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:52,597] Trial 12 finished with value: 0.8751318861629922 and parameters: {'kernel': 'poly', 'C': 1.292746743685531, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:52,784] Trial 13 finished with value: 0.8621890608340187 and parameters: {'kernel': 'poly', 'C': 0.21162414884556216, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4687052188878424, 'degree': 2}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:52,948] Trial 14 finished with value: 0.8885098519585837 and parameters: {'kernel': 'poly', 'C': 13.93652805413154, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5261968434186639, 'degree': 2}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,109] Trial 15 finished with value: 0.648581297859858 and parameters: {'kernel': 'sigmoid', 'C': 20.688682738534222, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.39872427564547874}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,278] Trial 16 finished with value: 0.6088588995894746 and parameters: {'kernel': 'poly', 'C': 0.09671126207558609, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.27716262187699625, 'degree': 5}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,440] Trial 17 finished with value: 0.8645597396378728 and parameters: {'kernel': 'poly', 'C': 23.677021076320134, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6646179710147847, 'degree': 3}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,609] Trial 18 finished with value: 0.5033333363519905 and parameters: {'kernel': 'poly', 'C': 0.0011639521730508326, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9794255917727444, 'degree': 2}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,775] Trial 19 finished with value: 0.6336524292635922 and parameters: {'kernel': 'sigmoid', 'C': 22.867016285579837, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7990386883466201}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:53,933] Trial 20 finished with value: 0.8849210689004323 and parameters: {'kernel': 'poly', 'C': 4.196425639995901, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.31345818247487006, 'degree': 3}. Best is trial 11 with value: 0.8914738736354602.
[I 2025-04-15 11:56:54,094] Trial 21 finished with value: 0.8948865842362925 and parameters: {'kernel': 'poly', 'C': 5.108339251903579, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.27564606176127415, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:54,265] Trial 22 finished with value: 0.8448896609086604 and parameters: {'kernel': 'poly', 'C': 850.1631379645714, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.1352667141651322, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:54,427] Trial 23 finished with value: 0.8720092649465031 and parameters: {'kernel': 'poly', 'C': 1.0493699810375274, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5568881024505028, 'degree': 2}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:54,588] Trial 24 finished with value: 0.8704295332766259 and parameters: {'kernel': 'poly', 'C': 10.966807690555044, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.24614999796546405, 'degree': 4}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:54,769] Trial 25 finished with value: 0.88786301041996 and parameters: {'kernel': 'poly', 'C': 58.92155719746452, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.421640030729423, 'degree': 2}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:54,936] Trial 26 finished with value: 0.8918306732941109 and parameters: {'kernel': 'poly', 'C': 2.217512335620645, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.674663283354034, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:55,123] Trial 27 finished with value: 0.7116683779124334 and parameters: {'kernel': 'sigmoid', 'C': 0.11225319892766618, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8506171326413021}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:55,298] Trial 28 finished with value: 0.8711693327901224 and parameters: {'kernel': 'rbf', 'C': 2.93159840133103, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:55,484] Trial 29 finished with value: 0.8476565623617669 and parameters: {'kernel': 'rbf', 'C': 0.4101568226452635, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:55,655] Trial 30 finished with value: 0.8484100312996556 and parameters: {'kernel': 'poly', 'C': 54.92719932730384, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.6724512561148108, 'degree': 4}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,055] Trial 31 finished with value: 0.8087788844501291 and parameters: {'kernel': 'poly', 'C': 1.9581099076568422, 'class_weight': None, 'gamma_type': 'float', 'gamma': 8.61046182533375, 'coef0': 0.5197680801448192, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,221] Trial 32 finished with value: 0.8839588516291857 and parameters: {'kernel': 'poly', 'C': 13.427752148504705, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.6949067922240038, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,388] Trial 33 finished with value: 0.8204017251822638 and parameters: {'kernel': 'poly', 'C': 5.304446296546494, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.006138614103668838, 'degree': 2}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,550] Trial 34 finished with value: 0.8813729072268901 and parameters: {'kernel': 'poly', 'C': 0.6215035051351435, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.8754613309852823, 'degree': 3}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,762] Trial 35 finished with value: 0.8156066952901513 and parameters: {'kernel': 'rbf', 'C': 0.038363880098931886, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 21 with value: 0.8948865842362925.
[I 2025-04-15 11:56:56,944] Trial 36 finished with value: 0.8952060068771438 and parameters: {'kernel': 'poly', 'C': 9.821939461031244, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5705997065030042, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:57,105] Trial 37 finished with value: 0.829825203550698 and parameters: {'kernel': 'linear', 'C': 2.1593730933059616, 'class_weight': 'balanced'}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:57,270] Trial 38 finished with value: 0.8573808185984173 and parameters: {'kernel': 'poly', 'C': 0.43945943473322835, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.6094934702074951, 'degree': 4}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:57,443] Trial 39 finished with value: 0.6544238300438366 and parameters: {'kernel': 'sigmoid', 'C': 36.56199037059574, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 7.7693389631457395, 'coef0': 0.7182781336142925}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:57,727] Trial 40 finished with value: 0.8188536223022468 and parameters: {'kernel': 'linear', 'C': 154.4321071162471, 'class_weight': 'balanced'}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:57,889] Trial 41 finished with value: 0.8952060068771438 and parameters: {'kernel': 'poly', 'C': 9.197165994281523, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5753313067101367, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,053] Trial 42 finished with value: 0.8952060068771438 and parameters: {'kernel': 'poly', 'C': 8.6070558302938, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.6053440334015091, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,219] Trial 43 finished with value: 0.8952060068771438 and parameters: {'kernel': 'poly', 'C': 8.999200232638763, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5975440905431243, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,382] Trial 44 finished with value: 0.8881927077966907 and parameters: {'kernel': 'poly', 'C': 6.652823701497542, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.589938104877101, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,546] Trial 45 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 9.403958511520791, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.45422232400954826, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,718] Trial 46 finished with value: 0.865470753738075 and parameters: {'kernel': 'rbf', 'C': 165.43720388593928, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:58,881] Trial 47 finished with value: 0.8918306732941109 and parameters: {'kernel': 'poly', 'C': 11.755266861534873, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.4596613412819468, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,120] Trial 48 finished with value: 0.8188536223022468 and parameters: {'kernel': 'linear', 'C': 83.3235007874723, 'class_weight': 'balanced'}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,285] Trial 49 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 9.045546329776386, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.41386905800642726, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,450] Trial 50 finished with value: 0.8920352607818692 and parameters: {'kernel': 'poly', 'C': 31.107901184439044, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.08318037758997444, 'coef0': 0.3428510960851716, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,614] Trial 51 finished with value: 0.8881927077966907 and parameters: {'kernel': 'poly', 'C': 8.357941732064935, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.3827092609889973, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,779] Trial 52 finished with value: 0.8853391058633092 and parameters: {'kernel': 'poly', 'C': 16.17241579538404, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.49304180033338135, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:56:59,944] Trial 53 finished with value: 0.8917408694702329 and parameters: {'kernel': 'poly', 'C': 39.431684821054546, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5777511202967168, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,110] Trial 54 finished with value: 0.8751318861629922 and parameters: {'kernel': 'poly', 'C': 1.273814786228443, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.6188784535347077, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,276] Trial 55 finished with value: 0.8782462528210022 and parameters: {'kernel': 'poly', 'C': 3.53279294958362, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.4357192449460245, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,437] Trial 56 finished with value: 0.6402981845441976 and parameters: {'kernel': 'sigmoid', 'C': 7.802893066730894, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5328934798386787}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,601] Trial 57 finished with value: 0.8918306732941109 and parameters: {'kernel': 'poly', 'C': 19.136504568382897, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.47357991245002756, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,777] Trial 58 finished with value: 0.8797900038202886 and parameters: {'kernel': 'poly', 'C': 94.20338848580165, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.6325752580156081, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:00,951] Trial 59 finished with value: 0.836337577880675 and parameters: {'kernel': 'poly', 'C': 262.8282971364586, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.549778199512866, 'degree': 5}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,123] Trial 60 finished with value: 0.8188536223022468 and parameters: {'kernel': 'linear', 'C': 10.150396663573208, 'class_weight': 'balanced'}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,307] Trial 61 finished with value: 0.8782462528210022 and parameters: {'kernel': 'poly', 'C': 4.468632333474647, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.34062079165122466, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,467] Trial 62 finished with value: 0.871862578439903 and parameters: {'kernel': 'poly', 'C': 1.7371643873165041, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.2692293026990957, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,637] Trial 63 finished with value: 0.8918306732941109 and parameters: {'kernel': 'poly', 'C': 24.851426004734993, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.17419107801780215, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,799] Trial 64 finished with value: 0.8745300658017298 and parameters: {'kernel': 'poly', 'C': 5.103042639736785, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.37967311747392307, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:01,963] Trial 65 finished with value: 0.8615850481760542 and parameters: {'kernel': 'poly', 'C': 0.6569330769360207, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.20867572550371186, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,123] Trial 66 finished with value: 0.8950498853842908 and parameters: {'kernel': 'poly', 'C': 3.3263738208599563, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.729529451999823, 'degree': 3}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,285] Trial 67 finished with value: 0.8749769450979129 and parameters: {'kernel': 'poly', 'C': 3.282468335159455, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.6399655682279496, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,501] Trial 68 finished with value: 0.5424515734750682 and parameters: {'kernel': 'rbf', 'C': 8.294247038237769, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.00011283166461189807}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,675] Trial 69 finished with value: 0.8839000699993201 and parameters: {'kernel': 'poly', 'C': 49.68088357799367, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.7213112437978331, 'degree': 2}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,836] Trial 70 finished with value: 0.633671855463651 and parameters: {'kernel': 'sigmoid', 'C': 13.27401976345418, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.759075200590329}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:02,999] Trial 71 finished with value: 0.8846540730656596 and parameters: {'kernel': 'poly', 'C': 2.5654658357452753, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.4935627959094588, 'degree': 3}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:03,163] Trial 72 finished with value: 0.8552174934499163 and parameters: {'kernel': 'poly', 'C': 0.871922851501995, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5564356847409851, 'degree': 3}. Best is trial 36 with value: 0.8952060068771438.
[I 2025-04-15 11:57:03,328] Trial 73 finished with value: 0.8918306732941109 and parameters: {'kernel': 'poly', 'C': 5.6023316360566, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.4303090867374761, 'degree': 3}. Best is trial 36 with value: 0.8952060068771438.

best_params

{'kernel': 'poly',
 'C': 8.080278139769582,
 'class_weight': 'balanced',
 'coef0': 0.48875906950513137,
 'degree': 2,
 'gamma': 'auto'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                              0
target                                                splashing
model                             SVC_splashing_smote_opt-model
holdout_test_f1_macro                                  0.806892
holdout_test_accuracy_balanced                         0.799769
holdout_test_roc_auc                                   0.892747
holdout_test_f1                                        0.868687
holdout_test_accuracy                                  0.826667
cv_test_f1_macro_median                                0.898584
cv_test_accuracy_balanced_median                       0.903251
cv_test_roc_auc_median                                 0.927245
cv_test_f1_median                                      0.923077
cv_test_accuracy_median                                 0.90566
cv_test_precision_class_0_median                       0.818182
cv_test_recall_class_0_median                          0.894737
cv_test_f1_class_0_median                              0.871795

Model saved in ..\results\models_modelling4\SVC_splashing_smote_opt-model

In [6]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True, # Would be False for optimization, True for metrics
    # 'shrinking': True, # already in the default params
}
params_to_process = ['gamma']

def svc_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    kernel = trial.suggest_categorical(
        'kernel', ['linear', 'rbf', 'sigmoid', 'poly']
    )
    C = trial.suggest_float('C', 1e-3, 1e3, log=True)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "kernel": kernel,
        "C": C,
        "class_weight": class_weight,
        # Optional params
        # 'gamma': gamma
        # 'coef0': coef0,
        # 'degree': degree,
    }
    
    if kernel in ['rbf', 'poly', 'sigmoid']:
        gamma_choice = trial.suggest_categorical(
            "gamma_type", ["scale", "auto", "float"]
        )
        if gamma_choice == "float":
            gamma = trial.suggest_float("gamma", 1e-4, 10, log=True)
        else:
            gamma = gamma_choice
        suggested_estimator_params['gamma'] = gamma
    
    # Optional params
    if kernel in ['sigmoid', 'poly']:
        suggested_estimator_params['coef0'] = trial.suggest_float(
            "coef0", 0.0, 1.0
        )
    if kernel == 'poly':
        suggested_estimator_params['degree'] = trial.suggest_int(
            "degree", 2, 5
        )
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    # print(estimator_params)
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=svc_objective,
    n_trials=1400,
    seed=seed,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 12:41:50,248] A new study created in memory with name: model_study
[I 2025-04-15 12:41:50,480] Trial 0 finished with value: 0.7887325010206364 and parameters: {'kernel': 'rbf', 'C': 0.008632008168602538, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 0 with value: 0.7887325010206364.
[I 2025-04-15 12:41:50,699] Trial 1 finished with value: 0.7887325010206364 and parameters: {'kernel': 'rbf', 'C': 0.012329623163659839, 'class_weight': 'balanced', 'gamma_type': 'scale'}. Best is trial 0 with value: 0.7887325010206364.
[I 2025-04-15 12:41:50,859] Trial 2 finished with value: 0.827403676065338 and parameters: {'kernel': 'linear', 'C': 0.5450293694558254, 'class_weight': None}. Best is trial 2 with value: 0.827403676065338.
[I 2025-04-15 12:41:51,031] Trial 3 finished with value: 0.42566619835948 and parameters: {'kernel': 'poly', 'C': 0.010547383621352036, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.09767211400638387, 'degree': 4}. Best is trial 2 with value: 0.827403676065338.
[I 2025-04-15 12:41:51,204] Trial 4 finished with value: 0.7986135217471168 and parameters: {'kernel': 'sigmoid', 'C': 285.7080075040722, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.0008399864445957502, 'coef0': 0.9695846277645586}. Best is trial 2 with value: 0.827403676065338.
[I 2025-04-15 12:41:51,377] Trial 5 finished with value: 0.8411053566469714 and parameters: {'kernel': 'rbf', 'C': 339.8172415010595, 'class_weight': 'balanced', 'gamma_type': 'float', 'gamma': 0.002273762810253686}. Best is trial 5 with value: 0.8411053566469714.
[I 2025-04-15 12:41:51,546] Trial 6 finished with value: 0.7510795658505588 and parameters: {'kernel': 'linear', 'C': 0.007007213496896407, 'class_weight': None}. Best is trial 5 with value: 0.8411053566469714.
[I 2025-04-15 12:41:51,828] Trial 7 finished with value: 0.8162157417435777 and parameters: {'kernel': 'linear', 'C': 78.12113973534926, 'class_weight': 'balanced'}. Best is trial 5 with value: 0.8411053566469714.
[I 2025-04-15 12:41:52,085] Trial 8 finished with value: 0.8295559204284715 and parameters: {'kernel': 'linear', 'C': 150.8761367568167, 'class_weight': None}. Best is trial 5 with value: 0.8411053566469714.
[I 2025-04-15 12:41:52,248] Trial 9 finished with value: 0.8706236042448587 and parameters: {'kernel': 'poly', 'C': 6.688747907702058, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.06403036652671171, 'coef0': 0.770967179954561, 'degree': 3}. Best is trial 9 with value: 0.8706236042448587.
[I 2025-04-15 12:41:52,420] Trial 10 finished with value: 0.8633007299226971 and parameters: {'kernel': 'poly', 'C': 3.319977760729009, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7654922079402076, 'degree': 2}. Best is trial 9 with value: 0.8706236042448587.
[I 2025-04-15 12:41:52,587] Trial 11 finished with value: 0.8734042666990304 and parameters: {'kernel': 'poly', 'C': 5.552661041119787, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7731722229182416, 'degree': 2}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:52,743] Trial 12 finished with value: 0.8671377458409675 and parameters: {'kernel': 'poly', 'C': 4.227037048440708, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6071842740332256, 'degree': 2}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:52,905] Trial 13 finished with value: 0.831631518383504 and parameters: {'kernel': 'poly', 'C': 0.21162414884556216, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.7853408064576318, 'degree': 3}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:53,127] Trial 14 finished with value: 0.7902554044907397 and parameters: {'kernel': 'poly', 'C': 15.142039581809946, 'class_weight': None, 'gamma_type': 'float', 'gamma': 2.0827600706085203, 'coef0': 0.4439875837140775, 'degree': 3}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:53,318] Trial 15 finished with value: 0.7236472918317476 and parameters: {'kernel': 'sigmoid', 'C': 0.18434865271268852, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.9974597158548155}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:53,492] Trial 16 finished with value: 0.8373365879278873 and parameters: {'kernel': 'poly', 'C': 30.85106557676194, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.37985925452361524, 'coef0': 0.43910601384159637, 'degree': 5}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:53,662] Trial 17 finished with value: 0.8441649449129892 and parameters: {'kernel': 'poly', 'C': 5.940709675700833, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.04045191588988909, 'coef0': 0.6926452458423964, 'degree': 2}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:53,825] Trial 18 finished with value: 0.840298653298175 and parameters: {'kernel': 'poly', 'C': 0.9032360273921896, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.8626219710630426, 'degree': 3}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:54,000] Trial 19 finished with value: 0.742431454729509 and parameters: {'kernel': 'sigmoid', 'C': 0.11496681839242444, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5529751012593238}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:54,181] Trial 20 finished with value: 0.35807543535955394 and parameters: {'kernel': 'poly', 'C': 0.0011997072580708827, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.028659304016674842, 'coef0': 0.20179286701624122, 'degree': 4}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:54,345] Trial 21 finished with value: 0.8633007299226971 and parameters: {'kernel': 'poly', 'C': 3.2755668517740912, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.636841564604146, 'degree': 2}. Best is trial 11 with value: 0.8734042666990304.
[I 2025-04-15 12:41:54,508] Trial 22 finished with value: 0.8737703822226717 and parameters: {'kernel': 'poly', 'C': 14.02674345969218, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5582226765655359, 'degree': 2}. Best is trial 22 with value: 0.8737703822226717.
[I 2025-04-15 12:41:54,653] Trial 23 finished with value: 0.8725027106743214 and parameters: {'kernel': 'poly', 'C': 25.33252869481415, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.30103049332526727, 'degree': 2}. Best is trial 22 with value: 0.8737703822226717.
[I 2025-04-15 12:41:54,811] Trial 24 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 31.61023579184231, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.35853026844418856, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:54,958] Trial 25 finished with value: 0.8796406293037445 and parameters: {'kernel': 'poly', 'C': 53.67383227000103, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3246719389901426, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,106] Trial 26 finished with value: 0.8796406293037445 and parameters: {'kernel': 'poly', 'C': 44.809456363552705, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.3354593901707578, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,249] Trial 27 finished with value: 0.6549218234753129 and parameters: {'kernel': 'sigmoid', 'C': 729.1870598904976, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.33241656289980087}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,412] Trial 28 finished with value: 0.8360514811589096 and parameters: {'kernel': 'rbf', 'C': 985.6586586437194, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,562] Trial 29 finished with value: 0.8525640115457997 and parameters: {'kernel': 'rbf', 'C': 70.9377225921462, 'class_weight': 'balanced', 'gamma_type': 'auto'}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,710] Trial 30 finished with value: 0.8420526497066241 and parameters: {'kernel': 'poly', 'C': 60.98903237737284, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.3053845674648065, 'degree': 3}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:55,853] Trial 31 finished with value: 0.868940989862872 and parameters: {'kernel': 'poly', 'C': 15.318898798896432, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4139862084027018, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:56,009] Trial 32 finished with value: 0.863176290984474 and parameters: {'kernel': 'poly', 'C': 160.0265394917746, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.16448804475298406, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:56,153] Trial 33 finished with value: 0.8803642358662509 and parameters: {'kernel': 'poly', 'C': 36.03997884753301, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5115863001409895, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:56,325] Trial 34 finished with value: 0.8125949802049682 and parameters: {'kernel': 'poly', 'C': 42.38723752164795, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.0002621123047129581, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:56,478] Trial 35 finished with value: 0.8446949988380774 and parameters: {'kernel': 'rbf', 'C': 137.57394638242744, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:56,621] Trial 36 finished with value: 0.8413816852653468 and parameters: {'kernel': 'poly', 'C': 1.5618415255431364, 'class_weight': 'balanced', 'gamma_type': 'scale', 'coef0': 0.36704998383499743, 'degree': 3}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:57,018] Trial 37 finished with value: 0.832970423446381 and parameters: {'kernel': 'linear', 'C': 374.9435889264481, 'class_weight': 'balanced'}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:57,164] Trial 38 finished with value: 0.6561997276155039 and parameters: {'kernel': 'sigmoid', 'C': 10.79387164803823, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.2353676823377263}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:57,308] Trial 39 finished with value: 0.8534186544107758 and parameters: {'kernel': 'poly', 'C': 1.6125470078675013, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.4910070095647069, 'degree': 2}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:57,602] Trial 40 finished with value: 0.832970423446381 and parameters: {'kernel': 'linear', 'C': 268.62288916903697, 'class_weight': None}. Best is trial 24 with value: 0.8811195463635596.
[I 2025-04-15 12:41:57,750] Trial 41 finished with value: 0.8845466824215789 and parameters: {'kernel': 'poly', 'C': 28.682610859801468, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.49963292619423594, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:57,894] Trial 42 finished with value: 0.877332103034121 and parameters: {'kernel': 'poly', 'C': 28.749035520325894, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3866010978215963, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,049] Trial 43 finished with value: 0.8626406424440972 and parameters: {'kernel': 'poly', 'C': 96.69442889657631, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.49623303741125724, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,196] Trial 44 finished with value: 0.87629015400376 and parameters: {'kernel': 'poly', 'C': 47.80397580690849, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.25507626260609845, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,396] Trial 45 finished with value: 0.8601964516399981 and parameters: {'kernel': 'poly', 'C': 526.3384394758225, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.47495350489807187, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,550] Trial 46 finished with value: 0.8461421208319779 and parameters: {'kernel': 'rbf', 'C': 203.79793060475234, 'class_weight': None, 'gamma_type': 'scale'}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,695] Trial 47 finished with value: 0.858145060581161 and parameters: {'kernel': 'poly', 'C': 105.55975590845885, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.09700910826311337, 'degree': 3}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,845] Trial 48 finished with value: 0.8175474705461757 and parameters: {'kernel': 'linear', 'C': 9.669959371817924, 'class_weight': None}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:58,992] Trial 49 finished with value: 0.877332103034121 and parameters: {'kernel': 'poly', 'C': 19.216804375221773, 'class_weight': 'balanced', 'gamma_type': 'auto', 'coef0': 0.5539520603295712, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,155] Trial 50 finished with value: 0.8095999489764731 and parameters: {'kernel': 'poly', 'C': 2.3259965776322047, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3607101108619543, 'degree': 5}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,302] Trial 51 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 34.32599898232147, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3882079391237793, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,445] Trial 52 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 36.15011491106365, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2830965255802791, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,589] Trial 53 finished with value: 0.8707158038654865 and parameters: {'kernel': 'poly', 'C': 6.948379642044337, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.24627431905036648, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,742] Trial 54 finished with value: 0.7718205625609731 and parameters: {'kernel': 'poly', 'C': 0.04774173490111867, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.40917271331702665, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:41:59,886] Trial 55 finished with value: 0.8614231346695286 and parameters: {'kernel': 'poly', 'C': 28.993406407864384, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.1386192428165144, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,046] Trial 56 finished with value: 0.7506257556482393 and parameters: {'kernel': 'sigmoid', 'C': 64.26551877214776, 'class_weight': None, 'gamma_type': 'float', 'gamma': 0.00011029924213744616, 'coef0': 0.44052111504846897}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,191] Trial 57 finished with value: 0.8661969990881049 and parameters: {'kernel': 'poly', 'C': 8.909434796461472, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2728248766174711, 'degree': 3}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,338] Trial 58 finished with value: 0.877332103034121 and parameters: {'kernel': 'poly', 'C': 21.296809882382114, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.6038541530042936, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,484] Trial 59 finished with value: 0.8392845796079939 and parameters: {'kernel': 'poly', 'C': 0.5721764446291575, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.5240898985253704, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,705] Trial 60 finished with value: 0.8265294290281038 and parameters: {'kernel': 'linear', 'C': 116.9681384789546, 'class_weight': None}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,848] Trial 61 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 33.58479296778733, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3211221592569738, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:00,995] Trial 62 finished with value: 0.8845466824215789 and parameters: {'kernel': 'poly', 'C': 44.41719138210891, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3048828028060847, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:01,139] Trial 63 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 36.211938214768765, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.39008001120602515, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:01,317] Trial 64 finished with value: 0.8528145062293745 and parameters: {'kernel': 'poly', 'C': 5.371088360767514, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3748457523119571, 'degree': 4}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:01,796] Trial 65 finished with value: 0.860705268357524 and parameters: {'kernel': 'poly', 'C': 17.292752811812157, 'class_weight': None, 'gamma_type': 'float', 'gamma': 3.0676406276063064, 'coef0': 0.18971627763774154, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:01,951] Trial 66 finished with value: 0.8765610979226771 and parameters: {'kernel': 'poly', 'C': 221.5035402246077, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.2878058668665514, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,098] Trial 67 finished with value: 0.8559307327091309 and parameters: {'kernel': 'poly', 'C': 70.71242603722165, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.4524538302306247, 'degree': 3}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,248] Trial 68 finished with value: 0.8681408731772472 and parameters: {'kernel': 'rbf', 'C': 11.565796381267429, 'class_weight': None, 'gamma_type': 'auto'}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,394] Trial 69 finished with value: 0.6645826179223248 and parameters: {'kernel': 'sigmoid', 'C': 3.704460804294107, 'class_weight': None, 'gamma_type': 'scale', 'coef0': 0.40652447572456357}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,539] Trial 70 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 35.51490388900184, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.34104332657093145, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,684] Trial 71 finished with value: 0.8811195463635596 and parameters: {'kernel': 'poly', 'C': 39.57699732649606, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.3565922867131358, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,832] Trial 72 finished with value: 0.8725027106743214 and parameters: {'kernel': 'poly', 'C': 26.356420955733405, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.22652428131142519, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:02,982] Trial 73 finished with value: 0.8626406424440972 and parameters: {'kernel': 'poly', 'C': 92.47350660096582, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.31189071170549026, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.
[I 2025-04-15 12:42:03,127] Trial 74 finished with value: 0.8649089930734198 and parameters: {'kernel': 'poly', 'C': 18.84027071998075, 'class_weight': None, 'gamma_type': 'auto', 'coef0': 0.27160191779186843, 'degree': 2}. Best is trial 41 with value: 0.8845466824215789.

best_params

{'kernel': 'poly',
 'C': 28.682610859801468,
 'class_weight': None,
 'coef0': 0.49963292619423594,
 'degree': 2,
 'gamma': 'auto'}

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                     0
target                                                no_fragmentation
model                             SVC_no_fragmentation_smote_opt-model
holdout_test_f1_macro                                         0.839194
holdout_test_accuracy_balanced                                0.861364
holdout_test_roc_auc                                          0.949091
holdout_test_f1                                               0.772727
holdout_test_accuracy                                         0.866667
cv_test_f1_macro_median                                       0.871224
cv_test_accuracy_balanced_median                              0.913004
cv_test_roc_auc_median                                        0.974359
cv_test_f1_median                                             0.823529
cv_test_accuracy_median                                       0.888889
cv_test_precision_class_0_median                              0.972222
cv_test_recall_class_0_median                                 0.871795
cv_test_f1_class_0_median                                     0.921053

Model saved in ..\results\models_modelling4\SVC_no_fragmentation_smote_opt-model