Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

base_estimator_params - redundant thing in logging!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = False
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 40 # was checked with 1000 and 5000

save_model_and_metrics = False

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    seed:int=seed,
):
    
    # Switch off probability for SVC, since it is long to optimize
    if 'probability' in estimator_params:
        estimator_params['probability'] = False
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
        seed=seed,
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    # Switch on probability for SVC, to get metrics like roc_auc for the final model
    if 'probability' in estimator_params:
        estimator_params['probability'] = True
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# CatBoost

In [6]:
estimator = CatBoostClassifier
target = 'splashing'
# TODO: Try with GPU!
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

def catboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    suggested_estimator_params = {
        "iterations": trial.suggest_int("iterations", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "depth": trial.suggest_int("depth", 3, 10),
        "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10.0, log=True),
        "random_strength": trial.suggest_float("random_strength", 0.0, 1.0),
        "border_count": trial.suggest_int("border_count", 32, 255),
        "grow_policy": trial.suggest_categorical("grow_policy", ["SymmetricTree", "Depthwise", "Lossguide"]),
        "bootstrap_type": trial.suggest_categorical("bootstrap_type", ["Bayesian", "Bernoulli", "MVS"]),
        "auto_class_weights": trial.suggest_categorical("auto_class_weights", ["Balanced", "SqrtBalanced", None]),
    }
    
    if suggested_estimator_params['bootstrap_type'] == 'Bernoulli':
        suggested_estimator_params['subsample'] = trial.suggest_float(
            "subsample", 0.5, 1.0
        )
        
    if suggested_estimator_params['bootstrap_type'] == 'Bayesian':
        suggested_estimator_params['bagging_temperature'] = (
            trial.suggest_float("bagging_temperature", 0.0, 1.0)
        )

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 12:08:19,211] A new study created in memory with name: model_study
[I 2025-04-15 12:08:25,749] Trial 0 finished with value: 0.8937955000766388 and parameters: {'iterations': 406, 'learning_rate': 0.22648248189516848, 'depth': 8, 'l2_leaf_reg': 0.24810409748678125, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 0 with value: 0.8937955000766388.
[I 2025-04-15 12:08:28,277] Trial 1 finished with value: 0.8768204014310234 and parameters: {'iterations': 224, 'learning_rate': 0.005670807781371429, 'depth': 7, 'l2_leaf_reg': 0.05342937261279776, 'random_strength': 0.2912291401980419, 'border_count': 169, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.8037724259507192}. Best is trial 0 with value: 0.8937955000766388.
[I 2025-04-15 12:08:35,351] Trial 2 finished with value: 0.8641856475089463 and parameters: {'iterations': 212, 'learning_rate': 0.0014492412389916862, 'depth': 10, 'l2_leaf_reg': 7.2866537374910445, 'random_strength': 0.8083973481164611, 'border_count': 100, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.6558555380447055}. Best is trial 0 with value: 0.8937955000766388.
[I 2025-04-15 12:08:38,046] Trial 3 finished with value: 0.8862119043850589 and parameters: {'iterations': 544, 'learning_rate': 0.02260828676373495, 'depth': 4, 'l2_leaf_reg': 7.556810141274429, 'random_strength': 0.7751328233611146, 'border_count': 242, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.9143687545759647}. Best is trial 0 with value: 0.8937955000766388.
[I 2025-04-15 12:08:39,357] Trial 4 finished with value: 0.8821650881155556 and parameters: {'iterations': 389, 'learning_rate': 0.0049648810171066555, 'depth': 7, 'l2_leaf_reg': 0.0036618192203924276, 'random_strength': 0.8021969807540397, 'border_count': 48, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'SqrtBalanced', 'subsample': 0.6792328642721364}. Best is trial 0 with value: 0.8937955000766388.
[I 2025-04-15 12:08:41,753] Trial 5 finished with value: 0.8962630174893488 and parameters: {'iterations': 160, 'learning_rate': 0.1374079439469766, 'depth': 7, 'l2_leaf_reg': 0.021066486017042207, 'random_strength': 0.06355835028602363, 'border_count': 101, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.770967179954561}. Best is trial 5 with value: 0.8962630174893488.
[I 2025-04-15 12:08:43,228] Trial 6 finished with value: 0.9000074906269113 and parameters: {'iterations': 519, 'learning_rate': 0.019718442220616167, 'depth': 6, 'l2_leaf_reg': 0.0012637946338082875, 'random_strength': 0.10789142699330445, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.289751452913768}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:08:49,828] Trial 7 finished with value: 0.8735410026851701 and parameters: {'iterations': 203, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 0.34167643418329696, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': None, 'subsample': 0.9090073829612466}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:01,282] Trial 8 finished with value: 0.8832053859284408 and parameters: {'iterations': 868, 'learning_rate': 0.001040450133602816, 'depth': 7, 'l2_leaf_reg': 0.0467351899956275, 'random_strength': 0.22210781047073025, 'border_count': 58, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.7486242529461927}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:02,226] Trial 9 finished with value: 0.8619722016181741 and parameters: {'iterations': 336, 'learning_rate': 0.005076734398297609, 'depth': 3, 'l2_leaf_reg': 0.27431991397796696, 'random_strength': 0.5026790232288615, 'border_count': 43, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:03,998] Trial 10 finished with value: 0.8939694228425344 and parameters: {'iterations': 652, 'learning_rate': 0.03357104002950685, 'depth': 5, 'l2_leaf_reg': 0.0011799062523159302, 'random_strength': 0.5025312176747964, 'border_count': 153, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.06569066558371356}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:04,227] Trial 11 finished with value: 0.866627883838475 and parameters: {'iterations': 92, 'learning_rate': 0.07019923676126961, 'depth': 5, 'l2_leaf_reg': 0.007223767547697707, 'random_strength': 0.031267559932569855, 'border_count': 106, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.8864474975258905}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:06,531] Trial 12 finished with value: 0.8898190165985321 and parameters: {'iterations': 764, 'learning_rate': 0.06882229358247148, 'depth': 6, 'l2_leaf_reg': 0.011340153917355185, 'random_strength': 0.027627233299954937, 'border_count': 110, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.4439875837140775}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:09,294] Trial 13 finished with value: 0.8962011017970087 and parameters: {'iterations': 1000, 'learning_rate': 0.07335829640540542, 'depth': 6, 'l2_leaf_reg': 0.001786709116335659, 'random_strength': 0.34978410362232804, 'border_count': 82, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.730607689502168}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:15,458] Trial 14 finished with value: 0.896075243660163 and parameters: {'iterations': 586, 'learning_rate': 0.010625832642110054, 'depth': 8, 'l2_leaf_reg': 0.015030256833470224, 'random_strength': 0.4062570060668099, 'border_count': 130, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bayesian', 'auto_class_weights': None, 'bagging_temperature': 0.3515216581332119}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:18,909] Trial 15 finished with value: 0.8928917724140657 and parameters: {'iterations': 688, 'learning_rate': 0.1372699925908556, 'depth': 5, 'l2_leaf_reg': 0.028467648020263074, 'random_strength': 0.16014780270761303, 'border_count': 35, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'Balanced', 'bagging_temperature': 0.18303300285044033}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:19,245] Trial 16 finished with value: 0.8556970179627553 and parameters: {'iterations': 52, 'learning_rate': 0.011378395750304936, 'depth': 8, 'l2_leaf_reg': 1.8726277447263366, 'random_strength': 0.6136421990447961, 'border_count': 182, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'auto_class_weights': 'SqrtBalanced', 'bagging_temperature': 0.6537096158441438}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:20,148] Trial 17 finished with value: 0.8974905077798595 and parameters: {'iterations': 294, 'learning_rate': 0.03551841536446975, 'depth': 3, 'l2_leaf_reg': 0.003779551123964298, 'random_strength': 0.11585639417226824, 'border_count': 77, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:21,140] Trial 18 finished with value: 0.8856056595582201 and parameters: {'iterations': 453, 'learning_rate': 0.033623347032272786, 'depth': 3, 'l2_leaf_reg': 0.0035798471744163418, 'random_strength': 0.23290145235773319, 'border_count': 80, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 6 with value: 0.9000074906269113.
[I 2025-04-15 12:09:22,631] Trial 19 finished with value: 0.9009256248538223 and parameters: {'iterations': 310, 'learning_rate': 0.017902054523659647, 'depth': 4, 'l2_leaf_reg': 0.0010132123695702968, 'random_strength': 0.9962253844052453, 'border_count': 132, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 19 with value: 0.9009256248538223.
[I 2025-04-15 12:09:25,237] Trial 20 finished with value: 0.8758569446919598 and parameters: {'iterations': 514, 'learning_rate': 0.002393846997665612, 'depth': 4, 'l2_leaf_reg': 0.0012672688299764823, 'random_strength': 0.59704467503944, 'border_count': 196, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 19 with value: 0.9009256248538223.
[I 2025-04-15 12:09:26,890] Trial 21 finished with value: 0.8927398041064253 and parameters: {'iterations': 344, 'learning_rate': 0.01458103363459501, 'depth': 4, 'l2_leaf_reg': 0.003502312851092158, 'random_strength': 0.9773097798018505, 'border_count': 131, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 19 with value: 0.9009256248538223.
[I 2025-04-15 12:09:27,842] Trial 22 finished with value: 0.9051591680986127 and parameters: {'iterations': 298, 'learning_rate': 0.027307414372781107, 'depth': 3, 'l2_leaf_reg': 0.005401718944251677, 'random_strength': 0.6680838764928432, 'border_count': 78, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:30,205] Trial 23 finished with value: 0.8853508719372322 and parameters: {'iterations': 488, 'learning_rate': 0.02175279234137196, 'depth': 4, 'l2_leaf_reg': 0.0010100891111753955, 'random_strength': 0.6758691171082526, 'border_count': 144, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:31,077] Trial 24 finished with value: 0.9048367655595912 and parameters: {'iterations': 276, 'learning_rate': 0.048142121019310584, 'depth': 3, 'l2_leaf_reg': 0.002545402209933729, 'random_strength': 0.9457851333529386, 'border_count': 64, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:31,961] Trial 25 finished with value: 0.8831649023455812 and parameters: {'iterations': 257, 'learning_rate': 0.04357356796899264, 'depth': 3, 'l2_leaf_reg': 0.006991783612736258, 'random_strength': 0.9726448270199789, 'border_count': 129, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:32,295] Trial 26 finished with value: 0.8326379019449662 and parameters: {'iterations': 132, 'learning_rate': 0.008253641606501463, 'depth': 3, 'l2_leaf_reg': 0.002600585719639381, 'random_strength': 0.9264960537527439, 'border_count': 91, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:33,607] Trial 27 finished with value: 0.8982365404782334 and parameters: {'iterations': 288, 'learning_rate': 0.0689716990842976, 'depth': 4, 'l2_leaf_reg': 0.006648135086659495, 'random_strength': 0.6990924528311823, 'border_count': 61, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:36,620] Trial 28 finished with value: 0.8796280627441806 and parameters: {'iterations': 413, 'learning_rate': 0.044518541659373856, 'depth': 5, 'l2_leaf_reg': 0.10696027760873182, 'random_strength': 0.9002311876330394, 'border_count': 119, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:37,699] Trial 29 finished with value: 0.8787764964572595 and parameters: {'iterations': 381, 'learning_rate': 0.28882002855722044, 'depth': 3, 'l2_leaf_reg': 0.7386210901079607, 'random_strength': 0.8637978084194083, 'border_count': 68, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:39,308] Trial 30 finished with value: 0.8699057996475295 and parameters: {'iterations': 315, 'learning_rate': 0.11380738271745854, 'depth': 4, 'l2_leaf_reg': 0.09658999634755215, 'random_strength': 0.7401870191390061, 'border_count': 161, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:43,510] Trial 31 finished with value: 0.8923369227083215 and parameters: {'iterations': 602, 'learning_rate': 0.02049308525395553, 'depth': 6, 'l2_leaf_reg': 0.0020386576836817533, 'random_strength': 0.4280685513602412, 'border_count': 33, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:44,463] Trial 32 finished with value: 0.8708530254080611 and parameters: {'iterations': 173, 'learning_rate': 0.016816785217703814, 'depth': 5, 'l2_leaf_reg': 0.0010117133577697062, 'random_strength': 0.98645673818662, 'border_count': 54, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:45,812] Trial 33 finished with value: 0.8698948286337851 and parameters: {'iterations': 446, 'learning_rate': 0.008357793600493785, 'depth': 3, 'l2_leaf_reg': 0.0021385985786293816, 'random_strength': 0.56194027249858, 'border_count': 69, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:46,876] Trial 34 finished with value: 0.9044076097572112 and parameters: {'iterations': 241, 'learning_rate': 0.022664453158795936, 'depth': 4, 'l2_leaf_reg': 0.005917688184348105, 'random_strength': 0.8324549362765654, 'border_count': 50, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:47,966] Trial 35 finished with value: 0.8965239776472561 and parameters: {'iterations': 213, 'learning_rate': 0.04934645570698514, 'depth': 4, 'l2_leaf_reg': 0.005970221602233928, 'random_strength': 0.8244554018335923, 'border_count': 92, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:49,375] Trial 36 finished with value: 0.896899847283925 and parameters: {'iterations': 262, 'learning_rate': 0.02629009866239543, 'depth': 4, 'l2_leaf_reg': 0.010850224498845902, 'random_strength': 0.7729385492860437, 'border_count': 251, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:50,436] Trial 37 finished with value: 0.8649335110211064 and parameters: {'iterations': 121, 'learning_rate': 0.003481527307565611, 'depth': 10, 'l2_leaf_reg': 0.0276803485812995, 'random_strength': 0.9156544465506162, 'border_count': 51, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': None}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:51,531] Trial 38 finished with value: 0.8595078090709947 and parameters: {'iterations': 365, 'learning_rate': 0.014969266837120592, 'depth': 3, 'l2_leaf_reg': 0.004731036120722886, 'random_strength': 0.84853547830364, 'border_count': 90, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'auto_class_weights': 'Balanced', 'subsample': 0.5059459842777343}. Best is trial 22 with value: 0.9051591680986127.
[I 2025-04-15 12:09:52,794] Trial 39 finished with value: 0.8933325230924609 and parameters: {'iterations': 237, 'learning_rate': 0.01222844330186142, 'depth': 4, 'l2_leaf_reg': 0.01466720504365071, 'random_strength': 0.7274471463769272, 'border_count': 222, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS', 'auto_class_weights': 'Balanced'}. Best is trial 22 with value: 0.9051591680986127.

best_params

{'iterations': 298,
 'learning_rate': 0.027307414372781107,
 'depth': 3,
 'l2_leaf_reg': 0.005401718944251677,
 'random_strength': 0.6680838764928432,
 'border_count': 78,
 'grow_policy': 'Lossguide',
 'bootstrap_type': 'MVS',
 'auto_class_weights': 'Balanced'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                       0
target                                                         splashing
model                             CatBoostClassifier_splashing_opt-model
holdout_test_f1_macro                                           0.823391
holdout_test_accuracy_balanced                                  0.818287
holdout_test_roc_auc                                             0.94213
holdout_test_f1                                                 0.877551
holdout_test_accuracy                                               0.84
cv_test_f1_macro_median                                         0.896201
cv_test_accuracy_balanced_median                                0.891641
cv_test_roc_auc_median                                          0.947368
cv_test_f1_median                                               0.925373
cv_test_accuracy_median                                          0.90566
cv_test_precision_class_0_median                                    0.85
cv_test_recall_class_0_median                                   0.888889
cv_test_f1_class_0_median                                       0.864865

In [7]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}
# params_to_process = ['gamma']
params_to_process = None

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=catboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 10:50:03,125] A new study created in memory with name: model_study
[I 2025-04-15 10:50:16,470] Trial 0 finished with value: 0.855167909848696 and parameters: {'iterations': 500, 'learning_rate': 0.22648248189516848, 'depth': 9, 'l2_leaf_reg': 6.387926357773329, 'random_strength': 0.15601864044243652, 'border_count': 66, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.855167909848696.
[I 2025-04-15 10:50:22,718] Trial 1 finished with value: 0.8436344979961399 and parameters: {'iterations': 866, 'learning_rate': 0.0033572967053517922, 'depth': 5, 'l2_leaf_reg': 2.650640588680904, 'random_strength': 0.3042422429595377, 'border_count': 149, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.855167909848696.
[I 2025-04-15 10:50:24,165] Trial 2 finished with value: 0.8515161679441593 and parameters: {'iterations': 565, 'learning_rate': 0.08810003129071789, 'depth': 5, 'l2_leaf_reg': 5.628109945722504, 'random_strength': 0.5924145688620425, 'border_count': 42, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6523068845866853}. Best is trial 0 with value: 0.855167909848696.
[I 2025-04-15 10:50:25,210] Trial 3 finished with value: 0.8482733376454574 and parameters: {'iterations': 278, 'learning_rate': 0.04953682563497157, 'depth': 7, 'l2_leaf_reg': 2.0983441136030097, 'random_strength': 0.4951769101112702, 'border_count': 39, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.855167909848696.
[I 2025-04-15 10:50:28,893] Trial 4 finished with value: 0.858549844856249 and parameters: {'iterations': 348, 'learning_rate': 0.25221951700214285, 'depth': 9, 'l2_leaf_reg': 9.455490474077703, 'random_strength': 0.8948273504276488, 'border_count': 165, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 4 with value: 0.858549844856249.
[I 2025-04-15 10:50:32,514] Trial 5 finished with value: 0.846261709691846 and parameters: {'iterations': 417, 'learning_rate': 0.11294923622078903, 'depth': 6, 'l2_leaf_reg': 3.5284105871864266, 'random_strength': 0.5426960831582485, 'border_count': 63, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.8154614284548342}. Best is trial 4 with value: 0.858549844856249.
[I 2025-04-15 10:50:37,711] Trial 6 finished with value: 0.8679340285391705 and parameters: {'iterations': 766, 'learning_rate': 0.06394979414183315, 'depth': 9, 'l2_leaf_reg': 1.6664018656068134, 'random_strength': 0.3584657285442726, 'border_count': 57, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:50:47,837] Trial 7 finished with value: 0.8419325740223683 and parameters: {'iterations': 784, 'learning_rate': 0.037958335792652884, 'depth': 10, 'l2_leaf_reg': 5.249934326457543, 'random_strength': 0.1195942459383017, 'border_count': 191, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5127095633720475}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:50:50,995] Trial 8 finished with value: 0.8276659310069938 and parameters: {'iterations': 286, 'learning_rate': 0.0011963380170058652, 'depth': 8, 'l2_leaf_reg': 3.82920382968694, 'random_strength': 0.5085706911647028, 'border_count': 235, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:50:58,542] Trial 9 finished with value: 0.8401656324483925 and parameters: {'iterations': 329, 'learning_rate': 0.20089716820180242, 'depth': 9, 'l2_leaf_reg': 6.700633808593811, 'random_strength': 0.8714605901877177, 'border_count': 212, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5550259622638384}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:01,540] Trial 10 finished with value: 0.8405014418994666 and parameters: {'iterations': 719, 'learning_rate': 0.01487610271655032, 'depth': 7, 'l2_leaf_reg': 1.1616568805333776, 'random_strength': 0.3316175144475764, 'border_count': 109, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.06168291818027871}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:14,613] Trial 11 finished with value: 0.8516810010905633 and parameters: {'iterations': 994, 'learning_rate': 0.012917179211596378, 'depth': 10, 'l2_leaf_reg': 9.323305812743335, 'random_strength': 0.9918179439690439, 'border_count': 150, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:17,994] Trial 12 finished with value: 0.8666958174737786 and parameters: {'iterations': 673, 'learning_rate': 0.040413976553836786, 'depth': 8, 'l2_leaf_reg': 9.732832987185276, 'random_strength': 0.7712176208336755, 'border_count': 112, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:21,295] Trial 13 finished with value: 0.8561323141884929 and parameters: {'iterations': 689, 'learning_rate': 0.028116734436234594, 'depth': 8, 'l2_leaf_reg': 8.622965110497992, 'random_strength': 0.6972126433588367, 'border_count': 105, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:24,242] Trial 14 finished with value: 0.8498607805516337 and parameters: {'iterations': 639, 'learning_rate': 0.007903108611506105, 'depth': 8, 'l2_leaf_reg': 7.568513465785312, 'random_strength': 0.7613592305412217, 'border_count': 107, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:26,682] Trial 15 finished with value: 0.8490790690315444 and parameters: {'iterations': 849, 'learning_rate': 0.07460851805073779, 'depth': 6, 'l2_leaf_reg': 4.636804996872561, 'random_strength': 0.3501128180175788, 'border_count': 88, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.17458226807840782}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:30,507] Trial 16 finished with value: 0.8456681982891661 and parameters: {'iterations': 967, 'learning_rate': 0.02410864407135131, 'depth': 4, 'l2_leaf_reg': 7.143133978432863, 'random_strength': 0.004740119653089181, 'border_count': 125, 'grow_policy': 'Depthwise', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:33,834] Trial 17 finished with value: 0.8479959145590813 and parameters: {'iterations': 521, 'learning_rate': 0.004847042133360555, 'depth': 9, 'l2_leaf_reg': 8.336526486113737, 'random_strength': 0.6665356393077191, 'border_count': 79, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:37,935] Trial 18 finished with value: 0.8458211962270291 and parameters: {'iterations': 750, 'learning_rate': 0.05526069979951117, 'depth': 8, 'l2_leaf_reg': 1.7389441401754073, 'random_strength': 0.41408436411211524, 'border_count': 130, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.9478505615596742}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:54,816] Trial 19 finished with value: 0.844895521283802 and parameters: {'iterations': 612, 'learning_rate': 0.12981967248393403, 'depth': 10, 'l2_leaf_reg': 3.168323051012435, 'random_strength': 0.22915558625596388, 'border_count': 59, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9447130840435278}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:51:58,387] Trial 20 finished with value: 0.8457959458521803 and parameters: {'iterations': 845, 'learning_rate': 0.020484126702874073, 'depth': 7, 'l2_leaf_reg': 4.512009792045429, 'random_strength': 0.7899944392951318, 'border_count': 167, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:02,549] Trial 21 finished with value: 0.8514209740592229 and parameters: {'iterations': 424, 'learning_rate': 0.16732114738054946, 'depth': 9, 'l2_leaf_reg': 9.214245263940985, 'random_strength': 0.9812415482005906, 'border_count': 165, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:04,804] Trial 22 finished with value: 0.853081311011836 and parameters: {'iterations': 222, 'learning_rate': 0.07513087818195711, 'depth': 9, 'l2_leaf_reg': 9.76086226925643, 'random_strength': 0.8783600419195761, 'border_count': 190, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:06,806] Trial 23 finished with value: 0.8548217195132669 and parameters: {'iterations': 424, 'learning_rate': 0.25224863038544326, 'depth': 8, 'l2_leaf_reg': 8.074576292521312, 'random_strength': 0.8330443727403698, 'border_count': 87, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:19,349] Trial 24 finished with value: 0.8221652464696192 and parameters: {'iterations': 788, 'learning_rate': 0.2794657971227901, 'depth': 10, 'l2_leaf_reg': 9.954891701796308, 'random_strength': 0.6322896152466358, 'border_count': 178, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:25,556] Trial 25 finished with value: 0.8571017707970474 and parameters: {'iterations': 699, 'learning_rate': 0.0371986397870493, 'depth': 9, 'l2_leaf_reg': 8.692537511683119, 'random_strength': 0.9209837129859562, 'border_count': 125, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:29,003] Trial 26 finished with value: 0.8573951527741376 and parameters: {'iterations': 644, 'learning_rate': 0.15384363905526083, 'depth': 8, 'l2_leaf_reg': 6.1429393561798795, 'random_strength': 0.7377985288390645, 'border_count': 140, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:31,430] Trial 27 finished with value: 0.8364319564789621 and parameters: {'iterations': 528, 'learning_rate': 0.009926445272982766, 'depth': 7, 'l2_leaf_reg': 7.245566435995375, 'random_strength': 0.45592429677996554, 'border_count': 216, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:42,661] Trial 28 finished with value: 0.8421770284286891 and parameters: {'iterations': 904, 'learning_rate': 0.05196606414628798, 'depth': 10, 'l2_leaf_reg': 9.156928965326935, 'random_strength': 0.5800987199100083, 'border_count': 250, 'grow_policy': 'Lossguide', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.5001899884993684}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:52:53,072] Trial 29 finished with value: 0.8618059590056595 and parameters: {'iterations': 566, 'learning_rate': 0.10828926993263603, 'depth': 9, 'l2_leaf_reg': 1.0288981967929598, 'random_strength': 0.2289378007641858, 'border_count': 53, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9119167051785454}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:00,883] Trial 30 finished with value: 0.8421849909131555 and parameters: {'iterations': 575, 'learning_rate': 0.0938399440668496, 'depth': 8, 'l2_leaf_reg': 1.050732118199871, 'random_strength': 0.17558624732941974, 'border_count': 32, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9135442104015083}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:09,660] Trial 31 finished with value: 0.8448602667981762 and parameters: {'iterations': 470, 'learning_rate': 0.19324529644127447, 'depth': 9, 'l2_leaf_reg': 2.4981142961421066, 'random_strength': 0.2373676011431326, 'border_count': 52, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.7968858041568786}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:16,987] Trial 32 finished with value: 0.8411782963684201 and parameters: {'iterations': 359, 'learning_rate': 0.13443649590324572, 'depth': 9, 'l2_leaf_reg': 1.6690264459300443, 'random_strength': 0.39305272944528874, 'border_count': 72, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8141415962139209}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:31,219] Trial 33 finished with value: 0.8361011071021919 and parameters: {'iterations': 670, 'learning_rate': 0.2970773146197149, 'depth': 9, 'l2_leaf_reg': 2.7715483700294476, 'random_strength': 0.10582301350288226, 'border_count': 97, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.9892364314060347}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:50,440] Trial 34 finished with value: 0.8460469926842994 and parameters: {'iterations': 783, 'learning_rate': 0.07480444706980986, 'depth': 10, 'l2_leaf_reg': 1.8513782966455246, 'random_strength': 0.27792411052194493, 'border_count': 49, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8532166081699745}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:55,687] Trial 35 finished with value: 0.8487757228479041 and parameters: {'iterations': 582, 'learning_rate': 0.033364841710331626, 'depth': 8, 'l2_leaf_reg': 4.004574530465485, 'random_strength': 0.9278896746830471, 'border_count': 69, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:53:57,316] Trial 36 finished with value: 0.8519884431411116 and parameters: {'iterations': 494, 'learning_rate': 0.11094955288768994, 'depth': 6, 'l2_leaf_reg': 5.78405020561629, 'random_strength': 0.04710503614160988, 'border_count': 158, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:54:01,799] Trial 37 finished with value: 0.851040125856336 and parameters: {'iterations': 210, 'learning_rate': 0.051917784277576096, 'depth': 9, 'l2_leaf_reg': 2.3242276920646763, 'random_strength': 0.19715620873896678, 'border_count': 47, 'grow_policy': 'Depthwise', 'bootstrap_type': 'Bernoulli', 'subsample': 0.7035133828351434}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:54:06,792] Trial 38 finished with value: 0.8383687372215011 and parameters: {'iterations': 733, 'learning_rate': 0.0015575866176113914, 'depth': 7, 'l2_leaf_reg': 3.2020014528624925, 'random_strength': 0.813122844498636, 'border_count': 34, 'grow_policy': 'Lossguide', 'bootstrap_type': 'MVS'}. Best is trial 6 with value: 0.8679340285391705.
[I 2025-04-15 10:54:11,485] Trial 39 finished with value: 0.858364609382692 and parameters: {'iterations': 342, 'learning_rate': 0.1104579273769457, 'depth': 10, 'l2_leaf_reg': 1.3599379956945654, 'random_strength': 0.2798163661523292, 'border_count': 137, 'grow_policy': 'SymmetricTree', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 0.46496931511742523}. Best is trial 6 with value: 0.8679340285391705.

best_params

{'iterations': 766,
 'learning_rate': 0.06394979414183315,
 'depth': 9,
 'l2_leaf_reg': 1.6664018656068134,
 'random_strength': 0.3584657285442726,
 'border_count': 57,
 'grow_policy': 'SymmetricTree',
 'bootstrap_type': 'MVS'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                              0
target                                                         no_fragmentation
model                             CatBoostClassifier_no_fragmentation_opt-model
holdout_test_f1_macro                                                  0.949653
holdout_test_accuracy_balanced                                         0.956818
holdout_test_roc_auc                                                       0.99
holdout_test_f1                                                        0.926829
holdout_test_accuracy                                                      0.96
cv_test_f1_macro_median                                                0.903571
cv_test_accuracy_balanced_median                                       0.887179
cv_test_roc_auc_median                                                 0.982906
cv_test_f1_median                                                      0.857143
cv_test_accuracy_median                                                0.925926
cv_test_precision_class_0_median                                       0.928571
cv_test_recall_class_0_median                                          0.974359
cv_test_f1_class_0_median                                                  0.95

# XGBoost

In [8]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 132/240 # For splashing

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [scale_pos_weight, 1.0]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-15 12:12:21,693] A new study created in memory with name: model_study
[I 2025-04-15 12:12:22,030] Trial 0 finished with value: 0.7629192547654765 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665}. Best is trial 0 with value: 0.7629192547654765.
[I 2025-04-15 12:12:22,833] Trial 1 finished with value: 0.392616568979092 and parameters: {'n_estimators': 723, 'learning_rate': 0.001124579825911934, 'max_depth': 10, 'min_child_weight': 17, 'gamma': 1.0616955533913808, 'subsample': 0.5909124836035503, 'colsample_bytree': 0.5917022549267169, 'reg_alpha': 0.016480446427978974, 'reg_lambda': 0.12561043700013558}. Best is trial 0 with value: 0.7629192547654765.
[I 2025-04-15 12:12:23,774] Trial 2 finished with value: 0.8577090282829423 and parameters: {'n_estimators': 460, 'learning_rate': 0.005265139631677754, 'max_depth': 7, 'min_child_weight': 3, 'gamma': 1.4607232426760908, 'subsample': 0.6831809216468459, 'colsample_bytree': 0.728034992108518, 'reg_alpha': 1.382623217936987, 'reg_lambda': 0.006290644294586149}. Best is trial 2 with value: 0.8577090282829423.
[I 2025-04-15 12:12:24,237] Trial 3 finished with value: 0.7494757886359936 and parameters: {'n_estimators': 539, 'learning_rate': 0.029341527565000736, 'max_depth': 3, 'min_child_weight': 13, 'gamma': 0.8526206184364576, 'subsample': 0.5325257964926398, 'colsample_bytree': 0.9744427686266666, 'reg_alpha': 7.2866537374910445, 'reg_lambda': 1.7123375973163988}. Best is trial 2 with value: 0.8577090282829423.
[I 2025-04-15 12:12:24,756] Trial 4 finished with value: 0.4121178477514705 and parameters: {'n_estimators': 339, 'learning_rate': 0.0017456037635797405, 'max_depth': 8, 'min_child_weight': 9, 'gamma': 0.6101911742238941, 'subsample': 0.7475884550556351, 'colsample_bytree': 0.5171942605576092, 'reg_alpha': 4.337920697490942, 'reg_lambda': 0.010842262717330166}. Best is trial 2 with value: 0.8577090282829423.
[I 2025-04-15 12:12:25,881] Trial 5 finished with value: 0.7556935982369002 and parameters: {'n_estimators': 680, 'learning_rate': 0.005917607170144194, 'max_depth': 7, 'min_child_weight': 11, 'gamma': 0.9242722776276352, 'subsample': 0.9847923138822793, 'colsample_bytree': 0.8875664116805573, 'reg_alpha': 5.727904470799623, 'reg_lambda': 3.7958531426706403}. Best is trial 2 with value: 0.8577090282829423.
[I 2025-04-15 12:12:26,583] Trial 6 finished with value: 0.8606269098722713 and parameters: {'n_estimators': 618, 'learning_rate': 0.19212959255386391, 'max_depth': 3, 'min_child_weight': 4, 'gamma': 0.22613644455269033, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 0.01217295809836997, 'reg_lambda': 2.0651425578959257}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:27,153] Trial 7 finished with value: 0.8168588864001975 and parameters: {'n_estimators': 389, 'learning_rate': 0.0049648810171066555, 'max_depth': 7, 'min_child_weight': 3, 'gamma': 4.010984903770199, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586, 'reg_alpha': 1.2273800987852967, 'reg_lambda': 0.0062353771356731605}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:27,266] Trial 8 finished with value: 0.7219779136636572 and parameters: {'n_estimators': 55, 'learning_rate': 0.10471209213501693, 'max_depth': 8, 'min_child_weight': 15, 'gamma': 3.8563517334297286, 'subsample': 0.5370223258670452, 'colsample_bytree': 0.6792328642721364, 'reg_alpha': 0.0029072088906598446, 'reg_lambda': 2.8340904295147746}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:28,042] Trial 9 finished with value: 0.8184567859490703 and parameters: {'n_estimators': 642, 'learning_rate': 0.006601984958164864, 'max_depth': 3, 'min_child_weight': 7, 'gamma': 1.6259166101337352, 'subsample': 0.864803089169032, 'colsample_bytree': 0.8187787356776066, 'reg_alpha': 3.53875886477924, 'reg_lambda': 0.0774211647399625}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:28,822] Trial 10 finished with value: 0.8484029147389912 and parameters: {'n_estimators': 956, 'learning_rate': 0.050904131025638163, 'max_depth': 5, 'min_child_weight': 1, 'gamma': 2.828065453407016, 'subsample': 0.6808837830192477, 'colsample_bytree': 0.6338413443561857, 'reg_alpha': 0.03713740624438138, 'reg_lambda': 0.47391191549480033}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:29,498] Trial 11 finished with value: 0.859657214255109 and parameters: {'n_estimators': 875, 'learning_rate': 0.28720855757427693, 'max_depth': 5, 'min_child_weight': 5, 'gamma': 2.1717813587820562, 'subsample': 0.6712579968688783, 'colsample_bytree': 0.7386064674702648, 'reg_alpha': 0.268371934144002, 'reg_lambda': 0.0012570339521301734}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:30,249] Trial 12 finished with value: 0.8485723152965919 and parameters: {'n_estimators': 951, 'learning_rate': 0.25640850319779096, 'max_depth': 5, 'min_child_weight': 6, 'gamma': 2.343526094439212, 'subsample': 0.6766980691634803, 'colsample_bytree': 0.7985092752876581, 'reg_alpha': 0.19382554671360513, 'reg_lambda': 0.0010552033488306432}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:30,899] Trial 13 finished with value: 0.7591736592139486 and parameters: {'n_estimators': 844, 'learning_rate': 0.09925694138663065, 'max_depth': 5, 'min_child_weight': 20, 'gamma': 0.053826310761716734, 'subsample': 0.8095839387020463, 'colsample_bytree': 0.7253010287172165, 'reg_alpha': 0.3101094635186756, 'reg_lambda': 8.657959303243224}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:31,574] Trial 14 finished with value: 0.8093975544611238 and parameters: {'n_estimators': 824, 'learning_rate': 0.1398308373769709, 'max_depth': 4, 'min_child_weight': 6, 'gamma': 4.9817012427718375, 'subsample': 0.6286191428179753, 'colsample_bytree': 0.805085811834259, 'reg_alpha': 0.0045943610934533665, 'reg_lambda': 0.026760320559088738}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:31,837] Trial 15 finished with value: 0.8517751012653331 and parameters: {'n_estimators': 161, 'learning_rate': 0.04357978309708971, 'max_depth': 4, 'min_child_weight': 4, 'gamma': 2.2427402844503805, 'subsample': 0.7601394287385591, 'colsample_bytree': 0.66592726899217, 'reg_alpha': 0.0010809068839145437, 'reg_lambda': 0.6669467286922344}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:32,387] Trial 16 finished with value: 0.8314522231728818 and parameters: {'n_estimators': 561, 'learning_rate': 0.021138946237959894, 'max_depth': 4, 'min_child_weight': 9, 'gamma': 3.1466433301490775, 'subsample': 0.8754986180062629, 'colsample_bytree': 0.8671553784997497, 'reg_alpha': 0.06361254832080036, 'reg_lambda': 0.001129059573387675}. Best is trial 6 with value: 0.8606269098722713.
[I 2025-04-15 12:12:33,244] Trial 17 finished with value: 0.8653762250057367 and parameters: {'n_estimators': 823, 'learning_rate': 0.2773104499774662, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 0.12638644071503213, 'subsample': 0.7529565028751162, 'colsample_bytree': 0.5820277679886149, 'reg_alpha': 0.010637210556042356, 'reg_lambda': 0.03585001325104272}. Best is trial 17 with value: 0.8653762250057367.
[I 2025-04-15 12:12:34,448] Trial 18 finished with value: 0.8961601204691112 and parameters: {'n_estimators': 744, 'learning_rate': 0.06639317158945211, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 0.03255073148340629, 'subsample': 0.7507285077111834, 'colsample_bytree': 0.5816808853055009, 'reg_alpha': 0.01473065249671296, 'reg_lambda': 0.042306118178481435}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:35,142] Trial 19 finished with value: 0.8502416372034638 and parameters: {'n_estimators': 765, 'learning_rate': 0.06690841025507702, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 1.5920355172166802, 'subsample': 0.7569405787682556, 'colsample_bytree': 0.5754833253487162, 'reg_alpha': 0.015491466240300787, 'reg_lambda': 0.03685661100106874}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:37,072] Trial 20 finished with value: 0.8727594140326903 and parameters: {'n_estimators': 767, 'learning_rate': 0.012662718259786055, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 0.07510605812843618, 'subsample': 0.8425054101541488, 'colsample_bytree': 0.5883019650024283, 'reg_alpha': 0.004769789373318175, 'reg_lambda': 0.02326049338350763}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:39,166] Trial 21 finished with value: 0.8760451589943509 and parameters: {'n_estimators': 787, 'learning_rate': 0.012559988080870617, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 0.0012137174869190914, 'subsample': 0.8593697666461243, 'colsample_bytree': 0.5999112304688664, 'reg_alpha': 0.005399657967205395, 'reg_lambda': 0.022853494243199296}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:40,740] Trial 22 finished with value: 0.8611704349476772 and parameters: {'n_estimators': 748, 'learning_rate': 0.011863278182855116, 'max_depth': 9, 'min_child_weight': 1, 'gamma': 0.4141399100066613, 'subsample': 0.9255066085194732, 'colsample_bytree': 0.6246789461602623, 'reg_alpha': 0.0033233679316301626, 'reg_lambda': 0.01815005826463889}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:42,478] Trial 23 finished with value: 0.8442248563516593 and parameters: {'n_estimators': 895, 'learning_rate': 0.011024531011592389, 'max_depth': 9, 'min_child_weight': 3, 'gamma': 0.0497897982923897, 'subsample': 0.8236696374617571, 'colsample_bytree': 0.502461842613607, 'reg_alpha': 0.0010922432855912897, 'reg_lambda': 0.003828803265854853}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:43,320] Trial 24 finished with value: 0.8497520228444996 and parameters: {'n_estimators': 760, 'learning_rate': 0.014822742751460198, 'max_depth': 9, 'min_child_weight': 8, 'gamma': 1.3628892947195954, 'subsample': 0.9076405595035453, 'colsample_bytree': 0.5492957175049129, 'reg_alpha': 0.006236559695520453, 'reg_lambda': 0.08774548241150755}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:46,509] Trial 25 finished with value: 0.8480754701564049 and parameters: {'n_estimators': 999, 'learning_rate': 0.002737120915387913, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 0.49473298133504007, 'subsample': 0.7962842470428295, 'colsample_bytree': 0.6178156701849394, 'reg_alpha': 0.032970198834447156, 'reg_lambda': 0.04939485710755689}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:47,250] Trial 26 finished with value: 0.848858672635915 and parameters: {'n_estimators': 612, 'learning_rate': 0.020814005187243186, 'max_depth': 9, 'min_child_weight': 5, 'gamma': 1.1602899074314243, 'subsample': 0.9666208092036277, 'colsample_bytree': 0.5632613446856178, 'reg_alpha': 0.002089428562858691, 'reg_lambda': 0.01598483515486672}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:48,313] Trial 27 finished with value: 0.8508437801757084 and parameters: {'n_estimators': 708, 'learning_rate': 0.008734999052548311, 'max_depth': 10, 'min_child_weight': 3, 'gamma': 1.8607765228464792, 'subsample': 0.8524793412264692, 'colsample_bytree': 0.6557859957661847, 'reg_alpha': 0.0057021402191186205, 'reg_lambda': 0.14873337242115975}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:49,468] Trial 28 finished with value: 0.8614740683202526 and parameters: {'n_estimators': 893, 'learning_rate': 0.03162784548662038, 'max_depth': 8, 'min_child_weight': 2, 'gamma': 0.48243075231867105, 'subsample': 0.9116145542762285, 'colsample_bytree': 0.6068606779008807, 'reg_alpha': 0.03477205022135302, 'reg_lambda': 0.0023522950823440035}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:50,263] Trial 29 finished with value: 0.731273034638784 and parameters: {'n_estimators': 445, 'learning_rate': 0.0037823541450290902, 'max_depth': 9, 'min_child_weight': 5, 'gamma': 0.7942794532994119, 'subsample': 0.7178799214605698, 'colsample_bytree': 0.5380556014639326, 'reg_alpha': 0.0019304249117808494, 'reg_lambda': 0.251747205850571}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:51,053] Trial 30 finished with value: 0.7952724353537359 and parameters: {'n_estimators': 777, 'learning_rate': 0.02759449587254828, 'max_depth': 10, 'min_child_weight': 13, 'gamma': 0.005608290011885446, 'subsample': 0.841713015425974, 'colsample_bytree': 0.5356872257473971, 'reg_alpha': 0.07298969619452213, 'reg_lambda': 0.011070759889398532}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:52,029] Trial 31 finished with value: 0.8729467187515493 and parameters: {'n_estimators': 817, 'learning_rate': 0.07068169771362866, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 0.3800461100556932, 'subsample': 0.7874938440208096, 'colsample_bytree': 0.5825376013968124, 'reg_alpha': 0.014098019863772605, 'reg_lambda': 0.053339390653933436}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:53,119] Trial 32 finished with value: 0.8720398669826286 and parameters: {'n_estimators': 689, 'learning_rate': 0.06698581149210302, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 0.4109227202135435, 'subsample': 0.7905756912576009, 'colsample_bytree': 0.5945631980490202, 'reg_alpha': 0.008470020714926176, 'reg_lambda': 0.06675532454492798}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:54,304] Trial 33 finished with value: 0.8456595668333425 and parameters: {'n_estimators': 803, 'learning_rate': 0.04466417542845935, 'max_depth': 8, 'min_child_weight': 4, 'gamma': 1.1726940410375881, 'subsample': 0.8806042326108677, 'colsample_bytree': 0.6479416926401318, 'reg_alpha': 0.020590623832244925, 'reg_lambda': 0.1721663748342626}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:55,820] Trial 34 finished with value: 0.8577965393537151 and parameters: {'n_estimators': 937, 'learning_rate': 0.013458741216943761, 'max_depth': 6, 'min_child_weight': 2, 'gamma': 0.7411403148031555, 'subsample': 0.7207497344629227, 'colsample_bytree': 0.56328641093705, 'reg_alpha': 0.008424434746817528, 'reg_lambda': 0.016812515059213447}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:57,604] Trial 35 finished with value: 0.8655607748013833 and parameters: {'n_estimators': 575, 'learning_rate': 0.009076097646851891, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 0.2874137937892963, 'subsample': 0.7788133671612727, 'colsample_bytree': 0.7112126067319047, 'reg_alpha': 0.02108347669955912, 'reg_lambda': 0.008496173921869628}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:58,417] Trial 36 finished with value: 0.8486130724265362 and parameters: {'n_estimators': 679, 'learning_rate': 0.03359978681634636, 'max_depth': 7, 'min_child_weight': 3, 'gamma': 1.0056682385272566, 'subsample': 0.8291568690006335, 'colsample_bytree': 0.5021345958158536, 'reg_alpha': 0.003924277515327491, 'reg_lambda': 0.02411587478982934}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:58,873] Trial 37 finished with value: 0.7619820003552863 and parameters: {'n_estimators': 498, 'learning_rate': 0.020217175786656674, 'max_depth': 8, 'min_child_weight': 18, 'gamma': 0.6421721251138064, 'subsample': 0.7150987021416679, 'colsample_bytree': 0.5896031971120484, 'reg_alpha': 0.11328088385432443, 'reg_lambda': 0.00422863460581624}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:12:59,267] Trial 38 finished with value: 0.8335746788728932 and parameters: {'n_estimators': 313, 'learning_rate': 0.17486750838108597, 'max_depth': 9, 'min_child_weight': 10, 'gamma': 0.3142139383095631, 'subsample': 0.9381251166433981, 'colsample_bytree': 0.7699978313263548, 'reg_alpha': 0.0018618013884854495, 'reg_lambda': 0.04611325248330677}. Best is trial 18 with value: 0.8961601204691112.
[I 2025-04-15 12:13:00,011] Trial 39 finished with value: 0.8588912312895538 and parameters: {'n_estimators': 732, 'learning_rate': 0.08256175604133713, 'max_depth': 7, 'min_child_weight': 4, 'gamma': 0.7439106989520275, 'subsample': 0.8899538249796326, 'colsample_bytree': 0.6906439405008131, 'reg_alpha': 0.02462229399339839, 'reg_lambda': 0.4486928712584463}. Best is trial 18 with value: 0.8961601204691112.

best_params

{'n_estimators': 744,
 'learning_rate': 0.06639317158945211,
 'max_depth': 10,
 'min_child_weight': 1,
 'gamma': 0.03255073148340629,
 'subsample': 0.7507285077111834,
 'colsample_bytree': 0.5816808853055009,
 'reg_alpha': 0.01473065249671296,
 'reg_lambda': 0.042306118178481435}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                  0
target                                                    splashing
model                             XGBClassifier_splashing_opt-model
holdout_test_f1_macro                                      0.868703
holdout_test_accuracy_balanced                             0.865741
holdout_test_roc_auc                                       0.945216
holdout_test_f1                                            0.907216
holdout_test_accuracy                                          0.88
cv_test_f1_macro_median                                    0.860788
cv_test_accuracy_balanced_median                           0.873839
cv_test_roc_auc_median                                     0.942724
cv_test_f1_median                                          0.898551
cv_test_accuracy_median                                    0.867925
cv_test_precision_class_0_median                           0.789474
cv_test_recall_class_0_median                              0.842105
cv_test_f1_class_0_median                                  0.829268

In [9]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def xgboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # https://xgboost.readthedocs.io/en/latest/parameter.html
    # sum(negative instances) / sum(positive instances)
    scale_pos_weight = 273/99 # For no_fragmentation

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [1.0, scale_pos_weight]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=xgboost_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-15 12:13:27,517] A new study created in memory with name: model_study
[I 2025-04-15 12:13:27,943] Trial 0 finished with value: 0.6266580841331084 and parameters: {'n_estimators': 406, 'learning_rate': 0.22648248189516848, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.7800932022121826, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998, 'reg_alpha': 2.9154431891537547, 'reg_lambda': 0.2537815508265665, 'scale_pos_weight': 1.0}. Best is trial 0 with value: 0.6266580841331084.
[I 2025-04-15 12:13:29,258] Trial 1 finished with value: 0.8286994662609282 and parameters: {'n_estimators': 972, 'learning_rate': 0.11536162338241392, 'max_depth': 4, 'min_child_weight': 4, 'gamma': 0.9170225492671691, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119, 'reg_alpha': 0.05342937261279776, 'reg_lambda': 0.014618962793704957, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8286994662609282.
[I 2025-04-15 12:13:29,753] Trial 2 finished with value: 0.6221645533266225 and parameters: {'n_estimators': 327, 'learning_rate': 0.008082071885709252, 'max_depth': 6, 'min_child_weight': 16, 'gamma': 0.9983689107917987, 'subsample': 0.7571172192068059, 'colsample_bytree': 0.7962072844310213, 'reg_alpha': 0.0015339162591163618, 'reg_lambda': 0.26926469100861794, 'scale_pos_weight': 1.0}. Best is trial 1 with value: 0.8286994662609282.
[I 2025-04-15 12:13:30,838] Trial 3 finished with value: 0.8303085538830206 and parameters: {'n_estimators': 952, 'learning_rate': 0.24659691172104828, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 0.48836057003191935, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 0.003077180271250686, 'reg_lambda': 0.09565499215943825, 'scale_pos_weight': 2.757575757575758}. Best is trial 3 with value: 0.8303085538830206.
[I 2025-04-15 12:13:31,145] Trial 4 finished with value: 0.6339845468471192 and parameters: {'n_estimators': 296, 'learning_rate': 0.043767126303409544, 'max_depth': 5, 'min_child_weight': 11, 'gamma': 2.7335513967163982, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9847923138822793, 'reg_alpha': 1.2604664585649468, 'reg_lambda': 5.727904470799623, 'scale_pos_weight': 1.0}. Best is trial 3 with value: 0.8303085538830206.
[I 2025-04-15 12:13:32,966] Trial 5 finished with value: 0.8360710076714543 and parameters: {'n_estimators': 926, 'learning_rate': 0.0016565580440884786, 'max_depth': 4, 'min_child_weight': 1, 'gamma': 1.6266516538163218, 'subsample': 0.6943386448447411, 'colsample_bytree': 0.6356745158869479, 'reg_alpha': 2.0651425578959257, 'reg_lambda': 0.026730883107816707, 'scale_pos_weight': 2.757575757575758}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:33,191] Trial 6 finished with value: 0.7291920297094256 and parameters: {'n_estimators': 184, 'learning_rate': 0.09708210658008556, 'max_depth': 3, 'min_child_weight': 20, 'gamma': 3.861223846483287, 'subsample': 0.5993578407670862, 'colsample_bytree': 0.5027610585618012, 'reg_alpha': 1.8274508859816028, 'reg_lambda': 0.6720930050156113, 'scale_pos_weight': 2.757575757575758}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:33,346] Trial 7 finished with value: 0.4233049487844008 and parameters: {'n_estimators': 120, 'learning_rate': 0.007726148927746463, 'max_depth': 3, 'min_child_weight': 18, 'gamma': 3.1164906341377896, 'subsample': 0.6654490124263246, 'colsample_bytree': 0.5317791751430119, 'reg_alpha': 0.017535949529764425, 'reg_lambda': 0.01998634077852888, 'scale_pos_weight': 1.0}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:34,203] Trial 8 finished with value: 0.6256902021771308 and parameters: {'n_estimators': 893, 'learning_rate': 0.014782014634883782, 'max_depth': 3, 'min_child_weight': 15, 'gamma': 3.803925243084487, 'subsample': 0.7806385987847482, 'colsample_bytree': 0.8854835899772805, 'reg_alpha': 0.09444574254983566, 'reg_lambda': 0.12329098365270515, 'scale_pos_weight': 1.0}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:34,504] Trial 9 finished with value: 0.4233049487844008 and parameters: {'n_estimators': 152, 'learning_rate': 0.0011963380170058652, 'max_depth': 8, 'min_child_weight': 7, 'gamma': 2.542853455823514, 'subsample': 0.9537832369630466, 'colsample_bytree': 0.6246461145744375, 'reg_alpha': 0.04380580767905655, 'reg_lambda': 1.0524574681335637, 'scale_pos_weight': 1.0}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:35,895] Trial 10 finished with value: 0.808636781251134 and parameters: {'n_estimators': 680, 'learning_rate': 0.0010347984019709346, 'max_depth': 6, 'min_child_weight': 1, 'gamma': 1.658087572237882, 'subsample': 0.8951735669692689, 'colsample_bytree': 0.628963476300746, 'reg_alpha': 7.938909678741384, 'reg_lambda': 0.0018066338345909892, 'scale_pos_weight': 2.757575757575758}. Best is trial 5 with value: 0.8360710076714543.
[I 2025-04-15 12:13:37,550] Trial 11 finished with value: 0.8470763586441498 and parameters: {'n_estimators': 733, 'learning_rate': 0.00326986275218858, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.26482042909391795, 'subsample': 0.83985573444758, 'colsample_bytree': 0.662427129308605, 'reg_alpha': 0.001227894827707895, 'reg_lambda': 0.024939020454194542, 'scale_pos_weight': 2.757575757575758}. Best is trial 11 with value: 0.8470763586441498.
[I 2025-04-15 12:13:39,956] Trial 12 finished with value: 0.8323885671122232 and parameters: {'n_estimators': 692, 'learning_rate': 0.0033317708204991556, 'max_depth': 10, 'min_child_weight': 1, 'gamma': 0.0912614311925134, 'subsample': 0.7064320329894239, 'colsample_bytree': 0.6479781298732975, 'reg_alpha': 0.4089959430771127, 'reg_lambda': 0.012863061078217521, 'scale_pos_weight': 2.757575757575758}. Best is trial 11 with value: 0.8470763586441498.
[I 2025-04-15 12:13:41,661] Trial 13 finished with value: 0.8467220663843192 and parameters: {'n_estimators': 763, 'learning_rate': 0.002903337663297932, 'max_depth': 7, 'min_child_weight': 5, 'gamma': 1.6554904480608155, 'subsample': 0.8223368426340427, 'colsample_bytree': 0.6737666799678391, 'reg_alpha': 0.0071540297573690625, 'reg_lambda': 0.0016801465443871141, 'scale_pos_weight': 2.757575757575758}. Best is trial 11 with value: 0.8470763586441498.
[I 2025-04-15 12:13:43,070] Trial 14 finished with value: 0.8522046371645341 and parameters: {'n_estimators': 704, 'learning_rate': 0.0037965659825255284, 'max_depth': 10, 'min_child_weight': 7, 'gamma': 1.6083643902139688, 'subsample': 0.8377971406658062, 'colsample_bytree': 0.705822200491805, 'reg_alpha': 0.0066284781961220484, 'reg_lambda': 0.0011065136021091012, 'scale_pos_weight': 2.757575757575758}. Best is trial 14 with value: 0.8522046371645341.
[I 2025-04-15 12:13:44,355] Trial 15 finished with value: 0.8596370112030787 and parameters: {'n_estimators': 551, 'learning_rate': 0.004871734844835071, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.023700598265445905, 'subsample': 0.9457256016582685, 'colsample_bytree': 0.8060141072077395, 'reg_alpha': 0.0010522354581821041, 'reg_lambda': 0.0043401229848273465, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:45,199] Trial 16 finished with value: 0.8289255714690432 and parameters: {'n_estimators': 561, 'learning_rate': 0.007015538296725006, 'max_depth': 9, 'min_child_weight': 9, 'gamma': 4.475097752695978, 'subsample': 0.9836662305664101, 'colsample_bytree': 0.8396408109536446, 'reg_alpha': 0.009539687528688286, 'reg_lambda': 0.0043138591755586715, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:45,833] Trial 17 finished with value: 0.8061157374801426 and parameters: {'n_estimators': 573, 'learning_rate': 0.02886394893896448, 'max_depth': 9, 'min_child_weight': 13, 'gamma': 1.8849798538318918, 'subsample': 0.909268658553563, 'colsample_bytree': 0.9095336881172504, 'reg_alpha': 0.004073110521119694, 'reg_lambda': 0.0010656275591537643, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:46,512] Trial 18 finished with value: 0.8385402086973244 and parameters: {'n_estimators': 429, 'learning_rate': 0.017097637376356917, 'max_depth': 10, 'min_child_weight': 9, 'gamma': 2.159288929998385, 'subsample': 0.8921962199415852, 'colsample_bytree': 0.7231610042250182, 'reg_alpha': 0.01898345772219757, 'reg_lambda': 0.004767888795794927, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:47,864] Trial 19 finished with value: 0.8429147622700403 and parameters: {'n_estimators': 828, 'learning_rate': 0.005972083485553463, 'max_depth': 8, 'min_child_weight': 9, 'gamma': 1.16508175243975, 'subsample': 0.9476052770225172, 'colsample_bytree': 0.8173036825063664, 'reg_alpha': 0.0011129709953152656, 'reg_lambda': 0.00514047785544291, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:49,200] Trial 20 finished with value: 0.8385562689033252 and parameters: {'n_estimators': 614, 'learning_rate': 0.0021327010820858566, 'max_depth': 7, 'min_child_weight': 3, 'gamma': 3.4183521089609488, 'subsample': 0.8158857447723741, 'colsample_bytree': 0.8812851748293707, 'reg_alpha': 0.37203656985849154, 'reg_lambda': 0.0029720466312085293, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:50,942] Trial 21 finished with value: 0.8478251355073555 and parameters: {'n_estimators': 765, 'learning_rate': 0.003802977186662303, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.06535321025830115, 'subsample': 0.8589969793121721, 'colsample_bytree': 0.5748265164090642, 'reg_alpha': 0.00244729321696737, 'reg_lambda': 0.05609816504893187, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:51,880] Trial 22 finished with value: 0.8511431596317056 and parameters: {'n_estimators': 454, 'learning_rate': 0.0047492281251342245, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.021671994018521337, 'subsample': 0.8755441254912064, 'colsample_bytree': 0.5797969258772578, 'reg_alpha': 0.003026157854921755, 'reg_lambda': 0.06700656228922967, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:52,770] Trial 23 finished with value: 0.8425064488666282 and parameters: {'n_estimators': 463, 'learning_rate': 0.011313483259043734, 'max_depth': 9, 'min_child_weight': 8, 'gamma': 0.5899129826509302, 'subsample': 0.9987395052125416, 'colsample_bytree': 0.7144395274348873, 'reg_alpha': 0.0058043432902195585, 'reg_lambda': 0.00835735342126824, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:53,443] Trial 24 finished with value: 0.7578346165029727 and parameters: {'n_estimators': 504, 'learning_rate': 0.004765227058770545, 'max_depth': 10, 'min_child_weight': 10, 'gamma': 1.2803129281059475, 'subsample': 0.5001310561523564, 'colsample_bytree': 0.7630819261872134, 'reg_alpha': 0.023237835620144472, 'reg_lambda': 5.852962828259753, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:54,516] Trial 25 finished with value: 0.821027364272922 and parameters: {'n_estimators': 629, 'learning_rate': 0.00206696514629956, 'max_depth': 9, 'min_child_weight': 13, 'gamma': 0.4848674152437216, 'subsample': 0.932275184634352, 'colsample_bytree': 0.5875628007628848, 'reg_alpha': 0.003219099570238166, 'reg_lambda': 0.001816771550989588, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:55,520] Trial 26 finished with value: 0.8220098365618063 and parameters: {'n_estimators': 514, 'learning_rate': 0.03234366496474334, 'max_depth': 8, 'min_child_weight': 3, 'gamma': 0.01288147347707902, 'subsample': 0.7995197872145817, 'colsample_bytree': 0.6953099721459401, 'reg_alpha': 0.010978250508484447, 'reg_lambda': 0.0592122673365211, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:56,095] Trial 27 finished with value: 0.8285651188976038 and parameters: {'n_estimators': 357, 'learning_rate': 0.009870954480695665, 'max_depth': 10, 'min_child_weight': 11, 'gamma': 2.1427336032155417, 'subsample': 0.8678306075592715, 'colsample_bytree': 0.5894363245398411, 'reg_alpha': 0.0016648164168517896, 'reg_lambda': 0.0011000027119649842, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:57,502] Trial 28 finished with value: 0.8410000278596114 and parameters: {'n_estimators': 838, 'learning_rate': 0.004763522089889227, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 1.3439945418662806, 'subsample': 0.7417902398612948, 'colsample_bytree': 0.7907500821834691, 'reg_alpha': 0.004658918055079416, 'reg_lambda': 2.4042376351904244, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:57,842] Trial 29 finished with value: 0.819232130075809 and parameters: {'n_estimators': 249, 'learning_rate': 0.024508626941589663, 'max_depth': 7, 'min_child_weight': 13, 'gamma': 4.991417930830018, 'subsample': 0.9145878898452796, 'colsample_bytree': 0.5443803909595528, 'reg_alpha': 0.0010227923345850376, 'reg_lambda': 0.4730062870626852, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:13:58,868] Trial 30 finished with value: 0.8188639607549659 and parameters: {'n_estimators': 420, 'learning_rate': 0.0018330087419368354, 'max_depth': 8, 'min_child_weight': 5, 'gamma': 0.7418928392638019, 'subsample': 0.8769111401306707, 'colsample_bytree': 0.9778939527788821, 'reg_alpha': 0.24966688898475542, 'reg_lambda': 0.009809872359848294, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:00,724] Trial 31 finished with value: 0.8474033517169948 and parameters: {'n_estimators': 786, 'learning_rate': 0.004550808958466309, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.2733382160749771, 'subsample': 0.8557325725513988, 'colsample_bytree': 0.583233767181973, 'reg_alpha': 0.002289339124384603, 'reg_lambda': 0.05176486215177102, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:02,105] Trial 32 finished with value: 0.8324721022077223 and parameters: {'n_estimators': 651, 'learning_rate': 0.0031000863203574066, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.8478655540380782, 'subsample': 0.959848230059775, 'colsample_bytree': 0.5621070451328753, 'reg_alpha': 0.0027293159958277423, 'reg_lambda': 0.1846726191189415, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:03,305] Trial 33 finished with value: 0.838632874149632 and parameters: {'n_estimators': 580, 'learning_rate': 0.012410289071591763, 'max_depth': 9, 'min_child_weight': 4, 'gamma': 0.3265298945723689, 'subsample': 0.7693650668890978, 'colsample_bytree': 0.7476248507070489, 'reg_alpha': 0.002045349457206204, 'reg_lambda': 0.04668133326074039, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:03,483] Trial 34 finished with value: 0.4233049487844008 and parameters: {'n_estimators': 54, 'learning_rate': 0.004318607177215197, 'max_depth': 10, 'min_child_weight': 6, 'gamma': 0.011177337862421206, 'subsample': 0.9260716237544139, 'colsample_bytree': 0.5030817162120989, 'reg_alpha': 0.010147765640844476, 'reg_lambda': 0.0931637100732862, 'scale_pos_weight': 1.0}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:05,265] Trial 35 finished with value: 0.834048763597747 and parameters: {'n_estimators': 732, 'learning_rate': 0.0024422686306258515, 'max_depth': 9, 'min_child_weight': 10, 'gamma': 1.045565849807305, 'subsample': 0.850074684231123, 'colsample_bytree': 0.6065452619952925, 'reg_alpha': 0.030023207903718204, 'reg_lambda': 0.002685935487197064, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:06,102] Trial 36 finished with value: 0.4233049487844008 and parameters: {'n_estimators': 477, 'learning_rate': 0.001373735524460989, 'max_depth': 10, 'min_child_weight': 8, 'gamma': 0.7499044891739313, 'subsample': 0.8002236471798628, 'colsample_bytree': 0.5595822004051048, 'reg_alpha': 0.0019678712418498266, 'reg_lambda': 0.23442111183958764, 'scale_pos_weight': 1.0}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:06,750] Trial 37 finished with value: 0.8402531463529955 and parameters: {'n_estimators': 367, 'learning_rate': 0.07038942343231833, 'max_depth': 5, 'min_child_weight': 4, 'gamma': 0.47525854435241965, 'subsample': 0.7329095184276322, 'colsample_bytree': 0.8459413411219282, 'reg_alpha': 0.004159349352075447, 'reg_lambda': 0.007863710881743478, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:08,084] Trial 38 finished with value: 0.8239428297156783 and parameters: {'n_estimators': 983, 'learning_rate': 0.006823960676371214, 'max_depth': 8, 'min_child_weight': 12, 'gamma': 0.9510463813796184, 'subsample': 0.8795593184959654, 'colsample_bytree': 0.7827583232793576, 'reg_alpha': 0.01499980418769357, 'reg_lambda': 0.4219023409068694, 'scale_pos_weight': 2.757575757575758}. Best is trial 15 with value: 0.8596370112030787.
[I 2025-04-15 12:14:08,889] Trial 39 finished with value: 0.7849018875175997 and parameters: {'n_estimators': 883, 'learning_rate': 0.18039732898294158, 'max_depth': 9, 'min_child_weight': 7, 'gamma': 2.811394605604973, 'subsample': 0.9730038470155306, 'colsample_bytree': 0.6960679771808506, 'reg_alpha': 0.006820213132210325, 'reg_lambda': 0.029914813244593035, 'scale_pos_weight': 1.0}. Best is trial 15 with value: 0.8596370112030787.

best_params

{'n_estimators': 551,
 'learning_rate': 0.004871734844835071,
 'max_depth': 10,
 'min_child_weight': 8,
 'gamma': 0.023700598265445905,
 'subsample': 0.9457256016582685,
 'colsample_bytree': 0.8060141072077395,
 'reg_alpha': 0.0010522354581821041,
 'reg_lambda': 0.0043401229848273465,
 'scale_pos_weight': 2.757575757575758}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                         0
target                                                    no_fragmentation
model                             XGBClassifier_no_fragmentation_opt-model
holdout_test_f1_macro                                             0.891551
holdout_test_accuracy_balanced                                    0.936364
holdout_test_roc_auc                                              0.984545
holdout_test_f1                                                   0.851064
holdout_test_accuracy                                             0.906667
cv_test_f1_macro_median                                            0.90293
cv_test_accuracy_balanced_median                                  0.910256
cv_test_roc_auc_median                                            0.954212
cv_test_f1_median                                                 0.857143
cv_test_accuracy_median                                           0.924528
cv_test_precision_class_0_median                                       1.0
cv_test_recall_class_0_median                                     0.897436
cv_test_f1_class_0_median                                         0.945946

# AdaBoost

In [ ]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}
# params_to_process = ['gamma']
params_to_process = None

def adaboost_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):

    # scale_pos_weight = 132/240 # For splashing

    suggested_estimator_params = {
        "n_estimators": trial.suggest_int("n_estimators", 50, 1000),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 20),
        "gamma": trial.suggest_float("gamma", 0, 5),
        "subsample": trial.suggest_float("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True), # Catboost l2_leaf_reg
        # "scale_pos_weight": trial.suggest_categorical("scale_pos_weight", [scale_pos_weight, 1.0]),
    }

    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params,
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=adaboost_objective,
    n_trials=n_trials,
)

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:34,  1.56it/s]

Progress: 1/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:34,  1.52it/s]

Progress: 2/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:33,  1.52it/s]

Progress: 3/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:32,  1.53it/s]

Progress: 4/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:03<00:32,  1.52it/s]

Progress: 5/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:31,  1.52it/s]

Progress: 6/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:30,  1.53it/s]

Progress: 7/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:05<00:29,  1.54it/s]

Progress: 8/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:29,  1.53it/s]

Progress: 9/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:06<00:28,  1.53it/s]

Progress: 10/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:07<00:28,  1.52it/s]

Progress: 11/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:27,  1.52it/s]

Progress: 12/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:08<00:26,  1.53it/s]

Progress: 13/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:09<00:26,  1.53it/s]

Progress: 14/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:09<00:25,  1.52it/s]

Progress: 15/54.	Score: 0.8054298642533937.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:10<00:24,  1.53it/s]

Progress: 16/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:11<00:24,  1.53it/s]

Progress: 17/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:11<00:23,  1.52it/s]

Progress: 18/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:12<00:22,  1.54it/s]

Progress: 19/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:13<00:21,  1.55it/s]

Progress: 20/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:13<00:21,  1.55it/s]

Progress: 21/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:14<00:20,  1.54it/s]

Progress: 22/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:15<00:20,  1.54it/s]

Progress: 23/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:15<00:19,  1.54it/s]

Progress: 24/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:16<00:18,  1.55it/s]

Progress: 25/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:16<00:18,  1.55it/s]

Progress: 26/54.	Score: 0.8089668615984406.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:17<00:17,  1.55it/s]

Progress: 27/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:18<00:16,  1.54it/s]

Progress: 28/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:18<00:16,  1.53it/s]

Progress: 29/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:19<00:15,  1.53it/s]

Progress: 30/54.	Score: 0.8253119429590017.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:20<00:14,  1.55it/s]

Progress: 31/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:20<00:14,  1.55it/s]

Progress: 32/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:21<00:13,  1.55it/s]

Progress: 33/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:22<00:12,  1.55it/s]

Progress: 34/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:22<00:12,  1.54it/s]

Progress: 35/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:23<00:11,  1.54it/s]

Progress: 36/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:24<00:10,  1.55it/s]

Progress: 37/54.	Score: 0.8650345260514751.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:24<00:10,  1.56it/s]

Progress: 38/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:25<00:09,  1.55it/s]

Progress: 39/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:25<00:09,  1.55it/s]

Progress: 40/54.	Score: 0.8392857142857142.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:26<00:08,  1.54it/s]

Progress: 41/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:27<00:07,  1.50it/s]

Progress: 42/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:27<00:07,  1.53it/s]

Progress: 43/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:28<00:06,  1.54it/s]

Progress: 44/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:29<00:05,  1.54it/s]

Progress: 45/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:29<00:05,  1.54it/s]

Progress: 46/54.	Score: 0.7925925925925925.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:30<00:04,  1.54it/s]

Progress: 47/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:31<00:03,  1.53it/s]

Progress: 48/54.	Score: 0.8234604105571848.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:31<00:03,  1.54it/s]

Progress: 49/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:32<00:02,  1.55it/s]

Progress: 50/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:33<00:01,  1.55it/s]

Progress: 51/54.	Score: 0.8279016580903372.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:33<00:01,  1.54it/s]

Progress: 52/54.	Score: 0.8506944444444444.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:34<00:00,  1.54it/s]

Progress: 53/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:35<00:00,  1.54it/s]

Progress: 54/54.	Score: 0.8156739811912226.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.873900293255132
Best params: {'k_neighbors': 3, 'sampling_strategy': 0.6}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smotenc_opt-smote...
holdout_test_f1_macro                                                      0.764521
holdout_test_accuracy_balanced                                             0.760417
holdout_test_roc_auc                                                       0.877701
holdout_test_f1                                                            0.836735
holdout_test_accuracy                                                      0.786667
cv_test_f1_macro_median                                                    0.813161
cv_test_accuracy_balanced_median                                           0.809598
cv_test_roc_auc_median                                                     0.905573
cv_test_f1_median                                                          0.869565
cv_test_accuracy_median                                                    0.830189
cv_test_precision_class_0_median                                           0.777778
cv_test_recall_class_0_median                                              0.736842
cv_test_f1_class_0_median                                                  0.756757

Model saved in ..\results\models_modelling4\AdaBoostClassifier_splashing_smotenc_opt-smotenc_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:33,  1.56it/s]

Progress: 1/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:01<00:33,  1.55it/s]

Progress: 2/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:32,  1.55it/s]

Progress: 3/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:02<00:32,  1.55it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:03<00:31,  1.53it/s]

Progress: 5/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:03<00:31,  1.53it/s]

Progress: 6/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:04<00:30,  1.55it/s]

Progress: 7/54.	Score: 0.8464285714285714.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:05<00:29,  1.56it/s]

Progress: 8/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:05<00:28,  1.55it/s]

Progress: 9/54.	Score: 0.7904490377761939.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:06<00:28,  1.55it/s]

Progress: 10/54.	Score: 0.8411330049261083.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:07<00:27,  1.54it/s]

Progress: 11/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:07<00:27,  1.53it/s]

Progress: 12/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:08<00:26,  1.55it/s]

Progress: 13/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:09<00:25,  1.56it/s]

Progress: 14/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:09<00:25,  1.55it/s]

Progress: 15/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:10<00:24,  1.55it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:10<00:23,  1.55it/s]

Progress: 17/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:11<00:23,  1.55it/s]

Progress: 18/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:12<00:22,  1.55it/s]

Progress: 19/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:12<00:21,  1.57it/s]

Progress: 20/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:13<00:21,  1.57it/s]

Progress: 21/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:14<00:20,  1.56it/s]

Progress: 22/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:14<00:19,  1.55it/s]

Progress: 23/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:15<00:19,  1.55it/s]

Progress: 24/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:16<00:18,  1.56it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:16<00:18,  1.52it/s]

Progress: 26/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:17<00:17,  1.53it/s]

Progress: 27/54.	Score: 0.7922705314009661.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:18<00:16,  1.53it/s]

Progress: 28/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:18<00:16,  1.52it/s]

Progress: 29/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:19<00:15,  1.53it/s]

Progress: 30/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:20<00:14,  1.55it/s]

Progress: 31/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:20<00:14,  1.55it/s]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:21<00:13,  1.56it/s]

Progress: 33/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:21<00:12,  1.56it/s]

Progress: 34/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:22<00:12,  1.55it/s]

Progress: 35/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:23<00:11,  1.55it/s]

Progress: 36/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:23<00:10,  1.56it/s]

Progress: 37/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:24<00:10,  1.58it/s]

Progress: 38/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:25<00:09,  1.56it/s]

Progress: 39/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:25<00:08,  1.56it/s]

Progress: 40/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:26<00:08,  1.56it/s]

Progress: 41/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:27<00:07,  1.54it/s]

Progress: 42/54.	Score: 0.8110483364720653.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:27<00:07,  1.56it/s]

Progress: 43/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:28<00:06,  1.57it/s]

Progress: 44/54.	Score: 0.8266129032258065.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:28<00:05,  1.57it/s]

Progress: 45/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:29<00:05,  1.56it/s]

Progress: 46/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:30<00:04,  1.56it/s]

Progress: 47/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:30<00:03,  1.55it/s]

Progress: 48/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:31<00:03,  1.56it/s]

Progress: 49/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:32<00:02,  1.57it/s]

Progress: 50/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:32<00:01,  1.57it/s]

Progress: 51/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:33<00:01,  1.56it/s]

Progress: 52/54.	Score: 0.8179068360556563.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:34<00:00,  1.55it/s]

Progress: 53/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:34<00:00,  1.55it/s]

Progress: 54/54.	Score: 0.802622950819672.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8503207412687099
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.9}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smotenc_op...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.938182
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.820946
cv_test_accuracy_balanced_median                                           0.838828
cv_test_roc_auc_median                                                     0.941392
cv_test_f1_median                                                              0.75
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.846154
cv_test_f1_class_0_median                                                  0.891892

Model saved in ..\results\models_modelling4\AdaBoostClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<00:53,  1.01s/it]

Progress: 1/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<00:53,  1.02s/it]

Progress: 2/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:03<00:52,  1.02s/it]

Progress: 3/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:04<00:51,  1.04s/it]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:05<00:50,  1.04s/it]

Progress: 5/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:06<00:49,  1.04s/it]

Progress: 6/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:07<00:48,  1.03s/it]

Progress: 7/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:08<00:47,  1.02s/it]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:09<00:46,  1.02s/it]

Progress: 9/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:10<00:45,  1.03s/it]

Progress: 10/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:11<00:44,  1.03s/it]

Progress: 11/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:12<00:43,  1.03s/it]

Progress: 12/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:13<00:41,  1.02s/it]

Progress: 13/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:14<00:40,  1.02s/it]

Progress: 14/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:15<00:39,  1.02s/it]

Progress: 15/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:16<00:38,  1.03s/it]

Progress: 16/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:17<00:38,  1.03s/it]

Progress: 17/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:18<00:37,  1.05s/it]

Progress: 18/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:19<00:36,  1.04s/it]

Progress: 19/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:20<00:35,  1.03s/it]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:21<00:33,  1.03s/it]

Progress: 21/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:22<00:32,  1.03s/it]

Progress: 22/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:23<00:31,  1.03s/it]

Progress: 23/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:24<00:30,  1.03s/it]

Progress: 24/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:25<00:29,  1.02s/it]

Progress: 25/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:26<00:28,  1.02s/it]

Progress: 26/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:27<00:27,  1.02s/it]

Progress: 27/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:28<00:26,  1.02s/it]

Progress: 28/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:29<00:25,  1.03s/it]

Progress: 29/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:30<00:24,  1.03s/it]

Progress: 30/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:31<00:23,  1.02s/it]

Progress: 31/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:32<00:22,  1.02s/it]

Progress: 32/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:33<00:21,  1.02s/it]

Progress: 33/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:34<00:20,  1.02s/it]

Progress: 34/54.	Score: 0.8940886699507389.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:35<00:19,  1.03s/it]

Progress: 35/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:36<00:18,  1.04s/it]

Progress: 36/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:37<00:17,  1.03s/it]

Progress: 37/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:39<00:16,  1.02s/it]

Progress: 38/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:40<00:15,  1.02s/it]

Progress: 39/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:41<00:14,  1.02s/it]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:42<00:13,  1.03s/it]

Progress: 41/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:43<00:12,  1.03s/it]

Progress: 42/54.	Score: 0.8721850273889227.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:44<00:11,  1.02s/it]

Progress: 43/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:45<00:10,  1.02s/it]

Progress: 44/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:46<00:09,  1.02s/it]

Progress: 45/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:47<00:08,  1.02s/it]

Progress: 46/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:48<00:07,  1.03s/it]

Progress: 47/54.	Score: 0.9210031347962382.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:49<00:06,  1.03s/it]

Progress: 48/54.	Score: 0.9210031347962382.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:50<00:05,  1.02s/it]

Progress: 49/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:51<00:04,  1.02s/it]

Progress: 50/54.	Score: 0.8885941644562334.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:52<00:03,  1.02s/it]

Progress: 51/54.	Score: 0.8444444444444446.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:53<00:02,  1.02s/it]

Progress: 52/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:54<00:01,  1.02s/it]

Progress: 53/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:55<00:00,  1.03s/it]

Progress: 54/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.9210031347962382
Best params: {'k_neighbors': 9, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smotenc_opt-s...
holdout_test_f1_macro                                                      0.806892
holdout_test_accuracy_balanced                                             0.799769
holdout_test_roc_auc                                                       0.934799
holdout_test_f1                                                            0.868687
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.876935
cv_test_roc_auc_median                                                     0.948142
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.888889
cv_test_f1_class_0_median                                                  0.842105

Model saved in ..\results\models_modelling4\RandomForestClassifier_splashing_smotenc_opt-smotenc_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:01<00:53,  1.01s/it]

Progress: 1/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:02<00:53,  1.02s/it]

Progress: 2/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:03<00:51,  1.02s/it]

Progress: 3/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:04<00:51,  1.02s/it]

Progress: 4/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:05<00:50,  1.03s/it]

Progress: 5/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:06<00:49,  1.03s/it]

Progress: 6/54.	Score: 0.8576271186440678.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:07<00:48,  1.02s/it]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:08<00:46,  1.02s/it]

Progress: 8/54.	Score: 0.8167613636363635.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:09<00:45,  1.02s/it]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:10<00:44,  1.02s/it]

Progress: 10/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:11<00:44,  1.03s/it]

Progress: 11/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:12<00:43,  1.03s/it]

Progress: 12/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:13<00:41,  1.02s/it]

Progress: 13/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:14<00:40,  1.01s/it]

Progress: 14/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:15<00:39,  1.02s/it]

Progress: 15/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:16<00:38,  1.02s/it]

Progress: 16/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:17<00:38,  1.03s/it]

Progress: 17/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:18<00:37,  1.03s/it]

Progress: 18/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:19<00:35,  1.03s/it]

Progress: 19/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:20<00:34,  1.02s/it]

Progress: 20/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:21<00:33,  1.02s/it]

Progress: 21/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:22<00:32,  1.02s/it]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:23<00:31,  1.03s/it]

Progress: 23/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:24<00:31,  1.04s/it]

Progress: 24/54.	Score: 0.8328912466843501.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:25<00:29,  1.02s/it]

Progress: 25/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:26<00:28,  1.02s/it]

Progress: 26/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:27<00:27,  1.01s/it]

Progress: 27/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:28<00:26,  1.02s/it]

Progress: 28/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:29<00:25,  1.03s/it]

Progress: 29/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:30<00:24,  1.03s/it]

Progress: 30/54.	Score: 0.800677966101695.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:31<00:23,  1.02s/it]

Progress: 31/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:32<00:22,  1.02s/it]

Progress: 32/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:33<00:21,  1.02s/it]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:34<00:20,  1.02s/it]

Progress: 34/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:35<00:19,  1.03s/it]

Progress: 35/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:36<00:18,  1.03s/it]

Progress: 36/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:37<00:17,  1.02s/it]

Progress: 37/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:38<00:16,  1.02s/it]

Progress: 38/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:39<00:15,  1.01s/it]

Progress: 39/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:40<00:14,  1.02s/it]

Progress: 40/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:41<00:13,  1.03s/it]

Progress: 41/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:43<00:12,  1.03s/it]

Progress: 42/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:43<00:11,  1.02s/it]

Progress: 43/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:44<00:10,  1.01s/it]

Progress: 44/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:46<00:09,  1.01s/it]

Progress: 45/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:47<00:08,  1.02s/it]

Progress: 46/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:48<00:07,  1.03s/it]

Progress: 47/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:49<00:06,  1.03s/it]

Progress: 48/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:50<00:05,  1.02s/it]

Progress: 49/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:51<00:04,  1.01s/it]

Progress: 50/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:52<00:03,  1.02s/it]

Progress: 51/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:53<00:02,  1.02s/it]

Progress: 52/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:54<00:01,  1.03s/it]

Progress: 53/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:55<00:00,  1.02s/it]

Progress: 54/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8590163934426229
Best params: {'k_neighbors': 5, 'sampling_strategy': 0.7}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smoten...
holdout_test_f1_macro                                                      0.900794
holdout_test_accuracy_balanced                                             0.913636
holdout_test_roc_auc                                                           0.98
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.935065

Model saved in ..\results\models_modelling4\RandomForestClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:22,  2.40it/s]

Progress: 1/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:18,  2.82it/s]

Progress: 2/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:01<00:18,  2.79it/s]

Progress: 3/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:17,  2.92it/s]

Progress: 4/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:16,  2.96it/s]

Progress: 5/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:02<00:16,  2.96it/s]

Progress: 6/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.03it/s]

Progress: 7/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:15,  3.05it/s]

Progress: 8/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:03<00:15,  2.97it/s]

Progress: 9/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  2.96it/s]

Progress: 10/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:14,  2.98it/s]

Progress: 11/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:04<00:14,  2.97it/s]

Progress: 12/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.02it/s]

Progress: 13/54.	Score: 0.8770726129216695.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:13,  3.06it/s]

Progress: 14/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:05<00:12,  3.03it/s]

Progress: 15/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  2.98it/s]

Progress: 16/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  2.96it/s]

Progress: 17/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:06<00:12,  2.97it/s]

Progress: 18/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:11,  3.03it/s]

Progress: 19/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:11,  3.06it/s]

Progress: 20/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:07<00:10,  3.07it/s]

Progress: 21/54.	Score: 0.8962962962962964.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:10,  2.99it/s]

Progress: 22/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  2.97it/s]

Progress: 23/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:08<00:10,  2.96it/s]

Progress: 24/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:08<00:09,  3.00it/s]

Progress: 25/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:09,  2.94it/s]

Progress: 26/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:09<00:09,  2.98it/s]

Progress: 27/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:09<00:08,  2.92it/s]

Progress: 28/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.93it/s]

Progress: 29/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:10<00:08,  2.93it/s]

Progress: 30/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:10<00:07,  2.99it/s]

Progress: 31/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.04it/s]

Progress: 32/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:11<00:06,  3.04it/s]

Progress: 33/54.	Score: 0.8699334543254689.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:11<00:06,  3.03it/s]

Progress: 34/54.	Score: 0.8464285714285715.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  2.82it/s]

Progress: 35/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:12<00:06,  2.84it/s]

Progress: 36/54.	Score: 0.8795518207282913.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:12<00:05,  2.92it/s]

Progress: 37/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  2.97it/s]

Progress: 38/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:13<00:05,  2.99it/s]

Progress: 39/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:13<00:04,  2.97it/s]

Progress: 40/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:04,  2.84it/s]

Progress: 41/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:14<00:04,  2.85it/s]

Progress: 42/54.	Score: 0.873900293255132.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:14<00:03,  2.93it/s]

Progress: 43/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:14<00:03,  2.94it/s]

Progress: 44/54.	Score: 0.8928571428571428.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:15<00:03,  2.97it/s]

Progress: 45/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:15<00:02,  2.98it/s]

Progress: 46/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:15<00:02,  2.89it/s]

Progress: 47/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:16<00:02,  2.92it/s]

Progress: 48/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:16<00:01,  2.99it/s]

Progress: 49/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:16<00:01,  3.01it/s]

Progress: 50/54.	Score: 0.8635477582846004.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:17<00:00,  3.03it/s]

Progress: 51/54.	Score: 0.8683385579937304.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:17<00:00,  3.02it/s]

Progress: 52/54.	Score: 0.8540723981900453.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:17<00:00,  2.99it/s]

Progress: 53/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:18<00:00,  2.96it/s]

Progress: 54/54.	Score: 0.851764705882353.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8962962962962964
Best params: {'k_neighbors': 2, 'sampling_strategy': 0.8}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smotenc_opt-smotenc_d...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                       0.939815
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.896201
cv_test_accuracy_balanced_median                                           0.900155
cv_test_roc_auc_median                                                      0.94127
cv_test_f1_median                                                          0.927536
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.888889
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.864865

Model saved in ..\results\models_modelling4\LGBMClassifier_splashing_smotenc_opt-smotenc_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_grid(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimizing parameters:   2%|▏         | 1/54 [00:00<00:16,  3.26it/s]

Progress: 1/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.6}.

Optimizing parameters:   4%|▎         | 2/54 [00:00<00:16,  3.11it/s]

Progress: 2/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.7}.

Optimizing parameters:   6%|▌         | 3/54 [00:00<00:17,  2.96it/s]

Progress: 3/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.8}.

Optimizing parameters:   7%|▋         | 4/54 [00:01<00:16,  3.00it/s]

Progress: 4/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 0.9}.

Optimizing parameters:   9%|▉         | 5/54 [00:01<00:16,  3.00it/s]

Progress: 5/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 1.0}.

Optimizing parameters:  11%|█         | 6/54 [00:01<00:15,  3.01it/s]

Progress: 6/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 2, 'sampling_strategy': 'auto'}.

Optimizing parameters:  13%|█▎        | 7/54 [00:02<00:15,  3.09it/s]

Progress: 7/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.6}.

Optimizing parameters:  15%|█▍        | 8/54 [00:02<00:14,  3.12it/s]

Progress: 8/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.7}.

Optimizing parameters:  17%|█▋        | 9/54 [00:02<00:14,  3.04it/s]

Progress: 9/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.8}.

Optimizing parameters:  19%|█▊        | 10/54 [00:03<00:14,  3.05it/s]

Progress: 10/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 0.9}.

Optimizing parameters:  20%|██        | 11/54 [00:03<00:14,  3.05it/s]

Progress: 11/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 1.0}.

Optimizing parameters:  22%|██▏       | 12/54 [00:03<00:13,  3.01it/s]

Progress: 12/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 3, 'sampling_strategy': 'auto'}.

Optimizing parameters:  24%|██▍       | 13/54 [00:04<00:13,  3.09it/s]

Progress: 13/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.6}.

Optimizing parameters:  26%|██▌       | 14/54 [00:04<00:12,  3.12it/s]

Progress: 14/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.7}.

Optimizing parameters:  28%|██▊       | 15/54 [00:04<00:12,  3.13it/s]

Progress: 15/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.8}.

Optimizing parameters:  30%|██▉       | 16/54 [00:05<00:12,  3.02it/s]

Progress: 16/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 0.9}.

Optimizing parameters:  31%|███▏      | 17/54 [00:05<00:12,  3.02it/s]

Progress: 17/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 1.0}.

Optimizing parameters:  33%|███▎      | 18/54 [00:05<00:11,  3.02it/s]

Progress: 18/54.	Score: 0.8590163934426229.	Considered params: {'k_neighbors': 4, 'sampling_strategy': 'auto'}.

Optimizing parameters:  35%|███▌      | 19/54 [00:06<00:11,  3.10it/s]

Progress: 19/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.6}.

Optimizing parameters:  37%|███▋      | 20/54 [00:06<00:10,  3.14it/s]

Progress: 20/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.7}.

Optimizing parameters:  39%|███▉      | 21/54 [00:06<00:10,  3.15it/s]

Progress: 21/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.8}.

Optimizing parameters:  41%|████      | 22/54 [00:07<00:10,  3.04it/s]

Progress: 22/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 0.9}.

Optimizing parameters:  43%|████▎     | 23/54 [00:07<00:10,  3.04it/s]

Progress: 23/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 1.0}.

Optimizing parameters:  44%|████▍     | 24/54 [00:07<00:09,  3.04it/s]

Progress: 24/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 5, 'sampling_strategy': 'auto'}.

Optimizing parameters:  46%|████▋     | 25/54 [00:08<00:09,  3.11it/s]

Progress: 25/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.6}.

Optimizing parameters:  48%|████▊     | 26/54 [00:08<00:09,  3.03it/s]

Progress: 26/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.7}.

Optimizing parameters:  50%|█████     | 27/54 [00:08<00:08,  3.07it/s]

Progress: 27/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.8}.

Optimizing parameters:  52%|█████▏    | 28/54 [00:09<00:08,  3.04it/s]

Progress: 28/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 0.9}.

Optimizing parameters:  54%|█████▎    | 29/54 [00:09<00:08,  2.95it/s]

Progress: 29/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 1.0}.

Optimizing parameters:  56%|█████▌    | 30/54 [00:09<00:08,  2.97it/s]

Progress: 30/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 6, 'sampling_strategy': 'auto'}.

Optimizing parameters:  57%|█████▋    | 31/54 [00:10<00:07,  3.06it/s]

Progress: 31/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.6}.

Optimizing parameters:  59%|█████▉    | 32/54 [00:10<00:07,  3.11it/s]

Progress: 32/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.7}.

Optimizing parameters:  61%|██████    | 33/54 [00:10<00:06,  3.13it/s]

Progress: 33/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.8}.

Optimizing parameters:  63%|██████▎   | 34/54 [00:11<00:06,  3.10it/s]

Progress: 34/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 0.9}.

Optimizing parameters:  65%|██████▍   | 35/54 [00:11<00:06,  2.98it/s]

Progress: 35/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 1.0}.

Optimizing parameters:  67%|██████▋   | 36/54 [00:11<00:06,  2.96it/s]

Progress: 36/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 7, 'sampling_strategy': 'auto'}.

Optimizing parameters:  69%|██████▊   | 37/54 [00:12<00:05,  3.04it/s]

Progress: 37/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.6}.

Optimizing parameters:  70%|███████   | 38/54 [00:12<00:05,  3.09it/s]

Progress: 38/54.	Score: 0.8516218081435472.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.7}.

Optimizing parameters:  72%|███████▏  | 39/54 [00:12<00:04,  3.09it/s]

Progress: 39/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.8}.

Optimizing parameters:  74%|███████▍  | 40/54 [00:13<00:04,  3.07it/s]

Progress: 40/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 0.9}.

Optimizing parameters:  76%|███████▌  | 41/54 [00:13<00:04,  3.04it/s]

Progress: 41/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 1.0}.

Optimizing parameters:  78%|███████▊  | 42/54 [00:13<00:04,  2.94it/s]

Progress: 42/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 8, 'sampling_strategy': 'auto'}.

Optimizing parameters:  80%|███████▉  | 43/54 [00:14<00:03,  3.02it/s]

Progress: 43/54.	Score: 0.8250000000000001.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.6}.

Optimizing parameters:  81%|████████▏ | 44/54 [00:14<00:03,  3.09it/s]

Progress: 44/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.7}.

Optimizing parameters:  83%|████████▎ | 45/54 [00:14<00:02,  3.12it/s]

Progress: 45/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.8}.

Optimizing parameters:  85%|████████▌ | 46/54 [00:15<00:02,  3.11it/s]

Progress: 46/54.	Score: 0.8412698412698413.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 0.9}.

Optimizing parameters:  87%|████████▋ | 47/54 [00:15<00:02,  3.06it/s]

Progress: 47/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 1.0}.

Optimizing parameters:  89%|████████▉ | 48/54 [00:15<00:02,  2.98it/s]

Progress: 48/54.	Score: 0.8299595141700404.	Considered params: {'k_neighbors': 9, 'sampling_strategy': 'auto'}.

Optimizing parameters:  91%|█████████ | 49/54 [00:16<00:01,  3.04it/s]

Progress: 49/54.	Score: 0.8346153846153845.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.6}.

Optimizing parameters:  93%|█████████▎| 50/54 [00:16<00:01,  3.09it/s]

Progress: 50/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.7}.

Optimizing parameters:  94%|█████████▍| 51/54 [00:16<00:00,  3.10it/s]

Progress: 51/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.8}.

Optimizing parameters:  96%|█████████▋| 52/54 [00:17<00:00,  3.10it/s]

Progress: 52/54.	Score: 0.8503207412687099.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 0.9}.

Optimizing parameters:  98%|█████████▊| 53/54 [00:17<00:00,  3.07it/s]

Progress: 53/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 1.0}.

Optimizing parameters: 100%|██████████| 54/54 [00:17<00:00,  3.05it/s]

Progress: 54/54.	Score: 0.81524926686217.	Considered params: {'k_neighbors': 10, 'sampling_strategy': 'auto'}.
-------------------------------------------------------------------------------------
Best score: 0.8590163934426229
Best params: {'k_neighbors': 4, 'sampling_strategy': 1.0}
-------------------------------------------------------------------------------------
Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smotenc_opt-sm...
holdout_test_f1_macro                                                      0.933862
holdout_test_accuracy_balanced                                             0.947727
holdout_test_roc_auc                                                           0.99
holdout_test_f1                                                            0.904762
holdout_test_accuracy                                                      0.946667
cv_test_f1_macro_median                                                    0.876543
cv_test_accuracy_balanced_median                                           0.857143
cv_test_roc_auc_median                                                     0.979487
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                    0.907407
cv_test_precision_class_0_median                                           0.923077
cv_test_recall_class_0_median                                              0.923077
cv_test_f1_class_0_median                                                  0.938272

Model saved in ..\results\models_modelling4\LGBMClassifier_no_fragmentation_smotenc_opt-smotenc_default-model

# For the notebook with Model optimization!

In [23]:
# def update_estimator_params(
#     ml_pipe:MLPipeline,
#     suggested_params:dict,
# ) -> dict:
#     """Update the estimator parameters based on the pipeline parameters.

#     Args:
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.
#         suggested_params: A dictionary containing the suggested Estimator hyperparameters.
    
#     Returns:
#         A dictionary containing the estimator parameters.
#     """
#     estimator_params = ml_pipe._pipeline_params['estimator_params']
#     estimator_params.update(suggested_params)
#     return estimator_params

# def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
#     """Objective function for logistic regression optimization using Optuna.

#     Args:
#         trial: An Optuna trial object used to suggest hyperparameters.
#         ml_pipe: An instance of MLPipeline used for model training and evaluation.

#     Returns:
#         The score of the model based on the specified evaluation metric.
#     """
    
#     categorical_features = ('wettability', 'inclination')
    
#     random_state = ml_pipe._pipeline_params['random_state']
    
#     # sample params
#     C = trial.suggest_loguniform('C', 1e-4, 1e3)
    
#     # SMOTE params
#     add_smote = trial.suggest_categorical('add_smote', [True, False])
#     if add_smote:
#         is_smotenc = trial.suggest_categorical('is_smotenc', [True, False])
#         smote_params = {
#             'sampling_strategy': trial.suggest_categorical(
#                 'sampling_strategy', [0.6, 0.7, 0.8, 0.9, 1.0]
#             ),
#             'k_neighbors': trial.suggest_int('k_neighbors', 3, 10),
#             'random_state': random_state,
#         }
#     else:
#         is_smotenc = False
#         smote_params = None
#     if is_smotenc:
#         wettability_cat = trial.suggest_categorical('wettability_cat', [True, False])
#         if wettability_cat:
#             inclination_cat = trial.suggest_categorical('inclination_cat', [True, False])
#         else:
#             inclination_cat = True
        
        
#         mask = [wettability_cat, inclination_cat]
        
#         masked_features = [
#             feature for feature, mask_value in zip(categorical_features, mask) 
#             if mask_value
#         ]
#         smote_params = {
#             **smote_params,
#             'categorical_features': masked_features,
#         }

#     suggested_params = {
#         "C": C,
#     }
    
#     estimator_params = update_estimator_params(ml_pipe, suggested_params)

#     estimator = LogisticRegression(
#         **estimator_params,
#         random_state=random_state,
#     )

#     score = ml_pipe.step(
#         estimator=estimator,
#         add_smote=add_smote,
#         is_smotenc=is_smotenc,
#         smote_params=smote_params,
#     )
    
#     return score



# opt = OptunaOptimizer(
#     objective=partial(logreg_objective, ml_pipe=ml_pipe),
#     study_name="logreg_study",
#     direction="maximize",
# )

# opt.optimize(n_trials=200)

# best_params = opt.study.best_trial.params
# display(best_params)
# # estimator_params = update_estimator_params(ml_pipe, best_params)

# # estimator = LogisticRegression(
# #     **estimator_params,
# #     random_state=ml_pipe._pipeline_params['random_state'],
# # )