Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
    OptunaOptimizer,
    smote_objective,
    pure_smote_objective,
    GridSearchOptimizer,
    RANDOM_STATE,
)

seed = RANDOM_STATE

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'optuna-opt-mean-smote_default-model'
add_smote = True
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 400

save_model_and_metrics = True
metrics_file = 'metrics_modelling4_smote_mean_opt.xlsx'

## Optimization functions
Optuna will not be used further, except first try, it is enough to conduct grid search

In [5]:
def optimize_smote_optuna(
    target:str,
    estimator:object,
    estimator_params:dict,
    n_trials:int=n_trials,
    step_scoring_average:str=step_scoring_average,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
    metrics_file:str=metrics_file,
    seed:int=seed,
):
    """
    Optimize the SMOTE parameters for a given estimator.

    Args:
        target: The target variable for the model.
        estimator: The machine learning estimator to be optimized.
        estimator_params: Parameters for the estimator.
        n_trials: The number of trials for optimization. Defaults to n_trials.
        model_postfix: A postfix to append to the model name. Defaults to model_postfix.
        add_smote: Whether to add SMOTE to the pipeline. Defaults to add_smote.
        is_smotenc: Whether to use SMOTENC for categorical features. Defaults to is_smotenc.
        smote_params: Parameters for SMOTE. Defaults to smote_params.
        scoring_metrics: Metrics for scoring the model. Defaults to scoring_metrics.
        save_model_and_metrics: Whether to save the model and metrics. Defaults to save_model_and_metrics.
    """
    
    smote_params = smote_params.copy()
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )

    opt = OptunaOptimizer(
        objective=partial(smote_objective, ml_pipe=ml_pipe),
        study_name="smote_study",
        direction="maximize",
        seed=seed,
    )

    opt.optimize(n_trials=n_trials)

    best_params = opt.study.best_params
    print('best_params')
    display(best_params)

    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params={**smote_params, **best_params},
        metrics_file=metrics_file,
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:47:50,524] A new study created in memory with name: smote_study
[I 2025-04-16 00:47:50,601] Trial 0 finished with value: 0.808631916777597 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:47:50,670] Trial 1 finished with value: 0.8033759141203999 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:47:50,740] Trial 2 finished with value: 0.8082580539469134 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:47:50,807] Trial 3 finished with value: 0.8086807655106563 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8086807655106563.
[I 2025-04-16 00:47:50,877] Trial 4 finished with value: 0.8069288014407415 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8086807655106563.
[I 2025-04-16 00:47:50,945] Trial 5 finished with value: 0.8091779675371186 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8091779675371186.
[I 2025-04-16 00:47:51,013] Trial 6 finished with value: 0.8189535216081174 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,080] Trial 7 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,146] Trial 8 finished with value: 0.813703466918272 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,247] Trial 9 finished with value: 0.8018019388452579 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,326] Trial 10 finished with value: 0.802875485873124 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,400] Trial 11 finished with value: 0.805870511829621 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.77}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:47:51,472] Trial 12 finished with value: 0.8209150053798104 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,545] Trial 13 finished with value: 0.8057775246374935 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,618] Trial 14 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,690] Trial 15 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.72}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,765] Trial 16 finished with value: 0.8029566706303755 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,836] Trial 17 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,909] Trial 18 finished with value: 0.8093724164387771 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:51,982] Trial 19 finished with value: 0.8073330774098217 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,055] Trial 20 finished with value: 0.8122456770823373 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.73}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,128] Trial 21 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,202] Trial 22 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,273] Trial 23 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,344] Trial 24 finished with value: 0.8057801408706019 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,415] Trial 25 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,547] Trial 26 finished with value: 0.8057775246374935 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,661] Trial 27 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:52,829] Trial 28 finished with value: 0.8131897204864958 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,006] Trial 29 finished with value: 0.8057801408706019 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,081] Trial 30 finished with value: 0.8133013504603495 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,154] Trial 31 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,228] Trial 32 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,303] Trial 33 finished with value: 0.8049846404973474 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,381] Trial 34 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,458] Trial 35 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,541] Trial 36 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,623] Trial 37 finished with value: 0.8101535621842993 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,752] Trial 38 finished with value: 0.8041141052658777 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:53,992] Trial 39 finished with value: 0.8025974392185125 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,069] Trial 40 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,148] Trial 41 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,227] Trial 42 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,307] Trial 43 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,386] Trial 44 finished with value: 0.8010284180437964 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,462] Trial 45 finished with value: 0.7920045276689839 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,538] Trial 46 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,617] Trial 47 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,698] Trial 48 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,777] Trial 49 finished with value: 0.802587677269975 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,855] Trial 50 finished with value: 0.8061857191031435 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:54,929] Trial 51 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,016] Trial 52 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,099] Trial 53 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,182] Trial 54 finished with value: 0.8025974392185125 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,264] Trial 55 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,371] Trial 56 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,454] Trial 57 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,536] Trial 58 finished with value: 0.8118186141132304 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,616] Trial 59 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,698] Trial 60 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,781] Trial 61 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,858] Trial 62 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:55,937] Trial 63 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,016] Trial 64 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,101] Trial 65 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,186] Trial 66 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,273] Trial 67 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,351] Trial 68 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,427] Trial 69 finished with value: 0.8112739239326043 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,523] Trial 70 finished with value: 0.8043041068880133 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,607] Trial 71 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,687] Trial 72 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,770] Trial 73 finished with value: 0.8133013504603495 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,849] Trial 74 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:56,955] Trial 75 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,036] Trial 76 finished with value: 0.8049846404973474 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,120] Trial 77 finished with value: 0.7940419619443385 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,201] Trial 78 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,279] Trial 79 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,363] Trial 80 finished with value: 0.8043029691906879 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,456] Trial 81 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,538] Trial 82 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,623] Trial 83 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,703] Trial 84 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,784] Trial 85 finished with value: 0.8131897204864958 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,868] Trial 86 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:57,947] Trial 87 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,031] Trial 88 finished with value: 0.810940008756207 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,114] Trial 89 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,222] Trial 90 finished with value: 0.8029566706303755 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,301] Trial 91 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,381] Trial 92 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,466] Trial 93 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,543] Trial 94 finished with value: 0.8043041068880133 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,629] Trial 95 finished with value: 0.8061476556952193 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,717] Trial 96 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,806] Trial 97 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,897] Trial 98 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:58,991] Trial 99 finished with value: 0.7984696051367034 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:59,076] Trial 100 finished with value: 0.8010284180437964 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:59,160] Trial 101 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:59,247] Trial 102 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:47:59,331] Trial 103 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.78}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_optuna-opt-...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.885031
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.799242
cv_test_accuracy_balanced_median                                           0.816667
cv_test_roc_auc_median                                                     0.871517
cv_test_f1_median                                                          0.848485
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.833333
cv_test_f1_class_0_median                                                      0.75

Model saved in ../results/models_modelling4/LogisticRegression_splashing_smote_optuna-opt-mean-smote_default-model

In [7]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:48:25,402] A new study created in memory with name: smote_study
[I 2025-04-16 00:48:25,483] Trial 0 finished with value: 0.808631916777597 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:48:25,562] Trial 1 finished with value: 0.8033759141203999 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:48:25,637] Trial 2 finished with value: 0.8082580539469134 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.808631916777597.
[I 2025-04-16 00:48:25,712] Trial 3 finished with value: 0.8086807655106563 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8086807655106563.
[I 2025-04-16 00:48:25,785] Trial 4 finished with value: 0.8069288014407415 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8086807655106563.
[I 2025-04-16 00:48:25,858] Trial 5 finished with value: 0.8091779675371186 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8091779675371186.
[I 2025-04-16 00:48:25,937] Trial 6 finished with value: 0.8189535216081174 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,012] Trial 7 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,086] Trial 8 finished with value: 0.813703466918272 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,164] Trial 9 finished with value: 0.8018019388452579 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,280] Trial 10 finished with value: 0.802875485873124 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,373] Trial 11 finished with value: 0.805870511829621 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.77}. Best is trial 6 with value: 0.8189535216081174.
[I 2025-04-16 00:48:26,458] Trial 12 finished with value: 0.8209150053798104 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,539] Trial 13 finished with value: 0.8057775246374935 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,616] Trial 14 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,694] Trial 15 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.72}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,772] Trial 16 finished with value: 0.8029566706303755 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,850] Trial 17 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:26,928] Trial 18 finished with value: 0.8093724164387771 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,003] Trial 19 finished with value: 0.8073330774098217 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,082] Trial 20 finished with value: 0.8122456770823373 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.73}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,156] Trial 21 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,233] Trial 22 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,313] Trial 23 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,397] Trial 24 finished with value: 0.8057801408706019 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,474] Trial 25 finished with value: 0.8154355244498557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,553] Trial 26 finished with value: 0.8057775246374935 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,628] Trial 27 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,705] Trial 28 finished with value: 0.8131897204864958 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,786] Trial 29 finished with value: 0.8057801408706019 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,876] Trial 30 finished with value: 0.8133013504603495 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:27,953] Trial 31 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,031] Trial 32 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,106] Trial 33 finished with value: 0.8049846404973474 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,182] Trial 34 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,299] Trial 35 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,377] Trial 36 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,454] Trial 37 finished with value: 0.8101535621842993 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,533] Trial 38 finished with value: 0.8041141052658777 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,608] Trial 39 finished with value: 0.8025974392185125 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,685] Trial 40 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,762] Trial 41 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,839] Trial 42 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,915] Trial 43 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:28,993] Trial 44 finished with value: 0.8010284180437964 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,072] Trial 45 finished with value: 0.7920045276689839 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,151] Trial 46 finished with value: 0.8125202047148272 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,229] Trial 47 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,307] Trial 48 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,382] Trial 49 finished with value: 0.802587677269975 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.79}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,466] Trial 50 finished with value: 0.8061857191031435 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,549] Trial 51 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,626] Trial 52 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,704] Trial 53 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,780] Trial 54 finished with value: 0.8025974392185125 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,863] Trial 55 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:29,951] Trial 56 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,045] Trial 57 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,125] Trial 58 finished with value: 0.8118186141132304 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,205] Trial 59 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,319] Trial 60 finished with value: 0.804983502800022 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,400] Trial 61 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,475] Trial 62 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,552] Trial 63 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,632] Trial 64 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,711] Trial 65 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,786] Trial 66 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,864] Trial 67 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.7}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:30,940] Trial 68 finished with value: 0.8157449654583849 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,019] Trial 69 finished with value: 0.8112739239326043 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,095] Trial 70 finished with value: 0.8043041068880133 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,171] Trial 71 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,253] Trial 72 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,331] Trial 73 finished with value: 0.8133013504603495 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,413] Trial 74 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,492] Trial 75 finished with value: 0.8139826366002606 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,570] Trial 76 finished with value: 0.8049846404973474 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,644] Trial 77 finished with value: 0.7940419619443385 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,732] Trial 78 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,812] Trial 79 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,891] Trial 80 finished with value: 0.8043029691906879 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:31,973] Trial 81 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,059] Trial 82 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,138] Trial 83 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,224] Trial 84 finished with value: 0.8049820242642388 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,305] Trial 85 finished with value: 0.8131897204864958 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,386] Trial 86 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,499] Trial 87 finished with value: 0.803531013834892 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,577] Trial 88 finished with value: 0.810940008756207 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,657] Trial 89 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,739] Trial 90 finished with value: 0.8029566706303755 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,821] Trial 91 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,899] Trial 92 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:32,978] Trial 93 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,060] Trial 94 finished with value: 0.8043041068880133 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,143] Trial 95 finished with value: 0.8061476556952193 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,219] Trial 96 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,297] Trial 97 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.63}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,383] Trial 98 finished with value: 0.8149670361700192 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,464] Trial 99 finished with value: 0.7984696051367034 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,543] Trial 100 finished with value: 0.8010284180437964 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,624] Trial 101 finished with value: 0.8179455770209003 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.62}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,703] Trial 102 finished with value: 0.8106946547408501 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8209150053798104.
[I 2025-04-16 00:48:33,784] Trial 103 finished with value: 0.81465759516149 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 12 with value: 0.8209150053798104.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.78}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                                    splashing
model                             LogisticRegression_splashing_smote_optuna-opt-...
holdout_test_f1_macro                                                      0.793956
holdout_test_accuracy_balanced                                             0.789352
holdout_test_roc_auc                                                       0.885031
holdout_test_f1                                                            0.857143
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.799242
cv_test_accuracy_balanced_median                                           0.816667
cv_test_roc_auc_median                                                     0.871517
cv_test_f1_median                                                          0.848485
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.681818
cv_test_recall_class_0_median                                              0.833333
cv_test_f1_class_0_median                                                      0.75

Model saved in ../results/models_modelling4/LogisticRegression_splashing_smote_optuna-opt-mean-smote_default-model

Full grid search can find better solution, than Optuna with small number of iterations - like 40! It appears in some Random_seed

In [8]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:48:59,058] A new study created in memory with name: smote_study
[I 2025-04-16 00:48:59,128] Trial 0 finished with value: 0.7953914760068441 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.7953914760068441.
[I 2025-04-16 00:48:59,196] Trial 1 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.7953914760068441.
[I 2025-04-16 00:48:59,260] Trial 2 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.7953914760068441.
[I 2025-04-16 00:48:59,327] Trial 3 finished with value: 0.7972483300592221 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.7972483300592221.
[I 2025-04-16 00:48:59,390] Trial 4 finished with value: 0.7927358172501057 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.7972483300592221.
[I 2025-04-16 00:48:59,458] Trial 5 finished with value: 0.7972483300592221 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.7972483300592221.
[I 2025-04-16 00:48:59,523] Trial 6 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.7972483300592221.
[I 2025-04-16 00:48:59,586] Trial 7 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 3 with value: 0.7972483300592221.
[I 2025-04-16 00:48:59,650] Trial 8 finished with value: 0.7986888172352199 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 8 with value: 0.7986888172352199.
[I 2025-04-16 00:48:59,713] Trial 9 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 9 with value: 0.7993857581360823.
[I 2025-04-16 00:48:59,780] Trial 10 finished with value: 0.7926459322449665 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 9 with value: 0.7993857581360823.
[I 2025-04-16 00:48:59,849] Trial 11 finished with value: 0.7926459322449665 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 9 with value: 0.7993857581360823.
[I 2025-04-16 00:48:59,919] Trial 12 finished with value: 0.8024548763429645 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8024548763429645.
[I 2025-04-16 00:48:59,990] Trial 13 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8024548763429645.
[I 2025-04-16 00:49:00,074] Trial 14 finished with value: 0.8027588628638668 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 14 with value: 0.8027588628638668.
[I 2025-04-16 00:49:00,140] Trial 15 finished with value: 0.8023586077733721 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 14 with value: 0.8027588628638668.
[I 2025-04-16 00:49:00,209] Trial 16 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 16 with value: 0.8042508987626824.
[I 2025-04-16 00:49:00,280] Trial 17 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,349] Trial 18 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,418] Trial 19 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,488] Trial 20 finished with value: 0.7986888172352199 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,561] Trial 21 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,638] Trial 22 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,743] Trial 23 finished with value: 0.8054796912609915 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,815] Trial 24 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,884] Trial 25 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:00,953] Trial 26 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,020] Trial 27 finished with value: 0.7986888172352199 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,087] Trial 28 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,155] Trial 29 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,224] Trial 30 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,296] Trial 31 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,365] Trial 32 finished with value: 0.8054796912609915 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,435] Trial 33 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,510] Trial 34 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,583] Trial 35 finished with value: 0.7927358172501057 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,650] Trial 36 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,722] Trial 37 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,794] Trial 38 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,866] Trial 39 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:01,938] Trial 40 finished with value: 0.7961089219778902 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,008] Trial 41 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,076] Trial 42 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,148] Trial 43 finished with value: 0.8027588628638668 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,216] Trial 44 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,282] Trial 45 finished with value: 0.802106586533207 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.72}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,371] Trial 46 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,444] Trial 47 finished with value: 0.802106586533207 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,515] Trial 48 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,587] Trial 49 finished with value: 0.7893690960867744 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.86}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,691] Trial 50 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,760] Trial 51 finished with value: 0.8054796912609915 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,832] Trial 52 finished with value: 0.802106586533207 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,905] Trial 53 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:02,976] Trial 54 finished with value: 0.8024548763429645 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,049] Trial 55 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,126] Trial 56 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,197] Trial 57 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,271] Trial 58 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,344] Trial 59 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,414] Trial 60 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,486] Trial 61 finished with value: 0.8054796912609915 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,557] Trial 62 finished with value: 0.802106586533207 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,630] Trial 63 finished with value: 0.802106586533207 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,701] Trial 64 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,779] Trial 65 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,851] Trial 66 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:03,928] Trial 67 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,003] Trial 68 finished with value: 0.8023997957395304 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,077] Trial 69 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,149] Trial 70 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,221] Trial 71 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,296] Trial 72 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,380] Trial 73 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,452] Trial 74 finished with value: 0.7953914760068441 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,553] Trial 75 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,630] Trial 76 finished with value: 0.8024548763429645 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,695] Trial 77 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,760] Trial 78 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,837] Trial 79 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,905] Trial 80 finished with value: 0.7934436297114765 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:04,975] Trial 81 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,043] Trial 82 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,115] Trial 83 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,182] Trial 84 finished with value: 0.7953914760068441 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,248] Trial 85 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,316] Trial 86 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,389] Trial 87 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,463] Trial 88 finished with value: 0.7957150504518486 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,534] Trial 89 finished with value: 0.7986888172352199 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,602] Trial 90 finished with value: 0.8027588628638668 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6599999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,671] Trial 91 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,741] Trial 92 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,809] Trial 93 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,877] Trial 94 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:05,946] Trial 95 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,014] Trial 96 finished with value: 0.7927422008145589 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,083] Trial 97 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,153] Trial 98 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,222] Trial 99 finished with value: 0.7993857581360823 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6699999999999999}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,299] Trial 100 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,402] Trial 101 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,472] Trial 102 finished with value: 0.8042508987626824 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 17 with value: 0.808852795988776.
[I 2025-04-16 00:49:06,546] Trial 103 finished with value: 0.808852795988776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 17 with value: 0.808852795988776.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.64}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                                  0
target                                                             no_fragmentation
model                             LogisticRegression_no_fragmentation_smote_optu...
holdout_test_f1_macro                                                      0.802991
holdout_test_accuracy_balanced                                                 0.85
holdout_test_roc_auc                                                       0.954545
holdout_test_f1                                                            0.734694
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.826797
cv_test_accuracy_balanced_median                                           0.864469
cv_test_roc_auc_median                                                      0.93956
cv_test_f1_median                                                          0.764706
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.967742
cv_test_recall_class_0_median                                              0.794872
cv_test_f1_class_0_median                                                  0.885714

Model saved in ../results/models_modelling4/LogisticRegression_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# KNClassifier

In [9]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:49:28,734] A new study created in memory with name: smote_study
[I 2025-04-16 00:49:28,859] Trial 0 finished with value: 0.839000057333054 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.839000057333054.
[I 2025-04-16 00:49:28,963] Trial 1 finished with value: 0.8366744957233221 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.839000057333054.
[I 2025-04-16 00:49:29,106] Trial 2 finished with value: 0.8275188914323743 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.839000057333054.
[I 2025-04-16 00:49:29,210] Trial 3 finished with value: 0.8339107074490688 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.839000057333054.
[I 2025-04-16 00:49:29,314] Trial 4 finished with value: 0.826598877826172 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.839000057333054.
[I 2025-04-16 00:49:29,421] Trial 5 finished with value: 0.8447644967813659 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:29,524] Trial 6 finished with value: 0.8200728810093054 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:29,627] Trial 7 finished with value: 0.8170942046629018 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:29,733] Trial 8 finished with value: 0.8373425769240865 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:29,846] Trial 9 finished with value: 0.8440321908808819 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:29,969] Trial 10 finished with value: 0.8381036738364411 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,087] Trial 11 finished with value: 0.8372303526075673 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,195] Trial 12 finished with value: 0.8406978616739517 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.74}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,303] Trial 13 finished with value: 0.8294422484143872 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,412] Trial 14 finished with value: 0.8291697628757652 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,515] Trial 15 finished with value: 0.8384778729469075 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 5 with value: 0.8447644967813659.
[I 2025-04-16 00:49:30,629] Trial 16 finished with value: 0.8505423796235594 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 16 with value: 0.8505423796235594.
[I 2025-04-16 00:49:30,736] Trial 17 finished with value: 0.8447402309543337 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.99}. Best is trial 16 with value: 0.8505423796235594.
[I 2025-04-16 00:49:30,850] Trial 18 finished with value: 0.8477807238843518 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9299999999999999}. Best is trial 16 with value: 0.8505423796235594.
[I 2025-04-16 00:49:30,958] Trial 19 finished with value: 0.8331521982967303 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 16 with value: 0.8505423796235594.
[I 2025-04-16 00:49:31,068] Trial 20 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,209] Trial 21 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,318] Trial 22 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,430] Trial 23 finished with value: 0.8505760771120493 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,538] Trial 24 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,643] Trial 25 finished with value: 0.8505760771120493 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,754] Trial 26 finished with value: 0.8417875440774599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,859] Trial 27 finished with value: 0.8357865717045342 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.83}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:31,963] Trial 28 finished with value: 0.8411715628843247 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,069] Trial 29 finished with value: 0.8342131333733199 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,181] Trial 30 finished with value: 0.8412014331260739 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,292] Trial 31 finished with value: 0.8568163936126121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,407] Trial 32 finished with value: 0.8496987067355357 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,516] Trial 33 finished with value: 0.8320264776923533 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,622] Trial 34 finished with value: 0.8558864354062561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,736] Trial 35 finished with value: 0.8505423796235594 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,847] Trial 36 finished with value: 0.8463478129079842 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:32,956] Trial 37 finished with value: 0.8235676589769005 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,080] Trial 38 finished with value: 0.8551248513434635 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,219] Trial 39 finished with value: 0.8413430814876135 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,323] Trial 40 finished with value: 0.8273150958323188 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,432] Trial 41 finished with value: 0.8568163936126121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,537] Trial 42 finished with value: 0.8444270444463403 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,650] Trial 43 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,764] Trial 44 finished with value: 0.8294773532459994 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8999999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,870] Trial 45 finished with value: 0.8417875440774599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:33,980] Trial 46 finished with value: 0.8531176356799832 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,091] Trial 47 finished with value: 0.8238130881349875 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,204] Trial 48 finished with value: 0.840977166881051 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,319] Trial 49 finished with value: 0.838282021320422 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,430] Trial 50 finished with value: 0.8415032535893557 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,542] Trial 51 finished with value: 0.8444270444463403 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,648] Trial 52 finished with value: 0.8505423796235594 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,751] Trial 53 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,858] Trial 54 finished with value: 0.8477807238843518 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:34,970] Trial 55 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,074] Trial 56 finished with value: 0.8587843212332888 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,179] Trial 57 finished with value: 0.8368955524497397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.99}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,285] Trial 58 finished with value: 0.8481946996603194 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,418] Trial 59 finished with value: 0.8414216970940787 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,524] Trial 60 finished with value: 0.8456693087605666 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,634] Trial 61 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,746] Trial 62 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,854] Trial 63 finished with value: 0.8444270444463403 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:35,962] Trial 64 finished with value: 0.8417875440774599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,080] Trial 65 finished with value: 0.8558864354062561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,191] Trial 66 finished with value: 0.8311209280653573 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,298] Trial 67 finished with value: 0.8368955524497397 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.99}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,407] Trial 68 finished with value: 0.8411715628843247 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,521] Trial 69 finished with value: 0.8496987067355357 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,631] Trial 70 finished with value: 0.8425328023590696 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,739] Trial 71 finished with value: 0.8568163936126121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,844] Trial 72 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:36,949] Trial 73 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,058] Trial 74 finished with value: 0.8481946996603194 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,160] Trial 75 finished with value: 0.8531176356799832 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,265] Trial 76 finished with value: 0.8439952029023274 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,410] Trial 77 finished with value: 0.8459147856420387 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,518] Trial 78 finished with value: 0.8558864354062561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,623] Trial 79 finished with value: 0.8295810479327738 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,735] Trial 80 finished with value: 0.8295766386700599 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,843] Trial 81 finished with value: 0.8568163936126121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:37,955] Trial 82 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,067] Trial 83 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,182] Trial 84 finished with value: 0.8587843212332888 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,287] Trial 85 finished with value: 0.8496987067355357 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,395] Trial 86 finished with value: 0.8490900461058265 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,507] Trial 87 finished with value: 0.8238130881349875 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,611] Trial 88 finished with value: 0.8425328023590696 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,719] Trial 89 finished with value: 0.8531176356799832 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,841] Trial 90 finished with value: 0.8477807238843518 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:38,952] Trial 91 finished with value: 0.8592644269630207 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,060] Trial 92 finished with value: 0.8568163936126121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,170] Trial 93 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,277] Trial 94 finished with value: 0.8496987067355357 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,391] Trial 95 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,502] Trial 96 finished with value: 0.8417875440774599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,640] Trial 97 finished with value: 0.8380930119730935 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,747] Trial 98 finished with value: 0.840489769360825 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,854] Trial 99 finished with value: 0.8558864354062561 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:39,959] Trial 100 finished with value: 0.8422612463837628 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:40,064] Trial 101 finished with value: 0.8637235106441158 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.95}. Best is trial 20 with value: 0.8637235106441158.
[I 2025-04-16 00:49:40,170] Trial 102 finished with value: 0.8444270444463403 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 20 with value: 0.8637235106441158.

best_params

{'k_neighbors': 9, 'sampling_strategy': 0.95}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                                    splashing
model                             KNeighborsClassifier_splashing_smote_optuna-op...
holdout_test_f1_macro                                                      0.829027
holdout_test_accuracy_balanced                                             0.834491
holdout_test_roc_auc                                                       0.891204
holdout_test_f1                                                             0.87234
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                    0.846377
cv_test_accuracy_balanced_median                                           0.876935
cv_test_roc_auc_median                                                     0.929323
cv_test_f1_median                                                             0.875
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                            0.73913
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.826087

Model saved in ../results/models_modelling4/KNeighborsClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [10]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:50:13,580] A new study created in memory with name: smote_study
[I 2025-04-16 00:50:13,691] Trial 0 finished with value: 0.8165889152726052 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8165889152726052.
[I 2025-04-16 00:50:13,803] Trial 1 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:13,901] Trial 2 finished with value: 0.8312963436962847 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:13,997] Trial 3 finished with value: 0.8152523468202186 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,118] Trial 4 finished with value: 0.8055981156379303 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,217] Trial 5 finished with value: 0.80896325246309 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,315] Trial 6 finished with value: 0.8370682459726995 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,453] Trial 7 finished with value: 0.839086928547068 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,569] Trial 8 finished with value: 0.8213314920431475 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,678] Trial 9 finished with value: 0.8105692533950324 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,808] Trial 10 finished with value: 0.821014941280774 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,902] Trial 11 finished with value: 0.8321906018985509 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:14,998] Trial 12 finished with value: 0.8095886371577994 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,098] Trial 13 finished with value: 0.8305893052695945 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,195] Trial 14 finished with value: 0.792982370161283 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,286] Trial 15 finished with value: 0.8321906018985509 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,380] Trial 16 finished with value: 0.819381927524712 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,474] Trial 17 finished with value: 0.828828670975649 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,569] Trial 18 finished with value: 0.8244584829136904 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,661] Trial 19 finished with value: 0.8255998593092944 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,755] Trial 20 finished with value: 0.8291564971112734 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,848] Trial 21 finished with value: 0.8199570222682482 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.69}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:15,945] Trial 22 finished with value: 0.8217720561499853 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.65}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,044] Trial 23 finished with value: 0.8208195195141358 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.65}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,140] Trial 24 finished with value: 0.8282064704859192 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,237] Trial 25 finished with value: 0.8218811390860676 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.77}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,333] Trial 26 finished with value: 0.7932996870590429 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,430] Trial 27 finished with value: 0.8359028961035866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,528] Trial 28 finished with value: 0.8227846163999335 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,623] Trial 29 finished with value: 0.797342774804675 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,758] Trial 30 finished with value: 0.830653330057067 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,870] Trial 31 finished with value: 0.8218958951467535 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:16,969] Trial 32 finished with value: 0.8359028961035866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,066] Trial 33 finished with value: 0.8319818707621909 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,161] Trial 34 finished with value: 0.8255157325927588 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.63}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,262] Trial 35 finished with value: 0.8001071244397707 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,357] Trial 36 finished with value: 0.8297116590683503 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.74}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,449] Trial 37 finished with value: 0.8064264304712033 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.71}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,545] Trial 38 finished with value: 0.8217214250211551 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,639] Trial 39 finished with value: 0.8124823419288256 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,730] Trial 40 finished with value: 0.8144688967891671 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,825] Trial 41 finished with value: 0.8359028961035866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:17,922] Trial 42 finished with value: 0.8321683287424805 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,016] Trial 43 finished with value: 0.833552509533441 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,112] Trial 44 finished with value: 0.8218958951467535 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.63}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,207] Trial 45 finished with value: 0.8218046749383446 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.82}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,304] Trial 46 finished with value: 0.8332232492079399 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.7}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,400] Trial 47 finished with value: 0.8321683287424805 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,501] Trial 48 finished with value: 0.8125861972800716 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,597] Trial 49 finished with value: 0.8156436693584378 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6699999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,696] Trial 50 finished with value: 0.8024743567701667 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,788] Trial 51 finished with value: 0.8359028961035866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,886] Trial 52 finished with value: 0.8359028961035866 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.62}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:18,986] Trial 53 finished with value: 0.8284960123582996 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.64}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,079] Trial 54 finished with value: 0.8149308298711482 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.61}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,172] Trial 55 finished with value: 0.8259545027053132 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,270] Trial 56 finished with value: 0.8281255870331302 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,415] Trial 57 finished with value: 0.8206440729641564 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,511] Trial 58 finished with value: 0.815227499141305 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,607] Trial 59 finished with value: 0.8366976750335587 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,704] Trial 60 finished with value: 0.8305893052695945 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,802] Trial 61 finished with value: 0.8366976750335587 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,896] Trial 62 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:19,989] Trial 63 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,083] Trial 64 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,177] Trial 65 finished with value: 0.8127359373812068 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,273] Trial 66 finished with value: 0.8125861972800716 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,373] Trial 67 finished with value: 0.8130149225737325 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,468] Trial 68 finished with value: 0.7984806522848557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,563] Trial 69 finished with value: 0.8244584829136904 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,663] Trial 70 finished with value: 0.8139181220413668 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,760] Trial 71 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,856] Trial 72 finished with value: 0.8210427108267274 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:20,956] Trial 73 finished with value: 0.8118434780595915 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,053] Trial 74 finished with value: 0.8182531629764577 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,146] Trial 75 finished with value: 0.8125861972800716 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,238] Trial 76 finished with value: 0.8118434780595915 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,332] Trial 77 finished with value: 0.8130149225737325 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,430] Trial 78 finished with value: 0.8261739814703818 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,527] Trial 79 finished with value: 0.7984806522848557 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,622] Trial 80 finished with value: 0.8144316374637492 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,721] Trial 81 finished with value: 0.8366976750335587 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,816] Trial 82 finished with value: 0.8301581540905507 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:21,961] Trial 83 finished with value: 0.8305893052695945 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,055] Trial 84 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,156] Trial 85 finished with value: 0.8182531629764577 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,254] Trial 86 finished with value: 0.8168706988228678 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,356] Trial 87 finished with value: 0.8208119751893571 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,453] Trial 88 finished with value: 0.8227846163999335 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,550] Trial 89 finished with value: 0.8190639146978498 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,644] Trial 90 finished with value: 0.8118434780595915 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,744] Trial 91 finished with value: 0.8366976750335587 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,845] Trial 92 finished with value: 0.8305893052695945 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:22,944] Trial 93 finished with value: 0.8144405282557255 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,046] Trial 94 finished with value: 0.8473500834496152 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,144] Trial 95 finished with value: 0.8227846163999335 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,243] Trial 96 finished with value: 0.8130149225737325 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,344] Trial 97 finished with value: 0.8277385395733338 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,442] Trial 98 finished with value: 0.7978445147109585 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.82}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,542] Trial 99 finished with value: 0.8261739814703818 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,636] Trial 100 finished with value: 0.7915805715341212 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,736] Trial 101 finished with value: 0.8270458359652731 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,833] Trial 102 finished with value: 0.8191861157370496 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 1 with value: 0.8473500834496152.
[I 2025-04-16 00:50:23,929] Trial 103 finished with value: 0.8275363428662035 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 1 with value: 0.8473500834496152.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.84}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_smote_op...
holdout_test_f1_macro                                                      0.825397
holdout_test_accuracy_balanced                                             0.852273
holdout_test_roc_auc                                                       0.943636
holdout_test_f1                                                            0.755556
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.841642
cv_test_accuracy_balanced_median                                           0.897436
cv_test_roc_auc_median                                                     0.951282
cv_test_f1_median                                                          0.777778
cv_test_accuracy_median                                                     0.87037
cv_test_precision_class_0_median                                           0.972222
cv_test_recall_class_0_median                                              0.897436
cv_test_f1_class_0_median                                                  0.909091

Model saved in ../results/models_modelling4/KNeighborsClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# SVC

In [11]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:50:54,430] A new study created in memory with name: smote_study
[I 2025-04-16 00:50:54,549] Trial 0 finished with value: 0.8617852500049572 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8617852500049572.
[I 2025-04-16 00:50:54,660] Trial 1 finished with value: 0.8644198887587763 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8644198887587763.
[I 2025-04-16 00:50:54,764] Trial 2 finished with value: 0.8550552362111962 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8644198887587763.
[I 2025-04-16 00:50:54,885] Trial 3 finished with value: 0.8529924934958182 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8644198887587763.
[I 2025-04-16 00:50:55,004] Trial 4 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,122] Trial 5 finished with value: 0.8465006846510682 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,228] Trial 6 finished with value: 0.8558524435358728 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,343] Trial 7 finished with value: 0.8559283973688476 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,463] Trial 8 finished with value: 0.8677841086083079 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,580] Trial 9 finished with value: 0.8559280383431279 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,704] Trial 10 finished with value: 0.8614058857649185 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,829] Trial 11 finished with value: 0.8597373417847842 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:55,975] Trial 12 finished with value: 0.8604769600147752 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,098] Trial 13 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,220] Trial 14 finished with value: 0.8594769598696101 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,339] Trial 15 finished with value: 0.8609523809166487 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,456] Trial 16 finished with value: 0.8677841086083079 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,567] Trial 17 finished with value: 0.8588583311119512 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,681] Trial 18 finished with value: 0.8571050623046421 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,800] Trial 19 finished with value: 0.8605072973245242 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:56,913] Trial 20 finished with value: 0.86393149885375 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,028] Trial 21 finished with value: 0.8677841086083079 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,144] Trial 22 finished with value: 0.8677841086083079 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,261] Trial 23 finished with value: 0.8605072973245242 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,389] Trial 24 finished with value: 0.8602254010300051 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,504] Trial 25 finished with value: 0.8635901261151292 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,622] Trial 26 finished with value: 0.8601220208363066 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,735] Trial 27 finished with value: 0.8604946589811769 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,865] Trial 28 finished with value: 0.8536094411822929 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 4 with value: 0.8716691814330063.
[I 2025-04-16 00:50:57,985] Trial 29 finished with value: 0.8718158679396064 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,104] Trial 30 finished with value: 0.8606106775182226 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,267] Trial 31 finished with value: 0.8644329499630317 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,400] Trial 32 finished with value: 0.8635901261151292 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,531] Trial 33 finished with value: 0.8571050623046421 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,652] Trial 34 finished with value: 0.8491831900541619 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,779] Trial 35 finished with value: 0.8606106775182226 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:58,926] Trial 36 finished with value: 0.858441587365076 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,051] Trial 37 finished with value: 0.8488413944546329 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,183] Trial 38 finished with value: 0.8639748051666516 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,309] Trial 39 finished with value: 0.86785987799135 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,436] Trial 40 finished with value: 0.8536908548666478 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,559] Trial 41 finished with value: 0.86785987799135 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,697] Trial 42 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,852] Trial 43 finished with value: 0.8683180227877301 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:50:59,976] Trial 44 finished with value: 0.86785987799135 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,093] Trial 45 finished with value: 0.8573610652293645 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,209] Trial 46 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,328] Trial 47 finished with value: 0.8611065634286442 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,454] Trial 48 finished with value: 0.8571050623046421 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,578] Trial 49 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,704] Trial 50 finished with value: 0.8601220208363066 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,838] Trial 51 finished with value: 0.8611065634286442 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:00,956] Trial 52 finished with value: 0.8683180227877301 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,076] Trial 53 finished with value: 0.8532277595416479 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,203] Trial 54 finished with value: 0.8536094411822929 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,327] Trial 55 finished with value: 0.8523568224135235 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,453] Trial 56 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,574] Trial 57 finished with value: 0.8639313242779629 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,694] Trial 58 finished with value: 0.8554671670476551 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.63}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,821] Trial 59 finished with value: 0.8683180227877301 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:01,951] Trial 60 finished with value: 0.8677710474040525 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,075] Trial 61 finished with value: 0.8683180227877301 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,198] Trial 62 finished with value: 0.8616838761220708 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,318] Trial 63 finished with value: 0.8536094411822929 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,452] Trial 64 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,583] Trial 65 finished with value: 0.8677710474040525 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,744] Trial 66 finished with value: 0.8569302625178201 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,867] Trial 67 finished with value: 0.8683180227877301 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:02,988] Trial 68 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,114] Trial 69 finished with value: 0.8540550634310959 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,245] Trial 70 finished with value: 0.8574698209985551 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,372] Trial 71 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,491] Trial 72 finished with value: 0.8616838761220708 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,610] Trial 73 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,733] Trial 74 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,851] Trial 75 finished with value: 0.8502582825370165 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:03,971] Trial 76 finished with value: 0.8614058857649185 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,094] Trial 77 finished with value: 0.8532277595416479 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,219] Trial 78 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,341] Trial 79 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,461] Trial 80 finished with value: 0.8526072170076006 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,593] Trial 81 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,720] Trial 82 finished with value: 0.8683483600974791 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,846] Trial 83 finished with value: 0.8601220208363066 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:04,974] Trial 84 finished with value: 0.8679630836092614 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,100] Trial 85 finished with value: 0.8611065634286442 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,225] Trial 86 finished with value: 0.8645087193460738 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,352] Trial 87 finished with value: 0.86785987799135 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,477] Trial 88 finished with value: 0.8575632071010222 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,637] Trial 89 finished with value: 0.8611065634286442 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,767] Trial 90 finished with value: 0.8574698209985551 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:05,894] Trial 91 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,026] Trial 92 finished with value: 0.8574773170039502 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,156] Trial 93 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,291] Trial 94 finished with value: 0.8645087193460738 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,413] Trial 95 finished with value: 0.8575225712732234 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,532] Trial 96 finished with value: 0.861291103628458 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,655] Trial 97 finished with value: 0.8716691814330063 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,775] Trial 98 finished with value: 0.8601220208363066 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:06,898] Trial 99 finished with value: 0.8571050623046421 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:07,034] Trial 100 finished with value: 0.8682291922004326 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 29 with value: 0.8718158679396064.
[I 2025-04-16 00:51:07,163] Trial 101 finished with value: 0.8649972014522028 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 29 with value: 0.8718158679396064.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.86}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                                  0
target                                                                    splashing
model                             SVC_splashing_smote_optuna-opt-mean-smote_defa...
holdout_test_f1_macro                                                      0.810348
holdout_test_accuracy_balanced                                              0.80787
holdout_test_roc_auc                                                       0.881944
holdout_test_f1                                                            0.865979
holdout_test_accuracy                                                      0.826667
cv_test_f1_macro_median                                                    0.844575
cv_test_accuracy_balanced_median                                           0.870743
cv_test_roc_auc_median                                                     0.925697
cv_test_f1_median                                                          0.870968
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                               0.72
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.818182

Model saved in ../results/models_modelling4/SVC_splashing_smote_optuna-opt-mean-smote_default-model

In [12]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 00:51:45,809] A new study created in memory with name: smote_study
[I 2025-04-16 00:51:45,922] Trial 0 finished with value: 0.8317057142869242 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8317057142869242.
[I 2025-04-16 00:51:46,026] Trial 1 finished with value: 0.8346658965165396 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,136] Trial 2 finished with value: 0.8331099974208901 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,245] Trial 3 finished with value: 0.831839385795292 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,353] Trial 4 finished with value: 0.8150515241534569 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,463] Trial 5 finished with value: 0.8285213616709418 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,566] Trial 6 finished with value: 0.831759840195847 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 1 with value: 0.8346658965165396.
[I 2025-04-16 00:51:46,666] Trial 7 finished with value: 0.8364280215452402 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:46,772] Trial 8 finished with value: 0.827610981061248 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:46,873] Trial 9 finished with value: 0.8181769067442903 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:46,973] Trial 10 finished with value: 0.8213549966694066 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,079] Trial 11 finished with value: 0.827716743974167 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,222] Trial 12 finished with value: 0.8267167612764901 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,330] Trial 13 finished with value: 0.8333422879011856 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,438] Trial 14 finished with value: 0.8171532017663878 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,539] Trial 15 finished with value: 0.8288840166867963 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6}. Best is trial 7 with value: 0.8364280215452402.
[I 2025-04-16 00:51:47,652] Trial 16 finished with value: 0.8367903424780668 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 16 with value: 0.8367903424780668.
[I 2025-04-16 00:51:47,769] Trial 17 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 17 with value: 0.8371795688485116.
[I 2025-04-16 00:51:47,879] Trial 18 finished with value: 0.8320994196954609 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 17 with value: 0.8371795688485116.
[I 2025-04-16 00:51:47,993] Trial 19 finished with value: 0.833507252464331 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 17 with value: 0.8371795688485116.
[I 2025-04-16 00:51:48,105] Trial 20 finished with value: 0.8226600243784734 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 17 with value: 0.8371795688485116.
[I 2025-04-16 00:51:48,216] Trial 21 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,326] Trial 22 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,434] Trial 23 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,540] Trial 24 finished with value: 0.836698142857439 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,648] Trial 25 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,763] Trial 26 finished with value: 0.8088661549786899 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.73}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,878] Trial 27 finished with value: 0.8300874787955966 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:48,988] Trial 28 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,101] Trial 29 finished with value: 0.8319315854159198 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,261] Trial 30 finished with value: 0.8226600243784734 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,380] Trial 31 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,490] Trial 32 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,597] Trial 33 finished with value: 0.8300874787955966 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,709] Trial 34 finished with value: 0.8193831882202813 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,821] Trial 35 finished with value: 0.8338615447241615 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:49,926] Trial 36 finished with value: 0.8088661549786899 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.73}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,031] Trial 37 finished with value: 0.8272883090752001 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.63}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,140] Trial 38 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,247] Trial 39 finished with value: 0.825140344916634 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,361] Trial 40 finished with value: 0.8338615447241615 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,469] Trial 41 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,580] Trial 42 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,693] Trial 43 finished with value: 0.8226600243784734 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,807] Trial 44 finished with value: 0.8310968394651391 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:50,917] Trial 45 finished with value: 0.8367617965408639 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,029] Trial 46 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,141] Trial 47 finished with value: 0.8190320700245665 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,257] Trial 48 finished with value: 0.827610981061248 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,364] Trial 49 finished with value: 0.8358523371945059 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,466] Trial 50 finished with value: 0.8322985197047057 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,575] Trial 51 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,720] Trial 52 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,831] Trial 53 finished with value: 0.8327557051610596 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:51,946] Trial 54 finished with value: 0.8262380824029923 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,061] Trial 55 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,167] Trial 56 finished with value: 0.8246730207937569 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,274] Trial 57 finished with value: 0.8227522239991012 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,386] Trial 58 finished with value: 0.8260575059655488 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,494] Trial 59 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 21 with value: 0.8408912983813985.
[I 2025-04-16 00:51:52,599] Trial 60 finished with value: 0.8442887799684738 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:52,703] Trial 61 finished with value: 0.8442887799684738 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:52,806] Trial 62 finished with value: 0.831759840195847 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.69}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:52,913] Trial 63 finished with value: 0.8343516485707282 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,015] Trial 64 finished with value: 0.8300874787955966 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,125] Trial 65 finished with value: 0.8442887799684738 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,235] Trial 66 finished with value: 0.8322985197047057 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,337] Trial 67 finished with value: 0.8286702111583646 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,443] Trial 68 finished with value: 0.8331099974208901 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,553] Trial 69 finished with value: 0.829652585420902 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.73}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,667] Trial 70 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,775] Trial 71 finished with value: 0.8364280215452402 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,886] Trial 72 finished with value: 0.8364280215452402 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:53,999] Trial 73 finished with value: 0.8442887799684738 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,105] Trial 74 finished with value: 0.824167932106136 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.69}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,209] Trial 75 finished with value: 0.825140344916634 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,315] Trial 76 finished with value: 0.8364280215452402 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,458] Trial 77 finished with value: 0.8260575059655488 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,569] Trial 78 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,674] Trial 79 finished with value: 0.825140344916634 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,795] Trial 80 finished with value: 0.8364280215452402 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:54,914] Trial 81 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,025] Trial 82 finished with value: 0.8346658965165396 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,145] Trial 83 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,258] Trial 84 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,375] Trial 85 finished with value: 0.8262380824029923 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,495] Trial 86 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,603] Trial 87 finished with value: 0.829652585420902 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.73}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,718] Trial 88 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.78}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,843] Trial 89 finished with value: 0.8367903424780668 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:55,960] Trial 90 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,081] Trial 91 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,196] Trial 92 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,317] Trial 93 finished with value: 0.8371795688485116 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,431] Trial 94 finished with value: 0.8262380824029923 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,555] Trial 95 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,673] Trial 96 finished with value: 0.8408912983813985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.77}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,786] Trial 97 finished with value: 0.8300874787955966 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:56,900] Trial 98 finished with value: 0.8425436763706075 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6599999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:57,014] Trial 99 finished with value: 0.8322985197047057 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:57,159] Trial 100 finished with value: 0.8289010381176306 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:57,266] Trial 101 finished with value: 0.8290968844812091 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:57,391] Trial 102 finished with value: 0.8168450577839741 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 60 with value: 0.8442887799684738.
[I 2025-04-16 00:51:57,507] Trial 103 finished with value: 0.8193831882202813 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.79}. Best is trial 60 with value: 0.8442887799684738.

best_params

{'k_neighbors': 3, 'sampling_strategy': 0.6699999999999999}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                                                  0
target                                                             no_fragmentation
model                             SVC_no_fragmentation_smote_optuna-opt-mean-smo...
holdout_test_f1_macro                                                      0.857143
holdout_test_accuracy_balanced                                             0.886364
holdout_test_roc_auc                                                       0.950909
holdout_test_f1                                                                 0.8
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.881326
cv_test_accuracy_balanced_median                                            0.89011
cv_test_roc_auc_median                                                     0.948718
cv_test_f1_median                                                          0.827586
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.947368
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.931507

Model saved in ../results/models_modelling4/SVC_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# CatBoost

In [13]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 00:52:31,252] A new study created in memory with name: smote_study
[I 2025-04-16 00:52:36,543] Trial 0 finished with value: 0.8868392980653509 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8868392980653509.
[I 2025-04-16 00:52:41,545] Trial 1 finished with value: 0.8825840948565951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8868392980653509.
[I 2025-04-16 00:52:46,260] Trial 2 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:52:51,433] Trial 3 finished with value: 0.8834258532725957 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:52:56,476] Trial 4 finished with value: 0.8871726599131404 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:01,740] Trial 5 finished with value: 0.8793508634674306 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:06,606] Trial 6 finished with value: 0.8895129061020475 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:11,486] Trial 7 finished with value: 0.8894943751221386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:16,555] Trial 8 finished with value: 0.8904781861746756 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:21,276] Trial 9 finished with value: 0.8895499795010512 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:25,835] Trial 10 finished with value: 0.8856243152379276 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:30,761] Trial 11 finished with value: 0.8934783043179628 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:35,665] Trial 12 finished with value: 0.8895869985793664 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:40,368] Trial 13 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 2 with value: 0.8968166188226805.
[I 2025-04-16 00:53:45,364] Trial 14 finished with value: 0.9008199930147497 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:53:50,529] Trial 15 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:53:55,658] Trial 16 finished with value: 0.8819893951302606 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:00,932] Trial 17 finished with value: 0.8907103933034344 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:06,076] Trial 18 finished with value: 0.9005364628797189 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:11,192] Trial 19 finished with value: 0.8924301858666178 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:16,477] Trial 20 finished with value: 0.8863821885253785 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:21,600] Trial 21 finished with value: 0.8905016662818271 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:26,776] Trial 22 finished with value: 0.8895869985793664 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:31,971] Trial 23 finished with value: 0.8864748119826064 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:37,265] Trial 24 finished with value: 0.8871726599131404 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:42,202] Trial 25 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.64}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:47,331] Trial 26 finished with value: 0.8899915022640025 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.77}. Best is trial 14 with value: 0.9008199930147497.
[I 2025-04-16 00:54:52,514] Trial 27 finished with value: 0.9041778334285923 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:54:57,567] Trial 28 finished with value: 0.8894573017231349 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:02,362] Trial 29 finished with value: 0.8861735537866113 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:07,356] Trial 30 finished with value: 0.8889794407772936 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:12,467] Trial 31 finished with value: 0.9008199930147497 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:17,597] Trial 32 finished with value: 0.8828157133727688 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:22,660] Trial 33 finished with value: 0.8864748119826064 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:27,818] Trial 34 finished with value: 0.8825969529323334 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:32,881] Trial 35 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:38,073] Trial 36 finished with value: 0.8857952879651061 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.84}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:43,052] Trial 37 finished with value: 0.886136534708296 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:48,119] Trial 38 finished with value: 0.8967991256534901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:53,503] Trial 39 finished with value: 0.8974446594317167 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:55:58,602] Trial 40 finished with value: 0.8864748119826064 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:03,582] Trial 41 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:08,582] Trial 42 finished with value: 0.8967991256534901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:13,619] Trial 43 finished with value: 0.9041778334285923 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:18,731] Trial 44 finished with value: 0.8856962814533552 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:23,847] Trial 45 finished with value: 0.8862297467781091 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.73}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:28,885] Trial 46 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:33,847] Trial 47 finished with value: 0.8748821510384989 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.62}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:39,008] Trial 48 finished with value: 0.8934412852396475 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:44,051] Trial 49 finished with value: 0.878927136335455 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:49,143] Trial 50 finished with value: 0.8899211484599299 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:54,119] Trial 51 finished with value: 0.8967610144437679 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:56:59,092] Trial 52 finished with value: 0.8894943751221386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:04,173] Trial 53 finished with value: 0.8901399089003652 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:09,070] Trial 54 finished with value: 0.8823384410395126 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.61}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:14,061] Trial 55 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:19,126] Trial 56 finished with value: 0.8895499795010512 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.72}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:24,161] Trial 57 finished with value: 0.8825969529323334 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:29,221] Trial 58 finished with value: 0.8823384410395126 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:34,262] Trial 59 finished with value: 0.8901399089003652 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:39,171] Trial 60 finished with value: 0.8856243152379276 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:44,128] Trial 61 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:49,115] Trial 62 finished with value: 0.8924301858666178 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:54,077] Trial 63 finished with value: 0.8895499795010512 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:57:59,133] Trial 64 finished with value: 0.886136534708296 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:04,156] Trial 65 finished with value: 0.8894943751221386 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6699999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:09,171] Trial 66 finished with value: 0.886136534708296 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:14,163] Trial 67 finished with value: 0.8864748119826064 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:19,356] Trial 68 finished with value: 0.889511868291329 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:24,518] Trial 69 finished with value: 0.8825969529323334 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:29,589] Trial 70 finished with value: 0.8899211484599299 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:34,569] Trial 71 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:39,563] Trial 72 finished with value: 0.9007643886358371 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:44,525] Trial 73 finished with value: 0.8924301858666178 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:49,493] Trial 74 finished with value: 0.9039735150189855 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.64}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:54,750] Trial 75 finished with value: 0.8966161401652687 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:58:59,779] Trial 76 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:04,724] Trial 77 finished with value: 0.8962115188158833 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.61}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:09,762] Trial 78 finished with value: 0.890232532357593 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.71}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:14,765] Trial 79 finished with value: 0.8889794407772936 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:19,783] Trial 80 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:24,766] Trial 81 finished with value: 0.9035913493201421 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:29,743] Trial 82 finished with value: 0.8929642838049522 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6799999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:34,755] Trial 83 finished with value: 0.8931534737319762 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:39,768] Trial 84 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:44,792] Trial 85 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:49,847] Trial 86 finished with value: 0.890594289739055 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.71}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:54,874] Trial 87 finished with value: 0.893385680860735 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.73}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 00:59:59,947] Trial 88 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:04,924] Trial 89 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:09,922] Trial 90 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:14,915] Trial 91 finished with value: 0.8929253130840841 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6799999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:20,128] Trial 92 finished with value: 0.9039023597167111 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:25,142] Trial 93 finished with value: 0.8860574502222319 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:30,089] Trial 94 finished with value: 0.8967827638169753 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:35,137] Trial 95 finished with value: 0.8968166188226805 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:40,200] Trial 96 finished with value: 0.8895869985793664 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.72}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:45,155] Trial 97 finished with value: 0.9041778334285923 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:50,195] Trial 98 finished with value: 0.8857460663245688 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:00:55,499] Trial 99 finished with value: 0.8940045448994044 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:01:00,473] Trial 100 finished with value: 0.8967827638169753 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6699999999999999}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:01:05,546] Trial 101 finished with value: 0.8860574502222319 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 27 with value: 0.9041778334285923.
[I 2025-04-16 01:01:10,492] Trial 102 finished with value: 0.9041778334285923 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 27 with value: 0.9041778334285923.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.69}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             CatBoostClassifier_splashing_smote_optuna-opt-...
holdout_test_f1_macro                                                      0.863609
holdout_test_accuracy_balanced                                             0.849537
holdout_test_roc_auc                                                        0.95679
holdout_test_f1                                                            0.910891
holdout_test_accuracy                                                          0.88
cv_test_f1_macro_median                                                    0.881696
cv_test_accuracy_balanced_median                                           0.900155
cv_test_roc_auc_median                                                     0.952012
cv_test_f1_median                                                          0.914286
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.833333
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.857143

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [14]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 01:25:45,740] A new study created in memory with name: smote_study
[I 2025-04-16 01:25:51,317] Trial 0 finished with value: 0.8515510297419553 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8515510297419553.
[I 2025-04-16 01:25:56,836] Trial 1 finished with value: 0.8365369752968795 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8515510297419553.
[I 2025-04-16 01:26:02,020] Trial 2 finished with value: 0.853562425722252 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.853562425722252.
[I 2025-04-16 01:26:07,566] Trial 3 finished with value: 0.8496138363462047 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 2 with value: 0.853562425722252.
[I 2025-04-16 01:26:13,078] Trial 4 finished with value: 0.8504222020545641 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 2 with value: 0.853562425722252.
[I 2025-04-16 01:26:18,559] Trial 5 finished with value: 0.8518248977567555 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 2 with value: 0.853562425722252.
[I 2025-04-16 01:26:23,794] Trial 6 finished with value: 0.844718450867941 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 2 with value: 0.853562425722252.
[I 2025-04-16 01:26:29,022] Trial 7 finished with value: 0.8556256252385299 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:26:34,485] Trial 8 finished with value: 0.8540752981903791 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:26:39,819] Trial 9 finished with value: 0.8412438745967545 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:26:44,952] Trial 10 finished with value: 0.8425765213144315 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.6}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:26:50,261] Trial 11 finished with value: 0.8485338002146705 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:26:55,695] Trial 12 finished with value: 0.8500415285556988 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:27:01,177] Trial 13 finished with value: 0.831301689969514 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 7 with value: 0.8556256252385299.
[I 2025-04-16 01:27:06,460] Trial 14 finished with value: 0.8691296677582517 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:11,708] Trial 15 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:16,821] Trial 16 finished with value: 0.8523734148384534 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.62}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:22,177] Trial 17 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:27,346] Trial 18 finished with value: 0.8515429463595373 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.6599999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:32,719] Trial 19 finished with value: 0.8503580732749975 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:37,918] Trial 20 finished with value: 0.83000870425539 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:43,345] Trial 21 finished with value: 0.8555830265314074 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:48,842] Trial 22 finished with value: 0.853977173759031 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:54,269] Trial 23 finished with value: 0.8509470482929448 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.82}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:27:59,418] Trial 24 finished with value: 0.8425665593724838 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.63}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:04,877] Trial 25 finished with value: 0.8626944322846948 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:10,283] Trial 26 finished with value: 0.8626944322846948 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:15,757] Trial 27 finished with value: 0.8426139995856511 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:21,268] Trial 28 finished with value: 0.8369376199545311 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:26,837] Trial 29 finished with value: 0.8515522569311191 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:32,325] Trial 30 finished with value: 0.8456948092699184 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:37,842] Trial 31 finished with value: 0.847625292780504 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:43,167] Trial 32 finished with value: 0.8469150515034928 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:48,653] Trial 33 finished with value: 0.8441428776721135 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:53,996] Trial 34 finished with value: 0.841654131427749 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:28:59,312] Trial 35 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:04,743] Trial 36 finished with value: 0.8418328496147017 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:10,038] Trial 37 finished with value: 0.8536142292582333 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:15,492] Trial 38 finished with value: 0.8488016804981581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:21,039] Trial 39 finished with value: 0.8503238793008921 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:26,399] Trial 40 finished with value: 0.8429893145420415 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:31,573] Trial 41 finished with value: 0.853562425722252 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:36,882] Trial 42 finished with value: 0.8485338002146705 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:42,054] Trial 43 finished with value: 0.8556256252385299 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:47,468] Trial 44 finished with value: 0.8597661048268853 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.76}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:52,947] Trial 45 finished with value: 0.8370250613967753 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:29:58,251] Trial 46 finished with value: 0.841654131427749 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:03,776] Trial 47 finished with value: 0.8391394233144648 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:09,282] Trial 48 finished with value: 0.8436571226750288 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8099999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:14,683] Trial 49 finished with value: 0.8474217878035776 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:19,989] Trial 50 finished with value: 0.8581473561157072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:25,335] Trial 51 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:30,580] Trial 52 finished with value: 0.8581473561157072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:35,803] Trial 53 finished with value: 0.8417049435289005 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:40,934] Trial 54 finished with value: 0.8444199739710107 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.64}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:46,356] Trial 55 finished with value: 0.853977173759031 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:51,669] Trial 56 finished with value: 0.8581473561157072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:30:57,053] Trial 57 finished with value: 0.8536142292582333 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:02,288] Trial 58 finished with value: 0.83000870425539 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:07,758] Trial 59 finished with value: 0.8527316419128127 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:13,187] Trial 60 finished with value: 0.8500371673615249 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.77}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:18,481] Trial 61 finished with value: 0.8581473561157072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:23,778] Trial 62 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:29,060] Trial 63 finished with value: 0.8626303035051283 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:34,282] Trial 64 finished with value: 0.8567678996159472 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:39,554] Trial 65 finished with value: 0.8370250613967753 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:44,819] Trial 66 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:50,290] Trial 67 finished with value: 0.8473481022554618 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:31:55,400] Trial 68 finished with value: 0.8576929788866884 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.61}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:00,597] Trial 69 finished with value: 0.8492675099724527 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:05,855] Trial 70 finished with value: 0.853977173759031 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:11,116] Trial 71 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:16,373] Trial 72 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:21,626] Trial 73 finished with value: 0.8556256252385299 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:26,955] Trial 74 finished with value: 0.8485338002146705 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:32,331] Trial 75 finished with value: 0.844816575299289 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:37,880] Trial 76 finished with value: 0.8425665593724838 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:43,462] Trial 77 finished with value: 0.8520036159437082 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:48,580] Trial 78 finished with value: 0.8452815898145941 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:54,087] Trial 79 finished with value: 0.8421493943340005 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:32:59,540] Trial 80 finished with value: 0.8441428776721135 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:04,794] Trial 81 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:10,000] Trial 82 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:15,270] Trial 83 finished with value: 0.8536142292582333 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:20,560] Trial 84 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:25,837] Trial 85 finished with value: 0.847689587123169 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:31,126] Trial 86 finished with value: 0.853977173759031 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:36,307] Trial 87 finished with value: 0.8626303035051283 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:41,823] Trial 88 finished with value: 0.8552299902724905 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:46,983] Trial 89 finished with value: 0.8370250613967753 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:52,359] Trial 90 finished with value: 0.8473743475904102 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:33:57,585] Trial 91 finished with value: 0.8556256252385299 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:02,734] Trial 92 finished with value: 0.853562425722252 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:08,045] Trial 93 finished with value: 0.852525153557011 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:13,328] Trial 94 finished with value: 0.8503580732749975 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:18,666] Trial 95 finished with value: 0.8485338002146705 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:23,936] Trial 96 finished with value: 0.8507752383134809 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:29,153] Trial 97 finished with value: 0.8452815898145941 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.65}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:34,322] Trial 98 finished with value: 0.8500415285556988 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.63}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:39,592] Trial 99 finished with value: 0.8492675099724527 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:44,834] Trial 100 finished with value: 0.8581473561157072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:50,193] Trial 101 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.
[I 2025-04-16 01:34:55,411] Trial 102 finished with value: 0.8591557272339417 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 14 with value: 0.8691296677582517.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.74}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             CatBoostClassifier_no_fragmentation_smote_optu...
holdout_test_f1_macro                                                      0.918496
holdout_test_accuracy_balanced                                             0.938636
holdout_test_roc_auc                                                       0.984545
holdout_test_f1                                                            0.883721
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                     0.90293
cv_test_accuracy_balanced_median                                           0.887363
cv_test_roc_auc_median                                                      0.97265
cv_test_f1_median                                                          0.857143
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.948718
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                      0.95

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# XGBoost

In [15]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:01:17,771] A new study created in memory with name: smote_study
[I 2025-04-16 02:01:19,752] Trial 0 finished with value: 0.850973610215128 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.850973610215128.
[I 2025-04-16 02:01:21,313] Trial 1 finished with value: 0.8792709610761528 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8792709610761528.
[I 2025-04-16 02:01:22,859] Trial 2 finished with value: 0.8737949693941839 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8792709610761528.
[I 2025-04-16 02:01:24,436] Trial 3 finished with value: 0.888533166234959 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.888533166234959.
[I 2025-04-16 02:01:26,001] Trial 4 finished with value: 0.8864529148094934 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.888533166234959.
[I 2025-04-16 02:01:27,617] Trial 5 finished with value: 0.8785820538760121 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.888533166234959.
[I 2025-04-16 02:01:29,202] Trial 6 finished with value: 0.8713707067372672 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.888533166234959.
[I 2025-04-16 02:01:30,763] Trial 7 finished with value: 0.8926256108010918 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 7 with value: 0.8926256108010918.
[I 2025-04-16 02:01:32,360] Trial 8 finished with value: 0.8936421357540054 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 8 with value: 0.8936421357540054.
[I 2025-04-16 02:01:33,915] Trial 9 finished with value: 0.8861747639000886 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 8 with value: 0.8936421357540054.
[I 2025-04-16 02:01:35,542] Trial 10 finished with value: 0.8713452703623723 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.76}. Best is trial 8 with value: 0.8936421357540054.
[I 2025-04-16 02:01:37,157] Trial 11 finished with value: 0.870861399201588 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 8 with value: 0.8936421357540054.
[I 2025-04-16 02:01:38,707] Trial 12 finished with value: 0.8892506556516989 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 8 with value: 0.8936421357540054.
[I 2025-04-16 02:01:40,299] Trial 13 finished with value: 0.8990740133669431 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:41,891] Trial 14 finished with value: 0.8901298486563143 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:43,520] Trial 15 finished with value: 0.8862057860941013 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:45,115] Trial 16 finished with value: 0.8905765380473497 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.83}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:46,707] Trial 17 finished with value: 0.8740008756700605 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.74}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:48,267] Trial 18 finished with value: 0.8898010858367187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:49,863] Trial 19 finished with value: 0.8945563527969086 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:51,449] Trial 20 finished with value: 0.8615786654348592 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:52,997] Trial 21 finished with value: 0.8680666035833383 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:54,603] Trial 22 finished with value: 0.8827661058775101 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:56,181] Trial 23 finished with value: 0.8816791999367138 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.82}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:57,754] Trial 24 finished with value: 0.8642300854441934 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:01:59,388] Trial 25 finished with value: 0.8782348690628025 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:00,965] Trial 26 finished with value: 0.8797683282817779 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:02,511] Trial 27 finished with value: 0.8854806852608551 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:04,077] Trial 28 finished with value: 0.8863772949094113 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:05,676] Trial 29 finished with value: 0.8756366847149762 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:07,260] Trial 30 finished with value: 0.8898010858367187 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:08,803] Trial 31 finished with value: 0.8828802748147769 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.63}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:10,396] Trial 32 finished with value: 0.8896507537323066 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:12,022] Trial 33 finished with value: 0.8820452457899277 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:13,598] Trial 34 finished with value: 0.8657638593900007 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:15,216] Trial 35 finished with value: 0.8861067638097665 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:16,747] Trial 36 finished with value: 0.877278825544012 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:18,348] Trial 37 finished with value: 0.8820270688048258 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6699999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:20,148] Trial 38 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:21,713] Trial 39 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:23,344] Trial 40 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:24,952] Trial 41 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:26,593] Trial 42 finished with value: 0.8710454743729211 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:28,228] Trial 43 finished with value: 0.8822923737490344 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:29,814] Trial 44 finished with value: 0.8861855215520819 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:31,459] Trial 45 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:33,057] Trial 46 finished with value: 0.8904057204136763 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:34,636] Trial 47 finished with value: 0.8831567217623373 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:36,219] Trial 48 finished with value: 0.8788354978846618 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:37,832] Trial 49 finished with value: 0.8609163236233505 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:39,458] Trial 50 finished with value: 0.874485777802745 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:41,030] Trial 51 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:42,634] Trial 52 finished with value: 0.8822923737490344 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:44,231] Trial 53 finished with value: 0.8775244793610942 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.94}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:45,865] Trial 54 finished with value: 0.8812442361596686 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:47,444] Trial 55 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:49,055] Trial 56 finished with value: 0.8756366847149762 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:50,644] Trial 57 finished with value: 0.8822166102496255 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:52,267] Trial 58 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:53,878] Trial 59 finished with value: 0.886022438681818 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:55,411] Trial 60 finished with value: 0.8864529148094934 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:57,024] Trial 61 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:02:58,585] Trial 62 finished with value: 0.8665709061959578 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:00,220] Trial 63 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:01,881] Trial 64 finished with value: 0.8822923737490344 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:03,463] Trial 65 finished with value: 0.874485777802745 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:05,061] Trial 66 finished with value: 0.8673996567679592 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:06,668] Trial 67 finished with value: 0.8783004539758539 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:08,260] Trial 68 finished with value: 0.8788354978846618 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:09,853] Trial 69 finished with value: 0.883805276101349 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:11,459] Trial 70 finished with value: 0.882159424138103 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:13,092] Trial 71 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:14,703] Trial 72 finished with value: 0.8812442361596686 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:16,352] Trial 73 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:18,030] Trial 74 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:19,768] Trial 75 finished with value: 0.8890503560700399 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:21,239] Trial 76 finished with value: 0.8665709061959578 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:22,928] Trial 77 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:24,557] Trial 78 finished with value: 0.8783004539758539 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:26,208] Trial 79 finished with value: 0.8904057204136763 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:27,851] Trial 80 finished with value: 0.8822166102496255 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:29,462] Trial 81 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:31,086] Trial 82 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:32,667] Trial 83 finished with value: 0.8897193402057725 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:34,243] Trial 84 finished with value: 0.8665709061959578 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:35,942] Trial 85 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:37,562] Trial 86 finished with value: 0.8902022915893264 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:39,174] Trial 87 finished with value: 0.8812442361596686 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:40,775] Trial 88 finished with value: 0.8783525777455836 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:42,421] Trial 89 finished with value: 0.8792709610761528 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:44,106] Trial 90 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:45,705] Trial 91 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:47,342] Trial 92 finished with value: 0.8824488173783844 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.69}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:48,987] Trial 93 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:50,569] Trial 94 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:52,233] Trial 95 finished with value: 0.8783004539758539 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:53,891] Trial 96 finished with value: 0.8822923737490344 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.97}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:55,548] Trial 97 finished with value: 0.8740255732093811 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:57,118] Trial 98 finished with value: 0.8816868046149414 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:03:58,708] Trial 99 finished with value: 0.8756366847149762 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:04:00,330] Trial 100 finished with value: 0.874485777802745 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:04:01,925] Trial 101 finished with value: 0.8978508961792794 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:04:03,581] Trial 102 finished with value: 0.8820428172538163 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.99}. Best is trial 13 with value: 0.8990740133669431.
[I 2025-04-16 02:04:05,160] Trial 103 finished with value: 0.8812442361596686 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 13 with value: 0.8990740133669431.

best_params

{'k_neighbors': 7, 'sampling_strategy': 0.94}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                                    splashing
model                             XGBClassifier_splashing_smote_optuna-opt-mean-...
holdout_test_f1_macro                                                      0.836601
holdout_test_accuracy_balanced                                             0.828704
holdout_test_roc_auc                                                        0.94483
holdout_test_f1                                                            0.888889
holdout_test_accuracy                                                      0.853333
cv_test_f1_macro_median                                                    0.876935
cv_test_accuracy_balanced_median                                           0.876935
cv_test_roc_auc_median                                                      0.95356
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.842105
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.842105

Model saved in ../results/models_modelling4/XGBClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [16]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:12:12,987] A new study created in memory with name: smote_study
[I 2025-04-16 02:12:14,587] Trial 0 finished with value: 0.8239303192151926 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8239303192151926.
[I 2025-04-16 02:12:16,104] Trial 1 finished with value: 0.83412563873452 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.83412563873452.
[I 2025-04-16 02:12:17,659] Trial 2 finished with value: 0.8324181440883308 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.83412563873452.
[I 2025-04-16 02:12:19,246] Trial 3 finished with value: 0.8419022858785005 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:21,006] Trial 4 finished with value: 0.8374503834259999 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:22,571] Trial 5 finished with value: 0.8314850186777016 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:24,120] Trial 6 finished with value: 0.8287555302260295 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:25,655] Trial 7 finished with value: 0.8303696020720875 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:27,190] Trial 8 finished with value: 0.8336772278564071 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:28,746] Trial 9 finished with value: 0.8280845121600284 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:30,360] Trial 10 finished with value: 0.831901871851634 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:31,952] Trial 11 finished with value: 0.8374503834259999 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:33,448] Trial 12 finished with value: 0.8372278104302486 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:35,010] Trial 13 finished with value: 0.826565191429968 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:36,495] Trial 14 finished with value: 0.8228740520816257 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:38,045] Trial 15 finished with value: 0.8238482829154572 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.85}. Best is trial 3 with value: 0.8419022858785005.
[I 2025-04-16 02:12:39,585] Trial 16 finished with value: 0.8430101110248034 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:41,172] Trial 17 finished with value: 0.8324061917485934 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:42,699] Trial 18 finished with value: 0.8340623129366472 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:44,237] Trial 19 finished with value: 0.835839451766871 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:45,802] Trial 20 finished with value: 0.8369585260789059 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:47,366] Trial 21 finished with value: 0.8335347103233604 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:48,924] Trial 22 finished with value: 0.8201526754344589 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:50,453] Trial 23 finished with value: 0.8350520948789635 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:52,062] Trial 24 finished with value: 0.835839451766871 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:53,598] Trial 25 finished with value: 0.8372278104302486 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:55,166] Trial 26 finished with value: 0.8351718124914961 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:56,730] Trial 27 finished with value: 0.8209499765975988 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:58,297] Trial 28 finished with value: 0.8250343716844367 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8999999999999999}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:12:59,885] Trial 29 finished with value: 0.8428171340367305 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 16 with value: 0.8430101110248034.
[I 2025-04-16 02:13:01,419] Trial 30 finished with value: 0.8453278226425779 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:02,987] Trial 31 finished with value: 0.8320275881566094 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:04,603] Trial 32 finished with value: 0.8303099500860233 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:06,223] Trial 33 finished with value: 0.8329315031652077 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:07,710] Trial 34 finished with value: 0.8320275881566094 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.97}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:09,285] Trial 35 finished with value: 0.8329315031652077 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:10,830] Trial 36 finished with value: 0.809618367505606 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.86}. Best is trial 30 with value: 0.8453278226425779.
[I 2025-04-16 02:13:12,367] Trial 37 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:13,987] Trial 38 finished with value: 0.830112260738061 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:15,554] Trial 39 finished with value: 0.8239303192151926 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:17,110] Trial 40 finished with value: 0.8392322584373039 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:18,634] Trial 41 finished with value: 0.8419022858785005 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:20,375] Trial 42 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:21,871] Trial 43 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:23,435] Trial 44 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:25,046] Trial 45 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:26,629] Trial 46 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:28,141] Trial 47 finished with value: 0.8414280995502194 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.99}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:29,724] Trial 48 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:31,266] Trial 49 finished with value: 0.8392322584373039 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:32,836] Trial 50 finished with value: 0.8441731054663636 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:34,393] Trial 51 finished with value: 0.8467773245621915 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:35,961] Trial 52 finished with value: 0.830112260738061 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:37,537] Trial 53 finished with value: 0.8239303192151926 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:39,103] Trial 54 finished with value: 0.8218274409370432 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.61}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:40,636] Trial 55 finished with value: 0.8385996704299539 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 37 with value: 0.8467773245621915.
[I 2025-04-16 02:13:42,212] Trial 56 finished with value: 0.8488838552213152 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:43,753] Trial 57 finished with value: 0.8255500314700569 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:45,254] Trial 58 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:46,782] Trial 59 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:48,398] Trial 60 finished with value: 0.8132606063331794 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:49,865] Trial 61 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:51,319] Trial 62 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:52,253] Trial 63 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:53,187] Trial 64 finished with value: 0.8237690750607772 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:54,335] Trial 65 finished with value: 0.8403856621369251 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:55,328] Trial 66 finished with value: 0.8266409539974251 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:56,249] Trial 67 finished with value: 0.8428171340367305 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:57,298] Trial 68 finished with value: 0.8160901877377483 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:58,395] Trial 69 finished with value: 0.818691399959387 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:13:59,333] Trial 70 finished with value: 0.8403856621369251 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:00,403] Trial 71 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:01,426] Trial 72 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:02,706] Trial 73 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:04,378] Trial 74 finished with value: 0.818691399959387 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:05,855] Trial 75 finished with value: 0.8359443681415603 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:07,486] Trial 76 finished with value: 0.8346823651785252 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:08,972] Trial 77 finished with value: 0.8428171340367305 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:10,372] Trial 78 finished with value: 0.8237690750607772 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:11,301] Trial 79 finished with value: 0.8403856621369251 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:12,260] Trial 80 finished with value: 0.818691399959387 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:13,423] Trial 81 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:14,425] Trial 82 finished with value: 0.8428171340367305 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:15,362] Trial 83 finished with value: 0.8413468651172707 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:16,474] Trial 84 finished with value: 0.8346823651785252 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:17,582] Trial 85 finished with value: 0.8352471266012207 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:18,500] Trial 86 finished with value: 0.8315834816319295 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:19,542] Trial 87 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:20,946] Trial 88 finished with value: 0.8413468651172707 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:21,880] Trial 89 finished with value: 0.8312467974104835 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:22,886] Trial 90 finished with value: 0.8119676206190551 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:24,038] Trial 91 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:25,026] Trial 92 finished with value: 0.8406535698989445 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.99}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:26,016] Trial 93 finished with value: 0.8428171340367305 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:27,171] Trial 94 finished with value: 0.8346823651785252 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:28,187] Trial 95 finished with value: 0.8413468651172707 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:29,113] Trial 96 finished with value: 0.8437528078797973 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:30,196] Trial 97 finished with value: 0.8312467974104835 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:31,301] Trial 98 finished with value: 0.8413468651172707 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:32,243] Trial 99 finished with value: 0.8329315031652077 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:33,227] Trial 100 finished with value: 0.8205557191067151 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:34,378] Trial 101 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.
[I 2025-04-16 02:14:35,330] Trial 102 finished with value: 0.8481943419597296 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.95}. Best is trial 56 with value: 0.8488838552213152.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.95}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             XGBClassifier_no_fragmentation_smote_optuna-op...
holdout_test_f1_macro                                                      0.918496
holdout_test_accuracy_balanced                                             0.938636
holdout_test_roc_auc                                                       0.990909
holdout_test_f1                                                            0.883721
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.962393
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                           0.926829
cv_test_recall_class_0_median                                              0.974359
cv_test_f1_class_0_median                                                  0.936709

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# AdaBoost

In [17]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:19:47,200] A new study created in memory with name: smote_study
[I 2025-04-16 02:19:47,473] Trial 0 finished with value: 0.8640537066058273 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:47,735] Trial 1 finished with value: 0.8437932211095193 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:47,994] Trial 2 finished with value: 0.8271081497714823 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:48,260] Trial 3 finished with value: 0.8276516517605865 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:48,529] Trial 4 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:48,797] Trial 5 finished with value: 0.8329266872646072 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:49,059] Trial 6 finished with value: 0.8154675929591597 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:49,330] Trial 7 finished with value: 0.8400402608271419 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:49,596] Trial 8 finished with value: 0.8489025185784875 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:49,856] Trial 9 finished with value: 0.837595163640627 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:50,125] Trial 10 finished with value: 0.8530600607103297 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:50,392] Trial 11 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:50,662] Trial 12 finished with value: 0.8267479169816837 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:50,925] Trial 13 finished with value: 0.8602580340608323 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:51,191] Trial 14 finished with value: 0.8509611300826094 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:51,457] Trial 15 finished with value: 0.8540137137728568 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:51,729] Trial 16 finished with value: 0.8528620037089035 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:51,995] Trial 17 finished with value: 0.853520825471848 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:52,263] Trial 18 finished with value: 0.8319776267763884 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:52,530] Trial 19 finished with value: 0.8595648229195166 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:52,796] Trial 20 finished with value: 0.8384491191429857 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:53,071] Trial 21 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:53,341] Trial 22 finished with value: 0.8514703866138996 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:53,608] Trial 23 finished with value: 0.8257068606315904 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:53,877] Trial 24 finished with value: 0.8567687059997048 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:54,145] Trial 25 finished with value: 0.8391818399830357 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:54,421] Trial 26 finished with value: 0.8374096063503098 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.97}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:54,694] Trial 27 finished with value: 0.8521639723937974 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.85}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:54,962] Trial 28 finished with value: 0.8352867590580969 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:55,226] Trial 29 finished with value: 0.8595648229195166 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:55,492] Trial 30 finished with value: 0.8317248750542594 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.83}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:55,766] Trial 31 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:56,034] Trial 32 finished with value: 0.8597541978877861 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:56,297] Trial 33 finished with value: 0.8557466833620581 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.77}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:56,567] Trial 34 finished with value: 0.8267479169816837 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:56,832] Trial 35 finished with value: 0.8213823084600433 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:57,102] Trial 36 finished with value: 0.8189587629086222 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:57,372] Trial 37 finished with value: 0.8412314034877723 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:57,648] Trial 38 finished with value: 0.827559027044411 and parameters: {'k_neighbors': 9, 'sampling_strategy': 1.0}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:57,920] Trial 39 finished with value: 0.8216262174592329 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:58,188] Trial 40 finished with value: 0.8259905106887796 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:58,456] Trial 41 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:58,723] Trial 42 finished with value: 0.8351080586542824 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:58,994] Trial 43 finished with value: 0.8438912030268735 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:59,266] Trial 44 finished with value: 0.8421707671572012 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:59,538] Trial 45 finished with value: 0.843967392534776 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:19:59,808] Trial 46 finished with value: 0.8567687059997048 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.94}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:00,076] Trial 47 finished with value: 0.8391818399830357 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:00,341] Trial 48 finished with value: 0.8144861831146508 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.64}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:00,619] Trial 49 finished with value: 0.8225860299874104 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:00,889] Trial 50 finished with value: 0.8413239744997184 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:01,158] Trial 51 finished with value: 0.8610354276494145 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:01,432] Trial 52 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:01,700] Trial 53 finished with value: 0.853520825471848 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:01,971] Trial 54 finished with value: 0.8438912030268735 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:02,250] Trial 55 finished with value: 0.82510670939837 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:02,520] Trial 56 finished with value: 0.8614819668765689 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:02,784] Trial 57 finished with value: 0.8474320377233221 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:03,059] Trial 58 finished with value: 0.8328300414394822 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:03,330] Trial 59 finished with value: 0.849874179776954 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:03,605] Trial 60 finished with value: 0.8365243375202321 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:03,873] Trial 61 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:04,142] Trial 62 finished with value: 0.8562048000213984 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:04,407] Trial 63 finished with value: 0.8421815039738512 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:04,676] Trial 64 finished with value: 0.8351080586542824 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:04,943] Trial 65 finished with value: 0.8259905106887796 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:05,221] Trial 66 finished with value: 0.8460990382076548 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:05,486] Trial 67 finished with value: 0.8388402521125595 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:05,748] Trial 68 finished with value: 0.8447046888271935 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:06,019] Trial 69 finished with value: 0.843967392534776 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:06,294] Trial 70 finished with value: 0.8247139589085822 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:06,577] Trial 71 finished with value: 0.8616016835043357 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:06,848] Trial 72 finished with value: 0.8610354276494145 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:07,120] Trial 73 finished with value: 0.8347199478101571 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:07,388] Trial 74 finished with value: 0.8597541978877861 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 0 with value: 0.8640537066058273.
[I 2025-04-16 02:20:07,663] Trial 75 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:07,932] Trial 76 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:08,202] Trial 77 finished with value: 0.8351366839417871 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.96}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:08,473] Trial 78 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:08,749] Trial 79 finished with value: 0.8650319697152021 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:09,021] Trial 80 finished with value: 0.8530600607103297 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:09,296] Trial 81 finished with value: 0.8474270846102121 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.94}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:09,567] Trial 82 finished with value: 0.8650319697152021 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:09,835] Trial 83 finished with value: 0.8283750092279204 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:10,103] Trial 84 finished with value: 0.8502484769441505 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.95}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:10,371] Trial 85 finished with value: 0.8215024170784844 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.99}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:10,641] Trial 86 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:10,911] Trial 87 finished with value: 0.8291900920184848 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9299999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:11,185] Trial 88 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:11,453] Trial 89 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:11,729] Trial 90 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:12,002] Trial 91 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:12,270] Trial 92 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:12,537] Trial 93 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:12,808] Trial 94 finished with value: 0.8562048000213984 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:13,081] Trial 95 finished with value: 0.8154744336880887 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:13,366] Trial 96 finished with value: 0.8507401681247444 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:13,639] Trial 97 finished with value: 0.8460472724309295 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:13,906] Trial 98 finished with value: 0.8154744336880887 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:14,174] Trial 99 finished with value: 0.8664449720026951 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:14,445] Trial 100 finished with value: 0.849507587493236 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.95}. Best is trial 75 with value: 0.8664449720026951.
[I 2025-04-16 02:20:14,715] Trial 101 finished with value: 0.8562048000213984 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9299999999999999}. Best is trial 75 with value: 0.8664449720026951.

best_params

{'k_neighbors': 8, 'sampling_strategy': 0.9099999999999999}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                                    splashing
model                             AdaBoostClassifier_splashing_smote_optuna-opt-...
holdout_test_f1_macro                                                      0.755981
holdout_test_accuracy_balanced                                             0.758102
holdout_test_roc_auc                                                       0.846065
holdout_test_f1                                                            0.821053
holdout_test_accuracy                                                      0.773333
cv_test_f1_macro_median                                                    0.805718
cv_test_accuracy_balanced_median                                           0.829721
cv_test_roc_auc_median                                                     0.885449
cv_test_f1_median                                                          0.848485
cv_test_accuracy_median                                                    0.811321
cv_test_precision_class_0_median                                           0.714286
cv_test_recall_class_0_median                                              0.789474
cv_test_f1_class_0_median                                                  0.772727

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [18]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:21:36,822] A new study created in memory with name: smote_study
[I 2025-04-16 02:21:37,090] Trial 0 finished with value: 0.8411554125130493 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:37,349] Trial 1 finished with value: 0.8137546557969431 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:37,606] Trial 2 finished with value: 0.8252131718939804 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:37,872] Trial 3 finished with value: 0.8330161401074437 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:38,136] Trial 4 finished with value: 0.7949676755822634 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:38,411] Trial 5 finished with value: 0.8262507173333548 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:38,666] Trial 6 finished with value: 0.8251247841591557 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:38,930] Trial 7 finished with value: 0.8135102207175978 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:39,186] Trial 8 finished with value: 0.8236373214501373 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:39,444] Trial 9 finished with value: 0.8270027391422768 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:39,708] Trial 10 finished with value: 0.8056002464499044 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:39,973] Trial 11 finished with value: 0.8262507173333548 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:40,236] Trial 12 finished with value: 0.8087046796600788 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:40,500] Trial 13 finished with value: 0.8213268740387883 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:40,756] Trial 14 finished with value: 0.8003369874442325 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:41,022] Trial 15 finished with value: 0.8052410078142983 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:41,287] Trial 16 finished with value: 0.8026145529325578 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:41,552] Trial 17 finished with value: 0.808524625713276 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:41,815] Trial 18 finished with value: 0.805307615173852 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:42,076] Trial 19 finished with value: 0.8188191705114625 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:42,339] Trial 20 finished with value: 0.8193717934667241 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:42,598] Trial 21 finished with value: 0.8265899614977955 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.72}. Best is trial 0 with value: 0.8411554125130493.
[I 2025-04-16 02:21:42,858] Trial 22 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:43,127] Trial 23 finished with value: 0.800474484848624 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:43,399] Trial 24 finished with value: 0.8235819258832981 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.94}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:43,666] Trial 25 finished with value: 0.8036397745793449 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:43,933] Trial 26 finished with value: 0.8024194316568504 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:44,194] Trial 27 finished with value: 0.8154324259880681 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:44,457] Trial 28 finished with value: 0.8026145529325578 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:44,729] Trial 29 finished with value: 0.8066912022267502 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:44,996] Trial 30 finished with value: 0.8138526451048799 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:45,256] Trial 31 finished with value: 0.8270027391422768 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:45,512] Trial 32 finished with value: 0.8208594745255818 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:45,771] Trial 33 finished with value: 0.824153927303288 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:46,029] Trial 34 finished with value: 0.8192081891423929 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:46,294] Trial 35 finished with value: 0.8267888220770426 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.7}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:46,574] Trial 36 finished with value: 0.8279314997739015 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:46,840] Trial 37 finished with value: 0.795744713918109 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:47,098] Trial 38 finished with value: 0.8151627063176704 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:47,360] Trial 39 finished with value: 0.8316658555158458 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:47,633] Trial 40 finished with value: 0.812465740784617 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:47,895] Trial 41 finished with value: 0.8316658555158458 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:48,158] Trial 42 finished with value: 0.8316658555158458 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:48,419] Trial 43 finished with value: 0.8153845327380759 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:48,685] Trial 44 finished with value: 0.8114154868309141 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.82}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:48,948] Trial 45 finished with value: 0.807109408440048 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9099999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:49,212] Trial 46 finished with value: 0.8193117540377423 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:49,477] Trial 47 finished with value: 0.8252590205179009 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:49,742] Trial 48 finished with value: 0.8316658555158458 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:50,007] Trial 49 finished with value: 0.8411554125130493 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:50,284] Trial 50 finished with value: 0.8218551033300344 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:50,551] Trial 51 finished with value: 0.8077285981956897 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:50,818] Trial 52 finished with value: 0.8249211247479232 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.98}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:51,088] Trial 53 finished with value: 0.808524625713276 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:51,352] Trial 54 finished with value: 0.8024194316568504 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8999999999999999}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:51,615] Trial 55 finished with value: 0.8112739886542498 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.94}. Best is trial 22 with value: 0.8427012144316208.
[I 2025-04-16 02:21:51,877] Trial 56 finished with value: 0.8495506166942935 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:52,140] Trial 57 finished with value: 0.8174806211614195 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:52,413] Trial 58 finished with value: 0.8136060294496961 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:52,676] Trial 59 finished with value: 0.810084877165371 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.86}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:52,943] Trial 60 finished with value: 0.8126216314250142 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:53,220] Trial 61 finished with value: 0.8495506166942935 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:53,482] Trial 62 finished with value: 0.8098354837301992 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:53,744] Trial 63 finished with value: 0.8495506166942935 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:54,016] Trial 64 finished with value: 0.8188191705114625 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:54,279] Trial 65 finished with value: 0.7973271337297707 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.84}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:54,543] Trial 66 finished with value: 0.8187096893326972 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.99}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:54,806] Trial 67 finished with value: 0.8417321983985655 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:55,082] Trial 68 finished with value: 0.828068794434354 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:55,345] Trial 69 finished with value: 0.8028908902035609 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:55,604] Trial 70 finished with value: 0.8365809849438214 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:55,870] Trial 71 finished with value: 0.8365809849438214 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:56,125] Trial 72 finished with value: 0.8002152032562314 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.69}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:56,385] Trial 73 finished with value: 0.8101690964618985 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:56,643] Trial 74 finished with value: 0.8215381969801289 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.73}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:56,906] Trial 75 finished with value: 0.828068794434354 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:57,172] Trial 76 finished with value: 0.7930134761553307 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:57,443] Trial 77 finished with value: 0.800474484848624 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:57,700] Trial 78 finished with value: 0.808637254941404 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6699999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:57,963] Trial 79 finished with value: 0.8026145529325578 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.86}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:58,224] Trial 80 finished with value: 0.8153206900718393 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:58,482] Trial 81 finished with value: 0.8365809849438214 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:58,745] Trial 82 finished with value: 0.8213268740387883 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:59,005] Trial 83 finished with value: 0.8174806211614195 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:59,276] Trial 84 finished with value: 0.8270027391422768 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:59,539] Trial 85 finished with value: 0.805047190726869 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:21:59,803] Trial 86 finished with value: 0.8153845327380759 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:00,074] Trial 87 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:00,338] Trial 88 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:00,604] Trial 89 finished with value: 0.8136060294496961 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:00,867] Trial 90 finished with value: 0.8107587605701004 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:01,130] Trial 91 finished with value: 0.8184641546711057 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.79}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:01,398] Trial 92 finished with value: 0.7994533501193403 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:01,663] Trial 93 finished with value: 0.8114283264596273 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:01,930] Trial 94 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:02,206] Trial 95 finished with value: 0.8161144747828141 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.82}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:02,469] Trial 96 finished with value: 0.8066912022267502 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:02,730] Trial 97 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:02,995] Trial 98 finished with value: 0.8146507223533396 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:03,263] Trial 99 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:03,526] Trial 100 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:03,798] Trial 101 finished with value: 0.8168511488726997 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 56 with value: 0.8495506166942935.
[I 2025-04-16 02:22:04,061] Trial 102 finished with value: 0.8427012144316208 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8099999999999999}. Best is trial 56 with value: 0.8495506166942935.

best_params

{'k_neighbors': 4, 'sampling_strategy': 0.84}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_smote_optu...
holdout_test_f1_macro                                                      0.780518
holdout_test_accuracy_balanced                                             0.809091
holdout_test_roc_auc                                                       0.930455
holdout_test_f1                                                            0.695652
holdout_test_accuracy                                                      0.813333
cv_test_f1_macro_median                                                    0.815385
cv_test_accuracy_balanced_median                                           0.828755
cv_test_roc_auc_median                                                     0.912088
cv_test_f1_median                                                          0.733333
cv_test_accuracy_median                                                    0.849057
cv_test_precision_class_0_median                                           0.918919
cv_test_recall_class_0_median                                              0.871795
cv_test_f1_class_0_median                                                  0.894737

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# Random Forest

In [19]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:23:24,061] A new study created in memory with name: smote_study
[I 2025-04-16 02:23:24,541] Trial 0 finished with value: 0.8620945466055197 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8620945466055197.
[I 2025-04-16 02:23:25,007] Trial 1 finished with value: 0.8629914840212102 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8629914840212102.
[I 2025-04-16 02:23:25,459] Trial 2 finished with value: 0.8686836798098685 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 2 with value: 0.8686836798098685.
[I 2025-04-16 02:23:25,923] Trial 3 finished with value: 0.8811047094343298 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:26,389] Trial 4 finished with value: 0.8729282104847041 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:26,856] Trial 5 finished with value: 0.8666458286927755 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:27,308] Trial 6 finished with value: 0.8692580163160485 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:27,761] Trial 7 finished with value: 0.8694782339267251 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:28,226] Trial 8 finished with value: 0.8725340915482217 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:28,681] Trial 9 finished with value: 0.8603007187414902 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:29,148] Trial 10 finished with value: 0.8751579925091544 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:29,617] Trial 11 finished with value: 0.8751579925091544 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9099999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:30,087] Trial 12 finished with value: 0.8562375816520306 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.9199999999999999}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:30,544] Trial 13 finished with value: 0.8655079150743735 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:31,001] Trial 14 finished with value: 0.8721954177885811 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:31,466] Trial 15 finished with value: 0.8712886335815883 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:31,933] Trial 16 finished with value: 0.8606532000049285 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:32,396] Trial 17 finished with value: 0.8781868597462001 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.78}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:32,856] Trial 18 finished with value: 0.86765981496732 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:33,322] Trial 19 finished with value: 0.8716666234532129 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:33,785] Trial 20 finished with value: 0.8780221932400228 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:34,245] Trial 21 finished with value: 0.8735091005450928 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:34,719] Trial 22 finished with value: 0.8765142470191731 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:35,179] Trial 23 finished with value: 0.8615507750868975 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.78}. Best is trial 3 with value: 0.8811047094343298.
[I 2025-04-16 02:23:35,641] Trial 24 finished with value: 0.8819210072923996 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 24 with value: 0.8819210072923996.
[I 2025-04-16 02:23:36,096] Trial 25 finished with value: 0.8777389675694499 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.71}. Best is trial 24 with value: 0.8819210072923996.
[I 2025-04-16 02:23:36,561] Trial 26 finished with value: 0.8821999623681821 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:37,020] Trial 27 finished with value: 0.8729501062742504 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.63}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:37,488] Trial 28 finished with value: 0.8606532000049285 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.95}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:37,959] Trial 29 finished with value: 0.8638539712558758 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:38,430] Trial 30 finished with value: 0.8711584753752052 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.96}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:38,899] Trial 31 finished with value: 0.8681953068957599 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8099999999999999}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:39,364] Trial 32 finished with value: 0.8754626149409039 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:39,827] Trial 33 finished with value: 0.8735445839760212 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:40,291] Trial 34 finished with value: 0.8737199628792836 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:40,757] Trial 35 finished with value: 0.8698634918239275 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:41,223] Trial 36 finished with value: 0.8568081624065282 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:41,681] Trial 37 finished with value: 0.8729220442670872 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:42,147] Trial 38 finished with value: 0.8705185014117784 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:42,607] Trial 39 finished with value: 0.8801820481999835 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8099999999999999}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:43,070] Trial 40 finished with value: 0.8698190070366216 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.82}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:43,532] Trial 41 finished with value: 0.8641714878515044 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.77}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:43,997] Trial 42 finished with value: 0.8690216586975328 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:44,460] Trial 43 finished with value: 0.8603090773465396 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.73}. Best is trial 26 with value: 0.8821999623681821.
[I 2025-04-16 02:23:44,926] Trial 44 finished with value: 0.8872471445338961 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.8899999999999999}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:45,391] Trial 45 finished with value: 0.8782200273554512 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:45,872] Trial 46 finished with value: 0.867787811734562 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:46,345] Trial 47 finished with value: 0.8816758325973081 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:46,821] Trial 48 finished with value: 0.8787722087334519 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:47,294] Trial 49 finished with value: 0.8787722087334519 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:47,766] Trial 50 finished with value: 0.8585484173525663 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:48,244] Trial 51 finished with value: 0.8738253905210546 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:48,712] Trial 52 finished with value: 0.8673157172424275 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.96}. Best is trial 44 with value: 0.8872471445338961.
[I 2025-04-16 02:23:49,183] Trial 53 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:49,656] Trial 54 finished with value: 0.8643883129525914 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:50,133] Trial 55 finished with value: 0.8766138672558684 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:50,610] Trial 56 finished with value: 0.8607165208180741 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.97}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:51,084] Trial 57 finished with value: 0.8738389860853053 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.86}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:51,556] Trial 58 finished with value: 0.8534422812994438 and parameters: {'k_neighbors': 8, 'sampling_strategy': 1.0}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:52,034] Trial 59 finished with value: 0.875220246467841 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.94}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:52,499] Trial 60 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:52,965] Trial 61 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:53,433] Trial 62 finished with value: 0.8858703932586026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:53,903] Trial 63 finished with value: 0.8858703932586026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:54,369] Trial 64 finished with value: 0.8858703932586026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:54,841] Trial 65 finished with value: 0.8858703932586026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:55,306] Trial 66 finished with value: 0.873155553391534 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:55,774] Trial 67 finished with value: 0.8740705747628683 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:56,252] Trial 68 finished with value: 0.8651931490948405 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:56,720] Trial 69 finished with value: 0.8658749236767107 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:57,190] Trial 70 finished with value: 0.8737363247157984 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:57,662] Trial 71 finished with value: 0.8858703932586026 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:58,131] Trial 72 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:58,598] Trial 73 finished with value: 0.8666496698773459 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9099999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:59,063] Trial 74 finished with value: 0.8652891218379483 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.86}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:59,525] Trial 75 finished with value: 0.8622103873990891 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:23:59,993] Trial 76 finished with value: 0.8809812696684599 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:00,458] Trial 77 finished with value: 0.8710965663931242 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:00,924] Trial 78 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:01,395] Trial 79 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:01,868] Trial 80 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:02,338] Trial 81 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:02,802] Trial 82 finished with value: 0.8736987982652568 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:03,271] Trial 83 finished with value: 0.8809812696684599 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:03,739] Trial 84 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:04,216] Trial 85 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:04,682] Trial 86 finished with value: 0.8737105924312697 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.85}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:05,155] Trial 87 finished with value: 0.8667231549809976 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:05,624] Trial 88 finished with value: 0.8651931490948405 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:06,086] Trial 89 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:06,549] Trial 90 finished with value: 0.8710965663931242 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:07,012] Trial 91 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:07,479] Trial 92 finished with value: 0.8666496698773459 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9099999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:07,948] Trial 93 finished with value: 0.8809812696684599 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9299999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:08,413] Trial 94 finished with value: 0.8658749236767107 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:08,908] Trial 95 finished with value: 0.8811047094343298 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:09,372] Trial 96 finished with value: 0.8736987982652568 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:09,838] Trial 97 finished with value: 0.8652891218379483 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.86}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:10,302] Trial 98 finished with value: 0.8651931490948405 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.9199999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:10,770] Trial 99 finished with value: 0.8737199628792836 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:11,239] Trial 100 finished with value: 0.8919612353209029 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}. Best is trial 53 with value: 0.8919612353209029.
[I 2025-04-16 02:24:11,706] Trial 101 finished with value: 0.8658749236767107 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 53 with value: 0.8919612353209029.

best_params

{'k_neighbors': 3, 'sampling_strategy': 0.8999999999999999}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                                    splashing
model                             RandomForestClassifier_splashing_smote_optuna-...
holdout_test_f1_macro                                                          0.82
holdout_test_accuracy_balanced                                             0.810185
holdout_test_roc_auc                                                       0.953318
holdout_test_f1                                                                0.88
holdout_test_accuracy                                                          0.84
cv_test_f1_macro_median                                                     0.87381
cv_test_accuracy_balanced_median                                            0.87381
cv_test_roc_auc_median                                                     0.946032
cv_test_f1_median                                                          0.911765
cv_test_accuracy_median                                                    0.886792
cv_test_precision_class_0_median                                           0.833333
cv_test_recall_class_0_median                                              0.842105
cv_test_f1_class_0_median                                                  0.833333

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [20]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:26:44,964] A new study created in memory with name: smote_study
[I 2025-04-16 02:26:45,540] Trial 0 finished with value: 0.8404884202789548 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8404884202789548.
[I 2025-04-16 02:26:46,040] Trial 1 finished with value: 0.8279257550100352 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8404884202789548.
[I 2025-04-16 02:26:46,517] Trial 2 finished with value: 0.8396656388231067 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8404884202789548.
[I 2025-04-16 02:26:47,048] Trial 3 finished with value: 0.8353574430162406 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8404884202789548.
[I 2025-04-16 02:26:47,577] Trial 4 finished with value: 0.8432365084612183 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8432365084612183.
[I 2025-04-16 02:26:48,076] Trial 5 finished with value: 0.8201872112760251 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 4 with value: 0.8432365084612183.
[I 2025-04-16 02:26:48,588] Trial 6 finished with value: 0.8230193821193174 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 4 with value: 0.8432365084612183.
[I 2025-04-16 02:26:49,069] Trial 7 finished with value: 0.8251833824633312 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 4 with value: 0.8432365084612183.
[I 2025-04-16 02:26:49,582] Trial 8 finished with value: 0.8343324506764483 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8432365084612183.
[I 2025-04-16 02:26:50,062] Trial 9 finished with value: 0.8448925978544136 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 9 with value: 0.8448925978544136.
[I 2025-04-16 02:26:50,551] Trial 10 finished with value: 0.8297394159749386 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.74}. Best is trial 9 with value: 0.8448925978544136.
[I 2025-04-16 02:26:51,066] Trial 11 finished with value: 0.8340883170529213 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 9 with value: 0.8448925978544136.
[I 2025-04-16 02:26:51,605] Trial 12 finished with value: 0.8457723346014703 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:52,107] Trial 13 finished with value: 0.8062006024358022 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:52,595] Trial 14 finished with value: 0.8347737517217766 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.75}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:53,097] Trial 15 finished with value: 0.8358306334198807 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:53,584] Trial 16 finished with value: 0.8382006177655253 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:54,063] Trial 17 finished with value: 0.8180915574394719 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.7}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:54,569] Trial 18 finished with value: 0.8159577042239375 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.61}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:55,083] Trial 19 finished with value: 0.8299556889119434 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:55,570] Trial 20 finished with value: 0.8366069758031246 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:56,103] Trial 21 finished with value: 0.8432365084612183 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:56,632] Trial 22 finished with value: 0.8334826708234707 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:57,170] Trial 23 finished with value: 0.8432368288809268 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:57,690] Trial 24 finished with value: 0.8432368288809268 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.84}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:58,175] Trial 25 finished with value: 0.8346310792402901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 12 with value: 0.8457723346014703.
[I 2025-04-16 02:26:58,669] Trial 26 finished with value: 0.8510548215740007 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:26:59,192] Trial 27 finished with value: 0.8408325918998264 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:26:59,737] Trial 28 finished with value: 0.8446794541258745 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:27:00,234] Trial 29 finished with value: 0.8265485430608062 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8099999999999999}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:27:00,725] Trial 30 finished with value: 0.828804306246447 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:27:01,249] Trial 31 finished with value: 0.8474653341311075 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 26 with value: 0.8510548215740007.
[I 2025-04-16 02:27:01,737] Trial 32 finished with value: 0.8515127783288607 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 32 with value: 0.8515127783288607.
[I 2025-04-16 02:27:02,220] Trial 33 finished with value: 0.8408325918998264 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 32 with value: 0.8515127783288607.
[I 2025-04-16 02:27:02,711] Trial 34 finished with value: 0.8139815147550664 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.73}. Best is trial 32 with value: 0.8515127783288607.
[I 2025-04-16 02:27:03,190] Trial 35 finished with value: 0.8532212384383501 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:03,672] Trial 36 finished with value: 0.8408325918998264 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.64}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:04,182] Trial 37 finished with value: 0.8302035553558547 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6799999999999999}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:04,684] Trial 38 finished with value: 0.8327722639833609 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:05,166] Trial 39 finished with value: 0.8170884204641072 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.65}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:05,678] Trial 40 finished with value: 0.8198783459198088 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.69}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:06,178] Trial 41 finished with value: 0.8387360375188345 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 35 with value: 0.8532212384383501.
[I 2025-04-16 02:27:06,758] Trial 42 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:07,255] Trial 43 finished with value: 0.824579772839127 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6699999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:07,743] Trial 44 finished with value: 0.8525238930408724 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:08,302] Trial 45 finished with value: 0.8346310792402901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:08,824] Trial 46 finished with value: 0.8293910952454636 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.71}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:09,388] Trial 47 finished with value: 0.8421404506812242 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:09,874] Trial 48 finished with value: 0.8391973393806492 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.73}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:10,391] Trial 49 finished with value: 0.8265485430608062 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8099999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:10,890] Trial 50 finished with value: 0.8330303458715876 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:11,415] Trial 51 finished with value: 0.8396656388231067 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:11,941] Trial 52 finished with value: 0.8525238930408724 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.72}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:12,461] Trial 53 finished with value: 0.828838421301388 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:12,981] Trial 54 finished with value: 0.8192119595275066 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.62}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:13,476] Trial 55 finished with value: 0.8383720213688327 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.79}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:13,962] Trial 56 finished with value: 0.8329234445430796 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.74}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:14,451] Trial 57 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:14,999] Trial 58 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:15,488] Trial 59 finished with value: 0.8348999816536146 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:16,033] Trial 60 finished with value: 0.8228572146089641 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:16,518] Trial 61 finished with value: 0.8424551235016019 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:17,005] Trial 62 finished with value: 0.8391973393806492 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.73}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:17,518] Trial 63 finished with value: 0.8220962768186604 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:18,012] Trial 64 finished with value: 0.8424551235016019 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.71}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:18,555] Trial 65 finished with value: 0.8243335803585689 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:19,060] Trial 66 finished with value: 0.839300863257886 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6699999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:19,561] Trial 67 finished with value: 0.8216447264690842 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:20,053] Trial 68 finished with value: 0.8317935630916214 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.72}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:20,607] Trial 69 finished with value: 0.828804306246447 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.77}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:21,187] Trial 70 finished with value: 0.8251627103830307 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.7}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:21,693] Trial 71 finished with value: 0.8381746030441521 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:22,216] Trial 72 finished with value: 0.8510548215740007 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:22,706] Trial 73 finished with value: 0.8421404506812242 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.76}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:23,198] Trial 74 finished with value: 0.8187059884710831 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.74}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:23,693] Trial 75 finished with value: 0.8263452120925466 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:24,177] Trial 76 finished with value: 0.8532212384383501 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:24,691] Trial 77 finished with value: 0.8532212384383501 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6799999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:25,180] Trial 78 finished with value: 0.8405897573787927 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6799999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:25,662] Trial 79 finished with value: 0.8333472796695917 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.6599999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:26,154] Trial 80 finished with value: 0.8496039896856773 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.62}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:26,704] Trial 81 finished with value: 0.8474653341311075 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.69}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:27,191] Trial 82 finished with value: 0.8446794541258745 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.7}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:27,676] Trial 83 finished with value: 0.828838421301388 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.72}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:28,202] Trial 84 finished with value: 0.8145156806630991 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.6799999999999999}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:28,757] Trial 85 finished with value: 0.8421385724188993 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.73}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:29,250] Trial 86 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:29,736] Trial 87 finished with value: 0.8346310792402901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:30,227] Trial 88 finished with value: 0.8358306334198807 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.74}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:30,710] Trial 89 finished with value: 0.8350169212441385 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.65}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:31,230] Trial 90 finished with value: 0.8432828875757795 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.77}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:31,721] Trial 91 finished with value: 0.8515127783288607 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.71}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:32,209] Trial 92 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:32,696] Trial 93 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:33,188] Trial 94 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:33,679] Trial 95 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:34,168] Trial 96 finished with value: 0.8228572146089641 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.76}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:34,682] Trial 97 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:35,177] Trial 98 finished with value: 0.8410622053732014 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:35,691] Trial 99 finished with value: 0.8348999816536146 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:36,183] Trial 100 finished with value: 0.8410622053732014 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:36,672] Trial 101 finished with value: 0.8342808079487577 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.74}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:37,165] Trial 102 finished with value: 0.8346310792402901 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.78}. Best is trial 42 with value: 0.8578387879122337.
[I 2025-04-16 02:27:37,678] Trial 103 finished with value: 0.8578387879122337 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 42 with value: 0.8578387879122337.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.75}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             RandomForestClassifier_no_fragmentation_smote_...
holdout_test_f1_macro                                                      0.903516
holdout_test_accuracy_balanced                                             0.929545
holdout_test_roc_auc                                                       0.980455
holdout_test_f1                                                            0.863636
holdout_test_accuracy                                                          0.92
cv_test_f1_macro_median                                                    0.875762
cv_test_accuracy_balanced_median                                           0.867216
cv_test_roc_auc_median                                                     0.954701
cv_test_f1_median                                                          0.814815
cv_test_accuracy_median                                                     0.90566
cv_test_precision_class_0_median                                              0.925
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.935065

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model

# LightGBM

In [21]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-16 02:30:10,764] A new study created in memory with name: smote_study
[I 2025-04-16 02:30:13,450] Trial 0 finished with value: 0.8937668325736822 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8937668325736822.
[I 2025-04-16 02:30:16,022] Trial 1 finished with value: 0.8758155858900383 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 0 with value: 0.8937668325736822.
[I 2025-04-16 02:30:18,422] Trial 2 finished with value: 0.8701472818088798 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 0 with value: 0.8937668325736822.
[I 2025-04-16 02:30:21,123] Trial 3 finished with value: 0.8760492580553016 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 0 with value: 0.8937668325736822.
[I 2025-04-16 02:30:23,652] Trial 4 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:26,315] Trial 5 finished with value: 0.8782982365156922 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:28,649] Trial 6 finished with value: 0.8671685073331553 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:30,983] Trial 7 finished with value: 0.8776832913249887 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:33,443] Trial 8 finished with value: 0.8800078313885907 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:35,829] Trial 9 finished with value: 0.8718468699062548 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:38,448] Trial 10 finished with value: 0.8715548053019145 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:41,019] Trial 11 finished with value: 0.8791562024760076 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:43,751] Trial 12 finished with value: 0.8823190925069914 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.97}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:46,160] Trial 13 finished with value: 0.8873539873820396 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:48,444] Trial 14 finished with value: 0.8673790814566678 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.6}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:51,253] Trial 15 finished with value: 0.8757789371951059 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:53,936] Trial 16 finished with value: 0.8720402855367827 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:56,351] Trial 17 finished with value: 0.8634709062857279 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:30:59,111] Trial 18 finished with value: 0.8724876356990305 and parameters: {'k_neighbors': 6, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:01,636] Trial 19 finished with value: 0.8680725204552461 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.79}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:04,309] Trial 20 finished with value: 0.8614519791340276 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9199999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:06,817] Trial 21 finished with value: 0.8873539873820396 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:09,254] Trial 22 finished with value: 0.8782613217770884 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.76}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:11,703] Trial 23 finished with value: 0.8709671984643075 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:14,157] Trial 24 finished with value: 0.8605289977819864 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:16,632] Trial 25 finished with value: 0.8741039393272364 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.75}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:19,399] Trial 26 finished with value: 0.8691448417028143 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:21,961] Trial 27 finished with value: 0.853166273877662 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.72}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:24,553] Trial 28 finished with value: 0.8652454742600534 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:26,937] Trial 29 finished with value: 0.8677252719295829 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:29,501] Trial 30 finished with value: 0.8713735039969895 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.87}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:31,965] Trial 31 finished with value: 0.8761546434718017 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.76}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:34,489] Trial 32 finished with value: 0.8546383018760658 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.78}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:36,777] Trial 33 finished with value: 0.8662055771406723 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.72}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:39,210] Trial 34 finished with value: 0.847384787106263 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:41,981] Trial 35 finished with value: 0.8937668325736822 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:44,761] Trial 36 finished with value: 0.882253867441951 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:47,513] Trial 37 finished with value: 0.8868343614413386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:50,203] Trial 38 finished with value: 0.8673310126770978 and parameters: {'k_neighbors': 5, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:52,668] Trial 39 finished with value: 0.8597720549480614 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9299999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:55,403] Trial 40 finished with value: 0.8790333475453308 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.96}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:31:57,751] Trial 41 finished with value: 0.8662219494304103 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.64}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:00,046] Trial 42 finished with value: 0.867343169166671 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:02,337] Trial 43 finished with value: 0.8706161590698865 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.69}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:04,932] Trial 44 finished with value: 0.8541363383014537 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:07,356] Trial 45 finished with value: 0.8747977989953665 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.78}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:09,723] Trial 46 finished with value: 0.8636704314755589 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.7}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:12,477] Trial 47 finished with value: 0.8789057943177649 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.98}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:14,771] Trial 48 finished with value: 0.8639628316132265 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.6599999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:17,137] Trial 49 finished with value: 0.856745967502928 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.73}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:19,640] Trial 50 finished with value: 0.8792991805123682 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.84}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:22,420] Trial 51 finished with value: 0.884037143560621 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.95}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:25,111] Trial 52 finished with value: 0.8868343614413386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:27,919] Trial 53 finished with value: 0.882253867441951 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.98}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:30,692] Trial 54 finished with value: 0.8686340530371245 and parameters: {'k_neighbors': 4, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:33,318] Trial 55 finished with value: 0.8868343614413386 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:35,906] Trial 56 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:38,599] Trial 57 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:41,183] Trial 58 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:43,775] Trial 59 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:46,342] Trial 60 finished with value: 0.863900026940364 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.88}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:48,939] Trial 61 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:51,548] Trial 62 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:54,114] Trial 63 finished with value: 0.8769426192683938 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:56,702] Trial 64 finished with value: 0.8764633371535532 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:32:59,297] Trial 65 finished with value: 0.8791562024760076 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:01,938] Trial 66 finished with value: 0.8769426192683938 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:04,576] Trial 67 finished with value: 0.8832748307103567 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:07,305] Trial 68 finished with value: 0.8763416236349251 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:09,920] Trial 69 finished with value: 0.8541363383014537 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8999999999999999}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:12,451] Trial 70 finished with value: 0.8712929265295909 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 4 with value: 0.8945019436033209.
[I 2025-04-16 02:33:15,024] Trial 71 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:17,621] Trial 72 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:20,213] Trial 73 finished with value: 0.8715789699772788 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.87}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:23,035] Trial 74 finished with value: 0.8763416236349251 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9199999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:25,518] Trial 75 finished with value: 0.8712929265295909 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:27,977] Trial 76 finished with value: 0.8779005258824437 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:30,366] Trial 77 finished with value: 0.8646612599822958 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:32,746] Trial 78 finished with value: 0.8736311833513855 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:35,377] Trial 79 finished with value: 0.8714978960246916 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:38,039] Trial 80 finished with value: 0.869121932726685 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9199999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:40,661] Trial 81 finished with value: 0.8945019436033209 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:43,205] Trial 82 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:45,802] Trial 83 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:48,399] Trial 84 finished with value: 0.8832748307103567 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.87}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:50,931] Trial 85 finished with value: 0.8514700546162625 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:53,605] Trial 86 finished with value: 0.8652454742600534 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9099999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:56,044] Trial 87 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:33:58,583] Trial 88 finished with value: 0.8601672404005247 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.87}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:00,868] Trial 89 finished with value: 0.8677252719295829 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:03,338] Trial 90 finished with value: 0.8634709062857279 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:05,833] Trial 91 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:08,406] Trial 92 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:11,030] Trial 93 finished with value: 0.8764633371535532 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:13,596] Trial 94 finished with value: 0.8779005258824437 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:16,108] Trial 95 finished with value: 0.8736311833513855 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:18,753] Trial 96 finished with value: 0.8732899324829201 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:21,355] Trial 97 finished with value: 0.9040520321353471 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:23,769] Trial 98 finished with value: 0.8514700546162625 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:26,438] Trial 99 finished with value: 0.8757789371951059 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:29,161] Trial 100 finished with value: 0.8791562024760076 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:31,794] Trial 101 finished with value: 0.8764633371535532 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 71 with value: 0.9040520321353471.
[I 2025-04-16 02:34:34,382] Trial 102 finished with value: 0.8736311833513855 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8999999999999999}. Best is trial 71 with value: 0.9040520321353471.

best_params

{'k_neighbors': 7, 'sampling_strategy': 0.88}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                                    splashing
model                             LGBMClassifier_splashing_smote_optuna-opt-mean...
holdout_test_f1_macro                                                      0.852826
holdout_test_accuracy_balanced                                             0.847222
holdout_test_roc_auc                                                       0.949846
holdout_test_f1                                                            0.897959
holdout_test_accuracy                                                      0.866667
cv_test_f1_macro_median                                                    0.858018
cv_test_accuracy_balanced_median                                           0.862229
cv_test_roc_auc_median                                                     0.953968
cv_test_f1_median                                                          0.895522
cv_test_accuracy_median                                                    0.867925
cv_test_precision_class_0_median                                           0.809524
cv_test_recall_class_0_median                                              0.894737
cv_test_f1_class_0_median                                                  0.820513

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_smote_optuna-opt-mean-smote_default-model

In [22]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

optimize_smote_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-16 02:47:17,015] A new study created in memory with name: smote_study
[I 2025-04-16 02:47:20,060] Trial 0 finished with value: 0.8422797523462326 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.98}. Best is trial 0 with value: 0.8422797523462326.
[I 2025-04-16 02:47:22,973] Trial 1 finished with value: 0.8599197691887189 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 1 with value: 0.8599197691887189.
[I 2025-04-16 02:47:25,655] Trial 2 finished with value: 0.8342135201627616 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6599999999999999}. Best is trial 1 with value: 0.8599197691887189.
[I 2025-04-16 02:47:28,826] Trial 3 finished with value: 0.8531695449663894 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.95}. Best is trial 1 with value: 0.8599197691887189.
[I 2025-04-16 02:47:31,815] Trial 4 finished with value: 0.8639931824265202 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:35,010] Trial 5 finished with value: 0.837451674738425 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.99}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:37,598] Trial 6 finished with value: 0.8298239206911948 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.6799999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:40,282] Trial 7 finished with value: 0.8435402325568704 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.6699999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:43,229] Trial 8 finished with value: 0.848922129871199 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.8099999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:45,793] Trial 9 finished with value: 0.828771096707234 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.71}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:48,793] Trial 10 finished with value: 0.8450298142281596 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:51,591] Trial 11 finished with value: 0.8599197691887189 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.84}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:54,570] Trial 12 finished with value: 0.8639931824265202 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8899999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:47:57,604] Trial 13 finished with value: 0.8487432099068278 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:00,280] Trial 14 finished with value: 0.848610062586433 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.75}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:03,279] Trial 15 finished with value: 0.8271539046411662 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:06,135] Trial 16 finished with value: 0.8247368617188228 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:09,052] Trial 17 finished with value: 0.8349043497347576 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.85}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:12,035] Trial 18 finished with value: 0.8402413822939901 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9299999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:14,808] Trial 19 finished with value: 0.8237824327372645 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.86}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:17,346] Trial 20 finished with value: 0.8224436862902903 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.61}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:20,287] Trial 21 finished with value: 0.847365165236709 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:23,280] Trial 22 finished with value: 0.8284820224033467 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.87}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:26,233] Trial 23 finished with value: 0.8349467222108303 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:29,385] Trial 24 finished with value: 0.8445607633515 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.96}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:32,178] Trial 25 finished with value: 0.8247368617188228 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.77}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:35,255] Trial 26 finished with value: 0.8360748532740947 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9299999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:38,259] Trial 27 finished with value: 0.8390920276252726 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.88}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:41,152] Trial 28 finished with value: 0.8337496576526462 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.84}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:44,264] Trial 29 finished with value: 0.8533604230853413 and parameters: {'k_neighbors': 7, 'sampling_strategy': 1.0}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:47,438] Trial 30 finished with value: 0.8332510567492141 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.96}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:50,282] Trial 31 finished with value: 0.8438794365303884 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.83}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:53,347] Trial 32 finished with value: 0.8487432099068278 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.9099999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:56,147] Trial 33 finished with value: 0.8258356975468103 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.79}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:48:59,093] Trial 34 finished with value: 0.8436421481947561 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:49:02,150] Trial 35 finished with value: 0.8349529497336652 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.9299999999999999}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:49:04,649] Trial 36 finished with value: 0.8357795798134516 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.74}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:49:07,451] Trial 37 finished with value: 0.8413082779019913 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 4 with value: 0.8639931824265202.
[I 2025-04-16 02:49:10,376] Trial 38 finished with value: 0.872095662295685 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:13,255] Trial 39 finished with value: 0.872095662295685 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:16,446] Trial 40 finished with value: 0.8295018672375759 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.97}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:19,484] Trial 41 finished with value: 0.8322547110878238 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:22,555] Trial 42 finished with value: 0.8237660326832981 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:25,659] Trial 43 finished with value: 0.8446663847588356 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9199999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:28,369] Trial 44 finished with value: 0.872095662295685 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:31,397] Trial 45 finished with value: 0.8483134950463026 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8899999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:34,495] Trial 46 finished with value: 0.8224729609486816 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.94}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:37,404] Trial 47 finished with value: 0.8326685695235125 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:40,578] Trial 48 finished with value: 0.8230636316108547 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.98}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:43,484] Trial 49 finished with value: 0.8317318325974931 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.9099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:46,552] Trial 50 finished with value: 0.8299987616475136 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8899999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:49,460] Trial 51 finished with value: 0.8512549285332097 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.86}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:52,180] Trial 52 finished with value: 0.8386052373334019 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:54,949] Trial 53 finished with value: 0.8535888059073543 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.83}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:49:58,003] Trial 54 finished with value: 0.8455262102468877 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:00,795] Trial 55 finished with value: 0.8425633247583085 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.85}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:03,846] Trial 56 finished with value: 0.8271539046411662 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.8999999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:06,819] Trial 57 finished with value: 0.8427210852643435 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.95}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:09,658] Trial 58 finished with value: 0.8571955784567085 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:12,333] Trial 59 finished with value: 0.8263577324595763 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.64}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:15,136] Trial 60 finished with value: 0.8476411204901174 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.79}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:18,147] Trial 61 finished with value: 0.8319815862702397 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.85}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:21,058] Trial 62 finished with value: 0.8349467222108303 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.82}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:23,922] Trial 63 finished with value: 0.8441129139881028 and parameters: {'k_neighbors': 10, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:27,033] Trial 64 finished with value: 0.8322547110878238 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.9199999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:30,064] Trial 65 finished with value: 0.846551363141619 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:33,046] Trial 66 finished with value: 0.8429622615479817 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.86}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:35,857] Trial 67 finished with value: 0.8239577740062219 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.82}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:38,768] Trial 68 finished with value: 0.8371969882063459 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.8899999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:41,599] Trial 69 finished with value: 0.8545038069634673 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:44,674] Trial 70 finished with value: 0.8541926185249576 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:47,524] Trial 71 finished with value: 0.8571955784567085 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:50,410] Trial 72 finished with value: 0.8515091525161983 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:53,356] Trial 73 finished with value: 0.8371403302036757 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.85}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:56,290] Trial 74 finished with value: 0.8323727789787025 and parameters: {'k_neighbors': 9, 'sampling_strategy': 0.83}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:50:59,283] Trial 75 finished with value: 0.8237660326832981 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:02,092] Trial 76 finished with value: 0.8455262102468877 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:05,115] Trial 77 finished with value: 0.8434763957616523 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.9199999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:07,891] Trial 78 finished with value: 0.8228851418816117 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.85}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:10,795] Trial 79 finished with value: 0.8326685695235125 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:13,728] Trial 80 finished with value: 0.8436421481947561 and parameters: {'k_neighbors': 8, 'sampling_strategy': 0.86}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:16,550] Trial 81 finished with value: 0.8571955784567085 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:19,496] Trial 82 finished with value: 0.8315286865293773 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:22,501] Trial 83 finished with value: 0.8465523436599529 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.94}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:25,365] Trial 84 finished with value: 0.8413082779019913 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:28,330] Trial 85 finished with value: 0.8237660326832981 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8999999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:31,226] Trial 86 finished with value: 0.8326685695235125 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:34,139] Trial 87 finished with value: 0.8315286865293773 and parameters: {'k_neighbors': 3, 'sampling_strategy': 0.8899999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:37,066] Trial 88 finished with value: 0.8347915920957268 and parameters: {'k_neighbors': 6, 'sampling_strategy': 0.86}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:39,991] Trial 89 finished with value: 0.8541926185249576 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.9099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:42,510] Trial 90 finished with value: 0.8548690627349017 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.8099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:45,377] Trial 91 finished with value: 0.8519973830834958 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.88}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:48,258] Trial 92 finished with value: 0.8571955784567085 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.87}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:51,131] Trial 93 finished with value: 0.863392440644087 and parameters: {'k_neighbors': 4, 'sampling_strategy': 0.83}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:54,085] Trial 94 finished with value: 0.8312227733693108 and parameters: {'k_neighbors': 5, 'sampling_strategy': 0.83}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:56,935] Trial 95 finished with value: 0.8573554393672408 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:51:59,679] Trial 96 finished with value: 0.847087373870191 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.78}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:02,575] Trial 97 finished with value: 0.8573554393672408 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:05,556] Trial 98 finished with value: 0.8455693404917416 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.82}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:08,356] Trial 99 finished with value: 0.8573554393672408 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:11,177] Trial 100 finished with value: 0.8445205848127448 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.8099999999999999}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:14,108] Trial 101 finished with value: 0.8573554393672408 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.84}. Best is trial 38 with value: 0.872095662295685.
[I 2025-04-16 02:52:17,104] Trial 102 finished with value: 0.8295074616765793 and parameters: {'k_neighbors': 7, 'sampling_strategy': 0.85}. Best is trial 38 with value: 0.872095662295685.

best_params

{'k_neighbors': 5, 'sampling_strategy': 0.88}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                                  0
target                                                             no_fragmentation
model                             LGBMClassifier_no_fragmentation_smote_optuna-o...
holdout_test_f1_macro                                                      0.913375
holdout_test_accuracy_balanced                                             0.906818
holdout_test_roc_auc                                                       0.989091
holdout_test_f1                                                            0.871795
holdout_test_accuracy                                                      0.933333
cv_test_f1_macro_median                                                    0.898077
cv_test_accuracy_balanced_median                                           0.880037
cv_test_roc_auc_median                                                      0.97094
cv_test_f1_median                                                          0.846154
cv_test_accuracy_median                                                    0.924528
cv_test_precision_class_0_median                                           0.945946
cv_test_recall_class_0_median                                              0.948718
cv_test_f1_class_0_median                                                  0.947368

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_smote_optuna-opt-mean-smote_default-model